tenzir/tenzir

scripts/dscat.py
test/dscat/dscat.cc

- Complete replication of funcionality and interface of dscat.cc in python.
- Tested server and client functionality between dscat.py instances and with vast and file/stdout transfers.
- Also included is small fix in dscat.cc info text output.

Add dscat python script

---

scripts/splunk-search.py

- Setup and usage instructions included in help.
- Help output and error messages available in both cmdline and Splunk.
- Uses InterSplunk format to support sending multivalue fields to Splunk.
- Splunk results as events (|vast) or stats (|vaststats).
- Does not use Splunk InterSplunk lib to avoid mv related bug.
- Option to use line-by-line stream mode (-s)
(for single source results with single header - Multivalues are not split in this mode).
Stream mode discards all headers and respective values diferent than the first one received.
- Non stream mode (default) supports mutiple sources and multivalues.
- Option to output _raw field (-r) (some Splunk commands process the _raw field).
- Option to override the timestamp field. (-t)
- Option to select query node (-n)
- Option to limit …

Add Splunk external search command script for Vast queries

---

libvast/test/parseable.cpp
libvast/vast/concept/parseable/numeric/byte.hpp

Fix bytes parser to support correct parsing into not zero initialized arrays. Add additional unit tests.

Fix bytes parser

---

libvast/src/system/exporter.cpp
libvast/src/system/partition.cpp
libvast/src/value_index.cpp
libvast/test/system/index.cpp
libvast/test/system/partition.cpp
libvast/vast/ids.hpp
libvast/vast/system/exporter.hpp
libvast/vast/system/index.hpp
libvast/vast/value_index.hpp

Here is a list of files (without the unit test files) I have changed or omitted.
Omitted with a question mark means I'm not sure if these files have to refactored as well. 
File | Note
----|-----------
libvast/vast/ids.* |                 added
libvast/vast/bitmap_algorithms.* |   omitted; low level bitmap operations
libvast/src/bitmap.* |               omitted; low level bitmap operations
vast/coder.*: |                      omitted; low level bitmap operations
libvast/src/system/configuration.* | omitted
libvast/vast/batch.* |               omitted; name ids in use
libvast/src/system/archive.* |               omitted
libvast/vast/value_index.* |         changed
libvast/src/system/indexer.* |       changed
libvast/vast/system/index.* |        changed
libvast/vast/system/exporter.* | …

Replace usage of bitmap with ids where appropiate

---

libvast/src/system/indexer.cpp
libvast/src/system/partition.cpp
libvast/vast/system/accountant.hpp
libvast/vast/system/archive.hpp
libvast/vast/system/consensus.hpp
libvast/vast/system/data_store.hpp
libvast/vast/system/exporter.hpp
libvast/vast/system/importer.hpp
libvast/vast/system/index.hpp
libvast/vast/system/indexer.hpp
libvast/vast/system/node.hpp
libvast/vast/system/partition.hpp
libvast/vast/system/profiler.hpp
libvast/vast/system/replicated_store.hpp
libvast/vast/system/signal_monitor.hpp
libvast/vast/system/task.hpp
libvast/vast/system/tracker.hpp

Many stateful actors in VAST have a member variable for their name where a
static member variable instead would suffice.

Make actor names static where possible

---

libvast/CMakeLists.txt
libvast/src/ids.cpp
libvast/test/batch.cpp
libvast/test/ids.cpp
libvast/test/system/archive.cpp

Building ID sets in unit tests is tedious. This little helper function helps
reducing the noise.

Add `make_ids` utility function

---

libvast/src/system/exporter.cpp
libvast/src/system/importer.cpp
libvast/src/system/spawn.cpp
libvast/test/system/exporter.cpp
libvast/vast/system/atoms.hpp
libvast/vast/system/exporter.hpp
libvast/vast/system/importer.hpp
libvast/vast/system/node.hpp
libvast/vast/system/node_state.hpp
libvast/vast/system/spawn.hpp

This PR addresses #131. The idea is to let the NODE identify when it spawns an exporter with a continuous query. It then sends the actor handle to each running IMPORTER, which monitors the actor and forwards it the same data it forwards to the ARCHIVE and INDEX.
There are some unresolved issues for now, which can be discussed in this thread.
I'd argue that continuous queries already work. I am not sure about the interference with historic queries, though.
I didn't get the test for universal queries to work as I wanted to. I tried to recreate a VAST node with an IMPORTER, ARCHIVE and INDEX. However, sending data to the IMPORTER doesn't seem to index everything ... That's why I opted for sending the data to the ARCHIVE and INDEX directly. Looks a bit dodgy to me. I can't tell if this is a …

Add continuous queries

---

libvast/CMakeLists.txt

When using CMake to generate a project file that includes links to headers / sources such as an Xcode project the header files did not show up in the editor. With this PR they do! Granted that is not helpful at the moment as Xcode uses the system compiler which does not currently support the C++17 flag. Not sure how other generators behave, but I guess they might have a similar problem.
I had these changes in the continuous query topic branch originally. Here is a separate PR to make it a bit cleaner.

Make headers available to generator configuration

---

libvast/vast/detail/type_traits.hpp
libvast/vast/variant.hpp

Use C++17 fold expressions instead of using `std::conjunction` and
`std::disjunction`.

Replace (con|dis)junction with fold expressions

---

libvast/src/format/bgpdump.cpp
libvast/src/format/pcap.cpp
libvast/src/type.cpp
libvast/vast/type.hpp

We saw this pattern multiple times in code base.
The function can also be used for the mrt parser and the netflow parser.

Add function which replaces types with new types if congruent

---

libvast/src/format/mrt.cpp
libvast/test/format/mrt.cpp
libvast/vast/format/mrt.hpp

This PR continue the work that @Musteblume started in #118. The last integration commit includes the heavy lifting that was necessary for completing the remaining work items.
At this point, the MRT format reads its input in fully incremental fashion, by parsing one record at a time before proceeding. The previous approached "slurped" in the entire file in memory first, which may not be feasible for large or continuous input.
I've ported two MRT formats as an example that shows how we should structure the implementation of the protocol. The remaining tasks are:

Integrate new MRT format

---

libvast/src/expression_visitors.cpp
libvast/test/expression.cpp

This PR fixes an issue with the expression validation. The implementation used the wrong internal helper function to compute whether the operands of a predicate are compatible to each other.

Fix expression evaluation

---

libvast/src/system/pcap_writer_command.cpp
libvast/src/system/spawn_sink.cpp
libvast/src/system/writer_command_base.cpp
libvast/test/system/sink.cpp
libvast/vast/system/pcap_writer_command.hpp
libvast/vast/system/sink.hpp
libvast/vast/system/writer_command.hpp
libvast/vast/system/writer_command_base.hpp

Fix shutdown issue when using the `export` command with a limit.

Pass limit to sink in export command

---

.gitignore
compile_commands.json
libvast/src/command.cpp
libvast/src/system/application.cpp
libvast/src/system/export_command.cpp
libvast/src/system/import_command.cpp
libvast/src/system/pcap_reader_command.cpp
libvast/src/system/pcap_writer_command.cpp
libvast/src/system/reader_command_base.cpp
libvast/src/system/remote_command.cpp
libvast/src/system/start_command.cpp
libvast/src/system/writer_command_base.cpp
libvast/test/command.cpp
libvast/vast/command.hpp
libvast/vast/system/application.hpp
libvast/vast/system/export_command.hpp
libvast/vast/system/import_command.hpp
libvast/vast/system/pcap_reader_command.hpp
libvast/vast/system/pcap_writer_command.hpp
libvast/vast/system/reader_command.hpp
libvast/vast/system/reader_command_base.hpp
libvast/vast/system/remote_command.hpp
libvast/vast/system/start_command.hpp
libvast/vast/system/writer_command.hpp
libvast/vast/system/writer_command_base.hpp
vast/vast.cpp

This is the first of a series of commits to redesign command.
In this step, we replace the caf::message in the command API by light weight iterators.

Replace caf::message in command by a range over args of strings

---

libvast/src/command.cpp
libvast/src/system/application.cpp
libvast/src/system/pcap_reader_command.cpp
libvast/src/system/pcap_writer_command.cpp
libvast/src/system/remote_command.cpp
libvast/src/system/start_command.cpp
libvast/vast/logger.hpp
libvast/vast/system/reader_command.hpp
libvast/vast/system/sink.hpp
libvast/vast/system/writer_command.hpp

Lift CAF logging primitives and avoid unnecessary complexity for features we get for free from CAF.

Consolidate logging API

---

libvast/CMakeLists.txt
libvast/test/parse_data.cpp

It seems like the unit_test `parse_data.cpp`was overlooked and not added to the cmake build.
Here is the fix.

Add missing unit-test to cmake build

---

libvast/src/option_map.cpp
libvast/test/option_map.cpp
libvast/vast/option_map.hpp

This PR changes the `option_map` API.
The function `get()`and `get_or()` expose the `option_map` internal data structure`data` which complicates its usage.
The new API returns the actual types.

Add global get() and get_or() for option_map

---

libvast/CMakeLists.txt
libvast/test/byte.cpp
libvast/test/span.cpp
libvast/vast/detail/byte.hpp
libvast/vast/detail/narrow.hpp
libvast/vast/detail/span.hpp

The GSL has various useful utilities. Of particular interest to us are the precursors to `std::byte` and `std::span`, now available in namespace `detail`. We also include [`narrow`](https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#es46-avoid-lossy-narrowing-truncating-arithmetic-conversions) to make narrowing explicit from now on.

Add a few GSL utilities: byte, narrow, span

---

libvast/test/data.cpp
libvast/test/value.cpp
libvast/vast/aliases.hpp
libvast/vast/detail/vector_map.hpp
libvast/vast/detail/vector_set.hpp

In this PR we replace the type of the  aliases `set` and `map` by a flat steady_set and steady_map because (i) data is immutable, (ii) it is a more cache-friendly data structure, and (iii) set cardinalities are typically small where sequential brute-force access/find is fast enough.
The first commit replaces the type of `set` and the second commit replaces the type of `map`.

Make set and map types aliases flat and steady

---

libvast/src/bitmap.cpp
libvast/src/expression.cpp
libvast/src/expression_visitors.cpp
libvast/src/system/exporter.cpp
libvast/src/system/index.cpp
libvast/src/system/indexer.cpp
libvast/src/system/partition.cpp
libvast/test/expression.cpp
libvast/test/expression_evaluation.cpp
libvast/test/json.cpp
libvast/test/view.cpp
libvast/vast/bitmap.hpp
libvast/vast/concept/parseable/vast/json.hpp
libvast/vast/concept/printable/vast/expression.hpp
libvast/vast/concept/printable/vast/json.hpp
libvast/vast/expression.hpp
libvast/vast/json.hpp
libvast/vast/system/source.hpp
libvast/vast/view.hpp

This PR converts the various sum types in VAST from `vast::variant` or `std::variant` to `caf::variant`.
Types to convert:
Cleanup:

Consolidate variant implementations

---

libvast/src/format/bro.cpp

Calling `x.name(...)` on a type no longer changes the type, hence `x = x.name(...)` is needed.

Fix name of bro format types

---

libvast/src/address.cpp
libvast/src/view.cpp
libvast/test/view.cpp
libvast/vast/address.hpp
libvast/vast/view.hpp

Currently there's no way to convert a `data_view` back to `data`. The new `materialize` function adds this feature.

Add conversion from views back to values

---

libvast/src/table_slice.cpp
libvast/src/table_slice_builder.cpp
libvast/test/default_table_slice.cpp
libvast/vast/data.hpp
libvast/vast/fwd.hpp
libvast/vast/table_slice.hpp
libvast/vast/table_slice_builder.hpp

Extracting events from table slices greatly simplifies (once could argue enables) testing.

Allow getting events from table slice rows

---

Jenkinsfile

We still need some updates in Jenkins, e.g. updating to the latest compiler on macOS. Maybe we could throw a FreeBSD 11 in the mix.
However, the Jenkinsfile itself is working: https://jenkins.inet.haw-hamburg.de/blue/organizations/jenkins/VAST%2Fvast/detail/story%2Fch3186/5/pipeline/54

Add Jenkinsfile to enable automatic builds

---

libvast/src/view.cpp
libvast/test/view.cpp
libvast/vast/view.hpp

Views previously had shallow comparison semantics for containers, which were only comparing pointer values.

Perform deep view comparison

---

libvast/CMakeLists.txt
libvast/src/const_table_slice_handle.cpp
libvast/src/default_table_slice.cpp
libvast/src/system/configuration.cpp
libvast/src/table_slice.cpp
libvast/src/table_slice_handle.cpp
libvast/test/default_table_slice.cpp
libvast/vast/const_table_slice_handle.hpp
libvast/vast/default_table_slice.hpp
libvast/vast/error.hpp
libvast/vast/ptr_handle.hpp
libvast/vast/table_slice.hpp
libvast/vast/table_slice_handle.hpp

We currently send `table_slice_ptr` between actors and mark them as unsafe message type to get it compiling. Adding a properly serializable `table_slice_handle` type is the first step to get back clean, distributable messaging.
Both handle types (`table_slice_handle` and `const_table_slice_handle`) *could* be implemented header-only (as alias to `ptr_handle`). However, by moving the `inspect` functions to .cpp files and giving them proper types we get away with very lean headers that rely almost exclusively on forward declarations.

Add new handle types for table slices

---

libvast/src/detail/mmapbuf.cpp
libvast/test/mmapbuf.cpp

The algorithm to expand a mmaped region is buggy and has already triggered segfaults on linux systems.

Fix mmapbuf::resize() and re-enable aligned resize test

---

libvast/test/mmapbuf.cpp

Sometimes resizing the mmap to 800 MB is too much for the Jenkins host, so this should reduce peak usage to 80 MB.

Reduce mmap size for large streambuf resize test

---

libvast/src/defaults.cpp
libvast/vast/system/reader_command.hpp

The default schemas are hardcoded at the moment, and stdin is used for data input.

Remove default name for schema file

---

CMakeLists.txt
configure

Mid-term, we want to make the most of our tool chain and enable most diagnostics modern compilers have to offer. I currently cannot recommend enabling this option for daily work, as it *will* flood your terminal.

Add --more-warnings config option

---

CMakeLists.txt
Jenkinsfile
configure
libvast/src/batch.cpp
libvast/src/detail/posix.cpp
libvast/src/value_index.cpp
libvast/test/vector_map.cpp
libvast/vast/bitvector.hpp
libvast/vast/command.hpp
libvast/vast/config.hpp.in
libvast/vast/detail/narrow.hpp
libvast/vast/detail/raise_error.hpp
libvast/vast/detail/vector_map.hpp
libvast/vast/format/mrt.hpp
libvast/vast/load.hpp
libvast/vast/save.hpp

Support VAST builds with exceptions disabled. The primary use case for such builds is coverage reporting. Otherwise, each function call to a potentially throwing function will reduce in a branch and thus make the branch coverage report pretty much useless.
Additionally, add coverage reporting to `Jenkinsfile` and close [ch857].

Allow disabling of exceptions and hook code coverage into CI

---

libvast/src/ewah_bitmap.cpp
libvast/src/system/exporter.cpp

Events can arrive in any order from the archive (pre table-slices it seems this wasn't the case). However, the loop in the exporter's `handle_batch` function builds a bitmap mask with the presumption that IDs are ascending. To leave the bitmap mask computation as-is (simple and append-only), we thus need to sort the candidates before entering the loop.

Fix performance issue in handle_batch of the EXPORTER

---

libvast/test/system/archive.cpp
libvast/test/system/exporter.cpp
libvast/test/system/importer.cpp
libvast/test/system/index.cpp
libvast/test/system/indexer.cpp
libvast/test/system/indexer_stage_driver.cpp
libvast/test/system/partition.cpp
libvast/test/system/source.cpp

Recent CAF master improved and simplified its testing API. However, several functions got deprecated.

Fix deprecation warnings

---

libvast/src/system/importer.cpp
libvast/src/system/reader_command_base.cpp
libvast/vast/system/importer.hpp
libvast/vast/system/reader_command_base.hpp

This feature is meant for integration testing and won't work in a distributed setting or when having parallel, high-volume imports.

Add flag to make import command blocking

---

libvast/test/system/importer.cpp

This only fixes the symptom, the underlying problem is that it is easy to misuse the `events` fixture. But we already have [[3446]](https://app.clubhouse.io/tenzir/story/3446/finish-migration-of-the-unit-tests-to-the-table-slice-api) for that.

Fix the importer test

---

libvast/src/system/start_command.cpp

This change is required for integration testing, where vast nodes are stopped and started in quick succession.

Enable reuse_addr when publishing the node

---

libvast/src/defaults.cpp
libvast/src/detail/compressedbuf.cpp
libvast/src/format/mrt.cpp
libvast/src/system/consensus.cpp
libvast/src/system/spawn.cpp
libvast/src/system/spawn_source.cpp
libvast/test/compressedbuf.cpp
libvast/test/mmapbuf.cpp
libvast/test/parseable.cpp
libvast/test/printable.cpp
libvast/vast/concept/parseable/core/literal.hpp
libvast/vast/concept/parseable/vast/address.hpp
libvast/vast/concept/parseable/vast/base.hpp
libvast/vast/concept/parseable/vast/data.hpp
libvast/vast/concept/parseable/vast/endpoint.hpp
libvast/vast/concept/parseable/vast/expression.hpp
libvast/vast/concept/parseable/vast/http.hpp
libvast/vast/concept/parseable/vast/json.hpp
libvast/vast/concept/parseable/vast/port.hpp
libvast/vast/concept/parseable/vast/time.hpp
libvast/vast/concept/parseable/vast/uri.hpp
libvast/vast/concept/printable/core/literal.hpp
libvast/vast/concept/printable/vast/attribute.hpp
libvast/vast/concept/printable/vast/type.hpp
libvast/vast/detail/compressedbuf.hpp
libvast/vast/si_literals.hpp
libvast/vast/system/replicated_store.hpp

This PR does two things:
1. Add a new namespace with user-defined literals for SI units.
2. Move the printer and parser literals into a dedicated namespace.

Enhance usage of user-defined literals

---

libvast/src/table_slice.cpp
libvast/test/default_table_slice.cpp
libvast/vast/default_table_slice.hpp

Extend `table_slice::deserialize_ptr` to support custom table slice types. Users only need to register a factory function for the custom type via `sys.runtime_settings().set(...)`.

Support custom table slice types

---

libvast/src/column_index.cpp
libvast/src/segment_store.cpp
libvast/src/system/consensus.cpp
libvast/src/system/index.cpp
libvast/src/system/partition.cpp
libvast/test/bitmap_index.cpp
libvast/test/bitvector.cpp
libvast/test/cache.cpp
libvast/test/chunk.cpp
libvast/test/coder.cpp
libvast/test/data.cpp
libvast/test/event.cpp
libvast/test/expression.cpp
libvast/test/range_map.cpp
libvast/test/save_load.cpp
libvast/test/schema.cpp
libvast/test/type.cpp
libvast/test/value.cpp
libvast/test/value_index.cpp
libvast/vast/load.hpp
libvast/vast/save.hpp

Currently, we have lots of blocks that read like this:
```
if (auto res = load(...); !res) { 
// ... log res.error()
}
```
Switching the result type reduces noise and redundancy:
```
if (auto err = load(...)) { 
// ... log err
}
```

Change API of load()/store() to return errors instead of expected<void>

---

libvast/src/segment_store.cpp
libvast/test/fixtures/events.cpp
libvast/test/format/writer.cpp
libvast/test/segment.cpp
libvast/test/segment_store.cpp
libvast/test/system/archive.cpp
libvast/test/system/index.cpp
libvast/test/system/source.cpp

The slice_size in unit tests is changed from 100 to 8. This had to be done in order to keep the segment store test meaningful.

Fix unit test expectations and segment_store::get

---

libvast/src/system/export_command.cpp
libvast/src/system/import_command.cpp
libvast/src/system/pcap_reader_command.cpp
libvast/src/system/pcap_writer_command.cpp
libvast/src/system/reader_command_base.cpp
libvast/src/system/remote_command.cpp
libvast/src/system/writer_command_base.cpp
libvast/vast/system/reader_command_base.hpp

This PR moves up the `-b` flag up one level in the command hierarchy, because it is not a format-specific option.

Move -b up on level in the command hierarchy

---

libvast/src/system/configuration.cpp
libvast/src/system/spawn.cpp
libvast/src/system/tracker.cpp
libvast/vast/system/source.hpp

This change allows users to set table slice sizes via `vast.ini` or CLI.

Make table slice sizes configurable

---

cmake/FindCAF.cmake

Fix `FindCAF.cmake` to work with CAF build directories again.

Detect build_config.hpp in build directories

---

libvast/src/system/configuration.cpp

CAF no longer accepts the old `caf#` prefix. However, it's still useful to continue using it for disambiguation with command options. This patch simply removes the `caf#` prefix before passing the options to CAF's parser.

Fix parsing of CAF options

---

libvast/src/table_index.cpp
libvast/test/table_index.cpp

Make queries such as `&type == "bro::conn"` working again.

Fix type name lookup

---

libvast/src/system/task.cpp
libvast/vast/system/replicated_store.hpp
libvast/vast/system/task.hpp

Including VAST headers in the "wrong" order produces a compiler error for ambiguously defined symbols. Culprit here is the namespace `vast::system::detail`.
Having multiple namespaces with the same name is only asking for trouble. Hence, this PR flattens the namespaces into `vast::detail`.

Flatten namespace vast::{system:: => }detail

---

libvast/src/default_table_slice_builder.cpp
libvast/src/table_slice_builder.cpp
libvast/vast/default_table_slice_builder.hpp
libvast/vast/system/source.hpp
libvast/vast/table_slice_builder.hpp

The table slice builder usually knows beforehand how many rows we're about to add. Giving it a parameter for calling `reserve` on the internal vector avoids unnecessary allocations.

Allow sources to pre-allocate builder rows

---

libvast/src/system/exporter.cpp
libvast/src/system/sink_command.cpp

Before this change the exporter would not terminate itself when it received an error from the index. This is the fix.

Quit exporter in case of error

---

libvast/src/column_index.cpp
libvast/src/table_index.cpp
libvast/test/system/partition.cpp
libvast/test/table_index.cpp
libvast/vast/column_index.hpp
libvast/vast/table_index.hpp

We no longer need to distinguish meta from actual data, since the only remaining meta column represents a type name. With (homogeneous) table slices, we don't need an index anymore and can process `&type` extractors more efficiently.

Remove distinction between meta and data columns

---

libvast/CMakeLists.txt
libvast/src/default_table_slice.cpp
libvast/src/meta_index.cpp
libvast/src/synopsis.cpp
libvast/src/table_slice.cpp
libvast/src/timestamp_synopsis.cpp
libvast/test/default_table_slice.cpp
libvast/test/fixtures/actor_system.hpp
libvast/test/synopsis.cpp
libvast/test/test.hpp
libvast/test/type.cpp
libvast/vast/error.hpp
libvast/vast/meta_index.hpp
libvast/vast/min_max_synopsis.hpp
libvast/vast/synopsis.hpp
libvast/vast/timestamp_synopsis.hpp
libvast/vast/type.hpp

Synopsis and meta index use complex two-phase mechanisms for registering factories. This uses the same mechanism we already use for table slices. Also fixes a bug with serializing `type` that became apparent when serializing synopsis.

Harmonize serialization of meta index and synopsis 

---

libvast/src/format/bro.cpp
libvast/src/type.cpp
libvast/test/event.cpp
libvast/test/fixtures/events.cpp
libvast/test/schema.cpp
libvast/test/type.cpp
libvast/test/type_test.hpp
libvast/vast/concept/parseable/vast/schema.hpp
libvast/vast/concept/parseable/vast/type.hpp
libvast/vast/type.hpp

Currently, `type` makes deep copies in its copy ctor and assignment operator. After this change, `type` makes shallow copies instead and uses copy-on-write for modifiers.

Make type implicitly shared

---

doc/vast.1
doc/vast.1.md
libvast/src/system/default_application.cpp
libvast/src/system/node.cpp

`vast send <run|flush>` is an implementation detail that should not be exposed to the user.

Remove vast send subcommand

---

libvast/CMakeLists.txt
libvast/src/error.cpp
libvast/test/error.cpp
libvast/vast/error.hpp

This PR fixes a mismatch in the error code definition and desription. New unit tests ensure that this hopefully won't happen again.

Fix out-of-sync error codes

---

libvast/src/default_table_slice_builder.cpp
libvast/src/format/test.cpp
libvast/src/table_slice.cpp
libvast/src/table_slice_builder.cpp
libvast/vast/default_table_slice_builder.hpp
libvast/vast/format/test.hpp
libvast/vast/table_slice_builder.hpp

Working with the test reader for generating table slices is tedious, because the reader only generates `vast::event`.

Support table slice builder in test reader

---

cmake/FindBroker.cmake
cmake/FindCAF.cmake
cmake/FindGperftools.cmake
cmake/FindPCAP.cmake
cmake/FindSnappy.cmake
libvast/CMakeLists.txt

This patch adds imported targets to the cmake find modules. The `libvast` target uses those targets instead of the library files directly to cut the dependencies to the full paths to these files.

Make cmake installation relocatable

---

libvast/src/system/source_command.cpp

Fixes the following warning when running VAST:
```
*** unexpected message [id: 7, name: bro-reader]: ('run')
```

Remove superfluous message

---

vast/vast.cpp

Currently, hitting CTRL+C at a VAST server prints "none" on exit but it shouldn't print anything.

Suppress printing on exit for "none" errors

---

doc/vast.1.md
libvast/src/system/default_application.cpp
libvast/src/system/node.cpp

This reflects our intention to have this command print more than "just" the topology. For example, partition size, total number of events, etc.

Rename "show" to "status" command

---

libvast/vast/logger.hpp

Consistently use constants such as `CAF_LOG_LEVEL_ERROR` instead of hard-coding integer values.

Fix hardcoding of log level constants

---

libvast/vast/system/tracker.hpp

Unsortedness turned out to be problematic when checking for the
expected state during integration testing.

Make registry sorted

---

libvast/src/system/node.cpp

Adds 1) nr. of running actors, 2) nr. of detached actors, and 3) nr. of worker threads to the output of `vast status`.
This is by no means an exhaustive list and we might add more CAF stats in the future.

Enrich status command with actor system stats

---

libvast/test/system/importer.cpp

We recently fixed a bug where failing sources of the IMPORTER killed ARCHIVE and INDEX. This regression test makes sure that this won't happen again.

Add regression test for IMPORTER stream errors

---

libvast/src/expression.cpp
libvast/src/expression_visitors.cpp
libvast/src/meta_index.cpp
libvast/src/table_index.cpp
libvast/test/expression.cpp
libvast/test/expression_parseable.cpp
libvast/vast/concept/parseable/vast/expression.hpp
libvast/vast/concept/printable/vast/expression.hpp
libvast/vast/expression.hpp
libvast/vast/system/atoms.hpp

This makes the attribute extractor more lightweight and dispatching on attributes cheaper.

Migrate attribute extractor data from string to atom

---

CMakeLists.txt

Currently, configuring an invalid log level gets detected at compile time rather than immediately when configuring the build.

Fail the build early on invalid log level setup

---

libvast/src/system/accountant.cpp
libvast/src/system/node.cpp
libvast/src/system/source_command.cpp
libvast/src/system/tracker.cpp
libvast/vast/system/accountant.hpp
libvast/vast/system/datagram_source.hpp
libvast/vast/system/source.hpp

This PR fixes the empty accounting.log and adds extra telemetry to better understand VAST's internals.

Improve telemetry details in accountant (WIP)

---

libvast/CMakeLists.txt
libvast/src/system/default_application.cpp
libvast/src/system/node.cpp
libvast/src/system/simple_store.cpp
libvast/src/system/spawn.cpp
libvast/test/system/simple_store.cpp
libvast/vast/save.hpp
libvast/vast/system/simple_store.hpp

Mostly self-explanatory, it is just an adaptation of `data_store` with serialization.
There are several open questions though:

Introduce simple_store

---

libvast/src/segment_store.cpp
libvast/src/system/archive.cpp
libvast/src/system/exporter.cpp
libvast/test/system/archive.cpp
libvast/vast/system/archive.hpp

- Notify INDEX about dropped queries
- Dismiss zombie requests in ARCHIVE
-> will be done in #343

Fix high latency exports

---

libvast/test/meta_index.cpp

In the statement
```cpp
auto str = "foo";
```
the lvalue `str` decays to `const char*` and not a `char[N]`. We only had a `char[N]` overload that creates a `view<std::string>`. Once we had a `const char*`, the overload with `const data&` got picked. And because `data` has non-explicit constructor, `make_view` created a temporary data object and return a view to it.

Fix pesky reference-to-temporary bug

---

libvast/src/meta_index.cpp
libvast/test/meta_index.cpp

This PR enhances the meta index to support type attribute queries. For example, it is now possible to process `&type != "foo"`.

Support meta index lookup via type attributes

---

libvast/test/string.cpp

After we have converted the string splitting functions, we forgot about adjusting the unit tests. This caused some reference-to-temporary bugs that are fixed now.

Fix string splitting unit tests

---

libvast/src/segment_store.cpp
libvast/src/store.cpp
libvast/src/system/archive.cpp
libvast/test/segment_store.cpp
libvast/vast/segment_store.hpp
libvast/vast/store.hpp

Support piecemeal result extraction from the archive

---

libvast/src/segment_store.cpp

The lookup session accidentally handled the return value from load_segment in the wrong way, treating a success as error and vice versa.

Fix loading of segments from file

---

libvast/src/expression.cpp
libvast/test/expression.cpp
libvast/vast/expression.hpp
libvast/vast/expression_visitors.hpp

Enable offset-based node access in expressions

---

libvast/src/detail/add_message_types.cpp
libvast/src/system/archive.cpp
libvast/src/system/exporter.cpp
libvast/test/system/archive.cpp
libvast/vast/system/archive.hpp
libvast/vast/system/exporter.hpp
libvast/vast/system/fwd.hpp
libvast/vast/system/query_status.hpp
libvast/vast/system/sink.hpp
libvast_test/src/node.cpp
libvast_test/vast/test/fixtures/node.hpp

A little bit of cleanup is being done on the side here:
- The name `query_statistics` was misleading, the type is renamed to `query_status`.
- The exporter now uses a counter for keeping track of outstanding id look ups instead of a bitmap.
- We don't request new ids any more after handling a table slice that was sent from the importer.

Return archive lookup results incrementally

---

libvast/src/system/dummy_consensus.cpp
libvast/vast/system/data_store.hpp
libvast/vast/system/dummy_consensus.hpp
libvast/vast/system/key_value_store.hpp
libvast/vast/system/replicated_store.hpp

I consider this extension mostly trivial. The only thing that might be questionable is in `replicated_store`, where the raft statistics now get cached in the state for no reason other than the status report.

Add status message handler to consensus

---

libvast/test/parse_data.cpp
libvast/vast/concept/parseable/vast/data.hpp

The inner parser (after the container tokens) was not optional.

Fix parsing of empty containers

---

libvast/src/defaults.cpp
libvast/src/system/node.cpp
libvast/src/table_slice_builder.cpp
libvast/vast/add_table_slice.hpp
libvast/vast/defaults.hpp
libvast/vast/system/datagram_source.hpp
libvast/vast/system/default_application.hpp
libvast/vast/system/reader_command.hpp
libvast/vast/system/source.hpp
libvast/vast/table_slice_builder.hpp

This PR adds a new factory for table slice builders such that it becomes possible to select a builder dynamically at runtime. We use this feature to support selection of a particular table slice type on the command line.

Support choice of table slice type on command line

---

libvast/src/system/index.cpp
libvast/src/system/indexer.cpp
libvast/src/system/indexer_stage_driver.cpp
libvast/src/system/spawn_indexer.cpp
libvast/src/system/table_indexer.cpp
libvast/test/system/indexer.cpp
libvast/test/system/indexer_stage_driver.cpp
libvast/vast/system/index.hpp
libvast/vast/system/indexer.hpp
libvast/vast/system/spawn_indexer.hpp
libvast_test/src/dummy_index.cpp

This patch fixes a bug where an indexer could be triggered to flush its data before all items in its inbound stream were consumed, loading to an incomplete column_index on disk.

Keep unpersisted partitions until indexing is done

---

libvast/test/parse_data.cpp
libvast/test/parseable.cpp
libvast/vast/concept/parseable/core/choice.hpp
libvast/vast/concept/parseable/vast/data.hpp
libvast/vast/concept/printable/vast/data.hpp
libvast_test/src/table_slices.cpp

Until now it was impossible to parse an empty map with the data parser, because the string `{}` represented both an empty set and and empty map. Now we're using `{-}` to represent an empty map.

Support parsing of empty map

---

libvast/src/default_table_slice_builder.cpp
libvast/src/format/bgpdump.cpp
libvast/src/format/bro.cpp
libvast/src/format/pcap.cpp
libvast/src/meta_index.cpp
libvast/src/to_events.cpp
libvast/test/column_index.cpp
libvast/test/format/bro.cpp
libvast/test/format/pcap.cpp
libvast/test/format/writer.cpp
libvast/test/meta_index.cpp
libvast/test/system/source.cpp
libvast/vast/format/bgpdump.hpp
libvast/vast/format/bro.hpp
libvast/vast/system/source.hpp
libvast/vast/type.hpp
libvast_test/src/events.cpp

It is now possible to designate the event timestamp by adding the `&time` attribute to a timestamp type in a schema. The existing formats do this automatically. The meta index now looks for a `&time` attribute when it gets a predicate of the form `&time op RHS`.
While implementing the `&time` feature, it was the right time to rip out the additional timestamp column that was prepended to every table slice.
As I was working on the formats, I also flattened the layout, since this would have happened downstream anyway.
Ideally, these would have been all separate commits (and even PRs), but the order of how I approached this was sub-optimal. Sorry about that. I hope the review is still manageable.

Use &time attribute to signal event time

---

libvast/CMakeLists.txt
libvast/src/boolean_synopsis.cpp
libvast/src/meta_index.cpp
libvast/src/synopsis.cpp
libvast/src/system/index.cpp
libvast/test/meta_index.cpp
libvast/test/synopsis.cpp
libvast/test/system/index.cpp
libvast/vast/boolean_synopsis.hpp
libvast/vast/meta_index.hpp
libvast/vast/synopsis.hpp

We got rid of the actor system logic, analogously to the table slice
factory.

Simplify synopsis factory logic

---

libvast/src/meta_index.cpp

If a field has a skip attribute, it will not be considered in the index.
Then it shouldn't be considered in the meta index either.

Respect skip attribute when creating synopses

---

libvast/src/system/default_configuration.cpp

This PR removes unnecessary calls to `load` in our derived actor system configuration.

Remove redundant CAF initialization code

---

libvast/src/chunk.cpp
libvast/vast/chunk.hpp

clang-format was not nice to that lambda, but what can you do...

Make chunk::const_pointer pointer to const

---

libvast/src/system/default_application.cpp
libvast/src/system/sink_command.cpp

With this patch, we have several options to pass queries:
1) single CLI argument: `vast export ascii ':addr == 192.168.1.103'`
2) multiple CLI arguments: `vast export ascii :addr == 192.168.1.103`
3) Via STDIN: `echo ':addr == 192.168.1.103' | vast export -e 5 ascii`
4) Via file: `echo ':addr == 192.168.1.103' > query.txt ; vast export -r query.txt ascii`

Allow passing queries via STDIN or file

---

libvast/src/data.cpp
libvast/src/value.cpp
libvast/test/data.cpp
libvast/test/event.cpp
libvast/test/format/writer.cpp
libvast/test/value.cpp
libvast/vast/format/json.hpp

We had a rather unwieldy form of printing data in JSON in the past whereboth type and data had been printed separately. We now switch to"zipped" output that takes the layout field names as JSON object keysand data as their corresponding values.
Moreover, I took the liberty to tweak the JSON output of ports: instead of printing `"53/udp"` we now simply display the number `53`. Since Zeek also dumps its port in this (lossy) form, downstream data analysis tools will likely expect such a format.

Streamline JSON output

---

libvast/src/system/default_configuration.cpp
libvast/vast/system/default_configuration.hpp
vast/vast.cpp

Makes sure that the CAF log gets places into the proper directory.

Fix -d flag

---

libvast/src/time.cpp
libvast/test/format/writer.cpp
libvast/test/json.cpp
libvast/vast/json.hpp

The nanosecond output is rather unusual. Hence the shift to fractional timestamps.

Use fractional timestamps in JSON output

---

libvast/src/detail/fill_status_map.cpp
libvast/src/system/importer.cpp
libvast/src/system/index.cpp
libvast/src/system/indexer_stage_driver.cpp
libvast/test/system/indexer_stage_driver.cpp
libvast/vast/detail/notifying_stream_manager.hpp
libvast/vast/system/importer.hpp
libvast/vast/system/index.hpp
libvast/vast/system/indexer_stage_driver.hpp

We previously broke the current implementation of the `-b` when making the INDEXERs parallel again. This patch fixes the "done" signaling by pushing it from the IMPORTER to the INDEX when the former is done (which in turn means that the ARCHIVE is already done).

Fix -b flag of the import command

---

libvast/src/system/evaluator.cpp
libvast/src/system/exporter.cpp
libvast/src/system/partition.cpp

a) race in the EXPORTER (corrupt state if hits arrive before initial INDEX response)
b) VAST doesn't shutdown for `&time < now` queries
c) VAST produces no results for said query

Fix three bugs in the export command

---

libvast/src/system/default_configuration.cpp

8221a0b broke the log file setup on the wrong assumption that the actor_system_config didn't preload the field on construction.

Fix log file initialization

---

libvast/CMakeLists.txt
libvast/src/defaults.cpp
libvast/src/endpoint.cpp
libvast/src/system/connect_to_node.cpp
libvast/src/system/start_command.cpp
libvast/test/endpoint.cpp
libvast/test/printable.cpp
libvast/vast/concept/parseable/core/action.hpp
libvast/vast/concept/parseable/core/choice.hpp
libvast/vast/concept/parseable/core/optional.hpp
libvast/vast/concept/parseable/core/sequence.hpp
libvast/vast/concept/parseable/detail/container.hpp
libvast/vast/concept/parseable/vast/endpoint.hpp
libvast/vast/concept/printable/core/kleene.hpp
libvast/vast/concept/printable/core/list.hpp
libvast/vast/concept/printable/core/optional.hpp
libvast/vast/concept/printable/core/plus.hpp
libvast/vast/concept/printable/core/sequence.hpp
libvast/vast/concept/support/detail/attr_fold.hpp
libvast/vast/defaults.hpp
libvast/vast/endpoint.hpp

The action parser did the wrong thing for action lambdas with a single arguemnt. The endpoint parser was overriding the defaults, even when the string to parse didn't contain relevant values.

Fix action and endpoint parser

---

libvast/src/detail/add_message_types.cpp
libvast/vast/expression.hpp

Running `vast export ascii "uid == Cp0n2D3vqPvXmJL95f"` currently results in:
```
[ERROR]: cannot serialize message because a type was not added to the types list, typeid name: N4vast13key_extractorE
```

Fix "cannot serialize message" error

---

libvast/src/system/exporter.cpp

Rather than a nanosecond timestamp, we now use `vast::to_string`, which dynamically chooses the best time duration for human consumption.

Produce human-readable timestamps in log output

---

libvast/src/system/importer.cpp

The IMPORTER initializes its last_replenish with a value of: `"last-replenish": "1677-09-21T01:06:12.-854"`.
That's not useful information, so we no longer add it to the status until we actually replenished at least once.

Include last_replenish for status only after use

---

libvast/src/system/configuration.cpp
libvast/vast/config.hpp.in

- Rename `vast.ini` to `vast.conf`
- Look for system-wide config file in `PREFIX/etc`
- Prefer current directory over system-wide include

Implement proper config file sourcing

---

CMakeLists.txt

I ran into `Illegal Instruction` woes when executing the fedora jenkins build on an osx-based docker host (LinuxKit). This will hopefully get rid of the problem. I enabled up to sse4.2 as a compromise, the chance of running on a box that does not support this is pretty low.

Relax instruction set requirements on target host

---

libvast/src/format/zeek.cpp
libvast/vast/format/zeek.hpp

This PR fixes an invalid substring operation when stripping off the `zeek::` type name prefix. The renaming from Bro to Zeek relied on a hardcoded substring offset, but Zeek is one character longer.
Moreover, we can now print events of multiple types on standard output. Previously, the output was just broken because only the header of the first type got printed. Now, we re-print a new header whenever the type changes. It's not ideal, but it's at least correct. When issueing queries where multiple log types show up in the result set, one should use the directory-based output anyway, which writes each log type in a separate file.

Fix Zeek ASCII output

---

libvast/src/format/zeek.cpp
libvast/test/printable.cpp
libvast/vast/concept/printable/detail/print_numeric.hpp
libvast/vast/concept/printable/numeric/integral.hpp
libvast/vast/concept/printable/numeric/real.hpp

Previously the output did not include trailing zeros if the fractional digits were less than 6.

Use exactly 6 fractional digits for Zeek floating point values

---

libvast/src/system/node.cpp
libvast/src/system/spawn_exporter.cpp
libvast/test/time.cpp
libvast/vast/concept/parseable/vast/time.hpp
libvast/vast/system/spawn_arguments.hpp

Previously the data parser would not parse `2.5` as 2.5 seconds because it didn't accept fractional values. This is now fixed.

Support fractional timespans

---

libvast/src/system/tracker.cpp

This PR fixes an issue in the tracker where all components were subject to a singleton constraint. We want that only for a subset of components.

Fix overly tight restriction on component instances

---

doc/vast.1.md
libvast/CMakeLists.txt
libvast/src/command.cpp
libvast/src/system/default_application.cpp
libvast/src/system/help_command.cpp
libvast/src/system/version_command.cpp
libvast/test/command.cpp
libvast/vast/command.hpp
libvast/vast/system/help_command.hpp
libvast/vast/system/version_command.hpp

Allow users to call `vast help` and replace `vast -v` with `vast version` to enable us to make better use of the `-v` option in the future (e.g. as `verbose` flag).

Add new help and version commands

---

libvast/src/system/exporter.cpp
libvast/src/system/index.cpp
libvast/src/system/source_command.cpp

The various paths through the two `done` handlers in the EXPORTER can lead to corrupt query status. This set of changes fixes a bug that can lead to too few results by enforcing a dependency between done messages from the ARCHIVE and done messages from QUERY_SUPERVISOR actors.

Fix bug in EXPORTER control flow

---

libvast/src/system/partition.cpp

Crashing VAST on malformed user input is not exactly a bright idea.

Remove assertions that trigger on user input

---

libvast_test/CMakeLists.txt
libvast_test/src/events.cpp
libvast_test/vast/test/fixtures/events.hpp
tools/CMakeLists.txt
tools/gen-vast-slices/CMakeLists.txt
tools/gen-vast-slices/README.md
tools/gen-vast-slices/gen-vast-slices.cpp

The new tool `gen-vast-slices` allows us to convert our log artifacts into table slices *once* while compiling `libvast_test`. The unit test than simply deserialize the slices instead of parsing them over and over again.

Add scaffold for using test logs in unit tests without parsing them over and over again

---

libvast/CMakeLists.txt
libvast/src/system/query_processor.cpp
libvast/test/system/query_processor.cpp
libvast/vast/system/query_processor.hpp

Adds a QUERY_PROCESSOR actor that implements an FSM and allows derived actors to extend the FSM via implementation hooks. For example, derived actors can override `transition_to` for adding entry/exit actions.
This is cherry-picked and squashed from https://github.com/vast-io/vast/pull/461. Further, two review comments were open there:
> There seems to be an invalid transition possible: after going through `collect hits` -> `request more hits` -> `no`, I end up in `idle`. But I would not go into `await query id` from there again, right?
The default handler message handlers in `idle` accept an `expression` with an actor handle to the INDEX to trigger transition to the next state. However, derived actors can replace the message handlers to whatever makes sense.
> >   /// @warning Calls …

Implement actor-based FSM for query processing

---

libvast/src/system/start_command.cpp
libvast/vast/system/start_command.hpp

This refactoring allows us to add additional application logic to the start command, e.g., for spinning up additional background service actors for aging.

Allow downstream code to extend start command

---

libvast/src/command.cpp
libvast/src/system/default_application.cpp
libvast/src/system/node.cpp
libvast/vast/command.hpp

For some actors, we need a way to trigger it deterministically for testing. However, such a `send` command should not be visible to the user (i.e. omitted in helptext, manual, etc.) and reserved for internal use only.

Add hidden command for sending atoms to actors

---

Dockerfile

I was trying to build against the latest git -master branch, but kept getting the following error:
```
Step 23/30 : COPY --from=builder /lib/x86_64-linux-gnu/libatomic.so.1 /lib/x86_64-linux-gnu/libatomic.so.1
COPY failed: stat /var/lib/docker/overlay2/3c7a738885f39264559723ad1d2cb907a1517384414e3a7b8c0b42b2c0d92795/merged/lib/x86_64-linux-gnu/libatomic.so.1: no such file or directory
```
After this patch, I was able to get a successful build.

Patching Dockerfile to build properly

---

libvast/src/command.cpp
libvast/src/system/node.cpp
libvast/vast/system/node.hpp

The NODE actor in VAST starts all components. However, we need a way to
add new components as extensions. This set of changes adds a static map
to the NODE actor's state that downstream projects can extend during
startup.

Allow adding new components to the NODE

---

libvast/src/system/query_processor.cpp
libvast/vast/system/query_processor.hpp

Actors such as the EXPORTER and the COUNTER need a way to tell the underlying FSM to not transition out of `collect_hits` when receiving `done` from the INDEX until processing other messages first (usually messages from the ARCHIVE).

Allow query processors to block end-of-hits transition

---

libvast/test/parseable.cpp
libvast/vast/concept/parseable/numeric/integral.hpp

Previously, integral parsers with a maximum digit specification failed when the input contained further digits. This is no longer considered a failure: the parser returns successfully with whatever is has parsed until it reached its digit limit.

Fix behavior of numeric parser for partial input

---

libvast/vast/format/json.hpp
libvast/vast/format/json/suricata.hpp

This additionally removes an overly noisy logging statement.

Fix suricata fileinfo schema

---

libvast/vast/concept/parseable/vast/data.hpp

This fixes cases where "*timespan* ago" would be parsed incorrectly.

Try timestamp before timespan in data parser

---

libvast/src/value_index.cpp
libvast/vast/value_index.hpp

This fixes a segfault that happens if a lookup runs on an index that did not receive any data yet.

Initialize value indexes at construction

---

CHANGELOG.md
libvast/vast/defaults.hpp

By using a different name than the VAST executable `vast`, we can now run `./vast` in the same directory where a state directory exists as well.

Adjust default name of state directory

---

libvast/src/command.cpp
libvast/src/system/default_configuration.cpp
libvast/src/system/node.cpp
libvast/test/command.cpp
libvast/vast/command.hpp
libvast/vast/system/default_configuration.hpp
vast/vast.cpp

Also fixes the weird behavior that `vast help` creates a directory [ch4976].

Implement 2-pass parsing of command line

---

libvast/src/command.cpp
libvast/test/command.cpp
libvast/vast/command.hpp
vast/vast.cpp

In case of parsing of command fails, we still need the original iterator position to figure out *where* things went wrong. This set of changes puts the error state into the `invocation` for this purpose.

Report iterator position with command invocation

---

libvast/src/format/writer.cpp
libvast/test/system/sink.cpp
libvast/vast/format/pcap.hpp
libvast/vast/format/printer_writer.hpp
libvast/vast/format/writer.hpp
libvast/vast/format/zeek.hpp
libvast/vast/system/sink.hpp
tools/zeek-to-vast/zeek-to-vast.cpp

This tweak adds a new virtual function to `writer` that allows subtypes to get the entire batch at once. It makes no difference to VAST at the moment, but I'm going to need the new member function for tackling `Arrow` export (since I need to see the entire batch all at once to create an Arrow table slice [record batch] from it).

Allow writers to consume batches of events

---

libvast/src/format/writer.cpp
libvast/vast/format/writer.hpp

This refactoring simply allows us to port the EXPORTER to table slices
while independently updating writer implementations.

Add write overload to the writer for table slices

---

libvast/src/expression_visitors.cpp
libvast/src/view.cpp
libvast/test/expression_evaluation.cpp
libvast/vast/expression_visitors.hpp
libvast/vast/view.hpp

Currently, the EXPORTER uses an `event_evaluator` for performing the candidate check. If we wish to switch to a table-slice based API then we first need this new function for checking candidates in table slices.

Implement an evaluate function for table slices

---

libvast/src/system/exporter.cpp
libvast/src/table_slice.cpp
libvast/src/to_events.cpp
libvast/test/system/exporter.cpp
libvast/test/system/sink.cpp
libvast/test/table_slice.cpp
libvast/vast/system/exporter.hpp
libvast/vast/system/query_status.hpp
libvast/vast/system/sink.hpp
libvast/vast/table_slice.hpp
libvast_test/src/node.cpp

This set of changes allows the EXPORTER to send table slices to the SINK and drops the conversion to `vector<event>`.
The two new free functions `split` and `truncate` that operate on table slices could be implemented more efficiently as virtual member functions, but I think we should not convolute the `table_slice` interface more than necessary. Those functions are only needed if a table slice exceeds the number of requested events, so they are probably not in a critical path. Should either one of these functions show up in a profile while benchmarking VAST then we can still move those functions into the `table_slice` interface and implement them efficiently for each table slice type.

Port SINK to the table slice API

---

CHANGELOG.md
libvast/test/format/zeek.cpp
libvast/vast/format/zeek.hpp

`capture_loss` logs from Zeek currently trigger an assertion, because VAST does not handle `real` correctly. These changes fix the Zeek reader and allow VAST to cope with `capture_loss` logs.

Properly deal with real input from Zeek logs

---

libvast/src/system/indexer.cpp
libvast/src/system/table_indexer.cpp
libvast/test/format/json.cpp
libvast/test/system/partition.cpp
libvast/test/system/table_indexer.cpp
libvast/test/value_index.cpp
libvast/vast/system/table_indexer.hpp

- Reinstate the regression test in `value_index`
- Fix a segfault in a (disabled) JSON format test (the test itself still fails)
- Bring back several tests in the `partition`
- Test `table_indexer` as good as possible without parent

Improve unit testing

---

CHANGELOG.md
libvast/src/command.cpp
libvast/src/system/default_application.cpp
libvast/src/system/default_configuration.cpp
libvast/vast/command.hpp
libvast/vast/system/default_configuration.hpp
vast/vast.cpp

- Consolidate various initialization steps that we needed in both VAST and Tenzir to streamline the startup sequence and make commands more easily extendible
- Improve user experience by allowing users to change the verbosity via `--verbosity=<level>` instead of `--ca#logger.console-verbosity=<level>`

 Add root command option to set verbosity

---

libvast/CMakeLists.txt
libvast/src/concept/hashable/sha1.cpp
libvast/src/detail/base64.cpp
libvast/src/icmp.cpp
libvast/src/port.cpp
libvast/src/value_index.cpp
libvast/test/community_id.cpp
libvast/test/detail/base64.cpp
libvast/test/hash.cpp
libvast/test/port.cpp
libvast/vast/address.hpp
libvast/vast/community_id.hpp
libvast/vast/concept/hashable/sha1.hpp
libvast/vast/concept/parseable/vast/port.hpp
libvast/vast/concept/printable/vast/port.hpp
libvast/vast/detail/base64.hpp
libvast/vast/detail/coding.hpp
libvast/vast/format/mrt.hpp
libvast/vast/icmp.hpp
libvast/vast/port.hpp
libvast/vast/span.hpp

This PR adds a the [Community ID](https://github.com/corelight/community-id-spec) to PCAP packet data.

Implement generic Community ID computation API

---

libvast/src/table_slice.cpp
libvast/test/format/pcap.cpp
libvast/test/table_slice.cpp
libvast/vast/table_slice.hpp

The new visitors for row- and column-based access provide a more intuitive API to use table slices programmatically, especially in unit tests.

Enable field-based access of table-slice columns

---

libvast/src/format/pcap.cpp

Adding the Community IDs to the PCAP packet type changed the offset of the payload. This resulted in the Community ID mistakenly being used as packet data.

Fix PCAP export

---

libvast/src/system/accountant.cpp

As of https://github.com/actor-framework/actor-framework/pull/863, `node_id` is now an opaque type. Hence, the accountant can no longer split it into its sub-components and instead has to print the node as a single field.

Port VAST to lastet node_id API

---

CHANGELOG.md
libvast/src/system/sink_command.cpp
libvast/vast/concept/printable/vast/expression.hpp

This PR makes PCAP export less error-prone. Users previously had to manually restrict the query expression to type `pcap.packet` by adding a predicate `#type == "pcap.packet"` to ensure that PCAP writer only receives packet events, and not data that it cannot write out as valid PCAP trace.

Restrict PCAP expressions to packet type

---

libvast/src/table_slice_factory.cpp

This PR exchanges usage of a deprecated function with the new one.

Fix deprecation warning by using new CAF API

---

CHANGELOG.md
CMakeLists.txt
README.md

Fixes for building CAF as a submodule

---

CMakeLists.txt
configure

This PR makes it easier to specify a custom install prefix for OpenSSL. Additionally, if there exists an OpenSSL installation from Homebrew on macOS, we'll try to use it by default.

Improve identification of OpenSSL install root

---

CONTRIBUTING.md

GitHub flavored markdown requires anything that looks like an HTML tag to be escaped.

Fix formatting in contribution guidelines

---

.cirrus.yml
CMakeLists.txt

In case VAST is a subproject, the link to the schema directory was generated in the wrong place.

Fix build tree schema dir location

---

integration/packages/wait/tcp.py

It seems that on Cirrus `create_connection` frequently times out on the first try but succeeds on the second try. The default timeout is 60 seconds which seems too much for just checking availability of a port. This change set default timeout to 1 second which helps mitigate the issue of frequent socket timeouts on the first attempt.

Set socket connection timeout

---

CONTRIBUTING.md

Quick fixes in master are no longer okay, as has been discussed at HQ and via Slack.

Change guidelines for quick fixes

---

CMakeLists.txt

Having to manually run the below command after every clone should be not be necessary.
```sh
ln -sf build/compile_commands.json compile_commands.json
```
This is a small, but very useful convenience change.
Open questions:

Link compilation database to project root

---

CMakeLists.txt

The underlying issue is that CMake passes these to llvm-ar, which does
not accept most (all?) linker flags. This commit might require a clean
build.

Explicitly ignore ldflags for static libraries

---

libvast/src/system/exporter.cpp

The exporter crashed for `max_events % table_slice_size == 0`.
Note that there are no integration tests for this crash because the output of `export -n <count>` can be indeterministic.

Fix crash in exporter

---

CHANGELOG.md
CMakeLists.txt

A follow-up to #601: `CMAKE_STATIC_LINKER_FLAGS` are supposed to be passed to the archiver, the name is wrong for backwards compatibility reasons.

Respect the users ARFLAGS

---

CHANGELOG.md
libvast/src/data.cpp
libvast/src/pattern.cpp
libvast/src/type.cpp
libvast/test/data.cpp
libvast/test/pattern.cpp
libvast/vast/pattern.hpp

This PR adds the ability to use operator `==` for patterns on the LHS or RHS. The semantics are the same as the match operator `~`.

Support equality operator for pattern matching

---

CHANGELOG.md
schema/suricata.schema

This changes `suricata.dns.flags` from `count` to `string` and adds support for the new event type `suricata.smtp`.

Update schema for Suricata 5

---

libvast/src/system/accountant.cpp

This commit also rewords the log entry for the accountant heartbeat so it says 'register' instead of 'ingest'.

Show accountant heartbeat for debug only

---

integration/default_set.yaml
integration/reference/manual-1-node/step_03.ref
libvast/src/system/remote_command.cpp

The underlying use case is supporting `vast -N status` to extract statistics from the database without connecting to a node.

Allow all remote commands to work with --node

---

.cirrus.yml
CMakeLists.txt
configure

- Use `rsync` over `scp` for artifact upload
- Reduce number of CPU cores used during artifact build.

Adjust Cirrus Build-Pipeline 

---

.cirrus.yml

Use a while loop to retry the upload via `rsync`.
This addresses the broken pipe problem at the cost of a potentially stalling build pipeline.

Use a while loop to retry rsync

---

.ci/conditional-release.sh
.ci/debian/Dockerfile
.cirrus.yml

Add another cirrus-ci `task` to be run only in case a tag has been pushed. Furthermore, a user must explicitly trigger the release task (either via github or cirrus web interface). The executing script will then check if it was an annotated git tag and build a release accordingly.
The produced artifacts are still stored to, and retrieved from, the `mule` server via `ssh+rsync`.

Use cirrus-ci for github releases

---

scripts/clang-build-analyzer

**Edit:** The target of this PR has changed from doing the improvements to adding the scaffolding needed for build performance analysis. I have changed the labels and title accordingly.
<hr>
We need to work on improving the compilation speed and reducing its memory usage so we get less seemingly random failures in our continuous integration. This is a long term goal.
Obvious improvements that we can implement:
- Reduce template instantiations by short-circuiting conjunctions and disjunctions with `std::conjunction<...>` and `std::disjuction<...>`.
- Use `extern template` for common template instantiations (may require LTO—is this a problem?).
- Use spdlog over CAF for logging (unlikely to happen in the scope of this PR).
<details>
<summary>Click to expand time trace analysis …

Add script for easier compilation/build performance analysis

---

RELEASING.md

Update the documentation of the release workflow.
At the same time, this is a proposal for how we could format and formulate all our documentation / guides in the main repo.

Document new releasing workflow

---

lgtm.yaml

LGTM integrates with github checks (see also this PR's checks). However, so far it does not analyse C++. That is because we need a custom extraction step, which is just introduced with this branch - and hence not enabled on the main repository.
This PR will enable C++ analysis on master.

Add continuous security analysis

---

lgtm.yml

Classify the `aux` folder as library code. `library` is a reserved keyword to exclude code.
https://lgtm.com/help/lgtm/file-classification

Exclude aux folder from LGTM analysis

---

.ci/scripts/build-target

Always expands configure flags, which is necessary when multiple flags are used.

Always expand configure flags

---

CHANGELOG.md
libvast/src/error.cpp
libvast/src/system/importer.cpp
libvast/src/system/pivot_command.cpp
libvast/src/system/sink_command.cpp
libvast/src/system/source_command.cpp
libvast/src/system/spawn_archive.cpp
libvast/src/system/spawn_consensus.cpp
libvast/src/system/spawn_importer.cpp
libvast/src/system/spawn_index.cpp
libvast/src/system/tracker.cpp
libvast/test/error.cpp
libvast/test/system/exporter.cpp
libvast/test/system/importer.cpp
libvast/vast/concept/printable/vast/json.hpp
libvast/vast/detail/array.hpp
libvast/vast/error.hpp
libvast/vast/system/atoms.hpp
libvast/vast/system/importer.hpp
libvast/vast/system/node.hpp
libvast/vast/system/node_control.hpp
libvast/vast/system/spawn_archive.hpp
libvast/vast/system/spawn_at_node.hpp
libvast/vast/system/spawn_consensus.hpp
libvast/vast/system/spawn_index.hpp

The IMPORTER used to be set up with a 2-step initialization process. Some necessary parameters were passed at the call to `spawn` and others are supplied by message from the TRACKER. This PR moves all essential parameters to the spawning invocation.
Additionally, this PR factors the logic of retrieving NODE components into the dedicated functions `get_component(node_actor*)` and `get_node_component(scoped_actor&, actor)` to further decouple the TRACKER from the other actors (it is an implementation detail of the NODE and should not leak through the interface).
TODO:

Refactor importer initialization

---

libvast/vast/bitvector.hpp
libvast/vast/span.hpp

These were a leftover from the time when span still used a signed size type.

Fix pointless checks

---

libvast/CMakeLists.txt
libvast/test/detail/flat_map.cpp
libvast/vast/detail/flat_map.hpp

We already had a `flat_set` abstraction, but `flat_map` was still missing. This is the missing implementation.

Add flat_map abstraction

---

integration/default_set.yaml

The test is currently failing in a non-deterministic fashion, which is hindering our CI workflow. Because we're not currently working on bgpdump, this PR simply disables the integration test for now.

Disable server-basic-bgpdump integration test

---

.ci/freeBSD/build-local
.ci/macOS/build-local
.ci/scripts/initialize-env
.cirrus.yml

The macOS `build-local` script did not work as intended, due to the usage of the wrong version of `readlink`. 
This PR ensures that `greadlink` from the `coreutils` package is used, if installed.

Fix CI / build-local script for macOS

---

CHANGELOG.md
libvast/vast/system/datagram_source.hpp

The datagram_source actor did not run its heartbeat loop, causing a regression where it looked like the import process was not picking up any data.
Additionally, this changes how warnings about dropped packets (which are to be expected with UDP) are displayed.

Fix datagram source actor not running heartbeat

---

CMakeLists.txt
doc/CMakeLists.txt

When the manpage target was available, but not explicitly built, the install target would fail because it tried to always install the manpage. This change fixes this oversight.
Should we install `md2man-roff` in CI and build the manpage using `cmake --build … --target man` right before the targets package or install?

Install manpage only when built

---

libvast/src/default_table_slice.cpp

The default table slice comes with a generator function to create slices with defaulted values for testing, this function does not need to check for success of every add because the layout and data are generated from the same source of truth.

Suppress a false positive warning

---

libvast/vast/detail/bit_cast.hpp

This is a non-constexpr clone of the std::bit_cast that ships with C++20, which is needed for properly punning types (e.g., instead of using reinterpret_cast to convert a stream buffer to the desired record type).

Add bit_cast helper function

---

libvast/src/command.cpp
libvast/src/error.cpp
libvast/src/system/application.cpp
libvast/vast/error.hpp

This PR also changes the option `--config-file` to `--config`.

Exit with an error code if command parsing fails

---

.github/workflows/vast.yml

Do not upload artifacts for all branches, but instead only for master builds.

Restrict S3 upload to master

---

.github/workflows/vast.yml

Turns out JSON files that do not contain `null` are valid Python files.

Ignore JSON files for Black

---

integration/default_set.yaml
integration/integration.py
integration/vast.conf

With this change, CAF logs (most notably `caf_flow` logs) are no longer disabled for integration tests. Some failures will now be easier to debug than before (e.g., https://github.com/tenzir/vast/runs/336745938).

Disable component blacklist in integration tests

---

CMakeLists.txt

The variable ARROW_INCLUDE_DIRECTORIES no longer exists. We actually use
the right one (ARROW_INCLUDE_DIR) internally already when extending the
include paths.

Fix Apache Arrow build summary

---

.github/workflows/vast.yml

Install clang-format for the `style` CI step.

Fix clang-format step in style-check CI

---

README.md

To be merged once LGTM deploys their fix for false classification of SFINAE in our code: https://github.com/Semmle/ql/issues/2382

Update LGTM badge in VAST readme

---

CHANGELOG.md
CMakeLists.txt
scripts/freebsd-rc-vast

This PR adds an `rc.d` script that facilitates running VAST on FreeBSD.

Add FreeBSD rc.d script

---

CMakeLists.txt
scripts/corelight-cat

This script demultiples the multiple connections a Corelight sensor opens when exporting logs via TCP.

Add script to demultiplex Corelight sensor data

---

CMakeLists.txt

For CCache users, we should relocate debug information to a common prefix to speed up rebuilds from a different path, e.g., when using `git-worktree`.
The cost of rewriting debug info paths is relatively low, so I think this should be on by default.

Relocate debug information to a common prefix

---

INSTALLATION.md

When installing via Homebrew, this is the resulting launchd configuration.
```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
<key>Label</key>
<string>homebrew.mxcl.vast</string>
<key>ProgramArguments</key>
<array>
<string>/usr/local/opt/vast/bin/vast</string>
<string>start</string>
</array>
<key>ProcessType</key>
<string>Interactive</string>
<key>RunAtLoad</key>
<true/>
<key>WorkingDirectory</key>
<string>/usr/local/var/vast</string>
<key>StandardOutPath</key>
<string>/usr/local/var/log/vast.log</string>
<key>StandardErrorPath</key>
<string>/usr/local/var/log/vast.log</string>
</dict>
</plist>
```

Document installation on macOS

---

CMakeLists.txt

The CMake `project` macro overwrites the PROJECT_VERSION* variables and prints a warning if they were set beforehand. This happens in our sub projects but is safe to be silenced.

Avoid CMake warning because of policy 48

---

libvast/CMakeLists.txt

From https://cmake.org/cmake/help/latest/command/target_include_directories.html
>  If `SYSTEM` is specified, the compiler will be told the directories are meant as system include directories on some platforms (signalling this setting might achieve effects such as the compiler skipping warnings, or these fixed-install system files not being considered in dependency calculations - see compiler docs).

Silence warnings from included Arrow headers

---

libvast/vast/concept/parseable/core/repeat.hpp

The parameters `min` and `max` don't necessarily need to be of the same type. I've noticed this restraint when trying something like this: `rep(p, 1, max_as_uint16)`, which failed to compile.

Allow different integral types in repeat parser

---

libvast/src/system/count_command.cpp
libvast/src/system/pivot_command.cpp
libvast/src/system/sink_command.cpp
libvast/src/system/source_command.cpp
libvast/src/system/start_command.cpp
libvast/vast/defaults.hpp
libvast/vast/system/signal_monitor.hpp

This PR moves the default signal watch interval of 750ms that was used by each of `{count,pivot,sink,source,start}_command` into the defaults header.

Refactor hard-coded constant for signal monitor.

---

libvast/src/system/pivot_command.cpp
libvast/src/system/sink_command.cpp
libvast/src/system/source_command.cpp
libvast/vast/system/node_control.hpp
libvast/vast/system/tracker.hpp

* Rename get_node_component -> get_node_components
* Change arguments to accept the desired actors as
strings instead of atoms.
* Change return type to use caf::actor instead of
caf::expected<caf::actor> to save one level of
error unwrapping on the call site, as actor is
already nullable.

Refactor interface of system::get_node_component

---

aux/broker/CMakeLists.txt
libvast/src/segment.cpp

Two changes here:
- We silence the warnings from Broker.
- We actually compare the version and magic stored in the segment header, instead of using an expression that always evaluated to false.

Fix warnings from Clang 10

---

libvast/src/column_index.cpp
libvast/src/meta_index.cpp
libvast/src/synopsis.cpp
libvast/src/system/index.cpp
libvast/src/system/indexer.cpp
libvast/src/system/spawn_indexer.cpp
libvast/src/value_index.cpp
libvast/src/value_index_factory.cpp
libvast/test/column_index.cpp
libvast/test/hash_index.cpp
libvast/test/synopsis.cpp
libvast/test/system/indexer.cpp
libvast/test/system/indexer_stage_driver.cpp
libvast/test/value_index.cpp
libvast/vast/aliases.hpp
libvast/vast/column_index.hpp
libvast/vast/concept/parseable/vast/base.hpp
libvast/vast/defaults.hpp
libvast/vast/detail/bit.hpp
libvast/vast/hash_index.hpp
libvast/vast/meta_index.hpp
libvast/vast/synopsis_factory.hpp
libvast/vast/system/indexer.hpp
libvast/vast/system/spawn_indexer.hpp
libvast/vast/value_index.hpp
libvast/vast/value_index_factory.hpp
libvast_test/src/dummy_index.cpp
libvast_test/src/table_slices.cpp

This PR adds the ability to pass arbitrary context into the value index factory, which allows for evaluating runtime parameters to select the appropriate index implementation. In particular, we pass in the partition size to automatically deduce the number of bytes for our optimized hash index for strings.

Support runtime options in value index factory

---

CHANGELOG.md
libvast/src/value_index_factory.cpp
libvast/test/hash_index.cpp

This makes it possible to use `#index=hash` on all data types.

Generalize hash indexes to all data types

---

libvast/vast/value_index.hpp

This was missed in #724, since the bug was introduced on master after branching that PR off.

Fix check whether expected<T> holds a value

---

.github/workflows/vast.yml
RELEASING.md

After GitHub release has been written + published manually, the action will pick it up and publish artifacts to it

Switch to manual release workflow

---

libvast/src/json.cpp
libvast/src/system/version_command.cpp
libvast/test/json.cpp
libvast/vast/json.hpp
libvast/vast/system/version_command.hpp

Here is the output of `vast version` after these changes:
```
{
"VAST": "0.2-398-ga5bf2082-dirty",
"CAF": "0.17.3",
"ARROW": "0.15.1",
"PCAP": "libpcap version 1.9.1 (with TPACKET_V3)"
}
```

Extend the output of vast version

---

libvast/src/format/csv.cpp
libvast/test/span.cpp

Fix two warnings, one about a possibly unused variables 'ws'
and clang-tidy warning about calling a method on a moved-from
object.

Fix warnings in CSV tests

---

libvast/src/format/pcap.cpp
schema/argus.schema
schema/suricata.schema

@mavam there are likely a lot I've missed, this was just from a quick grep in the source tree. We can always add these later on when we encounter them. For some fields we can obviously restrict the size of the hash as well, but that'd require an in-depth investigation into the fields allowed contents.
For the schema files, I've used mostly `:g/^\s\+field_name:/s/,\?$/ #index=hash&` to do the replacement.

Annotate schemas with #index=hash attribute

---

.github/workflows/vast.yml

- Upload failed integration test artifacts only when the integration test step caused the failure
- Upload build artifacts / assets to GCS for `master` *and* Git tags

Refine Artifact Uploads in CI

---

libvast/vast/coder.hpp
libvast/vast/concept/convertible/to.hpp
libvast/vast/concept/hashable/type_erased_hasher.hpp
libvast/vast/concept/parseable/core/parser.hpp
libvast/vast/concept/parseable/core/rule.hpp
libvast/vast/concept/parseable/core/sequence_choice.hpp
libvast/vast/concept/parseable/core/to_parser.hpp
libvast/vast/concept/printable/detail/as_printer.hpp
libvast/vast/concept/printable/string/literal.hpp
libvast/vast/concept/printable/vast/expression.hpp
libvast/vast/detail/bit_cast.hpp
libvast/vast/detail/operators.hpp
libvast/vast/detail/type_traits.hpp
libvast/vast/detail/varbyte.hpp
libvast/vast/detail/zigzag.hpp

Template machinery short-circuits only when a backtracking step is done. This is why C++17 ships `std::conjunction`, `std::disjunction`, and `std::negation`.
This change makes VAST compile faster, because less template instantiations are needed.
I've only done this on the basis of a grep for `enable_if` so far.

Use short-circuiting in template metaprogramming 

---

libvast/test/arrow_table_slice.cpp
libvast/test/command.cpp
libvast/test/format/pcap.cpp
libvast/test/view.cpp
libvast_test/vast/test/test.hpp

The `CHECK_EQUAL()` macro has a lot of additional behavior inherited from caf, most significantly the ability to compare types that don't define `operator==` (returning a configurable default value), and the automatic unboxing of variant types.
This PR simplifies the behavior by having `CHECK_EQUAL(x, y)` return `true` iff `x == y`.

Make `CHECK_EQUAL()` behave the same as `operator==`

---

CHANGELOG.md
libvast/src/system/application.cpp
libvast/src/system/spawn_exporter.cpp

This PR removes the `--historical` flag, since it's just the default and doesn't actually change anything.

Remove default option for historical queries

---

libvast/CMakeLists.txt

Due to a quirk in CTest, the `test` target is not a real target, and can not be used with `add_dependencies()` the workaround is to add a dedicated test that builds `vast-test` acts as a custom dependency for all other tests.
Caveat: The generator tools do not inherit the setting from the outer context, so both `Ninja` and `GNU Makefiles` build the dependencies of `test` with their default core counts, which are `NCORES + 2` and `1` respectively!

Let test target depend on the vast-test executable

---

.github/workflows/vast.yml

Trigger `pull_request` uses the last merge commit on the GitHub ref branch as `GITHUB_SHA`: https://help.github.com/en/actions/reference/events-that-trigger-workflows#pull-request-event-pull_request
- refine CI trigger to act on push to master and on pull_request
- use GitHub action checkout v2

Use checkout v2, refine workflow trigger

---

.github/workflows/vast.yml

When running the fetch step in our github action workflow
git fetch --depth=1 origin +refs/tags/*:refs/tags/*
we are *replacing* all existing commits that are tagged on the
remote with shallow commits.
For some reason that is not yet understood, this breaks the
output of `git describe` on the vast repository, calculating
an incorrect number of commits since the last tag.

Do not use shallow commits when fetching tags

---

.github/workflows/vast.yml

We have to set and resolve strings in different ways, which we do now.

Use correct string syntax for output referencing

---

libvast/src/chunk.cpp
libvast/src/filesystem.cpp
libvast/src/system/version_command.cpp
libvast/src/uuid.cpp
libvast/test/chunk.cpp
libvast/test/format/zeek.cpp
libvast/test/uuid.cpp
libvast/vast/chunk.hpp
libvast/vast/concept/parseable/vast/uuid.hpp
libvast/vast/concept/printable/core/choice.hpp
libvast/vast/concept/printable/core/operators.hpp
libvast/vast/concept/printable/core/sequence.hpp
libvast/vast/concept/printable/detail/as_printer.hpp
libvast/vast/concept/printable/vast/uuid.hpp
libvast/vast/detail/coding.hpp
libvast/vast/filesystem.hpp
libvast/vast/uuid.hpp

- Make printers `constexpr`
- Add standard-like function `file_size`
- Rewrite `uuid` as byte sequence
- Make `chunk` more flexible
- Fix some warnings

A potpourri of small tweaks

---

CHANGELOG.md
libvast/src/command.cpp
libvast/src/system/application.cpp
libvast/src/system/connect_to_node.cpp
libvast/src/system/spawn_node.cpp
libvast/vast/defaults.hpp
vast.conf

It's currently not possible to have different directories for the persistent state and the log files. 
The `--directory` option is the only way to specify the directory for all state. Inside this dir, VAST creates a directory log that contains all ASCII logs.
This PR adds a new option named `--log-directory` that optionally allows setting the directory for the logs only.

Allow for separating persistent state and log directories

---

CHANGELOG.md
libvast/src/format/pcap.cpp
libvast/src/format/zeek.cpp
schema/argus.schema
schema/suricata.schema

This partially reverts commit 9f656e800283a8fae2ed466678e56b2828049d5c.
When benchmarking, we discovered that the hash index introduces
a huge performance regression for the `vast import suricata`
command, due to a variant type being used as a key in a `flat_map`.
Therefore, we're removing the hash indices until the underlying
problem is fixed.

Revert "Annotate schemas with #index=hash"

---

libvast/vast/concept/parseable/core/repeat.hpp
libvast/vast/concept/parseable/core/skip.hpp

When invoked with a prvalue or an xvalue, the `parsers::rep` and `parsers::skip` wrappers were causing a stack-use-after-scope error from the address sanitizer.  The expected behavior is that integral types are stored by value instead of by const lvalue reference.

Fix stack-use-after-scope in rep and skip parsers

---

libvast/src/system/pivoter.cpp

NetFlow currently is a proprietary feature. Until the planned generalization of pivot, this hardcoded check will have to do.

Enable pivoting for NetFlow records

---

CHANGELOG.md
libvast/src/system/exporter.cpp
libvast/src/system/sink_command.cpp

Before this change, stopping a continuous export process with <kbd>ctrl</kbd> + <kbd>c</kbd> produced this error message:
```
exporter got error during streaming:  none
```

Fix user shutdown handling for continuous exports

---

CHANGELOG.md
libvast/src/system/application.cpp
libvast/src/system/configuration.cpp

Fixes a regression introduced in #705 that caused other `-c` short options not to work.

Remove -c short option for setting config file

---

CMakeLists.txt

Before this change, integration tests failed with an unintelligible error when `jq` was unavailable. This is a quick fix that works only when running the integration tests through the build target integration.

Fail integration tests early if jq is not in PATH

---

integration/default_set.yaml
libvast/vast/concept/parseable/vast/expression.hpp

`parsers::eoi` doesn't seem to play nicely with the rule parser in all build configurations. While fixing that, I've uncovered an issue in our `integration.py` script, which I've worked around for now.

Fix recently introduced bug in eoi check for expression parser

---

CHANGELOG.md
libvast/src/system/configuration.cpp
libvast/vast/system/configuration.hpp

The # made it really awkward to use, since it starts a comment in most shells.
```sh
vast '--caf#scheduler.max-threads=1' start
vast --caf.scheduler.max-threads=1 start
```

Replace 'caf#' prefix for CAF options with 'caf.'

---

vast.conf

Note that this excludes the `middleman` settings category, as it is likely to cause issues when changed by users.
```
middleman = {
; app-identifiers =
; network-backend =
; max-consecutive-reads =
; heartbeat-interval =
; cached-udp-buffers =
; max-pending-msgs =
; workers =
}
```

Reflect CAF config options in example vast.conf

---

aux/broker/CMakeLists.txt

This fixes an issue where `zeek-to-vast` failed to build for Zeek 3.1.

Update Broker to v1.3.1

---

libvast/src/fbs/utils.cpp
libvast/src/segment.cpp
libvast/src/segment_builder.cpp
libvast/src/segment_store.cpp
libvast/vast/fbs/segment.fbs
libvast/vast/fbs/utils.hpp
libvast/vast/segment_builder.hpp
libvast/vast/segment_store.hpp

This PR is a followup to #727 and ports the segment to store to use flatbuffers. Since the change involved actually changing the segment flatbuffer schema, the store is now completely stateless and initializes runtime state on startup.

Port segment store to flatbuffers

---

libvast/src/system/archive.cpp
libvast/src/system/index.cpp

~Blocked by #787. As is this is printing to INFO, which makes a lot of noise.~
For archive this is just the rate, for the index it's the minimum we print. All the other rates for the index are still in the accountant, this just makes it a lot more convenient to get them.

Print index/archive event handling rates for VERBOSE log level

---

CHANGELOG.md
libvast/src/command.cpp
libvast/src/logger.cpp
libvast/src/system/application.cpp
libvast/src/system/default_configuration.cpp
libvast/vast/defaults.hpp
libvast/vast/logger.hpp
vast.conf

Set file verbosity to 'quiet' by default, and do not create a log file and log directory when file verbosity is set to 'quiet'.
Set file verbosity to 'debug' by default only for the 'vast start' subcommand.

Restrict log file creation to 'vast start'

---

libvast/src/system/connect_to_node.cpp
libvast/src/system/node.cpp
libvast/vast/defaults.hpp

I'm not sure if this should be made configurable for now. 10s seems to be a reasonable value, and for decent usability 10s already feels like an infinite wait time.
For some of these, we might also want to print an error if the request timed out. Ultimately this is what motivated this change.

Set a default request timeout

---

libvast/vast/system/reader_command.hpp

Prior to this change, the message was printed only after the reader was successfully initialized. When mistakenly starting VAST configured to read input from stdin, but not actually providing any data over stdin, it often looked like VAST was hanging.

Print a message when expecting input

---

libvast/src/system/evaluator.cpp

This is _really_ noisy for large databases. I've had this print a few thousand lines for just 10 GB worth of data in the archive. This makes it much easier to look at the logs.

Reduce noise from evaluator hits debug log

---

libvast/src/command.cpp

This fixes a bug in our helptexts.
```
❯ vast export help
usage: export [<parameters>] <command>
parameters:
[-h | -? | --help=] <boolean>  prints the help text
[-c | --continuous=] <boolean>  marks a query as continuous
[-u | --unified=] <boolean>    marks a query as unified
[-n | --max-events=] <uint64>  maximum number of results
[-r | --read=] <string>        path for reading the query
```
```
❯ vast export help
usage: export [<parameters>] <command>
parameters:
[-h | -? | --help]             prints the help text
[-c | --continuous]            marks a query as continuous
[-u | --unified]               marks a query as unified
[-n | --max-events=] <uint64>  maximum number of results
[-r | --read=] <string>        path for reading the query
```

Improve helptext formatting for boolean options

---

libvast/src/error.cpp
libvast/test/error.cpp
libvast/vast/error.hpp

This will be used by some of the new matcher features in vast-pro

Add new error code for "out of memory"

---

CMakeLists.txt

`openssl@1.0`, which was aliased to `openssl`, was recently removed from Homebrew. It was usually installed into `${HOMEBREW_PREFIX}/openssl`. There's now only `openssl@1.1`, which is now aliased to `openssl@1.1`, but  still installed into `${HOMEBREW_PREFIX}/openssl@1.1`. 
This PR circumvents this whole mess by just using `brew` to get the prefix directly.

Use Homebrew to locate OpenSSL on macOS

---

CHANGELOG.md
libvast/src/system/start_command.cpp
libvast/vast/defaults.hpp

We dont want to expose vast to the network without the user explicitly setting it up that way.

Change default listen address to 'localhost'

---

CHANGELOG.md
libvast/src/format/csv.cpp
libvast/src/format/syslog.cpp
libvast/src/format/zeek.cpp
libvast/vast/defaults.hpp
libvast/vast/format/json.hpp
libvast/vast/system/source.hpp

This fixes a bug that caused continuous Suricata imports to possibly hang.

Use line reader timeout

---

CMakeLists.txt

E.g., `sh build/integration_Debug.sh -u` can now be used to update reference values. Due to technical reasons, passthrough using the build target `integration` is not possible with CMake.

Allow for passing parameters to integration tests

---

CHANGELOG.md
libvast/src/expression.cpp
libvast/src/system/counter.cpp
libvast/src/system/exporter.cpp
libvast/test/system/exporter.cpp

Removed an assertion that checked an expression could
not become 'none_t' after running the type resolver on
it.
Since the type resolver is using 'none_t' as a return value
to signal that it was not able to resolve a type, this
condition should not be an error, let alone an assertion
failure.
For example, an expression like 'foo.bar = "baz"' would always
return 'none' if the type to be matched against was not called
foo or had no field called bar.

Remove assertion from expression tailoring

---

CHANGELOG.md
libvast/CMakeLists.txt
libvast/src/system/application.cpp
libvast/src/system/connect_to_node.cpp
libvast/src/system/node.cpp
libvast/src/system/start_command.cpp
libvast/src/system/stop_command.cpp
libvast/vast/system/stop_command.hpp

The command previously returned regardless of whether it succeeded.

Make stop command blocking and return properly

---

libvast/src/detail/fdinbuf.cpp

We need to check `revents` for POLLHUP, not `events`.
NOTE: Probably the whole check could be simplified to `res <= 0`, but the current logic should be correct as well and I didn't want to risk introducing a bug because I'm overlooking something.

Fix event check in fdinbuf

---

scripts/index-du

This aliases find to gfind if it is available to explicitly use the find from gnu-findutils.

Make index-du script work on FreeBSD and macOS

---

libvast/src/command.cpp

This fixes a bug that caused the longest non-boolean parameter in the helptext to be misaligned by one space.

Fix alignment in paramaters helptext

---

libvast/src/meta_index.cpp
libvast/src/qualified_record_field.cpp
libvast/src/system/index.cpp
libvast/src/system/indexer_downstream_manager.cpp
libvast/src/system/partition.cpp
libvast/test/meta_index.cpp
libvast/vast/meta_index.hpp
libvast/vast/qualified_record_field.hpp
libvast_test/src/table_slices.cpp

The recent index refactoring flattened the partition layout. However, the old hierarchical structure still existed in the meta index. This commit re-synchronizes the architecture.

Refactor meta index

---

CHANGELOG.md
libvast/src/detail/line_range.cpp
libvast/test/format/csv.cpp
libvast/vast/detail/getline_generic.hpp

Support both Unix-, Windows- and Mac-style line endings
for all input formats, either uniformly or mixed.
NOTE: I'd actually like to run benchmarks for this change before merging, because I'm not sure if the libc-readline has some "magic sauce" that makes it far more performant.

Support \r\n-style newlines in VAST

---

Dockerfile
Dockerfile_prebuilt

- Use `vast` system user
- Use `/var/db/vast` as directory path
This PR aligns our `Docker` deployments with our `systemd` deployments.

Unify usernames and directories in deployment systems

---

CHANGELOG.md
integration/default_set.yaml
integration/reference/server-zeek-conn-log/step_06.ref
libvast/src/system/accountant.cpp
libvast/src/system/application.cpp
libvast/src/system/spawn_node.cpp
scripts/vast-du
vast.conf

We are currently using these names:
|Name|Usage|
|-|-|
|accountant|Name of the actor|
|accounting|Name of the feature that can be disabled|
|vast.statistics|Name of the layout of the produced event|
|metrics|Name of the documentation page|
This PR unifies these names to `accountant` for the actor itself and `metrics` for anything user-facing.

Rename statistics event to metrics

---

libvast/test/time.cpp
libvast/vast/concept/parseable/vast/time.hpp

@0ortmann I have verified this to fix the Sysmon import with the sample you provided.
```
❯ vast -N status | jq '.node.index.statistics.layouts'
{
"sysmon.RegistryEventObjectCreateAndDelete": {
"count": 3
}
}
```

Allow spaces as timestamp separators

---

systemd/README.md
systemd/vast.conf

To be consistent with Linux systems we should use `/var/log/vast` as log directory.
This PR changes the used log directory of the `systemd` service and updates the README.

Fix log directory

---

CHANGELOG.md
libvast/src/system/read_query.cpp

This consists of two commits:
1) Print a message when VAST is waiting for the user to input a query
2) Print a deprecation warning when a query is spread over several command line arguments.

UX improvements for `read_query()`

---

libvast/src/system/read_query.cpp

Warn only when spreading query over multiple args

---

.github/workflows/vast.yml
pyvast/pyvast/test_vast.py
pyvast/pyvast/vast.py
pyvast/setup.py

PyVAST could not handle VAST subcommands if they contained a dash. For example, `vast matcher ioc-remove --name=foo` could not be expressed with PyVAST.
This PR changes PyVAST to accept underscores in function names and replace them with dashes. With this change one can write `vast.matcher().ioc_remove(name="foo")`.

Handle subcommands with dashes in PyVAST

---

libvast/vast/detail/escapers.hpp

Noticed after compiling with gcc 10.1 for the first time.

Fix odr violations in escapers header

---

CHANGELOG.md
libvast/src/system/configuration.cpp

The configuration file is now looked at in the following order:
- Specified via `--config=path/to/vast.conf`
- `vast.conf` in current working directory
- `${INSTALL_PREFIX}/etc/vast/vast.conf`
- `/etc/vast/vast.conf`

Support /etc/vast/vast.conf as global config

---

libvast/src/segment_store.cpp

Even when the archive status report timed out, the node kept running this non-interruptible loop. For large archives, this causes the user to experience a hang, even after the status command returned successfully.

Remove segment store status that timed out regularly

---

libvast/test/detail/flat_map.cpp
libvast/vast/detail/vector_map.hpp
libvast/vast/format/json.hpp

Using operator[] on a map may create a new element.
In a `vector_map`, this new element was always appended
to the end of the vector, ignoring the insertion order
assumed by the policy.

Fix insert position in flat_map's operator[]

---

cmake/Findjemalloc.cmake
libvast/CMakeLists.txt

This is necessary because if vast links to a static libarrow that wants to link to its own vendored jemalloc build, which uses the name `jemalloc::jemalloc`. We rename ours to `jemalloc::jemalloc_` to get around the problem. This can be reverted once https://issues.apache.org/jira/browse/ARROW-7605 is resolved.

Adjust jemalloc imported target name

---

.github/workflows/vast.yml
systemd/vast.service

We faced an issue where the `PrivateUsers` setting caused a `NAMESPACE` error (code `226`) on `systemd` version `241` when multiple services had been started simultaneously. 
The removal of this setting fixed the issue.
(This also seems to be resolved with `systemd` version `245`. At least on Arch Linux. However, `241` is still used by many other distros, i.e., Debian Buster).

Allow multiple vast services to run as vast user

---

libvast/test/format/zeek.cpp

The default timeout has recently been raised to 10s, which is unnecessarily high for testing a timeout.

Reduce read-timeout in tests

---

CMakeLists.txt

Before this change, `./configure --build-dir=../build` failed.

Allow for builds outside of the repository

---

CMakeLists.txt
configure
libvast/test/parseable.cpp
libvast/vast/system/import_command.hpp

This enables `-Werror` for all warnings except `-Wdeprecated` (Clang) / `-Wdeprecated-declarations` (GCC)  in CI.

Treat warnings as errors in CI

---

configure

The helptext of the configure script lists the possible values of the log-level option to be all lowercase, but CMake expects them to be all uppercase. Let's simply transform the argument so it is all uppercase.

Allow for configure log-level value to be lowercase

---

libvast/src/schema.cpp
libvast/vast/schema.hpp
vast/vast.cpp

- An invalid schema file no longer causes VAST not to start
- The filename of an invalid schema is printed along with the proper error
Example output after breaking the bundled `suricata.schema`:
```
❯ vast start
2020-06-19T11:46:07.612 load_schema !! parse_error "/Users/dominiklohmann/Desktop/Tenzir/vast/build/share/vast/schema/suricata.schema"
2020-06-19T11:46:07.629 VAST node is listening on localhost:42000
```
We're still far off from getting proper error messages for the schema parser itself, as that's a bigger refactoring of parseable, but this should be a good starting point for users when something's wrong with their schemas.

Improve schema error handling

---

configure

Additionally, this commit removes an unused `VAST_USE_TCMALLOC` variable that was supposed to be removed in an earlier PR when removing the support for tcmalloc.

Respect global user env CMAKE_* variables

---

CHANGELOG.md
libvast/src/defaults.cpp
libvast/src/system/accountant.cpp
libvast/src/system/application.cpp
libvast/src/system/configuration.cpp
libvast/src/system/infer_command.cpp
libvast/src/system/spawn_source.cpp
libvast/src/table_slice.cpp
libvast/test/format/csv.cpp
libvast/test/format/json.cpp
libvast/test/format/pcap.cpp
libvast/test/format/syslog.cpp
libvast/test/format/zeek.cpp
libvast/test/system/datagram_source.cpp
libvast/test/system/importer.cpp
libvast/test/system/pivoter.cpp
libvast/test/system/source.cpp
libvast/vast/defaults.hpp
libvast/vast/system/import_command.hpp
libvast/vast/system/source.hpp
libvast_test/src/events.cpp
tools/gen-vast-slices/gen-vast-slices.cpp
vast.conf

We have a `table-slice-type` option available as both `system.table-slice-type` and `import.table-slice-type`. This is quite confusing. Let's make it a single option just like `import.table-slice-type`.

Use just a single option for setting the table slice type

---

.github/workflows/vast.yml
CMakeLists.txt
Dockerfile
Dockerfile_prebuilt
libvast/CMakeLists.txt
libvast/src/system/accountant.cpp
libvast/src/system/index.cpp
libvast/src/system/indexer.cpp
libvast/src/system/partition.cpp
libvast/src/system/spawn_indexer.cpp
libvast/test/system/indexer.cpp
libvast/test/system/indexer_stage_driver.cpp
libvast/vast/config.hpp.in
libvast/vast/defaults.hpp
libvast/vast/fwd.hpp
libvast/vast/system/index.hpp
libvast/vast/system/indexer.hpp
libvast/vast/system/instrumentation.hpp
libvast/vast/system/partition.hpp
libvast/vast/system/spawn_indexer.hpp
libvast_test/src/dummy_index.cpp

Make each indexer submit its own measurements to the accountant, as opposed to passing around pointers to atomic measurements to create a centralized report from the index.

Move measurement code into indexers

---

.dockerignore
Dockerfile
Dockerfile_prebuilt
systemd/README.md
systemd/vast.service

Vast should use the configuration file from `/etc/vast` on default. This PR adds the config to that location and starts `vast` normally for `systemd` / `Docker`

Use configuration from /etc/vast

---

CMakeLists.txt

We enable and disable some warnings that don't exist on older versions of compilers that we still want to support. An easy workaround is silencing the warnings about unknown warning options.
I noticed this when running `docker build .` for this repository, which uses GCC 8.

Disable warnings for unknown warnings

---

libvast/vast/system/datagram_source.hpp
libvast/vast/system/import_command.hpp
libvast/vast/system/make_source.hpp
libvast/vast/system/source.hpp
libvast/vast/system/spawn_source.hpp

This is essentially a bugfix; the configuration for sources and datagram sources deviated from the configuration for remotely spawning sources a while back, since the code was untested and took a different code path for configuration.  This change makes remotely spawning a source take the same code path as spawning a local source and thus enables remotely spawning datagram sources.
I don't yet have a good solution for printing the reader name in the source shutdown functor, so if anyone's got an idea for that I'd greatly appreciate that.

Unify source configuration

---

.github/workflows/vast.yaml

We want every push to master to cause an artifact to be uploaded to GCS, so we must run the workflow for _all_ changes on master. The restrictions still apply within PRs.

Always trigger VAST CI workflow on master pushes

---

.github/workflows/static-binary.yaml

With this PR the static binary is additionally uploaded to a public GCS bucket. That enables non-GitHub-users to download the artifact. The link for this upload is: https://storage.googleapis.com/tenzir-public-data/vast-static-builds/vast-2020.06.25-128-gaa76128c-static.tar.gz

Upload static binaries to GCloud

---

libvast/src/system/importer.cpp

This fixes a bug that makes it look like the available IDs counter has overflown. The underlying limitation is that we transport this information using `caf::settings`, which is a `caf::dictionary` of `caf::config_value`s, which can only represent signed 64 bit integers.

Print importer ID space using strings

---

.github/workflows/jupyter.yaml
.github/workflows/pyvast.yaml
.github/workflows/static-binary.yaml
.github/workflows/style-check.yaml
.github/workflows/vast-docker.yaml
.github/workflows/vast.yaml
Dockerfile
Dockerfile_prebuilt

This PR elevates the Ubuntu version used both in CI and in our Dockerfiles to 20.04.
A recent merge to master (https://github.com/tenzir/vast/pull/972) has corrupted the Docker build due to a missing dependency for `flatbuffers`. This branch also covers the fix of the current master.

Update GitHub workflows to run on Ubuntu 20.04

---

libvast/vast/fwd.hpp

Add the 'inline' qualifier to the atom instances
that are generated by the VAST_CAF_ATOM_ALIAS()
macro, to avoid odr-violations.
Add the [[maybe_unused]] attribute to prevent warnings
for unused variables defined in the current translation
unit which are emitted by some compilers.
NOTE: Technically changes along the same lines would also be required in the caf header, but the files have already changed upstream, so I'm not sure its worth bothering with that.

Add 'inline' qualifier to VAST atom aliases

---

CHANGELOG.md
CMakeLists.txt
libvast/src/system/application.cpp
libvast/src/system/configuration.cpp
libvast/vast/config.hpp.in
vast.conf
vast/vast.cpp

This PR removes the baking to the install prefix from the binary.
- The path to the lowest priority schema files was already determined relative to the binary location at runtime. Now the help message properly reflects that.
- The fallback path to `vast.conf` is now also determined by the runtime location.
This fixes 2 bugs: 
1. `VAST_RELOCATABLE_INSTALL` was not really relocatable because the paths above would not update on relocations.
2. The `CMAKE_INSTALL_PREFIX` leaked into the static binary, which is relocatable by definition.
In addition, this PR also adds `/etc/vast/schema` to the schema file lookup path.

Improve handling of the default schema paths

---

CHANGELOG.md
libvast/CMakeLists.txt
libvast/src/detail/pid_file.cpp
libvast/src/system/spawn_node.cpp
libvast/vast/detail/pid_file.hpp

To ensure that only a single server process can write into a given DB directory, we now write a PID lock file when we start VAST.

Protect DB directory with PID lock

---

doc/cli/vast-explore.md
doc/cli/vast-export-arrow.md
doc/cli/vast-export-csv.md
doc/cli/vast-export.md
doc/cli/vast-import-csv.md
doc/cli/vast-import-pcap.md
doc/cli/vast-import-suricata.md
doc/cli/vast-import-syslog.md
doc/cli/vast-import-test.md
doc/cli/vast-import-zeek.md
doc/cli/vast-import.md
doc/cli/vast-infer.md
doc/cli/vast-pivot.md
doc/cli/vast-start.md
doc/cli/vast-status.md
doc/cli/vast-stop.md
doc/cli/vast-version.md
doc/cli/vast.md

Note: This is still heavily work-in-progress, not worth reviewing yet.
Each subcommand currently has a `help` and a `documentation` subcommand. This change adds concrete usage example to _every_ subcommands documentation subcommand.

Add concrete usage examples to docs

---

integration/integration.py

When we pipe data to a `vast import` process (e.g., via gunzip), then it could well be that the VAST process terminates first. Then the upstream process sees a SIGPIPE. That's not a failure, which is we should ignore it.
Concretely: this PR removes this output when running the integration tests:
```
2020-08-07 13:22:28 ERROR    ['gunzip', '-c', '../vast/integration/data/zeek/conn.log.gz'] returned -13
```

Ignore SIGPIPE when waiting on process

---

libvast/src/filesystem.cpp
libvast/vast/filesystem.hpp

The change to "not close by default" was introduced in this commit, I'm not sure if it was intentional or just an oversight.
```
commit c01b22917f3b10fdea6d40ad3d9981dcf36693f3
Author: Matthias Vallentin <vallentin@icir.org>
Date:   Thu May 14 09:39:27 2015 -0700
Fix bugs in filesystem interface
Also, factor more POSIX wrappers.
```

Close file descriptor by default in 'vast::file'

---

nix/broker/source.json
nix/caf/source.json

Update dependencies for the static build after switching to a custom caf upstream.
The changes were generated by running the `nix/update.sh` script.

Update nix dependencies to latest master

---

CHANGELOG.md
libvast/src/system/index.cpp
libvast/vast/system/index.hpp

Don't overwrite the on-disk state if we fail to restore it, since
the newly written state will surely be empty and overwrite the
existing VAST data on disk.

Don't overwrite index state after startup error

---

libvast/src/system/terminator.cpp

Fix two potential segfaults that could happen when passing null actors to `vast::terminate()`

Fix potential segfaults in terminator

---

README.md

It doesn't make sense to show this badge for repository dispatch events, so we show it for push events only now.

Fix the VAST Static README badge

---

CHANGELOG.md
doc/cli/vast-status.md

I overlooked this in the review; we changed to `--detailed` and `--debug` very late yesterday.

Fix mistake in status command helptext

---

scripts/find-hanging-actors

* Match 'caf_flow' instead of 'caf.flow'
* Use exact match for ids (to prevent id 16 matching 163)
* Print all IDs to make it possible to detect id reusage

Fix script to find hanging CAF actors from log file

---

.github/workflows/vast-docker.yaml

We don't currently run the VAST Docker CI workflow for every PR that changes VAST simply because it takes too long. The VAST workflow changing is a strong indication for a change in the build process or required tooling, so we should have the VAST Docker workflow depend on it.

Trigger VAST Docker CI when VAST workflow changes

---

.github/workflows/vast.yaml
CHANGELOG.md
CMakeLists.txt
Dockerfile
configure
libvast/CMakeLists.txt
libvast/src/data.cpp
libvast/test/yaml.cpp
libvast/vast/concept/parseable/vast/yaml.hpp
libvast/vast/data.hpp

To be rebased onto master after #1017 is merged. Ignore everything up to and including 6b4e564.

Add YAML support

---

libvast/src/system/accountant.cpp
libvast/vast/system/accountant.hpp

When pimpl-ing actor states, we must move the actor name from the state impl to the state pimpl.

Fix display of the acccountant actor's name

---

libvast/src/segment.cpp
libvast/src/segment_builder.cpp
libvast/src/segment_store.cpp
libvast/vast/fbs/segment.fbs
libvast/vast/fbs/uuid.fbs
tools/lsvast/lsvast.cpp

**NOTE**: This is changing the binary format of the `Segment` flatbuffer. I'm undecided if its still early enough to sneak that in, or if we should use the opportunity to battle-test our upgrade paths and switch update to `Segment v1`.

Use UUID type in Segment flatbuffer

---

CMakeLists.txt
configure
tools/CMakeLists.txt
tools/lsvast/lsvast.cpp

gcc-8 does not have `std::filesystem` available, so let's just use `vast::filesystem` instead.

Fix lsvast build for gcc-8

---

libvast/src/system/index.cpp

@lava please review if this wording makes sense.
Besides removing unnecessary spaces and rewording, I've also moved the log message from verbose to debug, where I think it belongs.

Improve log message about partition uuids

---

libvast/src/system/index.cpp
libvast/src/system/partition.cpp

Turns out gcc-8 is unable to explicitly capture a variable in a lambda that was implicitly captured in a surrounding lambda if that variable is then only used in an unevaluated context like decltype in the inner lambda.
I verified that this builds as expected by running `docker build . -t vast`.

Fix release builds using gcc-8

---

libvast/src/data.cpp
libvast/src/type.cpp
libvast/test/json.cpp
libvast/vast/json.hpp

This change makes the convert overload from `map` to JSON less generic, i.e. only `std::string` is allowed as key type.

Restrict map to json conversion to string keys

---

libvast/src/system/application.cpp
libvast/src/system/node.cpp
libvast/src/system/spawn_archive.cpp
libvast/vast/system/application.hpp

For most commands, this is for completeness only. For the status and spawn sink commands, this fixes setting configuration options from the vast.yaml file.

Add missing options categories

---

libvast/src/system/get_command.cpp
libvast/src/system/pivot_command.cpp
libvast/src/system/sink_command.cpp
libvast/vast/system/import_command.hpp
libvast/vast/system/node_control.hpp

The first commit in this branch is cherry-picked from #1080, where we noticed that the build was broken for gcc-8 (again). This PR is essentially a better fix for the same issue.

Improve behavior of get_node_components

---

libvast/src/system/partition.cpp
libvast/vast/fbs/utils.hpp

Use the new serialize_bytes/deserialize_bytes convenience functions to simplify the flatbuffer-related code of the partition actor.

Make use of new serialize_bytes convenience function

---

libvast/src/arrow_table_slice_builder.cpp
libvast/src/data.cpp
libvast/src/expression.cpp
libvast/src/meta_index.cpp
libvast/src/msgpack_table_slice.cpp
libvast/src/msgpack_table_slice_builder.cpp
libvast/src/system/configuration.cpp
libvast/src/system/infer_command.cpp
libvast/src/system/partition.cpp
libvast/src/table_slice_builder.cpp
libvast/src/type.cpp
libvast/src/value_index.cpp
libvast/src/view.cpp
libvast/test/msgpack.cpp
libvast/test/value_index.cpp
libvast/vast/concept/printable/vast/data.hpp
libvast/vast/concept/printable/vast/view.hpp
libvast/vast/detail/overload.hpp
libvast/vast/hash_index.hpp
libvast/vast/json.hpp
libvast/vast/msgpack.hpp
libvast/vast/value_index.hpp
tools/zeek-to-vast/zeek-to-vast.cpp

In very much non-scientific tests, this version of `detail::overload` compiles slightly faster, and has better diagnostics, because the visitor no longer is an anonymous struct.
Additionally, the brace-list-init constructor allows for using a trailing comma, which makes git-diffs leaner, and improves formatting in a few places.
This change is purely syntactical and does not alter the behavior of the code.
---
I've verified this to work using gcc-8 manually by running `docker build .` from the repository root.

Improve the detail::overload visitor helper

---

.github/workflows/vast.yaml

This PR removes usage of the deprecated `set-env` function in favor of `$GITHUB_ENV`. Additionally, we now use a newer version of the upload artifact action.

Use GITHUB_ENV instead of set-env

---

libvast/src/system/application.cpp
libvast/src/system/index.cpp
libvast/src/system/spawn_index.cpp
libvast/test/system/counter.cpp
libvast/test/system/eraser.cpp
libvast/test/system/exporter.cpp
libvast/test/system/index.cpp
libvast/vast/system/index.hpp

This option was added as a workaround for the case where the
meta index grew large enough to cause significant slowdown
when changing the active partition.
However, the meta index is not stored in the index flatbuffer
anymore, so we can remove it again.

Remove '--disable-recoverability' option

---

libvast/src/system/node.cpp

`caf::print_and_drop` already is the default, no need to set it explicitly.

Remove explicit default handler from node

---

libvast/vast/concept/printable/core/literal.hpp
libvast/vast/concept/printable/string/literal.hpp

Without this change, the constructor for the parser that takes a `bool` was preferrred, because implicit conversion from `const char*` to `bool` has a higher precedence than conversion to `std::string`.
This was caught by a warning introduced by clang-11 that is enabled by default: `-Wc++11-narrowing`.

Fix the literal printer for string literals

---

.github/workflows/vast.yaml

This will make the average CI run slower, but will allow for using the cache for more PRs are the same time.

Use maximum available compression level for Ccache

---

CHANGELOG.md
libvast/src/system/default_configuration.cpp
libvast/vast/defaults.hpp
vast.yaml.example

Change the default format for logfiles to omit information about
the class, function and thread id. This information adds a lot
of visual noise and little value. In particular the thread id can
easily be confused with a unix time stamp.
Before:
5235076 vast DEBUG actor24 140049658796832 size_t,%20size_t,%20const%20vast.path&,%20vast.system.archive_type,%20caf.actor)<GLOBAL operator() disk_monitor.cpp:114 disk_monitor erasing removed ids from archive
After:
5235076 vast DEBUG actor24 disk_monitor.cpp:114 disk_monitor erasing removed ids from archive

Make default log format less verbose

---

CHANGELOG.md
libvast/src/detail/settings.cpp
libvast/src/system/node.cpp
libvast/vast/detail/settings.hpp

Unlike for other merge operations, for the status we want to recurse deep into the object structure and merge array contents instead of overwriting arrays.  This fixes an issue that caused only the sources' status to show up in the output of `vast status --detailed` that replied last.
I verified this to work locally. We don't have an integration test that covers this.
Please run this locally for testing. We do not have an integration test that covers this.

Fix merging of source status objects

---

CHANGELOG.md
libvast/src/system/default_configuration.cpp

Disable the `middleman.enable-automatic-connections` option by default to prevent VAST from opening a random public port, and since we're not currently linking multiple VAST instances in a mesh anyways.

Don't enable automatic connections by default

---

libvast/src/schema.cpp
libvast/vast/schema.hpp

This fixes a downstream bug in VAST Pro, which was unable to add
additional "magic" schema lookup paths after a recent change.
n/t

Allow for specifying objpath lookup addresses

---

libvast/src/system/type_registry.cpp
libvast/src/taxonomies.cpp
libvast/test/system/type_registry.cpp
libvast/test/taxonomies.cpp
libvast/vast/taxonomies.hpp
schema/ecs.yaml

Let concepts reference others via a dedicated list as opposed to inside the fields list as it has been up to now.
This change synchronizes the concepts feature to the documentation.
Only one significant commit. Start with the tests, then check the changed `concepts_type`, then review the implementation.

Make concepts work as documented

---

CHANGELOG.md
scripts/splunk-to-vast

This script makes it possible to convert a splunk CIM datamodel into a VAST taxonomy.
Look at it in one shot.

Add script to convert CIM to VAST taxonomy

---

libvast/src/system/disk_monitor.cpp
libvast/vast/system/disk_monitor.hpp

Add status handling stub into disk monitor

---

CHANGELOG.md
tools/lsvast/lsvast.cpp

Fix file identifier check in lsvast

---

schema/suricata.schema

Remove duplicate schema entry. FWIW: This kind of bug also leads to invalid export data (arrow + JSON) with duplicate keys.

Remove duplicate schema entries

---

CHANGELOG.md
Dockerfile
Dockerfile_prebuilt
INSTALLATION.md
systemd/README.md
systemd/vast.service
systemd/vast.yaml

Change occurences of `/var/db/vast` to `/var/lib/vast` on Linux deployments.

Change /var/db to /var/lib on Linux deployments

---

libvast/src/system/type_registry.cpp
libvast/src/taxonomies.cpp
libvast/test/system/type_registry.cpp
libvast/test/taxonomies.cpp
libvast/vast/taxonomies.hpp
schema/ecs.yaml

Before this change, concept descriptions were ignored by VAST, now they are loaded with the definition and added to the output of `vast status --detailed`.

Handle concept descriptions properly

---

CHANGELOG.md
README.md
pyvast/setup.py

This prepares the repository for the October 2020 release. The merge commit of this PR is the one to be tagged for release.
This PR is blocked by some open PRs that we want to merge before the release:
This branch must be rebased onto master before merging.

Prepare October 2020 release

---

CHANGELOG.md
libvast/src/detail/pid_file.cpp

Change to PID file check so that it automatically gets replaced if the owning process does not exist any more.
Please test this change locally.
1. Try to run `vast -d somedir start` 2 times in parallel, without stopping the first process.
2. Try to run `vast -d somedir start` 2 times sequentially; kill the first process before spawning the second.

Replace PID file if process does not exist

---

CHANGELOG.md
libvast/src/command.cpp
libvast/src/system/application.cpp
vast.yaml.example

This PR adds the new option `vast.client-log-file` that allows for re-enabling client file logging.
Checkout, compile, test. The code is quite simple.

Allow for enabling client file logging

---

CHANGELOG.md
integration/default_set.yaml
integration/vast.yaml
libvast/src/system/application.cpp
libvast/src/system/spawn_node.cpp
vast.yaml.example

The code change should be obvious, I verified the change locally.

Make metrics opt-in

---

libvast/src/system/type_registry.cpp
libvast/src/taxonomies.cpp
libvast/test/system/type_registry.cpp
libvast/test/taxonomies.cpp
libvast/vast/taxonomies.hpp

This change implements loading and storing of models in the in memory taxonomies structure.
commit-by-commit.

Load models from YAML schema files

---

CHANGELOG.md
libvast/src/segment.cpp
libvast/src/segment_store.cpp
libvast/src/table_slice.cpp
libvast/vast/fbs/segment.fbs
libvast/vast/fbs/table_slice.fbs
libvast/vast/segment_builder.hpp
libvast/vast/table_slice.hpp
libvast/vast/table_slice_visit.hpp

The third PR to be merged into #1140. This set of changes wraps the existing table slice FlatBuffers table in a union, and cleans up the `table_slice.fbs` file accordingly, and adds a utility function for visiting table slice encodings.
Commit-by-commit works best for this PR.

Allow for extending the table slice FlatBuffers table

---

CHANGELOG.md
libvast/src/expression.cpp
libvast/test/parse_data.cpp
libvast/vast/concept/parseable/vast/data.hpp

Allow tuple-style syntax for parsing records

---

libvast/src/schema.cpp

This small PR makes it easier to understand whether an actual schema file got loaded.

Improve logging when loading schemas

---

CHANGELOG.md
libvast/src/data.cpp
libvast/src/error.cpp
libvast/src/schema.cpp
libvast/src/system/spawn_type_registry.cpp
libvast/src/system/type_registry.cpp
libvast/vast/data.hpp
libvast/vast/defaults.hpp
libvast/vast/error.hpp
libvast/vast/schema.hpp

This PR enables recursive directory traversal when processing the schema directory.
Commit-by-commit suits best.

Process schema directories recursively

---

CMakeLists.txt

A user-error when switching my machine to python@3.9 made me notice that our integration test suite does not run `pip` using `python -m pip`, as it should be.
n/t

Run pip via python in integration test environemnt

---

CHANGELOG.md
libvast/src/system/sink.cpp

This errored previously, which was most noticeable for continuous exports.
```bash
❯ vast -v quiet status --detailed | jq .sinks
```
```json
[
{
"format": "json-writer",
"processed": 378
}
]
```
Read the relatively simple code. Run locally by running a continuous or unified export command and sending a status request.

Reply to status requests in sinks

---

CHANGELOG.md
libvast/src/error.cpp
libvast/src/format/csv.cpp
libvast/src/format/multi_layout_reader.cpp
libvast/src/format/pcap.cpp
libvast/src/format/single_layout_reader.cpp
libvast/src/format/syslog.cpp
libvast/src/format/zeek.cpp
libvast/test/format/zeek.cpp
libvast/vast/error.hpp
libvast/vast/format/json.hpp
libvast/vast/format/reader.hpp
libvast/vast/system/source.hpp

To reproduce the bug, run the following commands without this fix:
```bash
vast start
```
```bash
while true; do
sleep 30
cat integration/data/suricat/eve.json
done | vast import suricata
```
PR to be taken over by @tobim, who as per our call has an idea for another improvement.
n/t

Fix a bug that causes sources to stall

---

schema/sysmon.schema

This PR adds schema definitions for Winlogbeat wrapper events that wrap the raw Sysmon records.
In one shot.

Add Winlogbeat schema definitions

---

CHANGELOG.md
libvast/src/arrow_table_slice.cpp
libvast/src/arrow_table_slice_builder.cpp
libvast/src/format/arrow.cpp
libvast/src/table_slice.cpp
libvast/src/table_slice_builder_factory.cpp
libvast/src/table_slice_factory.cpp
libvast/test/arrow_table_slice.cpp
libvast/test/format/arrow.cpp
libvast/vast/arrow_table_slice.hpp
libvast/vast/arrow_table_slice_builder.hpp
libvast/vast/fbs/table_slice.fbs
libvast/vast/fwd.hpp
libvast/vast/msgpack_table_slice_builder.hpp
libvast/vast/table_slice.hpp
libvast_test/vast/test/fixtures/table_slices.hpp

The sixth PR to be merged into #1140. This one re-implements Arrow-encoded table slices to use FlatBuffers directly.
This is just a single commit; view file-by-file and compare to MessagePack-encoded table slices (#1157).

Implement new Arrow-encoded table slices

---

CHANGELOG.md
tools/lsvast/lsvast.cpp

Show file size information in lsvast

---

CHANGELOG.md
libvast/vast/defaults.hpp
vast.yaml.example

The 4x increase in segment size decreases the range map fragmentation in the archive. It also will reduce startup time for larger archives. There should not be a latency problem with larger file sizes since we mmap the segments.
All at once.

Increase the default segment size to 1 GiB

---

libvast/src/chunk.cpp
libvast/src/segment_store.cpp
libvast/vast/chunk.hpp

This PR adds `noexcept` specifications to the chunk API. Most notably, it requires deletion steps to be nothrow-invocable, because they are invoked in the destructor, where throwing is definitely not what we want to happen.
n/t

Specify noexcept for the chunk API

---

CHANGELOG.md
libvast/src/system/connect_to_node.cpp
libvast/src/system/start_command.cpp
libvast/test/endpoint.cpp
libvast/vast/defaults.hpp
libvast/vast/endpoint.hpp
libvast/vast/system/make_source.hpp

Sets a fallback port of `42000` when the `vast.endpoint` option is set, but does not contain a port.
Run `vast -e localhost start` with and without this change to verify this works.

Set fallback port for underspecified endpoints

---

libvast/src/table_slice.cpp
libvast/test/format/arrow.cpp
libvast/vast/table_slice.hpp

Make rebuiling table slices not a constructor

---

libvast/src/table_slice.cpp

gcc-8 fails to detect when a switch exhausts all uses of an enum class. This is usually worked around by calling a `[[noreturn]]` function afterwards. Apparently gcc-8 also fails to recognize that calling a `[[noreturn]]` function in a `constexpr` context is also totally fine, and fails to compile.
n/t

Fix build on gcc-8

---

libvast/src/table_slice.cpp

GCC erroneously instantiates in `std::is_invocable`, c.f. https://stackoverflow.com/questions/60440755
n/t

Fix --without-arrow builds for gcc

---

schema/suricata.schema

Fix a wrongly copy-pasted key name in the Suricata schema definition for `tftp`.
This simply fixes a small bug in a previous PR (#1176).

Fix key for 'tftp' subobject

---

libvast/src/chunk.cpp
libvast/vast/chunk.hpp
tools/lsvast/lsvast.cpp

This avoids the need to `const_cast` when using `chunk::make` on existing data. The chunk API already promises not to touch the underlying pointer unless it is safe to do so, so let's just make that clear from the interface of the make function already.
n/t

Construct chunks from const pointers

---

CMakeLists.txt
configure

See title. Be aware that compilation times go up by a lot, that's why I did not add it to `dev-mode` or `ci-build`.

Add an option to enable ubsan

---

libvast/src/table_slice.cpp
libvast/vast/chunk.hpp
libvast/vast/detail/keep.hpp
libvast/vast/detail/keeper.hpp
libvast/vast/table_slice.hpp

This fixes a bug in the new `as_record_batch` function.
Commit-by-commit feels best. Read the commit descriptions.

Fix result lifetime of as_record_batch

---

CHANGELOG.md
schema/suricata.schema

Add a new record type in the Suricata schema for RDP and add, among others, the missing `tls.sni` field that would be required for some applications involving domain indicators.
Just double-check the syntax please.

Add RDP schema record type and missing TLS fields

---

libvast/src/system/index.cpp
libvast/src/system/partition.cpp

This is a minor refactoring that ensures we use the same logic for releasing a `FlatBufferBuilder` into a `chunk` across the code base.
n/t

Use fbs::release where appropriate

---

libvast/src/arrow_table_slice_builder.cpp
libvast/src/msgpack_table_slice_builder.cpp

The check in the beginning should've been an assertion from the get-go: it indicates wrong API usage, and is never a result of wrong input.
n/t

Ensure that table slice builders cannot fail

---

.github/workflows/static-binary.yaml
.github/workflows/vast.yaml

`GoogleCloudPlatform/github-actions/setup-gcloud` is [deprecated](https://github.com/google-github-actions/setup-gcloud/tree/master/setup-gcloud#-deprecation-notice). This PR switches to the new version.

Switch to new GCP GitHub action

---

CHANGELOG.md
doc/cli/vast-count.md
doc/cli/vast-dump-concepts.md
doc/cli/vast-dump.md
libvast/src/system/application.cpp
libvast/src/system/node.cpp
libvast/src/system/type_registry.cpp
libvast/vast/system/type_registry.hpp
vast.yaml.example

This implements a command that dumps the known concepts without requiring the work to do a full status report.

Make it possible to dump concepts

---

CHANGELOG.md
libvast/src/system/index.cpp
libvast/src/system/partition.cpp

Send correct message type when replacing partition

---

CMakeLists.txt
nix/static-binary.sh

VAST uses the output of git describe in its version string, which is baked into the binary. Since v2.11 git estimates the length needed to avoid colisions based on the number of objects in the .git directory. That means that building VAST from a shallow clone would result in a different binary artifact compared to a build from a regular clone.

Fix the length of the abbreviated commit hash

---

libvast/src/chunk.cpp
libvast/src/fbs/utils.cpp
libvast/src/msgpack_table_slice.cpp
libvast/vast/chunk.hpp
libvast/vast/fbs/utils.hpp

Just a minor fix for a minor issue that I just noticed. The order of this was not well-defined before. It happened to work, but let's not rely on that.

Ensure get isn't called on a moved-from unique_ptr 

---

libvast/src/segment_builder.cpp
libvast/src/segment_store.cpp
libvast/test/segment.cpp
libvast/vast/segment_builder.hpp

This is an experimental PR that sets the initial buffer size of the underlying `FlatBufferBuilder` of the `segment_builder` to 110% of `vast.max-segment-size`. The 10% extra is needed because the configured limit is a soft limit, and because there's still some extra scaffolding in the FlatBuffers table that is only added when we call `segment_builder::finish()`.
n/t

Avoid reallocations in the segment builder

---

CHANGELOG.md
libvast/src/system/type_registry.cpp
libvast/src/taxonomies.cpp
libvast/src/type.cpp
libvast/test/system/type_registry.cpp
libvast/test/type.cpp
libvast/vast/format/json.hpp
libvast/vast/system/source.hpp
libvast/vast/type.hpp
libvast/vast/type_set.hpp
schema/types/test.schema

When changing schemas such that types are no longer a superset of previous versions of the same type, VAST may end up in a state where it cannot import events of that type.
This change makes the type registry ~forget about incompatible versions of types automatically when a new and incompatible type is registered.~ warn when this happens and ensures that newly registered types get priority over older types when importing data.

Detect and handle breaking changes in schemas

---

libvast/src/system/archive.cpp
libvast/src/system/index.cpp

This avoids stream errors on short-lived commands like `vast -N dump concepts`. These were really non-errors caused by early exits from shutting down the node. We shouldn't print red stuff when there isn't actually an error.
> 2020-11-26T14:40:06.085 archive got a stream error: exit_reason(user_shutdown)
> 2020-11-26T14:40:06.086 index aborts with error: !! exit
Run locally before and after the change I've made, verify that the quoted errors are no more.

Avoid stream errors for short-lived commands

---

CHANGELOG.md
CMakeLists.txt
configure
libvast/src/chunk.cpp
libvast/vast/detail/discard.hpp
libvast/vast/detail/tracepoint.hpp
libvast/vast/logger.hpp

See extensive description in the new header file itself.
Review all commits at once.
To verify that release builds now contain trace points by default:
1. Download the CI artifact on a linux system
2. Use `sudo perf buildid-cache -a /path/to/libvast.so` to add the binary to the buildid cache
3. Use `sudo perf probe --list | grep vast` to see if the tracepoint exist
(optionally)
4. Use e.g. `sudo perf probe sdt_vast:chunk_make` and `perf record -e sdt_vast:chunk_make -- vast start` to record the samples

Add support for USDT tracepoints in VAST

---

CHANGELOG.md
libvast/src/system/index.cpp

This fixes a logic error. To reproduce, add the following assertion on current master:
```diff
diff --git a/libvast/src/system/index.cpp b/libvast/src/system/index.cpp
index 2cfd19028..6bc869635 100644
--- a/libvast/src/system/index.cpp
+++ b/libvast/src/system/index.cpp
@@ -197,6 +197,7 @@ bool index_state::worker_available() {
}
caf::actor index_state::next_worker() {
+  VAST_ASSERT(worker_available());
auto result = std::move(idle_workers.back());
idle_workers.pop_back();
return result;
```
Compile, then start a node. Ideally, import lots of data—I tested this by ingesting the whole ICTF data set.
Now, start multiple export commands as background processes that don't have much work to do, e.g.,
```zsh
repeat 100; do vast export -n 100 null '#type ni ""' &; done
```
The newly added …

Switch index behavior when running out of workers

---

CHANGELOG.md

We did not expect this to make such a big impact, which is why we did not write a changelog entry at first. Turns out #1209 makes a massive difference for some queries.
n/t

Add missing changelog entry for #1209

---

libvast/src/system/index.cpp

A small fixup for a very unlikely issue that @lava and I noticed.
n/t

Ensure uniqueness of query ids

---

libvast/src/db_version.cpp
libvast/src/error.cpp
libvast/src/system/spawn_node.cpp
libvast/vast/db_version.hpp
libvast/vast/error.hpp

Sample output:
```
$ ./bin/vast start
!! filesystem_error: "wrong or missing database version in db-directory"2020-11-27T15:43:26.603 Cannot start VAST, breaking changes detected in the database directory
2020-11-27T15:43:26.603 Detailed explanation:
The dedicated `port` type was removed from VAST and replaced by a typedef for count. To update, adjust all custom schemas containing a field of type 'port' and reimport all data that contained a 'port' field.
```
Note that I have no idea how the file system error message can be printed *before* the log messages when the error hasn't even been created yet, but here we are.

Enforce better documentation for breaking changes

---

nix/static-binary.sh

This makes the static binary build more deterministic by not relying on the contents of `<nixpkgs>` any more.

Use pinned nixpkgs for static binary script

---

CMakeLists.txt

This is a break-out from the related jemalloc PR to get a successful static build CI run with only that change.

Always pass build-id flag to linker

---

CHANGELOG.md
integration/default_set.yaml
integration/reference/node-suricata-alert/step_03.ref
integration/vast.yaml
libvast/src/format/zeek.cpp
libvast/src/system/spawn_sink.cpp
libvast/test/format/zeek.cpp
libvast/test/system/sink.cpp
libvast/vast/format/zeek.hpp
vast.yaml.example

This PR lifts the restriction of the Zeek writer to only dump Zeek events. There is no conceptual limitation, but VAST had an assertition that prevented rendering other data than Zeek.

Make Zeek writer work with all data types

---

libvast/src/segment.cpp
libvast/src/segment_store.cpp
libvast/src/system/partition.cpp

Segments and partitions larger than `FLATBUFFERS_MAX_BUFFER_SIZE` can no longer be loaded.
n/t

Check allowed size of segments/partitions on load

---

CHANGELOG.md
libvast/test/address_synopsis.cpp
libvast/vast/address_synopsis.hpp
libvast/vast/bloom_filter.hpp

Fix the bloom filter synopsis deserialization

---

CHANGELOG.md
libvast/src/system/index.cpp
libvast/vast/system/index.hpp

A bug that causes the removal of index workers in case of false positive candidate partitions is fixed here.

Fix index worker depletion

---

Dockerfile

Probe PR to check workflow. 
Includes a minor change for builder dockerfile: switch to `debian:buster-backports` as a base image, which makes libsimdjson-dev possible to install.

Use buster-backports as a base for build-in-docker debian image.

---

nix/overlay.nix

This enables jemalloc profiling and changes our library dependencies to build with `-fno-omit-frame-pointer`.

Improve tracing tools support in the static binary

---

libvast/src/system/exporter.cpp

Print basic information about the number of total and scheduled partitions on VERBOSE.
Don't print a message for every export on INFO log level (this is especially noticable when using a command that spawns exporters dynamically, like `vast explore` or `vast matcher`).

Adjust logging verbosity in exporter

---

CHANGELOG.md
libvast/src/system/importer.cpp
libvast/src/system/node.cpp

Don't collect status messages from sources and sinks.
By commit.

Don't collect status from sources and sinks

---

CHANGELOG.md
libvast/src/system/node.cpp
libvast/src/taxonomies.cpp

Fix loading and dumping of composed concepts

---

CHANGELOG.md
schema/types/suricata.schema

This PR adds schema entries for two new Suricata EVE-JSON event types : `sip` and `dcerpc`. For the latter, the `interfaces` sub-structure is currently missing due to missing list of record support in VAST. It has hence been disabled for now.
Ensure that integration tests still finish on Tenzir side as well.

add SIP and DCERPC schema entries

---

CHANGELOG.md
libvast/src/bloom_filter_synopsis.cpp
libvast/src/meta_index.cpp
libvast/src/synopsis_factory.cpp
libvast/src/system/index.cpp
libvast/src/system/partition.cpp
libvast/src/system/spawn_index.cpp
libvast/test/address_synopsis.cpp
libvast/test/meta_index.cpp
libvast/test/system/counter.cpp
libvast/test/system/eraser.cpp
libvast/test/system/exporter.cpp
libvast/test/system/index.cpp
libvast/vast/address_synopsis.hpp
libvast/vast/bloom_filter.hpp
libvast/vast/bloom_filter_synopsis.hpp
libvast/vast/buffered_synopsis.hpp
libvast/vast/defaults.hpp
libvast/vast/fbs/synopsis.fbs
libvast/vast/meta_index.hpp
libvast/vast/string_synopsis.hpp
libvast/vast/system/index.hpp
vast.yaml.example

This adds support for type-level synopses to the meta index. For each field in a partition, it is possible to decide whether to use a specific synopsis, share one with the other fields of the same type, or not to use a synopsis at all.
A new string synopsis and buffered string synopsis is also introduced.
By commit.

Add support for type-level synopses and a string synopsis

---

libvast/src/system/accountant.cpp

This PR fixes the initialization of the accountant config.
Try it out locally.
Note that I'm not adding a changelog entry since we only introduced this bug after the last release.

Fix metrics configuration

---

.github/workflows/vast.yaml
CMakeLists.txt
configure
libvast/CMakeLists.txt
libvast_test/CMakeLists.txt

This prohibits `CMAKE_INSTALL_PREFIX` to be a relative path, and changes `configure` to convert arguments to `--prefix` to be absolute.
n/t

Fix installations with relative prefixes

---

CHANGELOG.md
libvast/src/system/application.cpp
libvast/src/system/configuration.cpp

|short option|long option|
|-|-|
|-qqq|--verbosity=quiet|
|-qq|--verbosity=error|
|-q|--verbosity=warning|
||--verbosity=info (default)|
|-v|--verbosity=verbose|
|-vv|--verbosity=debug|
|-vvv|--verbosity=trace|
Try it!

Support -v, -vv, -vvv, -q, -qq, -qqq for verbosity

---

CHANGELOG.md
libvast/src/system/configuration.cpp

This removes the check whether a config file is a regular file.
This is unnecessary after 5b4b052, which I accidentally pushed to master directly. Sorry about that one. That commit made it so manually specified config files could be in the same directory as normal config files.
The changelog entry covers both changes.
Look at this PR and the referenced commit.

Remove check whether config file is a regular file

---

CHANGELOG.md
libvast/src/arrow_table_slice.cpp

This fixes a crash when encountering an issue with the on-disk format of serialized Arrow Record Batches or Arrow Schemas.
Change random bytes from a segment and export contained table slices until you get the IOError from Arrow and notice that VAST doesn't crash anymore.

Handle Arrow decoder errors gracefully

---

CHANGELOG.md
libvast/src/format/json.cpp
libvast/vast/format/json.hpp

Please test modifying the suricata schema and ingesting test data from the repo. Everything but the modified field should remain intact upon export.

Gracefully deal with JSON to data conversion errors

---

cmake/VASTProvideFindModule.cmake
libvast/CMakeLists.txt
vast/CMakeLists.txt

Another round of fixes for the new CMake scaffold.
- Find Modules must be provided for PUBLIC and INTERFACE targets even when BUILD_SHARED_LIBS is on
- Dependencies are not propagated correctly for into `VASTConfig.cmake`
- The integration testing harness can now be used when linking against build trees

Fix installation scaffold

---

.github/workflows/static-binary.yaml

This changes the static binary workflow to trigger whenever we touch CMake code. Noticed this when reviewing #1253, where I wondered why the workflow did not run.
n/t

Trigger static binary workflow for CMake changes

---

libvast/src/data.cpp
libvast/src/directory.cpp
libvast/src/schema.cpp
libvast/vast/config.hpp.in
libvast/vast/detail/function.hpp
libvast/vast/directory.hpp

The regex include comes with a hefty compile time increase; a filter function is more appropriate (and more performant!) here.
File-by-file.

Remove regex include from directory.hpp

---

CMakeLists.txt
cmake/VASTUtilities.cmake
libvast/CMakeLists.txt
tools/zeek-to-vast/CMakeLists.txt

This adds a minimal version of the old build summary per request by @mavam, whom I've requested for review explicitly.
Checkout the branch and test locally.

Add back human-readable build summary

---

.github/workflows/vast-docker.yaml
vast.yaml.example

I have the feeling that the changes in #1208 are unrelated to the failure of this workflow, so let's run it whenever we touch our build system as well to catch issues earlier.
Edit: Confirmed to be broken; I'm repurposing this PR to fix the issue.
n/t

Fix the vast-docker workflow

---

libvast/src/plugin.cpp

just a small thing we overlooked.
n/t

Require plugin major versions to be identical

---

libvast/vast/concept/printable/core/printer.hpp
libvast/vast/concept/printable/detail/as_printer.hpp

While working on an unrelated PR, we discovered that a harmless bit shift of two numbers can be interpreted as the construction of a `sequence_printer` when the namespace vast is visible where the code is instantiated:
```
/usr/include/fmt/core.h:1856
unsigned int mask = (1 << detail::packed_arg_bits) - 1;
```
This is not ideal, since it is very easy to accidentally step into, and requires a massive debugging effort by the unsuspecting victim.

Restrict arguments of 'vast::detail::as_printer'.

---

CHANGELOG.md
libvast/test/time.cpp
libvast/vast/concept/parseable/vast/time.hpp

According to the docs on query-language (https://docs.tenzir.com/vast/query-language/values), VAST currently supports `secs` but not `seconds`, same for `mins` but not `minutes`. We do however support `weeks` and `days`, even though there are abbreviations of that as well. This PR aims to fix that inconsistency.
This can be best reviewed on a commit-by-commit bases.

Make duration units abbreviations consistent

---

libvast/test/flatbuffers.cpp
libvast/vast/system/partition.hpp

Add some explicit member default initializers for partition_state

---

CHANGELOG.md
libvast/src/plugin.cpp
libvast/src/system/version_command.cpp
libvast/vast/plugin.hpp

The `version` command now prints the plugin version as follows:
```json
{
"VAST": "2020.12.16-97-gced115d91-dirty",
"CAF": "0.17.6",
"Apache Arrow": "2.0.0",
"PCAP": "libpcap version 1.9.1",
"jemalloc": null,
"plugins": {
"example": "0.0.0-0"
}
}
```
In one shot.

Print plugin versions

---

vast/integration/default_set.yaml

We have a known shutdown bug that affects only commands run with `-N`, and every so often the dump command triggers it. Especially so when testing locally, because the CI runners are somewhat slow. Because the issue has received a very low priority as does anything that is specific to `-N`, this commit serves as a workaround to make running the integration test suite locally more reliable.
n/t

Use the ServerTester fixture for testing dump

---

libvast/src/table_slice_encoding.cpp
libvast/vast/component_config.hpp
libvast/vast/system/make_source.hpp

As a small bonus, this fixes a subtle issue that caused undefined behavior when the option `vast.import.batch-encoding` was not set.

Make table slice encodings printable

---

doc/cli/vast-infer.md
libvast/src/schema.cpp
libvast/src/segment_store.cpp
libvast/src/system/index.cpp
vast/integration/default_set.yaml

Address minor spelling issues as detected by Debian's lintian static checker.
Make sure that no internal tests etc. depend on the exact previous spelling.

fix spelling issues as detected by lintian

---

.github/workflows/static-binary.yaml

The current download instructions on the installation docs downloads the latest master build:
```
RELEASE=2020.12.16
curl -L -O https://storage.googleapis.com/tenzir-public-data/vast-static-builds/vast-${RELEASE}-static-latest.tar.gz
tar xf vast-${RELEASE}-static-latest.tar.gz
bin/vast version
{
"VAST": "2020.12.16-0-",
"CAF": "0.17.6",
"Apache Arrow": "2.0.0",
"PCAP": "libpcap version 1.9.1 (with TPACKET_V3)",
"jemalloc": "5.2.1-0-gea6b3e973b477b8061e0076bb257dbd7f3faa756",
"plugins": {}
}
```
The `"plugins"` key should not be there.

Only update the release tarball in an actual release build

---

.github/workflows/style-check.yaml

This should fix the style check CI workflow. ~The commit that intentionally breaks the formatting for testing should be removed before merging.~ Done
Watch CI.

Fix the style check CI workflow

---

CHANGELOG.md
doc/cli/vast-start.md
libvast/src/system/application.cpp
libvast/src/system/start_command.cpp
vast.yaml.example

This is helpful for test scripts that pass in `:0` to get a random free port allocated from the operating system.

Make the start command print the endpoint on stdout

---

CHANGELOG.md
libvast/src/system/application.cpp
libvast/vast/defaults.hpp
libvast/vast/format/json/field_selector.hpp
vast.yaml.example

This adds simdjson support to `vast import zeek-json`.
Try it out locally.

Add simdjson support to zeek-json import

---

CHANGELOG.md
libvast/src/detail/line_range.cpp
libvast/test/format/zeek.cpp
libvast/vast/detail/absorb_line.hpp
libvast/vast/detail/getline_generic.hpp
libvast/vast/detail/line_range.hpp

Fix incomplete events when a timeout is hit in the middle of a line.
By commit. You can check before / after with:
```
cat conn.log | pv -L 1000 | vast import zeek
```

Don't overwrite line content after a read timeout

---

CHANGELOG.md
examples/plugins/example/integration/tests.yaml
examples/plugins/example/integration/vast.yaml
libvast/src/system/application.cpp
vast.yaml.example
vast/vast.cpp

This changes the loading of plugins to only consider explicitly specified plugins.
File-by-file.
This is based on #1282, but this can be reviewed independently.

Load only explicitly specified plugins

---

libvast/CMakeLists.txt

This changes the CMake options for all available install root hints to be exposed.
Test whether the options show up in `ccmake`.

Expose install root hint variables as options

---

CHANGELOG.md
libvast/src/schema.cpp
libvast/src/system/application.cpp
vast.yaml.example
vast/vast.cpp

The `*-paths` option in our `vast.yaml` feel really confusing. A directory is necessarily a path, but not the other way round.
The old options continue to work, but are deprecated.
Try it out locally.

Rename *-paths to *-dirs options

---

CHANGELOG.md
libvast/src/format/arrow.cpp
libvast/src/system/sink.cpp
vast/integration/default_set.yaml
vast/integration/reference/arrow/step_03.ref

This fixes a small oversight from the recent unflattening PR.
Should be easy to verify locally like this:
```
❯ vast -N import suricata -r vast/integration/data/suricata/eve.json
❯ vast -N export arrow '"" in #type'
```

Fix Arrow export for nested records

---

.github/workflows/static-binary.yaml
.github/workflows/vast.yaml

Remove use of `service_account_email` from GCP setup in CI workflows.
File-by-file

Update GCP setup step in GitHub workflows

---

configure
vast/CMakeLists.txt

As requested by @lava, this should clarify how to use the VAST_PLUGINS CMake variable.
Try to misuse locally. Read the error messages.

Improve diagnostics for misuse of VAST_PLUGINS

---

examples/plugins/example/example.cpp

Since we already use 'override', no need to have 'virtual' in there.
Just a minor consistency fix.
Just look at the one-line diff.

Remove unnecessary virtual keyword

---

CMakeLists.txt

This changes which files we take into consideration for the build tree hash of libvast.
@mavam this should fix your issue with swap files. Please test locally.

Restrict file selection for buld tree hash

---

CHANGELOG.md
libvast/src/system/evaluator.cpp
libvast/src/system/partition.cpp
libvast/test/system/evaluator.cpp
libvast/vast/system/evaluator.hpp

This came up while pairing on on unrelated PR with @tobim . I have no proof that the described race can actually happen in practice, but intuitively it makes sense to me that it would.

Fix potential race condition between evaluator and partition

---

libvast/src/system/partition.cpp
libvast/vast/fbs/partition.fbs

The name was misleading, since the field actually stores
the *unqualified* field name. The fully qualified field
name is stored in the `combined_layout` field of the partition.

Rename "fully_qualified_field" flatbuffer field

---

libvast/src/system/index.cpp
libvast/vast/system/index.hpp

This is just a refactoring, no functional changes. Logically, these functions are part of the index state, and this change moves them to their appropriate place. This makes the monolithic `index` behavior function a tiny bit more readable.
File-by-file.

Cleanup active partition rotation

---

libvast/src/meta_index.cpp
libvast/src/system/index.cpp
libvast/test/meta_index.cpp
libvast/vast/meta_index.hpp
libvast/vast/system/index.hpp

In preparation for splitting out the meta index into a separate actor, this moves the synopsis factory options to the index directly.
File-by-file.

Move synopsis options from meta index to index

---

libvast/src/detail/add_message_types.cpp
libvast/src/system/exporter.cpp
libvast/src/system/importer.cpp
libvast/src/system/spawn_importer.cpp
libvast/test/system/exporter.cpp
libvast/test/system/importer.cpp
libvast/vast/fwd.hpp
libvast/vast/system/actors.hpp
libvast/vast/system/importer.hpp

This converts the IMPORTER component to the `caf::typed_actor` API.
File-by-file.

Make the importer a typed actor

---

CHANGELOG.md
libvast/CMakeLists.txt

There's a stupid bug in simdjson 0.8.0: it does not export a `simdjson-config.cmake` file, so `find_package(simdjson)` can't work. Instead, it exports the file as `simdjson-targets.cmake`, which usually exists for other purpsoes. ¯\\\_(ツ)\_/¯
Verify that it works with simdjson 0.8.0 while keeping compatibility with older versions.

Adapt build config to work with simdjson 0.8.0

---

CHANGELOG.md
libvast/src/format/simdjson.cpp
libvast/test/format/simdjson.cpp
libvast/vast/format/simdjson.hpp

Before simdjson 0.8.0, `simdjson::simdjson_result<T>` inherited from `std::pair<T, Error>` publicly, which allowed us to use it in a possibly unintended way. The type no longer decomposes into structured bindings, so we now use `.error()` and `.value()` respectively where appropriate.
File-by-file.

Fix usage of simdjson::simdjson_result<T>

---

CHANGELOG.md
examples/plugins/example/example.cpp

Per our vote within the team, this renames the functions and classes in the example plugin accordingly and moves it into the `vast::plugins` namespace as it's a bundled plugin.
n/t

Adjust naming in example plugin

---

CMakeLists.txt
configure
libvast/src/detail/add_message_types.cpp
libvast/src/flow.cpp
libvast/src/format/pcap.cpp
libvast/src/port.cpp
libvast/src/system/connect_to_node.cpp
libvast/src/system/start_command.cpp
libvast/test/community_id.cpp
libvast/test/endpoint.cpp
libvast/test/flow.cpp
libvast/test/port.cpp
libvast/vast/community_id.hpp
libvast/vast/concept/parseable/vast/port.hpp
libvast/vast/concept/printable/vast/port.hpp
libvast/vast/detail/stable_map.hpp
libvast/vast/flow.hpp
libvast/vast/fwd.hpp
libvast/vast/port.hpp
libvast/vast/system/make_source.hpp

This change ensures that all types that get added to a `caf::message` have a valid type ID assigned to them, and makes the necessary changes for this to work.
File-by-file. I recommend starting with `CMakeLists.txt` and `vast/fwd.hpp`.

Enable compile-time type ID checks in dev mode

---

vast/CMakeLists.txt

I came across a build error because the directory `/build/share/vast` did not exist when the symlink for the integration test directory was created. I don't know how the order of those targets is determined, but it is unnecessary to rely on implicit assumptions here.

Make sure the parent dir for the test link exists

---

nix/pinned.nix

This updates the following libs for the vast static build:
- Arrow: 3.0.0
- simdjson: 0.8.1
It also incorporates a bugfix so spdlog propagates its dependency on fmt, which broke the build.

Bump nixpkgs to 449b698

---

libvast/src/system/get_command.cpp
libvast/src/system/node.cpp
libvast/src/system/pivot_command.cpp
libvast/src/system/sink_command.cpp
libvast/src/system/spawn_archive.cpp
libvast/src/system/spawn_counter.cpp
libvast/src/system/spawn_disk_monitor.cpp
libvast/src/system/spawn_eraser.cpp
libvast/src/system/spawn_exporter.cpp
libvast/src/system/spawn_importer.cpp
libvast/src/system/spawn_index.cpp
libvast/src/system/spawn_type_registry.cpp
libvast/vast/detail/actor_cast_wrapper.hpp
libvast/vast/system/component_registry.hpp
libvast/vast/system/import_command.hpp
libvast/vast/system/node_control.hpp
libvast/vast/system/spawn_source.hpp

This commit
- replaces all usage of the untyped version of get_node_components with
the typed version,
- removes the untpyed version of get_node_components entirely,
- introduces a new typed find member function to the component registry,
and
- replaces calls to find_by_label with calls to the new typed find where
possible.
File-by-file.

Improve access of typed versions of components

---

.clang-format
.github/workflows/vast.yaml
CHANGELOG.md
CMakeLists.txt
Dockerfile
configure
libvast/CMakeLists.txt
libvast/src/logger.cpp
libvast/vast/detail/logger.hpp
libvast/vast/detail/logger_formatters.hpp
libvast/vast/logger.hpp
libvast/vast/system/make_source.hpp

This makes {fmt} a hard dependency of VAST, and fixes some of the remaining issues with the new logger.

Require fmt to be installed separately from spdlog

---

.github/workflows/static-binary.yaml
.github/workflows/vast.yaml

https://github.com/mknejp/delete-release-assets
Proposal: delete release assets if they exist before attempting to upload new assets. This is to avoid errors when uploading assets that already exist. 
See this run in a repository I created to test these two actions in isolation: https://github.com/0snap/release-action-test/runs/1816583406?check_suite_focus=true

Delete assets before uploading new ones

---

CHANGELOG.md
vast/vast.cpp

This fixes an issue where logger options were not recognized when passed on the command line.
Test locally.

Merge CLI options before initializing logger

---

libvast/src/system/accountant.cpp
libvast/src/system/archive.cpp
libvast/src/system/disk_monitor.cpp
libvast/src/system/evaluator.cpp
libvast/src/system/exporter.cpp
libvast/src/system/importer.cpp
libvast/src/system/index.cpp
libvast/src/system/indexer.cpp
libvast/src/system/node.cpp
libvast/src/system/partition.cpp
libvast/src/system/posix_filesystem.cpp
libvast/src/system/query_supervisor.cpp
libvast/src/system/sink.cpp
libvast/src/system/type_registry.cpp
libvast/vast/system/datagram_source.hpp
libvast/vast/system/disk_monitor.hpp
libvast/vast/system/evaluator.hpp
libvast/vast/system/posix_filesystem.hpp
libvast/vast/system/query_supervisor.hpp
libvast/vast/system/source.hpp

This changes many actor behaviors to capture `self` explicitly. This'll make live-reconfiguring of actors easier to implement in the future, and avoids some really stupid mistakes right now.
File-by-file.

Capture 'self' explicitly in actor behaviors

---

examples/plugins/example/example.cpp
libvast/src/system/importer.cpp
libvast/src/system/spawn_importer.cpp
libvast/test/system/exporter.cpp
libvast/test/system/importer.cpp
libvast/vast/plugin.hpp
libvast/vast/system/importer.hpp

This change allows analyzer plugins to communicate with the node.
File-by-file. Test locally.

Make the node handle available to analyzer plugins

---

examples/plugins/example/example.cpp
examples/plugins/example/integration/reference/example/step_01.ref
examples/plugins/example/integration/tests.yaml
libvast/src/system/importer.cpp
libvast/vast/plugin.hpp
libvast/vast/system/actors.hpp
libvast/vast/system/importer.hpp

This makes it possible to receive status information from analyzer plugin actors.
Here's how it looks when it works:
```json
❯ vast -qq status | jq .importer
{
"analyzers": [
{
"example": {
"answer": 42
}
}
]
}
```
And here's a fabricated test case with a timeout:
```json
❯ vast -qq status | jq .importer
{
"analyzers": [
{
"example": {
"error": "!! request_timeout"
}
}
]
}
```
File-by-file.

Make the analyzer plugin actor a status client actor

---

examples/plugins/example/CMakeLists.txt
examples/plugins/example/schema/types/plugin.example.schema
vast/CMakeLists.txt

This allows plugins to install `*.{schema,yml,yaml}` files from a `schema` subdirectory.
Test locally.

Add mechanism for plugins to install schema files

---

libvast/src/system/node.cpp

For reasons I admittedly still don't entirely understand, this fixes an error that was introduced with https://github.com/tenzir/vast/pull/1335 for queries that returned no results.
@lava please verify if this fixes the issue you've been seeing.

Fix misbehavior of queries returning no results

---

examples/plugins/example/example.cpp
libvast/src/plugin.cpp
libvast/vast/plugin.hpp
vast/vast.cpp

This allows plugins to assign additional type IDs rather easily, and detects overlaps when doing it in the recommended way.
File-by-file.

Allow for plugins to assign additional type IDs

---

libvast/vast/bitmap_index.hpp
libvast/vast/concept/hashable/hash_append.hpp
libvast/vast/concept/printable/detail/as_printer.hpp
libvast/vast/detail/function.hpp
libvast/vast/detail/narrow.hpp
libvast/vast/detail/type_traits.hpp
libvast/vast/span.hpp

Problem:
- `bool_constant` alias template is defined in vast, but widely
available in standard libraries.
- `bool_constant` is not widely used throughout the codebase. Instead,
the full form of `std::integral_constant<bool, expr>` is used.
Solution:
- Since C++17 is widely available and used throughout the codebase,
use `std::bool_constant` consistently.
- Remove `bool_constant` alias template defined in vast.
File-by-file

Prefer std::bool_constant over vast::bool_constant

---

libvast/vast/detail/function.hpp
libvast/vast/detail/type_traits.hpp

Problem:
- `void_t` from `type_traits.hpp` is not needed as `std::void_t` is
widely available.
- Hand-rolled `void_t` in `vast/detail/function.hpp` is not needed
either as CWG issue 1558 has been fixed as of GCC 5.0
Solution:
- Remove `void_t` from `type_traits.hpp` in favor of using `std::void_t`
directly.
- Remove hand-rolled `void_t` that worked around CWG issue 1558 in favor
of `std::void_t`.
File-by-file.

Remove void_t GCC bug workaround

---

libvast/vast/detail/type_traits.hpp

Problem:
- `contains` type trait is unused.
Solution:
- Remove `contains` type trait and associated variable template.
`caf::detail::tl_contains` is used instead throughout the codebase.
File-by-file.

Remove contains type trait

---

libvast/test/detail/type_traits.cpp
libvast/vast/concept/hashable/hash_append.hpp
libvast/vast/detail/type_traits.hpp

Problem:
- Compile time sum is defined in terms of recursive class templates
which is slow.
- There are no tests for `sum`.
Solution:
- Use fold expressions to speed up the implementation and make `sum` a
variable template instead.
- Add tests for `sum`.
File-by-file.

Speed up compile time computation of sum

---

CHANGELOG.md
doc/cli/vast-import-csv.md
libvast/src/command.cpp
libvast/src/defaults.cpp
libvast/src/format/pcap.cpp
libvast/src/format/writer_factory.cpp
libvast/src/format/zeek.cpp
libvast/src/schema.cpp
libvast/src/system/application.cpp
libvast/src/system/infer_command.cpp
libvast/src/system/node.cpp
libvast/src/system/spawn_sink.cpp
libvast/test/format/pcap.cpp
libvast/test/format/zeek.cpp
libvast/test/system/sink.cpp
libvast/vast/defaults.hpp
libvast/vast/detail/make_io_stream.hpp
libvast/vast/format/arrow.hpp
libvast/vast/format/ascii.hpp
libvast/vast/format/json.hpp
libvast/vast/format/null.hpp
libvast/vast/format/reader.hpp
libvast/vast/format/zeek.hpp
libvast/vast/schema.hpp
libvast/vast/system/import_command.hpp
libvast/vast/system/make_source.hpp
libvast/vast/system/spawn_source.hpp
vast/integration/default_set.yaml

The options `listen`, `read`, `schema`, `schema-file`, `type`, and `uds` can from now on be supplied to the `import` command directly. They can still be used after the format subcommand, but that usage is deprecated.
By commit.

Move options from format to the import subcommand

---

CHANGELOG.md
libvast/src/system/index.cpp
libvast/src/system/partition.cpp
libvast/src/system/spawn_index.cpp
libvast/test/flatbuffers.cpp
libvast/test/system/counter.cpp
libvast/test/system/eraser.cpp
libvast/test/system/exporter.cpp
libvast/test/system/index.cpp
libvast/vast/fbs/synopsis.fbs
libvast/vast/system/actors.hpp
libvast/vast/system/index.hpp
libvast/vast/system/partition.hpp
vast.yaml.example

Introduce a new `PartitionSynopsis` top-level flatbuffer and use that to split out the meta index state into separate files.
Note that the idea is to keep this as a backwards-compatible change, so no versions are bumped.
Review commit-by-commit.

Store partition synopses in separate files

---

libvast/src/system/accountant.cpp

No more
```
imorter adds anonymous source
...
imorter removes anonymous source
```

Turn the accountant into a named source

---

cmake/VASTGitVersion.cmake

A fix for the CMake version tag helper to handle `-DVAST_VERSION_TAG` correctly.

Fix the embedded version string for static

---

CHANGELOG.md
libvast/src/detail/settings.cpp
libvast/src/logger.cpp
libvast/src/system/spawn_disk_monitor.cpp
libvast/vast/defaults.hpp
libvast/vast/detail/settings.hpp
vast.yaml.example

This PR adds minimal configurability to the rotating file sink used for spdlog.
It adds the option `vast.log-rotation` to turn off rotation, which is required for production use where VAST's log rotation may interfere with log rotation configured in external programs like systemd or logrotated.
The size threshold, number of rotated log files, and whether to use time-based logrotate are not made configurable, since we did not have anyone asking for these features yet.

Make log rotation configurable

---

examples/plugins/example/example.cpp
libvast/vast/plugin.hpp

In order to avoid cyclic dependencies between type definitions and actor definitions, it is sometimes necessary to define two type ID blocks. This change enables plugins to use up to two type ID blocks.
n/t

Allow plugins to define up to two type ID blocks

---

CHANGELOG.md
libvast/src/schema.cpp

This change allows users to specify additional schema files in `<SYSCONFDIR>/vast/schema` and `<XDG_CONFIG_HOME>/vast/schema`.
The directory `<XDG_DATA_HOME>/vast/schema` is no longer considered for additional schema files.
n/t

Read user-supplied schema files from config dirs

---

CHANGELOG.md
libvast/src/schema.cpp
libvast/src/system/application.cpp
libvast/src/system/read_query.cpp

This PR
- removes the invalid `vast.spawn.importer.ids` option,
- removes the deprecated `vast.schema-paths` option,
- disallows spreading a query over multiple arguments, and
- fixes read_query for single argument queries for the pivot command.
File-by-file.

Remove long-deprecated code

---

CHANGELOG.md
libvast/src/system/spawn_index.cpp
vast.yaml.example

For consistencies' sake. We did not release this yet, so I'm not adding a deprecation warning.
It's a simple change. I've enabled auto-merge.

Rename vast.meta-index-path to vast.meta-index-dir

---

configure
vast/CMakeLists.txt
vast/vast.cpp

This commit adds a `--with-plugin-autoloading` option to `configure` and a corresponding `VAST_ENABLE_PLUGIN_AUTOLOADING` option to CMake that configures VAST such that all plugins built alongside VAST are enabled by default.
File-by-file.
I've tested this thoroughly locally with 0, 1, 2, and 3 plugins, and also tested locally that the deduplication works. This is really nice for the plugin development workflow.

Add a build-time option to always load all plugins

---

libvast/vast/concept/support/detail/sequence.hpp
libvast/vast/detail/type_traits.hpp
libvast/vast/factory.hpp

Problem:
- Detection idiom traits are hand-rolled in `type_traits.hpp` but they
are widely available in standard libraries now.
Solution:
- Use detection idiom traits from Library Fundamentals v2 in standard
library. Remove hand-rolled ones in `type_traits.hpp`.
File-by-file.

Use detection idiom from standard library

---

CHANGELOG.md
libvast/src/accountant/config.cpp
libvast/src/system/accountant.cpp
libvast/vast/accountant/config.hpp
vast.yaml.example

This PR contains three changes:
- It replaces underscores with dashes in `vast.metrics.*` options to be consistent with other options.
- It removes the unused `vast.metrics.enable` option. Use `vast.enable-metrics` instead.
- It adds new options `vast.metrics.{file,uds}-sink.real-time` to enable real-time metrics reporting. This is disabled by default.
For @tenzir/backend: Review code file-by-file. Please also review the related documentation PR.
For @0snap, who requested this feature: Run locally and see if this suits your needs. You can create a static binary for this branch on-demand with the new "Run workflow" button on the [actions page for the `VAST Static` workflow](https://github.com/tenzir/vast/actions?query=workflow%3A%22VAST+Static%22). **Edit:** I've done this, you can [find …

Enable real-time metrics reporting

---

schema/types/suricata.schema

This adds `#ioc` attributes to relevant fields for the matcher plugin to our Suricata schema.
n/t

Add #ioc attributes to bundled Suricata schema

---

CHANGELOG.md
libvast/src/system/evaluator.cpp
libvast/src/system/partition.cpp
libvast/test/system/evaluator.cpp
libvast/vast/system/evaluator.hpp

This reverts commit 3c932137af3398737d8e8ed18c46c141b2b191dc.
We empirically verified that this fixes a segfault that can occur when running an export containing a partition that is ejected from the LRU cache while the export is going on, but I don't really understand the root cause so far :'(

Revert "Fix potential race condition between evaluator and partition"

---

CHANGELOG.md
libvast/src/command.cpp
scripts/vast-completions.bash

Interestingly, we did this already for the `manual` command. The idea is that users that explicitly request `help` or `documentation` are interested in getting the result as result—not on a side channel.

Render help and documentation on stdout

---

configure

This aligns the `configure` wrapper script with CMake options (again).
n/t

Fix misalignment of configure and CMake options

---

CHANGELOG.md
libvast/src/format/json.cpp
libvast/vast/format/json.hpp

Let the JSON reader recover from unexpected inputs

---

libvast/vast/byte.hpp

Problem:
- `to_byte` with an argument delegates to an impl function template to
provide a nice error when the type isn't an `unsigned char`. This level
of indirection is unnecessary.
Solution:
- Use `if constexpr` and `always_false_v` to achieve the same goal.
File-by-file.

Simplify to_byte overloads

---

CHANGELOG.md
libvast/src/logger.cpp
libvast/vast/defaults.hpp
vast.yaml.example

This makes the logger queue size configurable, and increases its default size from 8192 to 32768.
n/t

Add vast.log-queue-size option

---

libvast/vast/defaults.hpp
vast.yaml.example

Change default vast.log-queue-size to 1M

---

libvast/src/detail/sigma.cpp
libvast/src/expression.cpp
libvast/src/system/eraser.cpp
libvast/src/system/spawn_arguments.cpp
libvast/vast/expression.hpp
libvast/vast/system/make_source.hpp

These functions copy by design, so it should be made clear from their interface that they copy. Additionally, this allows for moving the expression into the function, which removes the need to copy entirely.
File-by-file.

Improve API for copying expression utilities

---

libvast/src/system/connect_to_node.cpp

I saw `scoped_actor successfully connected to 0.0.0.0:42020/tcp` in the logs, which is fixed by this PR among some other log message fixups in the same function.
n/t

Clarify log messages when connecting to node

---

libvast/src/directory.cpp
libvast/vast/directory.hpp

Problem:
- `vast::directory::filter_dir` has a `detail::function` type as a
function parameter but this dependency on the 3rd party adopted
`function` type is overkill.
Solution:
- Use `std::function` directly.
Note:
- There is now only one place in the codebase (`chunk.hpp`) that has a
dependency on the 3rd party `function.hpp`. This is for storing the
function as a nonstatic data member. It is not trival to use
`std::function` here since the stored function is not allowed to be
marked `noexcept`. However, if we remove the `noexcept` requirement on the
deleter function, this breaks other things.
File-by-file.

Remove dependency on 3rd party function for vast::directory

---

libvast/src/data.cpp
libvast/test/data.cpp
libvast/vast/data.hpp

Add a recursion limit for flattening records.
NOTE: This is a quite minimalistic implementation of the corresponding story:
- There are still `make_record()`, `merge()` and `convert()` in the same header that will do unbounded recursion.
- While implementing I had the impression that it would make sense to have a "maximum record nesting depth" that is applied regardless of how whether the functions are implemented using recursion or not. (ie. now flatten() and unflatten() are asymmetric because the latter is implemented without recursion)
However, in particular the second point would require a bit more comprehensive change to catch all places, so I decided to put up this PR first so we can decide together how much more effort we want to invest.

Add recursion limit for calls to flatten()

---

libvast/CMakeLists.txt
libvast/src/config.cpp.in
libvast/src/detail/signal_handlers.cpp
libvast/src/plugin.cpp
libvast/src/system/connect_to_node.cpp
libvast/src/system/node.cpp
libvast/src/system/version_command.cpp
libvast/vast/config.hpp.in
libvast/vast/plugin.hpp

This avoids recompiling large parts of VAST when the version of build tree hash change.

Reduce number of TUs dependent on the build version

---

libvast/CMakeLists.txt
libvast/src/directory.cpp
libvast/src/system/disk_monitor.cpp
libvast/vast/directory.hpp

Problem:
- `recursive_size` has its own logic for "recursing" directories to get
the total size of files, but this can be implemented directly more or
less using `std::filesystem`.
Solution:
- Use `std::filesystem::recursive_directory_iterator` to do the heavy
lifting of recursing into directories.
Note:
- This requires linking explicitly with `stdc++fs` flag for GCC < 9.1.0.
File-by-file.

Simplify directory recursive_size function

---

CHANGELOG.md
libvast/src/schema.cpp
libvast/src/system/application.cpp
vast.yaml.example

The option is no longer needed since types can now be overridden in later schema directories.
File-by-file.

Deprecate the vast.no-default-schema option

---

.github/workflows/style-check.yaml

This will cause the Style Check to run properly PRs from external contributors. At some point, we should fix all of them.
n/t

Fix style check for PRs from external contributors

---

cmake/VASTGitVersion.cmake

See e4fb51c85ec9ff7d7712e72be9caf6bca45448c6 for why this is neccessary—apparently, we accidentally removed this during a refactoring.
n/t

Fix length of the abbreviated commit hash (again)

---

libvast/src/directory.cpp
libvast/src/system/disk_monitor.cpp
libvast/src/system/spawn_disk_monitor.cpp
libvast/vast/directory.hpp
libvast/vast/system/disk_monitor.hpp

Problem:
- `recursive_size` function uses `std::filesystem` in its
implementation, but its function argument and usage from callers still
use `vast::path`.
Solution:
- Switch to `std::filesystem::path` for the function argument and
convert callers to use `std::filesystem` equivalents.
- Fix additional uses of `vast::path` in favor of
`std::filesystem::path` throughout `disk_monitor` to keep things simple
rather than converting between the path types where required.
This gets us one step closer to removing `vast::directory` entirely in favor of `std::filesystem` equivalents.
File-by-file.

Migrate recursive_size to use std::filesystem

---

libvast/vast/detail/logger_formatters.hpp

Simplify uuid formatter

---

CHANGELOG.md
libvast/src/concept/parseable/vast/type.cpp
libvast/src/format/csv.cpp
libvast/src/schema.cpp
libvast/src/type.cpp
libvast/test/schema.cpp
libvast/test/type.cpp
libvast/vast/concept/parseable/vast/schema.hpp
libvast/vast/type.hpp
schema/types/suricata.schema

We introduce 4 operations that can be used on record types or type aliases (the underlying type must be a record too):
- `record + record`: Combine the fields of 2 records into a new record
- `record <+ record`: Like `+`, but prefer the left operand in case of a field name clash.
- `record +> record`: Like `+`, but prefer the right operand in case of a field name clash.
- `record - field_name`: Remove the field named `field_name` from a record.
By commit.

Add support for algebraic expressions on record types

---

libvast/src/system/disk_monitor.cpp
libvast/vast/detail/logger_formatters.hpp
libvast/vast/detail/type_traits.hpp

The standard library for the static build seems be missing the ostream operator<< overload for some std::filesystem stuff.
**Edit:** Actually it did have them hidden behind implicit conversions, but {fmt} 7 is more strict about `has_formatter` than old versions, and that caused our SFINAE for the fallback formatters not to pick it up.
I've manually triggered a static build run for this branch: https://github.com/tenzir/vast/actions/workflows/static-binary.yaml?query=branch%3Atopic%2Ffix-static-build

Fix the static build

---

libvast/src/data.cpp
libvast/src/directory.cpp
libvast/src/schema.cpp
libvast/src/system/spawn_disk_monitor.cpp
libvast/src/system/type_registry.cpp
libvast/vast/data.hpp
libvast/vast/directory.hpp
libvast/vast/schema.hpp

Problem:
- `filter_dir` uses `vast::path` when `std::filesystem::path` suffices.
Solution:
- Change `filter_dir` API to use `std::filesystem::path`. Adjust callers
to use `std::filesystem::path` throughout their respective call def
chain.
File-by-file.

Use std::filesystem for filter_dir and callers

---

.clang-tidy

This is a proposal for which clang-tidy checks can be enabled on VAST.
I'm using a blacklist approach here. Everything is enabled, and checks that don't fit our style are explicitly disabled. That comes with the advantage that newly introduced checks will be discovered automatically. But it is certainly not the way clang-tidy is intended. When a check is explicitly disabled, all redirects to the same check must be disabled as well.

RFC: Add a clang-tidy configuration file

---

.clang-tidy
libvast/src/detail/load_plugin.cpp
libvast/src/plugin.cpp
libvast/src/system/index.cpp
libvast/vast/detail/assert.hpp
libvast/vast/detail/logger_formatters.hpp
libvast/vast/logger.hpp
libvast/vast/plugin.hpp
libvast/vast/system/index.hpp

This is just me playing with #1417.
File-by-file.

Handle some clang-tidy warnings

---

libvast/src/data.cpp
libvast/src/directory.cpp
libvast/src/schema.cpp
libvast/src/system/disk_monitor.cpp
libvast/vast/detail/filter_dir.hpp
libvast/vast/detail/recursive_size.hpp
libvast/vast/directory.hpp

Problem:
- `filter_dir` is a free function in `directory.hpp`, but
`vast::directory` and thus `directory.hpp` will be going away soon.
- `recursive_size` is a free function in `directory.hpp`, but
`vast::directory` and thus `directory.hpp` will be going away soon.
Solution:
- Move `filter_dir` into a new header: `vast/detail/filter_dir.hpp`.
Mark the function inline since it's in a header file. In the future,
`filter_dir` ought to be templated on the filter to avoid having to
use `std::function`. This would give a slight runtime performance
since callers always pass lambdas now. This will be revisited in a
future PR.
- Move `recursive_size` into a new header:
`vast/detail/recursive_size.hpp`. Mark the function inline since it's in
a header file.

Move free functions out of directory.hpp

---

.clang-tidy
libvast/src/data.cpp
libvast/vast/data.hpp
libvast/vast/detail/type_traits.hpp

Handle clang-tidy warning for vast::data

---

libvast/src/io/save.cpp
libvast/src/path.cpp
libvast/src/segment_store.cpp
libvast/src/system/index.cpp
libvast/src/system/spawn_node.cpp
libvast/test/filesystem.cpp
libvast/test/format/pcap.cpp
libvast/vast/path.hpp
libvast_test/src/actor_system.cpp
libvast_test/vast/test/fixtures/filesystem.hpp

Problem:
- `rm` function for `vast::path` is implemented in terms of
`vast::directory` which is going away soon.
Solution:
- Remove `rm` member function from `vast::path` entirely. Replace call
sites with `std::filesystem::remove_all` to preserve the previous
behavior of deleting all files if the file is a directory.
File-by-file.

Remove vast::rm

---

libvast/vast/aliases.hpp

Problem:
- Some type aliases in `vast/aliases.hpp` are unused.
Solution:
- Remove unused type aliases.

Remove unused type aliases from aliases.hpp

---

libvast/src/chunk.cpp
libvast/src/io/save.cpp
libvast/src/io/write.cpp
libvast/src/segment_store.cpp
libvast/src/system/archive.cpp
libvast/test/chunk.cpp
libvast/test/segment_store.cpp
libvast/vast/chunk.hpp
libvast/vast/io/save.hpp
libvast/vast/io/write.hpp
libvast/vast/segment_store.hpp

Problem:
- `segment_store` uses `vast::path` which is going away soon.
Solution:
- Use `std::filesystem::path` throughout in `segment_store`.
Note:
- This adds an overload for `save` on both path types. The next step
would be to fix other callers of `save` to not use `vast::path` and
instead use `std::filesystem::path`.
File-by-file.

Remove vast::path use in segment_store

---

libvast/src/path.cpp
libvast/test/filesystem.cpp
libvast/vast/path.hpp

Problem:
- `trim` member function for `vast::path` is unused.
Solution:
- Remove `trim` member function for `vast::path`.
File-by-file.

Remove trim function from vast::path

---

CHANGELOG.md
libvast/src/expression_visitors.cpp
libvast/src/system/meta_index.cpp

Create a db with the 2021.01.28 and run `:timestamp` queries with a build from this PR.

Fix :timestamp queries for old data

---

libvast/src/path.cpp
libvast/test/filesystem.cpp
libvast/vast/path.hpp

Problem:
- `chop` member function for `vast::path` is unused and `vast::path` is
going away soon.
Solution:
- Remove unused `chop` member function for `vast::path`.
File-by-file.

Remove chop member function from vast::path

---

libvast/src/path.cpp
libvast/vast/path.hpp

Problem:
- `create_symlink` member function for `vast::path` is unused and
`vast::path` is going away soon.
Solution:
- Remove unused `create_symlink` member function for `vast::path`.
File-by-file.

Remove create_symlink member function from vast::path

---

libvast/src/detail/load_plugin.cpp
libvast/src/detail/process.cpp
libvast/src/path.cpp
libvast/src/schema.cpp
libvast/src/system/application.cpp
libvast/test/filesystem.cpp
libvast/vast/detail/load_plugin.hpp
libvast/vast/detail/process.hpp
libvast/vast/path.hpp
vast/vast.cpp

Problem:
- When loading plugins, there is use of `vast::path` which is going away
soon.
Solution:
- Use `std::filesystem::path` throughout when loading plugins.

Remove dependency on vast::path in load_plugin

---

.github/workflows/static-binary.yaml
nix/static-binary.sh
nix/vast/default.nix

This doesn't support plugins in the static binary yet, because that needs a few adjustments in the loading mechanism, and they need to be baked in properly.
To enable inclusion of plugins one can simply call
```
nix/static-binary.sh plugin otherplugin
```

Add support for plugins in the nix-based build

---

CHANGELOG.md
libvast/src/format/json.cpp
libvast/test/format/json.cpp

If the schema says string but the data is numerical, we call `to_string` instead of failing.

Accept numbers in place of strings in JSON

---

CHANGELOG.md
libvast/src/partition_synopsis.cpp
libvast/src/system/meta_index.cpp
libvast/vast/system/meta_index.hpp

We can take advantage of the fact that all string fields are covered by the same type level synopsis. To be more specific: A query like `suricata.smb.host == "foo" || suricata.ssh.host == "foo"` would check whether the string "foo" is included the same type-level string synopsis twice.
This PR adds a preprocessing step that removes predicates with duplicate strings from the expression as a preprocessing step for meta index lookups.
In my local comparisons with 12723 partitions with `eve.log` data I get the a 4 times speedup for the query `vast export null 'net.domain == "alhgeoafh" || net.hostname == "alhgeoafh"'`.
A release build on master finishes the command in ~ 930 ms, this branch is done after ~ 240 ms.
Try to reproduce my results.

Prune expressions for the meta index lookup

---

CHANGELOG.md

Add a changelog entry

---

libvast/src/io/save.cpp
libvast/src/system/index.cpp
libvast/src/system/posix_filesystem.cpp
libvast/src/system/spawn_type_registry.cpp
libvast/src/system/type_registry.cpp
libvast/test/system/exporter.cpp
libvast/test/system/type_registry.cpp
libvast/vast/io/save.hpp
libvast/vast/system/type_registry.hpp

Problem:
- There is an `io::save` overload for `vast::path` but `vast::path` is
going away soon.
Solution:
- Remove `io::save` overload for `vast::path`. Adjust callers
appropriately to work with `std::filesystem::path`.
File-by-file.

Remove io::save overload for vast::path

---

libvast/src/detail/pid_file.cpp
libvast/src/system/spawn_node.cpp
libvast/vast/detail/pid_file.hpp

Problem:
- `pid_file` depends on `vast::path` which is going away soon.
Solution:
- Replace `vast::path` use with `std::filesystem::path` in `pid_file`.
File-by-file.

Remove dependency on vast::path in pid_file

---

libvast/src/command.cpp

Problem:
- Having a using directive in an anonymous namespace doesn't buy us much
here and can only cause confusion later perhaps when reasoning about
type or function resolution.
Solution:
- Qualify the two uses in this file with `std::accumulate` to be
explicit.
File-by-file.

Avoid using declarative in anonymous namespace in command.cpp

---

CHANGELOG.md
libvast/vast/plugin.hpp

We only test the single argument version in CI, so this slipped through until I tried to actually use it.
n/t

Fix VAST_REGISTER_PLUGIN_TYPE_ID_BLOCK_2

---

CHANGELOG.md
libvast/src/system/accountant.cpp
libvast/src/system/archive.cpp
libvast/src/system/importer.cpp
libvast/src/system/sink.cpp
libvast/vast/system/source.hpp

Previously, VAST skipped metrics reports for the archive, importer, source, and sink components when they handled 0 events since the last metric report. This made it impossible to distinguish on metrics dashboards whether a component was offline or idle. Instead, VAST now properly reports 0 events while idle.
File-by-file.

Report metrics while idle

---

CHANGELOG.md
libvast/src/accountant/config.cpp
libvast/vast/accountant/config.hpp
libvast/vast/defaults.hpp
vast.yaml.example

Since the default partitions size is a power of 2 it makes sense to do the same for the default batch size.

Change the default batch size to 1024

---

CHANGELOG.md
libvast/src/system/disk_monitor.cpp
libvast/vast/detail/recursive_size.hpp

This make `recursive_size` return an error instead of throw a (then unhandled) exception. The underlying root cause will need to be eliminated in a separate PR—it's not that simple to fix.
File-by-file.

Fix possibly unhandled exception in disk monitor

---

vast.yaml.example

A leftover from before simdjson was made mandatory.

Remove simdjson keys from the example config file

---

libvast/src/chunk.cpp
libvast/src/db_version.cpp
libvast/src/io/read.cpp
libvast/src/system/index.cpp
libvast/src/system/posix_filesystem.cpp
libvast/src/system/spawn_node.cpp
libvast/src/system/type_registry.cpp
libvast/test/chunk.cpp
libvast/test/system/filesystem.cpp
libvast/vast/chunk.hpp
libvast/vast/db_version.hpp
libvast/vast/io/read.hpp
tools/lsvast/lsvast.cpp

Problem:
- `io::read` depends on `vast::path` which is going away soon.
Solution:
- Have `io::read` work with `std::filesystem::path` instead.
File-by-file.

Change io::read to use std::filesystem::path

---

tools/lsvast/lsvast.cpp

Problem:
- `lsvast` includes `<vast/path.hpp>` but doesn't need to. It has been
converted completely over to using `std::filesystem::path`.
Solution:
- Remove the unused include.

Remove unneeded <vast/path.hpp> include in lsvast

---

CHANGELOG.md
libvast/src/expression_visitors.cpp
libvast/src/type.cpp
libvast/test/flatbuffers.cpp
libvast/test/type.cpp

Don't allow field extractors to match field name suffixes

---

CHANGELOG.md

This was an oversight—I meant to remove that when sorting by category in the release prep.
🤷‍♂️

Remove emoji noise in 2021.02.24 changelog

---

libvast/vast/logger.hpp

This fixes a regression introduced during the spdlog refactoring. Noticed this when trying to compile with `--log-level=quiet`.
Read code. Run locally.

Fix unused args warnings for builds w/ quiet logs

---

CHANGELOG.md
libvast/src/system/type_registry.cpp

Change 2 use sites of `exists()`.

Use non-throwing std::filesystem functions in the type registry

---

tools/lsvast/lsvast.cpp

Problem:
- `std::error_code` value is cleared explicitly unncessarily. It is not
necessary since the call to `std::filesystem::is_regular_file` in the
case above when the path is a directory already clears the
`std::error_code` in the case of no errors.
Solution:
- Do not clear the `std::error_code` explicitly.

Remove unnecessary clearing of std::error_code in lsvast

---

libvast/src/format/pcap.cpp
libvast/vast/format/pcap.hpp

Problem:
- `pcap` reader uses raw pointers which doesn't express ownership
semantics to new readers of the code.
Solution:
- Use `std::unique_ptr` with an appropriate custom deleter.
- Add move and move assignment constructors to the pcap reader so it can
be moved still.

Prefer std::unique_ptr in pcap reader

---

CMakeLists.txt
libvast/CMakeLists.txt

This bug is very recent, so I don't think it needs a changelog entry.

Fix the reported VAST version when using version overrides

---

vast/integration/integration.py

This was the wrong way around: Expected timeouts were logged as errors, and unexpected timeouts were logged as debug messages.
n/t

Fix log level of timeouts in integration tests

---

CHANGELOG.md
libvast/src/system/component_registry.cpp
libvast/src/system/node.cpp
libvast/vast/system/component_registry.hpp

This PR attempts to fix an assertition failure in the DOWN handler in the node. The invariant should be that components in the registry are always monitored.

Attempt to fix assertition failure in component shutdown handler

---

CHANGELOG.md
libvast/src/system/node.cpp
libvast/src/system/partition.cpp

This fixes a recently introduced bug—the shutdown was not working while imports were still running.
n/t

Fix shutdown with importers running

---

CHANGELOG.md
libvast/vast/concept/parseable/vast/schema.hpp

See title, I will add an integration test in a follow up PR.
Convince yourself that `local_set` must be a reference instead of a copy in the symbol resolver.

Fix type operations on user configured schema dirs

---

CHANGELOG.md
libvast/src/system/type_registry.cpp
libvast/src/type.cpp
libvast/vast/concept/parseable/vast/schema.hpp
libvast/vast/type.hpp

The mutating implementation relied on a buggy overload of `get_if` that broke the type registry. This overload is now commented out with an explanatory comment so it won't accidentally get reintroduced.
By commit.

Make remove_field a non-mutating operation

---

schema/types/suricata.schema

As reported by @satta.
This is a very small fix, so I suggest we sneak this into the release.

Fix type of suiricata.rdp.rdp.reason

---

CHANGELOG.md
libvast/src/system/node.cpp
libvast/src/system/spawn_node.cpp
libvast/vast/system/disk_monitor.hpp

This fixes a bug that blocks the server process from exiting after a shutdown was initiated.

Make the disk-monitor a singleton component

---

.github/workflows/style-check.yaml
libvast/src/format/pcap.cpp
libvast/vast/format/pcap.hpp

Before this change, we linked against libpcap privately, but used it in our public headers—that's a bug. This change makes it a truly private dependency.
File-by-file. Confirm private linkage against `vast-test` and `libvast` targets.
The second commit update the style-check workflow a bit because my local clang-format-11 and clang-format-9 in CI were in disagreement.

Avoid using privately linked libpcap publicly

---

.github/workflows/jupyter.yaml
.github/workflows/pyvast.yaml
.github/workflows/static-binary.yaml
.github/workflows/vast-docker.yaml
.github/workflows/vast.yaml

Per internal discussion, we do not want to run all workflows for prereleases, e.g., the pyvast release.
File-by-file. To be reviewed by @0snap.

Ignore some workflows for prereleases

---

libvast/src/format/zeek.cpp
libvast/vast/format/zeek.hpp

Problem:
- `zeek` writer uses `vast::path` which is going away soon.
Solution:
- Change `zeek` writer to use `std::filesystem::path` instead.
File-by-file.

Remove dependency on vast::path in zeek writer

---

libvast/src/db_version.cpp
libvast/src/system/spawn_node.cpp
libvast/vast/db_version.hpp

Problem:
- `db_version` depends on `vast::path` which is going away soon.
Solution:
- Change `initialize_db_version` to work with `std::filesystem::path`.
File-by-file.

Remove dependency on vast::path in db_version

---

CMakeLists.txt
cmake/VASTConfigVersion.cmake

This makes the necessary changes to support CMake 3.20.

Use policies from CMake 3.20

---

libvast/src/detail/make_io_stream.cpp
libvast/src/system/accountant.cpp
libvast/vast/detail/make_io_stream.hpp

Problem:
- `make_io_stream` depends on `vast::path` which is going away soon.
Solution:
- Convert uses of `vast::path::path_type` to `std::filesystem::file_type`.
- Switch use of `vast::path::exists` to `std::filesystem::exists`.
File-by-file.

Remove dependency on vast::path from make_io_stream

---

libvast/src/arrow_table_slice_builder.cpp
libvast/src/msgpack_table_slice_builder.cpp
libvast/vast/arrow_table_slice_builder.hpp
libvast/vast/msgpack_table_slice_builder.hpp

This change adds a local cache for the binary serialized layout to table slice builders. The cached buffer will be used to avoid repeated invocations of the binary serializer.

Cache serialized layouts in slice builders

---

CHANGELOG.md
schema/types/suricata.schema

Add a new schema record type for Suricata's `rfb` event type.
There should not be any required updates to the reference files, at least `build/vast/integration_RelWithDebInfo.sh -u` did not change anything in the repo. Please double-check if that's the case.

Add `suricata.rfb` schema type

---

libvast/src/data.cpp
libvast/src/detail/load_contents.cpp
libvast/src/detail/pid_file.cpp
libvast/src/path.cpp
libvast/src/schema.cpp
libvast/src/system/configuration.cpp
libvast/src/system/spawn_arguments.cpp
libvast/vast/detail/load_contents.hpp
libvast/vast/path.hpp

Problem:
- Callers of `load_contents` are forced to construct a `vast::path` even
if they are already working with a `std::filesystem::path`. This is
because `load_contents` is coupled to only work with `vast::path`
currently.
Solution:
- Move `load_contents` into its own header since it is a useful function
even after `vast::path` is removed. Make it a function template so it
can easily work on different path types such as
`std::filesystem::path` and `vast::path`. Eventually, once all callers
are using `std::filesystem::path`, we can make it a function rather
than a function template.
File-by-file.

Move load_contents out of path.hpp

---

libvast/src/bloom_filter_parameters.cpp
libvast/src/bloom_filter_synopsis.cpp
libvast/src/detail/load_contents.cpp
libvast/vast/address_synopsis.hpp
libvast/vast/bloom_filter_parameters.hpp
libvast/vast/bloom_filter_synopsis.hpp
libvast/vast/buffered_synopsis.hpp
libvast/vast/detail/load_contents.hpp
libvast/vast/hasher.hpp
libvast/vast/string_synopsis.hpp

Per our contributing guide.
File-by-file.

Use "vast/..." over <vast/...> consistently

---

libvast/src/detail/pid_file.cpp
libvast/src/system/accountant.cpp
libvast/vast/system/type_registry.hpp

Problem:
- Some files include `vast/path.hpp` but it is not needed.
Solution:
- Remove extraneous include of `vast/path.hpp`.
File-by-file.

Remove some unused vast/path.hpp includes

---

CHANGELOG.md
libvast/src/schema.cpp
libvast/src/system/application.cpp

This removes the option entirely after we deprecated it with the last release.
File-by-file. The docs were already updated when we deprecated the option.

Remove deprecated no-default-schema option

---

libvast/src/chunk.cpp
libvast/src/path.cpp
libvast/src/segment_store.cpp
libvast/src/system/index.cpp
libvast/src/system/posix_filesystem.cpp
libvast/src/system/spawn_index.cpp
libvast/test/system/counter.cpp
libvast/test/system/eraser.cpp
libvast/test/system/exporter.cpp
libvast/test/system/index.cpp
libvast/vast/chunk.hpp
libvast/vast/path.hpp
libvast/vast/system/index.hpp

See commits one-by-one for the independent, isolated changes. This changes `chunk`'s `mmap` to work on `std::filesystem::path` instead of `vast::path`. When updating the callers in system index, that motivated the change of converting its internal uses of `vast::path` to be `std::filesystem::path`.

Minimize path conversions for chunk mmap and system index

---

libvast/src/file.cpp
libvast/src/io/read.cpp
libvast/src/io/write.cpp
libvast/test/filesystem.cpp
libvast/vast/file.hpp
libvast/vast/io/write.hpp
tools/dscat/dscat.cpp

Problem:
- `vast::file` depends on `vast::path` which is going away soon.
Solution:
- Switch to using `std::filesystem::path` as the path type for
`vast::file`.
File-by-file.

Remove dependency of vast::path from vast::file

---

libvast/src/system/index.cpp

Don't wait for unpersisted partitions when notifying flush listeners

---

libvast/src/chunk.cpp
libvast/src/segment_store.cpp
libvast/src/system/index.cpp
libvast/src/system/posix_filesystem.cpp
libvast/vast/chunk.hpp

Problem:
- There are multiple ways that `chunk::mmap` can not succeed. In some
cases, it logs and returns a `nullptr`, and in other cases, just returns
a `nullptr`. In the former case, this can lead to duplicate logging
since the callers of `mmap` already log on failure. However, the
callers lack sufficient information as to exactly which of the calls
inside `mmap` made it fail.
Solution:
- Change the return type of `chunk::map` to leverage `caf::expected` so
we can carry the error message back to the callers so it is known
exactly what failed when trying to perform the mmap operation.
File-by-file.

 Use expected for chunk::mmap

---

libvast/src/type.cpp
libvast/test/type.cpp

Trying to hunt down a weird behavior I found while working on #1510 here.
The test in the first commit fails in the Debian Clang CI configuration and succeeds in all others. The second commit fixes it.

Fix congruency check for unspecified types

---

libvast/src/command.cpp
libvast/src/data.cpp
libvast/src/schema.cpp
libvast/src/system/configuration.cpp
libvast/src/system/indexer.cpp
libvast/src/system/spawn_arguments.cpp
libvast/src/system/spawn_disk_monitor.cpp
libvast/vast/system/disk_monitor.hpp
libvast/vast/system/indexer.hpp

Problem:
- Some `vast/path.hpp` includes are present but not needed.
Solution:
- Remove unused `vast/path.hpp` includes.
File-by-file.

Remove some unused vast/path.hpp includes 

---

libvast/src/logger.cpp
libvast/src/system/configuration.cpp
libvast/vast/system/configuration.hpp

Problem:
- System configuration and logger both depend on `vast::path` which is
going away soon.
Solution:
- Migrate both to using `std::filesystem::path`.
File-by-file.

Remove vast::path dependency from configuration and logger

---

libvast/src/io/write.cpp
libvast/vast/io/write.hpp

Problem:
- The `write` overload with `vast::path` is unused.
Solution:
- Remove `write` overload for `vast::path`.
File-by-file.

Remove write overload for vast::path

---

libvast/src/schema.cpp
libvast/vast/schema.hpp

Problem:
- `schema` depends on `vast::path` which is going away soon.
Solution:
- Switch uses to `std::filesystem::path`.
File-by-file.

Remove vast::path dependency for schema

---

libvast/src/detail/load_contents.cpp
libvast/vast/detail/load_contents.hpp

Problem:
- `load_contents` overload for `vast::path` is unused.
Solution:
- Remove `load_contents` overload for `vast::path`.
File-by-file.

Remove load_contents overload with vast::path

---

libvast/src/db_version.cpp
libvast/src/schema.cpp

Problem:
- Checking for whether the `error_code` is set or not is superflous as
the `bool` returned from `std::filesystem::exists` will be set to the
correct value. As such, checking just the bool is sufficient.
Solution:
- Remove checking of `err` as the test for whether the exist check
failed or not.
File-by-file.

Clean up filesystem error handling

---

libvast/src/data.cpp
libvast/src/schema.cpp

Problem:
- Callers of `filter_dir` specify a directory filter which looks at the
string representation of the filesystem path to see if it matches some
extension. This is a bit verbose and loses the strong nature of the
`std::filesystem::path` type representation.
Solution:
- Use `extension()` method for `std::filesystem::path` to achieve the
same intent.
File-by-file.

Simplify filter_dir callers

---

CHANGELOG.md
examples/plugins/example/integration/vast.yaml
libvast/src/detail/load_plugin.cpp
libvast/vast/detail/load_plugin.hpp
vast.yaml.example
vast/CMakeLists.txt

Plugins are able to set their name to anything they want, e.g., `libexample.so` can set its name to `notexample`. This change forces the names to be aligned, which will allow for reliably checking static plugins by name in the future.
Note that this is a *breaking change* for some configurations: When specifying dynamic plugins under `vast.plugins`, the `lib` prefix is now stripped. To load a plugin from any of the usual or explicitly specified directories, use the key `<name>` instead of `lib<name>`.
File-by-file.

Align plugin and library output names

---

CHANGELOG.md
libvast/src/command.cpp
libvast/src/system/application.cpp
libvast/vast/system/application.hpp
vast.yaml.example

This removes the previously deprecated format-specific options that are actually format-independent. They have been deprecated for over two months now (#1354), so it's fair game to remove them.
File-by-file.

Remove deprecated format-specific options

---

CHANGELOG.md
libvast/src/logger.cpp

When configuring spdlog we do different things for client and server. We distinguish between the two by checking whether the current subcommand we're running is `start`.
However, this returned a false positive for a plugin that had a command `<plugin> start`. This commit changes to checking whether the full name of the command we're running is `start`.
n/t

Fix start command detection for spdlog

---

CHANGELOG.md
libvast/src/system/configuration.cpp

This fixes an overzealous check for configuration files.
n/t

Avoid shutdown when config dirs are not readable

---

CHANGELOG.md
libvast/src/detail/load_plugin.cpp
libvast/vast/detail/load_plugin.hpp
vast/vast.cpp

This commit changes VAST to ignore plugins specified in the `vast.yaml` when static versions of them are already loaded.
Aside from being the correct thing to do, this fixes an issue with the integration test suite where plugin integration tests specify their name in a `vast.yaml` file used for their tests.
File-by-file. Note that this is based on #1527 and cannot work without that change.

Ignore static plugins when specified in config

---

CHANGELOG.md
libvast/src/format/csv.cpp
libvast/src/table_slice.cpp
libvast_test/src/table_slices.cpp

This fixes a crash with nested aliases in the CSV reader. To reproduce, replace the definition of `port` in `base.schema` like this:
```
type proxy = count
type port = proxy
```
Then import CSV data, e.g., 
```
gunzip -c vast/integration/data/csv/argus-M57-10k-pkts.csv.gz | vast -N import csv
```

Handle alias types properly for CSV

---

CHANGELOG.md
libvast/src/command.cpp
libvast/test/command.cpp

Fix out-of-bounds access in command-line parser
For some errors, the command-line parser returns `last`
as the position of the error which we must not dereference
when building an error message.
This bug was originally found by an automated fuzzing run
via Code Intelligence.

Fix out-of-bounds access in command-line parser

---

libvast/CMakeLists.txt

This PR silences a verbose CMake warning in case a bundled dependency is not found.
In one shot.

Suppress verbose CMake warning

---

CHANGELOG.md
cmake/VASTRegisterPlugin.cmake
libvast/src/schema.cpp

This fixes a particularly annoying issue: Plugins may bundle custom schemas, but running integration tests from externally built plugins did not pick them up because the plugins were in a separate build directory. Similarly to `VAST_PLUGIN_DIRS`, this adds a variable `VAST_SCHEMA_DIRS` that adds additional schema directories with high precedence.
File-by-file.

Fix external plugin tests with custom schemas

---

libvast/vast/detail/logger_formatters.hpp
libvast/vast/detail/type_traits.hpp

This fixes an ODR violation that we've seen with our static binaries.
Check that the error does not occur any longer for static builds. I've requested @tobim for review as he has a local Nix setup.

Fix ODR violation in custom fallback_formatter

---

CHANGELOG.md
examples/plugins/example/example.cpp
examples/plugins/example/integration/tests.yaml
libvast/src/plugin.cpp
libvast/src/system/importer.cpp
libvast/src/system/node.cpp
libvast/vast/plugin.hpp
libvast/vast/system/actors.hpp
libvast/vast/system/importer.hpp

It turns out that just having a handle to the NODE is already a valuable plugin. Such a plugin can spawn an actor and register itself with the NODE. That's it.
Other plugins, like the analyzer plugin, will then inherit from this plugin.
The component plugin only gives you the node actor and requires that you implement the status subscriber.
File-by-file.

Factor common functionality in component plugin

---

.github/workflows/jupyter.yaml
.github/workflows/vast.yaml
Dockerfile
examples/jupyter/scripts/run-demo

~This is (most likely) blocked until the next major release of Apache Arrow.~ It is not! The Apache foundation set up the mirror already.
Bintray is shutting down, and Artifactory is its replacement: https://lists.apache.org/thread.html/r9200fed3fa812f8c7de07a2500425f258db3231baa8e05f288175e4a%40%3Cbuilds.apache.org%3E
File-by-file.

Switch to Artifactory for installing Arrow

---

vast/integration/misc/scripts/count_partitions_plus1.sh

`/bin/bash` doesn't work on NixOS, but `/usr/bin/env` is mandated by Posix and does work.
Trivial.

Use /usr/bin/env in the disk monitor integration test

---

libvast/src/system/node_control.cpp
libvast/vast/system/node_control.hpp

This commit adds timeouts to the node control functions. We end up deadlocking if the request times out when connecting to a remote node.
This will aid in debugging the deadlock we're experiencing when an analyzer plugin uses `get_node_components` in its `make_analyzer` function.
File-by-file.

Use timeouts when controlling a remote node

---

examples/plugins/example/example.cpp
libvast/src/plugin.cpp
libvast/src/system/importer.cpp
libvast/src/system/node.cpp
libvast/src/system/spawn_importer.cpp
libvast/test/system/exporter.cpp
libvast/test/system/importer.cpp
libvast/vast/plugin.hpp
libvast/vast/system/importer.hpp

This allows for fixing a deadlock in a proprietary analyzer plugin caused by using `get_node_components<...>(self, node)` from within the NODE actor context by enabling use of `node->state.registry.find<...>()` instead.
n/t

Give component plugins access to the NODE state

---

cmake/VASTRegisterPlugin.cmake

It is not possible to add dependencies to the target `vast` when building plugins against an installed VAST.
This bug snuck into #1549.
n/t

Fix building external plugins

---

cmake/VASTRegisterPlugin.cmake

We recently changed VASTRegisterPlugin to only put shared plugin libraries into `lib/vast/plugins` in the build directory. We failed to account for running plugin integration tests from within the plugin's build directory. This commit adjusts the plugin integration test setup to correctly take the target file directory of the shared plugin library.
n/t

Fix running integration tests for standalone plugins

---

CMakeLists.txt
examples/plugins/example/CMakeLists.txt
plugins/pcap/CMakeLists.txt

This is a convenience change targeted at plugin developers. We override `find_package(VAST [...])` to be a no-op in subprojects (e.g., plugins built alongside VAST) such that they are not required to check whether the VAST target already exists before calling `find_package`.
The general idea here is that the plugin build scaffolding should be the same for all possible ways to build a VAST plugin. This removes the last manual check that plugin developers needed to do.
File-by-file.

Make find_package(VAST) a no-op for subprojects

---

CHANGELOG.md
CMakeLists.txt
libvast/src/detail/load_plugin.cpp
libvast/src/schema.cpp
libvast/src/system/application.cpp
libvast/src/system/configuration.cpp
libvast/vast/system/configuration.hpp
vast/CMakeLists.txt
vast/integration/integration.py

The new option `--disable-default-config-dirs` that may only be supplied on the command line disables the loading of user and system configuration, schema, and plugin directories. We use this option internally when generating VAST's man page and when running integration tests.

Make it possible to run VAST without user configs

---

.clang-tidy

The `altera-*` warnings had many false positives, and the `readability-function-cognitive-complexity` warning just doesn't work well with actor behaviors.
n/t

Disable bogus clang-tidy 12 warnings

---

changelog/unreleased/bug-fixes/1563.md
libvast/src/system/component_registry.cpp
libvast/src/system/node.cpp
libvast/vast/system/component_registry.hpp
libvast/vast/system/node.hpp

- Don't bail when receiving a down message during teardown
- We've been terminating non-essential components after the main
ones, but now we do it before.
- We don't try to terminate remote actors any more.
- The shutdown sequence used to treat labels as types, which means
the actor of the label wouldn't be terminated at all and keeping
the process alive.
By commit.

Multiple node shutdown fixes

---

changelog/unreleased/bug-fixes/1570.md
cmake/VASTVersion.cmake

This change makes it so we warn instead of fail on git-describe errors, falling back to the specified fallback version. This helps in situation where git and the source tree are available, but git-describe fails, e.g., when working from within a shallow clone.
n/t

Fix building VAST within a shallow git tree

---

changelog/unreleased/bug-fixes/1573.md
cmake/VASTRegisterPlugin.cmake
nix/static-binary.sh

Two smaller bug fixes:
- `nix/static-binary.sh` now works again when invoked from somewhere other than the repository root.
- The `VASTRegisterPlugin` CMake function now correctly removes the `ENTRYPOINT` from the given `SOURCES`.

Deduplicate plugin entrypoint in sources

---

cmake/VASTRegisterPlugin.cmake

Older CMake versions do not correctly set up the compilation database in the build directory as a configuration target, so without this change `cmake --build <path/to/build> --clean-first` is broken.
n/t

Remove broken dependency for compilation database

---

CMakeLists.txt
libvast/CMakeLists.txt

Make use of the platform-independent `CMAKE_DL_LIBS` over the platform-specific `dl` to link against the libraries containing `dlopen`, `dlsym`, `dlerror`, and `dlclose`.
This fixes an issue with older CMake versions on Linux, where we errored because `dl` may not be linked against the interface library `libvast_internal` that we use for propagating compiler flags. Instead, we now link against `libvast` publicly when building a shared library.
File-by-file.

Use platform-independent CMAKE_DL_LIBS over -ldl

---

libvast/src/system/disk_monitor.cpp

When a custom command is used to compute the size of
the database directory, the returned value does not
necessarily need to represent a number of bytes, so
dont mention the unit in log messages.

Remove mention of 'size' from disk monitor logs

---

libvast/src/detail/env.cpp
libvast/src/detail/load_plugin.cpp
libvast/src/schema.cpp
libvast/src/system/configuration.cpp
libvast/src/systemd.cpp
libvast/vast/detail/env.hpp

As indicated by clang-tidy, getenv and friends are not thread-safe. This adds wrapper functions that synchronize the calls to them.
File-by-file.

Synchronize calls to getenv

---

scripts/create-release

This adds a script that automates all the release prep work. I will demonstrate its usage shortly.
n/t

Add a script that automates release prep work

---

.github/workflows/jupyter.yaml
.github/workflows/vast.yaml
Dockerfile

This is an intermediate fix until the ASF completed the migration to Artifactory. Once that is done, we need to remove the `sed` and rename `apache-arrow-archive-keyring` to `apache-arrow-apt-source`.
n/t

Patch Arrow APT sources URLs

---

.cmake-format
CMakeLists.txt
cmake/VASTRegisterPlugin.cmake

This ensures that the compilation database is not just linked during build time, but also once already when configuring the build. 
Additionally, this deduplicates the required code in a `VASTExportCompileCommands(<target>)` CMake function and uses it for both plugins and VAST itself.
File-by-file.

Link compilation database during build time

---

changelog/unreleased/bug-fixes/1590.md
libvast/test/parseable.cpp
libvast/vast/concept/parseable/vast/si.hpp

Before this change, setting the disk monitor budget (and other things expecting a bytesize) failed with spaces between number and SI prefix, e.g., '1 MiB' rather than '1MiB'. We now generally ignore spaces between number and SI prefixes.
n/t

Ignore spaces before SI prefixes

---

.github/workflows/vast.yaml

Before this change, we only tested building shared and static plugin libraries alongside VAST in CI. This sets up a CI workflow that downloads a previously created VAST artifact, and builds and tests plugins against that. For now, this is only done for the example plugin.
File-by-file.

Test building external plugins in CI

---

changelog/unreleased/breaking-changes/1593.md
cmake/VASTRegisterPlugin.cmake
libvast/src/detail/load_plugin.cpp

To avoid confusion between the PCAP plugin and libpcap, which both have a library file named `libpcap.so`, we now prefix the plugin library output names with `vast-plugin-`. The PCAP plugin library file is now named `libvast-plugin-pcap.so`.
This is a breaking change: The output name of plugins changed, so plugins specified with a full path in `vast.plugins` must be adapted accordingly.
File-by-file.

Prefix plugin library output names with vast-plugin-

---

cmake/VASTVersion.cmake

We did this incorrectly before.
@lava please test if this fixes your issue.

Remove libvast/{aux,test} from build tree hash

---

cmake/VASTRegisterPlugin.cmake

A function introduces a new scope in CMake, so for the variable to be picked up
in project-wide scope we need to set it using the `PARENT_SCOPE` option.
@tobim test locally.

Set CMAKE_EXPORT_COMPILE_COMMANDS in project scope

---

cmake/VASTRegisterPlugin.cmake
examples/plugins/example/example.cpp
libvast/src/system/version_command.cpp
libvast/vast/plugin.hpp
plugins/pcap/main.cpp

- Add an `INCLUDE_DIRECTORIES` argument that takes multiple relative paths to include directories to the `VASTRegisterPlugin` CMake function.
- Safeguard against absolute `CMAKE_INSTALL_*DIR` variables, and annotate the `cmake_parse_arguments` call for easier understanding.
- Change the `VAST_REGISTER_PLUGIN` macro to take between one and five arguments, making passing of the version optional. If just the plugin is passed to the macro, the VAST version is used as the plugin version. If at least the major version is specified, zeroes are used for the unspecified parts of the version.

Enable custom include directories for plugins

---

cmake/VASTRegisterPlugin.cmake

In case a plugin specifies only header files in SOURCES we did not correctly create a stub source file. ~Now we always generate one instead of relying on any heuristics.~ This rewrites the base target for plugins not to have this dependency.
I verified locally that this works with a plugin I'm working on. It's an edge case, but I think we should handle this gracefully instead of letting the plugin developer run into a hard-to-understand linker error.

Allow for plugins to specify only headers as sources

---

.clang-format

This was generated by:
```bash
clang-format -dump-config > tmp
mv -f tmp .clang-format
```
Additionally, I changed the value of `SpaceAfterCStyleCast` to `false`, because that wrongly adds spaces in `(*this)(args...)`, which looks really odd.
n/t

Adapt .clang-format for clang-format 12

---

.clang-format

Apparently clang-format hard-errors when its config file contains unknown values for existing keys, so this is a second attempt at #1606 that just updates the one key that was causing issues.
:shrug:

Fix clang-format configuration for older clang-format versions

---

cmake/VASTRegisterPlugin.cmake
vast/CMakeLists.txt

For plugins built alongside VAST there was an undocumented and since recent changes unnecessary restriction that plugin name and directory name containing the plugin's top-level `CMakeLists.txt` file must be the exact same. This commit removes that restriction, and as an added bonus allows the CMake variable `VAST_PLUGINS` to be specified using paths relative to the repository root instead of always requiring absolute paths.
File-by-file.

Remove dependency between directory and plugin name

---

CMakeLists.txt

VAST's own module path should always come first. Not doing so can be an issue when building VAST as a subproject.
Read the commit message and reason about it.

Fix CMAKE_MODULE_PATH when using VAST as subproject

---

vast/vast.cpp

Ran into this and did not expect VAST to just start with a default-initialized plugin. Let's abort when the configuration is invalid.
It's a very simple change, so just read it and confirm that this is what we want.

Fail if plugin configuration is invalid

---

changelog/unreleased/bug-fixes/1618.md
libvast/vast/plugin.hpp
libvast_test/src/main.cpp
vast/vast.cpp

There's no point in `plugin::initialize()` returning an error if it's never checked. So let's actually check and refuse to start if any plugin fails to initialize.
The change is really simple, so looking at the code should suffice.

Error when initializing a plugin fails

---

cmake/VASTRegisterPlugin.cmake
libvast/src/system/application.cpp

This is a collection of smaller plugin framework fixups that I came across today while working on a plugin.
Commit-by-commit, every commit message explains why I made the changes.

Fix a bunch of smaller plugin framework bugs

---

.github/PULL_REQUEST_TEMPLATE.md
.github/workflows/vast.yaml

Without this change the CI job for building external plugins failed because it tried to downlod the wrong VAST version, namely `2021.04.29-rc3-40` instead of `2021.04.29`.
We don't need to re-releae because the job does not attach any release artifacts, but this change makes sure it works properly on the next release.
The new step is copied exactly from the other jobs in the same workflow, so this should be easy to verify.

Fetch tags in external plugins CI job

---

changelog/unreleased/bug-fixes/1622.md
libvast/src/system/datagram_source.cpp
libvast/src/system/source.cpp
libvast/test/system/datagram_source.cpp
libvast/vast/system/actors.hpp
libvast/vast/system/datagram_source.hpp

Every so often, we break the DATAGRAM SOURCE actor. This happens because we cannot make the behavior-returning `datagram_source` function returns a typed broker behavior, since that is absolutely broken in CAF 0.17.6 which we're still stuck on, and so we miss changing it when we change the interface of the SOURCE actor. But, as it turns out, we can still define the typed actor and typed broker interfaces, and simply unbox the underlying untyped behaviors before returning them.
Additionally, this aligns the interfaces again so the datagram source works once more.
Read code. Test locally with netcat or similar.

Fix the datagram source

---

cmake/VASTRegisterPlugin.cmake
libvast/CMakeLists.txt
libvast/src/detail/load_plugin.cpp
libvast/src/plugin.cpp
libvast/src/system/version_command.cpp
libvast/vast/plugin.hpp
vast/CMakeLists.txt

We support built-in plugins by using the `VAST_REGISTER_PLUGIN` macro from within a source file that is part of either the `vast` or the `libvast` targets.  These plugins are always loaded and cannot be disabled. This channge hides such plugins from the version output, as they are really not plugins but simply use the plugin framework to add functionality.
The idea for this came up when reviewing the transforms functionality, which has some transformation as such built-in plugins directly as part of `libvast`.
File-by-file.

Hide built-in plugins from version command

---

libvast/src/bloom_filter_parameters.cpp
libvast/src/bloom_filter_synopsis.cpp
libvast/src/bool_synopsis.cpp
libvast/test/bloom_filter.cpp
libvast/vast/bloom_filter.hpp
libvast/vast/bloom_filter_parameters.hpp
libvast/vast/bloom_filter_synopsis.hpp
libvast/vast/bool_synopsis.hpp
libvast/vast/buffered_synopsis.hpp
libvast/vast/detail/logger_formatters.hpp
libvast/vast/min_max_synopsis.hpp
libvast/vast/synopsis.hpp
libvast_test/vast/test/synopsis.hpp
libvast_test/vast/test/test.hpp

Problem:
- Bloom filter uses `caf::optional` which is an unncessary dependency
given that `std::optional` exists and can be readily used.
Solution:
- Replace uses of `caf::optional` with `std::optional`. Similarly,
replace `caf::none` with `std::nullopt`.
- Add support for formatting `std::optional` with `fmt`.
Note:
- Other parts of the codebase will be converted to use `std::optional`
in lieu of `caf::optional` in follow-up MRs.
File-by-file.

Bloom filter: caf::optional -> std::optional

---

libvast/vast/concept/parseable/core/guard.hpp

Problem:
- `return_type` is defined in terms of decltype of calling some function
with some args, which is exactly a standard library trait.
Solution:
- Use `std::invoke_result_t` directly.

Simplify return type for guard parser

---

libvast/src/system/spawn_index.cpp

Problem:
- `caf::string_view` is used but its functionality exists in the
standard library.
Solution:
- Use `std::string_view` instead.
File-by-file.

Replace caf::string_view with std::string_view

---

libvast/vast/detail/type_traits.hpp

Problem:
- Some type traits and associated variable templates are unused.
Solution:
- Remove unused type traits and associated variable templates.
File-by-file.

Remove unused type traits

---

libvast/src/attribute.cpp
libvast/src/concept/parseable/vast/type.cpp
libvast/vast/attribute.hpp
libvast/vast/concept/parseable/from_string.hpp
libvast/vast/optional.hpp
libvast/vast/view.hpp

Problem:
- There is a using directive for `caf::optional` in `vast/optional.hpp`
at `vast` namespace level scope, which is not ideal. Some parts of the
codebase use `optional` unqualified which refers to `caf::optional` due
to this using directive, which makes refactorings more difficult.
Solution:
- Remove using directive.
- Be explicit about use of `caf::optional` where previously call sites
referred to `optional` unqualified.
File-by-file.

Remove using caf::optional in vast namespace
