- libvast/src/address.cpp
- libvast/test/address.cpp
- libvast/vast/address.hpp
Address constructor change of unit32_t to void pointer. Added Tests for the constructor.
> Change address constructor signature to const void* byte input 

- libvast/test/parseable.cpp
- libvast/vast/concept/parseable/numeric/byte.hpp
A new variable amount of bytes parser with additional tests.
> Add variable bytes parser

- libvast/src/type.cpp
- libvast/test/type.cpp
- libvast/vast/type.hpp
This PR adds a feature needed by #191.
> Add flat_index_at utility function to record_type

- libvast/src/system/configuration.cpp
- libvast/test/fixtures/actor_system.hpp
- vast/vast.cpp
See [CAF's mailing list](https://groups.google.com/forum/#!topic/actor-framework/6jop4znq0Gc) for details on the changes made.
> Fix deprecated warnings after latest CAF changes

- libvast/CMakeLists.txt
- libvast/src/default_table_slice.cpp
- libvast/src/default_table_slice_builder.cpp
- libvast/src/table_slice.cpp
- libvast/src/table_slice_builder.cpp
- libvast/test/default_table_slice.cpp
- libvast/vast/default_table_slice_builder.hpp
- libvast/vast/fwd.hpp
- libvast/vast/table_slice.hpp
- libvast/vast/table_slice_builder.hpp
- libvast/vast/view.hpp
- Move `default_table_slice`, `default_table_slice_builder`, and
`table_slice` into individual headers
- Add `offset_` member variable (and getter/setter) to `table_slice`
- Implement missing member functions in `table`
> Add table_slice::offset and separate classes

- libvast/src/data.cpp
- libvast/src/value.cpp
- libvast/test/data.cpp
- libvast/vast/data.hpp
This PR refactors and fixes how we flatten data.
> Refactor and fix flattening of data

- libvast/vast/concept/parseable/detail/as_parser.hpp
- libvast/vast/concept/printable/detail/as_printer.hpp
- libvast/vast/concept/printable/string/literal.hpp
- libvast/vast/fwd.hpp
- libvast/vast/type.hpp
- libvast/vast/value.hpp
Fix several build errors and segfaults when building VAST with GCC 8.1.0.
> Build errors on GCC

- libvast/src/default_table_slice.cpp
- libvast/src/system/exporter.cpp
- libvast/test/fixtures/events.cpp
- libvast/test/fixtures/events.hpp
- libvast/test/system/exporter.cpp
- libvast/vast/default_table_slice.hpp
- libvast/vast/table_slice.hpp
Fix `exporter` unit test suite and port the actor the new table slice API.
> Port exporter to new table slice API

- CONTRIBUTING.md
This PR contains updates regarding unit testing and doxygen comments.
> Updates to the contribution guidelines

- scripts/flamegraph
This script facilitates instrumentation (currently only via `dtrace`) and generation of [Flame Graphs](http://www.brendangregg.com/flamegraphs.html).
> Create script to generate Flame Graphs

- libvast/test/system/importer.cpp
The importer is a central component in VAST. The additional tests catch errors early that happen only when using nondeterministic scheduling.
> Add nondeterministic tests to importer

- libvast/CMakeLists.txt
- libvast/src/format/bro.cpp
- libvast/test/fixtures/actor_system.hpp
- libvast/test/logs/bro/small_conn.log
- libvast/test/system/datagram_source.cpp
- libvast/vast/format/bro.hpp
- libvast/vast/format/reader.hpp
- libvast/vast/system/datagram_source.hpp
- libvast/vast/system/source.hpp
Add scaffold for sources that receive data via UDP. This is a building block for implementing a NetFlow collector later on.
> Create UDP source scaffold

- libvast/src/table_slice_builder.cpp
- libvast/src/type.cpp
- libvast/test/fixtures/events.cpp
- libvast/test/fixtures/events.hpp
- libvast/test/format/writer.cpp
- libvast/vast/system/source.hpp
- libvast/vast/table_slice_builder.hpp
https://github.com/vast-io/vast/commit/0fd33cac81702228fa6cce244935dfa7773d2659 contains the actual fix, and https://github.com/vast-io/vast/commit/0fe7d5520fa3c66e098c0fdccfced202998fbfb3 fixes up the  unit tests.
> Fix table_slice_builder

- README.md
- doc/vast.1
- doc/vast.1.md
- libvast/src/system/node_command.cpp
> Update docs and remove unnecessary check

- libvast/src/column_index.cpp
- libvast/test/column_index.cpp
- libvast/vast/column_index.hpp
Fix time and space overhead of types with skip attribute.
> Fix column index to honor the skip attribute again

- tools/bro-to-vast/bro-to-vast.cpp
This branch contains a few tweaks and enhancements for `bro-to-vast`.
> Enhance bro-to-vast bridge

- libvast/CMakeLists.txt
- libvast/src/format/bgpdump.cpp
- libvast/src/format/bro.cpp
- libvast/src/format/pcap.cpp
- libvast/src/format/reader.cpp
- libvast/src/format/writer.cpp
- libvast/vast/format/ascii.hpp
- libvast/vast/format/bgpdump.hpp
- libvast/vast/format/bro.hpp
- libvast/vast/format/csv.hpp
- libvast/vast/format/parser_reader.hpp
- libvast/vast/format/pcap.hpp
- libvast/vast/format/printer_writer.hpp
- libvast/vast/format/reader.hpp
- libvast/vast/format/test.hpp
- libvast/vast/format/writer.hpp
- libvast/vast/system/sink.hpp
- tools/bro-to-vast/bro-to-vast.cpp
This PR refactors the reader and writer format API into clear base
classes.
> Refactor reader/writer inheritance hierarchy

- libvast/src/system/source_command.cpp
Use `--schema=<string>` for passing a schema inline and `--schema-file=<path>` for passing a schema via file.
> Support schema string and file via CLI

- libvast/src/command.cpp
- libvast/src/system/application.cpp
- libvast/src/system/export_command.cpp
- libvast/src/system/import_command.cpp
- libvast/src/system/node_command.cpp
- libvast/src/system/remote_command.cpp
- libvast/src/system/sink_command.cpp
- libvast/src/system/source_command.cpp
- libvast/src/system/start_command.cpp
- libvast/test/command.cpp
- libvast/vast/command.hpp
- libvast/vast/error.hpp
- libvast/vast/system/application.hpp
- libvast/vast/system/export_command.hpp
- libvast/vast/system/import_command.hpp
- libvast/vast/system/remote_command.hpp
- libvast/vast/system/sink_command.hpp
- libvast/vast/system/source_command.hpp
- libvast/vast/system/start_command.hpp
- vast/vast.cpp
This allows returning errors as well as actual results from commands.
> Return caf::message from command::run

- libvast/src/meta_index.cpp
- libvast/src/synopsis.cpp
- libvast/test/meta_index.cpp
- libvast/vast/meta_index.hpp
- libvast/vast/synopsis.hpp
This PR fixes the serialization of the meta index and adds more unit tests for
custom factories.
> Fix meta index serialization

- libvast/vast/save.hpp
This change modifies `save()` to create a temporary file for writing and renames that to the destined name upon successful completion.
> Create temporary files for saving

- libvast/CMakeLists.txt
- libvast/src/chunk.cpp
- libvast/src/column_major_matrix_table_slice_builder.cpp
- libvast/src/default_table_slice.cpp
- libvast/src/default_table_slice_builder.cpp
- libvast/src/detail/mmapbuf.cpp
- libvast/src/row_major_matrix_table_slice_builder.cpp
- libvast/src/segment.cpp
- libvast/src/segment_builder.cpp
- libvast/src/table_slice.cpp
- libvast/test/bitmap.cpp
- libvast/test/byte.cpp
- libvast/test/chunk.cpp
- libvast/test/span.cpp
- libvast/test/table_slice.cpp
- libvast/vast/bitmap_algorithms.hpp
- libvast/vast/byte.hpp
- libvast/vast/chunk.hpp
- libvast/vast/column_major_matrix_table_slice_builder.hpp
- libvast/vast/default_table_slice.hpp
- libvast/vast/default_table_slice_builder.hpp
- libvast/vast/detail/span.hpp
- libvast/vast/detail/type_traits.hpp
- libvast/vast/matrix_table_slice.hpp
- libvast/vast/policy/row_major.hpp
- libvast/vast/row_major_matrix_table_slice_builder.hpp
- libvast/vast/span.hpp
- libvast/vast/table_slice.hpp
- libvast/vast/table_slice_header.hpp
This PR changes how we construct table slices. The individual commits contain a more detailed description, which I won't replicate here.
> Enhance table slice construction

- libvast/src/data.cpp
- libvast/src/type.cpp
- libvast/src/view.cpp
- libvast/test/type.cpp
- libvast/vast/aliases.hpp
- libvast/vast/data.hpp
- libvast/vast/type.hpp
- libvast/vast/view.hpp
Along with this change, the `enumeration` type alias has been
consolidated with `count`.
> Add type_check overload for views

- libvast/test/column_index.cpp
- libvast/test/expression.cpp
- libvast/test/meta_index.cpp
- libvast/test/parseable.cpp
- libvast/test/schema.cpp
- libvast/test/system/importer.cpp
- libvast_test/vast/test/test.hpp
...along with some cosmetic tweaks.
> Re-enable broken unit test in action parser

- libvast/src/system/accountant.cpp
- libvast/src/system/archive.cpp
- libvast/src/system/exporter.cpp
- libvast/src/system/importer.cpp
- libvast/src/system/index.cpp
- libvast/vast/system/accountant.hpp
- libvast/vast/system/source.hpp
> Add status handler to accountant

- libvast/src/detail/make_io_stream.cpp
- libvast/src/system/exporter.cpp
- libvast/src/system/node.cpp
- libvast/src/system/spawn_archive.cpp
- libvast/src/system/spawn_arguments.cpp
- libvast/src/system/spawn_consensus.cpp
- libvast/src/system/spawn_exporter.cpp
- libvast/src/system/spawn_index.cpp
- libvast/src/system/spawn_profiler.cpp
- libvast/src/system/spawn_sink.cpp
- libvast/src/system/spawn_source.cpp
Recent changes in CAF make this prefix obsolete.
> Remove no longer valid global config section

- libvast/test/parseable.cpp
- libvast/test/time.cpp
- libvast/vast/concept/parseable/core.hpp
- libvast/vast/concept/parseable/core/end_of_input.hpp
- libvast/vast/concept/parseable/vast/time.hpp
This PR adds support for compound time durations.
> Support compound timespans

- libvast/src/ewah_bitmap.cpp
- libvast/src/system/table_indexer.cpp
- libvast/vast/ewah_bitmap.hpp
- libvast/vast/system/index.hpp
- libvast/vast/system/partition.hpp
- libvast/vast/system/table_indexer.hpp
This PR fixes two bugs in the `table_indexer`.
> Fix bugs in table indexer

- CMakeLists.txt
- Dockerfile
- README.md
- docker_build.sh
> Update docker image

- scripts/git-setup.sh
Also don't add `--cached` by default for all invocations of `git diff`.
> Make git format and pre-commit usable cross repo

- libvast/vast/system/reader_command.hpp
I only noticed this problem after the previous PR was already merged.
> Fix build for listener type readers

- libvast/src/system/index.cpp
Downstream components such as the QUERY_PROCESSOR can deadlock when
getting no hits from the INDEX since they'll wait for a 'done' message
for each query.
> Make sure all queries receive a 'done' message

- CHANGELOG.md
- libvast/test/format/writer.cpp
- libvast/vast/format/csv.hpp
- libvast/vast/system/reader_command.hpp
>  Remove obsolete id and ts from CSV writer

- CHANGELOG.md
- libvast/src/system/accountant.cpp
- libvast/src/system/index.cpp
- libvast/src/system/indexer_stage_driver.cpp
- libvast/vast/system/index.hpp
The status output needs additional information about the accountant log file and high-level index statistics.
> Enhance status output

- libvast/test/chunk.cpp
- libvast/test/hash.cpp
- libvast/test/span.cpp
- libvast/vast/community_id.hpp
- libvast/vast/span.hpp
- libvast_test/src/table_slices.cpp
Also remove non-standard utility functions [ch7265].
> Make span standard-compliant, clean-up header

- libvast/test/system/exporter.cpp
This works around a memory leak that can be observed with gccs address sanitizer in the replicated store.
> Use dummy_consensus in exporter unit tests

- README.md
As discussed last Wednesday at HQ.
> Remove unused Twitter account from README

- .ci/debian/Dockerfile
- .cirrus.yml
- integration/default_set.yaml
- integration/integration.py
- integration/reference/server-zeek-conn-log/step_06.ref
- integration/requirements.txt
- libvast/src/default_table_slice_builder.cpp
- libvast/src/format/json.cpp
- libvast/src/system/accountant.cpp
- libvast/src/system/node.cpp
- libvast/src/table_slice_builder.cpp
- libvast/test/meta_index.cpp
- libvast/test/system/datagram_source.cpp
- libvast/test/system/importer.cpp
- libvast/test/system/source.cpp
- libvast/vast/default_table_slice_builder.hpp
- libvast/vast/fwd.hpp
- libvast/vast/system/accountant.hpp
- libvast/vast/system/datagram_source.hpp
- libvast/vast/system/instrumentation.hpp
- libvast/vast/system/reader_command.hpp
- libvast/vast/system/source.hpp
- libvast/vast/table_slice_builder.hpp
This PR will change the ACCOUNTANT to relay its data back to the IMPORTER in the form of table slices. That will allow us to query the data flexibly and export it in the desired format.
TODO:
> Store accounting data in VAST native format

- CHANGELOG.md
Adds the missing changelog entry from #603.
> Add changelog entry for export -n crash fix

- README.md
The changelog is currently our most up-to-date document for software updates.
> Add changelog to README

- scripts/vast-du
Edit: [skip ci] for Cirrus in PR titles apparently does not work with force pushes. 🤷‍♂
> Calculate node throughput from accounting logs

- .github/workflows/vast.yml
- CMakeLists.txt
- aux/broker/CMakeLists.txt
- aux/lz4/contrib/cmake_unofficial/CMakeLists.txt
- aux/xxhash/cmake_unofficial/CMakeLists.txt
- cmake/FindArrow.cmake
- cmake/FindBROKER.cmake
- cmake/FindBrotli.cmake
- cmake/FindCAF.cmake
- cmake/FindDoubleConversion.cmake
- cmake/FindGCOV.cmake
- cmake/FindGCOVR.cmake
- cmake/FindGLOG.cmake
- cmake/FindGperftools.cmake
- cmake/FindLz4.cmake
- cmake/FindPCAP.cmake
- cmake/FindPandoc.cmake
- cmake/FindPlasma.cmake
- cmake/FindSnappy.cmake
- cmake/FindSnappyAlt.cmake
- cmake/FindThrift.cmake
- cmake/FindZSTD.cmake
- cmake/Finduriparser.cmake
- cmake/FinduriparserAlt.cmake
- cmake/GenerateGcov.cmake
- cmake/Helpers.cmake
- cmake/MacDependencyPaths.cmake
- doc/CMakeLists.txt
- libvast/CMakeLists.txt
- libvast_test/CMakeLists.txt
~Note: This is currently based off of #677, and needs to be rebased to master once that PR is merged.~
> Run cmake-format / black in CI

- .github/workflows/vast.yml
Use `set-env` instead of step outputs.
> Simplify GitHub actions environment usage

- .github/workflows/vast.yml
- INSTALLATION.md
- README.md
- Propose new header
- Add key features
- Extract installation instructions
I noticed that the Docker build (+ instructions) do not work any more. Nonetheless, I extracted the instructions as-is to a dedicated file. That should be addressed in a separate story.
> Polish README

- Dockerfile
- INSTALLATION.md
- scripts/docker-build
- Fix Docker build
- Update instructions in `INSTALLATION.md`
- Update `./scripts/docker-build`
> Fix Docker Build

- README.md
Preview here: https://github.com/tenzir/vast/blob/ad784778f4f72e6a683b69ebfd6f231bc0d5e4bb/README.md
> Add link to installation instructions to header

- INSTALLATION.md
Replace the TODO section by some basic information about linux binary installation.
> Add basic information to Linux section of install guide

- aux/broker/CMakeLists.txt
Followup for #722.
I'd appreciate if you could verify locally that you don't get the warnings anymore, @mavam.
> Silence Broker warning only when available

- libvast/src/expression_visitors.cpp
- libvast/src/format/csv.cpp
- libvast/src/format/json.cpp
- libvast/src/meta_index.cpp
- libvast/test/expression.cpp
- libvast/test/expression_parseable.cpp
- libvast/test/format/csv.cpp
- libvast/test/format/json.cpp
- libvast/test/format/mrt.cpp
- libvast/test/meta_index.cpp
- libvast/test/schema.cpp
- libvast/test/segment_store.cpp
- libvast/test/system/indexer_stage_driver.cpp
- libvast/test/time.cpp
- libvast/test/value_index.cpp
- libvast/vast/concept/parseable/vast/type.hpp
- libvast/vast/concept/support/unused_type.hpp
- libvast/vast/data.hpp
- libvast/vast/detail/range_map.hpp
- libvast/vast/json.hpp
- libvast/vast/meta_index.hpp
- libvast/vast/synopsis.hpp
- libvast/vast/view.hpp
Note: The unit tests still need to be fixed accordingly.
> Fix ADL issue for unused_type

- .github/workflows/vast.yml
Migrate artifact upload to GCS.
> Migrate to Google Cloud

- .dockerignore
- .github/workflows/vast.yml
- Dockerfile_prebuilt
Branch based on [story/ch12284](https://github.com/tenzir/vast/tree/story/ch12284) + rebased on master. Other PR should be merged first. 
See the [test run for DockerHub upload](https://github.com/tenzir/vast/runs/415437408?check_suite_focus=true#step:18:1) or try `docker run tenzir/vast:story-ch12293`.
> Auto-Publish to DockerHub

- .github/workflows/vast.yml
> Fix failure condition check for uploading integration tests

- libvast/src/system/application.cpp
@lava can you check if this fixes the issue on your end?
> Include PCAP header only when building with PCAP

- CMakeLists.txt
- configure
Two small-ish fixes for our scaffolding.
> Use custom build type for CI and fix cmake install target

- CHANGELOG.md
Note: The merge commit on master for this PR is the one we need to tag.
> Update changelog for release 2020.02.27

- Dockerfile
- Dockerfile_prebuilt
- use `$PREFIX/var/db/vast` as CWD
- add apache arrow and libasan5 to fix container build
> Use consistent working directory

- vast/vast.cpp
A command line flag existed for the `system.no-default-schema` option, but it was never checked against.
To verify that the change I made works:
```
❯ vast -N --no-default-schema import suricata -r integration/data/suricata/eve.json
vast.format.json.reader reads data from integration/data/suricata/eve.json
vast.format.json.suricata does not have a layout for event_type alert
vast.format.json.suricata does not have a layout for event_type dns
vast.format.json.suricata does not have a layout for event_type fileinfo
vast.format.json.suricata does not have a layout for event_type flow
vast.format.json.suricata does not have a layout for event_type http
vast.format.json.suricata does not have a layout for event_type netflow
vast.format.json.suricata does not have a layout for event_type stats …
```
> Handle no-default-schema option

- vast.conf
This slipped through a review, sorry for that.
> Add missing comments to vast.conf

- .github/workflows/pyvast.yaml
- .github/workflows/style-check.yaml
- .github/workflows/vast.yml
- .gitignore
- pyvast/Makefile
- pyvast/README.md
- pyvast/example/example.py
- pyvast/pyvast/test_vast.py
- pyvast/setup.py
> Make PyVAST available via PyPI

- libvast/src/system/node.cpp
This is a bandaid to fix an issue where fetching the archive status takes too long and locks up the node. The real fix must be changing the archive to fix the issue, but having a timeout here is generally a valuable thing. Fetching a status is something that users generally expect to be a quick operation.
> Use a timeout when collecting a components status

- libvast/vast/system/node_control.hpp
Add a new function that can look up an actor from a given
label and type, which should uniquely identify any one
actor.
> Add function for actor lookup by label and type

- libvast/src/column_index.cpp
- libvast/src/system/spawn_type_registry.cpp
- libvast/test/parseable.cpp
- libvast/test/system/partition.cpp
- libvast/test/system/type_registry.cpp
- libvast/vast/aliases.hpp
- libvast/vast/system/indexer_downstream_manager.hpp
- libvast/vast/system/indexer_stage_driver.hpp
- libvast/vast/system/partition.hpp
- libvast/vast/table_slice_column.hpp
These warnings result in a sour build experience.
> Fix ankle-biting compiler warnings

- libvast/test/system/type_registry.cpp
This is a follow-up PR that should have been part of #836.
> Fix comparison warning

- libvast/CMakeLists.txt
- libvast/src/fbs/utils.cpp
- libvast/src/io/read.cpp
- libvast/src/io/write.cpp
- libvast/src/meta_index.cpp
- libvast/src/segment.cpp
- libvast/src/segment_builder.cpp
- libvast/src/segment_store.cpp
- libvast/src/system/index.cpp
- libvast/src/table_slice.cpp
- libvast/vast/fbs/meta_index.fbs
- libvast/vast/fbs/utils.hpp
- libvast/vast/fbs/version.fbs
- libvast/vast/io/read.hpp
- libvast/vast/io/write.hpp
- libvast/vast/meta_index.hpp
- libvast/vast/table_slice.hpp
This PR migrates the index state to flatbuffers.
> Flatbufferize meta index state

- libvast/src/command.cpp
By assigning the keys of `invocation.options`, we would reset the already merged options to their un-merged original state, erasing any values that were merged from the default configuration.
> Dont overwrite default options when running a command

- CHANGELOG.md
This PR slightly tweaks the changelog, by adding a new emoji for experimental features and prettifying the one for changes.
> Tweak changelog style

- libvast/vast/detail/getline_generic.hpp
Fix several issues with the `vast::generic_getline()` function:
1) Check if sentry construction was succesful, and abort if not.
2) Set the input streams failbit if none or too many characters
were extracted from the input stream to be consistent with the
behaviour of std::getline.
3) Always set eofbit when encountering eof to avoid an extra blank
line at the end of the input.
The lack of (1) above could lead to a rather subtle race condition in
combination with line_range as follows:
When input was read from e.g. a socket and the last line before
encountering a read timeout was a blank line, the input stream would
have the eof bit set to signal the read timeout. Since line_range
would see an empty line returned with the input stream still being
"true" (but not .good()), so it would …
> Fix stream error state handling in getline_generic

- libvast/src/system/pivoter.cpp
Note that I have not tested this to work yet, as I need to gather appropriate data and schemas first. I will do so before merging this.
> Allow for pivoting over community_id by default

- .github/workflows/vast.yml
This PR is a cleanup pass over our main GitHub Actions workflow file.
> Cleanup VAST CI workflow

- CHANGELOG.md
The merge commit of this is the one we'll tag for the release tomorrow.
> Prepare changelog for the June 2020 release

- CMakeLists.txt
- libvast/src/format/arrow.cpp
- libvast/test/format/arrow.cpp
I've also cherry-picked the warning fixes from #945 into this.
> Require Apache Arrow >= 0.17 during build config

- .github/workflows/jupyter.yaml
- .github/workflows/vast.yml
- README.md
Adds a workflow to download the latest artifact of a successful VAST master merge and runs the jupyter demo.
> Add GitHub workflow to run jupyter notebook

- examples/jupyter/README.md
- examples/jupyter/requirements.txt
- examples/jupyter/scripts/run-demo
This PR additionally adds a script that runs the demo from a temporary directory.
> Fix Jupyter Notebook demo instructions

- .github/workflows/static-binary.yaml
- CMakeLists.txt
- nix/broker/source.json
- nix/caf/source.json
- nix/overlay.nix
- nix/update.sh
@tobim can you check what changes are required to `nix/caf/source.json` and just push any required changes onto this branch?
> Update CAF to 0.17.6

- CHANGELOG.md
The merge commit of this PR is the one we'll tag for the release.
> Prepare changelog for July 2020 release

- .github/ISSUE_TEMPLATE/crash_report.md
- .github/ISSUE_TEMPLATE/non_specific_bug_report.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/unexpected_query_result.md
> Add issue templates

- .gitmodules
- CHANGELOG.md
Companion PR: https://github.com/tenzir/actor-framework/pull/1
> Expand CAF stream slot ids to 32 bits

- libvast/test/data.cpp
- libvast/vast/data.hpp
See also my post on r/cpp regarding this issue: https://www.reddit.com/r/cpp/comments/iotebm
> Clarify comment on CWG issue 2137

- CHANGELOG.md
- doc/cli/vast-import.md
- integration/default_set.yaml
- libvast/src/format/csv.cpp
- libvast/src/format/pcap.cpp
- libvast/src/format/syslog.cpp
- libvast/src/format/test.cpp
- libvast/src/format/zeek.cpp
- libvast/src/system/application.cpp
- libvast/src/system/importer.cpp
- libvast/test/format/zeek.cpp
- libvast/vast/format/json.hpp
- libvast/vast/system/make_source.hpp
- libvast/vast/system/source.hpp
- vast.conf.example
~Not sure if I should split out the last commit into a separate PR. Also still have to write changelog entries.~
> Improve import batching options

- libvast/src/system/partition.cpp
- libvast/vast/system/partition.hpp
Instead of going over the whole partition and spawning all indexer when loading a partition, we `mmap` the partition and only access the relevant part of the memory once we get a query that actually uses this indexer.
> Spawn INDEXERs lazily from partition

- doc/cli/vast-start.md
- doc/cli/vast.md
> Update YAML config docs

- libvast/src/system/importer.cpp
- libvast/src/system/node.cpp
- libvast/src/system/spawn_archive.cpp
- libvast/src/system/spawn_counter.cpp
- libvast/src/system/spawn_eraser.cpp
- libvast/src/system/spawn_explorer.cpp
- libvast/src/system/spawn_exporter.cpp
- libvast/src/system/spawn_importer.cpp
- libvast/src/system/spawn_index.cpp
- libvast/src/system/spawn_pivoter.cpp
- libvast/src/system/spawn_type_registry.cpp
This is on verbose, so let's write it in a way that makes sense to the user.
> Make some verbose log messages more user-facing

- .github/workflows/vast.yaml
Revert "Extract conditional for docker steps"
This reverts commit a7734bf3bbcaf3fc7aadd09f13b7c27be85235c4.
> Fix conditional in Docker-related steps in VAST CI

- CHANGELOG.md
- doc/cli/vast-import.md
- libvast/src/format/csv.cpp
- libvast/src/format/multi_layout_reader.cpp
- libvast/src/format/pcap.cpp
- libvast/src/format/reader.cpp
- libvast/src/format/single_layout_reader.cpp
- libvast/src/format/syslog.cpp
- libvast/src/format/test.cpp
- libvast/src/format/zeek.cpp
- libvast/src/system/application.cpp
- libvast/src/system/importer.cpp
- libvast/test/format/pcap.cpp
- libvast/test/format/zeek.cpp
- libvast/vast/defaults.hpp
- libvast/vast/format/csv.hpp
- libvast/vast/format/json.hpp
- libvast/vast/format/multi_layout_reader.hpp
- libvast/vast/format/reader.hpp
- libvast/vast/format/single_layout_reader.hpp
- libvast/vast/format/zeek.hpp
- libvast/vast/fwd.hpp
- libvast/vast/system/source.hpp
- libvast_test/src/events.cpp
- vast.yaml.example
> Make the source actor more responsive

- .github/workflows/vast.yaml
- Rewrite paths in compiler stderr to be relative
- Print statistics about cache compression
> Make use of Ccache 4.0 features

- libvast/src/system/spawn_type_registry.cpp
- schema/ecs.yaml
Title is quite self-explanatory. Additionally, this fixes a spelling in the code and removes a useless copy from an error handler (I always fix these as I see them).
> Fix formatting of the bundled concepts

- CHANGELOG.md
- Add a breaking change category in the changelog file.
- Retroactively mark some changes as breaking for clarification.
Look at the past three-or-so releases in the changelog and verify that I caught all breaking changes.
> List breaking changes explicitly in changelog

- pyvast/README.md
- pyvast/example/example.py
- pyvast/pyvast/test_vast.py
- pyvast/pyvast/vast.py
- pyvast/setup.py
Pass optional, user-defined logger to PyVAST.
> Pass optional logger during construction

- README.md
It doesn't provide any meaningful information at this point. We might as well get rid of it.
> Remove Docker badge

- .github/workflows/static-binary.yaml
> Dont replace 'vast-latest' tarball for manually triggered runs

- CHANGELOG.md
- libvast/src/system/configuration.cpp
> Error when specified config file does not exist

- .github/workflows/static-binary.yaml
> Fix end-quote in static workflow

- libvast/src/segment_store.cpp
- libvast/vast/fbs/utils.hpp
> Don't verify segment flatbuffers on startup

- pyvast/pyvast/vast.py
> Use debug logging for debug messages

- CHANGELOG.md
- schema/suricata.yaml
- schema/taxonomy/vast/network.yaml
- schema/zeek.yaml
This PR includes enhancements for some concepts that are especially helpful for retro matching.
> Add domain concept and enhance uri + hostname

- CMakeLists.txt
n/t
Configure and run `vast-schema` target multiple times, verify that output of `tree build/share/vast/schema/` looks like below even after repeated runs.
```
❯ tree build/share/vast/schema/
build/share/vast/schema/
├── argus.schema
├── pcap.yaml
├── suricata.schema
├── suricata.yaml
├── sysmon.schema
├── sysmon.yaml
├── taxonomy
│   ├── ecs
│   │   └── source.yaml
│   └── vast
│       ├── file.yaml
│       ├── network.yaml
│       └── process.yaml
├── test.schema
├── zeek.schema
└── zeek.yaml
```
> Fix installation of schema directory

- libvast/CMakeLists.txt
- libvast/src/layout_version.cpp
- libvast/src/system/spawn_node.cpp
- libvast/vast/layout_version.hpp
> Create a version file for the database dir

- .github/workflows/static-binary.yaml
> Update VAST Static workflow dependencies

- schema/suricata.yaml
- schema/zeek.yaml
Add more fields to Zeek and Suricata schemas.
> Add more host(name) and domain name fields

- libvast/CMakeLists.txt
> Enable LTO for libvast in release builds

- CMakeLists.txt
- configure
- libvast/src/system/archive.cpp
- libvast/src/system/importer.cpp
- libvast/src/system/index.cpp
- libvast/src/system/spawn_importer.cpp
- libvast/src/system/type_registry.cpp
Mostly logging improvements, doesn't require a CL entry in my opinion.
Commit by commit.
> Minor improvements

- libvast/src/system/partition.cpp
This removes an unnecessary temporary allocation in the `partition_selector`. The change doesn't bring any performance gains, because the allocator was able to recycle the memory in subsequent calls. But it removes some noise from memory analysis tools like heaptrack.
> Avoid temporary allocations in partition selector

- .github/workflows/static-binary.yaml
- libvast/src/detail/fdinbuf.cpp
- nix/overlay.nix
- nix/static-binary.sh
- nix/vast/default.nix
This builds a static binary with that is more debugable in case something goes wrong.
Commit by commit.
> Extend the VAST Static workflow with a "CI" type build

- .github/workflows/vast.yaml
I've had to fix this one too many times, let's just catch the issues before they hit master.
n/t
> Add gcc-8 to CI matrix

- nix/broker/default.nix
- nix/overlay.nix
- nix/pinned.nix
- nix/vast/default.nix
- shell.nix
This turns off simd in Apache Arrow for the CI build type.
> Disable SIMD for nix-based CI builds

- integration/default_set.yaml
- integration/integration.py
> Add possibility to specify expected result in integration tests

- CHANGELOG.md
Thanks for noticing @0ortmann.
n/t
> Add missing PR reference to changelog entry

- libvast/src/system/exporter.cpp
> Send correct message to index when dropping further results

- schema/concepts/zeek.yaml
See [Zeek SSL::Info](https://docs.zeek.org/en/current/scripts/base/protocols/ssl/main.zeek.html#type-SSL::Info) `#server_name`.
> Add Zeek's ssl.server_name to net.domain concept

- libvast/src/system/importer.cpp
- libvast/src/system/index.cpp
- libvast/test/system/source.cpp
- libvast/vast/system/importer.hpp
- libvast/vast/system/source.hpp
Adds the following INFO messages to the node:
```
2020-12-13T23:17:05.668 importer adds zeek-reader source
2020-12-13T23:17:07.384 importer removes zeek-reader source
```
By commit.
> Track individual sources at the importer

- CHANGELOG.md
- libvast/src/meta_index.cpp
- libvast/vast/detail/tracepoint.hpp
Add debug log message and tracepoint for monitoring meta index lookups.
> Add tracing for meta index lookup speed

- CHANGELOG.md
- CMakeLists.txt
- README.md
- cmake/VASTCheckCompilerVersion.cmake
- pyvast/setup.py
This must be rebased before merging. The merge commit of this branch is the one I'll tag for release.
n/t
> Prepare repository for December 2020 release

- libvast/vast/bitmap_algorithms.hpp
- libvast/vast/bits.hpp
- libvast/vast/system/source.hpp
Fixes 3 UBSAN warnings.
By commit.
> Address 3 UBSAN Warnings

- nix/pinned.nix
- shell.nix
Update to a newer version, specifically this contains `simdjson` 0.7.
> Update nixpkgs to f42d6f8

- CHANGELOG.md
> Fix broken link to 2020.12.16 release in changelog

- .github/workflows/vast.yaml
- libvast/test/CMakeLists.txt
**Still work-in-progress.**
This PR enables ASan for vast-test and fixes the build with ASan enabled.
> Fix Address Sanitizer issues in vast-test

- libvast/src/system/explore_command.cpp
- libvast/src/system/explorer.cpp
- libvast/src/system/exporter.cpp
- libvast/src/system/pivot_command.cpp
- libvast/src/system/pivoter.cpp
- libvast/src/system/sink_command.cpp
- libvast/src/system/spawn_exporter.cpp
- libvast/test/system/exporter.cpp
- libvast/test/system/type_registry.cpp
- libvast/vast/system/explorer.hpp
- libvast/vast/system/exporter.hpp
- libvast/vast/system/exporter_actor.hpp
This changes the exporter component to be a typed actor.
> Make the exporter component a typed actor

- CHANGELOG.md
This PR adapts a changelog entry that was a breaking change.
In one shot.
> Be clear about breaking CLI change

- CHANGELOG.md
- libvast/src/system/spawn_disk_monitor.cpp
- vast.yaml.example
> Check that disk budget was not specified as non-string

- libvast/src/system/evaluator.cpp
- libvast/src/system/index.cpp
- libvast/src/system/partition.cpp
- libvast/src/system/query_supervisor.cpp
- libvast/test/flatbuffers.cpp
- libvast/test/system/evaluator.cpp
- libvast/test/system/index.cpp
- libvast/test/system/query_supervisor.cpp
- libvast/vast/system/evaluator.hpp
- libvast/vast/system/evaluator_actor.hpp
- libvast/vast/system/index.hpp
- libvast/vast/system/index_client_actor.hpp
- libvast/vast/system/partition.hpp
- libvast/vast/system/partition_actor.hpp
- libvast/vast/system/partition_client_actor.hpp
- libvast/vast/system/query_supervisor.hpp
- libvast/vast/system/query_supervisor_actor.hpp
> Refactor INDEX to remove 'await_evaluation_maps' construct

- vast.yaml.example
> Add vast.export.json.flatten to example config

- doc/cli/vast-export-arrow.md
> Remove port type from export arrow docs

- configure
This PR streamlines the DX of `configure` when building with plugins.
In one shot.
> Improve plugin developer experience

- CHANGELOG.md
- CMakeLists.txt
- Dockerfile
- LICENSE.3rdparty
This adds a list of embedded licenses in VAST, and bundles it with every installation.
Check the list for completeness.
> Add third-party licenses for embedded dependencies

- .github/workflows/vast.yaml
- Dockerfile_prebuilt
We don't need to build all default targets—let's just build the actual library we need.
This is covered by CI.
> Speed up simdjson build in CI and Dockerfile

- libvast/src/detail/add_message_types.cpp
- libvast/src/meta_index.cpp
- libvast/src/partition_synopsis.cpp
- libvast/src/system/index.cpp
- libvast/src/system/partition.cpp
- libvast/src/system/query_supervisor.cpp
- libvast/src/system/spawn_importer.cpp
- libvast/test/flatbuffers.cpp
- libvast/test/meta_index.cpp
- libvast/test/system/eraser.cpp
- libvast/test/system/query_processor.cpp
- libvast/vast/meta_index.hpp
- libvast/vast/partition_synopsis.hpp
- libvast/vast/system/actors.hpp
- libvast/vast/system/partition.hpp
- libvast/vast/system/query_supervisor.hpp
See commit messages
Look at the whole chain for an overview, then commit by commit.
>  Dont create parallel meta index inside the index

- libvast/src/system/exporter.cpp
- libvast/src/system/importer.cpp
- libvast/src/system/node.cpp
- libvast/src/system/spawn_exporter.cpp
- libvast/test/system/exporter.cpp
- libvast/test/system/importer.cpp
- libvast/test/system/source.cpp
- libvast/vast/detail/tuple_map.hpp
- libvast/vast/system/actors.hpp
- libvast/vast/system/import_command.hpp
- libvast/vast/system/make_source.hpp
- libvast/vast/system/node_control.hpp
- libvast/vast/system/source.hpp
- libvast/vast/system/spawn_source.hpp
This is a strict follow-up to #1300. I factored it out because of an issue that we've yet got to debug.
To be reviewed by @tobim and @dominiklohmann together.
> Improve wiring of importer and exporter

- CHANGELOG.md
- CMakeLists.txt
- README.md
- pyvast/setup.py
- Updates all version references for tomorrow's planned release.
- The merge commit of this PR is the one we'll tag for the release. 
- I've taken the freedom to re-arrange our changelog by categories like we do for the release.
Proofread the changelog.
> Prepare repository for January 2021 release

- .github/workflows/vast.yaml
- Dockerfile
- Fetch keys via cURL (avoids keyserver problems and IPv6 issues altogether)
- Remove custom key installation where possible (`flatbuffers`)
File-by-file.
> Fix keyserver receive error

- libvast/vast/word.hpp
Simplify `select` function templates by preferring `if-constexpr` with a predicate instead of SFINAE.
File-by-file.
> Simplify select overloads for words

- libvast/src/detail/load_plugin.cpp
- libvast/src/system/application.cpp
- libvast/vast/detail/load_plugin.hpp
- vast/vast.cpp
This refactors our main function a bit to make it a bit easier to maintain.
File-by-file.
> Factor out logic from main function

- CMakeLists.txt
- configure
> Expose -ftime-{trace,report} build options

- libvast/src/system/infer_command.cpp
- libvast/src/system/pcap_writer_command.cpp
- libvast/src/system/remote_command.cpp
- libvast/src/system/start_command.cpp
- libvast/src/system/stop_command.cpp
- libvast/vast/system/count_command.hpp
- libvast/vast/system/explore_command.hpp
- libvast/vast/system/get_command.hpp
- libvast/vast/system/infer_command.hpp
- libvast/vast/system/pcap_writer_command.hpp
- libvast/vast/system/pivot_command.hpp
- libvast/vast/system/remote_command.hpp
- libvast/vast/system/sink_command.hpp
- libvast/vast/system/start_command.hpp
- libvast/vast/system/stop_command.hpp
- libvast/vast/system/version_command.hpp
- tools/zeek-to-vast/zeek-to-vast.cpp
A minor refactoring for improved compilation time.
File-by-file.
> Remove some unnecessary command.hpp includes

- vast/integration/default_set.yaml
- vast/integration/vast.yaml
GitHub Actions seems to have a somewhat inconsistent container network setup, so here's hoping this reduces the amount of timeouts we see in CI.
n/t
> Use IPv4 for integration tests

- .github/workflows/static-binary.yaml
This adds an alternative way to trigger the static binary: Via a dropdown int he actions tab.
Sanity-check logic in action.
> Add a 'static binary' button to CI

- libvast/src/system/sink_command.cpp
> Fix log message formatting in sink command

- CHANGELOG.md
- CMakeLists.txt
- README.md
- libvast/src/format/json.cpp
- pyvast/setup.py
The merge commit of this PR is the one we'll tag for this months' release.
> Prepare February 2021 release

- .github/workflows/static-binary.yaml
> Fix static binary CI for release triggers

- libvast/vast/detail/assert.hpp
> Print assertion message to stderr

- .github/workflows/vast.yaml
- Dockerfile
This is an attempt to fix the CI workflows running our Dockerfile.
> Fix CI workflows running the Dockerfile

- libvast/test/segment_store.cpp
Problem:
- `segment_store` unit tests uses `vast::directory` which is going away
soon.
Solution:
- Replace `vast::directory` uses with `std::filesystem`.
- Replace `vast::path` uses with `std::filesystem::path`.
File-by-file.
> Replace vast::directory with std::filesystem in segment_store test

- libvast/src/system/disk_monitor.cpp
Problem:
- Use of `::stat` system call is discouraged when it can be replaced
with higher level standard facilities from `std::filesystem`.
Solution:
- Replace `::stat` call used to get the last modified time and file size
directly with their equivalent functions from `std::filesystem`. This
also allows us to work with strong types in the `partition_diskstate`
which is nice.
File-by-file.
> Replace ::stat call with std::filesystem equivalents

- tools/lsvast/lsvast.cpp
Problem:
- `lsvast` tool uses `vast::directory` which is going away soon.
Solution:
- Use `std::filesystem::directory_iterator` instead.
- Replace uses of `vast::path` with `std::filesystem::path` as well.
File-by-file.
> Replace vast::directory with std::filesystem in lsvast tool

- libvast/src/segment_store.cpp
Problem:
- When registering segments in the `segment_store`, `vast::directory` is
used which is going away soon.
Solution:
- Use `std::filesystem::directory_iterator` instead to remove the need
for `vast::directory`. As implemented, this creates some extra
conversions for converting back and forth between path types.
File-by-file.
> Remove dependency on vast::directory in segment_store

- tools/lsvast/lsvast.cpp
@lava feel free to push onto this branch if you immediately see the issue with the second commit. I don't think it's worth spending too much time on the matter.
Commit-by-commit. To be reviewed by @lava.
> Fix database detection for lsvast

- .github/workflows/static-binary.yaml
This is a follow-up to #1425.
We can't really review this outside of sanity-checking the syntax until it has landed on master.
> Expose options in static binary workflow trigger

- libvast/src/system/partition.cpp
> Handle race condition during passive partition shutdown

- CHANGELOG.md
- libvast/src/system/disk_monitor.cpp
- libvast/src/system/index.cpp
- libvast/src/system/meta_index.cpp
- libvast/vast/detail/recursive_size.hpp
- libvast/vast/system/actors.hpp
> Remove erased partitions from the meta index

- .github/workflows/vast.yaml
~This is more of an experiment than me actually knowing what I'm doing here. 🤷‍♂️~ I understand now. We're using CCache again _and_ are uploading the cache again. 
Review Instructions:
Take a look at all the changes, and verify that CI took less than 50 minutes to run on the last run.
> Fix usage of CCache inside Docker in CI

- libvast/src/format/pcap.cpp
- libvast/vast/format/pcap.hpp
Problem:
- The pcap writer uses raw pointers for the `pcap_t` and `pcap_dumper_t`
member variables which doesn't express ownership semantics to readers
of the code. It also requires manual cleanup of the resource in the
destructor.
Solution:
- Use `std::unique_ptr` for both pointers with appropriate custom
deleters to cleanup the resource.
Note:
- A similar thing can be done for the pcap reader, but then a move
constructor needs to be defined since there are places in the code
relying on the pcap reader being movable. Currently, it is trivially
copyable and hence movable. Making the pcap data member a
`std::unique_ptr` changes that.
File-by-file.
> Prefer std::unique_ptr in pcap writer

- libvast/src/system/disk_monitor.cpp
> Fix usage of 'stem()' in disk monitor

- CHANGELOG.md
- README.md
- pyvast/setup.py
The merge commit of this one is the commit we'll tag tomorrow, assuming everything's running as expected now.
> Prepare repository for release of 2021.03.25

- libvast/src/format/pcap.cpp
Problem:
- `pcap` formatter depends on `vast::path` for checking if the input
exists.
Solution:
- Use `std::filesystem::exists` instead.
Note:
- Did not change `input_` data member to be a `std::filesystem::path`
type since the pcap formatter allows for the input to be `-` meaning
`stdin` which isn't well representable using `std::filesystem::path`.
File-by-file.
> Remove dependency on vast::path in pcap formatter

- vast.yaml.example
Thanks @norg for pointing this one out.
n/t
> Fix false comment in example configuration

- cmake/VASTConfigVersion.cmake
This doesn't rely on a bunch of regexes that are hard to understand.
> Simplify the version extraction

- libvast/src/detail/add_message_types.cpp
- libvast/vast/system/actors.hpp
This makes the required changes for https://github.com/tenzir/vast/pull/1504#discussion_r602731887.
n/t
> Assign a type ID to std::filesystem::path

- libvast/src/arrow_table_slice.cpp
- libvast/src/msgpack_table_slice.cpp
- libvast/test/table_slice.cpp
- libvast/vast/data.hpp
- libvast/vast/fwd.hpp
- libvast/vast/project.hpp
- libvast/vast/table_slice.hpp
- libvast/vast/type.hpp
This adds a free `project` function to the table slice API that allows for type-safe, row-based iteration on selected columns.
File-by-file. Ideally we peer-review this in a call.
> Enable type-safe projections

- examples/plugins/example/integration/reference/example/step_01.ref
- examples/plugins/example/integration/tests.yaml
The example plugin integration tests failed locally with additional plugins loaded.
File-by-file.
> Fix running example plugin tests with additional plugins

- libvast/src/system/meta_index.cpp
- libvast/vast/detail/flat_map.hpp
- libvast/vast/detail/vector_map.hpp
- libvast/vast/system/meta_index.hpp
See commit message.
Ideally: Do a benchmark run to ensure no performance regressions.
> Switch to 'flat_map' over 'unordered_map' in the meta index

- .github/workflows/changelog.yaml
The one thing we were unable to test in CI before merging I got wrong. As usual. /sigh
n/t
> Fix changelog updates on master

- cmake/VASTRegisterPlugin.cmake
- examples/plugins/example/.gitignore
- plugins/pcap/.gitignore
I keep on adding this code to every plugin I write, so let's just add it to `VASTRegisterPlugin` so plugin developers get this for free.
n/t
> Create a compilation database for external plugins

- README.md
- changelog/unreleased/changes/1591.md
We're switching from EMS to Gitter, so let's make it official.
File-by-file.
> Update chat URL in README

- libvast/src/arrow_table_slice_builder.cpp
- libvast/src/format/arrow.cpp
- libvast/src/format/csv.cpp
- libvast/src/format/zeek.cpp
- libvast/test/arrow_table_slice.cpp
- libvast/vast/arrow_table_slice_builder.hpp
- libvast/vast/format/arrow.hpp
~This may supersede #1605.~ This supersedes #1605.
n/t
> Remove flat layout copy from Arrow table slice builder

- libvast/vast/detail/assert.hpp
This allows us to write new assertions with an optional message describing the failure.
> Add overload with message for VAST_ASSERT

- .github/workflows/static-binary.yaml
- .github/workflows/vast-docker.yaml
- .github/workflows/vast.yaml
I've initially restricted this to the long-running PRs that build VAST.
> Cancel previous workflow runs on push

- libvast/vast/data.hpp
Problem:
- `to_data_type` has several nested `std::conditional_t` which is slow
for compile times and hinders readability.
- `to_data_type` is not DRY with use of `std::is_same` several times in
one branch.
- `to_data_type` uses `std::false_type` to denote the idea of there
being no mapping for a given `T` to a vast data type. The intent at
the point of use in the data constructor isn't obvious due to
comparing with `std::false_type`.
Solution:
- Make `to_data_type` a function template so we can leverage `if
constexpr` to simplify the implementation (and speed it up).
- Use `detail::is_any_v` to check if `T` is contained within a list of
types instead of repeated `std::is_same`.
- Introduce a tag type to denote the invalid type mapping case:
`invalid_data_type`. This makes it clear from …
> data: Simplify to_data_type

- libvast/vast/concept/parseable/core/choice.hpp
Problem:
- Figuring out the attribute in the choice parser is complicated with
several nested `std::conditional_t` which hurts readability and
compilation times.
Solution:
- Replace nested `std::conditional_t` usage with `if constexpr` inside a
function to determine the attribute. This speeds up compilation times
and lets us collapse a branch from the previous code.
File-by-file.
> choice parser: Simplify attribute selection

- libvast/src/system/datagram_source.cpp
- libvast/src/system/make_transforms.cpp
- libvast/src/system/source.cpp
- libvast/src/table_slice.cpp
- libvast/src/transform.cpp
- libvast/src/transform_steps/delete.cpp
- libvast/src/transform_steps/hash.cpp
- libvast/src/transform_steps/replace.cpp
- libvast/test/transform.cpp
- libvast/vast/plugin.hpp
- libvast/vast/system/actors.hpp
- libvast/vast/system/datagram_source.hpp
- libvast/vast/system/importer.hpp
- libvast/vast/system/make_source.hpp
- libvast/vast/system/make_transforms.hpp
- libvast/vast/system/source.hpp
- libvast/vast/system/spawn_importer.hpp
- libvast/vast/table_slice.hpp
- libvast/vast/transform.hpp
- libvast/vast/transform_step.hpp
- libvast/vast/transform_steps/delete.hpp
- libvast/vast/transform_steps/hash.hpp
- libvast/vast/transform_steps/replace.hpp
- vast/vast.cpp
> Add missing documentation and style improvements for transforms

- Dockerfile
> Use correct prefix for config in Dockerfile

- .github/workflows/vast.yaml
- CMakeLists.txt
- Dockerfile
- INSTALLATION.md
- README.md
- libvast/CMakeLists.txt
- nix/vast/default.nix
This PR contains a bunch of things left out of #1657 intentionally to keep that PR simple.
Commit-by-commit, or file-by-file when enabling "hide whitespace changes".
> Prefer `ctest` and `cmake --install` over generated targets

- libvast_test/vast/test/test.hpp
> Fix syntax error in unit test macros

- README.md
We now use a CNAME redirect.
Just look/try.
> Simplify Slack URL

- changelog/unreleased/changes/1696--slack-community-chat.md
I forgot this one earlier.
:eyes:
> Change Slack URL in changelog

- cmake/Findsystemd.cmake
- libvast/CMakeLists.txt
- libvast/src/logger.cpp
- libvast/src/systemd.cpp
- libvast/vast/systemd.hpp
- vast.yaml.example
Add support for native journal / syslog output formats
> Add support for different sink types

- libvast/src/detail/backtrace.cpp
This enables VAST to compile when backtraces are disabled.
> Add missing namespace to 'backtrace()' fallback implementation

- .github/workflows/vast.yaml
Replace `github.ref` with the correct version `github.event_name`.
> Fix workflow trigger for docker build

- libvast/src/system/node.cpp
See comment in the diff. This is not user-facing for VAST, but fixes a persistence bug in the Matcher plugin.
Read the code, and most importantly, verify locally that everything still works.
> Shutdown the filesystem only when no longer used

- libvast/src/system/partition.cpp
- libvast/vast/detail/tracepoint.hpp
- Add new tracepoints for passive partition loading
- Add usage example to tracepoint header
See commit messages
> Add new tracepoints for passive partitions

- changelog/unreleased/bug-fixes/1755--bitmap-index-offset.md
- changelog/unreleased/features/1755--lsvast-indexers.md
This was a final feature request on #1755 , but split into a separate PR to avoid re-running CI over grammar/wording updates.
> Reword some changelog entries to active voice

- .github/workflows/vast.yaml
- CMakeLists.txt
- changelog/unreleased/changes/1768--C++20.md
- libvast/CMakeLists.txt
- libvast/src/chunk.cpp
- libvast/src/system/counter.cpp
- libvast/src/system/eraser.cpp
- libvast/src/system/index.cpp
- libvast/src/system/node.cpp
- libvast/src/system/query_processor.cpp
- libvast/src/system/source.cpp
- libvast/test/CMakeLists.txt
- libvast/test/index/enumeration_index.cpp
- libvast/test/time.cpp
- libvast/vast/query.hpp
- libvast/vast/system/component_registry.hpp
- libvast/vast/system/exporter.hpp
- libvast/vast/system/local_segment_store.hpp
- libvast/vast/system/meta_index.hpp
- libvast/vast/system/partition.hpp
- libvast/vast/system/source.hpp
- libvast_test/CMakeLists.txt
- libvast_test/vast/test/test.hpp
All supported build systems have recent compiler versions, so it's time to pull the trigger.
Issues that I ran into:
- `this` is no longer implicitly captured with `[=]`
- `concept` is now a keyword
- typed actor states should not have typed actor handles of different actors as their first member variable any more
Build and run locally.
> Compile with C++20

- .cmake-format
- cmake/VASTRegisterPlugin.cmake
- libvast/CMakeLists.txt
Each commit fixes a small issue that I came across recently.
Commit by commit.
> Minor build scaffold fixups

- .github/workflows/vast.yaml
- Dockerfile
- examples/jupyter/requirements.txt
- libvast/src/format/arrow.cpp
- pyvast/example/requirements.txt
- vast/integration/requirements.txt
The nix build still uses Arrow 4, so it should be good if CI passes.
> Fix compilation with Arrow 5.0

- libvast/vast/concept/hashable/hash_append.hpp
Problem:
- `hash_append` uses `std::enable_if_t` all over which is a bit verbose
and slower to compile.
Solution:
- Use concepts instead which are faster to compile and provide better
error messages.
File-by-file.
> Prefer concepts over enable_if_t in hash_append

- doc/cli/vast-version.md
As requested by @mavam, this should help avoid some confusion.
n/t
> Document showing plugins in version command help

- libvast/test/convertible.cpp
- libvast/vast/concept/convertible/data.hpp
This PR is a small addendum to the recent `convert` enhancements.
Take a quick look.
> Add convenience overload for data

- libvast/vast/concept/printable/core/printer.hpp
Problem:
- There are several call operators and some discern between the arity of
attributes which complicates the overload sets and is verbose.
Solution:
- Reduce number of call operator overloads from `4` to `2` by always
taking a parameter pack of attributes and just branching on the number
of attributes in the pack.
- Apply concepts to simplify the SFINAE.
File-by-file.
> Simplify call operators in core printer

- pyvast/setup.py
This was forgotten in the July release, and then consequently failed in the August release because the release prep script didn't pick it up. Luckily there were no changes in the past few months.
Read the description of the story and verify against the diff.
> Bump PyVAST version

- libvast/src/data.cpp
- libvast/src/segment_store.cpp
- libvast/src/system/accountant.cpp
- libvast/src/system/active_partition.cpp
- libvast/src/system/datagram_source.cpp
- libvast/src/system/exporter.cpp
- libvast/src/system/importer.cpp
- libvast/src/system/index.cpp
- libvast/src/system/local_segment_store.cpp
- libvast/src/system/node.cpp
- libvast/src/system/posix_filesystem.cpp
- libvast/src/system/sink.cpp
- libvast/src/system/source.cpp
- libvast/src/system/transformer.cpp
- libvast/src/system/type_registry.cpp
- libvast/vast/data.hpp
> Remove insert_record and insert_list

- .github/workflows/vast.yaml
These are required by follow-up actions in our internal CI.
> Upload artifacts for gcs when publishing a release

- libvast/src/system/node.cpp
Refactor the send_command to work without caf::atom_value
file-by-file review.
> Refactor the send_command to work without caf::atom_value

- libvast/src/system/index.cpp
> Add progress display for index startup

- libvast/src/system/index.cpp
- libvast/src/system/start_command.cpp
In this PR we add the version string to the startup log message and add an additional info message when the index component is ready for queries.
By commit.
> Log the version string with the startup message

- nix/overlay.nix
- nix/pinned.nix
- nix/static-binary.sh
- nix/vast/default.nix
This updates the Arrow version in the static binary to 6.0.0.
> Bump nixpkgs to 4789953e5c

- libvast/CMakeLists.txt
`liblibvast_native_plugins` -> `libvast_native_plugins`
> Fix the native plugins library name

- changelog/unreleased/features/1973--version-metrics.md
- libvast/src/system/accountant.cpp
- vast/CMakeLists.txt
Emit a metrics event when VAST is started
Review file by file.
> Emit version column along with metrics

- README.md
Wording update for readme.
Check that the links work
> Improve the wording about where to download latest (stable) vast release

- changelog/unreleased/features/2014--select-transform.md
- libvast/CMakeLists.txt
- libvast/src/transform.cpp
- libvast/src/transform_steps/select.cpp
- libvast/test/transform.cpp
- libvast/vast/transform_steps/select.hpp
- vast/integration/vast-transforms.yaml
- vast/integration/vast_integration_suite.yaml
Create the new selection transform plugin.
> Implement a selection transform plugin

- .github/workflows/vast.yaml
Do not pin actions to master and use v0 instead
> Do not pin actions to master and use v0 instead

- libvast/test/convertible.cpp
- libvast/test/index_config.cpp
- libvast/vast/concept/convertible/data.hpp
- libvast/vast/index_config.hpp
This PR contains the new index configuration.
In one slurp.
> Add new index configuration

- .github/workflows/vast.yaml
- flake.lock
- flake.nix
- nix/default.nix
- nix/nixos-test.nix
- nix/pinned.nix
- nix/static-binary.sh
> Fix static-binary.sh for flake

- libvast/test/experimental_table_slice.cpp
This verifies some assumptions we've had about Arrow and discussed this morning in Slack.
This is for @mavam / @dispanser following our earlier discussion.
> Verify Arrow List<Struct<...>> assumptions via test

- Dockerfile
> Build against libarrow700 in Dockerfile

- libvast/src/system/index.cpp
- libvast/test/system/eraser.cpp
- libvast/test/system/partition_transformer.cpp
- libvast/test/system/query_processor.cpp
- libvast/vast/fwd.hpp
- libvast/vast/system/actors.hpp
- libvast/vast/system/index.hpp
Implement "non-replacing" partition transforms
> Implement "non-replacing" partition transforms

- libvast/src/system/make_transforms.cpp
- libvast/vast/system/make_transforms.hpp
> Fix potential segfault with invalid transforms configuration

- libvast/src/system/index.cpp
- libvast/src/system/partition_transformer.cpp
- libvast/src/system/spawn_index.cpp
- libvast/src/system/type_registry.cpp
- libvast/test/system/counter.cpp
- libvast/test/system/eraser.cpp
- libvast/test/system/exporter.cpp
- libvast/test/system/index.cpp
- libvast/test/system/partition_transformer.cpp
- libvast/test/system/query_processor.cpp
- libvast/vast/system/actors.hpp
- libvast/vast/system/index.hpp
- libvast/vast/system/partition_transformer.hpp
- Allow passing multiple transforms to apply handler
- Notify type registry about transformed partitions
> Notify the type registry about transformed partitions

- plugins/aggregate/aggregate.cpp
This should improve the aggregate plugin for data that doesn't group really well.
@6yozo benchmark!
> Optimize aggregate for single-row buckets

- plugins/aggregate/README.md
Just a README bugfix that can safely go in before the release.
Double-check the README.
> Remove unrelated field in aggregate plugin example

- vast/integration/integration.py
Check that it really doesn't work as expected on current master.
> Fix the --retry option in the integration testing tool

- plugins/aggregate/aggregate.cpp
- plugins/aggregate/tests/aggregate.cpp
Improve generic aggregate error handling
> Improve generic aggregate error handling

- changelog/unreleased/changes/2122--require-arrow-7.md
- libvast/CMakeLists.txt
- plugins/aggregate/aggregate.cpp
Look for missed Arrow version checks.
> Bump the minimum version of Apache Arrow to 7.0

- libvast/src/transform.cpp
- plugins/aggregate/tests/aggregate.cpp
Improve transform trace messages.
> Improve transform messages

- cloud/aws/.terraform.lock.hcl
- cloud/aws/Makefile
- cloud/aws/README.md
This PR updates structure and content in the AWS README.
Read it.
> Tune AWS README

- libvast/src/system/application.cpp
> Clarify explanation of 'vast export'

- vast/integration/integration.py
- vast/integration/vast_integration_suite.yaml
- Add new 'ignore' option for integration test steps
- Add integration test for exporter timeouts
Review this pull request as a whole
> Add a new integration test for timed-out exporters

- libvast/include/vast/concept/convertible/data.hpp
This fixes two issues downstream in the compaction plugin with the bytesize parser:
- Passing '90' would be parsed as a YAML scalar, which in turn becomes a VAST integer, which then failed to be converted to a string.
- As an immediate follow-up, I noticed that passing an integer to the bytesize parser is also not a good option. Because YAML scalars and CAF settings only support signed integers, we must prefer not rendering the unary plus in front of positive signed integers, as otherwise downstream parsers cannot handle the resulting strings from convertible.
I don't think this needs a changelog entry here, as this had no visible effect inside VAST directly. Rather, I'll add a changelog entry to the compaction plugin when updating it to incorporate this change.
> Add a convertible overload from data to string

- plugins/aggregate/aggregate.cpp
It's not safe to store a `data_view` pointing into record batches whose underlying data may no longer be around after calls to `aggregation::add` when we want to access them in `aggregation::finish` later on. So now we store `data` instead, and to avoid having to materialize as often we instead use a robin map with support for heterogenous lookup from views.
This was a recently introduced bug only. Before the changes from #2159 we used `arrow::Scalar` for the bucket keys, which keeps the underlying data alive because it contains a strong reference to the buffer it is sliced from unlike `data_view`. Because this bug was never in a released version I think we do not need a changelog entry here.
@tobim try to reproduce the heap-use-after-free you've seen with the changes from this branch. …
> Fix heap-use-after-free in aggregate group-by keys

- .github/dependabot.yml
Let's use the existing label for this rather than a custom one.
n/t
> Use `maintenance` label for Dependabot PRs

- libvast/src/system/sink_command.cpp
This fixes a recently introduced bug that only occured in builds with assertions enabled, and thus caused CI to fail occasionally. When zeroing out the exporter and sink actor handles we can no longer compare their addresses with the address from the monitored actor in the down handler of the sink command. In case both sink and exporter issued a down message before the sink command was able to shut down the pipeline we ran into an assertion failure because the second down message would be from an actor that the sink command no longer knew. This is now fixed by taking the addresses of the actors by value rather than keeping a reference to the actor handles, and doubly so by demoting the assertion to a warning message.
@tobim since you already reviewed #2215 which introduced this bug it …
> Fix a false assertion failure on client shutdown

- changelog/unreleased/bug-fixes/2227--partition-erasure.md
- libvast/src/system/partition_transformer.cpp
- libvast/src/system/posix_filesystem.cpp
- libvast_test/vast/test/memory_filesystem.hpp
Review this pull request as a whole.
> Don't send null pointers when erasing whole partitions

- .github/workflows/jupyter.yaml
- .github/workflows/pyvast.yaml
- .github/workflows/vast.yaml
... and clean them up a bit, generally, such that we only trigger when
we really should.
Double-check with https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
> Fix CI triggers for hotfix releases

- libvast/test/query_queue.cpp
The file containing the unit test was not added to the tree by accident.
> Add missing query queue unit test

- changelog/unreleased/2239--indefinite-hang.md
- libvast/include/vast/defaults.hpp
- libvast/src/system/index.cpp
- libvast/src/system/passive_partition.cpp
- libvast/test/partition_roundtrip.cpp
- Fix direct value return after response promise has been created
- Add timeout for scheduler lookups
> Handle indefinite hang when evaluating queries on irrelevant partitions

- libvast/include/vast/system/partition_transformer.hpp
- libvast/test/transform.cpp
This PR includes remnants of a bug hunt that ultimately lead to a dead-end, but the changes are still useful.
> Add a name for the partition-transformer and improve unit test coverage

- libvast/include/vast/fbs/utils.hpp
- libvast/src/query_queue.cpp
- libvast/src/system/index.cpp
- libvast/src/system/node.cpp
- libvast/test/expression_evaluation.cpp
- libvast/test/system/filesystem.cpp
Adjust count of outstanding queries when skipping some.
Also contains
> Adjust count when skipping partitions

- vast.yaml.example
No code changes, just minor cleanup.
n/t
> Remove dead options from example configuration

- CHANGELOG.md
- changelog/legacy.md
- cmake/VASTChangelog.cmake.in
- plugins/pcap/CHANGELOG.md
- plugins/summarize/CHANGELOG.md
This should make it render better on the new docs page.
Check the generated page.
> Perform cosmetics fixups to changelog template

- libvast/include/vast/system/index.hpp
- libvast/src/system/index.cpp
> Align partition.scheduled key with the docs

- docs/docs/setup-vast/download.md
This resolves a TODO item from an earlier review on the dev build download.
Read it.
> Update prebuilt binary download instructions in docs

- docs/docs/get-started/README.md
- docs/docs/setup-vast/README.md
- docs/docs/setup-vast/deploy/README.md
- docs/docs/setup-vast/install/README.md
- docs/docs/use-vast/README.md
- docs/docusaurus.config.js
- docs/package.json
- docs/yarn.lock
This PR adds a /sitemap.xml to the page, improving SEO.
I followed the [sitemap plugin instructions](https://docusaurus.io/docs/api/plugins/@docusaurus/plugin-sitemap). Feel free to double check.
On other addition: all docs pages now contain a last modified timestamp, plus who edited it.
> Add a sitemap.xml to docs

- libvast/src/prune.cpp
A left-over from last release's hotfixing.
> Remove forgotten debug log statement

- web/docs/setup-vast/_category_.yml
- web/docs/understand-vast/README.md
- web/docs/understand-vast/data-model/concepts.md
- web/docs/understand-vast/data-model/modules.md
- web/docs/understand-vast/data-model/types.md
- web/docs/understand-vast/query-language/README.md
- web/docs/use-vast/_category_.yml
- web/docs/use-vast/ingest/README.md
- web/docs/use-vast/introspect/README.md
- web/docs/use-vast/query/README.md
- web/docs/use-vast/transform/README.md
- web/docusaurus.config.js
- web/package.json
- web/presets/CommercialPlugin.md
- web/presets/MissingDocumentation.md
- web/static/CNAME
- web/yarn.lock
This PR fixes a few smaller things:
- Fix the blog title
- Use a nicer dark mode color scheme
- Switch to latest canary release and show full docs
- Expand key sections
> Several smaller docs tweaks

- libvast/include/vast/plugin.hpp
- libvast/include/vast/system/partition_transformer.hpp
- libvast/src/system/partition_transformer.cpp
- libvast/test/system/partition_transformer.cpp
NOTE: The code compiles and looks kinda good, but hasn't been tested at all so far.
> Don't exceed max partition size in partition transformer

- cloud/aws/terraform/README.md
- cloud/aws/terraform/common/s3notif/inputs.tf
- cloud/aws/terraform/common/s3proc/inputs.tf
- cloud/aws/terraform/core-2/fargate/inputs.tf
There were some repetitions in comment, factoring it out into the README
> Refactor docs about TF resource naming

- cloud/aws/cli/plugins/integration.py
A python import seems to have been skipped during a rebase (see https://github.com/tenzir/vast/runs/7106418545)
> Fix rebase glitch

- web/docs/setup-vast/README.md
- web/docs/setup-vast/monitor.md
This PR ports the metrics docs.
Read the new use-case oriented presentation.
> Port metrics docs

- web/docusaurus.config.js
- web/package.json
- web/yarn.lock
This PR fixes the search on https://vast.io. The fix was actually in the Algolia settings and the changes in here just streamline the behavior of the search modal and the /search page.
Try searching on https://vast.io/search and read the two commits.
> Fix Algolia DocSearch

- web/docs/about-vast/vision.md
> Fix doc typo

- .github/workflows/vast.yaml
> Rename the CI workflow to properly reflect our transform renaming

- web/Makefile
This is the companion PR to https://github.com/tenzir/.github/pull/15.
Some files have now capitalized names, which this PR adjusts.
> Adjust to recent .github changes

- .github/PULL_REQUEST_TEMPLATE.md
- web/README.md
This PR updates the PR template to put more focus on the review process.
> Simplify PR template

- libvast/include/vast/bitmap.hpp
- libvast/include/vast/command.hpp
- libvast/include/vast/data.hpp
- libvast/include/vast/detail/logger.hpp
- libvast/include/vast/detail/logger_formatters.hpp
- libvast/include/vast/expression.hpp
- libvast/include/vast/module.hpp
- libvast/include/vast/msgpack_builder.hpp
- libvast/include/vast/query_queue.hpp
- libvast/include/vast/scope_linked.hpp
- libvast/include/vast/system/spawn_arguments.hpp
- libvast/include/vast/table_slice.hpp
- libvast/include/vast/table_slice_encoding.hpp
- libvast/include/vast/type.hpp
- libvast/include/vast/uuid.hpp
- libvast/include/vast/view.hpp
- libvast/src/arrow_table_slice_builder.cpp
- libvast/src/system/index.cpp
- web/docs/setup-vast/build.md
Just in time for v2.3 {fmt} released a breaking change update. This should be backwards compatible.
> Support building with {fmt} 9.x

- README.md
I went through this rather lengthy form today and filled it out, so here's a badge to show for it.
> Add an OpenSSF Best Practices badge

- libvast/native-plugins/rebuild.cpp
As discussed in Slack, this fixes a crash for 100% overlap between compaction and rebuild runs.
> Fix crash for 100% overlap between compaction and rebuilding

- libvast/src/system/partition_transformer.cpp
- libvast/src/system/passive_partition.cpp
- libvast/test/system/partition_transformer.cpp
- Don't create chunks for nonexisting indexes
- Cleanup flatbuffer container leftovers
> Don't create chunks for nonexisting indices

- .gitignore
- 000-TEMPLATE.md
- rfc/README.md
- web/Makefile
This PR factors the RFC infrastructure from #2511.
> Add RFC infrastructure

- web/docusaurus.config.js
- web/openapi/openapi.yaml
- web/package.json
- web/yarn.lock
This PR enhances the website to render the OpenAPI spec.
> Embed OpenAPI spec into site

- libvast/include/vast/system/partition_transformer.hpp
- libvast/src/system/partition_transformer.cpp
> Wait until all stores have exited before finishing a partition transform

- CMakeLists.txt
- cmake/VASTChangelog.cmake.in
- cmake/VASTRegisterPlugin.cmake
- examples/plugins/analyzer/CMakeLists.txt
- examples/plugins/pipeline_operator/CMakeLists.txt
- plugins/broker/CMakeLists.txt
- plugins/parquet/CMakeLists.txt
- plugins/pcap/CMakeLists.txt
- plugins/sigma/CMakeLists.txt
Just the usual housekeeping. No changes here that are relevant to us.
> Bump CMake policy opt-in version to 3.24

- tools/lsvast/src/print_partition.cpp
Change a word to match common DB lingo.
> Fix wording to match DB-native speak

- libvast/src/detail/pid_file.cpp
After a reboot (e.g., when restarting a container), PIDs may be re-assigned to another process. If the PID in a PID file that lingered from a VAST crash is assigned to a non-VAST process we should ignore the PID file instead of preventing startup.
> Improve PID file handling after reboot

- .github/workflows/vast.yaml
> Fix artifact uploads to GCS

- web/docs/about-vast/use-cases/README.md
- web/docs/develop-vast/README.md
- web/docs/develop-vast/contributing/README.md
- web/docs/develop-vast/guides/README.md
- web/docs/try-vast/README.md
- web/docs/understand-vast/README.md
- web/docs/understand-vast/query-language/frontends/README.md
- web/docs/understand-vast/query-language/operators/README.md
- web/docs/use-vast/README.md
- web/package.json
- web/yarn.lock
Just an upgrade, no content changes.
CI takes care of it.
> Upgrade to Docusaurus 2.1.0

- web/docs/setup-vast/monitor.md
Forgot to add metrics in feather store performance PR.
> Add missing documentation for passive store initialization time

- web/blog/public-roadmap-and-open-rfcs/index.md
CI didn't rerun after we merged #2563, which caused a TOCTTOU bug.
> Fix CI TOCTTOU race relating #2563

- libvast/native-plugins/rebuild.cpp
> Demote log level of rebuilder message

- libvast/include/vast/arrow_table_slice.hpp
- libvast/include/vast/coder.hpp
- libvast/include/vast/concept/convertible/data.hpp
- libvast/include/vast/concept/printable/vast/expression.hpp
- libvast/include/vast/detail/legacy_deserialize.hpp
- libvast/include/vast/fwd.hpp
- libvast/include/vast/hash/hash_append.hpp
- libvast/include/vast/msgpack_table_slice.hpp
- libvast/include/vast/query_context.hpp
- libvast/include/vast/system/actors.hpp
- libvast/include/vast/system/index.hpp
- libvast/include/vast/type.hpp
- libvast/native-plugins/segment_store.cpp
- libvast/src/format/csv.cpp
- libvast/src/store.cpp
- libvast/src/system/active_partition.cpp
- libvast/src/system/archive.cpp
- libvast/src/system/counter.cpp
- libvast/src/system/explore_command.cpp
- libvast/src/system/indexer.cpp
- libvast/src/system/node.cpp
- libvast/src/system/passive_partition.cpp
- libvast/src/system/type_registry.cpp
- libvast/test/feather.cpp
- libvast/test/partition_roundtrip.cpp
- libvast/test/query_queue.cpp
- libvast/test/system/catalog.cpp
- plugins/parquet/tests/parquet.cpp
Minor adjustment that will make final CAF upgrade PR shorter.
> Adjust code in preparation to CAF 18 upgrade

- libvast/CMakeLists.txt
- libvast/src/arrow_table_slice_builder.cpp
- libvast/src/format/test.cpp
> Support building VAST with clang-15

- .github/workflows/vast.yaml
> Unbreak CI on master

- .github/workflows/vast.yaml
A second follow-up to #2585, which of course failed in the section that only executes in CI in master.
> Load Docker images before adding additional tags

- rfc/001-composable-pipelines/README.md
As I was reading through RFC-001 to ensure the continuity with RFC-003, I noticed some minor glitches.
> RFC-001 minor amendments

- nix/overlay.nix
- nix/restinio/default.nix
- nix/static-binary.sh
- nix/vast/default.nix
Scaffolding to enable building the web plugin with nix
> Restinio nix package integration

- web/yarn.lock
Maintenance PR to upgrade dependencies. If CI checks out, give it a go.
> Upgrade web dependencies

- .github/workflows/vast.yaml
> Disable ASan in macOS CI job

- .github/workflows/vast.yaml
- .gitmodules
- Dockerfile
- VAST.spdx
- cmake/Findxxhash.cmake
- nix/static-binary.sh
- plugins/web/CMakeLists.txt
- plugins/web/aux/CMakeLists.txt
- plugins/web/aux/restinio.patch
- plugins/web/cmake/FindAsio.cmake
- plugins/web/cmake/Findhttp-parser.cmake
- plugins/web/cmake/Findhttp_parser.cmake
- plugins/web/src/authenticator.cpp
> Add librestinio as vendored library

- web/blog/parquet-and-feather-enabling-open-investigations/index.md
I was a few minutes too late with my read, so here goes as a fixup in a separate PR.
> Fix typo in latest blog post

- .github/workflows/vast.yaml
This should fix the problems from #2628 and #2629.
> Fix ghcr.io cache access for actors outside of Tenzir

- changelog/unreleased/changes/2619--rebuilder-log-message.md
- libvast/native-plugins/rebuild.cpp
> Demote log message for automatic rebuilds

- .github/workflows/terraform.yaml
- cloud/aws/terraform/cloudtrail/terragrunt.hcl
- cloud/aws/terraform/flowlogs/terragrunt.hcl
Story details: https://app.shortcut.com/tenzir/story/38249
- the fix is trivial, but I added some CI to actually deploy the flowlogs/cloudtrail datasources to prevent this regression from happening again
- I struggled quite a bit with Github actions to have it work:
- I split the workflow into multiple jobs to make the different checks more independent (the workflow is now a very pretty graph 😉)
- this created the need to cache the CLI docker image to avoid having to rebuild it in each job
> Fix VPC flowlogs and cloudrail plugins

- README.md
> Fix link for contributing-url in README

- changelog/unreleased/2642--uncache-failed-partitions.md
- libvast/src/system/index.cpp
> Clear failed partitions from the cache

- web/docusaurus.config.js
> Fix typo in announcement bar

- docker/misp/README.md
- docker/misp/app/app.py
- docker/misp/app/pyproject.toml
- docker/misp/docker-compose.app.yaml
- docker/poetry/Dockerfile
- docker/poetry/docker-compose.yaml
Prototype an integration between MISP and VAST
> MISP app scaffolging

- .github/workflows/vast.yaml
This fixes some oversights in the larger CI refactoring we've merged yesterday night that only showed up on master.
> Fix CI on master

- scripts/prepare-release
> Fix syntax error in prepare-release script

- changelog/unreleased/features/2567-2614-2638-3681--web-plugin.md
This adds a changelog entry for the web plugin.
> Add changelog entry for bundled frontend

- .github/workflows/vast.yaml
- docker/README.md
- docker/poetry/Dockerfile
- docker/thehive/README.md
- docker/thehive/app/app.py
- docker/thehive/app/poetry.lock
- docker/thehive/app/pyproject.toml
- docker/thehive/docker-compose.app.yaml
- docker/thehive/docker-compose.yaml
- docker/thehive/env.example
- docker/thehive/test
- docker/thehive/thehive/application.conf.template
- docker/thehive/thehive/entrypoint.py
- python/vast/__init__.py
- python/vast/utils/logging.py
- python/vast/vast/__init__.py
- python/vast/vast/cli.py
- python/vast/vast/vast.py
The goal is to create a POC python App script that forwards Alerts from Suricata to TheHive through VAST
> TheHive Alert POC Integration

- plugins/web/README.md
- plugins/web/ui/README.md
As the title says. Also fixes `vast rest` -> `vast web`.
> Add readme for the Frontend UI

- docker/thehive/README.md
- docker/thehive/app/app.py
Improve the translation of Suricata alerts into TheHive alerts
- fix severity
- fix timestamp
Also adds a reference to a test dataset
> Improve Suricata X TheHive alert translation

- .github/workflows/vast.yaml
- docker/compose/thehive.app.yaml
- docker/thehive/app/app.py
- docker/thehive/test
- docker/thehive/thehive/entrypoint.py
- docker/thehive/vast-cortex-neuron/tests/run
TheHive tests transiently fail (e.g in https://github.com/tenzir/vast/actions/runs/3619876264/jobs/6101834415). This PR tries to identify the reason and fix it.
> Fix transient errors with TheHive

- web/docusaurus.config.js
- web/src/pages/newsletter.tsx
This PR adds a link to our newsletter in the footer of the website.
> Add link to newsletter on website

- docker/thehive/README.md
> Fix command typo

- docker/thehive/README.md
Make the developer docs for TheHive more approachable.
> Improve TheHive developer facing docs

- web/docusaurus.config.js
- web/package.json
- web/src/components/Carousel/index.tsx
- web/src/components/Carousel/styles.module.css
- web/src/css/custom.scss
- web/src/pages/index.module.css
- web/src/pages/index.tsx
- web/tsconfig.json
- web/yarn.lock
This PR adds a Carousel that displays the newsletter signup link, and links to latest blogposts (release and non-release).
Please suggest changes to the copy and CSS.
```fish
cd web
yarn run docusaurus start
```
> Add Carousel component to docs site

- web/docusaurus.config.js
- web/src/pages/privacy-statement.md
This PR adds a privacy statement to the website.
> Add privacy statement to website

- web/package.json
- web/src/pages/index.module.css
- web/src/pages/index.tsx
- web/yarn.lock
These are the bugs fixed.
-    Its z-index is higher than the top bar's z-index
-    Blog post images don't show
-    It shows multiple "latest releases"
-   On Safari it is a lot taller than it's likely supposed to be (also on mobile Safari)
Make sure to use the following to test this.
```fish
cd web
yarn install
yarn start
```
> Fix multiple carousel bugs

- web/docs/understand/query-language/README.md
- web/docs/understand/query-language/frontends/README.md
- web/docs/understand/query-language/frontends/vastql.md
- web/docs/understand/query-language/pipelines.md
This PR updates the documentation after VASTQL became its own language frontend in #2832.
> Document query language frontend and related bits

- web/docs/about/target-audience.md
- web/docs/about/why-vast.md
This PR includes Oliver's latest rewording tweaks.
> Rework docs section Why VAST

- .github/workflows/vast.yaml
- scripts/regression-tests.sh
This adds automatic regression tests to our CI, comparing the current build against all previously tagged releases.
> Introduce regression tests

- web/blog/the-new-rest-api/index.md
This PR pushes the REST API blog post over the finish line.
> Publish REST API blog post

- web/blog/the-new-rest-api/index.md
Kindly reported by @1wilkens—thanks! 🙏
> Fix a typo in the REST API blog post

- libvast/src/table_slice.cpp
This was really a headscratcher: The constructor of table slice used when setting the import time in a slice that's not unqiue (1) was unnecessarily expensive and (2) only worked if the slice was serialized and not changed since.
Uisng server-side import pipelines actually resulted in a crash before this change: the pipelines resulted in slices that did not already have a serialized backing, which is a precondition for using the constructor that creates a slice from such a serialized backing.
No changelog entry, as this was just recently introduced on master.
> Fix a crash when running import pipelines

- libvast/src/system/make_pipelines.cpp
Compaction uses this one function that's not used anywhere else to build pipelines, and we forgot that in the earlier PR that added support for the new syntax for pipelines defined in the `vast.pipelines` section in the config file. This fixes that oversight.
Ultimately, we should just get rid of this function, but let's fix what we got for now and then rewrite it when we get back to this.
> Support pipeline syntax in compaction

- web/blog/vast-v3.0/index.md
Add a chapter that introduces the pipelines, with links to pages that elaborate on the implementation and usage.
> Add a chapter about the new pipeline syntax to the 3.0 blog post

- rfc/003-remote-pipelines/README.md
This PR augments [RFC-001](https://github.com/tenzir/vast/pull/2511) with remote pipelines.
> RFC-003: Remote Pipelines

- libvast/builtins/commands/rebuild.cpp
Now that we depend on CAF 0.18.7 and `fan_out_request` is properly working for requests with the result type `void` we can simplify this code a bit. The same could also be done in the partition transformer, but that's a bit more involved and likely to be replaced with some form of pipeline soon anyways, so I didn't bother.
> Use `fan_out_request` for request with `void` result

- .github/workflows/style-check.yaml
- cmake/VASTRegisterPlugin.cmake
- libvast/include/vast/plugin.hpp
- libvast/src/system/version_command.cpp
- nix/update-plugins.sh
- nix/vast/default.nix
- nix/vast/plugins/default.nix
- nix/vast/plugins/generic.nix
- nix/vast/plugins/names.nix
- nix/vast/plugins/source.json
- nix/vast/plugins/versions.nix
- plugins/parquet/CMakeLists.txt
- plugins/pcap/CMakeLists.txt
- plugins/sigma/CMakeLists.txt
- plugins/web/CMakeLists.txt
... and drop versions form bundled and Tenzir maintained plugins.
> Make plugin versioning optional

- libvast/builtins/endpoints/export.cpp
- libvast/builtins/endpoints/query.cpp
- web/openapi/openapi.yaml
Fix some syntax errors that prevented the correct API display on the website, as identified by the online validator.
> Fix OpenAPI specs

- .github/workflows/vast.yaml
- nix/vast/plugins/names.nix
- nix/vast/plugins/source.json
- plugins/fleet
This reverts a submodule bump reversion accidentally introduced in tenzir/vast#2969.
> Revert accidental submodule bump revert

- .github/workflows/vast.yaml
See https://github.com/cachix/cachix-action/issues/138 and https://github.com/NixOS/nixpkgs/pull/218858#issuecomment-1448758169.
> Bump the install-nix-action to v20

- changelog/unreleased/features/2981--openapi-endpoint.md
- plugins/web/include/web/specification_command.hpp
- plugins/web/src/server_command.cpp
- plugins/web/src/specification_command.cpp
This allows easier integration with various OpenAPI renderers.
> Add a new /openapi.json endpoint to the web plugin

- libvast/include/vast/data.hpp
- libvast/test/data.cpp
This PR does not yet refactor the existing code to make use of this.
Closes tenzir/issues#170.
> Add nested key getters `get_if` and `get_or` for record

- scripts/prepare-release
- version.json
A classic off-by-one. Good thing we have release candidates.
> Fix the tag's ancestor count prediction

- libvast/include/vast/system/active_partition.hpp
- libvast/include/vast/system/passive_partition.hpp
- libvast/src/system/active_partition.cpp
- libvast/src/system/passive_partition.cpp
This documents a known issue that right now is correctly handled, but likely to become problematic in the future. I've also filed an issue internally to track fixing this for an upcoming release.
> Document meaning of undersized index lookup results

- python/pyvast/vast/vast.py
- web/docs/use/integrate/python.md
Closes https://github.com/tenzir/issues/issues/60
> Python bindings documentation

- README.md
- web/docs/understand/language/frontends/sigma.md
These provide marginal values at this stage.
> Remove badges from README

- libvast/src/system/catalog.cpp
The catalog has for a while now shown a log message showing the number of candidate partitions to be considered for an incoming query. A few releases back we changed the catalog to do the lookup per schema, and then return the aggregated result. The log message was then shown per schema, rather than just once.
There are two ways to fix this:
1. Continue showing the log message once per schema, but actually show which schema it is for.
2. Show the log message once in total.
I chose to go for (2) as that aligns the log message with the corresponding `catalog.lookup.candidates` metric.
> Fix log message listing candidate partitions

- libvast/src/system/index.cpp
In case we get a partition that has no queries attached from the query queue we need to skip the scheduling.
> Catch wrongly queued partitions in the scheduler

- .github/workflows/vast.yaml
Fix oversight in #3099 that broke the CI configure step for pull requests.
> Fix ci configure step

- .github/workflows/configure_helpers.bash
- .github/workflows/vast.yaml
> Fix CI change detection 2

- libvast/builtins/connectors/directory.cpp
This allows combining the directory saver with downstream UNIX tools, e.g., `vast exec '... | write ssv to directory foo' | xargs awk ...`.
> Write generated file names for directory saver to stdout

- libvast/src/system/execution_node.cpp
This simplifies the stream drivers for the execution node to no longer receive ownership of the operators and to instead read them from the execution node state. The old mechanism could in some scenarios lead to a crash when calling `ctrl.warn(...)`, for which the precondition `state.op_ != nullptr` was sometimes violated.
> Fix invalid access to operator in an execution node

- .github/workflows/docker-config-base.json
- Dockerfile.extra
- demo-node/entrypoint.bash
- demo-node/timeshift-zeek.bash
Adds a docker image with custom startup behavior for demo purposes.
TODO:
> Create a dedicated Docker image for demo purposes

- libvast/include/vast/fwd.hpp
> Handle breaking change between FlatBuffers 23.5.8 and 23.5.9

- web/docs/setup/build.md
Jut a few things that came up over the last few days that I observed watching someone build VAST for the first time.
> Fix instructions for building from source

- nix/vast/plugins/source.json
- web/openapi/openapi.yaml
> Update `pipeline-manager` submodule pointer to include ephemeral pipelines

- libvast/src/configuration.cpp
This change makes it so we pick up `TENZIR_*` env variables with a higher precedence than `VAST_*` env variables. For backwards compatibility, we still support reading the old ones.
> Support `TENZIR_*` environment variables

- .github/workflows/docker.yaml
- .github/workflows/nix.yaml
- .github/workflows/vast.yaml
> Update AWS role for infra access from CI

- .github/workflows/vast.yaml
This should fix package uploads from `main` workflow runs.
> Use the vars context to access org level variables

- nix/vast/plugins/source.json
> Additional platform stability improvements

- nix/vast/plugins/source.json
Another `tenzir-plugins` submodule pointer update.
> Update submodules pointer

- libvast/builtins/operators/serve.cpp
- libvast/src/http_api.cpp
- nix/vast/plugins/source.json
- plugins/web/integration/reference/authenticated-endpoints/step_02.ref
- plugins/web/integration/reference/serve-errors/step_02.ref
- plugins/web/integration/reference/serve-errors/step_03.ref
- plugins/web/integration/reference/status-endpoint/step_03.ref
- plugins/web/integration/reference/tls-endpoints/step_03.ref
- plugins/web/integration/scripts/serve.sh
- plugins/web/integration/tests.yaml
- plugins/web/src/restinio_response.cpp
1. Fix a bug where an error response was not returned correctly
2. Improve the error messages returned from `/serve` when encountering invalid parameters
> Fix timeout issue with invalid parameters in serve endpoint

- .github/ISSUE_TEMPLATE/bug-report.yml
- .github/ISSUE_TEMPLATE/config.yml
- .github/PULL_REQUEST_TEMPLATE.md
> Update issue templates

- .github/workflows/vast.yaml
- scripts/prepare-release
And add an entry for the latest release candidate to the docs version selector.
> Update the release prep script for the Tenzir name

- changelog/next/features/XXXX--manager-diagnostics.md
- libvast/builtins/operators/shell.cpp
- libvast/include/vast/http_api.hpp
- libvast/include/vast/pipeline.hpp
- libvast/src/http_api.cpp
- libvast/src/pipeline.cpp
- nix/tenzir/plugins/source.json
> WIP: Add diagnostics to pipeline manager and a few other things

- libvast/src/execution_node.cpp
`long-running-operator | head 1` returned either
`caf::exit_reason::unreachable` or `caf::exit_reason::normal`; the error code seen should not depend on the shutdown order, so we now always return the latter.
> Fix error for early termination of upstream exec nodes

- libvast/builtins/endpoints/status.cpp
- nix/tenzir/plugins/source.json
- plugins/web/src/specification_command.cpp
- web/openapi/openapi.yaml
This documents the changes already merged with https://github.com/tenzir/tenzir/pull/3288 (and does some cleanup).
> Update pipeline manager OpenAPI docs

- scripts/prepare-release
And add `yarn` to the list of tools that are checked for availability.
> Fix generated commit msg from the prepare release script

- libvast/builtins/commands/exec.cpp
- libvast/builtins/operators/from_read_load_parse.cpp
- libvast/builtins/operators/write_to_print_save.cpp
- libvast/include/vast/error.hpp
- libvast/src/execution_node.cpp
- libvast/src/pipeline_executor.cpp
- libvast/test/pipeline.cpp
- nix/caf/source.json
- nix/tenzir/plugins/source.json
- web/openapi/openapi.yaml
This PR improves the diagnostics, in particular when using the pipeline manager, which had broken diagnostics if the error happens after parsing (see integration tests of the pipeline manager).
> Improve error and diagnostic propagation

- demo-node/entrypoint.bash
An oversight in a last minute addition on the previous PR.
> Fix the suricata ingest on the demo  node

- web/docs/setup-guides/deploy-a-node/_category_.yml
- web/docs/setup-guides/update-a-node.md
This PR provides instructions on how to update a node.
> Add update instructions

- web/blog/mobilizing-zeek-logs/index.md
- web/blog/zeek-and-ye-shall-pipe/index.md
- web/docusaurus.config.js
- web/package.json
- web/src/components/GiscusComponent/index.tsx
- web/src/pages/index.mdx
- web/src/theme/BlogPostItem/index.js
- web/yarn.lock
This PR contains a potpourri of docs-related improvements.
Most notably, we added [giscus](https://giscus.app/) commenting to the blog, using [this tutorial](https://dev.to/m19v/how-to-add-giscus-comments-to-docusaurus-439h). I enabled comments for the last two Zeek blogs.
> Perform more docs smithing

- .github/workflows/nix.yaml
The magic nix cache action leverages GitHub Actions cache to speed up Nix-related CI time by 30-50%.
https://github.com/DeterminateSystems/magic-nix-cache
> Add magic nix cache action

- libtenzir/include/tenzir/chunk.hpp
- libtenzir/include/tenzir/detail/logger_formatters.hpp
- libtenzir/include/tenzir/expression.hpp
- libtenzir/include/tenzir/module.hpp
- libtenzir/include/tenzir/port.hpp
- libtenzir/include/tenzir/query_context.hpp
- libtenzir/include/tenzir/query_processor.hpp
- libtenzir/include/tenzir/query_queue.hpp
- libtenzir/include/tenzir/scope_linked.hpp
- libtenzir/include/tenzir/table_slice_encoding.hpp
- libtenzir/include/tenzir/taxonomies.hpp
- libtenzir/include/tenzir/type.hpp
- libtenzir/include/tenzir/uuid.hpp
- nix/caf/source.json
- nix/tenzir/plugins/source.json
This change fixes ambiguous `format_to` calls that would result in build errors using `gcc>13` versions, since those versions include their own `format_to` implementation in `<format>`.
> Fix ambiguous code for gcc>13 builds

- libtenzir/builtins/formats/json.cpp
- libtenzir/include/tenzir/adaptive_table_slice_builder.hpp
- libtenzir/include/tenzir/detail/series_builders.hpp
- libtenzir/src/adaptive_table_slice_builder.cpp
- libtenzir/src/detail/adaptive_table_slice_builder_guards.cpp
- libtenzir/src/detail/series_builders.cpp
This solution is not ideal, but it should work for now.
> Fix adaptive builder by using in-place operations everywhere

- demo-node/entrypoint.bash
Immediately reading files after decompressing is dangerous, as they may still be partially buffered up to some time after the write "completed" in user space. This frequently triggered bad reads in the demo node Zeek pipeline, causing it to abort.
Calling sync after extracting the archive to disk effectively prevents this issue.
> Fix a disk IO race in the demo Zeek import

- web/docs/glossary.md
- web/sidebars.js
This PR adds a page defining key terms in the Tenzir ecosystem.
> Create a glossary that defines key terms

- nix/tenzir/plugins/source.json
This change is another submodule pointer bump.
> Bump submodules to include lazy pipeline parsing in pipeline manager

- libtenzir/builtins/operators/shell.cpp
This makes it so that the pipeline aborts when a shell operators within fails (`exit_code != 0`).
> Check exit-code in shell operator

- Dockerfile
- demo-node/csvstat.sh
- demo-node/entrypoint-noingest.bash
- demo-node/import.bash
- demo-node/load.bash
This moves the demo data import from the container startup to the image creation phase.
I also added 2 alternative stopped pipelines that are continuous by nature.
> Pre-import demo data in the demo node

- libtenzir/builtins/operators/compress_decompress.cpp
- web/docs/operators/transformations/compress.md
- web/docs/operators/transformations/decompress.md
I resolved comments on that PR as I was addressing them locally, and had auto-merge enabled, which happily triggered before I was able to push these three commits.
> Incorporate feedback for `compress` and `decompress`

- changelog/next/features/3455--show-config.md
- libtenzir/builtins/aspects/config.cpp
- libtenzir/include/tenzir/adaptive_table_slice_builder.hpp
- libtenzir/src/adaptive_table_slice_builder.cpp
- web/docs/operators/sources/show.md
The `config` aspect returns the current configuration as an event.
> Implement `show config`

- changelog/next/features/3457.md
- libtenzir/builtins/operators/show.cpp
- nix/tenzir/plugins/source.json
- tenzir/integration/reference/parse-operators/step_00.ref
- web/docs/operators/sources/show.md
Example output of `show pipelines`:
```json
{
"id": "0",
"name": "Example eth0 Import",
"definition": "from nic eth0 | decapsulate data | import",
"state": "stopped",
"error": "",
"restart_with_node": false
}
```
> Make `show pipelines` a thing

- changelog/next/features/3471--pausing-and-resuming-pipelines.md
- nix/tenzir/plugins/source.json
- plugins/web/src/specification_command.cpp
- web/openapi/openapi.yaml
Another submodule pointer bump.
> Bump the tenzir-plugins submodule pointer to include the pipeline manager's resuming and pausing functionality

- changelog/next/bug-fixes/3487--persisted-pipelines-stopped-upon-load.md
- nix/tenzir/plugins/source.json
Another submodule pointer bump.
> Bump submodule pointer to include pipeline manager deserialization update

- .github/workflows/nix.yaml
- flake.lock
- flake.nix
- nix/overlay.nix
- nix/restinio/default.nix
- nix/tenzir/default.nix
- shell.nix
Notable changes in this update are:
* Arrow 13
* spdlog 1.12 / fmt 10.1
* deduplication of abseil
> Bump nixpkgs to 5eba4b7a0

- .github/workflows/tenzir.yaml
- changelog/next/features/3498--gcs-connector.md
- nix/google-cloud-cpp/0001-Use-pkg-config-to-find-CURL.patch
- nix/overlay.nix
- nix/tenzir/default.nix
- plugins/gcs/CMakeLists.txt
- plugins/gcs/src/plugin.cpp
- web/docs/connectors/gcs.md
- web/docs/developer-guides/build-from-source.md
This change implements a `gcs` plugin, consisting of a `gcs` saver and loader.
> Implement the GCS connector plugin

- Dockerfile
- changelog/next/features/3496--s3-connector.md
- libtenzir/CMakeLists.txt
- libtenzir/builtins/connectors/s3.cpp
- libtenzir/include/tenzir/plugin.hpp
- libtenzir_test/src/main.cpp
- scripts/debian/install-dev-dependencies.sh
- tenzir/integration/reference/parse-operators/step_03.ref
- tenzir/integration/reference/s3-connector/step_00.ref
- tenzir/integration/tests.yaml
- tenzir/tenzir.cpp
- web/blog/tenzir-v4.2/index.md
- web/docs/connectors/s3.md
- web/docs/developer-guides/build-from-source.md
This change implements an S3 saver and loader.
> Implement the s3 connector

- libtenzir/builtins/connectors/s3.cpp
- plugins/gcs/src/plugin.cpp
- plugins/zmq/src/plugin.cpp
This PR improves the handling of URIs without an explicit scheme.
> Auto-complete missing URI schemes

- .github/workflows/installer.yaml
- scripts/install.sh
Follow up to https://github.com/tenzir/tenzir/pull/3502 that fixes the failing CI: https://github.com/tenzir/tenzir/actions/runs/6230415620/job/16926081974
> Fix installer on debian docker

- libtenzir/builtins/formats/pcap.cpp
- libtenzir/include/tenzir/pcapng.hpp
This PR gives a nicer error message when encountering PCAPng instead of PCAP dataflows.
> Provide meaningful error when encountering PCAPng

- nix/tenzir/plugins/source.json
- plugins/web/src/specification_command.cpp
- web/openapi/openapi.yaml
Another API docs and submodule pointer bump.
> Update the main repository to include the `/pipeline/launch` endpoint

- libtenzir/builtins/connectors/file.cpp
- libtenzir/builtins/formats/lines.cpp
- nix/tenzir/plugins/source.json
This adds a log message to inform the user when a disconnected node re-established the connection to the Tenzir Platform.
> Print a log message upon platform reconnect

- libtenzir/builtins/formats/zeek_tsv.cpp
- tenzir/integration/reference/zeek-tsv-pipeline-format/step_11.ref
- tenzir/integration/reference/zeek-tsv-pipeline-format/step_12.ref
- tenzir/integration/reference/zeek-tsv-pipeline-format/step_13.ref
- tenzir/integration/reference/zeek-tsv-pipeline-format/step_14.ref
- tenzir/integration/reference/zeek-tsv-pipeline-format/step_15.ref
- tenzir/integration/tests.yaml
> Unflatten implicitly in the `zeek-tsv` parser

- changelog/next/features/3554.md
- nix/tenzir/plugins/source.json
This change is a submodule pointer bump to include extended + serialized pipeline states.
> Update the plugins submodule pointer to include extended & serialized pipeline states

- Dockerfile
- nix/tenzir/plugins/source.json
- scripts/debian/install-dev-dependencies.sh
See description in the linked [submodule PR](https://github.com/tenzir/tenzir-plugins/pull/119).
> Link Boost.URL as a regular library

- plugins/velociraptor/src/plugin.cpp
- web/blog/integrating-velociraptor-into-tenzir-pipelines/index.md
- web/docs/operators/sources/velociraptor.md
This PR is basically #3573, but unfortunately we currently can't run CI from external contributors.
> Complete Velociraptor blog post and add a few fix-ups

- plugins/velociraptor/src/plugin.cpp
- web/blog/integrating-velociraptor-into-tenzir-pipelines/index.md
- Make it easier to filter out log messages
- Undraft blog and set correct publishing date
> Publish Velociraptor blog post

- web/blog/integrating-velociraptor-into-tenzir-pipelines/index.md
> Enable comments for Velociraptor blog post

- changelog/next/breaking-changes/3585.md
- changelog/next/features/3585.md
- libtenzir/src/http_api.cpp
- libtenzir/src/version.cpp
- nix/tenzir/plugins/source.json
- plugins/web/src/specification_command.cpp
- web/openapi/openapi.yaml
This change is a submodule bump and adds functionality for the extended deployment options in the pipeline manager.
> Implement extended deployment options

- libtenzir/test/legacy_type.cpp
We haven't touched code that relates to this in ages, and it started to fail sporadically in CI quite frequently over the past week. This attempts to isolate or even fix the failure, that we are sure is some form of UB.
I managed to reproduce the failure locally in a macOS VM that more or less mirrors our CI environment.
After some investigation, @tobim and I agreed that it is impossible for users to reach this code, as legacy types are only used as an intermediate data structure during parsing, but not for any equality comparisons outside of unit tests.
> Remove flaky unit test

- nix/tenzir/plugins/source.json
- plugins/web/src/specification_command.cpp
- web/openapi/openapi.yaml
(Note: Some of the changes in `openapi.yaml` are just because this file was not regenerated for a while.)
> Remove operator list from API

- demo-node/setup.bash
The app uses all-lowercase RGB strings. Although I have just opened a PR for coercing to lowercase before matching the fg and bg colors for the labels, it does not hurt to change them here too.
Also, the suricata label color was slightly wrong from the app value.
> Fix demo-node label color strings

- libtenzir/builtins/commands/exec.cpp
This is mainly useful for programs that want to wrap a user-defined pipeline into their own implicit source or sink without having to resort to string manipulation. One example would be a python binding that gets a user-defined pipeline string and wants to add a custom "to python format" implicit sink.
> Allow the user to control the implicit sinks and sources of a pipeline

- libtenzir/builtins/operators/show.cpp
- libtenzir/include/tenzir/pipeline.hpp
- libtenzir/src/execution_node.cpp
- nix/tenzir/plugins/source.json
Whoops.
This hasn't made it into a release yet, so no changelog entry required.
> Fix bug that caused all operators to be treated as internal

- libtenzir/builtins/connectors/tcp.cpp
The code replacement should be equivalent according to the [Boost.ASIO docs](https://www.boost.org/doc/libs/1_83_0/doc/html/boost_asio/reference/basic_socket_acceptor/basic_socket_acceptor/overload5.html)
> Avoid throwing constructor in tcp operator

- changelog/next/features/3646--kv-parser.md
- libtenzir/CMakeLists.txt
- libtenzir/builtins/formats/kv.cpp
- tenzir/functional-test/data/txt/key_value_pairs.txt
- tenzir/integration/reference/kv-operator/step_00.ref
- tenzir/integration/reference/parse-kv/step_00.ref
- tenzir/integration/reference/parse-kv/step_01.ref
- tenzir/integration/reference/parse-kv/step_02.ref
- tenzir/integration/tests.yaml
- web/docs/formats/kv.md
The `kv` parser splits strings into key-value pairs.
> Add `kv` parser

- Dockerfile
- demo-node/setup.bash
- docker-compose.yaml
- libtenzir/src/connect_to_node.cpp
- libtenzir/src/connector.cpp
- libtenzir/src/execution_node.cpp
These were left over from debugging the blocking operators fix; don't think we need them anymore.
> Remove two unnecessary calls to `schedule_run()`

- libtenzir/builtins/contexts/geoip.cpp
- libtenzir/builtins/contexts/lookup-table.cpp
- libtenzir/builtins/operators/lookup.cpp
- libtenzir/include/tenzir/plugin.hpp
- nix/tenzir/plugins/source.json
- web/docs/operators/lookup.md
This change implements the  `lookup` operator that allows the user to apply a context to a live or retroactive stream of events.
> Implement the `lookup` operator

- libtenzir/builtins/connectors/tcp.cpp
This PR streamlines the response promise handling in the TCP connector, avoiding potential double delivery.
> Improve robustness of TCP connector

- libtenzir/builtins/operators/pseudonymize.cpp
This bug was caused by `configuration::seed_bytes` being computed by the operator constructor, while at the same time, it was not listed in the `inspect()` implementation. Hence, serializing this operator made the seed all-zero.
> Fix serialization of `pseudonymize` operator

- plugins/fluent-bit/src/plugin.cpp
This change fixes a warning during building by adding a more explicit edge case handling for unknown MsgPack types in the `fluent-bit` plugin.
> Add an additional control flow for unspecified msgpack types in the fluent-bit plugin

- changelog/next/bug-fixes/3801--fix-launch.md
- nix/tenzir/plugins/source.json
> Optimize pipeline when using `/pipeline/launch`

- changelog/next/breaking-changes/3785.md
- changelog/next/features/3785.md
This should have been part of the original PR.
> Fix changelog of #3785

- .github/workflows/analysis.yaml
- .github/workflows/nix.yaml
- .github/workflows/tenzir.yaml
This supersedes https://github.com/tenzir/tenzir/pull/3740 and https://github.com/tenzir/tenzir/pull/3739.
> Use new job-level artifact mechanism in CI

- changelog/next/features/3812--concepts-everywhere.md
I forgot to push this commit to #3812, and that's already merged, so here it is in a new PR.
> Add a missing changelog entry

- web/docs/setup-guides/size-a-node.md
This PR embeds the node sizing calculator in the docs.
> Embed node sizing calculator

- changelog/next/bug-fixes/3854--amqp-static-binary.md
- cmake/TenzirPackage.cmake
- libtenzir/builtins/operators/python.cpp
- nix/tenzir/default.nix
- plugins/amqp/CMakeLists.txt
> Enable the AMQP plugin in the static binary

- changelog/next/features/3848--velociraptor-profiles.md
- plugins/velociraptor/src/plugin.cpp
- web/docs/operators/velociraptor.md
> Support setting profiles in the Velociraptor config

- libtenzir/src/execution_node.cpp
If a transformation or sink operator finishes without yielding, preceding operators effectively dangle because they are set up but never receive any demand. We need to explicitly shut them down to avoid a hang.
Note that there is no current operator that can run into this, so while this is a bug fix it is not something that a user could've run into; I just happened to run into this while working on a new operator with a stub implementation that didn't yield anything.
> Fix hang for no-op transformations and sinks

- changelog/next/features/3834.md
- libtenzir/builtins/contexts/bloom_filter.cpp
- libtenzir/include/tenzir/dcso_bloom_filter.hpp
- libtenzir/include/tenzir/dcso_bloom_hasher.hpp
- libtenzir/include/tenzir/hash/fnv.hpp
- libtenzir/src/dcso_bloom_filter.cpp
- libtenzir/test/dcso_bloom_filter.cpp
- libtenzir/test/hash/hash_algorithms.cpp
- web/blog/tenzir-v4.9/index.md
- web/docs/contexts/bloom-filter.md
This PR adds a Bloom filter context.
```[tasklist]
```
> Add Bloom filter context

- changelog/next/features/3883.md
- nix/tenzir/plugins/source.json
- web/docs/operators/diagnostics.md
- web/docs/operators/metrics.md
- web/openapi/openapi.yaml
This change is another submodule pointer + OpenAPI docs bump.
> Update the main repository to include the pipeline run ID

- web/docs/setup-guides/size-a-node.md
This PR adds more details on the node sizing docs.
> Enhance node sizing docs

- libtenzir/builtins/contexts/bloom_filter.cpp
- libtenzir/builtins/contexts/geoip.cpp
- libtenzir/builtins/contexts/lookup_table.cpp
- libtenzir/builtins/formats/kv.cpp
- libtenzir/builtins/operators/grok.cpp
- libtenzir/builtins/operators/time.cpp
- libtenzir/include/tenzir/fwd.hpp
- libtenzir/include/tenzir/plugin.hpp
- libtenzir/include/tenzir/series.hpp
- libtenzir/include/tenzir/series_builder.hpp
- libtenzir/src/detail/add_message_types.cpp
- libtenzir/src/plugin.cpp
- libtenzir/src/series_builder.cpp
- nix/tenzir/plugins/source.json
This is far from being what we'd like to have eventually, but it's a decent enough starting point to start iterating on.
> Introduce a most barebones `series` type

- web/docs/faqs.md
A small typo correction I discovered while reading the docs.
> Typo correction in FAQs

- .github/workflows/nix.yaml
- docker/systemd-test/Dockerfile
- scripts/debian/postinst
- scripts/install.sh
Contrary to the existing installer test, this one also verifies that the `tenzir-node` service comes up as desired.
> Test binary package installation in every PR

- .github/workflows/bump-plugins-submodule.yaml
- .github/workflows/tenzir.yaml
On a push to main, this will check if the commit that the tenzir-plugins submodule points to is the current master commit of the tenzir/tenzir-plugins repository. If not, it will automatically merge the corresponding plugins PR, update the nix settings, and push a new commit to main.
> Introduce a CI job to automatically update submodule main branch

- changelog/next/features/3893--context-content-dumping.md
- libtenzir/builtins/contexts/bloom_filter.cpp
- libtenzir/builtins/contexts/geoip.cpp
- libtenzir/builtins/contexts/lookup_table.cpp
- libtenzir/include/tenzir/plugin.hpp
- nix/tenzir/plugins/source.json
- web/docs/operators/context.md
This change implements a context content dumping mechanism for debugging purposes.
> Implement a context content dumping mechanism

- .github/workflows/upload-cache-artifact.yaml
> Fix upload cache artifact more harder

- scripts/install.sh
This PR improves `sudo` usage in the installer.
> Run the installer script more flexibly as root

- libtenzir/builtins/formats/json.cpp
- libtenzir/include/tenzir/series.hpp
- libtenzir/include/tenzir/table_slice.hpp
- libtenzir/src/offset.cpp
- libtenzir/src/table_slice.cpp
Opening this for @mavam as he wanted this functionality for another branch.
> Add `table_slice::values()` for row-major access

- .github/workflows/docker.yaml
- changelog/next/features/3989--arm64-docker.md
This makes our Docker images multi-arch images, running natively on linux/amd64 and on linux/arm64/v8.
> Introduce multi-arch Docker images

- libtenzir/builtins/contexts/lookup_table.cpp
- nix/tenzir/plugins/source.json
Closes https://github.com/tenzir/issues/issues/1087, plugins PR: https://github.com/tenzir/tenzir-plugins/pull/203
> Type-independent numeric lookup for `lookup-table`

- changelog/next/bug-fixes/3997--platform-periodic-reconnects.md
- nix/tenzir/plugins/source.json
This change is a pointer bump.
> Update the submodule pointers to include periodic platform reconnects

- libtenzir/builtins/formats/json.cpp
New releases of `simdjson` include `simdjson::ondemand::number_type::big_integer`. This PR makes it so that we don't have a non-exhaustive `switch` (if it exists), while still being compatible with older `simdjson` versions. 
This can be removed once we require a newer `simdjson` version, but it was easy enough to support.
> Handle presence of simdjson number type `big_integer`

- plugins/sigma/src/plugin.cpp
This validates some assumptions in the Sigma operator that could've led to a crash.
> Validate assumptions in Sigma operator

- changelog/next/features/4035--files-source.md
- libtenzir/builtins/operators/files.cpp
- web/docs/operators/files.md
Slowly but surely turning `tenzir` into my shell.
> Add a `files` source

- changelog/next/features/4050--every-operator-modifier.md
- libtenzir/builtins/operators/delay.cpp
- libtenzir/builtins/operators/every.cpp
- libtenzir/builtins/operators/local_remote.cpp
- tenzir/integration/data/reference/every/test_every_errors/step_00.ref
- tenzir/integration/data/reference/every/test_every_errors/step_01.ref
- tenzir/integration/data/reference/every/test_every_errors/step_02.ref
- tenzir/integration/data/reference/every/test_every_errors/step_03.ref
- tenzir/integration/data/reference/every/test_every_errors/step_04.ref
- tenzir/integration/data/reference/every/test_every_modifier/step_00.ref
- tenzir/integration/data/reference/every/test_every_modifier/step_01.ref
- tenzir/integration/data/reference/every/test_every_modifier/step_02.ref
- tenzir/integration/data/reference/every/test_every_with_remote/step_00.ref
- tenzir/integration/data/reference/every/test_every_with_remote/step_01.ref
- tenzir/integration/tests/every.bats
- web/docs/connectors/http.md
- web/docs/language/operator-modifiers.md
`every <interval> <operator> [<args...>]` runs the source operator `<operator>` every `<interval>`.
Fixes tenzir/issues#1670
> Introduce the `every` operator modifier

- .github/workflows/tenzir.yaml
> Fix plugin integration test running in CI

- changelog/next/features/4057--set-operator.md
- libtenzir/builtins/operators/put_extend_replace_set.cpp
- tenzir/integration/data/reference/pipelines_local/test_set_operator/step_00.ref
- tenzir/integration/tests/pipelines_local.bats
- web/docs/operators/extend.md
- web/docs/operators/replace.md
- web/docs/operators/set.md
This is the sweet spot between `extend` and `replace`.
> Add the `set` operator for upserting fields

- libtenzir/builtins/operators/python.cpp
The python operator creates dedicated virtual envs on first use, and that causes the initialization to take a long time. This causes problems when the pipeline is created somewhere that has a short timeout, triggering that before a response can be sent.
This change solves that by delaying the venv creation until the pipeline has reached the running state, at which point client timeouts are handled by the `/serve` endpoint.
> Fail late in the python operator setup

- libtenzir/builtins/operators/every.cpp
The current implementation never updates `now` when `every` is used as a source. As a consequence, the calculated `delta` grows bigger and bigger and the effective delay is multiplied by `n` for the `n`-th iteration. This PR makes sure that `now` is always updated.
As the bug was only recently introduced (#4109), no changelog is necessary.
> Fix `every` operator when used as a source

- libtenzir/include/tenzir/fwd.hpp
- libtenzir/src/error.cpp
- nix/tenzir/plugins/source.json
This PR contains some fixes to actually make configured pipelines autostart.
> Fix configured pipeline autostart

- nix/tenzir/plugins/source.json
Purely a refactoring for better maintainability, not a functional change at all.
> Split up the context plugin into multiple files

- nix/tenzir/plugins/source.json
This PR improves usage of our cURL abstractions.
> Improve cURL abstractions

- libtenzir/builtins/operators/slice.cpp
This fixes `batch X | slice --begin Y` where $`X = Y - 1`$.
> Fix an off-by-one in the `slice` operator

- libtenzir/src/start_command.cpp
- nix/tenzir/plugins/source.json
- web/docs/faqs.md
- web/docs/troubleshooting.md
- web/sidebars.js
This PR adds a new top-level *Troubleshooting* section that collects common issues and advice on how to mitigate them.
> Add troubleshooting docs section

- web/docs/tenzir-vs-cribl.md
This PR corrects an invalid statement in the docs.
> Remove invalid statement

- libtenzir/builtins/operators/unordered.cpp
- nix/tenzir/plugins/source.json
- web/docs/language/operator-modifiers.md
- web/docs/operators/publish.md
... and introduce the `unordered` modifier.
> Make the `publish` operator unordered

- libtenzir/src/execution_node.cpp
This vastly improves error handling when interfacing with third-party libraries that throw an unexpected exception.
> Render exceptions from operators as diagnostics

- libtenzir/builtins/components/metrics_collector.cpp
- tenzir/integration/data/misc/scripts/csvstat.sh
- tenzir/integration/lib/bats-tenzir/src/fixtures.bash
- tenzir/integration/tests/setup_suite.bash
These are a bunch of minor improvements that I found during other recent work. They are not directly related or necessary for any planned work, but it is still valuable to use opportunities for cleanup and simplifications to make our lives a little easier in the long run.
To the reviewer:
CI should catch possible errors, please don't spend more than 2 minutes on this. If you find an issue with one of the changes I will just drop that.
> Minor cleanups and simplifications

- .github/workflows/nix.nu
- CMakeLists.txt
- flake.lock
- flake.nix
- nix/overlay.nix
- nix/tenzir/default.nix
This bumps us to Arrow 16.0.0 and spdlog 3.9.1.
> Bump nixpkgs to 94035b482

- libtenzir/src/node.cpp
I recently introduced this alongside the component lifetime logging. For some old components, we do still use the labels that I thought we didn't use anymore. Ignoring them led to the components being tracked wrongly and the assertions `num_erased == 1` right below the diff to be triggered.
> Fix a panic on shutdown

- plugins/amqp/src/plugin.cpp
This fixes an oversight from tenzir/tenzir#4112 that caused the Nix build to fail.
> Fix rendering of AMQP error code

- web/docs/developer-guides/build-from-source.md
* Update the required version for flatbuffers to current
* Fix a few table entries that did bit align the version requirement correctly
> Update flatbuffers version requirement and fix table

- web/docs/integrations/velociraptor.md
- web/docs/setup-guides/deploy-the-platform.md
- web/docusaurus.config.js
- web/src/pages/newsletter.tsx
This PR updates Velociraptor and Platform docs.
> Update a few things in the docs

- libtenzir/builtins/formats/json.cpp
This PR increases the maximum size of a single object/event when *not* using the NDJSON mode (which does not have such a restriction). If a fixed maximum becomes problematic in the future, we can use a dynamic approach instead, but in the meantime, this should work with most documents.
> Increase maximum JSON object size to 10MB

- nix/tenzir/plugins/source.json
This change is another submodule pointer bump.
> Update the submodule pointer to include the new lookup operator integration tests

- changelog/next/features/4196--editable-definitions.md
- libtenzir/src/version.cpp
- nix/tenzir/plugins/source.json
- web/openapi/openapi.yaml
This is another submodule bump with an API docs update.
> Allow editing definitions of managed pipelines

- libtenzir/builtins/operators/sort.cpp
This makes the `sort` operator behave much better when trying to do a sort that Arrow doesn't support, e.g., sorting lists.
> Avoid crash when Arrow's `sort_indices` fails

- web/blog/an-interns-reflection/index.md
- web/blog/authors.yml
@balavinaithirthan wrote a blog post reflecting on this internship at Tenzir, which ended today.
> Publish Bala's internship reflection

- libtenzir/builtins/commands/rebuild.cpp
The multi-stage rebuilds come from a time when rebuilds were manually triggered only. The excess partitions will nowadays simply be picked up by the next automatic run of the rebuilder.
Why change this now, you may ask, with a revamp of the storage engine ongoing? A customer reported that the assertion that verified that excess implied at least two resulting assertions triggered. I don't understand why that assertion existed in the first place—unfortunately `git blame` only points to myself. So I chose to remove the problematic code.
> Remove multi-stage rebuilds

- libtenzir/builtins/aggregation-functions/quantile.cpp
- libtenzir/include/tenzir/plugin.hpp
Just a refactoring, not a functional change. Idea shamelessly stolen from https://github.com/tenzir/tenzir/pull/4239#discussion_r1659739896.
> Allow plugins to be registered with arguments

- libtenzir/include/tenzir/diagnostics.hpp
- libtenzir/include/tenzir/tql2/ast.hpp
- libtenzir/src/diagnostics.cpp
- libtenzir/src/tql2/exec.cpp
- nix/tenzir/plugins/source.json
This is an internal change that does not have any visible impact (yet).
> Prepare the pipeline manager for TQLv2

- libtenzir/include/tenzir/session.hpp
This should have really been part of #4357, not sure how this happened.
> Add missing diagnostic severity check

- libtenzir/builtins/formats/json.cpp
- libtenzir/builtins/formats/xsv.cpp
- libtenzir/include/tenzir/tql2/plugin.hpp
This adds a second TQLv2 parser besides `read_json`, namely `read_csv`. Because both parsers are currently wrappers for the TQLv1 parsers, this PR extracts a small adapter for this. This is very likely a temporary thing and needs to be replaced soon, for example when we want to support inferring the parser for `from "example.<ext>"`.
> Add `read_csv` and extract adapter for the legacy parser interface

- libtenzir/builtins/formats/grok.cpp
Some grok/regex patterns lead to catastrophic backtracking on some strings. Instead of aborting the pipeline, we decided to produce a warning instead, although such patterns should be simplified/optimized if possible.
> Handle complexity errors in `grok` parser

- libtenzir/include/tenzir/type.hpp
- libtenzir/src/pipeline.cpp
Just two small changes that we wanted to sneak in before the next release.
> Check sum type accesses and improve local executor

- libtenzir/src/tql2/set.cpp
Since schema name and the internal flag are reflected by Arrow's schema, we have to keep both in sync. The import time does not need this because it's not part of the Arrow schema.
> Fix TQL2 metadata assignment

- libtenzir/src/tql2/parser.cpp
Turns out this TQL2 feature was rather easy to implement.
> Add `else if` as a better alternative to nested `if`s

- libtenzir/builtins/commands/exec.cpp
- libtenzir/builtins/connectors/curl.cpp
- libtenzir/builtins/formats/json.cpp
- libtenzir/builtins/formats/yaml.cpp
- libtenzir/builtins/operators/compress_decompress.cpp
- libtenzir/builtins/operators/from_load_read.cpp
- libtenzir/include/tenzir/exec_pipeline.hpp
- libtenzir/include/tenzir/plugin.hpp
- libtenzir/include/tenzir/tql2/ast.hpp
- libtenzir/include/tenzir/tql2/plugin.hpp
- libtenzir/src/tql2/exec.cpp
- libtenzir/src/tql2/registry.cpp
This PR adds a bunch of new stuff:
- `load` 
- `save`
- `save_http`
- `read_suricata`
- `read_zeek_json`
- `read_yaml`
- `compress`
- `decompress` 
- `--dump-pipeline`
> Add `load`, `save` and a few related operators (TQL2)

- tenzir/tenzir.cpp
The plugin unloading guard has to be created before the call to `make_application`, as the return value of that can reference dynamically loaded command plugins, which must not be unloaded before the destructor of the return value.
> Fix dynamic plugin unloading order

- libtenzir/builtins/operators/shell.cpp
A very small addition so we can avoid one level of escaping in TQL2 pipelines.
> Make the `shell` operator available in TQL2

- libtenzir/builtins/operators/tcp-listen.cpp
This is a follow up to 45e4bba19, which did not resolve the problem entirely.
> Allow immediate restarts of the TCP listen connector - take 2

- libtenzir/builtins/operators/python.cpp
- libtenzir/src/active_partition.cpp
- libtenzir/src/index.cpp
It was unable to create it's internal cache directory.
> Fix the python operator in the docker image

- libtenzir/builtins/formats/syslog.cpp
Quick addition of `read_syslog` for TQL2
> Add TQL2 `read_syslog` operator

- libtenzir/builtins/formats/lines.cpp
This PR adds the `read_lines` operator.
> Add `read_lines` operator

- scripts/auto-reload.py
> Add script that auto-reloads TQL & input

- libtenzir/builtins/operators/serve.cpp
When using Tenzir via [app.tenzir.com](https://app.tenzir.com), the `serve` operator is one of the must used operators, as all data transfer from pipelines to the Tenzir Platform runs through it.
The operator was—for the lack of better internal APIs at the time of writing it—marked as detached, i.e., an operator that did not participate in cooperative scheduling but rather required its own thread.
This change makes it so the operator uses the newer internal APIs that work well with cooperative scheduling. This has two effects: spawning a pipeline with `serve` is now faster, and there's less oversubscription of threads.
Additionally, this ports the `serve` operator to TQL2.
> Make the `serve` operator cheaper to start

- libtenzir/src/package.cpp
The `restart-on-error` field in a package definition has a complicated type that is not easy to reliably parse from JSON and/or YAML input. As a convenience, if we encounter a string here try to parse it delayed as we validate the package definition.
> Allow strings for 'restart-on-error' field

- libtenzir/builtins/functions/ocsf.cpp
Completes the mappings between OCSF "category" and "class" and UIDs
> Complete bidirectional OCSF category and class mappings

- web/docs/map-data-to-ocsf/README.md
There was a small error in the Zeek mapping pipeline.
> Fix Zeek mapping pipeline

- web/docs/map-data-to-ocsf/README.md
This PR various touch-ups and tweaks.
> Docs nail filing 💅

- libtenzir/builtins/functions/misc.cpp
- libtenzir/builtins/operators/python.cpp
- libtenzir/src/plugin.cpp
- libtenzir/src/type.cpp
- tenzir/tenzir.cpp
- web/docs/overview.md
The unary `secret` and `env` functions access values in the `tenzir.secrets` configuration section and environment variables, respectively.
> Implement `secret` and `env` functions

- libtenzir/builtins/operators/every_cron.cpp
- libtenzir/include/tenzir/pipeline.hpp
- libtenzir/src/pipeline.cpp
- tenzir/integration/data/reference/every/test_every_with_multiple_operators/step_00.ref
- tenzir/integration/data/reference/every/test_every_with_multiple_operators/step_01.ref
- tenzir/integration/tests/every.bats
This is an interim implementation until we have proper sub-pipelines.
> Handle `every` with multiple operators

- web/docs/overview.md
Aligning it with the other marketing material.
> Fix the slogan on the overview page

- libtenzir/builtins/functions/string.cpp
This adds the following methods for transforming strings:
- `capitalize`
- `reverse`
- `to_lower`
- `to_title`
- `to_upper`
And also the following methods for classifying strings:
- `is_alnum`
- `is_alpha`
- `is_lower`
- `is_numeric`
- `is_printable`
- `is_title`
- `is_upper`
> Implement methods for transforming and classifying strings

- libtenzir/builtins/functions/community_id.cpp
- libtenzir/builtins/operators/decapsulate.cpp
- libtenzir/include/tenzir/community_id.hpp
- libtenzir/include/tenzir/series.hpp
- libtenzir/test/community_id.cpp
- tenzir/integration/data/reference/functions/test_community-2d5fid/step_00.ref
- tenzir/integration/tests/functions.bats
This PR adds a `community_id` function to TQL.
> Add `community_id` TQL function

- libtenzir/builtins/operators/batch.cpp
This adds the missing size and timeout parameters to the `batch` operator in TQL2. For example:
```
// tql2
batch 4Ki, timeout=250ms
```
- Fixes https://github.com/tenzir/issues/issues/2092
> Add missing `batch` parameters in TQL2

- .github/workflows/installer.yaml
> Keep going in installer tests if one fails

- .github/workflows/installer.yaml
- scripts/install.sh
This changes to installer test to run both the `latest` and `main` builds of the package. This is useful to verify that a fix has indeed solved a packaging problem without having to wait for the next release.
> Include the main branch in the installer tests

- changelog/next/bug-fixes/4578--azure-log-fix.md
- nix/tenzir/plugins/source.json
> Fix the `azure-log-analytics` operator (again)

- libtenzir/builtins/functions/int.cpp
Adds missing overloads for the integer conversion functions to allow `uint` <--> `int` conversions.
Closes https://github.com/tenzir/issues/issues/2108
> Add `int(<uint>)` and `uint(<int>)` overloads

- web/docs/installation/install-a-package.md
- web/docs/packages.md
- web/docs/write-a-package.md
- web/sidebars.js
This PR adds a guide on how to write a package.
Best reviewed commit-by-commit.
> Add a guide on how to write a package

- nix/tenzir/plugins/source.json
See https://github.com/tenzir/tenzir-plugins/pull/308
> Perform a final sanity check before sending websocket messages

- web/docs/integrations/azure-log-analytics.md
- web/docs/tenzir-vs-cribl.md
This PR improves the documentation at a few places.
> Improve docs here and there

- libtenzir/include/tenzir/as_bytes.hpp
- libtenzir/include/tenzir/concept/convertible/data.hpp
- libtenzir/include/tenzir/concept/parseable/core/parser.hpp
- libtenzir/include/tenzir/concept/parseable/core/repeat.hpp
- libtenzir/include/tenzir/concept/parseable/numeric/integral.hpp
- libtenzir/include/tenzir/concept/printable/core/printer.hpp
- libtenzir/include/tenzir/concept/printable/detail/print_numeric.hpp
- libtenzir/include/tenzir/concept/printable/numeric/integral.hpp
- libtenzir/include/tenzir/concepts.hpp
- libtenzir/include/tenzir/detail/algorithms.hpp
- libtenzir/include/tenzir/detail/math.hpp
- libtenzir/include/tenzir/detail/saturating_arithmetic.hpp
- libtenzir/include/tenzir/detail/varbyte.hpp
- libtenzir/include/tenzir/word.hpp
Also, remove duplicates of C++20 concepts.
> Add concept::integer and concept::number

- libtenzir/builtins/operators/load_tcp.cpp
This resolves a set of TODOs from the newly added `load_tcp`.
> Improve `load_tcp`

- changelog/next/features/4527--precise-parsers.md
- web/docs/formats.md
- web/docs/formats/csv.md
- web/docs/formats/ssv.md
- web/docs/formats/tsv.md
This PR does a minor fixup for the precise parsers docs and changelog.
> Minor changes to the precise parser docs/changelog

- libtenzir/builtins/operators/serve.cpp
Now that diagnostics are shown in the Tenzir Platform, we no longer need to support this workaround for delivering at most one error-level diagnostic through `/serve` for the connected pipeline. This resolves an issue that caused some errors to be shown twice in the Tenzir Platform.
> Remove pipeline errors from `/serve`

- tenzir/tenzir.cpp
We often run into issues around the low default of maximum open file descriptors. On current Linux systems the soft limit is 1024, but processes can raise it up to a hard limit set by the kernel or parent process if it knows that it is safe to do so.
For our own code base we know that it is safe, so we can eliminate this stumbling block.
Technically we should reset it to 1024 or lower after forking of any sub processes, but this is not easily doable with boost process, so we refrain from that and consider non-supporting legacy software as unsupported for the `shell` operator.
> Raise max fd soft limit during initialization

- libtenzir/builtins/formats/json.cpp
- Implement `read_ndjson` as a dedicated operator
- Remove the `ndjson` and `gelf` options from `read_json`
- Fix a bug in arrays_of_objects, where ill-formed arrays were not properly handled
> Implement TQL2 `read_ndjson`

- libtenzir/src/version.cpp
- Work towards https://github.com/tenzir/issues/issues/2145
> Remove flags for stabilized features

- web/docs/overview.md
- web/versioned_docs/version-v4.22/overview.md
Looks like we had two broken links sneak in with the latest patch release.
> Fix docs CI on main

- changelog/next/features/4704--sort-records-and-fields.md
- libtenzir/builtins/operators/sort.cpp
This implements sorting on lists (by value) and records (by field name).
> Implement `<list>.sort()` and `<record>.sort()`

- changelog/next/bug-fixes/4715--serve-manager-race.md
- libtenzir/builtins/operators/import.cpp
- libtenzir/builtins/operators/serve.cpp
- libtenzir/src/active_partition.cpp
- libtenzir/src/evaluator.cpp
- libtenzir/src/index.cpp
- libtenzir/src/passive_partition.cpp
- libtenzir/src/pipeline_executor.cpp
- libtenzir/src/series_builder.cpp
These 3 commits are basically independent, but are all caused by the same incident.
Refer to the actual commit messages for motivation and explanation.
> Correctly handle duplicate serve requests and tune some logs

- web/docs/tql2/functions.md
- web/docs/tql2/functions/all.md
- web/docs/tql2/functions/any.md
- web/docs/tql2/functions/collect.md
- web/docs/tql2/functions/count.md
- web/docs/tql2/functions/count_distinct.md
- web/docs/tql2/functions/distinct.md
- web/docs/tql2/functions/first.md
- web/docs/tql2/functions/last.md
- web/docs/tql2/functions/max.md
- web/docs/tql2/functions/mean.md
- web/docs/tql2/functions/median.md
- web/docs/tql2/functions/min.md
- web/docs/tql2/functions/mode.md
- web/docs/tql2/functions/quantile.md
- web/docs/tql2/functions/stddev.md
- web/docs/tql2/functions/sum.md
- web/docs/tql2/functions/value_counts.md
- web/docs/tql2/functions/variance.md
- web/docs/tql2/operators/summarize.md
This PR continues the series of TQL2 docs.
> Just another docs PR

- changelog/next/features/4725--tql2-kafka.md
- libtenzir/include/tenzir/tql2/plugin.hpp
- plugins/kafka/CMakeLists.txt
- plugins/kafka/builtins/plugin.cpp
- plugins/kafka/include/kafka/operator.hpp
- plugins/kafka/src/plugin.cpp
- web/docs/tql2/operators.md
- web/docs/tql2/operators/load_kafka.md
- web/docs/tql2/operators/save_kafka.md
Adds `loader_adapter`, `writer_adapter` and `saver_adapter`.
Implements `load_kafka` and `save_kafka`.
> Port kafka connector to TQL2

- changelog/next/features/4736--unroll.md
- libtenzir/builtins/operators/unroll.cpp
- web/docs/tql2/operators.md
- web/docs/tql2/operators/unroll.md
- Fixes https://github.com/tenzir/issues/issues/2176
> Port `unroll` to TQL2

- web/docs/tql2/operators/package/add.md
- web/docs/tutorials/write-a-package.md
This PR does a few more cleanups in the docs.
> Correct a few more docs pieces

- changelog/next/bug-fixes/4746--context-inspect-crash.md
- changelog/next/changes/4741-4746--tql-modules.md
- libtenzir/builtins/operators/show.cpp
- libtenzir/src/tql2/tokens.cpp
- nix/tenzir/plugins/source.json
With the new support for modules in TQL2 it makes sense to rename these operators for TQL2.
> Introduce `{package,pipeline}::list`

- scripts/install.sh
> Disable gpg check on rpm packages

- changelog/next/features/4716--tql2-lps.md
- libtenzir/builtins/connectors/email.cpp
- libtenzir/builtins/connectors/udp.cpp
- libtenzir/builtins/operators/load_tcp.cpp
- web/docs/tql2/operators.md
- web/docs/tql2/operators/load_tcp.md
- web/docs/tql2/operators/load_udp.md
- web/docs/tql2/operators/save_email.md
- web/docs/tql2/operators/save_udp.md
Ports:
- `load_udp`
- `save_udp`
- `save_email`
> Port udp and email

- changelog/next/features/4795--record-indexing.md
- libtenzir/src/tql2/eval_impl.cpp
- tenzir/integration/data/reference/expression/test_record_indexing/step_00.ref
- tenzir/integration/tests/expression.bats
Implements indexing records with expressions.
> Implement `x[y]` record indexing

- changelog/next/features/4806--base64.md
- libtenzir/builtins/functions/base64.cpp
- web/docs/tql2/functions.md
- web/docs/tql2/functions/decode_base64.md
- web/docs/tql2/functions/encode_base64.md
Implements functions:
- `encode_base64(blob|string) -> string`
- `decode_base64(blob|string) -> blob`
Closes https://github.com/tenzir/issues/issues/2360
> Implement `encode_base64` and `decode_base64`

- libtenzir/builtins/commands/rebuild.cpp
- libtenzir/builtins/operators/buffer.cpp
- libtenzir/builtins/operators/cache.cpp
- libtenzir/builtins/operators/export.cpp
- libtenzir/builtins/operators/fields.cpp
- libtenzir/builtins/operators/schemas.cpp
- libtenzir/builtins/operators/serve.cpp
- libtenzir/include/tenzir/context.hpp
- libtenzir/src/connect_to_node.cpp
- libtenzir/src/index.cpp
- libtenzir/src/node.cpp
- libtenzir/src/spawn_node.cpp
- nix/tenzir/plugins/source.json
Another smaller prep PR for the CAF upgrade.
> Insert missing includes for caf/actor_registry

- changelog/next/features/4716-4807--tql2-lps.md
- libtenzir/builtins/connectors/tcp.cpp
- web/docs/tql2/operators.md
- web/docs/tql2/operators/load_tcp.md
- web/docs/tql2/operators/save_tcp.md
- Closes https://github.com/tenzir/issues/issues/2365
> Port `save_tcp`

- changelog/next/features/4835--local-remote-unordered.md
- libtenzir/builtins/operators/local_remote.cpp
- libtenzir/builtins/operators/unordered.cpp
- web/docs/tql2/operators.md
- web/docs/tql2/operators/local.md
- web/docs/tql2/operators/remote.md
- web/docs/tql2/operators/unordered.md
- Fixes https://github.com/tenzir/issues/issues/2337
> Port `unordered`, `local`, and `remote` to TQL2

- libtenzir/builtins/operators/cache.cpp
Trying to learn how to use the new tools from CAF on a small example.
> Modernize CAF usage in `cache.cpp`

- changelog/next/features/4871--opensearch.md
- libtenzir/builtins/operators/to_opensearch.cpp
- tenzir/integration/data/reference/from_to/test_to_failure/step_00.ref
- tenzir/integration/data/reference/opensearch/test_doc_param/step_00.ref
- tenzir/integration/data/reference/opensearch/test_doc_param/step_01.ref
- tenzir/integration/data/reference/opensearch/test_missing_id/step_00.ref
- tenzir/integration/data/reference/opensearch/test_missing_id/step_01.ref
- tenzir/integration/data/reference/opensearch/test_normal_case/step_00.ref
- tenzir/integration/tests/opensearch.bats
- web/docs/tql2/functions/otherwise.md
- web/docs/tql2/operators.md
- web/docs/tql2/operators/to.md
- web/docs/tql2/operators/to_opensearch.md
- Closes https://github.com/tenzir/issues/issues/2398
> Add `to_opensearch` and `to_elasticsearch` sink operators

- web/docs/integrations/snowflake/README.md
This PR makes minor integrations to the Snowflake integration page.
> Make minor improvements to Snowflake integration

- .github/workflows/nix-config-base.json
> Revert "Disable macOS Nix CI job"

- libtenzir/builtins/operators/where_map.cpp
The `operator_base::name()` function needs to return a constant when it is used with `operator_inspection_plugin`, since that plugin uses the name from the default-constructed operator.
> Fix serialization of `where` and `assert`

- Dockerfile
- scripts/install-demo-node-package.tql
Four blind eyes came together in https://github.com/tenzir/tenzir/pull/4909 and did not see that the pipeline that's already shown in the diff and discussed in the PR was forgotten to be ported to TQL2.
> Port demo node setup to TQL2

- changelog/next/changes/4886--configured-pipeline-errors.md
- libtenzir/include/tenzir/variant_traits.hpp
- libtenzir/src/node.cpp
- nix/tenzir/plugins/source.json
Errors from the startup of configured pipelines, including those coming from
configured packages, now have improved rendering.
You can review the three commits in the plugins repository individually.
> Improve configured pipeline startup errors

- changelog/next/features/4917--more-string-functions.md
- libtenzir/builtins/functions/string.cpp
- web/docs/tql2/functions.md
- web/docs/tql2/functions/match_regex.md
- web/docs/tql2/functions/replace.md
- web/docs/tql2/functions/replace_regex.md
- web/docs/tql2/operators/read_kv.md
This implements `string.match_regex( string )`
- Fixes https://github.com/tenzir/issues/issues/2421
> Implement `match_regex`

- web/docs/tql2/functions.md
- web/docs/tql2/functions/sort.md
This PR documents the `sort` function.
> Document the `sort` function

- nix/tenzir/default.nix
The way our deb/rmp/tarball packaging was set up caused a recompilation of all source files after the regular installation of the runtime files into the Nix store.
The reason for that is that we had to reconfigure the build tree to set the correct package installation directory for CPack, and CMake incorrectly detected the the object files needed a rebuild.
To work around that issue, we now simply invert the order and build the packages directly in the `buildPhase` and unpack the tarball into $out for the installation
> Avoid compiling twice in the static binary packaging

- web/docs/integrations/amazon/README.md
- web/docs/tutorials/map-data-to-ocsf/README.md
This PR udpates the OCSF mapping tutorial to our newly established conventions that simplify the process.
> Update OCSF mapping tutorial

- web/src/pages/discord.tsx
Fixes the broken Discord link in the docs by replacing it with a permanent one.
> Fix broken Discord link

- .gitattributes
Using the Dart highlighter, because that seems to yield the best results.
> Add syntax highlighting to TQL files on GitHub

- Dockerfile
- scripts/debian/install-dev-dependencies.sh
> Pin arrow-adbc to v16-1

- changelog/next/bug-fixes/4978--fix-lookup-shutdown.md
- nix/tenzir/plugins/source.json
Fixing a problem found with https://github.com/tenzir/tenzir/pull/4971.
> Fix shutdown of the lookup helper actor

- libtenzir/builtins/formats/json.cpp
- libtenzir/include/tenzir/pipeline.hpp
- libtenzir/include/tenzir/plugin.hpp
- libtenzir/include/tenzir/tql2/plugin.hpp
- libtenzir/src/exec_pipeline.cpp
- libtenzir/src/execution_node.cpp
- libtenzir/src/tql2/eval_impl.cpp
This adds an experimental parallelization scheme to our NDJSON parser.
> Parallelize JSON parser

- libtenzir/builtins/formats/json.cpp
This adds the experimental `_jobs` option that enables parallelization inside a single parser to `read_gelf`, `read_suricata` and `read_zeek_json`. No changelog, as this is an hidden, unstable option.
> Add experimental `_jobs` option to more JSON formats

- changelog/next/bug-fixes/5012--include-to_splunk-in-binary-packages.md
- nix/overlay.nix
> Add to_splunk to the ce binary packages

- web/versioned_docs/version-v4.29/integrations/microsoft/azure/log-analytics/README.md
> Update README.md: typo

- changelog/next/bug-fixes/5070--fluentbit.md
- libtenzir/src/ssl_options.cpp
- plugins/fluent-bit/bats/tests/tests.bats
- plugins/fluent-bit/builtins/plugin.cpp
- plugins/fluent-bit/include/fluent-bit/fluent-bit-minimal.h
- plugins/fluent-bit/include/fluent-bit/fluent-bit_operator.hpp
- web/docs/tql2/operators/from_fluent_bit.mdx
- web/docs/tql2/operators/to_fluent_bit.mdx
> Fix fluentbit engine stop logic and disable TLS default

- .github/workflows/documentation.yaml
- .github/workflows/sync-docs.yaml
This PR synchronizes specific files to the new docs repo when they change.
> Add new workflow to sync to docs repo

- .github/workflows/documentation.yaml
> Fix GH action event names

- nix/tenzir/plugins/source.json
Second take, as #5078 didn't quite cut it.
> Update submodule to main and sync sources

- changelog/next/features/5114--http.md
- libtenzir/builtins/operators/http.cpp
- web/docs/tql2/operators.md
- web/docs/tql2/operators/from_http.md
This makes the future transition for `load_http` to `from_http` as an HTTP client easier.
> Require `server=true` for `from_http`

- .github/workflows/style-check.yaml
> Add `set -eo pipefail` to our style check CI

- libtenzir/CMakeLists.txt
- nix/tenzir/default.nix
- tenzir/tenzir.cpp
- web/docs/development/build-from-source.md
* Fix stack trace symbol resolution in plugins by always depending on libbacktrace.
* Fix logging of errors during plugin initialization.
> A set of logic error fixes

- libtenzir/builtins/commands/rebuild.cpp
This has been there for two years and nobody noticed; likely because this shouldn't crash in release builds, where accessing a moved-from optional aggregate struct member is not reaching into invalid memory.
> Fix a use-after-move in rebuild

- changelog/next/features/5173--load-tcp-sender.md
- libtenzir/builtins/operators/load_tcp.cpp
- libtenzir/include/tenzir/tql2/eval.hpp
- libtenzir/src/tql2/eval.cpp
- web/docs/tql2/operators/load_tcp.mdx
- Fixes https://github.com/tenzir/issues/issues/2987
> Add option to `load_tcp` for storing sender information

- changelog/next/bug-fixes/5221--clickhouse-fixes.md
- plugins/clickhouse/include/clickhouse/easy_client.hpp
- plugins/clickhouse/src/easy_client.cpp
- plugins/clickhouse/src/transformers.cpp
- web/docs/development/build-from-source.md
Fixes:
- https://github.com/tenzir/issues/issues/2992
> Fix a crash in `to_clickhouse` and bump `clickhouse-cpp`

- docs/operators/context/create_bloom_filter.md
- docs/operators/context/create_geoip.md
- docs/operators/context/create_lookup_table.md
- docs/operators/context/enrich.md
- docs/operators/context/erase.md
- docs/operators/context/inspect.md
- docs/operators/context/list.md
- docs/operators/context/load.md
- docs/operators/context/remove.md
- docs/operators/context/reset.md
- docs/operators/context/save.md
- docs/operators/context/update.md
- docs/operators/package/add.md
- docs/operators/package/list.md
- docs/operators/package/remove.md
- docs/operators/pipeline/activity.md
- docs/operators/pipeline/detach.md
- docs/operators/pipeline/list.md
- docs/operators/pipeline/run.md
This removes an ambiguity on the new docs page.
> Fully qualify reference card titles

- .github/workflows/release.yaml
The release workflow now updates version.json and includes it in the release commit along with the changelog file.
> Update version tracking in automated release process

- changelog/changes/N23ZJjVv48R5azO6raLuy84W2R.md
- changelog/changes/eGgfXqif4r6DXyByEGUjDkEsEl.md
- docs/functions/count_if.md
- docs/functions/map.md
- docs/functions/where.md
- docs/operators/from_http.md
- docs/operators/http.md
- libtenzir/builtins/connectors/curl.cpp
- libtenzir/builtins/formats/json.cpp
- libtenzir/builtins/formats/xsv.cpp
- libtenzir/builtins/formats/yaml.cpp
- libtenzir/builtins/operators/http.cpp
- libtenzir/include/tenzir/tql2/plugin.hpp
- libtenzir/src/json_parser.cpp
- libtenzir/src/plugin.cpp
- libtenzir/src/tql2/eval.cpp
- nix/caf/source.json
- plugins/parquet/builtins/plugin.cpp
- tenzir/bats/data/reference/from_to/test_from_deduction/step_05.ref
- tenzir/bats/data/reference/from_to/test_from_deduction/step_06.ref
- tenzir/bats/data/reference/from_to/test_from_failure/step_01.ref
- tenzir/bats/data/reference/from_to/test_from_failure/step_02.ref
- tenzir/bats/data/reference/http2/test_load_http_post/step_01.ref
- tenzir/bats/data/reference/http2/test_load_http_post_form/step_01.ref
- tenzir/bats/data/reference/http2/test_save_http_post/step_00.ref
- tenzir/bats/data/reference/http2/test_save_http_post_add_header/step_00.ref
- tenzir/bats/data/reference/http2/test_save_http_post_delete_header/step_00.ref
- tenzir/bats/data/reference/http2/test_save_http_post_overwrite_header/step_00.ref
- tenzir/bats/data/reference/http2/test_save_http_put/step_00.ref
- tenzir/bats/tests/http2.bats
- Closes https://github.com/tenzir/issues/issues/2596
> Implement `from_http` client

- changelog/changes/z1xXTT6R4joEKebXONYzNebbxb.md
- docs/functions/parse_cef.mdx
- docs/functions/parse_leef.mdx
- docs/functions/print_cef.md
- docs/functions/print_leef.md
- docs/operators/read_cef.mdx
- docs/operators/read_leef.mdx
- libtenzir/builtins/formats/cef.cpp
- libtenzir/builtins/formats/leef.cpp
- libtenzir/include/tenzir/series.hpp
- libtenzir/include/tenzir/view3.hpp
- libtenzir/src/series.cpp
- tenzir/tests/exec/functions/print/print_cef.tql
- tenzir/tests/exec/functions/print/print_cef.txt
- tenzir/tests/exec/functions/print/print_leef.tql
- tenzir/tests/exec/functions/print/print_leef.txt
This PR implements `print_leef` and `print_cef`.
- Closes https://github.com/tenzir/issues/issues/2937
> Implement `print_leef` & `print_cef`

- docs/functions/random.md
- docs/functions/uuid.md
This PR fixes broken docs links.
Closes tenzir/issues#3152.
> Fix `uuid` docs

- changelog/changes/talked-editor-horse.md
- libtenzir/builtins/operators/http.cpp
- scripts/clang-format-diff.py
This PR fixes a bug in the pagination of the `http` operator.
> Fix bug in `http` operator pagination

- libtenzir/builtins/operators/cache.cpp
- tenzir.yaml.example
> Improve warning and example config comment

- libtenzir/builtins/operators/http.cpp
This fixes a logic bug introduced in https://github.com/tenzir/tenzir/pull/5343, which checked for `chunk_ptr` after already adding the internal source. No changelog because it wasn't included in a release yet. This PR here also fixes a use-after-free, which I was exposed by this.
> Fix subpipeline handling in `from_http`

- .github/workflows/tenzir.yaml
This should make the `configure` CI job faster.
> Attempt to make CI a bit faster

- changelog/changes/sequel-larger-double.md
This PR fixes the titles in a changelog entry that mess things up.
> Fix changelog titles

- nix/caf/source.json
- nix/update-impl.sh
- nix/update.sh
- tenzir/tenzir.cpp
Setting it directly when creating the actor system prevents a rare data race.
> Set custom actor clock through `actor_system_config`

- libtenzir/builtins/functions/string.cpp
We are currently having a hard to reproduce bug. Hopefully, this reveals the exact location where things go wrong.
> Temporarily add additional assertions for `to_lower`

- .claude/agents/integration-tester.md
- .claude/commands/tenzir-figure-out-build-command.md
- .claude/commands/tenzir-implement-task-agentic.md
- .claude/commands/tenzir-implement-task-manual.md
- .claude/commands/tenzir-setup-build.md
- .claude/commands/tenzir-with-integration-test-context.md
- .claude/contexts/build-system.md
- .claude/contexts/cpp-writing.md
- .claude/contexts/integration-tests.md
- .gitignore
- AGENTS.md
> Hackathon: Claude.md experimentation
