libvast/src/msgpack_table_slice.cpp
Before the modification GCC10 would fail to compile this code with:
```
msgpack_table_slice.cpp:193:41: error: no matching function for call to
‘std::optional<unsigned char>::operator*(std::optional<unsigned char>*)’
193 |       return make_data_view(enumeration{*x});
```
Not creating the temporary fixes the problem.
=> Work around an optional deref bug in GCC10

libvast/vast/expression.hpp
Problem:
- The implementation for transforming a `conjunction` or `disjunction`
into a `result_type` is nearly identical.
Solution:
- Factor out the implementation into a common function template
parameterized on the input type to not repeat ourselves in the
implementation.
File-by-file.
=> expression: DRY with predicate_transformer

cmake/VASTRegisterPlugin.cmake, libvast/test/CMakeLists.txt
This sets the same timeout for plugin unit tests that we also use for VAST's unit tests, with the exception that the timeout is for all test suites defined in the plugin instead of for each test suite.
Additionally, this raises the unit test verbosity to the highest available level so we get better output on failure in CI.
File-by-file.
=> Set a 1 minute timeout for plugin unit tests

libvast/src/system/index.cpp, libvast/src/system/partition.cpp, libvast_test/src/main.cpp
With the introduction of spdlog logging, we finally have an easy way to get log output from unit tests without having to fight caf internals.
Note that this is purely a developer-facing feature, so any missing follow-ups (write to file, log format settings, etc.) can be implemented by the affected party as needed.
=> Add command-line option for VAST log output from unit tests

libvast/src/system/count_command.cpp, libvast/src/system/explore_command.cpp, libvast/src/system/get_command.cpp, libvast/src/system/import_command.cpp, libvast/src/system/pivot_command.cpp, libvast/src/system/remote_command.cpp, libvast/src/system/sink_command.cpp, libvast/src/system/spawn_or_connect_to_node.cpp, libvast/vast/system/spawn_or_connect_to_node.hpp
Problem:
- System commands use `caf::variant` whose functionality exists in the
standard library. Moreover, `caf::variant` may be deprecated in the
future.
Solution:
- Replace uses of `caf::variant` with `std::variant`. Similarly, use
`std::get_if` instead of `caf::get_if`.
File-by-file.
=> system: caf::variant -> std::variant

libvast_test/src/main.cpp
This introduces a custom log format for unit tests:
* Timestamps are usually not relevant, since they're either "right now" when tests are run locally or the time of the CI run when run remotely
* File and line number are important to jump quickly to the source of some unexpected log message
* Color is important to be able to add visually distinctive messages while debugging
=> Change default format for unit test logs

libvast/vast/concept/hashable/hash_append.hpp
Problem:
- `hash_append` for tuples delegates to a helper function for hashing
each item in a tuple.
Solution:
- Use fold expressions directly to hash each item in a tuple rather than
delegating to extra helper functions.
File-by-file.
=> Simplify hash_append for tuples

vast/integration/vast_integration_suite.yaml
The timeout of 0s is used to check for the error result, not for the empty result set. We cannot reliably make a 0 second timeout return 0 events, since that is inherently racy. The fix is to just not print any events by using the `null` export format.
It's a simple change. The commit message contains reasoning.
=> Fix the export timeout integration tests

.github/workflows/vast.yaml, cmake/VASTRegisterPlugin.cmake, configure, examples/plugins/transform/CMakeLists.txt, examples/plugins/transform/tests/transform_plugin.cpp, examples/plugins/transform/transform_plugin.cpp
The example transform plugin did not compile, and it was also not tested in CI or exposed via `configure`. This commit makes the necessary changes.
File-by-file.
=> Fix the example transform plugin

libvast/test/bloom_filter.cpp, libvast/vast/bloom_filter.hpp
This PR adds a new *tracking policy* to the Bloom filter, making it possible to
find out whether an addition resulted in a no-op (in case of a duplicate or
collision) or did turn at least one bit to 1.
In one shot.
=> Enable duplicate tracking in Bloom filters

libvast/test/detail/type_traits.cpp, libvast/vast/bitmap.hpp, libvast/vast/component_config.hpp, libvast/vast/detail/type_traits.hpp, libvast/vast/expression.hpp, libvast/vast/type.hpp
Problem:
- `caf::detail::tl_contains` only works with `caf::type_list` types,
which doesn't lend itself well to future refactorings.
- `caf::detail::tl_contains` is slow since it is defined in terms of
recursive class templates.
Solution:
- Use `vast::detail::contains_type_v` which works on any class template
holder rather than just `caf::type_list`.
- Compilation times improve as well due to use of fold expressions
rather than recursive class templates.
=> Decouple type contains trait from caf::detail::type_list

changelog/unreleased/bug-fixes/1659.md, libvast/test/segment_store.cpp, libvast/vast/detail/pp.hpp, libvast_test/vast/test/fixtures/filesystem.hpp
Before this change, the filesystem unit test fixture used a fixed `vast-unit-test` root directory. Now, we use `vast-unit-test/<suite>` instead to avoid races when running tests in parallel, e.g., via `ctest -j12 -C Debug`.
Test locally via
```bash
ctest --test-dir <path/to/build> -j12 -C Debug
```
=> Allow for running unit tests in parallel

libvast/test/view.cpp, libvast/vast/data.hpp, libvast/vast/detail/type_traits.hpp, libvast/vast/index/hash_index.hpp, libvast/vast/view.hpp
This moves code to where it should've been from the get-go. Needs this in a plugin to avoid code duplication.
File-by-file.
=> Opt-in to transparent lookup for data and data_view

.github/workflows/vast.yaml
We currently have no user for this build, and are already testing Clang via both AppleClang and the latest clang. For GCC we test GCC-8 explicitly on Debian, and latest via the Nix build. That already covers the range we want to support, so this is superfluous.
n/t
=> Remove Debian Clang-10 build from VAST CI

libvast/test/table_slice.cpp, libvast/vast/table_slice.hpp
Before this change, we deserialized the table slice's offset and then copied the table slice, resulting in the offset being reset to `invalid_id`. This caused no issues in practice until now, because no current code uses offsets after sending table slices over the wire. This did, however, just cause a very frustrating debugging session because I relied on this to work for a plugin.
The change should be obvious.
=> Fix table slice offset deserialization

cmake/VASTChangelog.cmake.in, scripts/create-release
Changelog entries may now contain an additional note separated with `--` in their title. This makes it easy to find entries in the unreleased section when appending to older changelog entries. We strip the note suffix in the `create-release` script.
The new title format is:
```
<pull-request|@author>[-...][--note].md
```
I tried this locally with a modified version if the create-release script. The code should be simple enough to follow.
=> Allow for adding a note to changelog entries

changelog/unreleased/features/1655--disk_monitor_step_size.md, libvast/src/system/application.cpp, libvast/src/system/disk_monitor.cpp, libvast/src/system/spawn_disk_monitor.cpp, libvast/vast/defaults.hpp, libvast/vast/system/disk_monitor.hpp, vast.yaml.example
Add a "step size" setting to the disk monitor to only trigger re-checking of the disk size after deleting N partitions. Useful for situations where computing the disk size is computationally expensive, e.g. on compressed filesystems.
=> Add step size to disk monitor

.github/workflows/vast.yaml, Dockerfile
`--test-dir` is too recent for Debian Buster.
Verify that tests now actually run in CI, instead of CTest silently saying "no tests found".
=> Work around outdated CTest in Debian Buster

.github/workflows/vast.yaml
The regular cache action has one shortfall that is often complained about: Caches are not re-uploaded when there's a cache hit, which works against Ccache. With this change, we let Ccache itself control the size of the cache and always upload it, thus letting us rotate cached object files in CI more efficiently.
Verify that CI now re-uploads caches on hits.
=> Improve CI cache usage by re-uploading on cache hits

.clang-tidy
Apparently clang-tidy 12 requires the trailing comma here.
@lava check locally if this fixes it on your end as well.
=> Properly disable uppercase literal suffix check

.github/workflows/vast.yaml
Noticed we ran this step both earlier and more often than we should've. Considering it takes around 20 seconds, this really makes a difference.
See CI run.
=> Login to GCS in CI only if necessary

changelog/unreleased/bug-fixes/1679--plugin-load-order.md, vast/CMakeLists.txt, vast/vast.cpp
This ensures the version comparison is agnostic to the order of the plugins.
Connect a local VAST to a VAST running the same plugins specified in a different order and notice VAST no longer warns unnecessarily.
=> Sort loaded plugins by name

cmake/VASTMacDependencyPaths.cmake, libvast/CMakeLists.txt
This marks some options as advanced that should've been marked as such upstream, which reduces the noise when looking at the ccmake interface.
Run locally, see if any obscure options are still in.
=> Clean up ccmake interface

CMakeLists.txt, scripts/clang-build-analyzer
Before this change, the `-DVAST_ENABLE_TIME_TRACE` CMake option was silently ignored when the current compiler was not set to `clang`.  On many machines, this led to the paradoxical situation where the `clang-build-analyzer` script by default runs a full build using no `clang` and no build analysis.
Instead, we now default the `CC` and `CXX` to `clang` and `clang++` respectively to still respect custom compilers and compiler wrappers, and check in our CMake code whether the current compiler supports the `-ftime-trace` flag rather than only enabling it when the compiler ID matches `clang`.
Try locally. Requested @lava for review since he noticed this in the first place.
I do not think this is worth a changelog entry since it does not affect VAST itself.
=> Use clang by default in clang-build-analyzer script

.github/workflows/vast.yaml
A recent change to always upload the cache overlooked that the caches were still uploaded with separate names, which is not ideal. We want to have one cache per build configuration and let `ccache` take care of the rest.
Reason about the change.
=> Improve caching behavior in CI

plugins/pcap/main.cpp
Unlike the drop warning, the discard should really only be a debug message.
Per discussion in Slack.
=> Silence overly noisy PCAP warning

.github/workflows/vast.yaml
This should fix the error
`Internal Error: Calculate hash value for sources in github repo tenzir/vast.`
that we sometimes get because of autogenerated merge commits that can't be fetched.
=> Use the local copy of the sources for the static CI build

changelog/unreleased/bug-fixes/1685--partition-synopsis-nil-segfault.md, libvast/src/partition_synopsis.cpp, libvast/test/bloom_filter_synopsis.cpp, libvast/vast/bloom_filter_synopsis.hpp
The meta index lookup would select type synopses based on the field name being looked up, without verifying that the right hand side of the query also has the corresponding type. This leads to undefined behavior for queries like `s == nil` or `s == 123` (where `s` is a string field) and depending on the compiler settings also segfaults or other kinds of bad behavior.
NOTE: I'm not completely sure if the same issue exists for "normal" synopsis and we just don't notice it because the invalid call to `caf::get<view<T>>()` was not using complex types like `std::string`, or if these were typechecked somewhere else beforehand.
=> Handle arbitrary types in bloom filter synopsis

.github/workflows/style-check.yaml
Before this change, the check only ran for `*.cmake` files, but not for `CMakeLists.txt` file because the latter were misspelled in the CI job definition.
n/t
=> Fix CMake Style Check

README.md, changelog/unreleased/changes/1696--slack-community-chat.md
This PR adapts the README to reflect our move from Gitter to Slack for our community chat.
In one scoop.
=> Change chat from Gitter to Slack

.github/workflows/vast.yaml, CMakeLists.txt, changelog/unreleased/bug-fixes/1697--plugins-build-shared-libs.md, cmake/VASTRegisterPlugin.cmake, examples/plugins/analyzer/CMakeLists.txt, examples/plugins/transform/CMakeLists.txt, libvast/CMakeLists.txt, libvast/test/vector_map.cpp, libvast/vast/plugin.hpp, plugins/pcap/CMakeLists.txt, scripts/clang-build-analyzer, tools/lsvast/CMakeLists.txt, vast/CMakeLists.txt
These commits don't have much to do with each other, but these are four things that I have noticed recently, none of which are changelog-worthy.
=> Fix a bunch of smaller issues

libvast/src/logger.cpp
Let's catch exceptions that occur during the spdlog setup and exit nicely with a proper error message.
Try locally, e.g., `vast --log-file=/private/server.log start` (or whatever directory has missing perms on your machine).
=> Handle spdlog exceptions gracefully

changelog/unreleased/features/1699--post-start-commands.md, libvast/src/system/application.cpp, libvast/src/system/start_command.cpp, vast.yaml.example
The new option `vast.start.commands` allows for specifying an ordered list of VAST commands that run inside the node after successful startup. This is useful for declarative deployments that run sources or matchers (via the proprietary Live Matching plugin) in the node.
Try locally. This can hardly be tested, sadly, since we do not have unit tests for the start command and cannot reliably test remote sources in the integration test framework. I played around with the following:
```yaml
vast:
start:
hooks:
- spawn source pcap -i en0
- spawn source netflow -i :4739/udp
- matcher start --match-types=address ips
```
=> Add option for configurable post-start hooks

Dockerfile, changelog/unreleased/changes/1705--pcap-plugin-docker.md
Before this change it was impossible to build the PCAP plugin inside the Docker image. Docker does not resolve symlinks when copying, not even those that are internal to the repository.
See if CI runs through, basically. Also, read the changed Dockerfile.
=> Fixup repository-internal symlinks in Dockerfile

changelog/unreleased/bug-fixes/1709--log-rotation-threshold.md, libvast/src/logger.cpp
As noticed by @tobim, the option was unaccounted for. I took the opportunity to improve some log messages as well.
=> Fix log rotation threshold option

changelog/unreleased/bug-fixes/1702--reconnect-uds-dgram-metrics.md, libvast/src/detail/posix.cpp, libvast/src/system/accountant.cpp, libvast/src/system/node.cpp, libvast/vast/accountant/config.hpp, libvast/vast/detail/posix.hpp
The previous way of setting up the UDS datagram metrics relied on a fake connection that made it possible to use the iostream abstraction. However this fake connection would get destroyed if the listening end deleted it's socket.
This commit introduces a wrapper around sockaddr_un and the client fd and uses sendto instead of write.
Code review by file.
Test by running VAST with
```
vast:
enable-metrics: true
metrics:
uds-sink:
enable: true
path: "/tmp/vast-metrics.sock"
type: "datagram"
```
And run and restart `socat UNIX-RECV:/tmp/vast-metrics.sock ` while the VAST node is running.
=> Make unix dgram metrics sink connectionless

.github/workflows/vast.yaml, changelog/unreleased/bug-fixes/1711--remove-dead-condition-and-fix-docker-release-tags.md
We had a dead condition in the CI code that was hit due to our workflow triggers. Our Docker images for release builds subsequently ended up with a wrong tag.
File-by-file.
=> Remove dead condition and fix Docker release tags

libvast/src/system/make_source.cpp, libvast/vast/system/make_source.hpp
Requiring the IMPORTER actor is needlessly strict here. This change allows for using `make_source` in plugins with a custom stream sink.
n/t
=> Relax requirements for stream sink in make_source

changelog/unreleased/bug-fixes/1712--quoted-strings-csv-parser.md, libvast/src/format/csv.cpp, libvast/test/format/csv.cpp
This change makes it possible to import CSV data containing quoted strings that contain the configured separator. This works for both header and fields.
Read code diff. Check provided unit tests.
=> Handle quoted strings in CSV parser

changelog/unreleased/features/1714--vast-endpoint-from-environment.md, libvast/src/system/configuration.cpp
This PR adds the ability to configure VAST's endpoint using an environment variable.
`commit-by-commit`
=> Optionally read environment variable for VAST endpoint

libvast/src/plugin.cpp, libvast/src/system/configuration.cpp
The contents of the install dir should be considered as vendored. In case of relocatable installations that means the path will not contain unintentional plugins. In case of non-relocatable we don't support running VAST from any place that is not the install location.
We should also look for plugins in the install plugindir last, after the locations set in the runtime configurations.
No changelog entry because `--bare-mode` is an undocumented development feature in the first place.
=> Still consider install plugindir in bare mode

libvast/src/system/configuration.cpp
This fixes a very subtle bug just recently introduced. If both `vast.plugin-dirs` from the command-line and `VAST_PLUGIN_DIRS` from env are empty, we must not put an empty `vast.plugin-dirs` into the option set, as this will override specified `vast.plugin-dirs` from any configuration file.
Read the commit message. The code change is really simple.
=> Avoid setting vast.plugin-dirs from empty env

.cmake-format, cmake/VASTRegisterPlugin.cmake, libvast/CMakeLists.txt
This change serves two purposes:
- Plugins can easily compile FlatBuffers schemas to use for their persistent state.
- VAST's own FlatBuffers files are abstracted behind a separate `libvast-fbs` target and not part of the main `libvast` library any more.
Read the code. Run locally. Build a plugin against an installed VAST with this change.
The compilation logic is the same. I was tempted to require a more current version of flatc because of all the new features, but let's do that in another PR.
=> Add utility for for compiling FlatBuffers schemas

changelog/unreleased/bug-fixes/1718--source-shutdown-hang.md, libvast/src/system/datagram_source.cpp, libvast/src/system/source.cpp
The new TRANSFORMER actor that always resides in the import process must be shut down when the SOURCE shuts down, as the SOURCE is the sole owner of the TRANSFORMER. Before this change, the DATAGRAM SOURCE shut down the stream of the TRANSFORMER, which caused it to quit somehow, but the SOURCE didn't propagate the shutdown to the TRANSFORMER at all, causing the import process to hang until a repeated SIGTERM/SIGINT led to a hard kill.
Try locally.
=> Fix shutdown hang in sources on SIGTERM/SIGINT

libvast/CMakeLists.txt, libvast/src/detail/backtrace.cpp, libvast/vast/config.hpp.in
This fixes setups where `FindBacktrace.cmake` provided `libexecinfo` rather than `libbacktrace`, but both `backtrace.h` and `execinfo.h` are available.
@lava please check locally if this fixes your issue.
=> Fix libexecinfo fallback for VAST_ENABLE_BACKTRACE

.github/workflows/vast.yaml, libvast/src/plugin.cpp
The bare-mode, which we use for integration tests to avoid side-effects from global configuration files, disabled the addition of `vast.plugin-dirs` to the plugin search paths. However, after recent changes that list also contained the options from both the command line and the environment variable, which were then ignored with bare-mode enabled.
Since we do not read configuration files that were not explicitly specified in bare-mode, it is safe to just read the option `vast.plugin-dirs` even with bare-mode enabled.
Read the description and the diff. This does not need a changelog entry since we just introduced this bug last week. I changed the CI for the example plugins to catch regressions on this and added a comment on the changed order.
=> Fix integration tests for external plugins

changelog/unreleased/changes/1721--merge-config-lists.md, libvast/src/command.cpp, libvast/src/data.cpp, libvast/src/detail/process.cpp, libvast/src/detail/settings.cpp, libvast/src/system/configuration.cpp, libvast/src/system/index.cpp, libvast/src/system/node.cpp, libvast/src/system/partition.cpp, libvast/src/system/start_command.cpp, libvast/test/data.cpp, libvast/vast/data.hpp, libvast/vast/detail/settings.hpp, libvast/vast/policy/merge_lists.hpp, vast/vast.cpp
Before this change, we merged configuration from different sources in a way that instead of merging nested lists, we overwrote them—leading to plugins specified in a configuration file not to load at all when plugins were specified on the command line as well. Now, we merge the lists in order of precedence.
File-by-file. Test locally.
Note that changelog entry + docs are yet to be written because I'd like to discuss this first with @tenzir/backend.
=> Merge lists from configuration and CLI

changelog/unreleased/features/1724--per-plugin-config-files.md, libvast/src/plugin.cpp, libvast/src/system/configuration.cpp, libvast/vast/system/configuration.hpp
This change adds per-plugin configuration files. The following two configurations are equivalent:
```yaml
plugins:
example-analyzer:
answer: 42
```
```yaml
answer: 42
```
This allows for unified deployments of plugins and their respective configuration. Plugin configuration no longer sneaks into the main deployments VAST configuration, and uninstalling a plugin no longer requires touching the main configuration file.
Run locally. Read code file-by-file.
This needs to be rebased after #1724 to make use of the new merge functions.
=> Add support for per-plugin configuration files

libvast/src/system/application.cpp, libvast/vast/system/application.hpp
A simple refactoring enabling creating of custom import commands in command plugins.
This only moves code out of an anonymous namespace and adds a declaration to the header. Just read the code and wait for CI to run through.
=> Expose make_import_command to plugins

cmake/VASTRegisterPlugin.cmake, libvast/CMakeLists.txt, vast/integration/integration.py
This PR fixes two bugs:
1. **Fix dependency graph for VASTTargets exports set**
For the Unix Makefiles generator, our CMake code generated a false install-time dependency for the VASTTargets export set, causing the installation of libvast-fbs to trigger a rebuild of all other targets in the VASTTargets set. This did not occur for other generators like Ninja. The effects could be seen for example in the static binary CI workflow, which compiled everything in the VASTTargets export set twice.
Installing the generated FlatBuffers interface library in the same export set fixes the issue. To make that work, the CMake 3.15+ property PUBLIC_HEADER must be manually filled with the generated headers, as adding sources to an interface library is a CMake 3.19+ feature.
I verified manually that this …
=> Fix dependency graph for VASTTargets exports set

.github/workflows/vast.yaml
This fixes a race condition in our CI that caused the past release not to have static binary artifacts attached. For now, I have attached the artifacts manually, so no third release-candidate will be necessary.
Read the changed logic carefully.
=> Fix race condition in release uploads

cmake/VASTRegisterPlugin.cmake
Before this change, plugin schemas and taxonomies were only installed with the build target `all`. Since plugins that bundle schemas usually depend on them, building the plugin should always bundle the schemas.
Run locally with the PCAP plugin. On master, notice that just running `cmake --build build --target pcap` does not install the bundled concept definitions, while running `cmake --build build --target all` does. This PR fixes that.
=> Bundle plugin schemas with the plugin build target

CMakeLists.txt
Without this change, running the `clean` target after running the `update-changelog` target causes the `CHANGELOG.md` file in the source directory to be removed, which is most certainly undesired.
Reading the code should suffice here, the change is really simple.
=> Fix byproduct listing for update-changelog target

default.nix, libvast/test/parseable.cpp, libvast/vast/system/disk_monitor.hpp, libvast_test/vast/test/test.hpp, nix/caf/source.json, nix/default.nix, nix/overlay.nix, nix/pinned.nix, nix/update.sh, nix/vast/default.nix, shell.nix
This updates nixpkgs to db6e089 so we can start using GCC 11 for our static binary build. I had to integrate some fixes in the CAF submodule for that too.
Download the static binary artifacts and verify that they pass the integration tests.
=> Bump nixpkgs and CAF to switch to GCC11 and clang12

changelog/unreleased/bug-fixes/1756--sort-plugins-by-name.md, libvast/src/plugin.cpp
The code that intended to sort plugins by name sorted by the in-memory location of the plugin names instead, which did not give consistent results. This caused a warning to sometimes be printed erroneously when connecting to a VAST server.
The code change is rather simple. If you want to run locally, just build with multiple plugins and verify that the plugins section in `vast status` is now always sorted.
=> Fix sorting of plugins by name

libvast/src/system/local_segment_store.cpp
Noticed this one when playing around with `vast.store-backend` set to `segment-store`.
:shrug:
=> Move dev-facing log message to debug logs

changelog/unreleased/bug-fixes/1754--log-startup-error-message.md, libvast/src/systemd.cpp
Don't use `VAST_WARN()` while initializing the logger, which leads to a nasty-looking error message.
Also, fix a parser bug in the journald detection routine that would cause us to always mistakenly return "false".
=> Fix error message about /dev/null-backend on startup

changelog/unreleased/bug-fixes/1759--json-import-abort.md, libvast/vast/format/json.hpp
=> Dont abort JSON import when encountering non-objects

changelog/unreleased/bug-fixes/1755--bitmap-index-offset.md, changelog/unreleased/features/1755--lsvast-indexers.md, libvast/src/system/index.cpp, libvast/test/bitmap_algorithms.cpp, libvast/vast/bitmap_algorithms.hpp, libvast/vast/index/hash_index.hpp, tools/lsvast/lsvast.cpp, vast/integration/lsvast_integration_suite.yaml
=> Fix bug in bitmap offset computation

changelog/unreleased/bug-fixes/1740--load-openssl-module.md, libvast/src/system/configuration.cpp, libvast/src/system/connect_to_node.cpp, libvast/src/system/start_command.cpp
Before this change, we never loaded the OpenSSL module despite checking whether any configuration option for using CAF's built-in OpenSSL module are set. This led to an uncaught runtime_error exception when trying to use the (undocumented) options.
For testing, I used the following:
```bash
vast --caf.openssl.certificate=cert.pem --caf.openssl.key=key.pem start
vast --caf.openssl.certificate=cert.pem --caf.openssl.key=key.pem status
```
Run locally. I don't think we should merge this before the release—it's been broken for months and nobody noticed it, so we should not need to rush this in.
=> Fix loading of the optional OpenSSL module

.dockerignore, .github/workflows/vast.yaml, Dockerfile, changelog/unreleased/changes/1765--drop-debian-buster-support.md
With this change, we drop support for Debian Buster and move up to requiring at least Debian Bullseye. We recommend users that require Debian Buster support to use the provided static Nix builds instead.
n/t
=> Bump minimum Debian requirement to Bullseye

.github/workflows/vast.yaml, Dockerfile
This is an earlier stage of the vast-dev Docker image that contains all the build dependencies and the VAST source tree, but no build of VAST itself.
Wait for CI :)
=> Publish a vast-deps Docker image

libvast/src/system/configuration.cpp
Loading an empty config file should not fail with an unintelligable error, but rather function as if the config file did not exist.
I don't think this needs a changelog entry. Test locally.
=> Skip empty config files

CMakeLists.txt, changelog/unreleased/features/1773--docker-arm64.md, cmake/FindSSE.cmake, libvast/vast/detail/base64.hpp, libvast/vast/detail/discard.hpp
- `FindSSE.cmake` module that checks for availability of various SSE-related compiler flags.
- Bug fixes in `base64.hpp` to account for the difference between char and signed char on some platforms, e.g., arm64.
- Use GCC-8 specific version of `VAST_DISCARD_ARGS` for all GCC versions; the same issues occured for GCC-10.
Reason about the changes I've made. Read the code changes carefully.
=> Fix Docker image builds for arm64

libvast/src/system/partition.cpp
This was falsely set to 1/15 the original timeout rather than the 3/5 it was intended to be set to.
It's a single character change, so whatever. No changelog entry needed, this was introduced just last week.
=> Fix the indexer status timeout

changelog/unreleased/bug-fixes/1771--dummy-transformer-sink.md, libvast/src/system/datagram_source.cpp, libvast/src/system/importer.cpp, libvast/src/system/source.cpp, libvast/src/system/transformer.cpp, libvast/test/system/importer.cpp, libvast/vast/system/actors.hpp, libvast/vast/system/transformer.hpp
This changes the source actor not to do busy work in the processing stage of its stream source so it stays responsive.
Give it a spin locally with various configurations
=> Make the source shutdown instantaneous

.github/workflows/vast.yaml, CMakeLists.txt, Dockerfile, changelog/unreleased/changes/1778--disabled-auto-vectorization-docker.md
The following new build options exist:
- `VAST_ENABLE_AUTO_VECTORIZATION` enables/disables all auto-vectorization flags.
- `VAST_ENABLE_SSE_INSTRUCTIONS` enables `-msse`; similar options exist for SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, AVX, and AVX2.
The CI now builds the Docker images hosted on Dockerhub with auto-vectorization disabled. This increases the portability of our hosted Docker images. Users building locally will still have flags enabled that their respective device supports.
- @tenzir/backend read the CMake code carefully
- @rolandpeelen see if this fixes the issue with AVX2 instructions on your end
=> Disable auto-vectorization in prebuilt Docker images

.github/workflows/style-check.yaml, CMakeLists.txt, changelog/unreleased/bug-fixes/1777--nix-etcdir.md, changelog/unreleased/features/1777--example-config.md, libvast/src/system/configuration.cpp, nix/vast/default.nix, vast.yaml.example, vast/CMakeLists.txt
This PR contains two changes:
- Our static binaries behaved differently than our regular relocatable installations: They were looking for the global configuration in `/etc/vast/vast.yaml` rather than the expected `<prefix>/etc/vast/vast.yaml`. This change makes them behave just like regular relocatable installations.
For users, this means that configuration files at `/etc/vast/vast.yaml` need to be moved accordingly.
- We now install an example config file alongside VAST.
Read the code, try the static binary from CI.
=> Remove /etc as hardcoded sysconfdir from Nix build 

CMakeLists.txt
Problem:
- When setting the default build type, there is a duplicate `if` check.
Solution:
- Remove the duplicate `if` check.
File-by-file.
=> Remove duplicate branch in CMakeLists.txt

Dockerfile
This shaves an additional ~10 MB off the resulting Docker images' size.
```
$ docker images
```
|REPOSITORY|TAG|IMAGE ID|CREATED|SIZE|
|-|-|-|-|-|
|vast-topic/strip-install-docker|latest|d89c14eb2291|5 seconds ago|162MB|
|vast-master|latest|40057e003de4|6 minutes ago|171MB
Decide whether or not we want this.
=> Strip installations in Dockerfile

Dockerfile
We recently changed VAST to install an example configuration file to `<sysconfdir>/vast/vast.yaml`, which overwrote the `systemd/vast.yaml` configuration file that we use inside the Dockerfile. This changes it so we install the custom configuration file after VAST.
Run `docker run vast version` and check if all plugins are loaded.
=> Install vast.yaml in Dockerfile later

libvast/test/detail/concepts.cpp, libvast/vast/detail/concepts.hpp, libvast/vast/detail/type_traits.hpp, libvast/vast/index/hash_index.hpp
Problem:
- `has_is_transparent` type trait is a bit of boilerplate using
`std::void_t` which is not needed as of C++20.
Solution:
- Add `transparent` concept and write it using `requires` clause
instead.
File-by-file.
=> Make has_is_transparent a concept

CMakeLists.txt, libvast/CMakeLists.txt
Problem:
- Some target compile options and target link libraries in CMake are no
longer needed since they are only needed for compilers which Vast no
longer claims support for.
Solution:
- Remove the check for older compilers for setting target compile
options and target link libraries.
File-by-file
=> Remove unused compile options/link libraries for older compilers

.github/workflows/vast.yaml, libvast/CMakeLists.txt
After recent changes, the VAST configury does not pick up the CAF submodule by default anymore, choosing either a system CAF or returning an error. For a successful build out of the box, `VAST_ENABLE_BUNDLED_CAF` has to be set explicitly if no system CAF is installed. This change makes it so we use the bundled CAF by default when developer mode (i.e., not building VAST as a subproject) is enabled and the submodule is checked out.
Try locally :)
=> Use bundled CAF by default if submodule is initialized

libvast/test/detail/concepts.cpp, libvast/vast/as_bytes.hpp, libvast/vast/concept/parseable/core/kleene.hpp, libvast/vast/concept/parseable/core/list.hpp, libvast/vast/concept/parseable/core/plus.hpp, libvast/vast/concept/parseable/core/repeat.hpp, libvast/vast/concept/parseable/detail/container.hpp, libvast/vast/detail/concepts.hpp, libvast/vast/detail/deserialize.hpp, libvast/vast/detail/type_traits.hpp, libvast/vast/format/syslog.hpp
Problem:
- Implementation of `is_container` type trait is a bit noisy due to the
need of two helper alias templates for checking whether `std::size(t)`
and `std::data(t)` is well-formed for a given `t`.
Solution:
- Add `container` concept and write it directly in terms of a requires
expression.
- Rename `container` to `container_t` since the identifier `container`
cannot be a `concept` entity and a `struct`. In favor of not having
concepts be prefixed with `is_` (like type traits), rename the struct
use.
File-by-file.
=> Make is_container a concept

.cmake-format, CMakeLists.txt, cmake/VASTRegisterPlugin.cmake, libvast/CMakeLists.txt, libvast/test/CMakeLists.txt, libvast_test/CMakeLists.txt, tools/dscat/CMakeLists.txt, tools/lsvast/CMakeLists.txt, vast/CMakeLists.txt
Around a third of the remaining clang-tidy warnings in our code base stem from the generated FlatBuffers headers, and since we cannot realistically fix them we should just include the files as system-provided includes.
Additionally, this adds a build option `VAST_ENABLE_CLANG_TIDY` that enables clang-tidy for select targets.
=> Silence warnings in generated FlatBuffers headers

.github/workflows/vast.yaml
A recent change caused the vast-ci Nix build not to have SSE disabled. Additionally, this disables AVX instructions for the regular vast Nix build in order not to break compatibility.
I consider this a bugfix to last week's set of PRs regarding this issue, so no separate changelog entry should be necessary.
To review this, reason about the logic, read the code changes and look at the CI output.
=> Disable SSE for vast-ci Nix build (again)

changelog/unreleased/features/1789--broker-plugin-nix-build.md, nix/static-binary.sh
I considered making this optional in CI, but don't see why we would treat this differently than the PCAP plugin. So this just enables the plugin by default.
Read the code, verify the resulting CI binary.
=> Enable Broker plugin by default for Nix

.github/workflows/style-check.yaml, libvast/vast/concept/parseable/core/repeat.hpp, libvast/vast/concept/parseable/numeric/integral.hpp, libvast/vast/concept/parseable/vast/si.hpp, libvast/vast/concept/printable/detail/print_numeric.hpp, libvast/vast/concept/printable/numeric/integral.hpp, libvast/vast/detail/concepts.hpp, libvast/vast/detail/math.hpp, libvast/vast/detail/varbyte.hpp, libvast/vast/msgpack_builder.hpp, libvast/vast/word.hpp
Problem:
- There is a fair amount of SFINAE and/or `static_assert`s used to
constrain various function templates with integral types which is
verbose and noisy.
Solution:
- Add `integral` concept and refinement concepts for it:
`signed_integral` and `unsigned_integral`. These are as-defined in the
`<concepts>` header that is not yet available in the standard
libraries for compilers used by Vast.
- Apply these concepts to clean up some SFINAE and `static_assert`
usage. Notably, this cleans up `vast::word` quite a bit.
File-by-file.
=> Integral concepts to clean up SFINAE

.github/workflows/vast.yaml, changelog/unreleased/bug-fixes/1799.md, cmake/VASTRegisterPlugin.cmake, nix/static-binary.sh
This PR adds the necessary scaffolding to support the new plugin versioning from #1764 for Nix and Docker.
To be taken over by @tobim for the Nix fixups and the changelog entry, then to be reviewed commit-by-commit.
=> Support unique plugin versions for Nix and Docker

nix/static-binary.sh
Until this change, the static binary script used to reuse the vast
version string for the filename of the final tarball. This was
inconsistent with the artifacts of dynamic builds that we do in CI
for Debian and macOS, where the commit hash is omitted for tagged
revisions.
=> Normalize static binary artifact name

changelog/unreleased/bug-fixes/1804.md, libvast/src/system/partition.cpp, libvast/test/system/partition.cpp
This PR fixes a segfault that occurs when a partition gets status or erase messages before it is fully initialized.
Review commit-by-commit. Test locallly.
=> Block requests to partially initialized partitions

libvast/src/bloom_filter_parameters.cpp, libvast/vast/bloom_filter_parameters.hpp
This PR makes it possible to perform equality comparison of Bloom filter parameters.
Convince yourself of the correctness by glancing at the diff.
=> Make Bloom filter parameters equality-comparable

libvast/test/concepts.cpp, libvast/vast/as_bytes.hpp, libvast/vast/concept/parseable/core/repeat.hpp, libvast/vast/concept/parseable/numeric/integral.hpp, libvast/vast/concept/parseable/numeric/real.hpp, libvast/vast/concept/parseable/vast/si.hpp, libvast/vast/concept/printable/detail/print_numeric.hpp, libvast/vast/concept/printable/numeric/integral.hpp, libvast/vast/concepts.hpp, libvast/vast/detail/deserialize.hpp, libvast/vast/detail/math.hpp, libvast/vast/detail/varbyte.hpp, libvast/vast/format/syslog.hpp, libvast/vast/index/hash_index.hpp, libvast/vast/msgpack_builder.hpp, libvast/vast/word.hpp
Problem:
- `vast::detail` namespace is used for concepts, but this is a bit
awkward in some cases and isn't clear whether something is a concept
entity or not.
Solution:
- Rename concepts namespace from `vast::detail` to `vast::concepts`.
File-by-file.
=> Rename concepts namespace

changelog/unreleased/1819.md, schema/types/suricata.schema
Add a new Suricata schema type 'packet'. this is output as EVE-JSON when the `tagged-packets` config option is set and a rule tags a packet using, e.g. `tag:session,5,packets;`. This PR adds schema support for this case, which has not been considered before.
Please test with current VAST version, I did not test (i.e. run the test suite) with the latest version due to compiler version issues.
=> Add new Suricata schema type 'packet'

libvast/src/system/evaluator.cpp, libvast/vast/config.hpp.in
Problem:
- `VAST_IGNORE_UNUSED` is defined in terms of another macro:
`CAF_IGNORE_UNUSED` which is complicated for its one use in the
codebase.
Solution:
- Use `[[maybe_unused]]` instead and remove the `VAST_IGNORE_UNUSED`
macro.
File-by-file.
=> Remove VAST_IGNORE_UNUSED macro

changelog/unreleased/bug-fixes/1820--bad-segments.md, libvast/src/segment_store.cpp, libvast/src/system/archive.cpp, libvast/test/segment_store.cpp, libvast/vast/segment_store.hpp
Commit by commit. Verify that the first commit makes the tests fail.
=> Gracefully handle malformed segments at startup

libvast/vast/concept/parseable/numeric/integral.hpp
Problem:
- The result of `std::isxdigit` is an int which triggers an int to
bool (the return value of this function) warning.
- Calling `std::isxdigit` with a `char` is undefined. Like other
functions from `<cctype>`, the behavior of `std::isxdigit` is undefined
if the argument's value is neither representable as an `unsigned char`
nor equal to `EOF`.
Solution:
- Explicitly compare the return value of `std::isxdigit` with `0` to
land in a boolean space.
- Convert the argument type to `unsigned char` before calling
`std::isxdigit`.
File-by-file.
=> Fix int-to-bool conversion warning in integral_parser

libvast/src/detail/posix.cpp, libvast/vast/segment_store.hpp
Problem:
- There are a few workarounds in place that were only needed for older
GCC versions that are no longer an issue.
Solution:
- Remove the workarounds.
File-by-file.
=> Remove a few GCC workarounds

.clang-format, libvast/src/concept/convertible/data.cpp, libvast/src/system/type_registry.cpp, libvast/src/taxonomies.cpp, libvast/src/type.cpp, libvast/test/concepts.cpp, libvast/test/convertible.cpp, libvast/test/taxonomies.cpp, libvast/vast/concept/convertible/data.hpp, libvast/vast/concepts.hpp, libvast/vast/detail/narrow.hpp, libvast/vast/taxonomies.hpp, libvast/vast/type.hpp
This PR adds a facility to do `vast::type` assisted conversion from `vast::data` to native c++ data types.
This makes it possible to define a type and an inspect overload for any struct and we get the `convert` for free, no more tedious manual conversion with a lot of error handling.
1. Everything before "Implement generic conversion function for vast::data" is preparatory small fry.
2. Next you can have a look at "Use the data conversion machinery for taxonomies" to get the big picture.
3. Then you can check the tests that are added with the main commit and work through them from top to bottom.
Look at the implementation of the tested functions and verify that the checks are correct.
=> Enable type-assisted data conversion

libvast/src/arrow_table_slice_builder.cpp
Problem:
- `arrow_table_slice_builder` uses `std::enable_if_t` to do different
behavior in different constructors which is verbose.
Solution:
- Use one constructor with `if constexpr` for the different behavior.
File-by-file.
=> Simplify std::enable_if_t usage in arrow_table_slice_builder

.github/workflows/vast.yaml, changelog/unreleased/bug-fixes/1828--plugin-versions-docker.md, cmake/VASTRegisterPlugin.cmake
This fixes the plugin versions in our prebuilt Docker images by using `>-` rather than `>` in the workflow file to avoid a newline in the middle of an env variable definition. And, as a small added bonus, align the plugin versions of the Nix build with all other plugin versions by adding `--abbrev=10` to all other builds as well.
Check Docker CI job: The variables should be set correctly now.
=> Fix plugin versions in prebuilt Docker images

libvast/vast/concept/printable/core/choice.hpp, libvast/vast/concept/printable/core/operators.hpp
Problem:
- `choice` printer uses `std::enable_if_t` which is verbose.
Solution:
- Use concepts instead.
File-by-file.
=> Replace enable_if_t with requires in choice printer

libvast/src/system/posix_filesystem.cpp, libvast/test/system/filesystem.cpp, libvast/vast/system/filesystem_statistics.hpp
This PR makes it possible to understand whether a filesystem operation failed
because the underlying file didn't exist.
Take a look; the unit tests cover it.
=> Make it possible to handle non-existant files

libvast/test/concepts.cpp, libvast/vast/bitmap.hpp, libvast/vast/bitmap_index.hpp, libvast/vast/chunk.hpp, libvast/vast/coder.hpp, libvast/vast/concept/convertible/is_convertible.hpp, libvast/vast/concept/convertible/to.hpp, libvast/vast/concept/printable/core/guard.hpp, libvast/vast/concept/printable/core/printer.hpp, libvast/vast/concept/printable/detail/as_printer.hpp, libvast/vast/concept/printable/numeric/real.hpp, libvast/vast/concept/printable/string/literal.hpp, libvast/vast/concept/printable/vast/bitmap.hpp, libvast/vast/concept/printable/vast/bits.hpp, libvast/vast/concept/printable/vast/coder.hpp, libvast/vast/concept/printable/vast/expression.hpp, libvast/vast/concepts.hpp, libvast/vast/data.hpp, libvast/vast/detail/bit_cast.hpp, libvast/vast/detail/cache.hpp, libvast/vast/detail/logger_formatters.hpp, libvast/vast/detail/operators.hpp, libvast/vast/expression.hpp, libvast/vast/msgpack_builder.hpp, libvast/vast/system/status.hpp, libvast/vast/type.hpp
Problem:
- There is still use of `std::enable_if_t` which is verbose, gives poor
error messages, and is slower to compile than concepts.
Solution:
- Convert most uses of `std::enable_if_t` to use concepts or in-place
`requires` expressions.
File-by-file.
=> Replace std::enable_if_t with requires expressions

libvast/src/system/source.cpp, libvast/src/system/spawn_source.cpp
This moves the log message for 0 event periods to DEBUG.
=> Reduce log output of idle sources

.github/workflows/style-check.yaml
The standalone clang-format package was recently updated for Linuxbrew to support clang-format 12, so let's use that over the much larger LLVM package.
Read the diff, check CI logs.
=> Speed up clang-format CI job

libvast/test/convertible.cpp, libvast/vast/concept/convertible/data.hpp
This adds a convert overload that delegates to the parseable framework. This is useful when the source of the record doesn't make full use of the data model of `vast::data`, or when the target type can be parsed from a string in general.
Check out the tests, contemplate the TODO message.
=> Add a convert overload that delegates to parse

libvast/test/chunk.cpp, libvast/vast/chunk.hpp
See comment in diff.
Follow the logic, trust our unit test suite. Or try to come up with something better.
=> Fix chunk::make for buffers with SBO

libvast/src/format/csv.cpp, libvast/src/format/json.cpp, libvast/vast/concept/convertible/data.hpp, libvast/vast/concept/parseable/core/parser.hpp, libvast/vast/concept/parseable/parse.hpp
Problem:
- `has_parser_v` name is a bit weird given that it is a concept and not
a variable template as one would think with the `_v` suffix.
Solution:
- Rename `has_parser_v` to `registered_parser_type` which sounds more
like a concept instead of possible confusion that it is a variable
template.
File-by-file.
=> Rename has_parser_v to registered_parser_type

libvast/test/detail/vector_map.cpp, libvast/test/detail/vector_set.cpp, libvast/vast/detail/vector_map.hpp, libvast/vast/detail/vector_set.hpp
This PR adds support for the new C++20 member functions `contains` in associative containers.
Look at the implementation and trust the unit tests.
=> Add C++20 overloads for stable containers

libvast/vast/detail/logger.hpp
Problem:
- `pretty_type_name` does different behavior whether `T` is a pointer
type or not which is unnecessary by only removing the pointer type if
`T` is a pointer type.
Solution:
- Always use `std::remove_pointer_t<T>` which will leave the `T` as is
for non-pointer types, thus preserving the same behavior.
File-by-file.
=> Simplify pretty_type_name in vast/detail/logger.hpp

libvast/src/command.cpp, libvast/src/format/zeek.cpp, libvast/src/plugin.cpp, libvast/src/system/configuration.cpp, libvast/src/system/meta_index.cpp, libvast/src/system/partition.cpp, libvast/src/system/pivoter.cpp, libvast/src/system/source.cpp, libvast/src/table_slice.cpp, libvast/vast/detail/string.hpp
Problem:
- There is a hand-rolled algorithm `starts_with` and `ends_with` which is not needed as
of C++20 due to member function `starts_with` and `ends_with` for `std::string` and
`std::string_view` types.
Solution:
- Remove the hand-rolled `starts_with` and `ends_with` algorithms in favor of the member
functions on string-like types.
=> Remove hand-rolled starts_with and ends_with algorithms

libvast/vast/concept/parseable/core/parser.hpp, libvast/vast/concept/printable/core/printer.hpp, libvast/vast/concepts.hpp
Problem:
- Core parser has a few overloaded call operators, some with default
arguments.
Solution:
- Reduce the number of overloads by always accepting a parameter pack
for the attributes and doing different behavior based on the arity.
- Add `range` concept and apply it to core parser and core printer.
Note:
- We could remove the C-array overload and collapse it into the range
overload if desired, but it's not worth it given how small the
implementation of the array overload is.
File-by-file.
=> Simplify call operators in core parser

changelog/unreleased/changes/1842--improved-error-format.md, libvast/src/error.cpp, libvast/src/plugin.cpp, libvast/test/convertible.cpp, libvast/test/error.cpp, libvast/vast/concept/convertible/data.hpp, libvast/vast/concepts.hpp
Best illustrated with a demo:
Old:
```
[22:45:53.372] failed to initialize plugins: !! unspecified: "failed to initialize plugin inventory: !! invalid_configuration: \"failed to apply config: !! convert_error: \\\"scope(\\\\\\\"[3](\\\\\\\\\\\\\\\"unable to parse \\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\"blahbal\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\\" into a vast.subnet\\\\\\\\\\\\\\\")\\\\\\\")\\\"\" "
```
New:
```
[23:01:15.022] failed to initialize plugins: !! unspecified: failed to initialize the inventory plugin: !! invalid_configuration: failed to apply config: !! convert_error: scope[3]: unable to parse "blahbal" into a vast.subnet
```
Commit-by-commit. Should be self-explanatory.
=> Improve rendering of error messages & fix record to map conversion

libvast/vast/concept/convertible/data.hpp
A recent oversight in tenzir/vast#1842 broke the build (again). We must use `VAST_FMT_RUNTIME` for format strings that cannot be verified at compile time, e.g., because they are not constant.
:shrug:
=> Fix build with {fmt} 8+

changelog/unreleased/bug-fixes/1848--relative-metrics-paths.md, libvast/src/system/accountant.cpp, libvast/src/system/node.cpp, libvast/vast/system/accountant.hpp
The paths `vast.metrics.{file,uds}-sink.path` were, unlike othe relative paths, interpreted as relative to the current working directory of the VAST server instead of relative to the database directory. This changes the ACCOUNTANT actor to be aware of the database directory.
File-by-file. Run locally.
=> Interpret metrics paths relative to the db root

.github/workflows/vast.yaml
This sets the correct version for our prebuilt VAST Docker images.
Verify that the change I made is correct.
Don't think this needs a changelog entry, it really only is relevant when connecting local VAST clients to a VAST server running inside Docker (or vice versa).
=> Set the exact version for prebuilt Docker images

changelog/unreleased/features/1805.md, libvast/src/partition_synopsis.cpp, libvast/src/system/archive.cpp, libvast/src/system/explorer.cpp, libvast/src/system/get_command.cpp, libvast/src/system/index.cpp, libvast/src/system/local_segment_store.cpp, libvast/src/system/meta_index.cpp, libvast/src/system/partition.cpp, libvast/test/flatbuffers.cpp, libvast/test/system/archive.cpp, libvast/test/system/local_segment_store.cpp, libvast/test/system/meta_index.cpp, libvast/vast/atoms.hpp, libvast/vast/fbs/interval.fbs, libvast/vast/fbs/segment.fbs, libvast/vast/fbs/synopsis.fbs, libvast/vast/fwd.hpp, libvast/vast/partition_synopsis.hpp, libvast/vast/query.hpp, libvast/vast/segment_builder.hpp, libvast/vast/system/actors.hpp, libvast/vast/system/archive.hpp, libvast/vast/system/local_segment_store.hpp, libvast/vast/system/meta_index.hpp
Restore the ability to use offsets/ids when working with partition-local stores. This should also make it possible to use `vast explore` and `vast get` in combination with custom store backends.
Review commit-by-commit. Some points worth considering:
* Should the query contain `optional<ids>` instead of ids, to distinguish between "no ids given" and "the empty set of ids requested"?
=> Restore unique IDs for partition-local stores

.cmake-format, changelog/unreleased/bug-fixes/1850--native-plugins-static-binary.md, cmake/VASTRegisterPlugin.cmake, libvast/CMakeLists.txt, libvast/test/CMakeLists.txt, vast/CMakeLists.txt
The plugin scaffold has an auto-registration feature, but for static linking this requires the plugin library to be assembled with `-whole-archive` (or similar, depending on the linker and platform). libvast doesn't use that option, so auto-registration fails for the generated static binary because the symbols are omitted.
The solution here is to extract native plugins from the libvast target into a separate library that is linked appropriately into the VAST binary directly, forcing the linker not to omit the symbols required for the auto-registration.
Run the generated static binary from CI and check if the native plugins works. Or, alternatively, build this locally and patch out the code that removes natives plugins from the output of `vast version`.
This is what it shows for me on this …
=> Support native plugins in the static binary

changelog/unreleased/bug-fixes/1852--in-process-sources-status.md, libvast/src/system/datagram_source.cpp, libvast/src/system/node.cpp, libvast/src/system/source.cpp, libvast/vast/system/status.hpp
This changes the exclusion of sources/sinks from the status output such that only remote sources/sinks are skipped. It also fixes a segfault in the status handler of the SOURCE actor and DATAGRAM SOURCE broker.
Try locally.
=> Include in-process sources/sinks in status output

changelog/unreleased/bug-fixes/1858--quoted-non-string-fields-csv.md, libvast/src/format/csv.cpp, libvast/test/format/csv.cpp
Before this change, only the `field` parser which we used for column names and string fields respected possible quoting and escaping of fields. Now, all non-container types support quoting.
Read the code. The tests should be self explanatory. The changed tests failed before the parser changes.
=> Support quoted non-string fields in the CSV parser

changelog/unreleased/bug-fixes/1857--journald-support-check.md, libvast/src/logger.cpp, vast.yaml.example
VAST now only switches to `journald` style logging by default when it is actually supported.
=> Fix logging in systemd when built without support

changelog/unreleased/changes/1854--update-suricata-dhcp.md, schema/types/suricata.schema
=> Align suricata.dhcp with the latest eve.log schema

changelog/unreleased/bug-fixes/1856--usr-to-etc.md, libvast/src/detail/installdirs.cpp.in
Per the recommendation at
https://cmake.org/cmake/help/v3.21/module/GNUInstallDirs.html#special-cases
Install static binary to /usr/bin/vast and test locally whether /etc/vast/vast.yaml is getting picked up.
=> Use /etc as sysconfdir for install prefix /usr

libvast/src/partition_synopsis.cpp, libvast/src/system/index.cpp, libvast/src/system/partition.cpp, libvast/test/flatbuffers.cpp, libvast/vast/detail/friend_attribute.hpp, libvast/vast/fbs/utils.hpp, libvast/vast/partition_synopsis.hpp, libvast/vast/synopsis.hpp, libvast/vast/system/partition.hpp, libvast/vast/uuid.hpp, tools/lsvast/src/print_partition.cpp, tools/lsvast/src/print_segment.cpp
- Check for errors when writing partition synopsis
- Fill in missing offset/events information for partition synopses
Import some data using `VAST 2021.07.29`, then do some queries using a build from this PR to verify that queries work and VAST doesn't crash with assertion failures.
=> Verify partition synopsis update and fill in correct information

changelog/unreleased/features/1871--status-list-config-files.md, libvast/src/plugin.cpp, libvast/src/system/configuration.cpp, libvast/src/system/node.cpp, libvast/vast/plugin.hpp, libvast/vast/system/configuration.hpp
This makes `vast status --detailed` show the loaded config files in the server process.
Build locally, run `vast status --detailed | jq .system` to see.
=> Show loaded config files in status output

changelog/unreleased/bug-fixes/1872--status-garbage-output.md, libvast/vast/system/status.hpp
This had a slight race condition: We captured a `string_view` to every component's type, and used that as a key in the status output. However, when small string optimization is used, the addition/removal of components caused the string views to be invalidated. This change makes it so the status handler copies the keys.
Reasoning about the change should suffice, it's really simple in hindsight.
=> Fix possible garbage in status command output

changelog/unreleased/bug-fixes/1873--remote-status.md, libvast/src/system/node.cpp
We erroneously compared the remote actors proxy actor system's node ID rather than the remote actors actual node ID when checking whether an actor is remote.
Try locally.
=> Fix ignoring of remote sources and sinks for status

changelog/unreleased/features/1881--pending-query-status.md, libvast/src/system/active_partition.cpp, libvast/src/system/index.cpp, libvast/src/system/indexer.cpp, libvast/src/system/meta_index.cpp, libvast/vast/system/actors.hpp, libvast/vast/system/index.hpp, vast/integration/reference/server-zeek-conn-log/step_07.ref
In addition to the title it also adds streaming info to the active partition and meta index.
Check the output of `vast status --debug` after some data was ingested.
=> Add the streaming and query info to the index status

changelog/unreleased/bug-fixes/1884--pending-query-map-mismatch.md, libvast/src/system/index.cpp, libvast/vast/system/index.hpp
This changes the INDEX to monitor EXPORTER actors in order to be able to remove pending queries when an EXPORTER goes down unexpectedly without cancelling its running queries. This fixes a mismatch in the pending queries map in the output of `vast status --detailed`, and also stops the index from doing further unnecessary work if an export was unexpectedly killed.
Commit-by-commit. Play around with it locally by killing processes off.
=> Fix possible desync in pending queries map

changelog/unreleased/bug-fixes/1886--bail-on-unsupported-exprs.md, libvast/src/expression_visitors.cpp, libvast/test/expression.cpp
The field meta extractor currently only supports equality comparisons with strings. This change adds a validation check to abort with an error in all other cases.
Read the commits in reverse order; consider whether additional cases should be tested.
=> Disallow unsupported field meta extractor predicates

CMakeLists.txt
Turns out we were only autovectorizing CI builds. D'uh.
=> Autovectorize beyond CI builds

libvast/vast/concept/parseable/vast/schema.hpp
This change simply removes the warning. Nothing else.
=> Don't warn for every layout field with type list<record{..}>

doc/cli/vast-export.md, libvast/src/system/read_query.cpp
After real-world experience, the previous rules had too many
false positives that caused VAST to break due to some file
descriptor being accidentally attached to stdin.
=> Be more lenient with empty queries on stdin

changelog/unreleased/features/1942--query-backlog-metrics.md, libvast/src/system/index.cpp, libvast/test/system/eraser.cpp, libvast/test/system/query_processor.cpp, libvast/vast/system/actors.hpp, libvast/vast/system/index.hpp, vast.yaml.example
Commits 2 and 3 are only moving code around and don't contain any logical changes.
=> Add metrics to the index

libvast/src/logger.cpp, libvast/src/system/application.cpp, libvast/src/system/shutdown.cpp, libvast/test/system/terminate.cpp, libvast/vast/atoms.hpp, libvast/vast/defaults.hpp, libvast/vast/logger.hpp
Removed usage of caf::atom_value for logger configuration.   
File by file review.
=> Remove usage of caf::atom_value for logger configuration

libvast/vast/detail/narrow.hpp
`std::forward` is no longer available when including `<type_traits>` only.
:shrug:
=> Fix build with libc++ from LLVM 13

libvast/src/system/index.cpp, libvast/src/system/node.cpp, libvast/src/system/query_supervisor.cpp, libvast/vast/system/actors.hpp, libvast/vast/system/index.hpp
This additionally changes the status output to use components labels instead of their type name. This means that all exporters should now be printed.
=> Add metrics about the index workers

libvast/CMakeLists.txt, libvast/vast/detail/byte_swap.hpp, libvast/vast/hash/uniquely_represented.hpp
We noticed these having an overall negative impact on
build times, since they prevent ccache from caching
the build result.
Since precompiled headers are used for every translation
unit, some minor fixups are needed to fix the build
after disabling them.
=> Disable precompiled headers

changelog/unreleased/bug-fixes/1959--load-static-plugins.md, libvast/src/plugin.cpp
We noticed that for our static builds with plugins it was impossible to disable the plugins, which is a regression and differs from the documentation that says that static plugins must be explicitly enabled. This change makes it so static plugins work as expected again.
I've tried this locally with a mix of dynamic and static plugins and various configurations, including mixed `all`, `bundled`, and specifically enabled plugins. Either reproduce this locally, or ask me to show you in a video call.
=> Load static plugins only when enabled

.github/workflows/jupyter.yaml, .github/workflows/vast.yaml
This one's on me, I forgot to update this workflow as part of the fix in #1959. This should get the Jupyter Notebook CI workflow to run through again.
Watch CI.
=> Enable PCAP plugin in Jupyter Notebook workflow

libvast/vast/detail/assert.hpp
Previous to this change the statement `VAST_ASSERT(expr)` would still evaluate `expr` unless the optimizer was able to eliminate the code after inlining.
Of course it is better not to rely on that mechanism, and indeed it sometimes fails even with LTO turned on.
In a simple ingest test on my T14s the suricata parser performance increased by about 16% and exporting with a highly selective query performed a whopping 4 times faster.
Trivial.
=> Avoid evaluating calls when assertions are disabled

.github/workflows/vast.yaml
To be merged once Apache Arrow 6.0.0 is available on Homebrew in CI.
This essentially reverts an earlier change. We can re-run this every so often and merge when the new Homebrew version is available in CI.
=> Make use of LLVM 13 in macOS CI

.github/workflows/vast.yaml
Since we want upload the output of release builds to GCS, we should also install gsutil and configure credentials for these CI runs.
=> Install gsutil when doing release builds

CMakeLists.txt, cmake/Findxxhash.cmake, cmake/VASTChangelog.cmake.in, cmake/VASTRegisterPlugin.cmake, examples/plugins/analyzer/CMakeLists.txt, examples/plugins/transform/CMakeLists.txt, plugins/broker/CMakeLists.txt, plugins/pcap/CMakeLists.txt
See CMake changelog and release notes at https://blog.kitware.com/cmake-3-22-0-available-for-download/
Nothing major that affects us, and no policy changes that affect our build either in any of the five build configurations I've tested this with (Debug, RelWithDebInfo, Release, MinSizeRel, CI).
Don't think this needs a thorough review—it's a pretty simple maintenance change.
This doesn't need a changelog entry either, as it does not raise the minimum version, but rather only the policy opt-in version.
=> Make use of CMake 3.22 policies

Dockerfile
This shaves an extra 50MB off of our Dockerfile. Noticed this file inside the container when debugging something at a stage where it definitely should not exist anymore. This fixes that issue.
It's a really simple thing. To debug, you can do the following:
```bash
docker build . -t review --target dependencies
docker run review ls -la
```
And check whether there are any files that should not exist at that point. Running it for me locally yields this as of this PR:
```
❯ docker run review ls -la
total 136
drwxr-xr-x  1 root root  4096 Nov 19 11:05 .
drwxrwxrwt  1 root root  4096 Nov 19 11:04 ..
-rw-r--r--  1 root root   263 Nov 18 13:25 BANNER
-rw-r--r--  1 root root 30072 Nov 18 13:25 CMakeLists.txt
-rw-r--r--  1 root root  1529 Nov 18 13:25 LICENSE
-rw-r--r--  1 root root  2128 Nov 18 …
```
=> Remove Arrow .deb after installing in Dockerfile

libvast/src/system/index.cpp, libvast/src/system/make_transforms.cpp, libvast/src/system/partition_transformer.cpp, libvast/vast/system/make_transforms.hpp
Several smaller refactorings that make working with partition transforms more convenient. In particular:
* Storing the transform configuration in the node state, so that plugins can have access to it.
* Exposed a function to make a transform object out of a configuration object describing a transform.
* Fixed a bug where transformed partitions were not correctly added to the index state.
* Various clean-ups and clang-tidy suggestions.
=> Partition Transforms Refactoring

libvast/vast/hash/hash_append.hpp
The legacy type system was the only place that depended on the hashes of the type name annotation in inspect overloads to be included in the hash, and now that we don't have that anymore we can remove it. This should result in a small speedup of hash functions using the hash inspector and make the branch predictor be in a happier place.
This builds on top of #1888. Really small PR, just need to verify manually that old databases still work.
=> Remove type name hashing

changelog/unreleased/features/1974--import-selector-json.md, doc/cli/vast-import-json.md, libvast/src/format/json.cpp, libvast/src/format/reader_factory.cpp, libvast/src/system/application.cpp, libvast/vast/format/json.hpp, libvast/vast/format/json/default_selector.hpp, libvast/vast/format/json/field_selector.hpp, libvast/vast/format/json/selector.hpp, libvast/vast/format/json/suricata_selector.hpp, libvast/vast/format/json/zeek_selector.hpp, vast.yaml.example, vast/integration/vast_integration_suite.yaml
This adds a new `--selector=<field>[:<prefix>]` option to the JSON import. The *field* contains the *event name*, which when prefixed with the optional *prefix* is used for selecting the event type.
This previously existed as a hard-coded option for the Zeek Stremaing JSON and Suricata Eve JSON readers, which still exist unchanged.
The following commands are now equivalent:
```sh
vast import suricata
vast import json --selector=event_type:suricata
vast import zeek-json
vast import json --selector=_path:zeek
```
File-by-file. I left some notes as review comments that are helpful to look at.
Note that this is based on #1888 to avoid merge conflicts.
=> Make JSON field selectors configurable

libvast/src/detail/add_message_types.cpp, libvast/src/system/exporter.cpp, libvast/src/system/index.cpp, libvast/src/system/query_processor.cpp, libvast/test/system/eraser.cpp, libvast/test/system/index.cpp, libvast/test/system/query_processor.cpp, libvast/vast/fwd.hpp, libvast/vast/system/actors.hpp, libvast/vast/system/index.hpp, libvast/vast/system/query_cursor.hpp
The internal query handler of the index used to return void but
actually sent an unsafe response with the uuid, candidates and
scheduled partitions triple to the requester. The historical
reason for this was to prevent a race condition which happened when
results started flowing to the requester before it received the
initial response. This problem happens when the OS scheduler
suspends the thread between initiating the worker and returning
the triple.
This commit replaces the old workaround with a cleaner approach:
We now use a response promise and deliver it before initiating the
worker. This is enough to guarantee that the messages will arrive
in the expected order at the requester.
Thanks to that the query handler signature now correctly indicates
that the requester should expect a …
=> Straighten the index actor signature

libvast/vast/detail/assert.hpp
With assertions disabled (e.g., in Release build configurations), the bugprone-* suite triggered for assertions, reporting a suspicious use of sizeof on a pointer to an aggregate. This change simply serves to disable that warning.
This is purely developer-facing, so just verify that I did not make a meaningful change to the underlying logic.
=> Silence bugprone-* clang-tidy warnings for assertions

libvast/test/concepts.cpp, libvast/vast/chunk.hpp, libvast/vast/concept/convertible/data.hpp, libvast/vast/concept/convertible/to.hpp, libvast/vast/concept/printable/detail/as_printer.hpp, libvast/vast/concept/printable/vast/bits.hpp, libvast/vast/concepts.hpp, libvast/vast/data.hpp, libvast/vast/detail/logger_formatters.hpp, libvast/vast/detail/operators.hpp, libvast/vast/hash/concepts.hpp, libvast/vast/msgpack_builder.hpp, libvast/vast/type.hpp
Now that we require clang-13 and gcc-10, we can make use of the standard concepts library, replacing some of the polyfill concepts we had defined in our `vast/concepts.hpp` header file.
This is just a 1-to-1 replacement, except for `vast::different`, which I replaced with `!std::same_as`. So it probably suffices to read through the code and rely on CI.
=> Make use of `<concepts>`

LICENSE.3rdparty, cmake/VASTRegisterPlugin.cmake, libvast/src/sketch/bloom_filter.cpp, libvast/src/sketch/bloom_filter_config.cpp, libvast/test/sketch/bloom_filter.cpp, libvast/vast/config.hpp.in, libvast/vast/detail/worm.hpp, libvast/vast/fbs/bloom_filter.fbs, libvast/vast/sketch/bloom_filter.hpp, libvast/vast/sketch/bloom_filter_config.hpp, libvast/vast/sketch/bloom_filter_view.hpp
This PR provides an alternative implementation of the existing (textbook) Bloom filter implementation using a fast modulo reduction technique called *worm hashing* by @pdillinger. Think of it as generalization of @lemire's fastrange reduction.
Notable points to consider:
- The overall plan is to do more work in namespace `vast::sketch`, such that we can treat the existing filter in namespace `vast` as the legacy version. Generally, the plan is to keep using "synopsis" for the legacy part and "sketch" for the new framework that has first-class support for a separate read and write path. 
- I've added two types two namespaces `vast::sketch`: `bloom_filter_config` and `bloom_filter_params`. The former is supposed to take a combination of *n*, *m*, *p*, and *k* parameters as input, the latter …
=> Add worm hashing Bloom filter

cmake/VASTRegisterPlugin.cmake, libvast/src/segment.cpp, libvast/src/segment_builder.cpp, libvast/test/flatbuffer.cpp, libvast/test/partition_roundtrip.cpp, libvast/test/segment.cpp, libvast/vast/flatbuffer.hpp, libvast/vast/fwd.hpp, libvast/vast/segment.hpp
This should help simplify our code a fair bit down the line: A wrapper around a FlatBuffers table pointer that shares the reference count of the chunk it is constructed from, and is thus easier to handle via RAII. A `vast::flatbuffer<T>`  can optionally be constructed from a `flatbuffers::DetachedBuffer&&`, allowing the developer to skip handling the chunk entirely. The major advantage of this compared to using a `vast::chunk` directly is that it is safe to slice a non-root table from a `vast::flatbuffer`, which helps reduce unnecessary pointer chasing.
Likely best reviewed by @lava, with whom I just recently discussed this in Slack. 
Note that this is a small Saturday ~morning~ project, so ~I've not bothered adding test cases~ test cases are minimal so far. I will add some if the general …
=> Implement a wrapper for FlatBuffers table pointers

CMakeLists.txt, LICENSE.3rdparty, libvast/src/partition_synopsis.cpp, libvast/src/system/active_partition.cpp, libvast/src/system/explorer.cpp, libvast/src/system/pivoter.cpp, libvast/src/type.cpp, libvast/src/view.cpp, libvast/test/type.cpp, libvast/vast/concept/convertible/data.hpp, libvast/vast/detail/generator.hpp, libvast/vast/project.hpp, libvast/vast/type.hpp
This takes `generator<T>` from the popular cppcoro library from Lewis Baker, and makes use of it in the new type system in places where previously we either returned a custom proxy type that had a range-interface or a vector. The resulting code changes for `record_type::fields()` and `record_type::leaves()` show just how big of a readability improvement this is.
This is purely a refactoring, there are no functional changes to the code. This was a small late afternoon project from yesterday, and I think it's not high-priority to review.
When you do the review, I recommend also doing a quick performance check or rolling this out onto our testbed as a sanity-check. With clang-13 on macOS the performance difference is negligible on export and the import is ~5% faster than on master for Zeek …
=> Add a coroutine-based generator type

libvast/CMakeLists.txt, libvast/vast/hash/xxhash.hpp
The patch version bump from 0.8 to 0.8.1 removed the `XXH_ACCEPT_NULL_INPUT_POINTER` macro.
Double-check with the release notes for xxHash 0.8.1: https://github.com/Cyan4973/xxHash/releases/tag/v0.8.1
=> Add support for xxHash >= 0.8.1

changelog/unreleased/features/1987--metrics-metatdata, libvast/src/format/csv.cpp, libvast/src/format/json.cpp, libvast/src/system/accountant.cpp, libvast/src/system/active_partition.cpp, libvast/src/system/archive.cpp, libvast/src/system/exporter.cpp, libvast/src/system/importer.cpp, libvast/src/system/index.cpp, libvast/src/system/meta_index.cpp, libvast/src/system/passive_partition.cpp, libvast/src/system/sink_command.cpp, libvast/src/system/source.cpp, libvast/src/system/type_registry.cpp, libvast/test/partition_roundtrip.cpp, libvast/test/system/meta_index.cpp, libvast/test/system/partition.cpp, libvast/vast/fwd.hpp, libvast/vast/system/active_partition.hpp, libvast/vast/system/actors.hpp, libvast/vast/system/meta_index.hpp, libvast/vast/system/passive_partition.hpp, libvast/vast/system/report.hpp, plugins/pcap/main.cpp
This change makes it possible to add pairs of strings as metadata to a metrics event.
This also removes code for the defunct server side STDOUT heartbeat and 2 commits adding accountant actor handles to the meta index and partition in preparation of additional metrics.
This depends on #1986.
By commit.
=> Add metadata elements to the metrics events

libvast/src/data.cpp
The warning was actually triggered because the counter was decremented
in every iteration of a loop, instead of only on recursion.
We fix that and make the function argument `const` while we're at it.
This should be straight forward, one file two lines.
=> Remove the erroneous warning about exceeded merge recursion limit

libvast/src/type.cpp, libvast/test/type.cpp
This removes the recursive `flat_size` helper function that `record_type:.num_leaves` and `record_type::flat_index` relied upon internally and removes it. Instead, I've rewritten the functions to operate without recursion directly on the underlying FlatBuffers table, which is a fair bit faster. Considering we spend over 10% of the time during `export null` in `record_type::flat_index` I expect this to be a meaningful optimization (measurements yet to be done).
No changelog entry needed as #1888 did not make it into a release yet. We need to measure the impact of this change before merging, although I am quite confident in expecting this to have a positive impact to export times.
Please review the logic function-by-function, verifying that their behavior is unchanged. The unit tests are …
=> Optimize `record_type::{num_leaves,flat_index}`

changelog/unreleased/features/1987--metrics-metatdata, changelog/unreleased/features/1987-1992--metrics-metatdata.md, libvast/src/system/accountant.cpp, libvast/src/system/active_partition.cpp, libvast/src/system/exporter.cpp, libvast/src/system/index.cpp, libvast/src/system/indexer.cpp, libvast/src/system/local_segment_store.cpp, libvast/src/system/meta_index.cpp, libvast/src/system/partition_transformer.cpp, libvast/src/system/passive_partition.cpp, libvast/src/system/spawn_index.cpp, libvast/test/system/counter.cpp, libvast/test/system/exporter.cpp, libvast/test/system/index.cpp, libvast/test/system/local_segment_store.cpp, libvast/test/system/partition_transformer.cpp, libvast/vast/plugin.hpp, libvast/vast/system/exporter.hpp, libvast/vast/system/index.hpp, libvast/vast/system/local_segment_store.hpp, libvast/vast/system/partition_transformer.hpp
This change adds metrics events that are emitted for each query from the meta index, partition and store components. All new metrics and the preexisting exporter metrics events use the query ID as metadata value to allow cross-referencing.
Each commit can be reviewed individually in order.
The last commit modifies the interface of the store plugin, which is unfortunate and I would like to discuss alternative approaches.
=> Emit fine grained metrics for every part of the query pipeline

libvast/src/arrow_table_slice.cpp, libvast/src/arrow_table_slice_builder.cpp, libvast/src/expression_visitors.cpp, libvast/src/msgpack_table_slice.cpp, libvast/src/msgpack_table_slice_builder.cpp, libvast/src/partition_synopsis.cpp, libvast/src/system/active_partition.cpp, libvast/src/system/importer.cpp, libvast/src/system/meta_index.cpp, libvast/src/system/partition_transformer.cpp, libvast/src/table_slice.cpp, libvast/test/system/exporter.cpp, libvast/vast/arrow_table_slice.hpp, libvast/vast/concept/printable/vast/expression.hpp, libvast/vast/detail/partition_common.hpp, libvast/vast/detail/spawn_container_source.hpp, libvast/vast/expression.hpp, libvast/vast/fbs/synopsis.fbs, libvast/vast/fbs/table_slice.fbs, libvast/vast/msgpack_table_slice.hpp, libvast/vast/partition_synopsis.hpp, libvast/vast/table_slice.hpp
This adds the ingest time to the table slice API, which is set in the server process alongside the id/offset assignment.
=> Capture the ingest time for new table slices

libvast/src/system/meta_index.cpp, libvast/test/system/counter.cpp, libvast/test/system/meta_index.cpp, libvast/vast/detail/partition_common.hpp, libvast/vast/partition_synopsis.hpp
Turns out that `min(epoch, t)` is always `epoch`. This fixes that by assigning `time::max()` for the minimum import time.
Not really user-facing (yet), so no changelog entry needed. The fix is quite easy to understand.
=> Fix minimum import time in partition synopses

libvast/src/system/indexer.cpp
Instead of decoding columns in table slice for every row, we should make use of the existing API for appending a whole column at once. I'm not sure when this got thrown out, but it's been dead code before this change, although we definitely do want to make use of it.
An even better API for this would be to not have a custom function in the table slice API that takes a value index, but rather to return a `detail::generator<data_view>` per column that can be lazily iterated over. That still shouldn't stop us from using this special function before we have a more generic solution, though.
Measure perf.
=> Make use of `table_slice::append_column_to_index`

libvast/src/experimental_table_slice.cpp, libvast/src/experimental_table_slice_builder.cpp, libvast/src/table_slice.cpp, libvast/src/table_slice_builder_factory.cpp, libvast/test/experimental_table_slice.cpp, libvast/vast/concept/parseable/vast/table_slice_encoding.hpp, libvast/vast/experimental_table_slice.hpp, libvast/vast/experimental_table_slice_builder.hpp, libvast/vast/fbs/table_slice.fbs, libvast/vast/fwd.hpp, libvast/vast/table_slice.hpp, libvast/vast/table_slice_encoding.hpp
The `experimental` format is explicitly unstable, and serves as a playground for upcoming changes to the Arrow encoding. We plan to merge these as a v2 of the current encoding some time in the future, but want to be able to make incremental changes. Please do not use this feature in production, as we explicitly do not guarantee backwards compatibility for it.
To enable permanently for local development, put this into your `vast.yaml` configuration file:
```yaml
vast:
import:
batch-encoding: experimental
```
This format is intentionally undocumented and thus does not require a changelog entry. For reviewing, I suggest running the integration tests locally after changing the default encoding to `arrow-ng`. Most of the code is just a copy, except for the occasional `_ng` suffix to avoid ODR …
=> Introduce an experimental Arrow table slice encoding

libvast/src/experimental_table_slice.cpp, libvast/src/experimental_table_slice_builder.cpp, libvast/test/experimental_table_slice.cpp, libvast/test/expression_evaluation.cpp, libvast/vast/table_slice.hpp
Instead of using `Int64Array` to represent our `duration_type`, we now use the `DurationArray` which is the proper arrow data type for durations. This only applies to our `experimental` table slice, and is therefor not considered a breaking change for our customers.
This should be relatively straight forward: please convince yourself that the existing unit tests for experimental table slice properly capture encoding / decoding paths for durations.
=> Represent vast `duration_type`s as `arrow::DurationType` in arrow / experimental table slice

examples/plugins/analyzer/example_analyzer.cpp, libvast/src/detail/settings.cpp, libvast/src/system/source.cpp, libvast/src/system/spawn_counter.cpp, libvast/src/system/spawn_eraser.cpp, libvast/src/system/spawn_explorer.cpp, libvast/src/system/spawn_exporter.cpp, libvast/src/system/spawn_pivoter.cpp, libvast/src/systemd.cpp, libvast/test/convertible.cpp, libvast/vast/concept/parseable/vast/schema.hpp, libvast/vast/detail/logger_formatters.hpp
This makes it easier for any given struct to be opted into using `caf::deep_to_string` for formatting with {fmt} by simply defining a static member variable `use_deep_to_string_formatter` with the value `true`.
This is purely a refactoring that does not incur any user-facing changes.
@mavam in your PR you can now simply add `constexpr inline static bool use_deep_to_string_formatter = true` to your structs, which will make them use this formatter automatically.
=> Make opt-in to formatting via deep_to_string easier

libvast/src/system/type_registry.cpp, libvast/vast/fbs/type.fbs, libvast/vast/fbs/type_registry.fbs, libvast/vast/fwd.hpp
This changes the Type Registry state to be persisted using FlatBuffers in a versioned fashion, rather than the old CAF-serialized format. When starting VAST for the first time with this PR the old state is removed automatically.
This should not be user-facing at all.
I recommend reading the code, and most importantly reviewing the new FlatBuffers table, and then giving it a spin locally. For me this has worked as expected so far.
=> Use FlatBuffers for the Type Registry state

libvast/src/type.cpp, libvast/test/flatbuffer.cpp, libvast/vast/fbs/type.fbs
This is a refactoring that @mavam and I talked about this morning in Slack. Figured I'd do it directly instead of writing the idea down since it was only a set of text replacements.
The general idea here is that instead of using a _vX suffix, we name the union members explicitly, adding a suffix for outdated versions only.
The version of FlatBuffers we depended on when writing most of our FlatBuffers table did not allow for explicitly naming union members, which is part of why we ended up with the existing naming scheme in the first place.
Review the `type.fbs` changes; everything else is mechanical.
=> Simplify naming scheme in `type.fbs`

libvast/src/experimental_table_slice_builder.cpp, libvast/test/experimental_table_slice.cpp, libvast/vast/experimental_table_slice_builder.hpp, vast/integration/vast_integration_suite.yaml
This provides the ability to partially recover a VAST type from a
provided Arrow schema.  In the current transformation from VAST to Arrow we lose certain information and cannot recover it. This requires changes in the way VAST layouts are represented in Arrow, and will be worked on in follow-up PRs.
At the moment, the supported functionality is:
- all basic types except enum
- lists
- address (every `FixedBinary(16)` is assumed to be an address)
- subnet (every `FixedBinary(17)` is assumed to be a subnet)
- record types (structs)
- nested records at the field level
Not supported:
- recursive top-level record types (because VAST -> conversion
"flattens" the schema)
- pattern: cannot be distinguished from `string` type
- maps: cannot be distinguished from a list<structs<key, value>>
- …
=> Allow  computing a VAST type from an Arrow schema

.clang-tidy
By default, clang-tidy warns if it encounters classes like
struct A {
virtual ~A() = default;
};
requiring that we also define a copy constructor and assignment
operator. I don't see a good reason for this, and since there's
an option to change this behavior let's enable that option.
This also removes an earlier option for `readability-else-after-return`, since we completely disabled that check in an earlier commit.
=> Dont warn for classes with defaulted virtual destructor

libvast/src/experimental_table_slice.cpp, libvast/src/experimental_table_slice_builder.cpp, libvast/test/experimental_table_slice.cpp
To further align with the arrow ecosystem, we use `arrow::MapType` to more precisely express the semantics of `vast::map`.
This is hopefully obvious. Verify that a unit test exists that tests the desired table slice behavior (`single column - map`).
=> Use `arrow::MapType` to represent `vast::map` in arrow schema

libvast/src/base.cpp, libvast/src/ewah_bitmap.cpp, libvast/src/null_bitmap.cpp, libvast/src/wah_bitmap.cpp, libvast/test/bitmap.cpp, libvast/test/bitmap_index.cpp, libvast/test/coder.cpp, libvast/vast/base.hpp, libvast/vast/bitmap_algorithms.hpp, libvast/vast/bitmap_index.hpp, libvast/vast/coder.hpp, libvast/vast/concept/printable/vast/coder.hpp, libvast/vast/fbs/coder.fbs, libvast/vast/fwd.hpp
This adds `pack` and `unpack` functions for our various coder types, associated FlatBuffers tables and unit tests for the pack/unpack roundtrip. This is not yet used in practice, but is in preparation for an upcoming change that puts value indexes into FlatBuffers tables.
This is based on #2021. Review commit-by-commit.
=> Add FlatBuffers for `*_coder` and `bitmap_index`

changelog/unreleased/bug-fixes/2032--index-telemetry.md, libvast/src/system/index.cpp, libvast/test/system/eraser.cpp, libvast/test/system/query_processor.cpp, libvast/vast/system/actors.hpp
If I understood the code before this change directly, then the index set the accountant actor properly upon spawning, and then expected to be sent the accountant actor again to start its telemetry loop—which never happens. This resulted in the telemetry loop never actually being started.
The change itself is trivial.
I requested @tobim for review because he worked on these metrics recently, and I know that they've been shown on our testbed. When did this break?
=> Start the telemetry loop of the index correctly

libvast/src/system/active_partition.cpp, libvast/src/system/importer.cpp, libvast/src/system/index.cpp, libvast/src/system/partition_transformer.cpp, libvast/vast/detail/shutdown_stream_stage.hpp, libvast/vast/detail/specialization_of.hpp
Properly shutting down a caf stream stage is not an easy task, with many ordering details that one can get wrong. This commit introduces a utility function to simplify the issue.
Credits to @dominiklohmann for contributing the `is_specialization_of` template function.
Review as a whole.
=> Create a dedicated function to shut down stream stages

libvast/src/detail/add_message_types.cpp
We used to check that all plugin type ids from all prior calls
to `add_message_types()` in the same process are disjunct.
However, this is too strict for unit tests, which will spawn
a fresh actor system for every test in a fixture.
Instead we now only check for overlaps in plugin id spaces
that are present within a single call to `add_message_types()`.
=> Allow multiple independent calls to 'add_message_types()'

changelog/unreleased/changes/2033.md, libvast/CMakeLists.txt, libvast/src/arrow_table_slice_builder.cpp, libvast/src/experimental_table_slice_builder.cpp, libvast/src/format/arrow.cpp
Also removes multiple `#ifdef`s for handling older Arrow versions in specific ways.
https://docs.tenzir.com/vast/installation/build-from-source already mentions Arrow version 6.0.0, so no change in documentation required.
Make sure `ARROW_VERSION_` is only used in `version_command.cpp`.
=> Upgrade the minimum Arrow dependency to 6.0

cmake/VASTRegisterPlugin.cmake, libvast/CMakeLists.txt, libvast/test/CMakeLists.txt, vast/CMakeLists.txt
This library is required for binaries linked against VAST
that want to use native plugins.
=> Install native plugins static library

changelog/unreleased/bug-fixes/2046--schema-dirs-db-directory.md, libvast/src/schema.cpp, libvast/src/system/spawn_node.cpp
This is a two-fold fix that came up when reviewing a potential bug with @satta—thanks for the feedback!
=> Create intermediate dirs for db-directory and respect schema-dirs in bare mode

libvast/src/arrow_extension_types.cpp, libvast/src/experimental_table_slice.cpp, libvast/src/experimental_table_slice_builder.cpp, libvast/test/arrow_extension_types.cpp, libvast/test/experimental_table_slice.cpp, libvast/vast/arrow_extension_types.hpp
Create an extension type wrapping `arrow::StringType` to represent vast `pattern_type` in new arrow-based (experimental) table slices.
This one is very simple.
=> Use an extension type to represent VAST pattern types in Arrow

libvast/src/format/arrow.cpp, libvast/src/table_slice.cpp, libvast/src/transform.cpp, libvast/src/transform_steps/select.cpp, libvast/test/arrow_table_slice.cpp, libvast/test/experimental_table_slice.cpp, libvast/test/transform.cpp, libvast/vast/table_slice.hpp
This is a bug fix for transforms, which operated under the assumption that it was always safe to create a new table slice from a record batch. If, however, assumptions about the record batch memory layout change between Arrow table slice encoding versions, this will no longer work, requiring us to rebuild the slice to the latest encoding version before retrieving the underlying record batch.
This bug is not affecting the current release, so (1) we don't need to merge it before the release and (2) it doesn't need a changelog entry. It is preparatory for upcoming work.
=> Rebuild older Arrow table slices in `as_record_batch`

libvast/src/system/configuration.cpp
Improve the message when config file not found
Review this pull request commit-by-commit, or file-by-file.
=> Improve the message when config file not found

libvast/src/arrow_extension_types.cpp, libvast/src/experimental_table_slice.cpp, libvast/src/experimental_table_slice_builder.cpp, libvast/test/arrow_extension_types.cpp, libvast/vast/arrow_extension_types.hpp, vast/integration/reference/arrow-experimental/step_01.ref, vast/integration/reference/arrow-experimental/step_03.ref, vast/integration/reference/arrow-full-data-model-experimental/step_01.ref
Expose the VAST `address` type as an `ExtensionType` in Arrow (still wrapping the same fixed binary 16 representation under the hood).
Straight forward.
=> Use an extension type to represent VAST address types in Arrow

libvast/src/arrow_extension_types.cpp, libvast/src/experimental_table_slice.cpp, libvast/src/experimental_table_slice_builder.cpp, libvast/test/arrow_extension_types.cpp, libvast/vast/arrow_extension_types.hpp, vast/integration/reference/arrow-experimental/step_01.ref, vast/integration/reference/arrow-experimental/step_03.ref, vast/integration/reference/arrow-full-data-model-experimental/step_01.ref
Use an extension type to represent VAST subnet types in Arrow
A subnet will be represented as a struct, the first element, `length`, is
a `uint8` specifying the prefix length. The second element, `address`, is
an existing extension type wrapping a 16-byte fixed width type.
1. `arrow_extension_types.{hpp,cpp}`
2. `experimental_table_slice_builder.cpp`
3. `experimental_table_slice.cpp`
4. integration test fixtures / unit test coverage
=> Represent VAST subnet as arrow extension type

libvast/src/index/address_index.cpp, libvast/src/index/enumeration_index.cpp, libvast/src/index/list_index.cpp, libvast/src/index/string_index.cpp, libvast/src/index/subnet_index.cpp, libvast/src/value_index.cpp, libvast/test/index/address_index.cpp, libvast/test/index/hash_index.cpp, libvast/test/index/string_index.cpp, libvast/test/value_index.cpp, libvast/vast/coder.hpp, libvast/vast/fbs/value_index.fbs, libvast/vast/fwd.hpp, libvast/vast/index/address_index.hpp, libvast/vast/index/arithmetic_index.hpp, libvast/vast/index/enumeration_index.hpp, libvast/vast/index/hash_index.hpp, libvast/vast/index/list_index.hpp, libvast/vast/index/string_index.hpp, libvast/vast/index/subnet_index.hpp, libvast/vast/value_index.hpp
This adds FlatBuffers tables for `value_index` and related classes, and adds unit tests for them. A follow-up PR will integrate this into the partition FlatBuffers table.
I recommend going over this diff in a call together, as it's the most complicated of the bunch.
If you want to take a peek I recommend looking at the FlatBuffers table first, `value_index.hpp` second, and then going file-by-file through the remaining files.
Note that early on in design we thought we could get by without serializing `value_index::opts_`. That turned out to be a false assumption, as the concrete value index implementation needs to be created before we can dispatch to its unpack implementation. Otherwise, all possible instantiations need to be reflected in the FlatBuffers tables, which is just not feasible. …
=> Add FlatBuffers for `value_index`

libvast/src/experimental_table_slice_builder.cpp, libvast/src/type.cpp, libvast/test/experimental_table_slice.cpp, libvast/test/type.cpp, libvast/vast/experimental_table_slice_builder.hpp, libvast/vast/type.hpp, vast/integration/misc/schema/all-types.schema, vast/integration/reference/arrow-experimental/step_01.ref, vast/integration/reference/arrow-experimental/step_03.ref, vast/integration/reference/arrow-full-data-model-experimental/step_01.ref, vast/integration/reference/arrow-full-data-model/step_01.ref
Stores the VAST type name and attribute sets inside the Arrow schema and fields, making it possible to restore the full VAST type information from an Arrow schema.
Commit by commit.
=> VAST type names and attributes to Arrow mapping

libvast/src/arrow_table_slice.cpp, libvast/src/chunk.cpp, libvast/src/experimental_table_slice.cpp, libvast/src/table_slice.cpp, libvast/src/transform.cpp, libvast/vast/chunk.hpp, libvast/vast/fwd.hpp
This change fixes an issue that was rather hard to run into, and far from simple to debug once you did. Consider this example code:
```c++
table_slice A = get_table_slice();
auto B = as_record_batch(A);
auto C = B->Slice(...);
A = {};
B = {};
do_something_with(C); // crashes before this change
```
If C shares any memory with B, the above example crashed before this change. This happens because because only A and B shared ownership of A's underlying buffer, but the internal buffers of B did not. Any operation that created a new record batch C that sliced referenced B's internal buffers did thus break the structural lifetime-sharing with the table slice A.
This commit changes the lifetime-sharing setup and moves it from B to its internal buffers. This works seemlessly with the existing …
=> Fix record batch lifetime sharing

libvast/src/partition_synopsis.cpp, libvast/src/synopsis.cpp, libvast/src/system/active_partition.cpp, libvast/src/system/index.cpp, libvast/src/system/partition_transformer.cpp, libvast/src/system/passive_partition.cpp, libvast/src/uuid.cpp, libvast/test/partition_roundtrip.cpp, libvast/test/system/partition_transformer.cpp, libvast/vast/fbs/index.fbs, libvast/vast/fbs/partition.fbs, libvast/vast/fbs/partition_synopsis.fbs, libvast/vast/fbs/segment.fbs, libvast/vast/fbs/synopsis.fbs, libvast/vast/fbs/uuid.fbs, libvast/vast/fbs/value_index.fbs, libvast/vast/partition_synopsis.hpp, libvast/vast/synopsis.hpp, libvast/vast/system/passive_partition.hpp, libvast/vast/uuid.hpp, tools/lsvast/src/print_partition.cpp, tools/lsvast/src/util.hpp
This is a pure refactoring, no additional content provided. Essentially, this makes room for the next-gen partition FlatBuffers table. I've split this out to make the upcoming diff easier to review, because that then only has to (almost only) touch new code instead of doing this as well.
File-by-file. This should be trivial to review, as there are no functional changes. CI passing should suffice to verify correctness.
=> Make room for next-gen partition FlatBuffers table

.clangd
Trying to use `clangd` on the VAST project often results in an error message `please use -fcoroutines to enable coroutines` for many files. This is caused by the combination of using clang with the libstdc++ header files, which assume that this macro will be enabled when using coroutines. (clang sets a different macro to signal its coroutine support)
=> Add .clangd file for VAST

libvast/src/arrow_extension_types.cpp, libvast/src/experimental_table_slice.cpp, libvast/src/experimental_table_slice_builder.cpp, libvast/test/experimental_table_slice.cpp, libvast/test/format/arrow.cpp, libvast/vast/arrow_extension_types.hpp, libvast/vast/experimental_table_slice.hpp, libvast/vast/experimental_table_slice_builder.hpp, libvast/vast/fbs/table_slice.fbs, vast/integration/misc/schema/all-types.schema, vast/integration/reference/arrow-experimental/step_03.ref, vast/integration/reference/arrow-full-data-model-experimental/step_01.ref, vast/integration/reference/arrow-full-data-model/step_01.ref, vast/integration/vast_integration_suite.yaml
This establishes nested `arrow::RecordBatch` in table slices. With that in place, we don't need additional VAST type information in the table slice flatbuffer representation, so the last commit removes that field.
1. check the integration tests, make sure that the changes in the expectations reflect your intuition of what a nested structure would look like
2. read table slice builder changes
3. read table slice changes
=> Preserve nesting in arrow schema

changelog/unreleased/changes/2082--projection-transform-step, libvast/src/transform_steps/project.cpp, libvast/test/transform.cpp
Skip slices when no columns are matched in projection
=> Projection transform step should not skip slices where no columns are matched

libvast/src/table_slice.cpp, libvast/test/table_slice.cpp
Table slice filter and select operations keep the import timestamp
=> Table slice filter and select operations drop the import timestamp

.github/workflows/vast.yaml, Dockerfile, changelog/unreleased/features/2076--new-transforms.md, libvast/CMakeLists.txt, libvast/src/transform.cpp, libvast/src/transform_steps/rename.cpp, libvast/src/transform_steps/replace.cpp, libvast/vast/detail/vector_map.hpp, libvast/vast/plugin.hpp, nix/static-binary.sh, plugins/aggregate/CHANGELOG.md, plugins/aggregate/CMakeLists.txt, plugins/aggregate/README.md, plugins/aggregate/aggregate.cpp, plugins/aggregate/tests/aggregate.cpp
This implements a generic aggregation transform step plugin. See the attached README file for more information.
File-by-file. Go over the algorithm in a call with me. Test locally alongside compaction.
=> Implement a generic aggregation transform step

libvast/src/transform.cpp, libvast/test/transform.cpp, libvast/vast/transform.hpp
Modify the transform to check the layout name only once
=> Successive transform steps in a transform must not check the layout name

changelog/unreleased/bug-fixes/2086--slow-queries.md, libvast/src/system/meta_index.cpp, libvast/test/partition_roundtrip.cpp
The candidate check of the meta index must use the proper suffix matching algorithm of the type system rather than plain suffix matching on a flat qualified record field's name in order to avoid false positive candidate partitions. E.g., the field extractor "ts" resolved to partitions that contained layouts with a field names "orig_pkts" rather than just those that only contained a field exactly named "ts". This change fixes that behavior.
@tobim please verify that this fixes the issue you've described. The check itself is rather simple.
This does not need a changelog entry since it should only be a speed improvement for some queries, but does not change any behavior in a user-facing way.
=> Improve name lookup in meta index to reduce FPs

libvast/src/arrow_extension_types.cpp, libvast/src/arrow_table_slice.cpp, libvast/src/experimental_table_slice_builder.cpp, vast/integration/reference/arrow-full-data-model-experimental/step_01.ref
Flip the order of `length` and `address` fields in the arrow `subnet` representation.
n/a
=> Switch the order of columns in the subnet struct

libvast/src/experimental_table_slice_builder.cpp, libvast/vast/arrow_extension_types.hpp, plugins/aggregate/aggregate.cpp
This change massively improves the performance of the aggregate transform by getting rid of calls into Arrow Compute: While nice in theory, the overhead of calling into the kernels was >80% of the time spent aggregating in benchmarks with a median slice size of 3.
The new implementation does a lot of template trickery to allow for flexibly working with scalars directly, which allows for keeping an accumulator per column and bucket that can simply be updated for every slice in the record batch that fits into the same bucket.
@6yozo can you try this against your benchmarks?
=> Massively improve aggregate performance

changelog/unreleased/bug-fixes/2097--adjust-index-statistics-for-partition-transforms.md, changelog/unreleased/bug-fixes/2103--move-after-use.md, changelog/unreleased/features/2103--send-initial-dbstate.md, libvast/src/system/index.cpp, libvast/src/system/meta_index.cpp, libvast/test/system/eraser.cpp, libvast/test/system/query_processor.cpp, libvast/vast/fwd.hpp, libvast/vast/system/actors.hpp, libvast/vast/system/index.hpp, libvast/vast/system/meta_index.hpp
Give listeners the option to receive the whole prior db state to get a full overview of the current system.
Review this pull request commit-by-commit.
=> Send initial db state to new partition creation listeners

libvast/src/transform.cpp
These log messages are printed for every table slice that goes in or out of vast, bloating the logs.
=> Demote verbose log messages

changelog/unreleased/changes/2119--log-actors-with-id.md, libvast/vast/detail/logger_formatters.hpp
This changes the log output of `*self` from `name` to `name-id`.
For example `exporter` would now be formatted as `exporter-16` or `exporter-48`. This makes it easier to track the execution flow of specific instances of actors that exist multiple times in the same process.
=> Log actor names together with the unique actor ID

changelog/unreleased/changes/2123--partition-transforms.md, libvast/src/system/index.cpp, libvast/src/system/partition_transformer.cpp, libvast/test/system/partition_transformer.cpp, libvast/vast/system/actors.hpp, libvast/vast/system/partition_transformer.hpp
The case where a partition transform removed all input data
and returned an empty output (which is important when deleting
partitions) was not handled correctly, leading to potential
segfaults.
This was not caught by test because we lacked an end-to-end test for whole-partition erasure, with existing tests all mocking the partition transformer.
=> Correctly handle partition transforms without output

libvast/src/arrow_table_slice.cpp, libvast/src/arrow_table_slice_builder.cpp, libvast/src/experimental_table_slice_builder.cpp, libvast/src/expression_visitors.cpp, libvast/src/format/json.cpp, libvast/src/format/test.cpp, libvast/src/format/zeek.cpp, libvast/src/index/list_index.cpp, libvast/src/msgpack_table_slice.cpp, libvast/src/schema.cpp, libvast/src/system/infer_command.cpp, libvast/src/system/meta_index.cpp, libvast/src/type.cpp, libvast/src/value_index_factory.cpp, libvast/src/view.cpp, libvast/test/arrow_extension_types.cpp, libvast/test/experimental_table_slice.cpp, libvast/test/schema.cpp, libvast/test/system/meta_index.cpp, libvast/test/table_slice.cpp, libvast/test/transform.cpp, libvast/test/type.cpp, libvast/vast/arrow_extension_types.hpp, libvast/vast/concept/convertible/data.hpp, libvast/vast/fwd.hpp, libvast/vast/project.hpp, libvast/vast/type.hpp, plugins/aggregate/tests/aggregate.cpp, plugins/broker/src/zeek.cpp
The `none_type` is a blast from the past: It originated in the old type system that required an explicit variant member for signaling the empty type, which is not a requirement for the new type system. This will allow for removing `arrow::NullType` in VAST, which was—until now—required for symmetry in generic code like the custom sum type access for `arrow::Array` and `arrow::DataType`.
Note that type is still semi-regular—nothing changed about that. This change is purely internal.
I recommend going file-by-file. The changes in `project.hpp` are probably the most complicated, but other than that it should be easy to understand.
=> Remove the concrete `none_type`

CMakeLists.txt, vast/CMakeLists.txt, vast/services/launchd/com.tenzir.vast.plist.in, vast/services/rc.d/vast.in
Installing VAST on macOS now also installs a `com.tenzir.vast.plist` launchd job definition file for the current user.
Run locally on macOS.
```bash
cmake --build build
cmake --install build --prefix path/to/install/root
launchctl load -w ~/Library/LaunchAgents/com.tenzir.vast.plist
path/to/install/root/bin/vast status
launchctl unload -w ~/Library/LaunchAgents/com.tenzir.vast.plist
```
Not sure if this warrants a changelog entry, I mostly made this for personal use. Requested @mavam as reviewer since he runs macOS locally and this may come in handy for demos.
=> Add launchd support on macOS

changelog/unreleased/bug-fixes/2120--fix-explorer-shutdown.md, libvast/src/system/explore_command.cpp, libvast/src/system/explorer.cpp, libvast/src/system/sink.cpp, libvast/src/system/spawn_explorer.cpp, libvast/vast/detail/saturating_arithmetic.hpp, libvast/vast/system/explorer.hpp
This commit fixes 2 issues that prevented the exporter for the initial query from exiting.
* When the explorer received the requested number of results for the initial query it did not communicate this to the exporter, causing the latter to wait for a follow-up request indefinitely.
* When the `max-events-query * max-events-context` was lower than `max-events` the sink would wait for additional results but the `explorer` would only wait to get terminated.
Run an explore command on a database with more than 5 partitions and an initial query with a low selectivity.
=> Correctly terminate the explore command

libvast/src/segment_store.cpp, libvast/src/system/active_partition.cpp, libvast/src/system/archive.cpp, libvast/src/system/local_segment_store.cpp, libvast/src/system/passive_partition.cpp, libvast/src/system/query_supervisor.cpp, libvast/test/partition_roundtrip.cpp, libvast/test/segment_store.cpp, libvast/test/system/archive.cpp, libvast/test/system/local_segment_store.cpp, libvast/test/system/query_supervisor.cpp, libvast/vast/segment_store.hpp, libvast/vast/system/actors.hpp, libvast/vast/system/archive.hpp, libvast/vast/system/local_segment_store.hpp, libvast/vast/system/passive_partition.hpp
This changes the query handlers in the partition and store actors to return a hit count instead of a done atom.
* Verify that the additional test checks are sufficient.
=> Return a hit count from the partition query handler

changelog/unreleased/changes/2137--more-intuitive-makefile.md, cloud/aws/Makefile, cloud/aws/README.md, cloud/aws/fargate/outputs.tf, cloud/aws/lambda-handler.py, cloud/aws/outputs.tf
The first users of the deployment scripts noticed that the behavior of the task management commands (`run-task`, `execute-command`...) were somewhat counter-intuitive. This PR addresses that by:
- making the output of the make commands more explicit
- preventing users from creating duplicated VAST servers
- use more explicit working for the command names
- streamlining the behavior of `execute-command` by allowing the useage of a `CMD` variable, similar to `run-lambda`
- base64 encode the CMD variable of `run-lambda` to avoid escaping
The changes are mainly small improvements of the Makefile recipes. Appart from that:
- I added the base64 decoding of the CMD parameter in the Lambda python script to match the encoding that was added in the Makefile
- exported the task family from Terraform …
=> More intuitive Makefile

libvast/src/experimental_table_slice_builder.cpp, libvast/src/type.cpp, libvast/test/type.cpp, libvast/vast/type.hpp
This is best explained by the unit test that this PR adds. A bug that is rather hard to run into, but really annoying when you actually run into it.
I discovered this while working on #2130, and figured I'd fix this in a separate PR because this should get reviewed separately.
Look at the unit test first, then at the implementation. Users were theoretically able to run into this, but that'd require such a weird setup that I don't think we need to add a changelog entry.
=> Merge unnamed metadata layers in nested types

cloud/aws/.gitignore, cloud/aws/Makefile, cloud/aws/README.md, cloud/aws/fargate/ecs.tf, cloud/aws/fargate/efs/efs.tf, cloud/aws/fargate/efs/inputs.tf, cloud/aws/fargate/efs/outputs.tf, cloud/aws/fargate/inputs.tf, cloud/aws/fargate/locals.tf, cloud/aws/main.tf, cloud/aws/modules.tf
This adds EFS as an alternative storage for the VAST server, which enables persistence across Fargate task executions.
The entrypoint is a new terraform variable called vast_server_storage_type which enables choosing between EFS and ATTACHED storage (main.tf). The rest is the basic config to mount EFS on Fargate.
It might we worth checking whether the access restrictions to the access point are tight enough, but this is likely not critical.
=> Add option to use EFS as storage for the VAST server

changelog/unreleased/features/2133--status-grand-total.md, libvast/src/system/index.cpp, plugins/pcap/integration/reference/importing-vlan-traffic/step_01.ref, plugins/pcap/integration/reference/manual-1-node/step_03.ref, vast/integration/reference/server-zeek-conn-log/step_07.ref
Add a grand total event counter to the status output
=> Add a grand total event counter to the status output

VAST.spdx
A recent commit moved all VAST header files into a `include` subdirectory, but did not adapt our SBOM file accordingly. This makes the required changes to the latter.
n/t
=> Change paths in VAST.spdx after header file move

examples/plugins/transform/transform_plugin.cpp, libvast/include/vast/plugin.hpp, libvast/include/vast/transform_step.hpp, libvast/include/vast/transform_steps/delete.hpp, libvast/include/vast/transform_steps/hash.hpp, libvast/include/vast/transform_steps/project.hpp, libvast/include/vast/transform_steps/replace.hpp, libvast/include/vast/transform_steps/select.hpp, libvast/src/system/make_transforms.cpp, libvast/src/transform_step.cpp, libvast/src/transform_steps/count.cpp, libvast/src/transform_steps/delete.cpp, libvast/src/transform_steps/hash.cpp, libvast/src/transform_steps/identity.cpp, libvast/src/transform_steps/project.cpp, libvast/src/transform_steps/rename.cpp, libvast/src/transform_steps/replace.cpp, libvast/src/transform_steps/select.cpp, libvast/test/system/partition_transformer.cpp, libvast/test/transform.cpp, plugins/aggregate/aggregate.cpp, plugins/aggregate/tests/aggregate.cpp
Change transform step API to use vast::record
=> Change transform step API to use vast::record

changelog/unreleased/bug-fixes/2146-count-estimate.md, libvast/src/system/local_segment_store.cpp
This causes local segment stores of passive partitions to be loaded lazily, i.e., initialized only after the actor received its first message.
I was unable to reproduce the behavior from the removed comment locally. Please make sure this also holds true for other platforms.
It'd be great to measure this—if the impact is big, then we probably want to add a changelog entry.
=> Load stores lazily

.github/workflows/blocked.yaml
This is to avoid accidental merges during the feature freeze period. A small quality of life change for developers.
Test adding/removing the `blocked` label.
=> Fail CI if a PR is labeled `blocked`

libvast/include/vast/type.hpp, libvast/src/type.cpp, libvast/test/type.cpp
The new function `type::aliases` returns all aliases of a type, from outermost to innermost. Essentially, this iterates over the internal metadata structure of a type and yields a slice of FlatBuffers table for every named metadata layer.
This is useful when wanting to write code that accepts both a type and any of its aliases, e.g., as a key of a map for a custom index configuration, or when tracking occurences of types in the catalog.
Depends on #2130.
The provided unit test should explain the functionality easily. Review that first, then the implementation. @mavam, please verify that this would work for your needs in #2058.
=> Expose nested type aliases

changelog/unreleased/bug-fixes/2155--zeekify.md, libvast/src/detail/zeekify.cpp, libvast/test/format/zeek.cpp
This fixes the Zeekify function.
=> Use the timestamp type for inferred event timestamp fields in the Zeek reader

.cmake-format, cmake/VASTRegisterPlugin.cmake, vast/CMakeLists.txt
This changes plugin example configuration files to install to docdir rather than sharedir, which makes a lot more sense.
```
❯ tree path/to/install/share/doc
path/to/install/share/doc
└── vast
├── CHANGELOG.md
├── LICENSE
├── README.md
├── VAST.spdx
├── VERSIONING.md
├── examples
│   ├── plugin
│   │   └── example-analyzer
│   │       └── example-analyzer.yaml
│   └── vast.yaml
└── plugin
├── aggregate
│   ├── CHANGELOG.md
│   └── README.md
└── pcap
├── CHANGELOG.md
└── README.md
```
I don't think this needs a changelog entry. Review file-by-file. I think the changes should be pretty much self-explanatory.
=> Install example config files to docdir

cloud/aws/lambda-handler.py
Currently, the lambda function is not logging the output of the executed command. We need this logs for longer running jobs where the CLI might timeout. Also, we would like these logs to be written to Logwatch continuously instead of the end of the command execution.
We are limited to specific "threading" libraries on AWS lambda. `multiprocessing` for instance usually doesn't work with the pool and queue interfaces. This is why we use the basic `threading` module with a small adapter to get the return values from the threaded function.
Also modified `logging.basicConfig(level=logging.INFO)` because it seems that it is not working properly on Lambda because of some pre-initialization of the logger in the Lambda python runtime.
=> Add continuous logging in AWS Lambda

cloud/aws/.gitignore, cloud/aws/Makefile
There were two bugs that are being fixed here:
- execute-command was not robust, some `CMD` arguments with pipes where failing
- run-lambda had a 60s timeout that was re-triggering the lambda client unexpectedly
The encoding to avoid escaping issues for execute-command is quite convoluted. Open to simplification suggestions.
=> Fix CMD execution from lambda and fargate

cloud/aws/cluster.tf, cloud/aws/fargate/inputs.tf, cloud/aws/fargate/locals.tf, cloud/aws/fargate/outputs.tf, cloud/aws/modules.tf, cloud/aws/monitoring.tf, cloud/aws/vast-server.yaml
The goal of this PR is to have more visibility on what is happening within the VAST server that runs on Fargate. AWS offers a lot of tooling out of the box, provided that the logging stream responds to a few basic criteria:
- logs are more easily parser if they are JSON formatted
- the std output of the entrypoint is automatically forwarded to cloudwatch.
To comply with these requireement, we make all logs json and add metrics to the vast stdout log stream. 
We also setup a "metric filter" for rate metrics generated by VAST (could be extended for other metrics). This service parses the log stream and converts the entries into CloudWatch metrics that can be plotted into time series graphs.
Unfortunately, "metric filters" are currently not capable of generating metrics with a resolution …
=> Improve logging on the VAST Fargate server

changelog/unreleased/bug-fixes/2160.md, changelog/unreleased/features/2160--disk-monitor-blacklist.md, libvast/include/vast/query.hpp, libvast/include/vast/system/disk_monitor.hpp, libvast/include/vast/system/index.hpp, libvast/include/vast/system/query_supervisor.hpp, libvast/src/system/disk_monitor.cpp, libvast/src/system/index.cpp, libvast/src/system/query_supervisor.cpp
This PR contains a forward-port of the changes in #2160, and also adds a new "blacklist" to the disk monitor to avoid retrying partitions that previously failed with an error.
Review this pull request commit-by-commit.
=> Add blacklist to disk monitor

libvast_test/src/events.cpp, libvast_test/vast/test/fixtures/events.hpp
This rename is missing on master, so it does not compile
=> Rename schema to module in suricata tests

libvast/src/system/index.cpp, libvast/test/system/eraser.cpp, libvast/test/system/query_processor.cpp, libvast/vast/system/actors.hpp
A query gets removed from the list of 'pending' queries
in the index when the corresponding exporter actor goes
DOWN.
However, when the meta index lookup takes long enough the
exporter can time out before the query is added to 'pending'.
We did not check for this condition and thus would add
an already-dead query to 'pending', which of course would
never be able to progress afterwards.
=> Fix race condition with exporter timeouts

libvast/include/vast/concepts.hpp, libvast/include/vast/expression_visitors.hpp
- Add missing 'requires' clauses for some concepts
- Fix potential infinite recursion
Review this pull request commit-by-commit.
=> Fix some bugs detected by newer gcc versions

changelog/unreleased/features/2162--environment-variables-as-config.md, libvast/include/vast/detail/env.hpp, libvast/include/vast/system/configuration.hpp, libvast/src/detail/env.cpp, libvast/src/logger.cpp, libvast/src/module.cpp, libvast/src/plugin.cpp, libvast/src/system/configuration.cpp, libvast/src/system/index.cpp, libvast/src/systemd.cpp, libvast/test/system/configuration.cpp
This PR adds new functionality to use environment variables as alternate input to a YAML config file.
=> Support environment variables as alternate config mechanism

CMakeLists.txt, cmake/VASTChangelog.cmake.in, cmake/VASTRegisterPlugin.cmake, examples/plugins/analyzer/CMakeLists.txt, examples/plugins/transform/CMakeLists.txt, plugins/aggregate/CMakeLists.txt, plugins/broker/CMakeLists.txt, plugins/pcap/CMakeLists.txt, plugins/sigma/CMakeLists.txt
Just the usual maintenance stuff. No new warnings from changed policies in the newest CMake release.
n/t
=> Bump CMake policy opt-in version to 3.23

changelog/unreleased/breaking-changes/2178--console-verbosity.md, libvast/src/system/application.cpp
This PR adds a patch to fix the mapping of shorthand verbosity options (e.g., `-v`, `-q`) to the proper underlying option `--console-verbosity`.
I realized that renaming `--verbosity` to `--console-verbosity` is actually a breaking change. We may want to revert it here, or in my opinion preferably, deprecate `--verbosity` in favor of `--console-verbosity`. The reason for preferring the latter is that it is the vocabulary used in the configuration files, as well as clearer what this does.
Look at the one-line change. :eyes:
=> Fix CLI verbosity shorthands

.github/workflows/blocked.yaml
This additionally lets the check run on pull request synchronize events, which
should make the workflow more robust against the recent CI failures by simply
running it more often.
n/t
=> Improve robustness of the Check Labels CI workflow

vast/integration/vast_integration_suite.yaml
This adds a total of 6 seconds to the integration test runtime, but should make flaky runs in the CI less common.
I think we've all seen this fail on the spectacularly slow macOS machines in CI, so here's hoping this improves the situation.
=> Make `#import_time` integration test more robust

libvast/src/system/disk_monitor.cpp
This fixes a bug that would cause no partitions to be deleted by the disk monitor at as soon as the disk monitor had at least one blacklisted partition.
This does not need a changelog entry since the blacklist feature did not make it into a release yet.
=> Fix disk monitor partition blacklist

.github/workflows/style-check.yaml, .github/workflows/terraform.yaml
We need a way to ensure that the Terraform scripts to deploy VAST on AWS keep working throughout the product lifecycle. This PR adds a Github Action workflow to test some basic commands of the deployment CLI.
Note that:
- the CI run uses Terraform Cloud as a backend. This is safer than having the state locally in the Github action, because it might be hard to recover it if the CI job crashes.
- The run takes between 30 minutes and 1 hour to complete, mostly because tearing down some of the network resources is very slow on the AWS side.
- The CI run uses paying AWS resources. It tears down all the resources at the end of the job, so the costs of running it should be minimal (somewhere between $0.1 and $0.5). 
- It is worth noting that a failing job run might leave the resources running, …
=> Add CI job for terraform (trial 2)

changelog/unreleased/bug-fixes/2184--csv-real-opt-dot.md, libvast/src/format/csv.cpp, libvast/test/format/csv.cpp
This adds support for real values in the CSV parser that don't have a dot.
Originally reported by @tobim when he tried ingesting the NYC Taxi dataset. I've verified that this fixes the issue and added a minimal unit test.
Commit-by-commit. Should be straightforward.
=> Add support for reals in CSV without dot

cloud/aws/step-2/modules.tf
Currently the VAST process is forked and thus does not receive the SIGTERM from Fargate. We solve this by using `exec`
=> Fix sigterm not received by server on Fargate

libvast/include/vast/partition_synopsis.hpp, libvast/include/vast/system/eraser.hpp, libvast/src/partition_synopsis.cpp, libvast/src/system/catalog.cpp, libvast/test/system/catalog.cpp
After the recent meta index configuration changes, the partition synopsis size would always show as `0` because it only contains type synopses by default.
=> Also look at type synopses when computing partition synopsis size

.github/workflows/vast.yaml
The CI has been very bad at caching lately. Because the cache download speeds appear to have improved massively I'd like to experiment with just having two caches for the repository for all branches combined. Let's see if this works better.
I've also adjusted the cache compress level to a fixed value rather than the automatically chosen one.
Sanity-check, then monitor CI after merging for the next few days.
=> Experiment with a simpler cache action config

changelog/unreleased/changes/2193--client-command-threads.md, libvast/src/system/application.cpp, libvast/src/type.cpp, vast.yaml.example, vast/vast.cpp
Running many sub-commands in parallel can quickly result in very large numbers of threads being created. This can become a problem when these processes are in a restricted environment, and some start receiving "resource unavailable" errors. We can mitigate the problem by using only the minimum amount of workers for client commands, which don't need a these resources anyways.
=> Minimize the threadpool for client commands

changelog/unreleased/features/2186--aging-revival.md, libvast/CMakeLists.txt, libvast/include/vast/query.hpp, libvast/include/vast/system/actors.hpp, libvast/include/vast/system/eraser.hpp, libvast/include/vast/system/local_segment_store.hpp, libvast/include/vast/system/make_transforms.hpp, libvast/include/vast/transform.hpp, libvast/include/vast/transform_steps/filter.hpp, libvast/include/vast/transform_steps/select.hpp, libvast/src/system/archive.cpp, libvast/src/system/eraser.cpp, libvast/src/system/local_segment_store.cpp, libvast/src/system/make_transforms.cpp, libvast/src/system/spawn_eraser.cpp, libvast/src/transform.cpp, libvast/src/transform_steps/filter.cpp, libvast/src/transform_steps/select.cpp, libvast/test/system/catalog.cpp, libvast/test/system/eraser.cpp, libvast/test/system/transformer.cpp, libvast/test/transform.cpp, vast/integration/vast_integration_suite.yaml
Aging used to work only partially; deleting events from the archive but not from the index. It was deprecated and scheduled for removal in VAST 2.0.
With this PR we change the internals of the eraser, so aging now works as a functionality-reduced form of temporal compaction.
Some supporting commits add support for transforms that apply to every type, and a new "invert" option for the "select" transform step.
=> Implement support for transforms that apply to every type and use compaction for aging

libvast/src/format/reader_factory.cpp, libvast/src/system/make_source.cpp, vast/integration/vast_integration_suite.yaml
This fixes a segfault when the `vast import test` was invoked.
I'd argue this is not a user command so a changelog entry isn't warranted. The `test` source is also not mentioned in the online documentation.
=> Fix the import test subcommand

libvast/src/partition_synopsis.cpp, libvast/test/partition_synopsis.cpp
The new fine-grained index configuration is currently hardcoded for address and string types, but misrepresented the address type using the wrong type extractor. Let's use `:addr` over `:address` for consistency with the existing schema language and type extractor syntax.
Should be a trivial review. No changelog entry needed since this is a new feature.
=> Use `:addr` over `:address` for index config

libvast/src/query_queue.cpp
This fixes a severe bug that can deadlock the index actor. The problem surfaced with one of the integration tests which should be more reliable after this is done.
=> Fix infinite loop in query removal

libvast/include/vast/expression.hpp
Per discussion in Slack, this was missing.
n/t
=> Assert that expressions must not be empty connectives

changelog/unreleased/bug-fixes/2215--new-queries-after-stop.md, libvast/src/system/index.cpp, libvast/src/system/legacy_index.cpp, libvast/src/system/signal_monitor.cpp, libvast/src/system/sink_command.cpp
Before this change, the index continued accepting queries after initiating shutdown, which could lead to an infinite hang because queries were coming in faster than the index was able to process them.
Try locally:
```
T1> vast [--use-legacy-query-scheduler] start
T2> while true; do { sleep 0.5; vast export null & }; done
T3> vast stop
```
=> Stop accepting new queries after initiating shutdown

.github/workflows/style-check.yaml, .github/workflows/vast.yaml, .markdownlint.yaml, CHANGELOG.md, README.md, changelog/2020.04.29/features/827-844.md, changelog/2021.01.28/bug-fixes/1276.md, changelog/2021.01.28/changes/1257-1289.md, changelog/2021.02.24/features/1330-1376.md, changelog/2021.02.24/features/1368.md, changelog/2021.02.24/features/1382.md, changelog/2021.03.25/bug-fixes/1473-1485.md, changelog/2021.04.29/bug-fixes/1549.md, changelog/2021.07.29/features/1742.md, changelog/2021.08.26/bug-fixes/1862.md, changelog/2021.11.18/changes/1896.md, changelog/2021.12.16/features/1987-1992.md, changelog/legacy.md, cloud/aws/README.md, cmake/VASTChangelog.cmake.in, docs/README.md, docs/cli/vast-count.md, docs/cli/vast-export.md, plugins/broker/README.md, plugins/pcap/CHANGELOG.md
This adds `markdownlint` to our style check workflow.
As of opening this PR this just adds the workflow, which will fail. We need to actually fix the issues it reports before merging, or adapt our configuration accordingly.
n/t
=> Run `markdownlint` in CI

CHANGELOG.md, cmake/VASTChangelog.cmake.in
We need a newline above the links section, which was removed as part of the `markdownlint` PR recently that removed stray newlines at the end of files. This adds it back at the appropriate place: the changelog template.
n/t
=> Add missing newline to changelog template

changelog/unreleased/bug-fixes/2236--env-lists.md, cmake/VASTRegisterPlugin.cmake, libvast/src/module.cpp, libvast/src/system/configuration.cpp, libvast/src/system/start_command.cpp
Before this change, there were four different ways to handle environment variables for list options: Either through a `caf::config_option_set`, manually split at a colon or a comma, or through the `data` parser.
Now, all list options are handled consistently, and can be specified either as single values or as comma-separated lists that support proper escaping.
For the `VAST_SCHEMA_DIRS` and `VAST_PLUGIN_DIRS` option this is a subtle breaking change, as they no longer can be specified with a colon-seperator, and commas in the specified directories must now be escaped.
File-by-file. The logic changes in the C++ code should be rather simple to follow. The CMake changes escape `,` to `\\,` in paths.
Note that this is a bug-fix, as it aligns the actual behavior with the documented behavior.
=> Treat list options in env variables consistently

libvast/include/vast/defaults.hpp, libvast/src/system/application.cpp, libvast/src/system/spawn_index.cpp
A recent refactoring caused us to no longer read this option correctly, always using the default. This simplifies and fixes the option.
Double-check that the option now works correctly.
This should not need a changelog entry since the bug was newly introduced.
=> Fix `vast.active-partition-timeout` option

changelog/unreleased/changes/2233--duplicate-catalog-status.md, libvast/include/vast/system/index.hpp, libvast/include/vast/system/legacy_index.hpp, libvast/src/system/index.cpp, libvast/src/system/legacy_index.cpp, vast/integration/reference/server-zeek-conn-log/step_07.ref
The `catalog-bytes` was not updated for removals, so not correct anyways. The `catalog` section is also part of the root document, it doesn't add value to have a duplicate in the `index` section.
Trivial
=> Remove the "catalog" and "catalog-bytes" keys from the index status

.github/workflows/vast.yaml, CMakeLists.txt, Dockerfile, nix/vast/default.nix, tools/lsvast/CMakeLists.txt, vast/CMakeLists.txt
This makes the dynamic nix build work with man pages enabled. I also added the `VAST_ENABLE_MANPAGES` CMake option to as an explicit way to control man page generation of all enabled binaries.
Verify that the option works as expected. By default, the configuration step should fail if pandoc is not available.
=> Add a configuration option to toggle manpage generation

libvast/src/io/read.cpp, libvast/src/system/accountant.cpp, libvast/test/msgpack.cpp, libvast/test/system/filesystem.cpp
The `std::span` conversions work differently with clang 14; this PR fixes the incompatible usages.
=> Fix Clang 14 incompatibilities

changelog/unreleased/features/2247--lsvast-segments.md, changelog/unreleased/features/lsvast-segmetns--2247.md
An invalid changelog entry broke the autogenerated changelog. This fixes it.
=> Fix up changelog

changelog/unreleased/bug-fixes/2255--json-selector-non-string.md, libvast/include/vast/format/json/field_selector.hpp
This does not need to be a string.
The code change is rather straightforward. I'd recommend giving this a spin locally.
=> Lift selector field requirements for JSON import

libvast/src/system/configuration.cpp, vast/vast.cpp
Doesn't change anything about how things work, but effectively makes us not load files multiple times.
Don't think this needs a changelog entry since it's essentially only cleanup work.
=> Deduplicate config files before loading

changelog/unreleased/bug-fixes/2258--deeply-nested-record-type-transforms.md, libvast/include/vast/type.hpp, libvast/src/arrow_table_slice.cpp, libvast/src/type.cpp, plugins/summarize/CHANGELOG.md, plugins/summarize/summarize.cpp, plugins/summarize/tests/summarize.cpp
This fixes a segfault in the `summarize` transform step when its configuration caused all fields to be dropped from the table.
Run this on our testbed and check that we encountered that same issue there. The unit test this adds crashes without the additional changes to the plugin and to libvast.
=> Ignore types unrelated to the configuration in the summarize plugin

docs/package.json, docs/yarn.lock
This PR upgrades the docs dependencies to the latest versions by running `yarn upgrade`. It also bumps Docusaurus to the latest .29 beta release. AFAICT breaking changes do not concern us.
Make sure CI is still green.
=> Update docs dependencies to latest versions

docs/cli/vast-export-json.md, libvast/src/system/application.cpp
This just documents existing behavior.
Read the new help text.
=> Document JSON rendering behavior for durations

libvast/src/system/index.cpp
Currently, we do not erase partitions from the pending queries map. Instead, we just skip partitions that fail to load, i.e., because they were already erased. Because the fix is non-trivial this demotes the error message that really is no error in most cases.
n/t
=> Demote a noisy error message

changelog/unreleased/bug-fixes/2264--query-pruning.md, libvast/include/vast/detail/heterogenous_string_hash.hpp, libvast/include/vast/prune.hpp, libvast/include/vast/system/catalog.hpp, libvast/src/prune.cpp, libvast/src/system/catalog.cpp, libvast/test/system/query_pruning.cpp
Updates the catalog to rewrite queries like `http.hostname == "foo" || dns.rrname == "foo"` to `:string == "foo"` (as opposed to rewriting them to `http.hostname == "foo"`, as was done previously).
Additionally, introduces a set of field names that have separate configured bloom filters (presumably with a higher precision than the default one), which should not be touched by the pruner.
Review this pull request commit-by-commit.
=> Fix query pruning in the catalog

Dockerfile
`libarrow-dev` now points to Arrow 8.0, so we need to use `libarrow800` for the later stages of the image.
It's the same deal every other month. Nothing much to review. This fixes downstream usage of the image in the CI for our proprietary plugins.
=> Follow upstream Arrow changes in Docker image

docs/src/css/custom.css
Per the documentation: https://docusaurus.io/docs/markdown-features/assets#github-style-themed-images
Nothing to review, really; this is a carbon copy from the docs. We're not making use of it yet, but now we can use a single way of specifying dark-mode specific images for both GitHub and Docusaurus.
=> Make docs compatible with GitHub's dark-mode images

vast/CMakeLists.txt
This allows for using non-recursive CMake globbing expression in the `VAST_PLUGINS` CMake cache variable. E.g., configuring a VAST build using `cmake -B build -S . -D VAST_PLUGINS=plugins/*` will build all bundled open-source plugins alongside VAST.
Developer-facing only; not sure if we need to put this somewhere into the docs.
=> Support globs in CMake variable `VAST_PLUGINS`

libvast/test/module.cpp
Implement parser and unit tests for YAML types and Record Algebra.
The YAML Type parser is an internal component, not directly visible to the user; a later PR will integrate it into VAST.
=> Implement YAML Types

changelog/unreleased/bug-fixes/2289--plugins-options-order.md, libvast/src/system/configuration.cpp
We parsed the plugins, plugin-dirs, and schema-dirs options too early from the command line, leading to them being overruled by the configuration file. This aligns the behavior with the other options.
Try it locally.
=> Prefer CLI over config file for vast.plugins

changelog/unreleased/features/2268--compress-table-slice.md, docs/cli/vast-import.md, libvast/include/vast/defaults.hpp, libvast/src/arrow_table_slice_builder.cpp, vast.yaml.example
In a repeated test with 8'557'668 ingested Suricata events enabling the compression had a negligible effect on import speed (under 0.5%), but reduced the size of the archive and also the in-memory size of the loaded slices by roughly the same amount.
Here are the sizes of the database for three scenarios: Uncompressed, Zstd with the default compression level, and Zstd with the max compression level (50% slower on import, so irrelevant in the grand scheme of things).
```
❯ du -csh vast.db.uncompressed/{index,archive}
667M	vast.db.uncompressed/index
1.8G	vast.db.uncompressed/archive
2.5G	total
❯ du -csh vast.db.zstd.default/{index,archive}
668M	vast.db.zstd.default/index
426M	vast.db.zstd.default/archive
1.1G	total
❯ du -csh vast.db.zstd.max/{index,archive}
675M	vast.db.zstd.max/index
361M …
```
=> Compress in-memory slices with Zstd

changelog/unreleased/changes/2290--archive-deprecation.md, libvast/include/vast/system/active_partition.hpp, libvast/include/vast/system/index.hpp, libvast/src/system/active_partition.cpp, libvast/src/system/index.cpp, libvast/test/system/counter.cpp, vast/vast.cpp
This removes the possibility for users to configure the archive for writing new data, and instead automatically sets the segment-store as the default store backend. Reading from the archive is still supported.
The change is rather local in scope, so it should be covered by CI. I recommend reviewing file-by-file.
=> Deprecate the archive store-backend

schema/types/suricata.schema, vast/integration/reference/arrow/step_03.ref
The matcher plugin has long moved on to using concepts over custom attributes, so it doesn't make sense for it to leak into the main VAST repository anymore.
n/t
=> Remove unused #ioc attribute

docs/docs/get-started/quick-start-guide.md, docs/docusaurus.config.js, docs/static/CNAME
This PR makes vast.io the new project page.
Feel free to double-check the setup instructions at
https://docusaurus.io/docs/next/deployment#deploying-to-github-pages, or just
give it a go. We can't test this well prior to merging, unfortunately.
=> Enable vast.io

changelog/unreleased/features/2288--status-filter-by-component.md, libvast/src/system/application.cpp, libvast/src/system/node.cpp, vast/integration/reference/server-zeek-conn-log/step_08.ref, vast/integration/vast_integration_suite.yaml
Running `vast status` continues to get the status of all components, but positional arguments allow for restricting the output of the status command to just any given amount of components. E.g., `vast status importer index` will show just the status of the importer and index components.
Try it out! The code change itself is really simple.
Requesting @lava for review since we just recently talked about this.
=> Add optional status command filters

changelog/unreleased/bug-fixes/2295--partition-query-evaluation.md, libvast/include/vast/detail/partition_common.hpp
This fixes a rather annoying timing bug: We create new active partitions on demand, and immediately feed them events. If, however, a query arrives it may be scheduled before any of the events were added to the active partition, leading to it not having any indexers, which in turn leads to it not having a combined layout. The query evaluation wrongly assumed that every partition always had a combined layout, which caused a crash.
Follow the changed logic and verify that this was indeed an issue.
=> Fix crash in query evaluation for new partitions

libvast/include/vast/validate.hpp, libvast/src/validate.cpp, libvast/test/validate.cpp
Add a utility function to validate that a given `vast::data`
object conforms to the layout described by some record type.
This is being upstreamed from the closed-source compaction plugin.
=> Add function to validate configuration

libvast/src/system/application.cpp, libvast/src/system/spawn_sink.cpp, libvast/src/system/start_command.cpp, libvast/src/system/stop_command.cpp
When trying to start VAST with the '-N' option,
it complains with
$ vast -N start
!! parse_error: cannot start a local node
even though no error occurred during parsing, and the
term "local node" is never mentioned anywhere else.
=> Improved error message for invalid vast start

libvast/include/vast/system/active_partition.hpp, libvast/include/vast/uuid.hpp, libvast/native-plugins/segment_store.cpp, libvast/src/segment_store.cpp, libvast/src/system/active_partition.cpp, libvast/src/system/index.cpp, libvast/src/system/partition_transformer.cpp, libvast/src/system/passive_partition.cpp, libvast/test/system/partition_transformer.cpp
This encompasses 3 changes:
* UUIDs are consistently lowercase in log messages
* The local segment store appends the partition id to its actor ids. (This required an API change for store plugins).
* The partition transformer is logged with actor IDs now like all other actors.
=> Various logging improvements

libvast/include/vast/query.hpp, libvast/include/vast/query_options.hpp, libvast/include/vast/system/explorer.hpp, libvast/include/vast/table_slice.hpp, libvast/native-plugins/segment_store.cpp, libvast/src/system/archive.cpp, libvast/src/system/explorer.cpp, libvast/src/system/exporter.cpp, libvast/src/system/index.cpp, libvast/src/system/legacy_index.cpp, libvast/src/system/spawn_exporter.cpp, libvast/src/table_slice.cpp, libvast/test/partition_roundtrip.cpp, libvast/test/system/archive.cpp, libvast/test/system/catalog.cpp, libvast/test/system/index.cpp, libvast/test/system/local_segment_store.cpp, libvast/test/system/query_processor.cpp
The explore command can fire of multiple sub-queries after initial hits were produced for the given expression. When these sub-queries produce overlapping result sets we need to make sure that we don't present any events multiple times to the user. We achieve this by maintaining a set of already forwarded events in the explorer actor.
Before this change that set consisted of event ids, relying on the fact that those are globally unique. With this change the set to contain event hashes instead. That means we have to produce a hash of every result candidate, which is less efficient compared to the ids approach, but it shouldn't increase the delay noticeably for the case where we only produce a small number of intermediate results.
Changing the overall approach to wait for the initial query …
=> Deduplicate explore hits by hash instead of ID

flake.lock, flake.nix, nix/overlay.nix
This supports proper handling of `duration[ns]` in parquet, and is also
what's already in the official Arrow debian package repository..
=> Update Apache Arrow to 8.0

changelog/unreleased/bug-fixes/2305.md, libvast/src/system/configuration.cpp
Fix regression where setting `VAST_ENDPOINT=127.0.0.1:42000` wouldn't work because the parsing would fail.
It's a one-line change.
=> Fall back to string when parsing config options from environment

CMakeLists.txt
Fixes an oversight from #2313
Watch CI; it now renders correctly.
=> Fix rendering of compiler in build summary

libvast/include/vast/query_queue.hpp, libvast/src/query_queue.cpp, libvast/src/system/index.cpp
We don't remove the partition from the queue directly because the query API requires clients to keep track of the number of candidate partitions. Removing the partition from the queue would require us to update the partition counters in the query states but the client would go out of sync. That would require the index to deal with a few complicated corner cases.
A partition that failed to load but was not erased can now be logged with a proper warning thanks to this addition.
This isn't really testable in the unit test framework because the only observable effect is a log message. Just read the code changes and see if you can find flaws.
=> Mark erased partitions as such in the query queue

.github/workflows/terraform.yaml, cloud/aws/cli.py, cloud/aws/integration.py, cloud/aws/step-2/fargate/locals.tf
Closes #2187
To enable the repeated run of the tests, we needed a way to clean all the state, including EFS. To achieve this, I added the capability for the VAST fargate task to run arbitrary commands instead of just `vast start`. This way, by starting a task that simply runs `rm -rf /var/lib/vast/*` we can clean up EFS.
=> Add integration tests to vast-cloud CLI

plugins/parquet-store/CMakeLists.txt, plugins/parquet-store/cmake/FindLibevent.cmake
The parquet installation links to thrift, but fails to call `find_dependency` for it. Thrift itself tries to find libevent but doesn't install its own FindLibevent module.
=> Fix static binary build of the parquet-store plugin

.github/workflows/terraform.yaml, cloud/aws/cli.py, cloud/aws/docker/lambda-handler.py, cloud/aws/integration.py, cloud/aws/step-2/fargate/definition.tf, cloud/aws/step-2/fargate/ecs.tf, cloud/aws/step-2/fargate/iam.tf, cloud/aws/step-2/fargate/inputs.tf, cloud/aws/step-2/fargate/nlb.tf, cloud/aws/step-2/fargate/outputs.tf, cloud/aws/step-2/modules.tf, cloud/aws/step-2/network/main.tf, cloud/aws/step-2/network/new.tf, cloud/aws/step-2/network/peered.tf, cloud/aws/step-2/outputs.tf
This change wraps the VAST server task in a load balancer into a service and adds a network load balancer in front. This allows us to:
- expose the server on a pre-defined local IP, removing the need to dynamically resolve it through the Fargate API
- automatically restart the VAST server when it crashes
It requires a few extra resources to be initiated:
- in terms of code complexity, this is offset-ed by the fact we can remove all the logic for the dynamic IP resolution
- in terms of cost, the extra network load balancer adds a fix cost of ~$0.03 / hour to the stack
- Add a service and a load balancer resource in the `fargate` module
- The task now being wrapped in a service, we use `desiredCount` to start / stop the server instead of `start-task` / `stop-task` API calls (for stopping, …
=> Add Internal Load Balancer

.gitmodules, VAST.spdx, changelog/unreleased/bug-fixes/2332--integrate-fast_float.md, libvast/CMakeLists.txt, libvast/include/vast/concept/parseable/numeric/real.hpp, libvast/include/vast/concept/parseable/vast/data.hpp, libvast/include/vast/concept/parseable/vast/json.hpp, libvast/include/vast/concept/parseable/vast/time.hpp, libvast/src/bloom_filter_parameters.cpp, libvast/src/concept/parseable/numeric/real.cpp, libvast/src/format/csv.cpp, libvast/src/format/test.cpp, libvast/test/format/json.cpp, libvast/test/parseable.cpp, nix/fast_float/default.nix, nix/fast_float/source.json, nix/overlay.nix, nix/update.sh, nix/vast/default.nix, plugins/summarize/summarize.cpp, plugins/summarize/tests/summarize.cpp, web/docs/setup-vast/build.md
This replaces the internal float parsing code with the https://github.com/fastfloat/fast_float library. The main benefit is more correct parsing and support for scientific notation.
File by file. `parseable/numeric/real.{ch}pp` are probably the most interesting starting point. Be aware the `real` is semantically the old `real_opt_dot`. A parser that requires a dot does not exist in `fast_float` so we don't have that any more. The only code that really wanted this was the `data` parser, but a small modification was enough to change to the regular real parser.
=> Use fast_float to parse reals

changelog/unreleased/features/2334-KaanSK--pyvast-container.md, pyvast/README.md, pyvast/pyvast/vast.py
This PR adds support for utilizing containerized VAST instances with pyvast. 
-  `VAST()` checks binary on system first then fallbacks to container runtime.
-  Default container options `container={"runtime":"docker", "name":"vast"}` . Runtime can be specified like Docker, Podman etc.
-  Fixes a bug with having "--iter-" gets added to self.call_stack
Tests (test_vast.py) on local system passes.
=> Enable containerized VAST instances to be used in Python bindings

vast/CMakeLists.txt
On systems where `python` points to Python 2 by default,
using a mixture of calls to `python` and `python3` leads
to an inconsistent environment missing required
dependencies.
=> Use consistent python version for integration tests

web/docusaurus.config.js
This PR adds a search bar to the project site, powered by Algolia DocSearch.
My hunch is that this won't locally and has to merged first. I double-checked the params.
=> Configure DocSearch

libvast/include/vast/detail/assert.hpp
This fixes a rather obvious oversight in the recent PR #2330 that we did not catch in CI because that always builds with assertions.
n/t
=> Fix warnings for builds without assertions

changelog/unreleased/features/2302--index-metrics.md, libvast/include/vast/system/index.hpp, libvast/src/system/index.cpp
Add a new index metric for created active partitions, so it becomes possible to monitor how many new partitions are created over time.
=> Add index metric for created active partitions

libvast/CMakeLists.txt
Let's treat this like other potentially bundled dependencies.
Check the CI logs or build locally with the bundled fast_float.
=> Fix bundled fast_float location in build summary

changelog/unreleased/features/2346--indexer-compression.md, libvast/fbs/value_index.fbs, libvast/include/vast/chunk.hpp, libvast/src/chunk.cpp, libvast/src/system/active_partition.cpp, libvast/src/system/passive_partition.cpp, libvast/test/chunk.cpp
This works around a limitation of FlatBuffers: The maximum size of a FlatBuffers table is 2 GiB. Now while us running into this can be solved by moving indexers to separate files, we can get quite a ways by simply compressing the individual indexers.
In my initial measurements, I saw reductions between 2-10x in size of the partition FlatBuffers tables, with partitions containing mostly string indexes compressing best.
In limited testing, I was able to bump the max-partition-size from 4 Mi events to 64 Mi events without running into any size limitations, so with this change we should be good for a while, and can even consider bumping the size again.
Test with old and newly created databases. Rebuild an older one. Review the code file-by-file.
=> Compress serialized indexers

libvast/src/partition_synopsis.cpp
This fixes a potential crash when loading older partition synopses that I introduced recently. 
Please try this out @6yozo / @tobim. I don't think this needs a dedicated changelog entry, since this was a recent introduction.
=> Fix a crash when loading older partition synopses

changelog/unreleased/features/2360--catalog-partition-info.md, libvast/src/system/catalog.cpp
This adds information about all active partitions to the catalog's status output for `vast status --detailed`.
```bash
vast status --detailed catalog |
jq
```
```json5
{
"catalog": {
"memory-usage": 2431424,
"num-partitions": 9,
"partitions": [
{
"id": "080fc364-24dd-4903-8457-23dc97b1dd72",
"schema": "suricata.dns",
"num-events": 671418,
"import-time": {
"min": "2022-06-19T11:56:00.385162",
"max": "2022-06-19T11:56:00.385162"
}
},
{
"id": "3ece0263-4f7f-4291-ac33-291cf4d2c1f6",
"schema": "suricata.stats",
"num-events": 32,
"import-time": {
"min": "2022-06-19T11:56:00.385161",
"max": "2022-06-19T11:56:00.385161"
}
},
{
"id": "6ec1a045-9dd9-4ca7-87ad-056e0b7517fc",
"schema": "suricata.http",
"num-events": 457826,
"import-time": {
"min": "2022-06-19T11:56:00.385162",
"max": …
```
=> Render partition info in detailed catalog status

changelog/unreleased/features/2351--event-percentage.md, libvast/src/system/index.cpp, plugins/pcap/integration/reference/importing-vlan-traffic/step_04.ref, plugins/pcap/integration/reference/manual-1-node/step_03.ref, vast/integration/reference/heterogenous-jsonl-import/step_01.ref, vast/integration/reference/server-zeek-conn-log/step_06.ref, vast/integration/reference/server-zeek-conn-log/step_07.ref, vast/integration/reference/server-zeek-conn-log/step_08.ref
This allows for running things like this to get a visual representation of the event distribution:
```bash
vast status --detailed index | jq -r '.index.statistics.layouts | to_entries | sort_by(-.value.percentage) | .[] | "\(.key): \(.value.percentage * 100 | round / 100)%"'
```
```
suricata.flow: 80.74%
suricata.dns: 7.85%
suricata.http: 5.35%
suricata.fileinfo: 4.57%
suricata.tls: 1.04%
suricata.ftp: 0.41%
suricata.smtp: 0.04%
suricata.stats: 0%
```
This should be a trivial review.
=> Add percentage of total number of events to index status

cloud/aws/terraform/core-2/monitoring.tf
Cloudtrail dashboards are actually global, so stacks deployed in different regions will conflict
=> Add region to dash name to make it unique

libvast/include/vast/detail/algorithms.hpp, libvast/include/vast/query_queue.hpp, libvast/src/query_queue.cpp, libvast/test/detail/algorithms.cpp
These checks are motivated by some spurious warnings about failed partition loads during testing. The added assertions are intended to verify that the query queue works correctly.
A "static" review should suffice. The commits are orthogonal.
=> Add a few additional checks to the query queue

cloud/aws/terraform/cloudtrail/.terraform.lock.hcl, cloud/aws/terraform/common/s3notif/inputs.tf, cloud/aws/terraform/flowlogs/.terraform.lock.hcl
Currently, if the datasource bucket is not defined in `.env`, a default dummy value is used and hence the datasource that is in charge of checking that the bucket is valid fails. We propose using a provisioner instead.
=> Fix missing bucket when datasource not used

libvast/include/vast/system/partition_transformer.hpp, libvast/include/vast/transform.hpp, libvast/native-plugins/where.cpp, libvast/src/system/partition_transformer.cpp, libvast/src/transform.cpp
This causes non-aggregating transforms to properly persist import timestamps.
Don't think this needs a changelog entry. While this has affected compaction in theory, this was only really visible with the rebuild command, and that's a new addition for the current release.
For the review itself, I recommend going file-by-file. I tested this locally by looking at the detailed catalog status output before and after rebuilds.
=> Persist import timestamps during transforms

cloud/aws/cli/core.py, cloud/aws/cli/plugins/integration.py, cloud/aws/docker/lambda-handler.py
Currently:
- the commands that fail are not logged as errors in lambda
- the way stdout and stderr are multiplexed is hard to use in practice
We propose to raise an exception is the command returns a non 0 code and to return an object with both stdout and stderr from the lambda otherwise.
- Note that in the lambda, we log the stderr in real time to allow better monitoring of long running lambdas. To avoid duplication of those logs when an exception is raised, we silence it in a "hacky way" (temp redirect of the python sys.stdout)
- the web documentation wast not updated with the new output format of the lambda as this would be an excessive level of detail. The CLI help was updated instead.
=> Improve error management in Lambda

libvast/src/system/catalog.cpp, libvast/test/system/catalog.cpp
An attempt to improve the performance by doing a cheaper suffix match and moving the type check back.
=> Optimize catalog field extractor matching

cloud/aws/terraform/common/s3notif/inputs.tf
Yet another buck when checking the bucket region in the datasource, hotfixing this
Follow up to https://github.com/tenzir/vast/pull/2368
=> Fix bad command in bucket check provisioner

libvast/CMakeLists.txt, tools/vast-regenerate/main.cpp
Building plugins against an installed VAST was broken. This is the fix.
Try building a plugin against an installed VAST, see that it fails without this commit.
=> Don't export the indicators dependency

changelog/unreleased/bug-fixes/2376--write-failure-is-not-a-hard-error.md, libvast/src/system/index.cpp
The index used to quit if partitions fail to persist their data, this is not really necessary as VAST can still execute queries just fine when the disk is full.
This should be trivial enough to accept without manual testing.
=> The index shall not quit on write errors

libvast/include/vast/system/index.hpp, libvast/native-plugins/rebuild.cpp, libvast/src/system/index.cpp, web/docs/setup-vast/tune.md
Before this change, running at least two instances of rebuild, compaction, or aging caused compaction to break its internal state, rebuild to abort or even crash, and aging to crash the VAST server. This change makes it so we're a bit more lenient with overlapping partition transforms.
Don't think this needs a changelog entry, as this was not an issue before v2.1.
Review file-by-file, and definitely test locally.
=> Avoid clashes between rebuild, compaction, and aging

changelog/unreleased/bug-fixes/2324.md, libvast/include/vast/system/index.hpp, libvast/src/system/importer.cpp, libvast/src/system/index.cpp
This fix is intended to prevent the occasional hang when VAST is shut down.
The tests suggest that the fix is effective, but more tests might be needed. 
=> Prevent slices coming in when a shutdown is in progress

cloud/aws/terraform/core-2/fargate/definition.tf
When a Fargate task is stopped, the process inside receives a SIGTERM command with a grace period that defaults to 30 sec before receiving a SIGKILL. We propose here to increase that period to 120 (Fargate's maximum) to leave more time for VAST to flush its content.
=> Increase task shutdown timeout

.github/workflows/terraform.yaml, cloud/aws/cli/common.py, cloud/aws/cli/core.py, cloud/aws/cli/plugins/cloudtrail.py, cloud/aws/cli/plugins/flowlogs.py, cloud/aws/cli/plugins/integration.py, cloud/aws/cli/plugins/tfcloud.py, cloud/aws/cli/tfcloud.py, cloud/aws/terraform/README.md, cloud/aws/terraform/cloudtrail/terragrunt.hcl, cloud/aws/terraform/core-1/terragrunt.hcl, cloud/aws/terraform/core-2/terragrunt.hcl, cloud/aws/terraform/flowlogs/terragrunt.hcl, cloud/aws/terraform/terragrunt.cloud.hcl, cloud/aws/terraform/terragrunt.local.hcl
The goal is to simplify the switch between terraform backends and avoid the current file override hack we do in github actions. This goes into our general effort to make the scripts simpler and more flexible.
The heart of this PR is the change in the terragrunt step HCL files:
- ```find_in_parent_folders("terragrunt.${get_env("TF_STATE_BACKEND")}.hcl")```
This makes it possible to have multiple backend configs. The rest of this PR is refactoring to make it easier to use and have the right validators for each command.
=> Refactoring terraform backend switch

changelog/unreleased/bug-fixes/2390--plugin-env-vars.md, libvast/src/system/configuration.cpp, web/docs/setup-vast/configure.md
This is best explained on an example:
```
VAST_PLUGINS__EXAMPLE_ANALYZER__MAX_EVENTS=10 vast start
```
This will now correctly set the `max-events` option of the `example-analyzer` plugin to 10. This did not work correctly before, because it referred to the invalid option `vast.plugins.example-analyzer.max-events` rather than the valid option `plugins.example-analyzer.max-events`.
The example-analayzer plugin prints the max-events option from the description if you run `vast -v start`, so that makes it pretty easy to test this for correctness. Other than that I think this is really straightforward to review.
=> Support environment variables for plugin options

web/docs/setup-vast/README.md, web/docs/use-vast/detect/execute-sigma-rules.md, web/docs/use-vast/integrate/_category_.yml, web/docs/use-vast/integrate/python.md, web/docs/use-vast/integrate/threatbus/README.md, web/docs/use-vast/integrate/threatbus/configure.md, web/docs/use-vast/integrate/threatbus/deploy.md, web/docs/use-vast/integrate/threatbus/install.md, web/docs/use-vast/integrate/threatbus/understand/_category_.yaml, web/docs/use-vast/integrate/threatbus/understand/design-goals.md, web/docs/use-vast/integrate/threatbus/understand/plugins/README.md, web/docs/use-vast/integrate/threatbus/understand/plugins/apps/_category_.yml, web/docs/use-vast/integrate/threatbus/understand/plugins/apps/misp.md, web/docs/use-vast/integrate/threatbus/understand/plugins/apps/zeek.md, web/docs/use-vast/integrate/threatbus/understand/plugins/apps/zmq.md, web/docs/use-vast/integrate/threatbus/understand/plugins/backbones/_category_.yml, web/docs/use-vast/integrate/threatbus/understand/plugins/backbones/in-mem.md, web/docs/use-vast/integrate/threatbus/understand/plugins/backbones/rabbitmq.md, web/docs/use-vast/integrate/threatbus/understand/plugins/plugin-development.md, web/docs/use-vast/integrate/threatbus/understand/snapshotting.md, web/docs/use-vast/integrate/threatbus/understand/subscription-message-passing.md, web/docs/use-vast/integrate/threatbus/use.md
Port PyVAST and Threat Bus docs, plus a few fixes.
Commit-by-commit. You can skip the Threat Bus commit, which just integrates the existing content from https://docs.tenzir.com/threatbus/ under *Use VAST → Integrate → Threat Bus*.
=> Port PyVAST and Threat Bus docs

changelog/unreleased/bug-fixes/2394--improve-index-crash-recovery.md, libvast/native-plugins/rebuild.cpp, libvast/src/system/index.cpp
This causes VAST to restore from the available partition synopses on the filesystem instead of the partition synopses listed in the `index.bin` file, which can easily go out of sync during crashes.
This is a first change towards getting rid of the `index.bin` file entirely.
Review commit-by-commit. Test by terminating VAST ungracefully during a rebuild.
=> Improve index crash recovery

vast.yaml.example
The old values did not reflect the default, but the vast.yaml.example file advertises that all shown values are the default exactly. This changes the default fp-rate for string and address types to actually be the default.
Simple text review. Should not need a changelog entry.
=> Show default index config in vast.yaml.example

libvast/native-plugins/rebuild.cpp
Instead of showing `<num in progress>/<num total>` for the first rebuilding phase where we split heterogeneous partitions, we showed `<num left>/<num total>`, which was not very intuitive.
I observed this when running large-scale test on our testbed. Review should be trivial, and I don't think this deserves another rc.
=> Show progress in first rebuild phase correctly

cloud/aws/terraform/common/lambda/inputs.tf, cloud/aws/terraform/common/lambda/lambda.tf, cloud/aws/terraform/core-2/efs/efs.tf, cloud/aws/terraform/core-2/efs/inputs.tf, cloud/aws/terraform/core-2/efs/outputs.tf, cloud/aws/terraform/core-2/fargate/ecs.tf, cloud/aws/terraform/core-2/fargate/inputs.tf, cloud/aws/terraform/core-2/fargate/outputs.tf, cloud/aws/terraform/core-2/inputs.tf, cloud/aws/terraform/core-2/modules.tf, cloud/aws/terraform/core-2/securitygroups.tf
Currently the EFS module in included in the Fargate module, so each task will have its own filesystem. If we want the ability to re-use the file system, it's better if it is at the same level as the fargate module.
- moving the security groups into `securitygroups.tf` in the parent module to give a better view on network restrictions between services
- otherwise, mostly mechanical changes imposed by the refactoring
=> Refactor EFS module for better re-usability

libvast/src/system/posix_filesystem.cpp
Add file names to error messages produced by file system actor.
Just read the few lines.
=> Enrich error messages with file names

changelog/unreleased/bug-fixes/2393--render-reals-with-at-least-one-decimal-place.md, libvast/include/vast/concept/printable/vast/json.hpp, libvast/test/printable.cpp
Json export will always render reals with at least one decimal place
=> Render reals with at least one decimal place

web/docs/setup-vast/monitor.md
I noticed that our docs did not quite reflect reality here, at least not according to our testbed's dashboard.
Double-check that this is correct.
=> Fix duration unit in metrics docs

changelog/unreleased/features/2419--drop-by-schema.md, libvast/native-plugins/drop.cpp, libvast/test/transform.cpp, web/docs/understand-vast/query-language/operators/drop.md
The new `schemas` option allows for dropping entire schemas by name rather than
individual `fields` by extractors.
Go file-by-file. The change is trivial.
=> Support dropping entire schemas in `drop` operator

cloud/aws/cli/core.py, cloud/aws/terraform/core-2/modules.tf
After some debugging with @lava, we identified that this was [again](https://github.com/tenzir/vast/pull/2194) caused by SIGTERM not being propagated to the child process. 
Also increased overall restart timeout to factor in shutdown time.
=> SIGTERM sometimes hangs when running VAST within docker

web/docs/setup-vast/build.md
Improved documentation for compilation in release type.
Capturing lessons learned from https://tenzir-community.slack.com/archives/C022GBMDDG8/p1657888891586829
Is a changelog entry desired? Looking at the changelog I didn't see entries for documentation.
=> Add instructions for the Release build type

web/docs/setup-vast/deploy/README.md, web/docs/use-vast/run/README.md
This PR fixes a few docs typos.
:eyes: the diff.
=> Fix docs typos

web/blog/vast-v2.2/index.md
Fixing a typo in future blog post. Added marking import and export as keywords, as it's exactly the names used in the config.
N/A
=> Fix a typo in draft v2.2 blogpost

libvast/include/vast/segment_builder.hpp, libvast/src/segment_builder.cpp
Try not to create invalid flatbuffer segments.
Flatbuffers have a hard size limit of 2 GiB, and no API to detect if a builder has exceeded this size limit. (throwing an assertion instead) To avoid running into the assertion, we drop table slices that would 
Note that this is just a temporary hotfix to avoid running into the assertion, ideally of course we do not want to discard table slices since this loses data.
=> Drop table slices that exceed the flatbuffer limit

.github/workflows/terraform.yaml, cloud/aws/cli/common.py, cloud/aws/cli/core.py, cloud/aws/cli/main.py, cloud/aws/cli/plugins/README.md, cloud/aws/cli/plugins/cloudtrail.py, cloud/aws/cli/plugins/flowlogs.py, cloud/aws/cli/plugins/integration.py, cloud/aws/cli/plugins/pro.py, cloud/aws/cli/plugins/tfcloud.py, cloud/aws/cli/vast_invoke.py, cloud/aws/docker/cli.Dockerfile, cloud/aws/terraform/core-2/terragrunt.hcl, cloud/aws/vast-cloud
Currently, all the commands get a PTY by default. This is not necessary in general and tends to mess up the output (stderr is redirected to stdout).
This change also cleans up the output the the help command.
There are three aspects to this change:
- cleanup the output of the help command by subclassing `Program` in main.py (this is not directly linked to the PTY fix)
- create a thin layer around PyInvoke tasks to allow the `vast-cloud` entrypoint script to know if a TTY is required. This is implemented in `vast_invoke.py`
- update the `vast-cloud` entrypoint script to first check if TTY is required before running the actual command
- make all the tasks use this wrapper instead of the original PyInvokde `@task` decorator
- also cleaned up per namespace config `INVOKE_CONFIG` made …
=> Fix PTY for vast-cloud CLI

libvast/src/store.cpp, libvast/src/table_slice.cpp, libvast/test/feather.cpp, plugins/parquet/tests/parquet.cpp
This came up during feather testing: `count` yielded zero everywhere because vast failed to construct a valid `ids{}` set for invalid `offset`.
=> Fix `count_matching` when the calling store impl does not provide offset

web/src/pages/index.tsx
We didn't have one there, which looked weird when pasting the link to vast.io somewhere with rich link previews.
n/t
=> Set a description in the header for vast.io

libvast/include/vast/system/index.hpp, libvast/src/system/index.cpp
This change fixes a bug for repeated calls to `flush` or calls to flush with a very low `vast.active-partition-timeout` that was caused by us not resetting the entire state the index held for the active partition. Flushing twice with no additional events added in between should no longer cause errors, but rather return (almost) immediately and do nothing.
This should not need a changelog entry, as this was a newly introduced bug with `vast flush`, which was not part of any release yet.
Review-wise: Try to reproduce the bug locally before and after, and read the changes in the code.
=> Reset entire active partition state on decommission

CMakeLists.txt
Running `cmake -B .` (which errors) followed by `cmake -B build` used to yield errors not understandable to non-experts of CMake. Now, we error if remnants of an earlier attempted in-source build exist.
Try it!
=> Detect remnants of in-source builds

README.md
This pull request fixes the broken license hyperlink in README.md file. It was observed that there was a license file named COPYING and in time it was replaced with LICENSE.
=> Fix license hyperlink in README.md file to point LICENSE file

libvast/src/system/index.cpp
We recently changed `decommission_active_partition` to invalidate iterators, but forgot to adapt the `vast.active-partition-timeout` trigger for it accordingly, so that operatored on schemas that were already moved-from.
Change is straightforward, just a slight re-ordering to account for the possible iterator invalidation.
I don't think this needs a changelog entry, I introduced this myself just recently in #2445.
=> Fix use-after-move for the active-partition-timeout

libvast/include/vast/arrow_table_slice.hpp, libvast/native-plugins/summarize.cpp
This fixes a crash for aggregation functions with different input and output types, which just happened to work most of the time because the memory access into the storage of an Arrow ListArray works transparently, so we passed the unit tests. The additional assertions ensure that this works as expected. I double-checked that just adding the assertions causes the unit tests to fail.
Newly introduced bug with v2.2, so no changelog entry. I tested with this configuration locally:
```yaml
vast:
pipelines:
aggregate-flows:
- summarize:
group-by:
- timestamp
- src_ip
- dest_ip
- dest_port
- proto
time-resolution: 1 hour
aggregate:
timestamp_min:
min: timestamp
timestamp_max:
max: timestamp
flow.pkts_toserver: sum
flow.pkts_toclient: sum
flow.bytes_toserver: sum
flow.bytes_toclient: sum …
```
=> Fix crash for aggregation functions returning lists

libvast/include/vast/plugin.hpp, libvast/src/plugin.cpp
Native plugins are built-ins: They are always loaded by design. This change makes it so we don't error if users specify them explicitly in their configuration, but rather just silently ignore them. This makes the change of the summarize plugin to be a native plugin no longer a breaking configuration change.
Start VAST with `vast --plugins=summarize start` and observe that it starts instead of erroring. Review the code; it's a simple erase-remove.
=> Ignore native plugins when loaded explicitly

plugins/parquet/parquet.cpp
This aligns the default Parquet store row-group size with the other stores' batch sizes. This speeds up selective queries in the Parquet store, and generally causes our system to run a bit smoother, as CAF isn't well-suited to handle single messages whose serialized size is a few GB.
New feature, so no changelog entry. The change should be simple to review, as it's only adjusting a default value.
=> Align default row-group-size with other stores

libvast/native-plugins/summarize.cpp
Release 2.2 introduces changes to the summarize plugin config format.
VAST supports pre 2.2 config by internally formatting it to the new layout.
It was suggested to not unit test this code as it will be removed by the next release
=> Rewrite summarize configuration transparently

changelog/unreleased/bug-fixes/2466--rebuild-failure.md, libvast/native-plugins/rebuild.cpp
The rebuild command triggered an assertion on failure in debug modes when splitting old heterogeneous partitions, and it turned out that we did not properly handle the failure case. This changes the rebuild command to show an error if it did not succeed, detailing to the user what went wrong.
I've attached a small database with one heterogeneous partitions that can be used for reproducing the error. I did this by modifying the `apply` handler of the index to always return an error.
📁 [vast.db.archive.zip](https://github.com/tenzir/vast/files/9188473/vast.db.archive.zip)
=> Properly indicate failure in the rebuild command

libvast/native-plugins/count.cpp, libvast/test/summarize.cpp
This used to count *nil* values rather than values, i.e., do the opposite of what it was supposed to do. The fast-path for buckets with >= 2 contiguous rows worked correctly.
New code, so no changelog entry necessary.
=> Fix the slow path of the count aggregation function

libvast/src/chunk.cpp, libvast/test/chunk.cpp
Empty chunks did not survive a CAF serialization roundtrip before this.
Build the matcher plugin against this branch, and create an empty exact filter matcher and try to save it to disk. This used to crash, because an empty chunk did not properly arrive at the client process. Alternatively, trust the added unit test.
This was not user-facing in VAST itself, so I don't think this should get a changelog entry.
=> Fix serialization of empty chunks

changelog/unreleased/bug-fixes/2470--cli-missing-arg.md, libvast/src/system/configuration.cpp
Missing arguments for the `--plugins`, `--plugin-dirs`, and `--schema-dirs` options on the command line caused an assertion failure in debug mode and ran into undefined behavior in release mode. In practice, this was unlikely to cause a crash.
Run `vast --plugin-dirs= start` and observe the error.
=> Fix missing options sometimes not causing an error

.github/workflows/terraform.yaml, changelog/unreleased/changes/2435--clean-command.md, cloud/aws/cli/common.py, cloud/aws/cli/core.py
It happens that some terraform/terragrunt cache files are left behind after destroying a stack, which can impact subsequent deployments. We propose adding a `./vast-cloud init` command that runs init again on all modules. It also has a `--clean` option that removes the files from previous inits first.
- `init` on all modules has been made possible by adding `mock_outputs` on every terragrunt dependency
- Try running some `deploy` commands, then run `init` or `init --clean` and then continue with other operations
=> Add clean command

changelog/unreleased/bug-fixes/2479--native-plugins-expansion.md, libvast/src/plugin.cpp
During startup, VAST silently removes all native plugins
from the list of plugins to be loaded (they're part of
libvast and don't need to be loaded) and then expands
the special keywords "bundled" and "all" into a list of plugins.
However, this breaks if we have native plugins called "bundled"
or "all". Which we do indeed have. As a workaround, we switch
around the order of the two steps so expansion happens first.
=> Switch order of keyword expansion and native plugin removal

changelog/unreleased/changes/bug-fixes/2480--query-queue-erased-entries.md, libvast/include/vast/query_queue.hpp, libvast/src/query_queue.cpp, libvast/test/query_queue.cpp
Query queue tombstone mechanism wasn't working properly. The output items from the queue didn't inherit .erased attribute from the original queue entry.
=> Correctly mark query entries as erased

.github/workflows/vast.yaml
This builds upon the changes from #2488 with one further improvement that caused the CI to only upload the cache once per pull request, causing further commits to be unable to upload a cache.
Watch CI. Safe to merge after the release; it's purely an optimization of the caching fixes.
=> Force CI to re-upload cache for every commit

libvast/src/store.cpp
As per quick discussion in Slack, we agreed that this should not be printed on INFO, but rather DEBUG, as it can get noisy very quickly.
Probably not worth a changelog entry. Review should be trivial.
=> Demote a noisy log from Parquet/Feather stores

libvast/include/vast/arrow_table_slice.hpp, libvast/include/vast/arrow_table_slice_builder.hpp, libvast/include/vast/msgpack_table_slice.hpp, libvast/include/vast/table_slice.hpp, libvast/src/arrow_table_slice.cpp, libvast/src/arrow_table_slice_builder.cpp, libvast/src/msgpack_table_slice.cpp, libvast/src/segment_builder.cpp, libvast/src/table_slice.cpp, libvast/test/arrow_table_slice.cpp, libvast/test/table_slice.cpp
This reverts commit 6b4791e59e6e1a7df167fa5854f2d405492c8427 and implements fixes on top of it.
VAST's table slices currently have an IPC backing that we always create, even when we already have an in-memory record batch. This is very cheap for the Segment store, but unnecessarily expensive for the Feather and Parquet stores.
Follow the code changes file-by-file.
This should be covered by the tests.
Performance-wise, this makes a difference only when using Parquet/Feather stores or when using transforms extensively. I did not add a changelog entry, as we can much rather add the overall performance delta to the release notes.
=> Defer table slice IPC backing until serialization

libvast/src/system/exporter.cpp
The issued warning is actually a non-issue and just confuses users (including myself).
n/t
=> Demote logging message that doesn't indicate error

nix/static-binary.sh
This fixes the artifact name for out-of-tree static binary builds like we do in our proprietary plugin CI for the `nix/static-binary.sh` script, which now runs `git describe` with an explicit git directory set.
=> Fix artifact name for out-of-tree static binary builds

web/docs/understand-vast/data-model/taxonomies.md
This PR update our taxonomy docs to reflect the recent launch of the OCSF.
=> Update taxonomy docs after launch of OCSF

changelog/unreleased/features/2430--optional-partition-indexes.md, changelog/unreleased/features/2499--connection-timeout.md, libvast/include/vast/defaults.hpp, libvast/src/system/application.cpp, libvast/src/system/connect_to_node.cpp, vast.yaml.example
This adds a `--connection-timeout` option to VAST that is used for determining the timeout when connecting to a VAST server. The default stays at 10 seconds, but in some scnearios users may wish to increase the timeout. Setting it to a zero duration causes VAST to use an infinite timeout.
=> Make the connection timeout configurable

changelog/unreleased/bug-fixes/2500.md, libvast/src/system/index.cpp
Active partition actor will be inserted into unpersisted partitions on decomission.
While running export and import concurrently we received many warning messages because we couldn't receive any partition_actor that was part of a query.
=> Add active partition actor to unpersisted partitions on decomission

web/docs/setup-vast/build.md
There were some breaking changes introduced in libfmt9 which require some effort to work around; in the meantime we only support versions up to 8.
=> Update libfmt dependency requirements

libvast/include/vast/system/active_partition.hpp, libvast/src/system/active_partition.cpp, libvast/src/system/partition_transformer.cpp
Fixes a bug in which `vast rebuild --all` produced fully indexed partitions, because it was ignoring the index configuration.
We don't need a changelog entry because the feature (optional dense indexes) hasn't been there before so there's no actual change for the previous rebuild behavior.
=> Make partition transformer comply to the dense index configuration

web/docs/setup-vast/tune.md
It might be a bit misleading to represent `batch-size = 0` as a `tip`,
as it somewhat implies a recommendation, which I think it shouldn't
be.
=> Minor rewording of tuning table slices

changelog/unreleased/bug-fixes/2507--store-errors.md, libvast/src/system/passive_partition.cpp
Before this change, when a store failed to load users would get an opaque error message like this:
> [11:11:19.496] index-14 failed to evaluate query ac71d436-6b82-415d-8048-a0ba0ef0426e for partition e6522411-fa5c-4cf4-85ca-ff60fc1852ee: !! request_receiver_down
This can be easily reproduced by calling `self->quit(...)` in the `self->request(filesystem, ...).await(...)` handler that loads the store from a chunk in `vast/store.cpp`.
Instead, the partitions now display an error message like this and shut themselves down:
> [17:17:35.725] partition-5645eed0-d37e-457d-8b15-ea9d58498353-66 cannot reach its feather store and shuts down: <error from store>
This helps both the user understand what went wrong and developers in debugging.
=> Display store load failures to the user

changelog/unreleased/bug-fixes/2515--slow-rebuild.md, libvast/src/system/partition_transformer.cpp
This makes `vast rebuild start -j1` almost 10x faster on my machine given optimal batch sizes in the input data.
=> Speed up index building in partition transformer

libvast/src/index_config.cpp, libvast/test/index_config.cpp
This fixes the check whether an index configuration should apply for aliases types. I added a unit test to ensure this works as expected.
I don't think this needs a changelog entry—the feature this bug was in is new with v2.3.
=> Fix partition index config for aliased types

.github/workflows/vast.yaml
For unclear reasons this test has recently become extremely flaky,
causing failed CI runs on master. So we turn it off until further
investigation.
=> Don't build PCAP plugin on macOS

web/docs/setup-vast/README.md
This PR fixes a typo in setup instructions using bash script provided in vast.io documentation
- [N/A] All user-facing changes have changelog entries
- [N/A] User-facing changes are reflected on [vast.io](https://github.com/tenzir/vast/tree/master/web)
=> fix typo in setup instructions for PATH variable

libvast/native-plugins/rebuild.cpp
During heterogeneous partition rebuild the current_run_events was not calculated. It is now added under the proper if statement in the code 
=> Calculate rebuild current_run_events properly

changelog/unreleased/changes/2512--default-endpoint.md, libvast/include/vast/defaults.hpp, libvast/src/system/connect_to_node.cpp, libvast/src/system/start_command.cpp
Using 'localhost' empirically leads to hard-to-diagnose connection
errors depending on the order in which 'localhost' is resolved into
IPv4 and IPv6 addresses on a machine.
=> Change default endpoint to 127.0.0.1

libvast/include/vast/detail/spawn_container_source.hpp, libvast/include/vast/detail/spawn_generator_source.hpp, libvast/native-plugins/segment_store.cpp, libvast/src/system/accountant.cpp, libvast/src/system/datagram_source.cpp, libvast/src/system/exporter.cpp, libvast/src/system/import_command.cpp, libvast/src/system/source.cpp, libvast/test/system/datagram_source.cpp, libvast/test/system/importer.cpp, libvast/test/system/source.cpp, libvast/test/system/transformer.cpp
CAF 18.6 removed the make_sink, make_source and make_continuous_source methods.
The free functions i have replaced them with are supported both in CAF 17.6 and 18.6
=> Replace CAF 18.6 deprecated methods in favour of supported free function

web/yarn.lock
This fixes CVE-2022-36036. Fortunately this cannot trigger in our circumstances, given that users have no control to inject JavaScript into the Markdown rendering engine, which executes only at build time.
If CI runs through, we're good to go.
=> Upgrade mdx-mermaid to 1.3.2

libvast/include/vast/expression.hpp, libvast/src/defaults.cpp, libvast/src/detail/load_contents.cpp, libvast/src/detail/settings.cpp, libvast/src/system/make_source.cpp, libvast/src/system/node.cpp, libvast/src/system/pivot_command.cpp, libvast/src/system/type_registry.cpp, vast/vast.cpp
CAF 18.6 does compile time type checks for get_if, get, holds_alternative. It requires the passed type to be part of caf::config_value::types (none_t, integer, boolean, real, timespan, uri,
string, list, dictionary)
=> Adjust code to CAF 18.6 config/settings API restrictions

changelog/unreleased/changes/2471--memory-usage-metrics-for-catalog-and-index.md, libvast/include/vast/query_context.hpp, libvast/include/vast/query_queue.hpp, libvast/include/vast/system/index.hpp, libvast/src/query_queue.cpp, libvast/src/system/catalog.cpp, libvast/src/system/index.cpp, web/docs/setup-vast/monitor.md
As suggested by @tobim it would be beneficial to have some memory usage being reported in the telemetry.
The measurement is not precise but it can still help when looking for a memory leak
=> Add memory-usage to index and catalog telemetry reports

plugins/parquet/parquet.cpp
size_t is not an alias for uint64_t on macOS. The only safe assumption to make is that they have the same size, but they are not required to be the same type by the standard.
Should be trivial to review. This is a regression we recently introduced in #2528.
=> Fix Parquet plugin build on macOS

.github/workflows/vast.yaml
This fixes a recently introduced regression that caused us not to upload artifacts generated in the macOS CI job that builds VAST, which are valuable for debugging in case something goes wrong in CI.
This was just recently introduced in #2513, which made setting the `CPACK_PACKAGE_FILE_NAME` variable required.
=> Set package name for macOS CI job

changelog/unreleased/bug-fixes/2568--shutdown-grace-period-removal.md, libvast/include/vast/system/node.hpp, libvast/include/vast/system/shutdown.hpp, libvast/include/vast/system/terminate.hpp, libvast/include/vast/system/terminator.hpp, libvast/src/system/application.cpp, libvast/src/system/node.cpp, libvast/src/system/shutdown.cpp, libvast/src/system/spawn_node.cpp, libvast/src/system/terminator.cpp, libvast_test/src/node.cpp, vast.yaml.example, web/docs/setup-vast/tune.md
This removes the `vast.shutdown-grace-period` functionality and its underlying mechanism. This has two reasons:
1. The mechanism was broken, and in case of yet unpersisted data taking longer than the grace period to persist on shutdown caused both data loss and an infinite hang.
2. It is the purpose of a service manager to issue hard kills to hanging process, not of the hanging process itself.
Ultimately we decided that the internal hard kill causes more issues than it helps solves, so now the new grace period is infinite: VAST simply waits for as long as it takes to shut down properly.
=> Remove the shutdown grace period

.github/workflows/vast.yaml
We recently disabled testing for the plugins in the macOS CI due to test flakiness; that flakiness, however, we were not able to reliably reproduce after a few days. This re-enables the building of plugins in the macOS CI.
The plan is to run the CI multiple times before merging this, just so we can be somewhat sure that the issue no longer exists.
=> Re-enable plugin tests in macOS CI

cmake/VASTPackage.cmake
I verified in the CPack docs and source code that `DEB` is correct. https://cmake.org/cmake/help/latest/module/CPackComponent.html#variable:CPACK_%3CGENNAME%3E_COMPONENT_INSTALL
-> Not necessary, as the packaging feature was introduced after the most recent release.
-> This level of detail is not documented, and the new behavior matches user expectations.
=> Fix CPack Deb component based packages

Dockerfile
This was accidentally enabled in 7a6d9f3f68, so it was a newly introduced regression in v2.3 over v2.2 that massively increased the size of the Dockerfile.
=> Disable building unit tests in Dockerfile

libvast/test/feather.cpp
Fixture scope names should be distinct.
This is a trivial cosmetic change.
=> Fix name of a feather fixture that was copy-pasted

.github/workflows/changelog-override.md, .github/workflows/vast.yaml, CMakeLists.txt, Dockerfile, changelog/unreleased/changes/2582--bump-cmake-to-319.md, cmake/VASTChangelog.cmake.in, cmake/VASTRegisterPlugin.cmake, cmake/VASTVersion.cmake, cmake/VASTVersionFallback.cmake, examples/plugins/analyzer/CMakeLists.txt, examples/plugins/pipeline_operator/CMakeLists.txt, nix/overlay.nix, nix/vast/default.nix, plugins/broker/CMakeLists.txt, plugins/parquet/CMakeLists.txt, plugins/pcap/CMakeLists.txt, plugins/sigma/CMakeLists.txt, scripts/prepare-release, version.json, web/docs/setup-vast/build.md
CMake is not the only tool that is interested in the version string, so we move it into a format that is widely supported.
Note that the value of `vast-version-fallback` is not prefixed with 'v', because it is easier to add where needed than to remove when undesired.
In order to allow this change, the minimum required CMake version is bumped from 3.18 to 3.19.
=> Move the version string into a central JSON file

changelog/unreleased/bug-fixes/2515--improve-startup-resilience.md, libvast/src/system/index.cpp
If something is wrong with a partition we now skip it instead of preventing VAST from starting up.
=> Don't abort startup if individual partitions fail to load

.github/workflows/style-check.yaml, libvast/include/vast/detail/weak_handle.hpp, libvast/include/vast/system/posix_filesystem.hpp, libvast/src/system/node.cpp, libvast/src/system/posix_filesystem.cpp, vast/integration/vast_integration_suite.yaml
This fixes a regression I introduced myself last week when adding metrics to the filesystem actor: A cycle between the accountant and the filesystem that caused an infinite hang on shutdown when metrics are enabled. We didn't catch this in integration tests because those, well, run with metrics disabled.
Because I didn't want to add a `actor_cast<T>(some_weak_actor_ptr)` to our code base in a seemingly random place, I added a typed abstraction for weak actor handles to our code base, which feels like a thing that we should contribute upstream as `typed_actor<...>::weak_handle` or similar.
This shouldn't need a changelog entry since this regression was introduced only after the last releaase.
For testing, it's easy enough to see it in action by running this command, which shuts down as of …
=> Fix shutdown hang in the filesystem actor

.github/workflows/vast.yaml, python/README.md, python/poetry.lock, python/pyproject.toml, python/tests/test_utils_arrow.py, python/vast/utils/arrow.py, python/vast/vast/cli.py, python/vast/vast/vast.py
This PR integrates all features from #2518.
All functionality is covered by unit tests. Please check them.
=> Implement VAST extension types in Python

python/tests/test_utils_arrow.py, python/vast/utils/arrow.py
This PR fixes the failing `EnumType` unit tests.
Turns out that `pa.array()` with `type=T` where `T` is a dictionary type is not sufficient to use the proper type for the dictionary indices. We had `uint8` in our type, but unless we explicitly go through `pa.DictionaryArray.from_arrays`, we will get a `int8`. This type clash was the issue in the past.
=> Make enum extension types work

nix/vast/default.nix
The recent version fallback refactoring exposed an issue in the Nix packaging the made it possible to prefix the version with two 'v's. We need to make sure to strip the leading 'v' for the Nix package version, then we can re-prepend it when passing the number into the build scaffold.
This regression was introduced after the most recent release, so I don't think we need to update the changelog and docs.
=> Fix version passing for the static binary

libvast/native-plugins/rest_endpoints/status.cpp, plugins/web/src/server_command.cpp, web/openapi/openapi.yaml
Additionally, this fixes a use-after-move bug that caused the status endpoint to ignore all passed parameters.
=> Add 'verbosity' parameter to status endpoint

changelog/unreleased/bug-fixes/2609--fix-cannot-connect-msg.md, libvast/src/system/connect_to_node.cpp
It erroneously contained `host:host` instead of `host:port`.
=> Fix a connection error message

libvast_test/src/main.cpp
caf::message_builder::extract_opts method was remove in CAF 0.18.
We can apply the same approach as in configuration.cpp to use caf::config_option_set in order to parse and process the arguments passed into vast-test.
=> Use CAF 0.18 approach for argument parsing in unit tests main function

plugins/web/src/plugin.cpp, plugins/web/src/server_command.cpp
Before this change, it was impossible to set options for the web plugin using environment variables, and in the configuration file they had to be specified in the wrong category.
This change fixes that, enabling use of `VAST_PLUGINS__WEB__MODE=dev vast web server` and similar uses, which comes in handy for everything Docker-related.
=> Enable use of env variables for web plugin options

libvast/include/vast/detail/inspection_common.hpp, libvast/include/vast/detail/settings.hpp, libvast/src/module.cpp, libvast/src/plugin.cpp, libvast/src/system/make_pipelines.cpp, libvast/test/detail/inspection_common.cpp, libvast/test/detail/settings.cpp
CAF 0.18.6 introduces new inspector API (https://actor-framework.readthedocs.io/en/stable/TypeInspection.html)
The common_inspection file introduces classes that allow the VAST inspectors to abide to this API.
The real example of the new inspector API can be seen in CAF repo (https://github.com/actor-framework/actor-framework/blob/cf0af7de5c4bbd93fc5e25e220a03cacc4c98953/libcaf_core/caf/uri.hpp#L242)
In the 0.18.6 we cannot also use caf::get_if<std::vector<std::string>>. Every caf::get_if/get_as etc has a static_check.
The passed T into get_if<T> must be a config value_type. The only std::vector that is a config value type is:
using list = std::vector<config_value>;
This Is why i have created a helper function for extracting std::vector<T>
Review this pull request by ensuring the …
=> Common helper class implementation for new inspector api and common function for extracting std::vector from configs 

cmake/VASTRegisterPlugin.cmake
I just noticed locally when running `ctest --test-dir build -j8` that there was a race for building libvast, which happens because we have test fixtures for vast-test and the individual plugin unit test binaries that ensure that we build the plugins. However, there was a race between the fixture setup the individual plugin unit test binaries in case libvast was not yet built. This change fixes that by making the dependency more explicit, and ensuring that the fixture for the vast-test binary has priority when running CTest.
=> Fix race in plugin tests for CTest with -j2 or higher

libvast/include/vast/system/actors.hpp, libvast/include/vast/system/terminate.hpp, libvast/include/vast/system/terminator.hpp, libvast/src/system/terminator.cpp
Terminator and it's response promise could die before the response was received. This caused actors to not shutdown properly.
The call to terminate will now capture terminator into response handlers so it can never die before it responds.
=> Fix terminator lifetime issue

libvast/native-plugins/rebuild.cpp
Scenario: We have the partitions A and B, and automatic rebuilding merges them into the partition AB. All except for the last batch in AB are perfectly sized.
Now comes partition C with undersized batches. If the rebuilder operates in the order C -> AB it is more likely to have to rebatch than if it were to operate in the order AB -> C, because the beginning of AB is already guaranteed not to require rebatching.
This change makes it so we always rebuild the selected partitions for a given rebuild run in time ascending order, while keeping the selection order for rebuilding to be time descending.
=> Make it less likely for rebuild to require rebatching

.github/workflows/terraform.yaml, cloud/aws/cli/core.py, cloud/aws/cli/main.py, cloud/aws/cli/plugins/tests.py, cloud/aws/cli/vast.py, cloud/aws/terraform/core-2/inputs.tf, cloud/aws/terraform/core-2/modules.tf, cloud/aws/terraform/core-2/outputs.tf, cloud/aws/terraform/core-2/terragrunt.hcl, web/docs/setup/deploy/aws.md, web/docs/use/detect/cloud-matchers.md
Some of the commands where named at the creation of the VAST Cloud tooling, and the scope has changed quite a bit since then.  This PR operates some long needed command renaming to provide a more streamlined UX. This is okay because there is a disclaimer in the documentation indicating that these APIs are subject to change.
=> Revamp Cloud commands

cloud/aws/cli/common.py, cloud/aws/cli/plugins/tests.py, cloud/aws/resources/configs/misp/502.html
Currently, the start and stop yield as soon as the task is created. We should rather wait for the task to enter the expected status.
=> Poll starting and stopping Cloud task status

vast/vast.cpp
Print all dynamically loaded plugins as INFO-level message during startup.
Preview:
```
$ ./bin/vast --plugins=bundled start
[13:53:28.446] loaded plugin: /home/benno/src/vast/master/build/lib/vast/plugins/libvast-plugin-web.so
[13:53:28.458] VAST (v2.3.0-513-gf52482f0c1) is listening on 127.0.0.1:42000
[13:53:28.524] index-12 finished initializing and is ready to accept queries
```
=> Print loaded plugins on startup

changelog/unreleased/bug-fixes/2624--transform-oversized-partition.md, libvast/src/system/index.cpp
Previously calls to the `apply` handler of the index would hang
indefinitely, since the promise never got delivered.
=> Abort the response promise if running into oversized partitions

libvast/src/format/test.cpp
The result of instantiating `uniform_int_distribution<T>` is undefined unless the template argument is one of short, int, long, long long, unsigned short, unsigned int, unsigned long, or unsigned long long.
Newer versions of clang seem to have a static assert that checks the template argument.
=> Use proper types for uniform_int_distribution

plugins/web/include/web/configuration.hpp, plugins/web/include/web/restinio_response.hpp, plugins/web/src/configuration.cpp, plugins/web/src/restinio_response.cpp, plugins/web/src/server_command.cpp
A minimal change to the web plugin to allow development against separate API and frontend servers. The mechanism may be reused to insert other relevant headers in the future.
For production usage we probably need to at least make the allowed origins user-configurable, but it's not clear yet when this will be needed since we also expect to be serving the frontend and the API from the same origin eventually.
=> Allow cross-origin requests in dev mode

Dockerfile
For the python tooling, we need Pyhton 3.10, but bullseye packages an older version. We update the docker image using `python:3.10-slim-bullseye` as base image.
=> Update the python version in the VAST docker image

changelog/unreleased/bug-fixes/2635--fix-blocking-uds-metrics.md, libvast/include/vast/detail/posix.hpp, libvast/src/detail/posix.cpp, libvast/src/detail/terminal.cpp, libvast/src/system/accountant.cpp, libvast/src/system/node.cpp
We now wait for up to one second while trying to write metrics, but only if the previous line was not dropped.
Additionally, the file descriptor used for sending is put into non-blocking mode to avoid endless blocking in case the listening socket hangs up but isn't cleaned up fully.
=> Add a timeout to the UDS metric sink

plugins/web/aux/CMakeLists.txt
Old:
```
CMake Error at plugins/web/aux/CMakeLists.txt:20 (add_custom_command):
add_custom_command Wrong syntax.  A TARGET or OUTPUT must be specified.
```
New:
```
CMake Error at plugins/web/aux/CMakeLists.txt:4 (message):
submodule
'/Users/dominiklohmann/Desktop/vast/git-submodules-error/plugins/web/aux/restinio'
is not initialized
```
Probably doesn't need a changelog entry, this is purely dev-facing.
=> Improve error message for missing restinio submodule

libvast/src/concept/parseable/vast/expression.cpp, libvast/test/expression.cpp
Before this change to the expression parser the newly added test failed because the expression parser required that it ended at the end of parseable input.
Should not need a changelog entry, as this was not user-facing so far. It's relevant for being able to implement pipelines, though.
=> Make the expression parser composable

.github/workflows/analysis.yaml, .github/workflows/vast.yaml
VAST (fow now) does not build against Arrow 10.0.0, which was just released, but doesn't even have release notes yet.
=> Pin Arrow to 9.0.0 in CI

.github/dependabot.yml
This enables Dependabot for version bumping for Python packages in the `python` and `web` directories.
=> Enable Dependabot for Python

libvast/include/vast/error.hpp, libvast/src/detail/posix.cpp, libvast/src/error.cpp, libvast/src/system/accountant.cpp, libvast/src/system/posix_filesystem.cpp
* Fix the success condition for `sendto`
* Instead of shutting down on anything but timeouts we now just keep on trying to write to the socket.
This can be tested with the following `vast.yaml`:
```
vast:
enable-metrics: true
metrics:
uds-sink:
enable: true
path: /tmp/vast-metrics.sock
type: datagram
```
Start a vast node with this and then start and stop socat with this command:
```bash
socat  'UNIX-RECV:/tmp/vast-metrics.sock' -
```
`socat` should print data to stdout every time it is active.
=> Fix UDS datagram metrics reporting

web/docusaurus.config.js
This PR brings back the star-us-on-github CTA on the website.
⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️⭐️
Review this pull request by building the site locally and looking at the announcement bar.
=> Bring back announcement bar

vast.yaml.example, vast/vast.cpp
The option hasn't existed since VAST v2.1, which was quite some time ago.
=> Remove mentions of `vast.use-legacy-query-scheduler` option

libvast/include/vast/bloom_filter_synopsis.hpp, libvast/include/vast/bool_synopsis.hpp, libvast/include/vast/buffered_synopsis.hpp, libvast/include/vast/min_max_synopsis.hpp, libvast/include/vast/synopsis.hpp, libvast/src/bool_synopsis.cpp, libvast/src/synopsis.cpp
This is the cleanup of synopsis hierarchy that i've done for CAF 0.18.6 update.
Instead of creating virtual function for each inspector that has the same implementation we can create one using "double dispatch"
deserialize(vast::detail::legacy_deserializer& will be gone with the main PR as all inspect function will return bool 
The inspect(legacy_deserializer, synopsis_ptr) will also be gone as the common template inspect function will suffice 
=> Refactor synopsis inspection API for easier maintenance

.github/workflows/analysis.yaml, .github/workflows/vast.yaml, Dockerfile, changelog/unreleased/changes/2685--update-arrow-to-10.0.0.md, flake.lock, flake.nix, libvast/CMakeLists.txt, libvast/include/vast/arrow_compat.hpp, libvast/src/arrow_table_slice_builder.cpp, libvast/src/chunk.cpp, libvast/src/type.cpp, nix/overlay.nix, plugins/parquet/CMakeLists.txt, plugins/parquet/parquet.cpp, vast/integration/requirements.txt, web/docs/setup/build.md
Support building VAST against Arrow 10.0.0.
=> Arrow 10.0.0 support

.github/workflows/vast.yaml
This PR adds support for running the integration tests on the nix-built static binary.
There is already an `installCheckPhase` test for the same. However, that fails in the static build as `systemdMinimal` is a dependency (which is broken for pkgsStatic platform on nixpkgs right now).
The approach in this PR is to just extract the binary and run the tests in a nix shell with the python etc. dependencies. This makes the integration tests decoupled from the build process, and as we need to just test the resulting binary, IMO, this approach is fine.
**Note to reviewers**: Please check the Upload Logs step in the CI, I have not tested that. Also, `mach-nix` is certainly not required for the Python shell, but it is pretty handy. Let me know if you want me to do it the regular way.
Review this …
=> Run integration tests on the Nix Static binary

.github/workflows/vast.yaml
It can happen that master base of a branch in PR didn't finish building yet. The Google store artifacts won't be published, which will cause build failure in case we wan't to trigger jobs that use them (build plugins without build vast for now)
I have done some local testing by manipulating build_sha to see how it behaves with a master that published artifacts. Seemed to work :D
=> Run build vast jobs when only plugins are required to be rebuilt, but the build artifact from master is not yet available

.github/workflows/vast.yaml
This fixes the oversight that allowed #2705 to be merged with failing checks, and does some additional improvements to the CI to make it fail faster.
=> Fix branch protections enforcement for VAST workflow

.github/PULL_REQUEST_TEMPLATE.md
Nobody is really using the PR template that we've had, so this reduces it down to the comment at the beginning and makes the comment a bit more elaborative.
=> Simplify the pull request template

.clangd, libvast/include/vast/bitmap_algorithms.hpp, libvast/include/vast/chunk.hpp, libvast/include/vast/concept/parseable/core.hpp, libvast/include/vast/data.hpp, libvast/include/vast/event_types.hpp, libvast/include/vast/fwd.hpp, libvast/include/vast/plugin.hpp, libvast/include/vast/type.hpp, libvast/include/vast/view.hpp, vast/vast.cpp
When pairing with @Dakostu earlier today I noticed that his Qt Creator showed inline hints for include-what-you-use via clangd. Turns out this is an option in clangd that we can enable, and Qt Creator does so by default. I think this makes for a better dev experience for everyone, so let's enable it by default instead of relying on some editor's custom flags for clangd.
I've also done a small pass over some headers (chosen randomly) to test how well this works. IWYU has come a long way since we first tried using it a few years ago.
=> Enable clangd IWYU integration

plugins/web/integration/tests.yaml, plugins/web/src/server_command.cpp
This was included in #2667, but since it's not clear if that will be merged in time for 2.4 it deserves to have its own PR.
- Don't throw an exception when encountering invalid query parameters
- Add test with invalid query paramter
=> Catch exception when encountering invalid query parameters

.github/workflows/vast.yaml
Our new Python bindings are currently waiting for a PEP 541 request to resolve a name-squatting issue on PyPI. As such, the CI will not be able to publish the package. Now with the bundling from #2636 being delayed until after VAST v2.4 this is not a big issue, as that leaves us some more time to resolve the remaining issues until the next release. We do, however, need to disable the publishing for v2.4 as that's already in feature freeze.
=> Temporarily disable publishing on PyPI in CI

.github/workflows/analysis.yaml
This was an oversight when introducing the script as a central place to install our dependencies, and it broke on master because of the new Arrow release 10.0.1-1. This fixes it by just re-using the logic from the other CI workflows and the Dockerfile.
=> Fix analysis CI workflow

.github/workflows/vast.yaml
This was an oversight we recently introduced, and it caused the Docker Compose CI job to fail early in the VAST v2.4 release candidate cycle. Essentially, we always have to upload images with tagged with their SHA so downstream jobs in CI can refer to them consistently.
=> Upload Docker images tagged with commit SHA on release

.github/workflows/vast.yaml
We've seen the Parquet plugin unit tests run into illegal instruction crashes that we cannot reproduce locally, so for now we're just disabling the plugin in CI for the macOS platform as it's not critical on it.
=> Disable the Parquet plugin in CI for macOS

.github/workflows/vast.yaml
Now that GitHub Actions always uses Arrow 10 in macOS, it's time to see whether the issue from tenzir/vast#2601 is fixed.
=> Re-enable ASan in macOS CI

docker/test, docker/vast/docker-compose.yaml
These tests did not properly check for the exit code of all spawned containers since we started explicitly setting a container name. This fixes that oversight.
=> Fix exit code check in Docker Compose tests

libvast/src/system/index.cpp
I noticed that my compiler showed a `unused no-discard return value` warning, The culprit is a`std::filesystem::exists(path)` call whose return value seems to get ignored. I propose replacing it with an `std::filesystem::exists(path, err)` instead.
=> Use std::filesystem::exists(path, err) call instead of std::filesystem::exists(path) call

changelog/unreleased/2743--status-invalid-argument.md, libvast/src/system/active_partition.cpp
When creating the status response for the active partition, some indexers may be null. These return an "invalid argument" error when attempting to fetch the status from them.
Discovered by @tobim during our recent hackathon.
=> Skip null indexers when creating status response

libvast/src/table_slice.cpp
The short-circuiting in the function evaluating a filter expression on a batch of data short-circuited later than it could've, which made queries that return all or no events unnecessarily expensive. This moves the checks to their proper places.
Noticed by @tobim when benchmarking a bulk-export for VAST v2.4.
=> Short-circuit earlier when filtering batches

libvast/src/evaluate.cpp
This change makes it so we only instantiate regex objects once per batch instead of once per row, causing a massive speedup even for simple pattern searches.
No changelog entry as this wasn't possible at all prior to #2769, which this is based upon.
=> Reduce regex compilations to speed up pattern search

libvast/src/system/index.cpp
One of the promise is never delivered when persist request to partition transformer return an error.
The other is a race condition that got visible during CAF 0.18.6 bump.
The only thing keeping partition_transfomer alive in index is the index's request to partition_transfomer and the pending queries.
It can happen that partition_transfomer lifetime is over before it can fulfill it's own internal promise that is needed to fulfill index promise. This leads to the broken promise error.
=> Fix broken promises in index.cpp

changelog/unreleased/changes/2776--removed-meta-field-extractor.md, libvast/include/vast/concept/printable/vast/expression.hpp, libvast/include/vast/detail/partition_common.hpp, libvast/include/vast/expression.hpp, libvast/src/concept/parseable/vast/expression.cpp, libvast/src/evaluate.cpp, libvast/src/expression_visitors.cpp, libvast/src/system/catalog.cpp, libvast/src/taxonomies.cpp, libvast/test/expression.cpp, libvast/test/expression_evaluation.cpp, libvast/test/table_slice.cpp, libvast/test/taxonomies.cpp, web/docs/understand/query-language/expressions.md
The predicate `#field == "X"` matched all events for which the field extractor `X` had data, i.e., it was semantically equivalent to `X != nil`.
Fundamentally, the `#field` meta extractor broke our model of extractors, since it did not result in a single value or a list of values to compare against, but rather created an implicit disjunction with changed relational operator semantics compared to all other predicates.
This removes the operator without a deprecation period as it received very little usage.
=> Remove the `#field` meta extractor

changelog/unreleased/bug-fixes/2768--infer-non-config-types.md, libvast/builtins/operators/extend.cpp, libvast/builtins/operators/replace.cpp, libvast/test/pipeline.cpp
Previously, using an address value in the extend or replace operators did not work. This is now fixed, and will produce the proper type as long as it can be inferred from the data. This bug applied to all types that were not also used as types in configuration, i.e., address, subnet, pattern, and map.
=> Infer non-config types in extend and replace operators

.github/workflows/vast.yaml
Using `google-github-actions/setup-gcloud` with `service_account_key` is deprecated, replacing it with `google-github-actions/auth@v1` and Workload Identity
=> Upgrade GCP setup action

scripts/sync-vast-nodes.sh
This shell script keeps two VAST nodes in sync by periodically polling one node and importing all matching records into another node. It keeps track of the last successful sync in a file contaiing a timestamp, so it is somewhat robust to being cancelled etc.
The actual sync runs in an infinite loop, and it may be better to let the script be a one-off sync and manage the repeated execution to something more suited, like a systemd timer.
=> Basic script that synchronizes two VAST nodes on a filter expression

.github/workflows/vast.yaml, Dockerfile, changelog/unreleased/features/2742--vast-slim-image.md, cmake/VASTRegisterPlugin.cmake, flake.nix, libvast/CMakeLists.txt, libvast/builtins/endpoints/query.cpp, libvast/src/detail/installdirs.cpp.in, libvast/src/detail/installdirs_relocatable.cpp.in, libvast/src/plugin.cpp, nix/restinio/default.nix, nix/static-binary.sh, nix/vast/default.nix, shell.nix
This can be used with
```
nix run .#stream-image | docker load
```
It reuses the regular static binary output so it won't rebuild VAST if the static binary is already available.
According to `docker image ls` the resulting image weighs 117 Mb,
significantly lighter than the Debian based image which is ~330 Mb.
=> Make it easy to create docker images with Nix

.github/workflows/vast.yaml, libvast/CMakeLists.txt, libvast/builtins/endpoints/query.cpp
Should be fairly simple: This causes the bundled CAF to build without any deprecation warnings.
=> Silence deprecation warnings in bundled CAF

libvast/builtins/commands/rebuild.cpp, libvast/builtins/endpoints/export.cpp, libvast/include/vast/bitmap_algorithms.hpp, libvast/include/vast/id_range.hpp, libvast/include/vast/ids.hpp, libvast/include/vast/table_slice.hpp, libvast/src/segment.cpp, libvast/src/system/exporter.cpp, libvast/src/system/sink.cpp, libvast/src/table_slice.cpp, libvast/test/bitmap_algorithms.cpp, libvast/test/feather.cpp, libvast/test/table_slice.cpp, plugins/parquet/tests/parquet.cpp
This makes a significant change to how `select` on table slices operates: Instead of re-creating the selected data, it now slices the incoming table slices without copying anything. `filter` is now just `concatenate(select(...))`, where `concatenate` is a new operation that we kind of already had for the internal `rebatch` operator of the `rebuild` command.
Additionally, this fixes `truncate` and `split` to properly handle import timestamp and offset, renames `truncate` to `head`, introduces a `tail` operation, and changes `split` to just be a call to `head` and `tail` respectively.
This should be tested for the performance delta before merging. In terms of review, `join` is the only thing here that may look really scary, but remember that it's almost a carbon copy of what we had already …
=> Optimize `select` and `filter` on table slices

libvast/src/system/configuration.cpp, libvast/test/system/configuration.cpp
One function in configuration.cpp was still removing the caf. prefix when parsing CLI arguments. This logic gets removed as CAF now needs all it's options to be preceded by "caf."
=> Fix parsing of CAF CLI options

vast/integration/vast.yaml
The keys used for CAF logs in the yaml config file are no longer correct.
I have tried using caf.logger.file.path to get the logs from with no success.
The 0.17.6  CAF required file-name option which was not set in caf.logger. Probably the CAF logging didn't work?
Even though the logging might not work, i still think it's worth having up to date keys in the config instead of deprecated ones
=> Use CAF 0.18 keys for VAST integration tests file logging

libvast/builtins/commands/rebuild.cpp
Following the introduction of a minimum partition version of 1 with tenzir/vast#2778, all partitions are now guaranteed to be homogeneous. The rebuilder as such does not need to take care of heterogeneous partitions any longer.
=> Remove rebuild support for heterogeneous partitions

libvast/include/vast/partition_synopsis.hpp, libvast/src/partition_synopsis.cpp, libvast/src/system/index.cpp, libvast/src/system/passive_partition.cpp
Following the introduction of a minimum partition version of 1 with tenzir/vast#2778, all partitions are now guaranteed to have an id range specified in their partition synopsis. Rewriting old partition synopses on startup is no longer necessary.
=> Remove rewriting of partition synopses without id range

libvast/include/vast/fwd.hpp, libvast/include/vast/partition_synopsis.hpp, libvast/include/vast/system/actors.hpp, libvast/include/vast/system/partition_transformer.hpp, libvast/src/system/catalog.cpp, libvast/src/system/index.cpp, libvast/src/system/partition_transformer.cpp, libvast/test/system/partition_transformer.cpp
Following the introduction of a minimum partition version of 1 with tenzir/vast#2778, the augmented partition synopsis is now irrelevant as the schema is always contained in the partition synopsis already. This has no user-facing implications, it's purely an internal cleanup.
=> Remove the `augmented_partition_synopsis`

.github/workflows/vast.yaml, flake.nix, nix/overlay.nix, shell.nix
Using the `github` flake input scheme such as with `mach-nix` often hits GitHub's API rate limit.
This can be avoided by exposing an environment with the dependencies for the integration tests as a dedicated `shell` output.
=> Make static binary CI integration test more reliable

libvast/include/vast/partition_synopsis.hpp, libvast/include/vast/system/actors.hpp, libvast/src/system/catalog.cpp, libvast/src/system/index.cpp, libvast/test/system/catalog.cpp
The compaction plugin allows the user to compact a given partition by hand. It is required for the user to pass the UUID of a partition as an input. Since the index API changed from uuid to partition_info it was needed for compaction plugin to somehow map one to the other one. I find the extension of catalog API to be the cleanest way to do it.
=> Add new API for partition_info by uuid extraction in Catalog

web/docusaurus.config.js
This PR adds [Plausible](https://plausible.io/) analytics to our website.
=> Add Plausible analytics to website

libvast/include/vast/detail/inspection_common.hpp, libvast/include/vast/fwd.hpp, libvast/include/vast/hash/hash_append.hpp, libvast/include/vast/system/actors.hpp, libvast/src/detail/add_message_types.cpp, libvast/test/detail/inspection_common.cpp
These changes were added due to compilation failure of some plugins (matcher, compaction)
- Moved inspection related code from actors.hpp to fwd.hpp as it may be needed by plugins. To me it would be akward to include actors.hpp just for some inspector_access instantiations
- inspect_enum doesn't need to rely on Setter and Getter Inspector API. It would require complicating record_inspector in order to get some plugins to work. Also it constrained custom inspectors to implement Setter and Getter which is not necessary with how enums are serialized in VAST.
- In some plugins it may be needed to call inspect overloads which use on_load for serialization. Previously it was a compilation error. Now it behaves like in CAF. Calling on_load with serializer just doesn't call the callback. It …
=> Adjust libvast to allow compaction and matcher plugins compilation.

.github/workflows/vast.yaml
This action fails randomly sometimes because of rate limitations in unauthorized API calls. I don't think we actually need this at all, so if the CI runs through we're good.
=> Remove unnecessary use of `ndeloof/install-compose-action`

libvast/src/table_slice.cpp
Fix of the latest ASAN issues on the CI. I have retried unit tests jobs multiple times and the issue doesn't seem to reproduce
Thanks to @dominiklohmann for figuring this out.
=> Fix table slice state on non unique chunk when setting import time

libvast/include/vast/command.hpp, libvast/include/vast/config_options.hpp, libvast/include/vast/detail/settings.hpp, libvast/include/vast/plugin.hpp, libvast/src/command.cpp, libvast/src/config_options.cpp, libvast/src/detail/settings.cpp, libvast/src/system/configuration.cpp, libvast/test/config_options.cpp, libvast/test/detail/settings.cpp, libvast/test/system/configuration.cpp, plugins/cef/src/plugin.cpp, plugins/pcap/main.cpp
The CAF 0.18.6 upgrade introduced a changes to caf::config_value_set parsing. The most used syntax for list config values was a simple CSV, e.g. --plugins=web,pcap
This doesn't work out of box and a free function was introduced to convert the incoming list arguments into a format that caf::config_value_set could parse. This was a ticking bomb, because you had to remember about it and "sanitize" the list value arguments before parsing. Instead of using caf::config_value_set and sanitizing the list value arguments the new type was created to do it automatically.
=> Create a custom type for handling CLI options

docker/thehive/thehive/application.conf.template
As stated in the migration docs from 4.x to TheHive 5.y [link], the configuration key to enable modules has been changed. This commit silences a warning about usage of the deprecated key.
[link]: https://docs.strangebee.com/thehive/setup/installation/upgrade-from-4.x/#prepare-for-the-new-installation
=> TheHive: rename deprecated configuration key

vast/integration/vast_integration_suite.yaml
Disable two integration tests that turn out to be flaky during various CI runs.
=> Disable two flaky integration tests

.github/workflows/vast.yaml
The python bindings are used in docker, docker-compose and vast-io. It is safer to run these jobs when there are changes in the /python directory.
=> Run docker, docker-compose, vast-io and python job when /python changes

libvast/src/format/arrow.cpp, web/docs/understand/formats/arrow.md
This causes the Arrow import to skip Arrow data that was not produced by VAST, as that cannot yet be handled by VAST. A proper fix for this is in sight, but for now this will have to do. It's obviously better to reject gracefully than to crash here.
No changelog entry as the Arrow import was only introduced after the latest release.
=> Skip record batches with incompatible metadata on import

libvast/include/vast/format/arrow.hpp, libvast/src/format/arrow.cpp
This is necessary for continuous export with Apache Arrow as output format. The `StdoutStream` uses `cout` internally, which buffers written data by default. This buffering means that the most recent batch does not arrive in its entirety at the destination until more results are produced.
=> Flush every batch when exporting arrow

libvast/builtins/endpoints/export.cpp, libvast/builtins/endpoints/query.cpp, libvast/include/vast/system/spawn_arguments.hpp, libvast/src/system/spawn_arguments.cpp, libvast/test/rest_api.cpp
The `vast::to<expression>()` function only converts a string to a `vast::expression`, but it does not validate the semantics of the resulting expression. The index expects the validation to have already happened (and does not double-check this), leading to random errors up to segfaults when trying to search with invalid expressions.
=> Validate query in REST endpoints

plugins/web/integration/reference/authenticated-endpoints/step_04.ref, plugins/web/integration/reference/tls-endpoints/step_05.ref, plugins/web/integration/tests.yaml, vast/integration/reference/server-zeek-conn-log/step_07.ref, vast/integration/vast_integration_suite.yaml
Only the number of events is really important, so we ignore partitions.
This should improve test reliability a bit more.
=> Ignore num-partitions in integration tests

changelog/unreleased/bug-fixes/2861--pid-file-startup.md, libvast/src/detail/pid_file.cpp
This check seems to have at some point been converted from `sprintf` to `fmt::format` without adjusting the syntax. (although its a bit surprising that `fmt` doesn't throw a compile error here)
=> Fix linux PID file check on startup

changelog/unreleased/bug-fixes/2693--connect-crash.md
This adds a missing changelog entry; the upgrade to CAF 0.18 fixed this long-standing but rare bug. Or at least we cannot reproduce it anymore.
=> Add missing changelog entry for connection crash

changelog/unreleased/bug-fixes/2868--async-start-commands.md, libvast/src/system/start_command.cpp, vast.yaml.example
Run start commands asynchronously
We used to run start commands sequentially, but this has the
disadvantage the if any start command blocks indefinitely
(eg. `web server`) the subsequent commands are never executed
and the start command itself never gets to the CTRL-C signal
handling code below.
=> Run start commands asynchronously

libvast/src/system/catalog.cpp
A small thing I randomly noticed while looking at the catalog result struct; I did not do any benchmarking nor do I expect a visible impact but since we have a vector with potentially thousands of elements this looks like a free optimization.
=> Move per-type catalog results

libvast/include/vast/plugin.hpp, libvast/src/system/node.cpp
This makes it possible for plugins to use a component name that is more fitting than the plugin name (ie. 'matcher' vs 'matcher_supvervisor'), or keep the old component name when renaming the plugin.
=> Add a new component_plugin::component_name() function

changelog/unreleased/bug-fixes/2860--web-plugin-shutdown.md, libvast/builtins/endpoints/query.cpp, plugins/web/include/web/restinio_server.hpp, plugins/web/src/restinio_server.cpp, plugins/web/src/server_command.cpp
This PR fixes 2/3 shutdown issues I found in the web plugin; in particular the web plugin now shuts down correctly when run as a separate command when receiving a signal and when detecting a node shutdown.
Note that it does not address the situation where `web server` is passed as a start command to `vast start`.
=> Fix some shutdown issues in the web plugin

changelog/unreleased/features/2835--retry-mechanism-for-vast-clients.md, libvast/include/vast/defaults.hpp, libvast/include/vast/fwd.hpp, libvast/include/vast/system/actors.hpp, libvast/include/vast/system/connect_request.hpp, libvast/include/vast/system/connector.hpp, libvast/src/detail/add_message_types.cpp, libvast/src/system/application.cpp, libvast/src/system/connect_to_node.cpp, libvast/src/system/connector.cpp, vast.yaml.example, web/docs/use/run/README.md
1. Added a new actor that allows the caller to connect with a remote node in async/sync manner with a retry mechanism.
2. Adjusted current connect_to_node to use the new actor as a implementation detail.
I have done a simple test to check the retry mechanism.
Run export -> wait a 2 - 3 seconds and run vast start.
Previously the client exits with error:
> ! system_error: failed to connect to VAST node at 127.0.0.1:42000: !! caf::sec::cannot_connect_to_node: ip_connect failed 127.0.0.1 message("ip_connect failed", "127.0.0.1", 42000)
Now it manages to export the data.
=> Implement a retry mechanism for VAST clients failing to connect to the server

CMakeLists.txt, libvast/include/vast/arrow_table_slice.hpp, libvast/src/arrow_table_slice.cpp
This could in theory lead to a miscompilation of code, and GCC kindly warned us about it in release builds with PGO/LTO enabled.
I also added a small tweak to our build scaffolding so we catch this in CI; there is absolutely no reason why we should ever write code that violates the one definition rule.
=> Fix an ODR violation in `arrow_table_slice.hpp`

plugins/parquet/CMakeLists.txt, vast/integration/integration.py, vast/integration/vast_integration_suite.yaml
This is a band aid over integration test failures in CI that block progress of unrelated PRs. The real fixes will take a little bit of time to implement correctly, so we this is proposed as a temporary workaround.
=> Relax integration test strictness

libvast/builtins/query-languages/vastql.cpp, libvast/include/vast/concept/parseable/vast/option_set.hpp, libvast/src/pipeline.cpp
This makes it possible to also include whitespace characters like non-breaking spaces and newlines in pipelines, effectively allowing the user to write complex pipelines with formatting however they prefer. For example, if you'd like to get really funky with your formatting, this would now be possible:
```bash
vast export json <<EOF
identity
| drop ts |
select orig_h,
orig_p
,resp_h
| identity
EOF
```
@Dakostu I requested you for review since we had already talked about this one—and I have mistaken the char classes the last time around.
=> Be lenient about whitespace in pipeline parser

web/docs/setup/tune.md, web/docs/understand/formats/zeek.md, web/docs/understand/query-language/expressions.md, web/docs/use/detect/cloud-matchers.md, web/docs/use/detect/match-threat-intel.md, web/docs/use/introspect/README.md, web/docs/use/query/README.md
We still had some uses of the old type names `count`, `real`, and `addr` in the docs. These aren't really explained any more so they can be confusing.
=> Remove leftover mentions of old names of basic types

examples/plugins/pipeline_operator/pipeline_operator_plugin.cpp, libvast/builtins/commands/rebuild.cpp, libvast/builtins/operators/drop.cpp, libvast/builtins/operators/extend.cpp, libvast/builtins/operators/hash.cpp, libvast/builtins/operators/identity.cpp, libvast/builtins/operators/pseudonymize.cpp, libvast/builtins/operators/rename.cpp, libvast/builtins/operators/replace.cpp, libvast/builtins/operators/select.cpp, libvast/builtins/operators/summarize.cpp, libvast/builtins/operators/where.cpp, libvast/include/vast/arrow_table_slice.hpp, libvast/include/vast/pipeline.hpp, libvast/include/vast/pipeline_operator.hpp, libvast/src/arrow_table_slice.cpp, libvast/src/cast.cpp, libvast/src/pipeline.cpp, libvast/test/pipeline.cpp, libvast/test/summarize.cpp
This lowers the boundary to writing additional operators, as falling down to the lower-level Arrow APIs is now opt-in rather than being required. It also makes it so that pipeline operators that do not create new data (e.g., summarize) can keep the import timestamps unchanged, which fixes a long-standing issue that caused compaction and rebuilding to shift import timestamps.
Most importantly, this will make the transition to the upcoming rewritten executor and its pipeline operator API changes a lot easier.
This is based on #2889.
=> Pass table slices through pipeline operators

CMakeLists.txt
Building VAST with a bundled CAF failed to correctly install the CAF libraries, causing CPack-created packages to require CAF to be installed separately.
=> Fix package generation with bundled CAF

python/pyvast/apps/thehive.py, python/pyvast/vast/cli.py, python/pyvast/vast/vast.py, python/tests/test_vast.py
This changes the API to go through an object of the `VAST` type
instead of working directly on the type. This way it is possible
to specify certain option parameters like the connection endpoint
for a group of commands without requiring filesystem or process
level state.
This makes it also possible to run the integration tests of the
bindings without docker.
=> Python library ergonomics improvements

libvast/include/vast/system/actors.hpp, libvast/src/system/datagram_source.cpp, libvast/src/system/source.cpp
This change is introduced to fix the quitting import commands that is visible on the testbed.
These changes were running for about a week on the testbed and the issue never reproduced. It also made the import throughput graph more stable.
The idea is to respect what the CAF wants. The stream handler is called with 10000 events -> we push the 10000 events.
Previously the source actor delegated providing these events in it's own internal handler which increased the backpressure.
=> Process table slices in stream handler for source

libvast/builtins/operators/summarize.cpp
We re-use the `output_schema` member variable of aggregations, as we only create them once per unique schema. As such, we cannot move from them in `aggregation::finish()`, as that will cause subsequent calls to the function to fail.
This crash was newly introduced after the last release, so no changelog entry should be required.
=> Fix a crash in the summarize operator

changelog/unreleased/bug-fixes/2908--fix-openssl-configuration.md, libvast/src/system/configuration.cpp
In the `actor_system_config`, some settings are not like the others. While most modules read their options directly from the `content` object, the SSL configuration is stored in member variables of the main config class. The CAF command line and config file parsers handle this correctly, but settings from `vast.yaml` files or those that are passed in as environment variables are injected through a different code path.
This commit adds assignments to set the aforementioned class members explicitly.
I considered the alternative solution of translating non CAF-native option formats to native ones and let the `parse` function handle it, but that approach would be a large amount of work rather little benefit.
=> Add a workaround to fix CAF OpenSSL options

libvast/src/system/default_configuration.cpp, vast.yaml.example
After short experimenting on the testbed these values suggested by @dominiklohmann seem to work.
Increasing the batch size to 2 seemed to occasionally cause a spike in the throughput. Sometimes it takes longer for the stream to buffer two tokens and send them together.
Changing the buffer size didn't seem to affect the import throughput.
A value of 64 corresponds to the maximum number of events that a one partition can hold.
=> Set default values to new CAF 0.18.6 streaming options

libvast/src/system/passive_partition.cpp, libvast/test/partition_roundtrip.cpp
Partition index creation can selectively be disabled in configuration, and doing so should not lead to warnings when attempting to access data. This PR achieves that by simply not attempting to deserialize non-existing indexes.
Additionally, this fixes the error message in case the deserialization of an existing index fails and changes it from an error to a warning, as VAST already handles this gracefully.
Before:
```
[17:48:32.267] user.scheduled-actor-23 failed to deserialize value index at 5
```
After:
```
[17:51:37.517] passive-partition (834e31a1-8e25-49be-8a8d-fd1e7eda27a9) failed to deserialize value index for field suricata.ftp.dest_ip
```
I don't think this is worth a changelog entry, as it's a really minor thing.
=> Do not warn about missing indexes

Dockerfile, scripts/debian/install-dev-dependencies.sh, web/package.json, web/yarn.lock
All yarn packages were upgraded via the following commands
```
yarn upgrade
syncyarnlock
yarn install
```
No version have been upgraded with breaking changes (major semver is preserved).
https://github.com/vasilevich/sync-yarnlock-into-packagejson
=> Upgrade docusaurus to ^2.3.1 and update all yarn packages

changelog/unreleased/changes/2693-2923--require-caf-0-18.md, nix/caf/source.json, web/docs/setup/build.md
This updates CAF to the latest stable release 0.18.7.
closes tenzir/issues#71.
TODO:
=> Bump CAF to 0.18.7

changelog/unreleased/bug-fixes/2924--count-command-hangs-when-zero-results.md, libvast/src/system/query_processor.cpp
Call `process_done()` to prevent `query_processor` and -derived classes from hanging when there are no candidate partitions to process.
Fixes tenzir/issues#68.
=> Prevent query_processor from hanging when there are no candidate partitions

.github/workflows/style-check.yaml, ansible/README.md, ansible/roles/vast/tasks/debian.yaml, ansible/roles/vast/tasks/main.yaml, ansible/roles/vast/tasks/static.yaml, ansible/roles/vast/tasks/vast-service-overrides.conf.j2, ansible/roles/vast/vast.service, ansible/test/Dockerfile, ansible/test/README.md, ansible/test/example-playbook.yaml, ansible/test/inventory.ini, ansible/test/vast.yaml, changelog/unreleased/changes/2604--ansible-role.md, web/docs/setup/deploy/README.md, web/docs/setup/deploy/ansible.md
This adds a relatively simple role for deploying VAST to a Linux host with Ansible. It supports FHS-based distributions in general, but Debian and derivatives are tested the most.
This role has been in use at Tenzir for a while and we hope to provide additional value to our users by adding it the the open source distribution.
=> Provide an Ansible role for VAST

VAST.spdx, libvast/builtins/stores/feather.cpp, libvast/include/vast/arrow_table_slice.hpp, libvast/include/vast/bitmap_algorithms.hpp, libvast/include/vast/collect.hpp, libvast/include/vast/concept/convertible/data.hpp, libvast/include/vast/detail/env.hpp, libvast/include/vast/generator.hpp, libvast/include/vast/plugin.hpp, libvast/include/vast/store.hpp, libvast/include/vast/table_slice.hpp, libvast/include/vast/type.hpp, libvast/src/partition_synopsis.cpp, libvast/src/store.cpp, libvast/src/system/parse_query.cpp, libvast/src/table_slice.cpp, libvast/src/type.cpp, libvast/test/bitmap_algorithms.cpp, libvast/test/feather.cpp, libvast/test/partition_synopsis.cpp, libvast/test/system/partition.cpp, libvast/test/table_slice.cpp, plugins/parquet/parquet.cpp, plugins/parquet/tests/parquet.cpp
We use generator coroutines basically everywhere nowadays. Let's remove those pesky eight characters in `detail::` from oh so many places.
=> De-detail generator

flake.lock, flake.nix, nix/overlay.nix
Just some extra clean-up in flake.nix (we don't need `nix-npm-buildpackage` anymore).
=> Remove nix-npm-buildpackage from flake.nix

libvast/include/vast/system/actors.hpp, libvast/include/vast/taxonomies.hpp, libvast/src/system/catalog.cpp, libvast/src/taxonomies.cpp
The taxonomy resolution is applied per-schema since we merged the type registry into the catalog, and since then the overload of taxonomy resolution that resolved for more than one schema at the same time was only used because the single-schema version mapped onto the old function. This simplifies the whole ordeal.
=> Simplify taxonomy resolution

libvast/builtins/commands/show.cpp, libvast/include/vast/type.hpp, libvast/src/type.cpp, vast/integration/reference/server-zeek-multiple-imports/step_01.ref, vast/integration/vast_integration_suite.yaml
This is an intentionally undocumented and mostly internal option to render schema definitions in an expanded form; it's mostly for a future PR that changes the REST API endpoints to always show the expanded schema as that's easier to handle programmatically.
=> Add a `--expand` flag to `vast show schemas`

ansible/roles/vast/tasks/vast-service-overrides.conf.j2
This fixes an undefined variable error if the `write_paths` option is not specified.
The functionality is new so we don't need a mention in the changelog.
=> Fix empty write_paths in the ansible role

changelog/unreleased/features/2773-2937-pipeline-parameter.md, changelog/unreleased/features/2773-pipeline-parameter.md, libvast/builtins/endpoints/export.cpp, libvast/builtins/endpoints/query.cpp, libvast/test/rest_api.cpp, plugins/web/integration/reference/export-endpoint/step_06.ref, plugins/web/integration/tests.yaml, web/openapi/openapi.yaml
Fixed a bug which made the /query/next return the same results infinitely. Now it returns 0 events if all events were shipped.
The query and export endpoints now accept an optional pipeline string in the query parameter.
The changelog entry for /query endpoints is already in unreleased state
=> Support pipelines in export and query endpoints

web/src/pages/discord.tsx
This one's set to never expire, unlike the old one.
=> Fix Discord invite link

changelog/unreleased/features/2944--cors-handling.md, libvast/include/vast/http_api.hpp, plugins/web/include/web/configuration.hpp, plugins/web/src/configuration.cpp, plugins/web/src/plugin.cpp, plugins/web/src/server_command.cpp
For "non-simple" requests to external domains, the browser sends a preflight CORS request with method OPTIONS. The server needs to return a success response (with a matching origin, method, and headers) in order for the browser to go ahead with the request itself.
Fixes https://github.com/tenzir/issues/issues/86
=> Add CORS preflight request handling

libvast/builtins/endpoints/query.cpp, libvast/test/rest_api.cpp, plugins/web/src/server_command.cpp, web/openapi/openapi.yaml
This PR adds schema information to the `/query` endpoint. Use it like this:
```bash
❯ curl -XPOST -H "Content-Type: application/json" -d "{\"query\": \"taste 10 | drop timestamp\"}" http://localhost:42001/api/v0/query/new
{"id": "4b4f23d7-0807-4f3b-9994-6bf6bfb610d0"}
❯ curl -XGET -H "Content-Type: application/json" http://localhost:42001/api/v0/query/4b4f23d7-0807-4f3b-9994-6bf6bfb610d0/next?n=10
```
The output contains two parts: An `events` section containing the raw, row-based data as JSON and also a unique identifier for the schema of the row. The same identifier for the schema also occurs in the `schemas` section, which renders the full type definition as also available via `vast show schemas --expand`.
Fixes tenzir/issues#98
=> Add schema information to the `/query` endpoint

.github/workflows/vast.yaml
Fixes an oversight from #2916 that didn't run within the PR.
=> Fix CI on master

libvast/builtins/operators/summarize.cpp, libvast/include/vast/pipeline.hpp, libvast/include/vast/pipeline_operator.hpp, libvast/src/pipeline.cpp, libvast/src/system/datagram_source.cpp, libvast/src/system/exporter.cpp, libvast/src/system/importer.cpp, libvast/src/system/sink.cpp, libvast/src/system/source.cpp, libvast/test/pipeline.cpp
Note that this fix is for `export` only, this will stay slightly incorrect for both partition transformations and `import` until we have the new executor in place.
=> Make summarize in export block properly

CMakeLists.txt, cmake/VASTPackage.cmake, nix/vast/default.nix
The package conflicts directive caused unintended conflicts when trying to upgrade or side-grade from the open source edition to the community edition or back.
We now only encode the edition name into the package output file name but leave the package name itself as "vast".
=> Fix debian package updates

libvast/builtins/endpoints/export.cpp, libvast/builtins/query-languages/vast.cpp, libvast/include/vast/plugin.hpp, libvast/src/system/parse_query.cpp, libvast/test/pipeline.cpp, plugins/sigma/src/plugin.cpp, web/blog/vast-v3.0/index.md, web/docs/understand/architecture/plugins.md, web/docs/understand/language/frontends/README.md, web/docs/understand/language/frontends/sigma.md, web/docs/understand/language/frontends/vast.md, web/openapi/openapi.yaml
This PR replaces the "VAST Query Language" with just "VAST Language" - to be specific, it replaces the following namings:
|old|new|
|:-:|:-:|
|VASTQL|VAST|
|VAST Query Language|VAST Language|
|`vastql` plugin|`vast` plugin|
|`query_language_plugin`|`language_plugin`|
Also includes an addition to the 3.0 blog post.
=> Replace occurences of the VAST Query Language with query-less naming wherever appropriate

nix/vast/default.nix
The static binary contains references to some store paths that are not needed at runtime, namely `tzinfo` and `openssl.etc`.
=> Prune unwanted store paths from *-slim images

libvast/fbs/data.fbs, libvast/include/vast/concept/parseable/vast/pattern.hpp, libvast/include/vast/concept/printable/vast/pattern.hpp, libvast/include/vast/pattern.hpp, libvast/include/vast/view.hpp, libvast/src/data.cpp, libvast/src/evaluate.cpp, libvast/src/expression_visitors.cpp, libvast/src/pattern.cpp, libvast/src/view.cpp, libvast/test/convertible.cpp, libvast/test/data.cpp, libvast/test/parse_data.cpp, libvast/test/pattern.cpp, libvast/test/view.cpp, plugins/sigma/src/parse.cpp
This is the https://github.com/tenzir/vast/pull/2957 PR without the change from `std::regex` to `re2` for quicker inclusion into v3.0 since the `re2` inclusion causes some issues with the CI.
=> Instantiate regex in pattern eagerly (without re2)

flake.lock, flake.nix, nix/overlay.nix, nix/vast/default.nix, shell.nix
This brings in a few version updates for the static binary and vast*-slim docker images:
* GCC 12
* Arrow 11.0
* simdjson 3.1.2
* robin-map 1.2.1
* flatbuffers 22.11.23
* clang 15
=> Bump nixpkgs to 9499706a6

.github/workflows/vast.yaml
This PR also contains a fix for the policy enforcement check so that out of sync nix sources actually fail CI.
=> Test vast plugins in CI if the submodule changed

libvast/src/expression.cpp, libvast/src/store.cpp, libvast/src/system/active_partition.cpp, libvast/test/expression_evaluation.cpp, libvast/test/system/active_partition.cpp
This PR encompasses 2 changes:
* Fix a crash in the query eval logic of the active partition (a82557cd)
* Fix a logic error causing wrong query results, also in the active partition (0e6f24eb0)
=> Ignore dense indexes in the active partition lookup path

changelog/unreleased/breaking-changes/2976--removed-map-type.md, libvast/src/concept/parseable/vast/legacy_type.cpp, libvast/src/system/accountant.cpp, libvast/test/legacy_type.cpp, libvast/test/schema.cpp, vast/integration/misc/schema/all-types.schema, vast/integration/reference/arrow-full-data-model/step_01.ref, web/blog/vast-v3.0/index.md, web/docs/setup/monitor.md
We want to remove the map type, but doing that is a larger operation. To get the user-facing breaking change out earlier, i.e., in time for 3.0, we're just making it inaccessible first and are then removing it later on.
Additionally, this PR removes the only place in VAST that ever used the map type for table slices written to disk: The `vast.metrics` event, whose metadata was never queryable.
Now, behold the beauty of actually queryable metrics from the self-sink:
```
$ vast -qq export json '#type == "vast.metrics.passive-store.init.runtime"
| select ts,value
| summarize min(value), max(value) by ts resolution 10s'
{"ts": "2023-02-28T17:21:50.000000", "min(value)": 0.218875, "max(value)": 107.280125}
{"ts": "2023-02-28T17:20:00.000000", "min(value)": 0.549292, "max(value)": 0.549292}
``` …
=> Make the map type inaccessible to users

changelog/unreleased/bug-fixes/2977--infinite-recursion-in-record-algebra-parser.md, libvast/src/concept/parseable/vast/legacy_type.cpp, libvast/test/legacy_type.cpp
Fixes parsing of
```
type broken = record {
test: : string
}
```
as reported by @satta.
=> Fix infinite recursion in the record algebra parser

libvast/include/vast/detail/make_io_stream.hpp, libvast/src/detail/make_io_stream.cpp, libvast/src/system/accountant.cpp
This should make the metrics sink more compatible with logrotate. THe copytruncate mode should no longer cause NULL bytes to appear.
=> Open the metrics file sink in append mode

libvast/include/vast/type.hpp, libvast/include/vast/validate.hpp, libvast/src/validate.cpp, libvast/test/validate.cpp
A mini-project during the most recent hackathon; the idea is to slowly support everything that's required to model the complete vast config as a record type and move away from caf::settings. (Follow-ups for that would be an `opaque` attribute for configuration that's not validated, ie. pluging configuration, and a `deprecated` attribute, as well as easy accessor functions for getting typed data out of a `record` according to a given path)
=> Support 'required' attribute for config validation

web/docusaurus.config.js, web/package.json, web/yarn.lock
This PR replaces webpacks's default babel loader with esbuild (https://esbuild.github.io/) resulting in about a rough 30% decrease in build time for our docs site.
=> Switch to esbuild for docs site to speed up build

libvast/src/system/default_configuration.cpp
The VAST server seems to sometimes lose connection with the import clients under heavy load. Changing the default timeout from 30 seconds to 120 seconds may prevent that.
=> Set CAF middleman connection timeout to 120 seconds

libvast/CMakeLists.txt
simdjson 3.1.4 and 3.1.5 were released today, with the former including my upstream fix that we were working around in our CMake.
=> Bump bundled simdjson to 3.1.5 and drop workaround

changelog/next/breaking-changes/3008--pipeline-triggers.md, vast/vast.cpp
These will be superseded by node ingress/egress pipelines soon, so let's be kind to our users and deprecate them now already.
=> Deprecate `vast.pipeline-triggers`

libvast/include/vast/system/indexer.hpp, libvast/src/system/index.cpp, libvast/src/system/posix_filesystem.cpp
Going through the `store_header` in the partition file requires file system reads. This affects query performance, and inversely, a high query load may cause the disk monitor's throughput to drop below the ingest rate.
Now, we check whether the store file is located at one of a few probable paths before falling back to the logic described above.
=> Switch main and fallback code paths for erasing partitions

changelog/next/bug-fixes/3006--compaction-retry.md, nix/vast/plugins/source.json
Failing in a compaction run should not cause VAST to wait for the configured interval until it starts a new run, as this may lead to the disk running full. This bumps the compaction plugin to include the changes done by @lava to fix this behavior.
=> Trigger new compaction runs immediately on error

libvast/builtins/printers/json.cpp, libvast/include/vast/plugin.hpp, libvast/test/printer_plugin.cpp
This PR adds a new `printer` plugin type with the first `json` implementation that transforms table slices into a stream of [NDJSON](https://github.com/ndjson/ndjson-spec) data.
Currently unreachable from the user POV.
=> Implement the `json` printer

libvast/builtins/dumpers/stdout.cpp, libvast/builtins/printers/json.cpp, libvast/include/vast/plugin.hpp, libvast/test/dumper_plugin.cpp, libvast/test/loader_plugin.cpp
This PR adds a new `dumper` plugin type with the first `stdout` implementation that sends out chunks to `stdout`.
Currently unreachable from the user POV.
=> Implement the `stdout` dumper

.github/workflows/analysis.yaml, .github/workflows/style-check.yaml, .github/workflows/vast.yaml, README.md, docker/test, libvast/aux/README.md, rfc/README.md, scripts/clang-build-analyzer, scripts/git-setup.sh, scripts/prepare-release, web/README.md, web/blog/public-roadmap-and-open-rfcs/index.md, web/blog/vast-v3.0/index.md, web/docs/contribute/changelog.md, web/docs/contribute/documentation.md, web/docs/contribute/notebooks.md, web/docs/develop/guides/write-a-plugin.md, web/docs/setup/deploy/ansible.md, web/docs/setup/deploy/aws.md, web/docs/setup/deploy/docker-compose.md, web/docs/setup/deploy/docker.md, web/docs/setup/download.md, web/docusaurus.config.js, web/src/pages/download/vast-latest.zip.tsx
This change reflects the switch to `main` as the default branch name within the code base.
References in the documentation, scripts and CI workflows are updated to the new name.
=> Align default branch refs to main

web/src/pages/docs.tsx
This correctly redirected from `/docs` to `/docs/about`, but it also redirected from `/docs/` to `/docs/docs/about`, which was not correct. The added leading slash fixes this behavior for redirects from the URL with the trailing slash.
=> Fix redirect of `vast.io/docs/`

changelog/unreleased/bug-fixes/3026.md, libvast/builtins/commands/rebuild.cpp
The count of currently rebuilt partitions was calculated based on size of a moved from vector. 
This resulted in wrong rebuild metrics
=> Fix usage of moved from variable in rebuild metrics

changelog/unreleased/bug-fixes/3026.md, changelog/v3.0.2/bug-fixes/3026.md, python/pyproject.toml, scripts/prepare-release, version.json, web/blog/vast-v3.0/index.md
This prepares the repository for the VAST v3.0.2 release, bringing fixes to the metrics emitted by the `vast rebuild` command.
=> Prepare repository for VAST v3.0.2

changelog/next/features/3004-3010--exec-command.md, libvast/builtins/commands/exec.cpp
This command takes a single positional argument that must parse as a valid logical pipeline, and then immediately executes it.
The current implementation is pretty naïve, but it suffices for initial testing once we have the from and to operators in place to actually be able to write a closed pipeline.
I've written a follow-up issue to implement signal handling in the executor; I've intentionally not implemented that for now as the API for the exeuctor will change to an asynchronous rather than just concurrent API soon after this initial version, which makes it easier to implement signal handling correctly.
Fixes tenzir/issues#202
=> Implement the `vast exec` command

libvast/src/system/active_partition.cpp
When a partition synopsis is not present, VAST warns about it on startup attempts to restore it. However, we did not log when serializing or persisting that synopsis failed, which is the information you're looking for first when something related went wrong. This adds such logs, clearly indicating that the data will be restored on the next start of the VAST node.
=> Log handled failures to persist partition synopses

.github/workflows/vast.yaml
This job used to work because the webfactory/ssh-agent action used to do this, but changed its behavior with v0.8.0.
=> Fix submodule checkout in the vast-plugins CI job

.clang-tidy
Per a vote in the engineering team:
- Majority to disable `modernize-use-nodiscard`
- Majority to keep `readability-qualified-auto` enabled
- Majority to enable `modernize-use-trailing-return-type`
=> Update some clang-tidy rules

.github/workflows/analysis.yaml, .github/workflows/vast.yaml, CMakeLists.txt, Dockerfile, cmake/VASTConfig.cmake.in, cmake/VASTRegisterPlugin.cmake, docker/dev/Dockerfile, docker/quarto/Dockerfile, docker/thehive/vast-cortex-neuron/Dockerfile, libvast/include/vast/hash/xxhash.hpp, python/tests/test_vast.py, scripts/debian/install-dev-dependencies.sh, vast/integration/requirements.txt, web/docs/setup/build.md
Since bookworm is now in hard freeze this upgrade should be safe. This will allow us to bump the minimum version of GCC to 12 should the need arise.
=> Migrate Debian based builds to bookworm

.github/workflows/vast.yaml, VAST.spdx, changelog/next/changes/3043--add-boost.md, libvast/CMakeLists.txt, nix/vast/default.nix, plugins/web/aux/CMakeLists.txt, plugins/web/include/web/restinio_server.hpp, plugins/web/include/web/server_command.hpp, scripts/debian/install-dev-dependencies.sh, scripts/macOS/install-dev-dependencies.sh, web/docs/setup/build.md
VAST can benefit from Boost libraries in various areas, such as better stack trace support, correct resource tracking or runtime executable path lookup, while abstracting away platform details.
=> Add Boost as a dependency

changelog/v2.4.2/changes/3047.md, docker/thehive/app/poetry.lock, libvast/include/vast/query_context.hpp, libvast/include/vast/system/index.hpp, libvast/src/query_queue.cpp, libvast/src/system/index.cpp, libvast/test/query_queue.cpp, python/pyproject.toml, version.json
This PR backports #3047 and prepares the repository for a new patch release on the v2.4.x branch.
=> Prepare a VAST v2.4.2 release

changelog/next/changes/3047.md, changelog/v2.4.2/changes/3047.md, libvast/include/vast/query_context.hpp, libvast/include/vast/system/index.hpp, libvast/src/query_queue.cpp, libvast/src/system/index.cpp, libvast/test/query_queue.cpp
With a large value in `vast.rebuild.parallel` or `vast.automatic-rebuild` and a low value in `vast.max-queries`, VAST may end up in a state in which the state at which it is able to respond to queries is limited by the speed at which it is able to rebuild.
This fixes that issue, and then adds some additional logging that helped find this bug.
=> Reduce conflict potential between rebuilding and queries

.github/workflows/vast.yaml
The CI is unable to run VAST v2.4.2 because that patch release was cut after the renaming of the master branch to main, but the v2.4.x branch still assumed the default branch to be named main.
=> Ignore VAST v2.4.2 in regression tests

changelog/next/features/3050--tail-operator.md, libvast/builtins/operators/tail.cpp, libvast/test/pipeline.cpp, web/docs/understand/language/operators/tail.md
This PR adds the `tail` operator. Currently only available as a new `crtp_operator`.
=> Add `tail` operator

scripts/git-setup.sh
This is a follow-up for our recent switch of the default branch name.
=> Rename master -> main in git setup scripts

changelog/next/changes/3058--systemd-restart-on-failure.md, vast/services/systemd/vast.service.in
In case of failures like OOM we want the service to restart by default.
=> Restart the systemd service on failure

libvast/builtins/endpoints/query.cpp, libvast/builtins/endpoints/status.cpp, libvast/include/vast/http_api.hpp, libvast/test/rest_api.cpp, nix/overlay.nix, plugins/web/include/web/configuration.hpp, plugins/web/include/web/restinio_response.hpp, plugins/web/integration/reference/status-endpoint/step_03.ref, plugins/web/src/configuration.cpp, plugins/web/src/restinio_response.cpp, plugins/web/src/server_command.cpp
This fixes parsing of escaped characters in HTTP Post requests such as `/query/new`.
Tested with
```
curl -XPOST -H "Content-Type: application/json" -d '
{"query": "where \"Cm8HIj3H2K9GvysCW5\"", "limit": 5}' http://127.0.0.1:42001/api/v0/query/new
{"id": "a21da879-d603-4ff1-80dc-91847608c42c"}
```
=> Unescape query endpoint parameters

changelog/next/changes/3067--user-defined-operators.md, libvast/builtins/commands/exec.cpp, libvast/builtins/endpoints/query.cpp, libvast/include/vast/data.hpp, libvast/include/vast/pipeline.hpp, libvast/src/pipeline.cpp, libvast/test/loader_plugin.cpp, libvast/test/pipeline.cpp
This PR adds support for user-defined operator aliases that can be defined in the config. For example:
~~~yaml
vast:
operators:
anonymize_urls: |
replace net.url="xxx"
aggregate_flows: |
summarize 
pkts_toserver=sum(flow.pkts_toserver),
pkts_toclient=sum(flow.pkts_toclient),
bytes_toserver=sum(flow.bytes_toserver),
bytes_toclient=sum(flow.bytes_toclient),
start=min(flow.start),
end=max(flow.end)
by
timestamp,
src_ip,
dest_ip
resolution
10 mins 
~~~
This allows composing more complex pipelines, for instance `from vast | anonymize_urls | aggregate_flows | write json to stdout`. The PR only affects the new pipelines, which will eventually be used everywhere.  The new pipeline parser also looks for definitions in `vast.pipelines` instead of `vast.operators`. However, this behavior is …
=> Add support for user-defined operator aliases

changelog/next/bug-fixes/3068--distinct-list-handling.md, changelog/next/features/3068--count-distinct.md, libvast/builtins/operators/count_distinct.cpp, libvast/builtins/operators/distinct.cpp, libvast/test/summarize.cpp, web/docs/understand/language/operators/summarize.md
`count` and `distinct`, fused together. This new aggregation function returns the number of distinct, non-null values.
In addition, this removes the special-handling of list values in distinct: The `distinct` function silently performed a different operation on lists, returning the distinct non-null elements in the list rather than operating on the list itself. This feature will return in the future as unnesting on the extractor level via `distinct(field[])`, but for now it has to go to make the distinct aggregation function work consistently.
=> Introduce the `count_distinct` aggregation function

.github/workflows/vast.yaml
Currently our CI fails a lot because of a known transient error with TheHive. We ignore this error code, but still the CI shows as failed a lot of the time, making the indicator rather worthless. This changes the setup so the tests doesn't actually fail in this scenario, but rather emits a warning.
=> Warn when TheHive integration tests fail

.clang-tidy, changelog/next/features/3064--operator-aliases.md, changelog/next/features/3079--from-to-operators.md, libvast/builtins/connectors/dash.cpp, libvast/builtins/connectors/stdin.cpp, libvast/builtins/connectors/stdout.cpp, libvast/builtins/formats/json.cpp, libvast/builtins/operators/from_read.cpp, libvast/builtins/operators/load.cpp, libvast/builtins/operators/parse.cpp, libvast/builtins/operators/print.cpp, libvast/builtins/operators/save.cpp, libvast/builtins/operators/write_to.cpp, libvast/include/vast/pipeline.hpp, libvast/include/vast/plugin.hpp, libvast/src/pipeline.cpp, libvast/test/pipeline.cpp, web/docs/understand/pipelines.md
This exposes the expert operators underlying `from … read …` and `write … to …`.
Fixes tenzir/issues#276
Fixes tenzir/issues#254
=> Expose the lower-level `load`, `parse`, `print`, and `save` operators

changelog/v3.0.4/bug-fixes/3083.md, libvast/builtins/commands/rebuild.cpp, web/blog/vast-v3.0/index.md, web/docs/setup/tune.md, web/versioned_docs/version-VAST v3.0/setup/tune.md
This fixes the `rebuild` command not to loop infinitely over all partitions when at least one not-emprty set of partitions needed to be rebuilt.
This logic bug was introduced with the VAST v3.0.2 release, and can be tracked down to the confusing meaning of the `--all` flag. In addition, this also changes the meaning of the option to do what it should, namely rebuild _all_ partitions instead of just _outdated_ ones. The `--undersized` flag remains unchanged and still adds all undersized partitions to the list of partitions considered for rebuilding, regardless of whether they're outdated or not.
=> Fix partition selection for the `rebuild` command

libvast/include/vast/adaptive_table_slice_builder.hpp, libvast/include/vast/detail/adaptive_table_slice_builder_guards.hpp, libvast/include/vast/detail/series_builders.hpp, libvast/src/adaptive_table_slice_builder.cpp, libvast/src/detail/adaptive_table_slice_builder_guards.cpp, libvast/src/detail/series_builders.cpp, libvast/test/adaptive_table_slice_builder.cpp
This changes enable writing of suricata/zeek parsers as a pipeline operators.
Handling known schemas enables the user to use enumeration types. There is also an option to start with a given schema, but allow it to discover new fields (might be useful in the future in some way)
=> Add an option to construct `adaptive_table_slice_builder` with a schema starting point

changelog/next/features/3098--directory-saver.md, libvast/builtins/connectors/dash.cpp, libvast/builtins/connectors/directory.cpp, libvast/builtins/connectors/file.cpp, libvast/builtins/operators/write_to.cpp, libvast/include/vast/plugin.hpp
This PR adds a `directory` saver that creates a directory with a file for each schema in the specified format.
=> Add `directory` saver

.clang-tidy, changelog/next/features/3104--xsv-format.md, libvast/builtins/connectors/file.cpp, libvast/builtins/formats/xsv.cpp, libvast/include/vast/concept/parseable/vast/pipeline.hpp, vast/integration/data/json/nested-structure.json
This PR adds an `xsv` parser and printer that enables the user to parse and print character-separated values, with specializations for `csv`, `tsv` and `ssv`.
=> Implement `xsv` parser & printer

changelog/next/features/3103--feather-parquet-parsers-printers.md, libvast/builtins/connectors/file.cpp, libvast/builtins/formats/json.cpp, libvast/builtins/operators/print.cpp, libvast/builtins/operators/write_to.cpp, libvast/builtins/query-languages/vast.cpp, libvast/builtins/stores/feather.cpp, libvast/include/vast/data.hpp, libvast/include/vast/pipeline.hpp, libvast/include/vast/plugin.hpp, libvast/src/chunk.cpp, libvast/src/plugin.cpp, libvast/test/data.cpp, libvast/test/printer_plugin.cpp, plugins/parquet/parquet.cpp
This changes the store plugin to implement the parser and printer plugin protocols implicitly, effectively adding Feather and Parquet parsers and printers.
```[tasklist]
```
=> Add Feather and Parquet parsers and printers

libvast/CMakeLists.txt, libvast/builtins/formats/json.cpp, libvast/include/vast/detail/padded_buffer.hpp, libvast/test/json_parser.cpp
1. Fix a frequent crash when parsing long json files due to wrong bytes shifting in padded_buffer
2. Emit a warning in a JSON parser when a field cannot be parsed and continue parsing the current record. It will be up to a user to treat warnings as errors. The unparsable fields will be omitted which will turn them into a NULL value in the table slice if this field is parsed correctly in the next rows.
3. Try to parse the JSON input line by line if the simdjson::iterate_many fails in a specific way (it states that there is more bytes to still parse after a failure than the input. This most likely happens when the JSON is in a very bad state. See newly added unit test for an example)
=> Multiple JSON parsing fixes

changelog/next/features/3123--version-operator.md, libvast/builtins/commands/exec.cpp, libvast/builtins/formats/json.cpp, libvast/builtins/operators/pass.cpp, libvast/builtins/operators/version.cpp, libvast/include/vast/config.hpp.in, libvast/include/vast/pipeline.hpp, libvast/include/vast/plugin.hpp, libvast/src/config.cpp.in, libvast/src/system/spawn_counter.cpp, libvast/src/system/version_command.cpp, web/docs/understand/operators/sources/version.md
This adds a new opeator that yields VAST's version as a single event, and changes `vast exec` to have an implicit sink. It also adds the `--pretty` option to the JSON printer to opt into multi-line output.
=> Introduce a `version` source operator

changelog/unreleased/features/3122--plugin-enabled.md, libvast/include/vast/plugin.hpp, libvast/src/plugin.cpp, libvast_test/src/main.cpp
This PR adds a new `enabled()` virtual method to  the plugin base class, which allows plugins to decide whether or not they want to be initialized at all based on their configuration.
The default implementation checks for the presence of an `enabled` field in the plugin config, and defaults to `true` if that isn't found.
=> Add a new 'enabled()' method to plugin API

.github/workflows/vast.yaml
Fixes a regression from the recent refactoring. The plugins should always be built if vast itself is scheduled to be built.
=> Link the plugin CI jobs to the main vast job

libvast/include/vast/detail/file_path_to_parser.hpp, libvast/src/detail/file_path_to_parser.cpp
This PR fixes the case where `eve.json` file path checks may output the incorrect parser for all files ending with `eve.json`.
=> Extend `file_path_to_parser` check to also include full file path checks

libvast/include/vast/detail/shutdown_stream_stage.hpp
This fixes two issues in the matcher and matcher supervisor that were found while going over the code in a bughunting session.
=> Remove outgoing paths when matcher clients go down

web/docs/setup/build.md
Boost was pointing to the arrow website. Now it uses the proper one.
=> Fix boost lib URL in docs

libvast/builtins/connectors/file.cpp, libvast/include/vast/detail/fdostream.hpp, libvast/include/vast/detail/fdoutbuf.hpp, libvast/include/vast/detail/posix.hpp, libvast/include/vast/plugin.hpp, libvast/src/detail/make_io_stream.cpp, libvast/src/detail/posix.cpp, libvast/src/format/zeek.cpp, scripts/debian/install-dev-dependencies.sh
This PR improves the file saver connector:
- Add home path expansion for paths like `~/foo.json`
- Use a more robust output stream type (and deprecate the old one that is somewhat broken)
- Buffer writes to to the filesystem
- Create directories to output file if they don't exist
- Call `ctrl.abort()` if closing the output file fails instead of silently discarding the error
=> Improve file saver

changelog/next/bug-fixes/3147--rebuilder-stats.md, libvast/builtins/commands/rebuild.cpp
This fixes a few things around rebuild statistics, in particular the `rebuilder.partitions.remaining` metric and the
`rebuild.statistics.remaining` field in the output of `vast status rebuild`:
- Fixed a bug where the rebuilder dereferenced an invalidated iterator into the list of catalog lookup results when no partitions for one schema needed to be rebuilt. This bug only affected metrics, but not the actual partitions used for the rebuilding.
- Removed a trigger for rebuilder metrics that caused metrics to be emitted twice when done, or before some partitions that did not need to be rebuilt were pruned from the list of partitions.
=> Fix remaining partitions counter in the rebuilder

web/blog/apache-arrow-as-platform-for-security-data-engineering/index.md, web/blog/parquet-and-feather-enabling-open-investigations/index.md, web/blog/richer-typing-in-sigma/index.md, web/blog/the-new-rest-api/index.md, web/blog/vast-v1.0/index.md, web/blog/vast-v1.1/index.md, web/blog/vast-v2.2/index.md, web/blog/vast-v3.0/index.md, web/presets/CommercialPlugin.md, web/versioned_docs/version-VAST v3.0/try/quickstart.md
I broke a few links with the v3.1 release. This fixes them.
=> Repair a bunch of broken links in docs

libvast/builtins/operators/enumerate.cpp
Using `emplace_back` on `transformations` causes a build error under Clang 15.0.7:
This PR replaces the `emplace_back` with a `push_back` call to fix Clang builds.
=> Fix `enumerate` causing a build error under Clang 15.0.7

libvast/builtins/operators/enumerate.cpp, libvast/include/vast/concept/parseable/vast/pipeline.hpp
This PR replaces the `aggregation_func_char` parser with the almost identical but more lenient `plugin_name` parser.
=> Replace aggregation_func_char parser with plugin_name parser

changelog/v3.1.0/changes/3076.md
A small oversight; thanks to a user for pointing this one out.
=> Add missing changelog entry to VAST v3.1

web/docs/understand/formats/zeek-json.md
This was correct for `suricata`, but in a weird format for `zeek-json`.
=> Fix description of the zeek-json parser

libvast/builtins/formats/zeek_tsv.cpp, vast/integration/vast_integration_suite.yaml
This PR adds a missing check whether the end of an input has been reached.
=> Fix the `zeek-tsv` parser crashing when encountering empty input

libvast/include/vast/detail/logger_formatters.hpp, libvast/include/vast/expression.hpp, libvast/include/vast/system/query_processor.hpp, libvast/src/data.cpp, nix/vast/plugins/source.json, plugins/web/src/server_command.cpp
A few things that are breaking in this release for us:
- There's now a built-in formatter for `std::optional<T>`, so we can't have our own anymore.
- Enums no longer degenerate to their underlying type implicitly anymore when formatted (which was a bug in all scenarios I've found, so that's good to have fixed).
- Some implicit conversions to string view no longer happen, so we needed to define a formatter for boost's string view.
=> Support building against {fmt} 10.x

libvast/builtins/formats/json.cpp, libvast/include/vast/adaptive_table_slice_builder.hpp, libvast/include/vast/detail/series_builders.hpp, libvast/include/vast/table_slice.hpp, libvast/src/adaptive_table_slice_builder.cpp, libvast/src/detail/series_builders.cpp, libvast/src/format/test.cpp, libvast/src/table_slice.cpp, libvast/test/adaptive_table_slice_builder.cpp, libvast/test/json_parser.cpp, libvast/test/table_slice.cpp, web/docs/understand/formats/json.md, web/docs/understand/formats/zeek-json.md
The zeek-json parser didn't fully work due to lack of unflattening. The JSON parser supports --separator option which is hardcoded to `.` with zeek-json.
vast::type is used in series_builders to preserve attributes when constructed with a known shcema.
=> Support flattened data in JSON parser

libvast/src/validate.cpp
We should not discard subsequent fields in case we come across one that is marked `opaque`.
=> Fix validation with opaque record fields

Dockerfile.extra, nix/overlay.nix
I noticed that plugin doesn't get build for the respective docker images and static binary packages.
=> Add the pipeline manager plugin to edition builds

changelog/next/bug-fixes/3185--compaction-fix-initial-init.md
With this update the compaction plugin now respects weights on first start.
=> Add a changelog entry for the compaction fix

.github/workflows/docker-manual.yaml, .github/workflows/nix-config-base.json, .github/workflows/nix-manual.yaml, .github/workflows/nix.nu, .github/workflows/nix.yaml, .github/workflows/vast.yaml, flake.nix, nix/overlay.nix, nix/vast/plugins/source.json
Here we refactor the nix CI job to make it more flexible.
The API is analogous to the reusable workflow for the Docker build, but we still use a matrix for Nix because the static binary build can't share intermediate build products (yet).
The core logic is implemented in a nushell script, which simplifies the implementation thanks to its rich data model.
=> Migrate the Nix build to a reusable workflow

libvast/builtins/formats/json.cpp, libvast/builtins/formats/xsv.cpp, libvast/builtins/operators/version.cpp, libvast/include/vast/detail/adaptive_table_slice_builder_guards.hpp, libvast/include/vast/detail/series_builders.hpp, libvast/src/detail/adaptive_table_slice_builder_guards.cpp, libvast/src/detail/series_builders.cpp, libvast/test/adaptive_table_slice_builder.cpp
The errors are returned from adaptive_table_slice_builder field/list guards.
These errors are reported to control_plane whenever applicable in the current code base.
Also implemented early return of an error when value casting failed k  adaptive_table_slice_builder that can't change the schema.
=> Report adaptive table slice builder errors to the control plane

nix/vast/plugins/source.json, web/openapi/openapi.yaml
This change reflects the change in the `vast-plugin` PR: https://github.com/tenzir/vast-plugins/pull/50
=> Update the `vast-plugins` submodule pointer to include elaboration on the `managed` pipeline flag

cmake/VASTRegisterPlugin.cmake, libvast/src/application.cpp, libvast/src/start_command.cpp, nix/module.nix, nix/vast/default.nix, vast/CMakeLists.txt, vast/services/systemd/vast.service.in, web/docs/setup/configure.md, web/docs/setup/deploy/aws.md, web/docs/setup/monitor.md, web/docs/setup/tune.md, web/docs/try/process-argus-flow-logs.md, web/docs/try/quickstart.md, web/docs/understand/frontends/sigma.md, web/docs/understand/operators/modifier.md, web/docs/understand/operators/sinks/import.md, web/docs/use/detect/cloud-matchers.md, web/docs/use/detect/execute-sigma-rules.md, web/docs/use/detect/match-threat-intel.md, web/docs/use/export/README.md, web/docs/use/import/README.md, web/docs/use/integrate/rest-api/README.md, web/docs/use/introspect/README.md, web/docs/use/run/README.md, web/docs/use/transform/README.md
We were about premature with calling the node executable `tenzird`. This PR
re-adjusts the new name to `tenzir-node` for clarity. We don't want that users
think of the node as "daemon" but rather as a first-class architectural element.
To streamline the naming, we agreed on the naming pattern `tenzir-*` for
executables from the Tenzir family. Hence, we also renamed `tenzirctl` to
`tenzir-ctl` again.
=> Readjust new binary names

libvast/src/adaptive_table_slice_builder.cpp, libvast/src/detail/adaptive_table_slice_builder_guards.cpp, libvast/src/table_slice.cpp, libvast/test/adaptive_table_slice_builder.cpp
Adding lists into a parent record in adaptive table slice builder could sometimes fail.
The list_guard was constructed as if the type was not known when in fact it was known.
This resulted in not calling arrow::ListBuilder::Append enough times and the output recordBatch would have list entries missing.
Additional changes:
- added offset to table slices that are returned from adaptive table_slice_builder.
- the output of unflatten will inherit offset/timestamp from the original
=> Fix construction of list guard when created from known type field

changelog/next/changes/3194--status-post.md, libvast/builtins/endpoints/status.cpp, libvast/include/vast/node.hpp, libvast/src/node.cpp, nix/vast/plugins/source.json, plugins/web/integration/scripts/serve.sh, plugins/web/integration/tests.yaml, plugins/web/src/server_command.cpp
This switches the HTTP method of the status endpoint to `POST`, and bumps the `vast-plugins` submodule to include changes to the platform protocol.
=> Switch /status to POST

vast/tenzir.cpp
The thread limit does not play well with some pipelines, so it's time that we remove it for the new commands and binaries.
=> Remove thread limit for tenzir and tenzir-node processes

changelog/next/bug-fixes/3207--importer-and-source-shutdown.md, libvast/include/vast/detail/shutdown_stream_stage.hpp, libvast/src/active_partition.cpp, libvast/src/importer.cpp, libvast/src/index.cpp
This fixes a shutdown issue for sources and the importer actor when the outbound source buffer was full and the remote node was shut down.
=> Fix shutdown of sources and importer

.github/workflows/docker-manual.yaml, .github/workflows/nix-manual.yaml, .github/workflows/vast.yaml
This together with deleting the `GCS_BUCKET` secret will fix CI run on the main branch.
The problem is that the bucket name was present in the `vast-nix` jobs matrix, which lead to a rejection of that matrix because its contents matched against that secret.
The solution is to simply put the value into an environment variable instead, because does not contain sensitive information.
=> A collection of CI fixes

changelog/next/changes/3208--arrow-prefix.md, libvast/include/vast/type.hpp, libvast/src/format/arrow.cpp, libvast/src/type.cpp, plugins/parquet/parquet.cpp, python/pyvast/utils/arrow.py, python/tests/test_convert.py, python/tests/test_utils_arrow.py, vast/integration/misc/scripts/print-arrow-batch-size.py, vast/integration/reference/arrow-export/step_01.ref, vast/integration/reference/arrow-export/step_03.ref, vast/integration/reference/arrow-full-data-model/step_01.ref, vast/integration/reference/arrow-import/step_01.ref, vast/integration/reference/arrow-import/step_02.ref
We now register extension types as `tenzir.ip`, `tenzir.subnet`, and `tenzir.enumeration` instead of `vast.address`, `vast.subnet`, and `vast.enumeration`, respectively. Type metadata now has a `Tenzir:` prefix instead of a `VAST:` prefix.
The change is mostly backwards compatible. The old type names and prefixes are still supported. However, reading old Apache Feather V2 and Apache Parquet inside the database directory files using the Python bindings will not work until a `tenzir-ctl rebuild --all` was run.
=> Change Arrow extension type and metadata prefixes

changelog/next/features/3164--pipeline-manager.md, libvast/src/http_api.cpp, nix/vast/plugins/source.json, plugins/web/src/server_command.cpp
This change includes a scaffolding for `vast-plugin`  to include a working TTL mechanism.
=> Include `pipeline-manager` TTL mechanism

changelog/next/breaking-changes/3221--remove-prefix-function.md, libvast/builtins/endpoints/status.cpp, libvast/builtins/operators/serve.cpp, libvast/include/vast/plugin.hpp, libvast/src/node.cpp, nix/vast/plugins/source.json, plugins/web/src/server_command.cpp
It turned out to be more complication than it was worth it; in particular it generated a mismatch between an endpoints external and internal name that could lead to bugs.
=> Remove the `prefix()` function from the REST endpoint plugin API

libvast/builtins/operators/load.cpp, libvast/builtins/operators/save.cpp, libvast/builtins/operators/write_to.cpp
All connectors we currently have should be detached. So instead of making this configurable at the connector level, we instead treat all operators wrapping connectors as detached for now, until someone adds a connector that has different requirements.
=> Make `load` and `save` implicitly detached

.github/workflows/vast.yaml
The Apache Arrow brew package is currently broken because of a breaking update to protobuf.
=> Temporarily disable macOS jobs in CI

libvast/builtins/formats/zeek_tsv.cpp
This change fixes a weird bug that seemed to occur only on macOS devices, but is actually a wrong incrementation of the current line iterator during parsing.
Thank you @dominiklohmann  for the Mac debugging.
=> Continue instead of incrementing generator iterator during zeek-tsv parsing

.github/workflows/docker.yaml, .github/workflows/nix.yaml
This should allow us to remove the secret variable and get rid of the log obfuscation in Github Actions.
=> The dockerhub username is not a secret

nix/vast/plugins/source.json, web/openapi/openapi.yaml
This change is another refresh of the `vast-plugins` submodule pointer, with an updated OpenAPI spec.
=> Include pipeline-manager version without 'managed' flag

libvast/include/vast/plugin.hpp, libvast/src/plugin.cpp
Disabled plugins are erased from the plugin list, but `std::vector::erase` does not call the destructor of the exact element that gets erased, but the moved-from ones at the end. This breaks dynamic plugin management.
The correct fix for this is to clean up resources owned resources in the move assignment operator of `plugin_ptr`. Failing to do so makes them unreachable otherwise.
With that, the call to `erase` works as expected because it moves the subsequent entries on top of the one that gets erased.
=> Prevent a memory leak from disabled plugins

.github/workflows/vast.yaml
CI re-adjusted the CNAME to vast.io after every merge. This PR fixes it, along with a some further renaming.
=> Rename docs building in CI

libvast/src/configuration.cpp
As part of renaming from VAST to Tenzir, we want to allow users to switch from `vast:` in `vast.yaml` to `tenzir:` in `tenzir.yaml`.
This change makes it possible to do so in a backwards compatible manner.
=> Accept 'tenzir' as top-level config section

libvast/builtins/formats/zeek_tsv.cpp, vast/integration/vast_integration_suite.yaml, web/docs/formats/zeek-tsv.md
This change adds a new TQL parser argument `--disable-timestamp-tags` to the `zeek-tsv` printer.
=> Implement '--disable-timestamp-tags' long-form parameter for zeek-tsv printer

libvast/include/vast/http_api.hpp, libvast/src/http_api.cpp, libvast/src/node.cpp, libvast/test/rest_proxy.cpp, nix/vast/plugins/source.json, plugins/web/src/server_command.cpp
A client forwarding incoming requests to the node will generally
not be able to parse all request parameters to the correct
types declared by the endpoint. Therefore, for POST requests
we now have a way of forwarding the raw JSON body to the node.
This also implies the need to split up JSON body parameters and
other parameters in the http_request_description, since the
parsing rules for the latter are slightly different.
Also, increase test coverage of our unit tests.
=> Delay JSON parsing of incoming parameter data

libvast/include/vast/http_api.hpp, nix/vast/plugins/source.json
Ensure we have a valid JSON body for a default-constructed rest response by using '{}' as the default body.
=> Return empty object by default

scripts/install.sh, web/docs/get-started.md
This PR adds an installer shell script so that installing Tenzir will be as simple as:
```bash
curl -L get.tenzir.app | sh
```
This supersedes #2476, a more complex attempt that was Homebrew-inspired.
=> Add installer shell script

libvast/builtins/connectors/directory.cpp, libvast/builtins/connectors/file.cpp, libvast/builtins/formats/cef.cpp, libvast/builtins/formats/json.cpp, libvast/builtins/formats/xsv.cpp, libvast/builtins/formats/zeek_tsv.cpp, libvast/builtins/operators/from_read_load_parse.cpp, libvast/builtins/operators/head.cpp, libvast/builtins/operators/version.cpp, libvast/builtins/operators/where.cpp, libvast/builtins/operators/write_to_print_save.cpp, libvast/src/detail/series_builders.cpp, libvast/src/tql/parser.cpp, libvast/test/adaptive_table_slice_builder.cpp, vast/integration/data/suricata/dns-with-no-schema-column.json, vast/integration/reference/parse-operators/step_02.ref, vast/integration/reference/parse-operators/step_03.ref, vast/integration/reference/parse-operators/step_04.ref, vast/integration/vast_integration_suite.yaml
It seems that --no-infer doesn't work with suricata/zeek-json parsers after pipeline parsing refactor.
This PR fixes this issue + fixes a bug in the series_builder which allowed fields to be cast into a common_type when --no-infer was enabled.
=> Fix JSON parser --no-infer option

web/README.md, web/blog/from-slack-to-discord/index.md, web/docusaurus.config.js, web/src/pages/privacy-statement.md
The primary change in this PR is updating the `data-domain` for Plausible, so that we get correct statistics at now <https://plausible.io/docs.tenzir.com>.
=> Adjust Plausible website tracking

libvast/builtins/formats/json.cpp, libvast/include/vast/to_lines.hpp, libvast/test/json_parser.cpp, vast/integration/reference/parse-operators/step_05.ref, web/docs/formats/json.md, web/docs/formats/suricata.md, web/docs/formats/zeek-json.md
Blocked by: https://github.com/tenzir/tenzir/pull/3252
If the input is NDJSON then we can handle malformed JSON errors in a more sophisticated way.
Given JSON
`
{"a}.?>
{"b" : "d"}
`
We would get an simdjson_error from iterate_many. The parser would give us no information about how many bytes are malformed. From it's PoV the whole input is bad as it expects the well formed JSON documents on the input. We can't always assume that end of a line is a separator of a documents. 
Parsing the first line as JSON we can discard it as it is malformed one.
Handling the second line as a separate JSON document allows us to parse this event properly.
Zeek-json and suricata parsers use --ndjson option by default.
I didn't give a much thought about optimizing the memory allocation when parsing line by …
=> Introduce ndjson mode for json parser
