libvast/builtins/operators/serve.cpp
The `rest_response` already wraps the error message into a JSON object, so there's no need to do it manually in the serve endpoint anymore.
=> Remove double-wrapping of error response in serve endpoint

libvast/src/plugin.cpp
With over 70 native plugins at the time of writing, this log message has become a source of considerable log spam when starting a Tenzir node in verbose logging mode.
=> Only print startup message for non-native plugins

flake.nix, nix/tenzir/default.nix, shell.nix
The static binary has a much smaller runtime closure, so defaulting to that makes first time invocations down to just a few seconds.
=> Use the static build for nix run github:tenzir/tenzir

libvast/src/table_slice.cpp
This fixes a bug reported by @tobim. To reproduce on main, run this:
```
jq --null-input -c '{"foo.bar": 1, "bar": 2}' | tenzir 'read json | flatten'
```
The duplicate detection now works properly with this change.
=> Fix duplicate name detection in `flatten` operator

changelog/next/features/3291--unroll-zeek-tsv-header-parsing-loop.md, libvast/builtins/formats/zeek_tsv.cpp, vast/integration/data/zeek/broken_no_closing_tag.log, vast/integration/data/zeek/broken_no_data_after_open.log, vast/integration/reference/zeek-tsv-pipeline-format/step_14.ref, vast/integration/reference/zeek-tsv-pipeline-format/step_15.ref, vast/integration/vast_integration_suite.yaml
This change unrolls the header parsing loop in the `zeek-tsv` parser to allow early yielding during header parsing.
=> Unroll the Zeek TSV header parsing loop

scripts/debian/postinst, scripts/install.sh
We switch from a link to the latest GitHub release to GCS. GitHub's stable link does not consider pre-releases, but we need to mark ours as such currently.
=> Use a GCS link to fetch the latest release package

libvast/builtins/formats/zeek_tsv.cpp, vast/integration/reference/zeek-tsv-pipeline-format/step_07.ref
The `zeek-tsv` parser has been a troublemaker lately. It was one of the few parsers that we more or less translated directly from the old reader plugin interface to the new parser plugin interface without changing the parsing approach. While that was convenient initially, I personally spent way too many hours debugging things going wrong with this parser lately.
This new approach has a few advantages:
- There exists only a single place in which we advance the input generator, and as such only a single place in which we need to yield an empty on exit.
- The parser now emits helpful diagnostics when something goes wrong.
- Parsing the header is now a lot less strict, and allows for header fields to allow in any order, and for closing tags to be omitted.
- Parsing events no longer copies all …
=> Rewrite the zeek-tsv parser from the ground up

libvast/include/vast/fwd.hpp, libvast/include/vast/plugin.hpp, libvast/src/node.cpp, libvast/src/plugin.cpp, libvast_test/src/main.cpp, nix/tenzir/plugins/source.json
A plugin being enabled or disabled based on the runtime config is not useful except for component plugins.
Removing that bit of state from the generic plugin level rids us form a couple of corner cases, e.g., missing plugins from the `version` operator, or a warning that gets displayed `tenzir` connects to a `tenzir-node` with mismatching plugins.
=> Remove API to dynamically disable plugins

libvast/builtins/commands/exec.cpp, libvast/src/execution_node.cpp, libvast/src/pipeline_executor.cpp
This makes it so we track the total time an execution node is scheduled for, which is a good indicator for performance when compared against (1) the total time spent in `advance_generator()` and (2) the total time since the execution node was started.
=> Add further performance logs to the execution node

libvast/builtins/operators/serve.cpp
To reproduce, run `… | head 0 | serve foo`: This pipeline immediately finishes right before serve, but before this change set a non-null continuation token instead of null. That is now fixed, and the continuation token is now always null when the previous operator is done already.
=> Fix /serve sometimes returning a token instead of null

libvast/src/module.cpp, libvast/src/table_slice_builder.cpp, libvast/test/feather.cpp
This is two changes in one PR for the sake of CI throughput:
First, this fixes the detection of schemas in `$XDG_CONFIG_HOME/tenzir/schemas`.
Second, this fixes a rare crash in table slice builders for schemas like this one:
```go
type test = record {
foo: record {
bar: record {
baz: string, // anything but a record
qux: record {
quux: string,
}
}
}
}
```
A logic bug in the builder caused two entries to be added for `foo.bar`: Once when adding `foo.bar.baz`, and once when adding `foo.bar.qux.quux`.
=> Fix a rare crash in table slice builders

scripts/install.sh
This change fixes the Tenzir installer adding the wrong prefix to the PATH variable to check for successful Tenzir installations.
=> Add /bin to prefix when installing Tenzir via install script

docker-compose.yaml
Running `docker compose up` had a mysterious "exited with code 0" at the end. This is confusing: users may think that the node exited again immediately.
```
$ docker compose up
[+] Building 0.0s (0/0)
[+] Running 3/3
Attaching to main-tenzir-1, main-tenzir-api-1, main-tenzir-node-1
main-tenzir-node-1  |
main-tenzir-node-1  |      _____ _____ _   _ ________ ____
main-tenzir-node-1  |     |_   _| ____| \ | |__  /_ _|  _ \
main-tenzir-node-1  |       | | |  _| |  \| | / / | || |_) |
main-tenzir-node-1  |       | | | |___| |\  |/ /_ | ||  _ <
main-tenzir-node-1  |       |_| |_____|_| \_/____|___|_| \_\
main-tenzir-node-1  |
main-tenzir-node-1  | Visit https://app.tenzir.com to get started.
main-tenzir-node-1  |
main-tenzir-node-1  | [12:09:33.971] node (v4.0.0-rc5) is listening on …
```
=> Remove a confusing exit message for `docker compose up`

libvast/builtins/operators/where.cpp, vast/integration/reference/export-in-pipeline/step_10.ref, vast/integration/reference/export-in-pipeline/step_11.ref
We will probably re-enable this warning in the future, but want to make it more reliable first.
=> Disable `failed to tailor` warning

demo-node/entrypoint.bash
The main fix here is to apply correct quote escaping so that the body is actually valid JSON.
The PR also contains reliability and quality of life improvements:
* Make sure that the HTTP endpoint is listening when the endpoint message is printed
* Enable unsafe pipelines in the demo node
* Make the entrypoint interruptible
* Add names to the demo data pipelines
* Filter out `suricata.stats` events
=> More demo node fixes

changelog/next/features/3329--implicit-sink.md, libvast/builtins/commands/exec.cpp
This is the dual to the already existing feature of the `tenzir` binary that added implicit `save -` or `write json --pretty` to the pipeline if the pipeline ended in bytes or events, respectively: now we also add a source as needed.
=> Use `load -` and `read json` as implicit sources

libvast/builtins/operators/local_remote.cpp
The current implementation of `local_remote_operator::predicate_pushdown` is broken because it does not re-wrap the optimized operator, which means that we are losing the `local`/`remote` modifier.
=> Fix predicate pushdown implementation of `local`/`remote`

libvast/builtins/operators/decapsulate.cpp, vast/integration/reference/pcap-format/step_01.ref
Packet parsing is not a worth emitting a warning. Our `decapsulate` operator is support to work on a best-effort basis: it parses what it can and yields the layers it understands. Otherwise we'd have an incredibly noisy warning stream because there are so many packets we will never be able to parse at the various layers.
=> Do not warn when packet parsing fails

.github/labels.yml, web/docs/contribute/github.md
This PR adds dev-facing docs with instructions on how to sync repo labels.
=> Add developer documentation for label syncing

libvast/src/table_slice.cpp
Queries such as `from file vast/integration/data/zeek/zeek.json read zeek-json`previously spammed the console with unflattening warnings. This PR demotes the warnings to debug messages.
=> Fix noisy unflatten warning

libvast/builtins/formats/json.cpp, libvast/test/json_parser.cpp
When the JSON document is malformed it sometimes crashes when we try to continue to the next document.
It seems safer to just break here. The error message already contains the broken JSON and will be recoverable in the future when we implement "failed to parse" error channel.
=> Fix a crash when the JSON document is malformed

libtenzir/builtins/commands/exec.cpp, libtenzir/builtins/operators/shell.cpp, libtenzir/include/tenzir/execution_node.hpp, libtenzir/include/tenzir/operator_control_plane.hpp, libtenzir/include/tenzir/pipeline_executor.hpp, libtenzir/src/execution_node.cpp, libtenzir/src/node.cpp, libtenzir/src/pipeline.cpp, libtenzir/src/pipeline_executor.cpp, libtenzir/test/json_parser.cpp, libtenzir/test/loader_plugin.cpp, libtenzir/test/pipeline.cpp, libtenzir/test/printer_plugin.cpp, libtenzir/test/saver_plugin.cpp, nix/tenzir/plugins/source.json
This PR solves the issue discussed in https://github.com/tenzir/tenzir/pull/3350#discussion_r1261408423.
=> Add `ctrl.has_terminal()` and use it for `shell`

libtenzir/builtins/formats/json.cpp, libtenzir/test/json_parser.cpp
With ndjson mode introduction the simdjson was no longer guaranteed to have null terminated input JSON.
The current_location() method would return a char pointer to a not null terminated string that would be then interpreted as a null terminated one. This situation lead to crashes
=> Fix invalid buffer access in warnings for unparseable JSON

libtenzir/builtins/formats/json.cpp
Calling get_string() or any get_xxx() on simdjson twice is not allowed.
=> Fix an occasional crash when parsing a string in JSON parser

changelog/next/features/3379.md, libtenzir/builtins/connectors/directory.cpp, web/docs/connectors/directory.md
This PR adds two new options (that are already known from the `file` saver) to the `directory` saver: `--append` and `--real-time`.
=> Add --append and --real-time to directory saver

libtenzir/include/tenzir/cast.hpp, libtenzir/include/tenzir/detail/adaptive_table_slice_builder_guards.hpp, libtenzir/include/tenzir/detail/series_builders.hpp, libtenzir/include/tenzir/detail/type_list.hpp, libtenzir/include/tenzir/type.hpp, libtenzir/include/tenzir/view.hpp, libtenzir/src/adaptive_table_slice_builder.cpp, libtenzir/src/detail/adaptive_table_slice_builder_guards.cpp, libtenzir/src/detail/series_builders.cpp, libtenzir/src/view.cpp, libtenzir/test/adaptive_table_slice_builder.cpp, libtenzir/test/cast.cpp
In this PR we allow the some form of a common type casting inside a records and lists.
Previously changing a field inside a nested record was considered as a casting of a `record_type` so it was not implemented.
Same with the lists. A `list<int>` changing to `list<string>` is a list casting, which was not planned to be implemented yet.
It seems that the live data has a lot of `ip` -> `string` conversions that must be supported. These conversions occurr inside the lists and inside the nested record so this type of casting should be supported.
In this PR we allow:
- changing of a list_type when the added value requires the common type casting. E.g when we have a `list<ip>` we may add a "www.tenzir.com". This is inferred as a string type and the whole list must be cast to a `list<string>` in …
=> Allow list builder to change type

libtenzir/include/tenzir/detail/series_builders.hpp, libtenzir/src/adaptive_table_slice_builder.cpp, libtenzir/src/detail/series_builders.cpp, libtenzir/test/adaptive_table_slice_builder.cpp
The AppendArraySlice API shouldn't be used with the extension types.
In this change we no longer use it.
The row_guard::cancel_row() is also calling fill_nulls() now. All the fields that were not added to the row would have different length.
The code expects fill_nulls() to be called after each row is inserted. This logic is implemented in row_guard DTOR, which will only be run after the cancel_row() call.
=> Don't use AppendArraySlice in remove_last_row

changelog/next/changes/3377--reduce-passive-partition-cache-size.md, changelog/next/changes/3377--reduce-rebuild-frequency.md, libtenzir/builtins/commands/rebuild.cpp, libtenzir/include/tenzir/defaults.hpp, libtenzir/src/application.cpp, tenzir.yaml.example
This reduces the default frequency in which automatic rebuilds are triggered from 5 Minutes to 2 Hours, and decouples the option from the active partition timeout.
We also demote the number of cached query partitions to 1, to avoid holding multiple copies of the same data in memory.
=> Improve low-load memory consumption

libtenzir/builtins/operators/serve.cpp
When a pipeline is at its end, the `continuation_token` is left as an empty string.
However, that is also the expected value of the continuation token for the initial request to the serve endpoint.
So if a client repeats the initial request (i.e. because the response was dropped by the network) after a pipeline is done but before its state is ultimately removed, the serve manager will assume this is a valid initial request and assign a new continuation token, getting stuck in an endless loop until the state is finally cleaned up.
=> Use a distinctive marker for the final continuation token

libtenzir/builtins/operators/serve.cpp
This PR make a `constexpr std::string` a `constexpr std::string_view` to support Clang.
=> Support more compilers with constexpr string_view

tenzir.yaml.example, web/blog/shell-yeah-supercharging-zeek-and-suricata-with-tenzir/index.md, web/docs/operators/transformations/shell.md, web/docs/operators/user-defined.md
Otherwise newlines in the `shell` operator may mess with some applications.
Note to the reviewer: I snuck in another UDO definition in the `tenzir.yaml.example`, based on our last blog post.
=> Switch to YAML flow scalars

libtenzir/builtins/endpoints/ping.cpp, libtenzir/builtins/endpoints/version.cpp, web/openapi/openapi.yaml
In order to implement HTTP health checks, we want an endpoint that always returns instantly and puts no strain on the system. The existing `/status` is not suited for this, since it can take up to 10s to respond if actors are not responsive.
The ping response contains the node version as payload in order to give a low-effort alternative to the `version` operator for developers trying to determine the version of a remote node.
=> Create a new /ping endpoint

nix/tenzir/plugins/source.json
This change bumps the submodule pointer to include an important fix for the 4.0.0-rc9 release.
=> Bump submodule pointer to include the /pipeline/update endpoint fixes

libtenzir/builtins/operators/from_load_read.cpp, libtenzir/builtins/operators/to_write_save.cpp, libtenzir/include/tenzir/pipeline.hpp
Instead of showing the full internals of operators for type clashes, it makes a lot more sense to just show the name to keep the error message legible.
=> Improve error message for operator type clashes

scripts/debian/postinst
Looks like migrations from VAST to Tenzir were broken between rc9 and rc10 :see_no_evil: 
I don't think anyone was affected by this.
=> Revert renaming that broke the migration logic

libtenzir/src/detail/series_builders.cpp
This is a hotfix commit to prevent the adaptive table slice builder from crashing on certain inputs. The problematic fields will now be dropped instead. This patch is meant as an urgent fix so the JSON input format is usable while we are working on a proper fix.
=> Prevent a crash in the JSON parser

libtenzir/src/pipeline_executor.cpp
The pipeline executor has a check that aborts startup if a pipeline is started with a non-void output type (e.g. `version`). However, there was a `return` missing after this check, such that the execution continued. This could sometimes lead to signaling a successful pipeline start, even though we already emitted an error.
=> Fix pipeline executor output check

plugins/web/README.md, plugins/web/src/specification_command.cpp, web/openapi/openapi.yaml
This change fixes a mishap as a result of the VAST->Tenzir renaming.
=> Replace the wrong "generate-token" commands in the documentation with the correct versions

web/src/pages/sbom.tsx
This PR creates a static route to our SBOM so that we can link it reliably.
=> Add fixed route to SBOM

libtenzir/builtins/formats/xsv.cpp
This fixes a hang in the XSV parser when the header was in the middle of a chunk boundary. This usually happens for really small inputs.
=> Fix hang in XSV parser for small inputs

schema/concepts/suricata.yaml, version.json
We noticed today that Tenzir ships a `net.domain` concept referencing the EVE JSON field `suricata.tls.sni` which does not exist in the schema. It should be `suricata.tls.tls.sni` according to the schema definition:
```
type suricata.tls = suricata.component.common + record {
tls: record {
sni: string,
session_resumed: bool,
subject: string,
issuerdn: string,
serial: string,
fingerprint: string,
ja3: suricata.component.ja3,
ja3s: suricata.component.ja3,
notbefore: time,
notafter: time
}
}
```
For the sake of completeness we also add it to the `net.hostname` concept, as it serves a similar purpose as `suricata.http.http.hostname`  which is also in that concept.
=> Fix Suricata TLS SNI field name in concepts

version.json
The rev was accidentally changed in a918c20e82cc88d36b9986dece34a8dea30cbcdd.
=> Reset the tenzir-plugins submodule

.github/workflows/tenzir.yaml, Dockerfile, nix/tenzir/plugins/source.json, web/docs/user-guides/run-a-pipeline/README.md
The plugin isn't working all too well currently, and has basically been in maintenance mode for a while now. This disables it until we have time to bring it back properly. Note that the plugin had already been disabled for quite some time for all publicly available builds, so this change only affects developers.
=> Disable the inventory plugin

changelog/next/bug-fixes/3470--exec-node-tweak.md, libtenzir/builtins/aspects/build.cpp, libtenzir/builtins/aspects/connectors.cpp, libtenzir/builtins/aspects/dependencies.cpp, libtenzir/builtins/aspects/formats.cpp, libtenzir/builtins/aspects/operators.cpp, libtenzir/builtins/aspects/plugins.cpp, libtenzir/builtins/aspects/version.cpp, libtenzir/builtins/commands/exec.cpp, libtenzir/include/tenzir/pipeline.hpp, libtenzir/src/execution_node.cpp
This makes the following changes to execution nodes:
- Reduce batch timeout from 250ms to 10ms with exponential backoff to 2s. Execution nodes are now always scheduled after the timeout hits, assuming that the previous operator does not block indefinitely.
- Remove the never correctly implemented logic to advance generators multiple times per scheduled run of an execution node.
Additionally, this fixes the operator location of some aspects.
=> Tweak the execution node behavior

web/openapi/openapi.yaml
This PR is a simple addition to the API docs. Somehow the `pause` action did not make it during the sequential pipeline manager PR.
=> Add the missing "pause" pipeline action to the API docs

.github/workflows/nix.yaml
Without adding `--inputs-from` we always get the latest versions of the dependencies that are currently available in `nixpkgs`. Explicitly using the revision from the flake is an easy way to pin and avoid unexpected breakage.
=> Use pinned nixpkgs for nushell script deps

changelog/next/features/3479--rendered-diagnostics-and-failed-state.md, nix/tenzir/plugins/source.json, plugins/web/src/specification_command.cpp, web/openapi/openapi.yaml
Another submodule pointer bump.
=> Bump the tenzir-plugins submodule pointer to include the pipeline manager's failure and rendered diagnostics functionality

.github/workflows/tenzir.yaml, changelog/next/features/3138--sigma-operator.md, libtenzir/src/pattern.cpp, nix/tenzir/default.nix, plugins/sigma/CMakeLists.txt, plugins/sigma/include/sigma/parse.hpp, plugins/sigma/src/parse.cpp, plugins/sigma/src/plugin.cpp, plugins/sigma/tests/tests.cpp, web/docs/operators/transformations/sigma.md
The `sigma` operator takes a path to a directory or a single *.yaml or *.yml file, takes all input events, and applies the sigma rule. The resulting events contain matches for the Sigma rule and the rule itself.
=> Introduce an experimental `sigma` operator

scripts/install.sh
This change is a quick fix for the Linux node install script that still used deprecated operators.
=> Fix the deprecated operator in the Linux node install script

.github/workflows/style-check.yaml, ansible/roles/tenzir/meta/argument_specs.yaml, ansible/roles/tenzir/tasks/main.yaml, ansible/roles/tenzir/tasks/tenzir-node-service-overrides.conf.j2, ansible/roles/tenzir/tenzir-node.service
* Clean leftover the `systemd` service overrides when deploying
* Fix the `ReadWritePaths` override syntax
* Add an argument_specs file to document the role parameters
=> A few minor ansible role fixes

web/docs/connectors/ftps.md, web/docs/connectors/https.md
=> Fix connector names in docs for `https` and `ftps`

.github/workflows/update-sbom.yaml, flake.nix
The `id-token` permission does actually not accept the value `read`.
See https://github.com/github/docs/issues/26481.
=> Fix and improve the "Update SBOM" GHA Workflow

changelog/next/changes/3513.md, changelog/next/features/3513.md, libtenzir/builtins/formats/pcap.cpp, libtenzir/include/tenzir/pcap.hpp, libtenzir/src/execution_node.cpp, libtenzir/src/pcap.cpp, plugins/nic/src/plugin.cpp, tenzir/integration/reference/pcap-format/step_04.ref, tenzir/integration/reference/pcap-format/step_05.ref, tenzir/integration/tests.yaml, web/blog/tenzir-v4.2/index.md, web/docs/connectors/nic.md, web/docs/formats/pcap.md
This PR equips the `pcap` parser with the capability to parse a stream of *concatenated* PCAPS.
This means that you can now do the following:
```bash
cat *.pcap | tenzir 'read pcap'
```
=> Support parsing of concatenated PCAPs

docker/quarto/Dockerfile, libtenzir/src/detail/installdirs.cpp.in, scripts/debian/install-dev-dependencies.sh
This PR updates the quarto Dockerfile which started to fail due to remote changes.
It also switches to the new official installation method of NodeJS.
=> Fix the documentation CI job

nix/tenzir/default.nix, plugins/zmq/CMakeLists.txt
`nix run .#tenzir` was broken for multiple reasons. Each commit fixes one of them.
=> Fixes for building dynamic executables with Nix

changelog/next/features/3517.md, libtenzir/include/tenzir/detail/posix.hpp, libtenzir/src/detail/pid_file.cpp, libtenzir/src/detail/posix.cpp, plugins/nic/src/plugin.cpp, web/blog/tenzir-v4.2/index.md, web/docs/operators/sources/show.md
This PR makes `show nics` possible by turning the `nic` plugin into an aspect plugin.
=> Support `show nics` to see network interfaces

nix/overlay.nix
The recent addition of the s3 connector causes the linker to add symbols from the AWS crypto abstraction layer library. This lib uses the `dlopen` and `dlclose` functions even when built as a static library - which is possible. What's more, the return value of those functions is asserted, causing the tenzir executables to abort during initialization.
The good news is that this can be worked around by disabling the problematic assert. For that we pull a patch that does exactly that from an open upstream pull request.
Fixes https://github.com/tenzir/issues/issues/885.
=> Fix program startup of the static binary

libtenzir/builtins/connectors/s3.cpp, plugins/gcs/src/plugin.cpp
This PR adds missing scheme omission to the `s3` and `gcs` loaders.
=> Add scheme omission to s3 and gcs loaders

changelog/next/changes/3515--decapsulate-keep-data.md, changelog/next/features/3515--decapsulate-keep-data.md, libtenzir/builtins/formats/pcap.cpp, libtenzir/builtins/operators/decapsulate.cpp, tenzir/integration/reference/pcap-format/step_00.ref, tenzir/integration/reference/pcap-format/step_05.ref, tenzir/integration/tests.yaml
This changes the `decapsulate` operator to keep the `data` field in its incoming packet events that rather than dropping it. It does so without copying the data.
=> Do not drop the `data` field in `decapsulate`

changelog/next/bug-fixes/3535.md, libtenzir/builtins/connectors/curl.cpp
This PR fixes a bug with the `http` loader. Adding customer headers didn't work prior to this fix.
=> Fix processing of http arguments

changelog/next/bug-fixes/3537--implement-printer-serialization-plugin-for-store-plugins.md, libtenzir/include/tenzir/plugin.hpp, libtenzir/src/plugin.cpp
This PR fixes `store_plugin`s being unusable due to assertions being fired during normal usage.
=> Implement serialization_plugins for store_plugins

libtenzir/src/version.cpp
This change adds the `/pipeline/launch` endpoint to the `tenzir_features()` to help the app discern whether unifying the "run & deploy" workflow in the app is possible.
=> Add the `/pipeline/launch` endpoint to the `tenzir_features()`

libtenzir/src/type.cpp, libtenzir/test/type.cpp
=> Implement `type::to_definition()` for the null type

changelog/changes/3536.md, plugins/zmq/src/plugin.cpp
This PR disables 0mq socket lingering to enable instant freeing of resources.
=> Disable 0mq socket lingering

changelog/next/bug-fixes/3553.md, plugins/web/src/restinio_response.cpp, plugins/web/src/server_command.cpp
This change fixes an obscure crash when a web server is shutting down while receiving requests at the same time.
=> Fix timing-related crashes in the `web` plugin

changelog/next/features/3541.md, libtenzir/src/http_api.cpp, libtenzir/src/version.cpp, nix/tenzir/plugins/source.json, plugins/web/src/specification_command.cpp, web/openapi/openapi.yaml
This PR is a submodule pointer bump + `http_api` support for pipeline labels in HTTP requests.
=> Add pipeline label support to the main repository

schema/concepts/zeek.yaml, schema/types/zeek.schema
Small thing that I noticed while analysing some Zeek data. The smb_mapping logs contain flat id keys and concepts don't work.
=> Add structured support for the smb_mapping Zeek log

libtenzir/builtins/operators/serve.cpp, libtenzir/include/tenzir/defaults.hpp
This is no longer needed, as the platform can now correctly handle responses over 128 KiB in size.
=> Drop workaround for oversized responses in serve

libtenzir/builtins/operators/compress_decompress.cpp
This was an issue only in Debug mode, so it's not really worth a changelog entry. The decompressed buffer is not guaranteed to be larger than the compressed buffer, as they can also be the same size. This usually happens for very small chunk sizes.
=> Fix an assertion failure in the `decompress` operator

web/docs/setup-guides/deploy-a-node/README.md
This PR fixes the download link for static binaries from the `main` branch.
=> Fix download link to static binary from main

.dockerignore, changelog/next/bug-fixes/3578.md, libtenzir/builtins/formats/zeek_tsv.cpp, tenzir/functional-test/data/zeek/duplicate_field_name.log, tenzir/integration/reference/zeek-tsv-pipeline-format/step_16.ref, tenzir/integration/tests.yaml
Fixes https://github.com/tenzir/issues/issues/933
We don't expect valid Zeek TSV data to ever contain duplicate field names, so if we encounter some, we can error with good conscience. Without this fix, there's a crash later on.
=> Check for duplicate field names in zeek_tsv_parser

changelog/next/features/3580--show-partitions-events.md, libtenzir/builtins/aspects/partitions.cpp
One simple use case for this is wanting to see how many events are stored at the node per schema.
```
show partitions
| summarize events=sum(events) by schema
| sort events desc
```
=> Add `events` field to output of `show partitions`

libtenzir/builtins/operators/serve.cpp, nix/tenzir/plugins/source.json
This changes the `/serve` endpoint to keep track of previously known but expired serve ids to display a richer error message. Previously, this was indistinguishable from unknown serve ids.
Additionally, this silences a bogus warning for pipelines with an expired TTL.
=> Improve error in `/serve` endpoint for expired pipelines

libtenzir/builtins/commands/exec.cpp
We can't assume that `en_US.UTF-8` is available at runtime. We format metrics in a locale-agnostic way instead.
=> Make metrics formatting locale agnostic

changelog/next/features/3596--show-serves.md, libtenzir/builtins/operators/serve.cpp, web/docs/operators/sources/show.md
The new `serves` aspect shows all currently active serve ids in the `/serve` API endpoint.
I developed this when debugging the TTL problems last week, and I figured it was useful enough to just be added to the codebase with a small disclaimer in the docs.
=> Add `show serves` for debugging the `serve` operator

libtenzir/include/tenzir/chunk.hpp, libtenzir/include/tenzir/detail/legacy_deserialize.hpp, libtenzir/src/chunk.cpp
This addition allows for transferring metadata about chunks in-stream. Specifically, this adds a metadata field for the content type, which is the missing piece for tenzir/tenzir#3539.
The alternative to this approach is to forbid `write <format> | save <connector>` in favor of always requiring the combined `to <connector> write <format>`. However, the latter does not compose as freely as transferring the content type in-stream.
What's left is to make use of the content type, but I will leave that to the linked PR adding HTTP(S) savers.
=> Add an optional content type to chunk

changelog/next/bug-fixes/3599--predicate-pushdown.md, libtenzir/builtins/aspects/build.cpp, libtenzir/builtins/formats/lines.cpp, libtenzir/builtins/operators/export.cpp, libtenzir/include/tenzir/catalog.hpp, libtenzir/src/catalog.cpp, libtenzir/src/execution_node.cpp, libtenzir/src/expression.cpp, libtenzir/src/passive_partition.cpp, libtenzir/test/catalog.cpp, nix/tenzir/plugins/source.json
This is five fixes in one PR:
1. Predicate pushdown did not work in v4.3; this supersedes my previous attempt in #3590
2. The catalog expected expressions to be already normalized and validated, which for non-normalized expressions caused all partitions to be returned
3. We introduced a race in #3562 that caused operators to sometimes hang on shutdown; this mostly occurred in release builds with high-volume pipelines at the process boundary (no changelog entry for this one as we never released with this bug)
4. The long option `--skip-empty` for `read lines` now works as expected
5. We now include the feature flags in `show build`
=> Fix predicate pushdown in `export` and other small fixes

plugins/fluent-bit/functional-test/reference/tests/test_Print_data_in_the_fluent-2dbit_output_format/step_00.ref, plugins/fluent-bit/functional-test/tests/tests.bats
This PR removes a flaky Fluent Bit integration test. The flakiness is a result of the time-based ramp-up and teardown of the Fluent Bit mainloop. The API doesn't have wait-until-complete semantics, so races may occur.
Removing this test is okay because we have a similar test that covers the tested functionality.
=> Remove flaky integration test

changelog/next/bug-fixes/3605--fix-zeek-tsv-subnet.md, changelog/next/bug-fixes/3606--fix-zeek-tsv-subnet.md, libtenzir/builtins/formats/zeek_tsv.cpp
Correcting a small oversight from the the zeek-tsv parser rewrite.
=> Fix parsing of subnet columns in zeek-tsv

plugins/yara/functional-test/reference/tests/test_accumulate_chunks_and_match_when_the_input_exhausted/step_00.ref, plugins/yara/src/plugin.cpp, web/blog/matching-yara-rules-in-byte-pipelines/index.md
This PR simplifies the chunk management, switching away from the incremental interface and simply accumulating the input in a buffer to ensure that we perform a scan on a single chunk.
=> Do not assume YARA can match across chunks

plugins/parquet/parquet.cpp
Arrow's `arrow::io::BufferReader` complains when being constructed from a `arrow::Buffer` instead of a `std::shared_ptr<arrow::Buffer>` since the recent release of Arrow 14.0.0. The change is entirely backwards compatible.
=> Fix a deprecation warning when using Arrow >= 14.0

changelog/next/bug-fixes/3629.md, libtenzir/builtins/connectors/directory.cpp, libtenzir/builtins/connectors/file.cpp
This makes the language as a whole more consistent. This is how the option was originally specified, and somehow that slipped through in review and hasn't been noticed before.
Categorizing this as a bug fix since it aligns the connector with the documentation.
=> Rename `--appending` option for `save file` to `--append`

.github/workflows/docker-config-base.json, Dockerfile, demo-node/entrypoint.bash, demo-node/import.bash, demo-node/load.bash
- Push the demo node image to DockerHub because it can be handy to play with the Demo node locally. 
- Change the import to use the http operator. To make that possible we also switch to the compressed file data instead of the tarballs.
- Remove the intermediate image layer with data files
=> Demo node improvements

.github/workflows/docker.yaml
Originally we considered putting enterprise features in the demo node, so we needed to enforce a private registry.
However, the current demo node is just the community addition in combination with a public dataset, so
we can drop this restriction for now.
=> Allow pushing the demo node image to public registries

changelog/next/features/3634--numeric-literals.md, libtenzir/include/tenzir/expression.hpp, libtenzir/src/concept/parseable/tenzir/expression.cpp, libtenzir/src/expression_visitors.cpp, libtenzir/src/type.cpp, libtenzir/test/expression_parseable.cpp, web/docs/language/expressions.md
This changes expression evaluation for queries with numeric literals in two ways:
1. Queries with a numeric literal against a field or type extractor no longer require the field's type and the numeric literal's inferred type to match exactly. This allows for querying without knowing whether a value is a signed or unsigned integer or a floating point number.
2. Queries with value predicates (i.e., just a value without a field or type to compare against) now automatically expand to a disjunction covering all three numeric types when the value predicate is a numeric literal.
```[tasklist]
```
=> Relax type restrictions for queries with numeric literals

changelog/next/bug-fixes/3633--ensure-exporter-metrics.md, libtenzir/src/exporter.cpp
Before this change metrics from the exporter were not sent in case the exporter itself hit a completion condition (either by shipping the requester number of events or hitting a timeout), while the database was still able to provide more results.
We solve the issue by moving the complete metrics reporting into a code path that is guaranteed to be called once.
=> Ensure exporter metrics don't get lost

libtenzir/builtins/connectors/curl.cpp
This is an oversight from https://github.com/tenzir/tenzir/pull/3584.
=> Fix `http` loader use-after-free

changelog/next/changes/3639--build-time-and-bool-synopses.md, libtenzir/src/partition_synopsis.cpp
This changes the catalog to always build time and bool synopses. These are really compact, so there is no downside to having them always enabled.
=> Always enable time and bool synopses

changelog/next/changes/3616--prefix-matching.md, libtenzir/builtins/operators/drop.cpp, libtenzir/builtins/operators/pseudonymize.cpp, libtenzir/builtins/operators/put_extend_replace.cpp, libtenzir/builtins/operators/rename.cpp, libtenzir/builtins/operators/select.cpp, libtenzir/include/tenzir/table_slice.hpp, libtenzir/src/table_slice.cpp
This PR enables `select <field_of_record_type>` and similar examples by using prefix matching instead of suffix matching. This is a breaking change because it also makes it so that `select bar` does not select the inner field of `{"foo": {"bar": 42}}` anymore. However, we wanted to make this change anyway in the near future.
Some uses of `record_type::resolve_key_suffix` still remain for now. In particular, expressions are still resolved using suffix semantics.
=> Use prefix matching instead of suffix matching

changelog/next/features/3642--operator-blocklist.md, libtenzir/src/application.cpp, libtenzir/src/configuration.cpp, libtenzir/src/plugin.cpp, tenzir.yaml.example, web/docs/command-line.md, web/docs/operators/modifier.md
The `tenzir.disable-plugins` option is a list of names of plugins and builtins to explicitly forbid from being used in Tenzir.
For example, adding `export` will prohibit use of the `export` operator builtin, and adding `kafka` will prohibit use of the `kafka` connector plugin. This allows for a more fine-grained control than the `tenzir.allow-unsafe-pipelines` option.
```[tasklist]
```
=> Add an operator blocklist

web/docs/operators/sources/fluent-bit.md
And link to the correct upstream documentation page.
=> Fix the fluent-bit elasticsearch example

web/docusaurus.config.js
This PR brings back the dark/light mode toggle in the docs.
When sharing screens or giving demos, it's arguably easier to quickly click a button than changing the system settings.
=> Bring back dark/light mode toggle

changelog/next/features/3640--summarize-empty-input.md, libtenzir/builtins/aggregation-functions/all.cpp, libtenzir/builtins/aggregation-functions/any.cpp, libtenzir/builtins/aggregation-functions/count.cpp, libtenzir/builtins/aggregation-functions/count_distinct.cpp, libtenzir/builtins/aggregation-functions/distinct.cpp, libtenzir/builtins/aggregation-functions/max.cpp, libtenzir/builtins/aggregation-functions/min.cpp, libtenzir/builtins/aggregation-functions/sample.cpp, libtenzir/builtins/aggregation-functions/sum.cpp, libtenzir/builtins/operators/summarize.cpp, libtenzir/include/tenzir/plugin.hpp, tenzir/integration/reference/summarize-all-none-some/step_00.ref, tenzir/integration/reference/summarize-all-none-some/step_02.ref, tenzir/integration/reference/summarize-all-none-some/step_04.ref, tenzir/integration/reference/summarize-all-none-some/step_06.ref, tenzir/integration/reference/summarize-all-none-some/step_07.ref
If the `summarize` operator has no `by` clause, it now returns a result even if there is no input. For example, `summarize num=count(.)` returns an event with `{"num": 0}`. Aggregation functions which do not have a single default value, for example because it would depend on the input type, return `null`.
=> Improve `summarize` result for empty inputs

changelog/next/features/3608--uri-loader.md, libtenzir/builtins/connectors/file.cpp, libtenzir/builtins/operators/from_load_read.cpp, libtenzir/builtins/operators/to_write_save.cpp, libtenzir/include/tenzir/detail/loader_saver_resolver.hpp, libtenzir/include/tenzir/plugin.hpp, libtenzir/src/detail/loader_saver_resolver.cpp, libtenzir/src/plugin.cpp, plugins/gcs/src/plugin.cpp, tenzir/integration/reference/parse-operators/step_03.ref, tenzir/integration/reference/parse-operators/step_11.ref, tenzir/integration/reference/parse-operators/step_12.ref, tenzir/integration/reference/parse-operators/step_13.ref, tenzir/integration/reference/parse-operators/step_14.ref, tenzir/integration/reference/parse-operators/step_15.ref, tenzir/integration/reference/parse-operators/step_16.ref, tenzir/integration/reference/parse-operators/step_17.ref, tenzir/integration/reference/parse-operators/step_18.ref, tenzir/integration/reference/parse-operators/step_19.ref, tenzir/integration/tests.yaml, web/docs/connectors.md, web/docs/connectors/gcs.md, web/docs/formats/yaml.md, web/docs/operators/sinks/save.md, web/docs/operators/sinks/to.md, web/docs/operators/sources/from.md, web/docs/operators/sources/load.md, web/versioned_docs/version-Tenzir v4.3/formats/yaml.md, web/versioned_docs/version-Tenzir v4.4/formats/yaml.md, web/versioned_docs/version-Tenzir v4.5/formats/yaml.md
Supersedes https://github.com/tenzir/tenzir/pull/3500, related to https://github.com/tenzir/issues/issues/328
In this PR:
- `OP <uri>` is mapped to `OP <uri-scheme> <rest-of-uri>`, where `OP` is one of `(from, load, to, save)`, and `<uri>` is a RFC 3986 -compliant URI.
- `OP <something-else>` is mapped to `OP file <something-else>` if `<something-else>` isn't a possible plugin name (doesn't conform to the pattern `[A-Za-z0-9-_]*`)
This effectively means, that the following mappings are implemented:
- `from https://example.com/foo` -> `from https example.com/foo`
- `from gs://foo/bar` -> `from gcs gs://foo/bar`
- `from file:///tmp/file` -> `from file /tmp/file`
- `from /tmp/file` -> `from file /tmp/file`
- `from ./local-file` -> `from file ./local-file`
- `from local-file` -> error (no …
=> Add `from/load/to/save <uri/file>`

changelog/next/features/3651--yield-operator.md, libtenzir/builtins/operators/yield.cpp, tenzir/integration/reference/yield-operator/step_00.ref, tenzir/integration/reference/yield-operator/step_01.ref, tenzir/integration/reference/yield-operator/step_02.ref, tenzir/integration/reference/yield-operator/step_03.ref, tenzir/integration/reference/yield-operator/step_04.ref, tenzir/integration/reference/yield-operator/step_05.ref, tenzir/integration/tests.yaml, web/docs/operators/transformations/yield.md
The remaining todos are mostly something for the language revamp. Also, the operator is intentionally a bit under-specified because we are not sure yet how exactly nulls, unknown fields, etc., will be handled eventually.
=> Add `yield` operator

changelog/next/changes/3658--ingress-egress-redef.md, libtenzir/builtins/operators/discard.cpp, libtenzir/builtins/operators/export.cpp, libtenzir/builtins/operators/import.cpp, libtenzir/builtins/operators/local_remote.cpp, libtenzir/include/tenzir/pipeline.hpp, libtenzir/src/execution_node.cpp, nix/tenzir/plugins/source.json, plugins/web/src/specification_command.cpp, web/openapi/openapi.yaml
We do not want to count egress or ingress for discard, export, and import. This makes it so their metrics are specifically annotated to be internal, as they are technically not ingress or egress.
=> Consider discard, export, and import as internal operators

plugins/velociraptor/CMakeLists.txt
Abseil versions 2023 and later require C++14 or newer. The previous versions only required C++11. `libprotobuf`, which depends on Abseil, only declares that it needs C++11, and doesn't check what Abseil needs. This caused `velociraptor-proto` to be built with `-std=gnu++11`, leading to errors in Abseil.
Abseil version 2023.* is shipping with Fedora 39, which is why I ran into this. No Ubuntu version ships with 2023.*, yet.
No other changes seem to be necessary for everything to work.
=> Fix velociraptor-plugin build with Abseil 2023.*

changelog/next/features/3666--serve-latency.md, libtenzir/builtins/operators/serve.cpp, libtenzir/include/tenzir/defaults.hpp, web/docs/operators/sinks/serve.md, web/openapi/openapi.yaml
This adds a new parameter 'min_events' to the `/serve` endpoint, with the semantics that the endpoint will return a result as soon as `min_events` events have arrived, regardless of the configured `timeout` and `max_events`.
The idea is to allow long polling, by specifying a long timeout and a low value for `min_events`. The defaults for the endpoint are adjusted accordingly.
=> Add 'min_events' parameters to /serve endpoint

version.json
With the v4.5 release, we dropped dense indexes and enabled more sparse indexes by default. In order to make existing deployments take advantage of these improvements, we should've bumped the partition version—but we didn't. So this makes it so that as of the next release existing deployments will take care of upgrading partitions so that we can be sure that no more dense indexes exist after some time.
=> Bump the partition version

changelog/next/features/3650--show-all.md, libtenzir/builtins/operators/show.cpp, nix/tenzir/plugins/source.json, tenzir/integration/reference/parse-operators/step_00.ref, tenzir/integration/reference/parse-operators/step_01.ref, tenzir/integration/reference/parse-operators/step_02.ref, web/docs/operators/sources/show.md
This makes the aspect in `show <aspect>` optional. When the aspect is not specified, all aspects are used automatically.
=> Support `show`-ing all aspects at once

.github/workflows/nix-config-base.json, .github/workflows/nix.nu, .github/workflows/nix.yaml, CMakeLists.txt, CMakePresets.json, cmake/TenzirPackage.cmake, flake.lock, flake.nix, libtenzir/CMakeLists.txt, libtenzir/src/store.cpp, nix/fix-protobuf-dep.patch, nix/overlay.nix, nix/restinio/default.nix, nix/tenzir/default.nix, plugins/fluent-bit/cmake/Findfluentbit.cmake, scripts/install.sh, scripts/macOS/install-dev-dependencies.sh, shell.nix, tenzir/CMakeLists.txt
This PR makes it possible to build macOS packages that only need standard system libraries to run.
Our approach uses the same Nix dependency management as for the static Linux package under the hood.
=> Build arm64 macOS packages

libtenzir/builtins/operators/serve.cpp, web/docs/operators/sinks/serve.md, web/openapi/openapi.yaml
I got a litle bit confused by the behavior of the new `min_events` and its default value of 1. I think a bit more docs about the semantics of the endpoint would help a bit.
=> Improve the `/serve` API docs

.github/workflows/tenzir.yaml, scripts/macOS/install-dev-dependencies.sh, web/blog/parquet-and-feather-writing-security-telemetry/index.qmd
We often run into problems when a plugin job runs on a different macOS action runner image than the main tenzir build. In that case some of the linked dependencies may have a different `soversion`, which causes the tests to fail.
This change moves all plugins to build in bundled mode, sidestepping the problem.
=> Build plugins in bundled mode on macOS

changelog/next/features/3608--uri-loader.md, changelog/next/features/3653--file-extension-loader.md, libtenzir/src/detail/loader_saver_resolver.cpp, web/docs/connectors.md, web/docs/connectors/gcs.md, web/docs/operators/sources/from.md, web/docs/operators/sources/load.md
Related discussion https://github.com/tenzir/tenzir/pull/3675#discussion_r1410691025
The `s3` connector still uses the term "URI", both in the docs, and in the implementation, even though "URL" would be more precise. I left that out of this drive-by fix, since they have been there for longer than this newfangled URL-connector stuff.
=> "URI" -> "URL" in docs and loader_saver_resolver.cpp

python/pyproject.toml, version.json
This commit is was created with /scripts/prepare-release.
* Updated `/version.json` to v4.6.1 and the expected rev-count of the merge commit to 18880.
* Updated the python bindings version in `/python/pyproject.toml` to v4.6.1.
=> Prepare repository for Tenzir v4.6.1

python/pyproject.toml, version.json
This commit is was created with /scripts/prepare-release.
* Updated `/version.json` to v4.6.2 and the expected rev-count of the merge commit to 18883.
* Updated the python bindings version in `/python/pyproject.toml` to v4.6.2.
=> Prepare repository for Tenzir v4.6.2

Dockerfile, ansible/roles/tenzir/tenzir-node.service, changelog/next/bug-fixes/3705.md, nix/overlay.nix, scripts/debian/postinst, tenzir/services/systemd/tenzir-node.service.in
This PR drops the migration support from VAST. The logic to implement that did so without updating the internal state of dpkg, causing problems with the package on the next update.
We also include a commit to simplify the setup of the `cache`, `state` and `log` directories in the systemd unit.
=> Fix debian package installation when a vast state directory exists

changelog/next/features/3723--show-udos.md, libtenzir/builtins/aspects/config.cpp, libtenzir/builtins/aspects/operators.cpp, libtenzir/include/tenzir/pipeline.hpp, libtenzir/include/tenzir/plugin.hpp, libtenzir/src/pipeline.cpp
This adds user-defined operators to the output of `show operators`.
=> Include UDOs in `show operators`

changelog/next/features/3675--disk-usage-for-show-partitions.md, libtenzir/builtins/aspects/partitions.cpp, libtenzir/include/tenzir/active_partition.hpp, libtenzir/include/tenzir/actors.hpp, libtenzir/include/tenzir/fwd.hpp, libtenzir/include/tenzir/partition_synopsis.hpp, libtenzir/include/tenzir/resource.hpp, libtenzir/include/tenzir/store.hpp, libtenzir/src/active_partition.cpp, libtenzir/src/detail/add_message_types.cpp, libtenzir/src/index.cpp, libtenzir/src/plugin.cpp, libtenzir/src/store.cpp, libtenzir/test/active_partition.cpp, libtenzir/test/feather.cpp, plugins/parquet/tests/parquet.cpp
The partitions aspect is enhanced by the urls and file sizes of all persisted files.
Here is a sample:
```json
{
"uuid": "9b6f3896-580d-461e-a930-59f784b3b59a",
"memusage": 520,
"events": 1,
"min_import_time": "2023-11-27T16:59:28.946264",
"max_import_time": "2023-11-27T16:59:28.946264",
"version": 2,
"schema": "suricata.http",
"schema_id": "4e0aca2cf6a30f52",
"store": {
"url": "file:///home/tobim/t/tenzir/store-size-in-partition-metadata/tenzir.db/archive/9b6f3896-580d-461e-a930-59f784b3b59a.feather",
"size": 7554
},
"bitmaps": {
"url": "file:///home/tobim/t/tenzir/store-size-in-partition-metadata/tenzir.db/index/9b6f3896-580d-461e-a930-59f784b3b59a",
"size": 17080
},
"sketches": {
"url": "file:///home/tobim/t/tenzir/store-size-in-partition-metadata/tenzir.db/index/9b6f3896-580d-461e-a930 …
```
=> Add file data to show partitions

changelog/next/features/3683--grok-parser.md, libtenzir/CMakeLists.txt, libtenzir/builtins/operators/grok-patterns/NOTICE.txt, libtenzir/builtins/operators/grok-patterns/patterns.inc, libtenzir/builtins/operators/grok.cpp, libtenzir/builtins/operators/parse.cpp, tenzir/integration/reference/parse-with-grok/step_00.ref, tenzir/integration/reference/parse-with-grok/step_01.ref, tenzir/integration/reference/parse-with-grok/step_02.ref, tenzir/integration/reference/parse-with-grok/step_03.ref, tenzir/integration/reference/parse-with-grok/step_04.ref, tenzir/integration/reference/parse-with-grok/step_05.ref, tenzir/integration/reference/parse-with-grok/step_06.ref, tenzir/integration/reference/parse-with-grok/step_07.ref, tenzir/integration/reference/parse-with-grok/step_08.ref, tenzir/integration/tests.yaml, web/docs/formats/grok.md, web/docs/operators/transformations/parse.md
Closes https://github.com/tenzir/issues/issues/1022.
Adds a new parser, `grok`, reachable by the `parse` operator, based on the Logstash plugin of Elasticsearch of the same name: https://www.elastic.co/guide/en/logstash/current/plugins-filters-grok.html. Its syntax is
```
grok <input_pattern> [--pattern_definitions <patterns>] [--indexed_captures] [--include-nulls] [--include-unnamed]
```
where `<input_pattern>` is the grok-pattern used for parsing. Other options:
* `--pattern-definitions` can be used to define additional patterns for the use by `<input_pattern>`, alongside the [built-in ones](https://github.com/logstash-plugins/logstash-patterns-core/tree/main/patterns/ecs-v1), that are included as-is.
* `--indexed-captures` can be used to include all captures in the result, not just the …
=> Add `grok` parser

libtenzir/builtins/operators/grok.cpp, tenzir/integration/reference/parse-with-grok/step_09.ref, tenzir/integration/tests.yaml
In regular expressions, named capture groups don't match the pattern `\(\?<.+?>`, but `\(\?<\w+>`. The former would erroneously match `(?<=` and `(?<!`, which mean lookbehind. This manifested as regex lookbehind directives being included as named capture groups.
=> Fix implicit discovery of named capture groups in Grok

changelog/next/changes/3742--empty-field-names.md, libtenzir/src/type.cpp, libtenzir/test/table_slice.cpp
Previously, the record `{"": 42}` was not allowed. This PR removes this restriction.
=> Allow empty field names

.github/workflows/tenzir.yaml, changelog/next/bug-fixes/3743--blocking-operators.md, demo-node/setup.bash, libtenzir/builtins/commands/exec.cpp, libtenzir/builtins/operators/export.cpp, libtenzir/builtins/operators/import.cpp, libtenzir/builtins/operators/python.cpp, libtenzir/builtins/operators/serve.cpp, libtenzir/builtins/operators/shell.cpp, libtenzir/include/tenzir/actors.hpp, libtenzir/include/tenzir/chunk.hpp, libtenzir/include/tenzir/diagnostics.hpp, libtenzir/include/tenzir/pipeline.hpp, libtenzir/src/chunk.cpp, libtenzir/src/diagnostics.cpp, libtenzir/src/error.cpp, libtenzir/src/execution_node.cpp, libtenzir/src/module.cpp, libtenzir/src/pipeline.cpp, libtenzir/src/pipeline_executor.cpp, nix/tenzir/plugins/source.json, tenzir/functional-test/reference/python/test_empty_output_throws/step_00.ref
This change removes the outbound buffer of execution nodes, changing them to fulfill demand incrementally by immediately sending out partial results. This reduces latency, and avoids a problem with operators that block during execution, which sometimes held up already buffered partial results at the execution node instead.
=> Prevent delays for blocking operators

Dockerfile, changelog/next/features/3731--geoip-context.md, cmake/Findlibmaxminddb.cmake, libtenzir/CMakeLists.txt, libtenzir/aux/README.md, libtenzir/builtins/contexts/geoip.cpp, libtenzir/builtins/contexts/lookup-table.cpp, libtenzir/fbs/geoip.fbs, nix/overlay.nix, nix/tenzir/default.nix, nix/tenzir/plugins/source.json, scripts/debian/install-dev-dependencies.sh, scripts/macOS/install-dev-dependencies.sh, web/docs/contexts/geoip.md, web/docs/developer-guides/build-from-source.md
This change implements the `geoip` context - a built-in that reads MaxMind DB files and uses IP values in events to enrich them with the MaxMind DB geolocation data.
=> Implement the `geoip` context

web/docs/formats/grok.md, web/docs/operators/shell.md
=> Fix `shell` categorization in docs sidebar

changelog/next/bug-fixes/3758--hang-fix.md, libtenzir/src/execution_node.cpp, libtenzir/src/pipeline_executor.cpp
This PR fixes two bugs:
1. This reduces memory usage for fast operators right in front of very slow operators. Previously, the fast operator overfulfilled the demand of the slow operator, causing the inbound buffer of the slow operator to overfill. This no longer happens as drastically, and is limited to at most one batch.
2. This fixes a potential hang on shutdown due to a bug in CAF by sending an explicit exit message to operators preceding an operator that itself down early (e.g., `head`). I accidentally dropped this fix as part of the blocking operators fix.
=> Downtone push behavior of pipelines

Dockerfile, changelog/next/bug-fixes/3764--slim-image.md, flake.nix
This was missing the `TENZIR_CACHE_DIRECTORY`, causing the slim variant to fail on startup.
=> Fix the `tenzir/tenzir:latest-slim` image

cmake/TenzirRegisterPlugin.cmake, libtenzir/CMakeLists.txt, libtenzir/test/CMakeLists.txt, tenzir/CMakeLists.txt
This moves away from having a separate static library for builtins in favor of setting the required compile definition for all translation units in the `libtenzir/builtins` directory.
This is a bit experimental; we should measure whether this reduces or increases compile- and link-time.
=> Simplify builtins setup

libtenzir/builtins/operators/api.cpp, libtenzir/include/tenzir/pipeline.hpp, libtenzir/include/tenzir/plugin.hpp, libtenzir/src/argument_parser.cpp, libtenzir/src/pipeline.cpp, libtenzir/src/series_builder.cpp, web/blog/tenzir-v4.7/index.md, web/docs/formats/kv.md, web/docs/user-guides/run-a-pipeline/README.md
Some new-year cleanup. These probably found their way in due to the bad option+space default keybind on macOS.
=> Replace non-breaking spaces with normal ones

cmake/TenzirRegisterPlugin.cmake, libtenzir/CMakeLists.txt, libtenzir/test/CMakeLists.txt, tenzir/CMakeLists.txt
This reverts commit b7791a0312af60f34504db3ba4c4b644e2b29f68.
The commit broke builtins in the static binary build.
```
_____ _____ _   _ ________ ____       
|_   _| ____| \ | |__  /_ _|  _ \      
| | |  _| |  \| | / / | || |_) |     
| | | |___| |\  |/ /_ | ||  _ <      
|_| |_____|_| \_/____|___|_| \_\     
v4.7.1-18-g21bf4c89a8            
Visit https://app.tenzir.com to get started.
[20:50:21.790] loaded configuration file: /home/tobim/.config/tenzir/tenzir.yaml
[20:50:21.791] loaded plugin configuration file: /home/tobim/.config/tenzir/plugin/platform.yaml
[20:50:21.802] !! invalid_configuration: could not find store plugin 'feather'
[20:50:21.803] node terminates after DOWN from index with reason !! invalid_configuration: could not find store plugin 'feather'
[20:50:21.803] failed …
```
=> Revert "Simplify builtins setup"

.github/workflows/nix-manual.yaml
The actual builder workflow now takes an additional parameter named "gha-runner-labels". The workflow broke when we added support for building on darwin.
=> Update the manual static build workflow

web/src/css/custom.scss
Closes tenzir/issues#1080.
Docusaurus and Infima does a lot of CSS abstractions that don't map one-on-one to Tailwind (and thus our design system on the app and the site). For example, Tailwind sets line-height for each of `text-base, text-lg` etc, while docusaurus just uses a base and a header line-height variables. Docusaurus also conditionally changes the font-size for small screens - which will apply when the iframe width (the main motivation for this PR) is small, but not always.
Having considered all of these, I think we should just pluck the low-hanging fruit of changing the font-families on the docs site.
=> Use Inter and JetBrains Mono fonts on docs site

.github/workflows/tenzir.yaml
This change removes a remnant of the Docker-Documentation dependency that https://github.com/tenzir/tenzir/pull/3797 removed.
=> Remove the remnant of the Docker-Documentation dependency in the CI Configuration step

changelog/next/bug-fixes/3790--export-live.md, changelog/next/features/3790--metrics-operator.md, libtenzir/builtins/operators/export.cpp, libtenzir/builtins/operators/metrics.cpp, libtenzir/include/tenzir/actors.hpp, libtenzir/include/tenzir/importer.hpp, libtenzir/src/importer.cpp, web/docs/metrics.md, web/docs/operators/metrics.md
The `metrics [--live]` source operator is a short-hand notation for accessing all metrics events via `export --internal`.
Additionally, this PR fixes `export --live`, which was broken in many ways.
=> Fix `export --live` and introduce `metrics`

web/docs/operators/metrics.md
This fixes the docs for the metrics operator, which were mislabeled.
=> Fix metrics operator docs

.github/workflows/tenzir.yaml
* Ensure that `ccache` can actually read the downloaded ccache during the build
* Split upload and download cache steps to upload before integration tests
=> Fix ccache upload behavior

libtenzir/builtins/contexts/geoip.cpp, libtenzir/builtins/contexts/lookup-table.cpp, libtenzir/builtins/operators/chart.cpp, libtenzir/builtins/operators/delay.cpp, libtenzir/builtins/operators/drop.cpp, libtenzir/builtins/operators/hash.cpp, libtenzir/builtins/operators/parse.cpp, libtenzir/builtins/operators/pseudonymize.cpp, libtenzir/builtins/operators/put_extend_replace.cpp, libtenzir/builtins/operators/rename.cpp, libtenzir/builtins/operators/select.cpp, libtenzir/builtins/operators/sort.cpp, libtenzir/builtins/operators/summarize.cpp, libtenzir/builtins/operators/timeshift.cpp, libtenzir/include/tenzir/type.hpp, libtenzir/src/table_slice.cpp, libtenzir/src/type.cpp
This change adds support for concepts in almost all operators and contexts. In particular, this affects the following contexts or operators:
- `context`
- `delay`
- `drop`
- `enrich`
- `extend`
- `geoip`
- `hash`
- `lookup`
- `lookup-table`
- `parse`
- `pseudonymize`
- `put`
- `rename`
- `replace`
- `select`
- `sort`
- `summarize`
- `timeshift`
- `lookup`
Note that `put net.src.ip` creates a field `net.src.ip`, but `select net.src.ip` keeps the original field name.
=> Support concepts in more places

ansible/roles/tenzir/tenzir-node.service, changelog/next/features/3784--open-fds.md, libtenzir/builtins/health-metrics/process.cpp, libtenzir/include/tenzir/detail/process.hpp, libtenzir/include/tenzir/os.hpp, libtenzir/src/detail/process.cpp, libtenzir/src/os.cpp, tenzir/services/systemd/tenzir-node.service.in, web/docs/metrics.md
Attempt to improve the behavior of nodes that are running into the maximum number of open files:
* Increase the upper limit imposed by our systemd unit files to 64Ki
* Add monitoring of open file descriptors as a health metric so that leaks can be detected by looking at the rate of change over time.
=> Improve handling of open file descriptors

libtenzir/builtins/operators/enrich.cpp, nix/tenzir/plugins/source.json
This fixes a few bugs in the `lookup` operator:
- Deleting a context did previously not shut down `lookup` operators making use of the context.
- Unrecognized actions for the `context` operator, e.g., `context remove`, did not trigger an erorr but rather did nothing silently.
=> Fix various bugs in the `lookup` operator

python/tests/test_tenzir.py
Since we now rewrite `tenzir-ctl import` to `tenzir exec 'from ... | import'` internally, but we don't support `tenzir-ctl import -r` any more.
=> Convert python binding tests to tenzir exec

libtenzir/src/detail/string.cpp, libtenzir/test/http.cpp, libtenzir/test/string.cpp
Closes https://github.com/tenzir/issues/issues/1128, old PR https://github.com/tenzir/tenzir/pull/3791
```cpp
// Before:
// Only first separator after `max_splits` was reached
// had its escape sequence removed in the output
auto ret = detail::split_escaped("abc\\==def==ghi\\==jkl\\==mno", "==", "\\", 1);
// ret == ["abc==def", "ghi==jkl\\==mno"]
// After:
// Escape sequences not removed after `max_splits` is reached
auto ret = detail::split_escaped("abc\\==def==ghi\\==jkl\\==mno", "==", "\\", 1);
// ret == ["abc==def", "ghi\\==jkl\\==mno"]
```
TODO: sign commits
=> Fix handling of escapes in detail::split_escaped, attempt 2

tenzir.yaml.example
This corrects a few mistakes in the example config file. Most notable, user-defined operators were incorrectly listed in the `caf` config section.
=> Clean up the example config file

libtenzir/src/index.cpp
This fixes a very rare crash in the index on startup where taxonomies were not yet retrieved from the catalog but already attempted to access.
This crash was introduced a few months back when we backported a bug fix for our CAF fork that allowed system messages to be scheduled while another requests's response was awaited. The index uses the (rightfully) deprecated CAF streaming, which uses system messages under the hood. This means that awaiting the taxonomies on startup of the index did no longer ensure that they couldn't be used from CAF streaming handlers already.
Luckily, all this was rather easy to fix as we made taxonomies available globally rather than just in the catalog actor quite a while ago. It looks like we just forgot to update the logic of the index here.
=> Fix a rare crash in the index on startup

CMakeLists.txt, libtenzir/CMakeLists.txt, nix/caf/source.json
Fixes tenzir/issues#1157
This makes it so that `CAF_ASSERT` is always enabled alongside `TENZIR_ASSERT_EXPENSIVE`. This is the default behavior in debug builds.
=> Enable CAF assertions alongside our own assertions

changelog/next/bug-fixes/3836--zeek-tsv-metadata.md, libtenzir/builtins/formats/zeek_tsv.cpp, libtenzir/src/execution_node.cpp, libtenzir/src/table_slice.cpp, tenzir/integration/reference/zeek-tsv-pipeline-format/step_11.ref
Fixes tenzir/issues#587
This addresses two issues in the `zeek-tsv` printer:
1. Previously, the printer returned opening and closing tags once per batch rather than when the schema changes. That is not technically incorrect, but bloated the generated file sizes by a lot for small batches.
2. The printer was incorrectly marked as not allowing joining the output. Zeek TSV can be printer interleaved, so things like `to stdout write zeek-tsv` should not be forbidden.
=> Print Zeek TSV metadata when schema changes

changelog/next/features/3833--syslog-years.md, libtenzir/include/tenzir/format/syslog.hpp, tenzir/functional-test/data/syslog/syslog-rfc3164.log, tenzir/integration/reference/syslog-format/step_01.ref
Closes https://github.com/tenzir/issues/issues/1162
The RFC 3164 syslog parser couldn't handle (non-standard) years in timestamps. Now it can.
=> Add support for Cisco Firepower syslog messages

libtenzir/builtins/formats/zeek_tsv.cpp
This fixes a bug I accidentally introduced in #3836 that caused the Zeek TSV printer to not print schema information when no empty batch arrived before the first batch containing a result. This is a rare case, but it can actually happen depending on timing and the operators preceding `write zeek-tsv`.
=> Fix a logic bug in the Zeek TSV printer

web/docs/connectors/s3.md
This adds a note to the documentation of the S3 connector explaining a pitfall that a user ran into: They configured access to S3 for the wrong user account, and were then not able to access it using Tenzir.
Fixes tenzir/issues#1102
=> Explain how the S3 connector uses AWS configuration files

.clang-format
We've changed our coding style to always using braces almost two years ago now, and it turns out that there's actually a clang-format option to automatically rewrite code to have statements around braces for improved legibility.
=> Force braces around statements with clang-format

changelog/next/bug-fixes/3865--less-aggressive-scheduling.md, libtenzir/src/execution_node.cpp
This reduces the CPU usage of `load tcp://localhost:3000 | discard` where no data arrives over TCP drastically by re-implementing exponential backoff for the execution node's internal run loop.
Fixes tenzir/issues#1483
=> Schedule idle operators less aggressively

cmake/TenzirRegisterPlugin.cmake, tenzir/CMakeLists.txt, tenzir/functional-test/tests/setup_suite.bash
I stumbled upon this when trying to group our test suites with a directory structure: We just picked up tests in `<dir>/tests/*.bats` instead of `<dir>/tests/**/*.bats`, with tests in subdirectories being silently ignored.
=> Support execution of *.bats files in subdirectories

changelog/next/bug-fixes/3885--serve-inconsistencies.md, libtenzir/builtins/operators/serve.cpp, web/openapi/openapi.yaml
This fixes a bug in the `/serve` endpoint where sometimes the last continuation token was rendered as an empty string rather than null.
Fixes tenzir/issues#1509
=> Make `/serve` more consistent

.github/workflows/tenzir.yaml, scripts/macOS/install-dev-dependencies.sh
See also: https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/
=> Use the new M1 runners for the macOS CI

Dockerfile, changelog/next/changes/3889--state-directory.md, flake.nix, libtenzir/builtins/health-metrics/disk.cpp, libtenzir/include/tenzir/defaults.hpp, libtenzir/include/tenzir/disk_monitor.hpp, libtenzir/src/application.cpp, libtenzir/src/configuration.cpp, libtenzir/src/disk_monitor.cpp, libtenzir/src/logger.cpp, libtenzir/src/plugin.cpp, libtenzir/src/spawn_disk_monitor.cpp, libtenzir/src/spawn_node.cpp, libtenzir/test/feather.cpp, nix/module.nix, plugins/parquet/tests/parquet.cpp, tenzir.yaml.example, tenzir/functional-test/data/misc/scripts/break-sizelimit.sh, tenzir/functional-test/lib/bats-tenzir/src/fixtures.bash, tenzir/functional-test/tests/database.bats, tenzir/functional-test/tests/vast_server.bats, tenzir/integration/integration.py, tenzir/tenzir.cpp
The option `tenzir.db-directory` is quite old, and comes from a time when Tenzir wasn't all about pipelines, but rather mostly about its storage engine VAST. Nowadays, we store lots of state in this directory that is not part of a "database" in the classical sense. As such, the option is now called `tenzir.state-directory`, with the old option name still being supported for the foreseeable future in a backwards-comaptible way.
Additionally, this change makes it possible to set the `tenzir.cache-directory` on the command line when starting the node.
Fixes tenzir/issues#1109
=> Replace `tenzir.db-directory` with `tenzir.state-directory`

cmake/TenzirRegisterPlugin.cmake, libtenzir/CMakeLists.txt
With this change, plugins using `TenzirCompileFlatBuffers` can now use the `include "<file>";` directive to include FlatBuffers files from libtenzir like `type.fbs` or `data.fbs`.
I came across this deficiency while working on another plugin, and I think this is best reviewed separately, so I split it out into a PR of its own. Right now, this is just a build scaffolding change that is only user-visible in that the installed package now includes `*.fbs` files.
Fixes https://github.com/tenzir/issues/issues/1498
=> Allow using libtenzir FlatBuffers schemas from plugins

libtenzir/builtins/operators/serve.cpp, libtenzir/include/tenzir/type.hpp, libtenzir/src/type.cpp, libtenzir/src/version.cpp, web/openapi/openapi.yaml
This is an experimental branch for @dit7ya to play with: It changes the schema definition included with the response in `/serve` to a simpler to parse format for the app hosted at app.tenzir.com.
=> Make the schema definition easier to parse programmatically

nix/tenzir/plugins/source.json, web/docs/operators/metrics.md, web/openapi/openapi.yaml
Why? Because of two very simple reasons:
1. Our integration tests should be order-independent. Having truly random pipeline ids forces us to write them without relying on the ids being incremental.
2. When using the `metrics` and `diagnostics` operators, it was rather easy to make the mistake `where pipeline_id == 42` when it should've been `where pipeline_id == "42"`. This won't happen anymore now that the id is obviously not a number anymore.
This change should not be user-visible, as we never made any guarantees about the format of the pipeline ids.
Additionally, this fixes a small oversight in the recent addition of the `created_at` and `last_modified` fields in managed pipelines, which were not rendered as `time` values when using `show pipelines`.
=> Randomize pipeline ids

web/docs/integrations/windows-event-logs.md
This PR adds some more details about setting up an OpenWEC server to ingest Windows events into Tenzir. It distills the most important steps down so they can be concisely shown within the integration documentation.
There are also small typographical fixes.
=> Add more details to OpenWEC section

libtenzir/builtins/operators/shell.cpp, libtenzir/include/tenzir/actors.hpp, libtenzir/include/tenzir/detail/weak_handle.hpp, libtenzir/include/tenzir/diagnostics.hpp, libtenzir/include/tenzir/fwd.hpp, libtenzir/include/tenzir/operator_control_plane.hpp, libtenzir/include/tenzir/shared_diagnostic_handler.hpp, libtenzir/src/detail/add_message_types.cpp, libtenzir/src/diagnostics.cpp, libtenzir/src/execution_node.cpp
This introduces a diagnostics handler that is safe to use from other threads, allowing operators, connectors, and formats that spawn threads through third-party libraries or other actors to emit diagnostics.
To create a shared diagnostics handler, call `ctrl.shared_diagnostics()` instead of `ctrl.diagnostics()` on the operator's control plane.
Unlike for the regular diagnostics handler, errors emitted through the shared handler do not shut down the operator's execution node immediately. Diagnostics sent through the shared diagnostics handler may arrive out of order.
This is a first step towards being able to emit errors in the context API. For the `shell` transformation operator, this fixes an unsafe use of the regular diagnostic handler from another thread.
Fixes tenzir/issues#1073
=> Introduce the shared diagnostics handler

.cmake-format, cmake/TenzirRegisterPlugin.cmake, libtenzir/include/tenzir/diagnostics.hpp, libtenzir/include/tenzir/flatbuffer.hpp, libtenzir/include/tenzir/fwd.hpp, libtenzir/include/tenzir/type.hpp, libtenzir/src/catalog.cpp, libtenzir/src/type.cpp, plugins/amqp/CMakeLists.txt, plugins/kafka/CMakeLists.txt, plugins/sigma/CMakeLists.txt, plugins/velociraptor/CMakeLists.txt, plugins/web/CMakeLists.txt, plugins/web/src/authenticator.cpp, plugins/zmq/CMakeLists.txt
This set of changes improves the developer experience when working with FlatBuffers tables in Tenzir. I've made them out of frustration when working with FlatBuffers for another plugin, and for an improved reviewability I split them out into a separate pull request.
This PR
1. Fixes the version comparison to detect FlatBuffers versions without an opt-in to 64-bit offsets,
2. adds a convenience parameter for compiling, linking, and including FlatBuffers table in plugins,
3. makes globbing for files in plugins easier,
4. adds support for setting and checking the file identifier of a FlatBuffers root table, and
5. introduces support for size-prefixed FlatBuffers root tables.
None of this is user-facing, so no changelog entry required. The plugin scaffolding changes are also entirely …
=> Make FlatBuffers easier to use

changelog/next/bug-fixes/3910--retroactive-lookup-lifetime-fix.md, libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/contexts/lookup_table.cpp, nix/tenzir/plugins/source.json
This change is another submodule pointer bump, with a change to the "missing field" lookup error that hopefully makes it more usable.
=> Update the repository to include lookup lifetime fixes

changelog/next/features/3866--chart-operator.md, libtenzir/builtins/operators/chart.cpp, libtenzir/src/type.cpp, tenzir/integration/data/reference/pipelines_local/test_chart_attributes/step_06.ref, web/docs/operators/chart.md
The frontend already has the capability to handle `area` charts. This PR simply adds the type to the operator.
=> Add 'area' chart type

nix/tenzir/plugins/source.json
This makes use of the new simplified globbing and FlatBuffers setup in all of our proprietary plugins. There are no functional changes in this.
=> Simplify CMake of proprietary plugins

.github/workflows/nix.nu, .github/workflows/tenzir.yaml, flake.lock, flake.nix, libtenzir/CMakeLists.txt, nix/fix-fluent-bit-install.patch, nix/overlay.nix, nix/pfs/default.nix, nix/tenzir/check.nix, nix/tenzir/default.nix, plugins/fluent-bit/CMakeLists.txt, plugins/fluent-bit/integration/tests/tests.bats, plugins/web/integration/tests/rest.bats, shell.nix, tenzir/CMakeLists.txt, tenzir/integration/tests/setup_suite.bash, tenzir/integration/tests/tcp.bats
The Nix package expression is refactored into 2 derivations. The first
builds the binary and package as before, and the newly introduced second
derivation runs the functional tests. This allows us to iterate on the
tests without having to rebuild c++ code with every change.
The untested binary can still be accessed with the the `unchecked`
attribute, e.g. `...#tenzir-static.unchecked`, `...#tenzir-de.unchecked`
and so on.
=> Run functional tests when building the static binary

changelog/next/bug-fixes/3903--time-comma.md, libtenzir/include/tenzir/concept/parseable/numeric/real.hpp, libtenzir/include/tenzir/concept/parseable/tenzir/time.hpp, libtenzir/src/concept/parseable/numeric/real.cpp, tenzir/integration/tests/vast.bats
Closes https://github.com/tenzir/issues/issues/1520
Makes `double_parser` a template, that accepts the expected radix separator as a parameter. `parsers::real` is `double_parser<'.'>`, and the new `parsers::real_comma` is `double_parser<','>`.
`parsers::real_detect_sep` is also added, that tries both `real` and `real_comma`, and yields whichever matched more characters. The seconds parser in `parsers::time` is changed to use that.
The end result is, that both dots and commas are accepted as separators for subsecond values in `parsers::time`, as specified by ISO 8601. I'm not 100% happy with the implementation, but it works.
=> Add support for commas in seconds in the time data parser

libtenzir/src/type.cpp
We want to include `-1` in the path only when we are dealing with lists of records, and not for lists of other types.
The code was actually authored by @dominiklohmann.
=> Fix non-records list path with use_simple_format

.github/workflows/nix.nu, .github/workflows/nix.yaml
Before this change the enterprise edition install job actually used the community edition build. This sometimes led to a failure in case the latter was not uploaded yet.
We fix both problems by merging both into a joint "Build & Install" job.
=> Test debian package install in the build job

.github/workflows/bump-plugins-submodule.yaml, .github/workflows/tenzir.yaml, nix/tenzir/plugins/source.json
* Require an open PR for any changes to the plugins submodule
* Remove some leftover debug code
* Rename the used secrets away from `TESTAPP`
* Fix a bug where the submodule would be bumped to an incorrect state.
=> Improve submodule bump workflow

scripts/install.sh
A recent change added the ability to override the package URL with an environment variable, but the check for the non-emptyness of this variable was incorrect in the presence of `set -u`.
=> Fix the installer

changelog/next/changes/3945--context-versioning.md, libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/contexts/geoip.cpp, libtenzir/builtins/contexts/lookup_table.cpp, libtenzir/include/tenzir/plugin.hpp, libtenzir/src/plugin.cpp, nix/tenzir/plugins/source.json, web/docs/contexts/bloom-filter.md, web/docs/contexts/geoip.md, web/docs/contexts/lookup-table.md
Closes https://github.com/tenzir/issues/issues/1454, plugins-PR: https://github.com/tenzir/tenzir-plugins/pull/196
This PR implements versioned loading of serialized contexts.
- The `context` base class is refactored, to support multiple `context_loader`s, each associated with a version
- Each context is refactored accordingly, with a single loader corresponding to "v1"
- When persisted on disk, the version number is stored in the filename: `<name>.<type>.<version>.ctx` (previously `<name>.<type>.ctx`). No version number in the filename is assumed to mean "v1".
- Saving is not materially changed:
- Only a single saver per context is still supported
- `context::save` also returns a version number
- When persisted, the version number is marked in the filename
- When starting a node, the …
=> Context versioning

.github/workflows/tenzir.yaml, Dockerfile, scripts/debian/build-fluent-bit.sh, scripts/debian/install-dev-dependencies.sh, scripts/debian/install-fluent-bit.sh
The docker image is currently broken on `arm64`, because we install a custom `amd64` fluent-bit package without checking for the platform. This PR changes the docker setup to build fluent-bit as part of the `dependencies` target.
The regular Debian CI build is still using the prebuilt fluent-bit package to avoid increasing the runtime of the slowest job.
=> Build Fluent Bit as part of the Docker image

.github/workflows/tenzir.yaml
The recent versioning update accidentally removed the `v`-prefix from docker image tags and package file names. This change was unintentional and is hereby reverted.
=> Reintroduce the v-prefix in version tags

CMakeLists.txt, libtenzir/include/tenzir/cast.hpp, libtenzir/include/tenzir/concept/parseable/tenzir/schema.hpp, libtenzir/src/detail/posix.cpp, libtenzir/src/format/arrow.cpp, libtenzir/src/format/csv.cpp
All supported compilers implement NRVO, so we don't need to disable this warning any more.
This also fixes an operator precedence bug in the old CSV parser that was found with the help of `-Wmaybe-uninitialized`.
=> Enable redundant move warnings

.github/workflows/upload-cache-artifact.yaml
Github does not offer an API to download entries from the actions cache for inspection. This workflow offers a way around that limitation.
=> Add a helper to copy GHA cache entries

.github/workflows/bump-plugins-submodule.yaml, .github/workflows/tenzir.yaml
As observed by @jachris , if a PR does not change the plugins, but some other PR does in the meantime, that the branch protections (of the PR that does not change plugins) do not pass. This means that all PRs have to be updated, even though they don't necessarily conflict.
This PR aims to solve this by allowing submodule commits that are either direct ancestors or direct descendants of `origin/main`.
=> Slightly relax rules for policy enforcement

.github/workflows/nix.nu
The package is broken, so for now it's better not to upload it at all. No changelog entry necessary as we never announced it in the first place.
=> Remove the macOS package upload

changelog/next/bug-fixes/3994--index-toctou.md, libtenzir/src/index.cpp
This fixes a bug that sometimes caused the index actor to shut down with an exception when combined with compaction or the disk monitor because of a time of check vs. time of use bug when trying to canonicalize paths in the returned partition infos from the catalog lookup.
=> Fix a TOCTOU bug that caused the index to fail

libtenzir/src/application.cpp, libtenzir/src/spawn_importer.cpp, libtenzir/src/spawn_index.cpp, tenzir.yaml.example, web/docs/setup-guides/tune-performance/README.md
Parquet as a format is entirely fine, but the store backend has a bunch of issues. This removes the option and forces use of the `feather` store backend instead.
Parquet can still be used in combination with the `from`, `load`, `to`, and `save` operators.
=> Disable the `parquet` store backend

changelog/next/bug-fixes/3999-remote-python.md, libtenzir/builtins/operators/python.cpp
This fixes `remote python`, i.e., using explicit location overrides with the `python` operators to run a script at a node.
Additionally, this adds a 60 second timeout to waiting for the named semaphore guarding the virtualenv setup. During development of this branch, I managed to crash once while inside the critical section, and the operator was unusable afterwards as it locked up indefinitely. It's far from a perfect solution, but erroring after a minute is a lot better than being stuck with no way out.
Fixes tenzir/issues#1632
=> Make `remote python` work

nix/overlay.nix
This fixes a build issue with the static binary that caused our `librdkafka` dependency to be built without ZLIB support.
=> Support ZLIB compressed data in the kafka connector

changelog/next/bug-fixes/3998--tcp-connector-cloexec.md, libtenzir/builtins/connectors/tcp.cpp
Child processes created via `shell` or `python` inherit all currently open file descriptors from the node, which prevent the TCP connector form getting the same port upon restart, because it was now blocked by the children, because of the inherited open file descriptors.
To prevent this, we now create our own socket with `FN_CLOEXEC` that we assign to the ASIO abstraction where possible, and use `fcntl` where not.
=> Prevent tcp socket inheritance to child processes

changelog/next/bug-fixes/4001--s3-overrides.md, changelog/next/features/4001--s3-config.md, libtenzir/builtins/connectors/s3.cpp, web/docs/connectors/s3.md
This fixes partial overrides of the S3 configuration in the arguments to the URL. Previously, when providing any arguments to the S3 connector as part of the URL, it failed to respect the default credentials from the configuration file.
Additionally, this makes it possible to specify the S3 secrets in the S3 plugin's configuration file directly.
=> Fix partial specialization of S3 configuration in URL

changelog/next/bug-fixes/4010--sigma-crash-missing-file.md, plugins/sigma/src/plugin.cpp
This fixes a potential crash in the `sigma` operator when reading a non-existent file.
=> Fix crash in `sigma` operator for non-existent file

changelog/next/features/4006--configurable-pipelines.md, nix/tenzir/plugins/source.json, web/docs/user-guides/run-pipelines/README.md
This addition allows defining pipelines in `tenzir.yaml`. Configured pipelines will be started automatically with the node.
Here is an example for how to use this functionality from `tenzir.yaml`:
```
pipelines:
my-fancy-pipeline:
definition: show version | write json -c | save stdout
autostart:
failed: false
json-import:
name: JSON Import
definition: from tcp://0.0.0.0:34343 read json | import
autostart:
failed: true
```
=> Add configurable pipelines

changelog/next/bug-fixes/4012--multiline-syslog.md, libtenzir/builtins/formats/syslog.cpp, tenzir/integration/data/inputs/syslog/multiline.log, tenzir/integration/data/reference/pipelines_local/test_syslog_format/step_02.ref, tenzir/integration/tests/pipelines_local.bats
Reported on Discord.
This PR fixes a logic bug in the parser, that previously caused a panic, when encountering an invalid syslog message. This is caused by a multiline message, where the latter lines are not valid messages themselves. We don't currently provide proper support for multiline syslog messages, but now we no longer crash.
Lines that don't look like a syslog message on their own are parsed as `syslog.unknown`, with the entire line contained in a field called `syslog_message`, as can be seen in the test reference files.
=> Fix panic on parsing invalid syslog messages

changelog/next/bug-fixes/4020--configured-pipelines-crash.md, nix/tenzir/plugins/source.json
This fixes a crash that you could sometimes run into when upgrading to Tenzir v4.10 and using configured pipelines for the first time.
=> Fix crash when using configured pipelines for the first time

changelog/next/bug-fixes/3997--platform-periodic-reconnects.md, changelog/next/bug-fixes/4028--lookup-no-bind.md, changelog/next/changes/3997--platform-periodic-reconnects.md, libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/contexts/lookup_table.cpp, nix/tenzir/plugins/source.json
This fixes two issues in `lookup`:
1. The operator did not ignore internal events, and
2. the operator let events through for which the provided fields did not bind.
=> Ignore events in `lookup` that did not bind

changelog/next/bug-fixes/4034--sigma-type-infer-crash.md, plugins/sigma/src/plugin.cpp
This fixes a crash in the Sigma operator when type inference failed due to mixed types in a list. Instead, we now just use the series builder for attaching the rule to the output, which already supports this.
=> Fix a crash in the Sigma operator

changelog/next/bug-fixes/4033--large-context-load.md, nix/tenzir/plugins/source.json
This PR fixes a logic bug in `context load`, where each chunk of the input was attempted to be loaded individually, rather than loading the entire input. This error was only encountered, when loading contexts that were large enough to be split into multiple chunks.
Plugins PR https://github.com/tenzir/tenzir-plugins/pull/210
=> Fix loading of large contexts

changelog/next/bug-fixes/4040--multi-drop-select.md, changelog/next/changes/4040--context-metadata.md, changelog/next/features/4040--context-replace-separate.md, libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/contexts/geoip.cpp, libtenzir/builtins/contexts/lookup_table.cpp, libtenzir/builtins/operators/drop.cpp, libtenzir/builtins/operators/select.cpp, libtenzir/include/tenzir/plugin.hpp, libtenzir/include/tenzir/type.hpp, libtenzir/src/type.cpp, nix/tenzir/plugins/source.json, web/docs/connectors/s3.md, web/docs/operators/enrich.md, web/docs/operators/lookup.md
This adds `--yield` and `--separate` options to the `lookup` and `enrich` operators, and the `--replace` option for `enrich`.
The `--replace` option makes the `enrich` operator replace the input value with the context as opposed to adding it to the output, and makes the output a lot leaner.
The `--separate` option causes the operators duplicate the input events for each matched field alongside making the nesting structure a lot less deep for the context.
The `--yield <field>` option causes the operators to add only the specified subset of the context.
Additionally, this changes the context structure slightly to add the meta information per context as opposed to once per event. This makes it easier to work with the results of the two operators in downstream tooling.
This also fixes a bug …
=> Introduce `--replace`, `--separate`, and `--yield` for contexts

libtenzir/src/detail/loader_saver_resolver.cpp
This fixes an oversight from #4043 that led to a CI failure; we hastily merged it earlier to get the fix in for S3 with explicit credentials, but overlooked that the URI parser from libcurl rejects schemes it does not support. The fix is to simply switch to the Arrow URI parser instead, which is a lot more forgiving.
=> Fix a regression in `from <uri>`

changelog/next/bug-fixes/4045--context-load-off-by-one.md, nix/tenzir/plugins/source.json
This fixes a nasty off-by-one error when loading persisted contexts that reliably led to every second context to be skipped when loading from disk.
=> Fix an off-by-one error when loading persisted contexts

changelog/next/bug-fixes/4048--compress-equal-size.md, changelog/v4.10.4/bug-fixes/4031.md, libtenzir/builtins/operators/compress_decompress.cpp
The result of a compression may sometimes be the same size as the uncompressed chunk.
=> Fix invalid assertion in `compress` operator

libtenzir/builtins/operators/export.cpp
This reverts the recent change to the `export` operatot that made it go through the index actor, similar to the old `vast export` command. In some production setups, we've seen the index be so busy sorting the priority queue of partitions that something as simple as `export | head 1` takes minutes to finish.
We made these changes in the first place to reduce the pressure from having too many queries running from _Threat Bus_ in parallel, but that's alongside the matcher plugin on its way out and effectively superseded by the `lookup` operator, so it should be safe to make this change.
=> Revert recent changes to the `export` operator

changelog/next/features/4041.md, libtenzir/builtins/connectors/email.cpp, libtenzir/include/tenzir/curl.hpp, libtenzir/src/curl.cpp, libtenzir/src/transfer.cpp, web/docs/connectors/email.md
This PR adds an email saver.
```[tasklist]
```
I tested this with this pipeline:
```
version
| repeat 3
| write json
| save email -f mavam@localhost -v user@example.org
```
~For the first version of the `email` saver, I deliberately ignored MIME parts. Libcurl [supports this nicely](https://curl.se/libcurl/c/smtp-mime.html), but I'd rather get some experience with this before going more complex.~ Turns out that this was easier than expected. It's now part of the PR.
An open question is how to batch events. Today, we only have the `batch` operator. In TQLv2, we'll be able to window at the event level, which is the missing piece here. I think we can ignore this problem until then.
=> Add an email saver

changelog/next/changes/4040--context-metadata.md, libtenzir/builtins/contexts/bloom_filter.cpp, nix/tenzir/plugins/source.json
This makes a further adjustment to a change from #4040 that fixes filtering with a bloom-filter context. That change hasn't made it into any release yet, so there's no changelog entry necessary.
=> Fix bloom filter contexts for `enrich … --filter`

tenzir/integration/data/reference/pipelines_local/test_set_operator/step_00.ref, tenzir/integration/tests/pipelines_local.bats
We should _really_ stop using the `version` operator as sample data...
=> Fix test that relied on the patch version number

.github/workflows/tenzir.yaml, python/pyproject.toml, scripts/prepare-release, version.json, web/blog/tenzir-v4.11/index.md
This commit was created with /scripts/prepare-release.
* Updated `/version.json` to v4.11.1.
* Moved all changelog entries from `/changelog/next` to `/changelog/v4.11.1`.
* Updated the python bindings version in `/python/pyproject.toml` to v4.11.1.
=> Prepare repository for Tenzir v4.11.1

changelog/next/bug-fixes/4082--show-contexts-schema.md, libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/operators/every.cpp, nix/tenzir/plugins/source.json
This erroneously showed a single schema name for all contexts, even when they have differing types.
=> Fix the schema name in `show contexts`

libtenzir/builtins/formats/bitz.cpp, libtenzir/builtins/formats/feather2.cpp, libtenzir/builtins/formats/pcap.cpp, libtenzir/include/tenzir/make_byte_reader.hpp, libtenzir/src/chunk.cpp
This change builds on top of @balavinaithirthan's upcoming Feather format and adds zero-copy support to it. This is a vast improvement when reading Feather from a memory-mapped file, where copies of data can now be avoided entirely until we need to do IPC or exchange any columns.
=> Support zero-copy reading in new Feather parser

changelog/next/bug-fixes/4087--fix-json-printer-inf-nan.md, libtenzir/include/tenzir/concept/printable/tenzir/json.hpp, tenzir/integration/data/reference/pipelines_local/test_weird_json_floats/step_00.ref, tenzir/integration/tests/pipelines_local.bats
The JSON printer previously printed invalid JSON for `inf` and `nan`, which means that `serve` could sometimes emit invalid JSON, which is not handled well by platform/app. Instead, we now emit `null`.
```diff
- {"inf": inf.0, "nan": nan, "subnormal": 2.2250738585072e-310, "zero": -0.0}
+ {"inf": null, "nan": null, "subnormal": 2.2250738585072e-310, "zero": -0.0}
```
=> Fix JSON printer handling of `inf` and `nan`

changelog/next/bug-fixes/4085--python-operator-underscore.md, python/tenzir/tools/python_operator_executor.py
Fields starting with `_` were previously discarded due to some implementation details. However, following #4036, this is no longer necessary. I also used this opportunity to clean up the surrounding code.
=> Make `python` operator not discard fields that start with an underscore

changelog/next/bug-fixes/4092--http-put-fix.md, libtenzir/builtins/connectors/email.cpp, libtenzir/include/tenzir/curl.hpp, libtenzir/src/curl.cpp, libtenzir/src/transfer.cpp, libtenzir/src/version.cpp
This PR fixes a bug when attempting to send a HTTP PUT request with an empty request body.
=> Fix HTTP PUT with empty request body

changelog/next/bug-fixes/4093--node-shutdown.md, libtenzir/include/tenzir/node.hpp, libtenzir/src/node.cpp, tenzir/integration/tests/shutdown.bats
In some cases, pipelines created with a `tenzir` process connected to a `tenzir-node` process did not shut down correctly when the `tenzir-node` process was terminated. This change makes it so that remotely spawned operators are always shut down reliably.
Fixes tenzir/issues#1712
=> Fix shutdown of connected pipelines alongside node

Dockerfile, changelog/next/bug-fixes/4099--wrong-expose.md, flake.nix
Our Docker images always exposed port 5158/tcp, regardless of how that was configured. This broke running multiple nodes in the same Docker Compose file or in host mode.
=> Remove wrong EXPOSE in Dockerfile

changelog/next/features/4095--batch-timeout.md, libtenzir/builtins/operators/batch.cpp, web/docs/operators/batch.md
This makes the `batch` operator a bit more flexible, allowing users to control batching not just by size, but also by latency. Without this option, choosing a large batch size often resulted in events being delayed a lot until the desired batch size was available. Now, there is a maximum latency for events.
This doesn't have a direct use case (yet), but I plan to make use of this implicitly internally as part of the upcoming database plugin when writing files. We should also consider inserting this into pipelines in front of operators whose performance suffers heavily when using too small batches.
=> Add a `--timeout <duration>` option to `batch`

changelog/next/bug-fixes/4097--configured-pipeline-startup-errors.md, libtenzir/include/tenzir/shutdown.hpp, libtenzir/src/node.cpp, libtenzir/src/shutdown.cpp, nix/tenzir/plugins/source.json
A configured pipeline with a syntax error should not allow nodes to start up successfully.
Fixes tenzir/issues#1714
=> Shut down node a configured pipeline fails to start

.cmake-format, CMakeLists.txt, cmake/TenzirRegisterPlugin.cmake, tenzir/CMakeLists.txt, tenzir/integration/README.md
Purely a convenience thing, because explaining that for every integration test target `integration*` there is a corresponding `update-integration*` is a lot easier than remembering which environment variable to set for updating test references.
=> Add targets to CMake for updating test references

changelog/next/changes/4080--multiline-syslog.md, changelog/next/features/4080--multiline-syslog.md, libtenzir/builtins/formats/syslog.cpp, tenzir/integration/data/inputs/syslog/multiline.log, tenzir/integration/data/reference/pipelines_local/test_syslog_format/step_02.ref
Closes https://github.com/tenzir/issues/issues/1068
This PR adds support for multi-line syslog messages. This is achieved through a simple assumption, where if a line of input couldn't be parsed as a syslog message, it's assumed to be a continuation of a message in a preceding line (if any). This is technically a change in behavior, which is reflected in the changelog.
=> Add multi-line syslog message support

libtenzir/builtins/operators/every.cpp, libtenzir/src/execution_node.cpp
These operators are effectively commands, i.e., they cannot actually be combined with any other operator, except for operator modifiers.
The rationale for this is an upcoming change to `context save`, `context update`, and `context create` that turns the three operators into sinks. But since `context create` already is a source operator this means that we now had to implement support for operators that are both a source and a sink at the same time. Luckily this was rather easy to implement.
For testing, I modified the `version` soucce operator to return a `generator<std::monostate>` and to print the event on the stderr instead. The only code outside of the execution nodes that I needed to modify was the `every` operator modifier that ran into an assertion for void-to-void operators.
=> Add support for void-to-void operators

cmake/TenzirRegisterPlugin.cmake, tenzir/CMakeLists.txt
This adds a few targets to our CMake, structured like a tree. The general format of the new targets is this:
```
[update-]integration
[update-]integration-tenzir
[update-]integration-tenzir-${suite}
[update-]integration-${plugin}
[update-]integration-${plugin}-${suite}
```
A few examples:
- `update-integration-web-serve` will update the reference files for the `serve` test suite of the `web` plugin.
- `integration-tenzir` will run all integration test suites from the main library and its builtins.
- `update-integration` will update the reference files for the main library and all plugins.
=> Add CMake targets for all individual test suites

changelog/next/features/4109--every-generalized.md, libtenzir/builtins/operators/every.cpp, libtenzir/builtins/operators/local_remote.cpp, tenzir/integration/data/reference/every/test_every_modifier/step_01.ref, tenzir/integration/data/reference/every/test_every_modifier/step_02.ref, tenzir/integration/tests/every.bats, web/docs/language/operator-modifiers.md
This enables streaming aggregations by turning blocking operators into operators that stream their results at a fixed interval. This is best explained on an example. The following pipeline returns the total ingress as bytes per minute per pipeline:
```
metrics --live
| where #schema == "tenzir.metrics.operator"
| where source == true
| every 1min summarize ingress=sum(output.approx_bytes), duration=sum(duration) by pipeline
```
Similarly, this pipeline returns for every managed pipeline how many diagnostics were encountered, grouped by severity (warning or error):
```
diagnostics --live
| every 10s count=count(.) by severity
```
=> Generalize `every` to work with all operators

changelog/next/changes/4114--removed-metrics-from-list-endpoint.md, nix/tenzir/plugins/source.json, web/openapi/openapi.yaml
We recommend getting metrics from the `metrics` operator for good reason, and it has been long enough now that we can safely remove the metrics from the endpoint. They were problematic from a performance perspective, as they required the `/pipeline` API to inspect operator metrics.
=> Remove metrics from `/pipeline/list`

changelog/next/changes/4117--0mq-optional-monitoring.md, changelog/next/features/4117--0mq-inproc-sockets.md, plugins/zmq/src/plugin.cpp, web/docs/connectors/zmq.md
As a poorman's pub/sub, we want to use our existing `zmq` connector in combination with `bitz`. This requires support for [inproc sockets](http://api.zeromq.org/4-2:zmq-inproc) sockets, which this PR adds.
=> Support 0mq inproc sockets

changelog/next/bug-fixes/4123--serve-504.md, libtenzir/builtins/operators/serve.cpp
This fixes a very odd race condition in the bridge between the `serve` operator and the `/serve` API endpoint. When a pipeline completes, we keep its last result set around so that it can be retrieved in case the last request failed. However, when a second pipeline using serve in precisely that time frame was started and ran into a timeout on its first request, we accidentally leaked resources for the first pipeline and had the request for the second pipeline go unanswered, leading to a 504 error in the explorer.
The cuplrit behind this was in a wrong comparison in the handler that delivers underful results when a timeout hit that compared using the continuation token as opposed to the serve id. Since both the initial and the final continuation tokens are null, it found the wrong serve …
=> Fix a race condition in `/serve`

.github/workflows/tenzir.yaml, Dockerfile, libtenzir/builtins/connectors/email.cpp, libtenzir/builtins/connectors/udp.cpp, libtenzir/builtins/operators/from_load_read.cpp, libtenzir/builtins/operators/to_write_save.cpp, libtenzir/include/tenzir/plugin.hpp, libtenzir/src/detail/loader_saver_resolver.cpp, libtenzir/src/plugin.cpp, nix/tenzir/plugins/names.nix, nix/tenzir/plugins/source.json, plugins/gcs/src/plugin.cpp, plugins/zmq/src/plugin.cpp, web/docs/operators/publish.md, web/docs/operators/subscribe.md
This change implements a single-producer multi-consumer version of pub/sub that builds on top of the recently added BITZ format and the ZeroMQ connector's `inproc` sockets.
It's very simple to use: You run `publish <topic>` to publish, and `subscribe <topic>` to subscribe.
=> Implement a KISS version of pub/sub

web/docs/platform-cli.md
This mostly moves around the different sections of the platform CLI docs, to more clearly separate on-premise exclusive commands from generally available ones, and to move simple commands to the beginning and complex commands to the end.
* The high-level is now subdivided in 4 blocks, "Authentication", "Manage Nodes", "Manage Workspaces" and "Configure Access Rules", two of which are exclusive to on-prem deployments.
* The `workspace list` and `workspace select` commands are moved into the Authentication section, the rules-related commands are moved out.
* Added some additional text to some of the auth-rule related documentation
=> Refactor platform CLI docs

web/blog/tenzir-v4.10/index.md, web/versioned_docs/version-Tenzir v4.10/user-guides/run-pipelines/README.md, web/versioned_docs/version-Tenzir v4.11/user-guides/run-pipelines/README.md
These were missing a level of indentation, as reported by a user via Discord.
=> Fix Pipelines as Code examples

web/docs/setup-guides/deploy-the-platform.md
Fix naming of the `*_ENDPOINT` variables to correspond with our example docker compose files, and switch to a better example url for the blob storage.
=> Small fixups for the platform docs

changelog/next/features/4126--configurable-contexts.md, libtenzir/builtins/components/metrics_collector.cpp, nix/tenzir/plugins/source.json, tenzir.yaml.example, web/docs/contexts.md
Similar to configurable pipelines, we can now also configure contexts in `tenzir.yaml` files:
```
tenzir:
contexts:
lt:
type: lookup-table
geoip:
type: geoip
arguments:
db-path: /path/to/GeoLite2-ASN.mmdb
bf:
type: bloom-filter
arguments:
capacity: 100
fp-probability: 0.1
```
=> Add configurable contexts

changelog/next/features/4131--show-schemas.md, libtenzir/builtins/aspects/schemas.cpp, web/docs/operators/show.md
This is pretty helpful for debugging when there are too many layouts of one schema.
=> Add `show schemas` to display all available schemas

libtenzir/builtins/connectors/s3.cpp, libtenzir/include/tenzir/fwd.hpp, libtenzir/src/detail/loader_saver_resolver.cpp, libtenzir/src/socket.cpp, plugins/gcs/src/plugin.cpp
Arrow stabilized the `arrow::util::Uri` API, which was previously in the internal namespace.
=> Fix the build with Arrow 16+

schema/types/suricata.schema
This PR adds some more detail to the `suricata.flow` record type in the Suricata schema by including fields that were previously missing. This is aimed at reducing the number of non-schema fields encountered in potential input from recent Suricata versions, which would then lead to a larger number of schema layouts that need to be inferred based on the observed event content.
Please review and -- if necessary -- ensure that reference files in the tests are updated.
=> Update Suricata schema with additional flow fields

changelog/next/bug-fixes/4137--large-lookup-table.md, libtenzir/include/tenzir/fbs/utils.hpp, libtenzir/include/tenzir/flatbuffer.hpp, libtenzir/src/fbs/utils.cpp
This fixes a bug when loading large lookup tables or other data persisted in a FlatBuffers table from disk. The default behavior of the FlatBuffers table verifier is to blame here.
=> Fix verification of large FlatBuffers tables

scripts/prepare-release
This is a small fix for the prepare-release script, which before this required manual intervention to move around the changelog .gitkeep files, which while not a lot of effort was easy to overlook.
=> Keep changelog .gitkeep files when cutting a release

.github/workflows/docker.yaml, Dockerfile, changelog/next/bug-fixes/4143--enrich-stop.md, changelog/next/changes/4143--context-breakup.md, libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/contexts/geoip.cpp, libtenzir/builtins/contexts/lookup_table.cpp, libtenzir/include/tenzir/drain_bytes.hpp, libtenzir/include/tenzir/plugin.hpp, libtenzir/src/execution_node.cpp, libtenzir/src/node.cpp, libtenzir/src/pipeline_executor.cpp, nix/tenzir/plugins/source.json, plugins/parquet/parquet.cpp, tenzir/integration/data/reference/pipelines_local/test_parse_operators/step_03.ref, tenzir/integration/data/reference/pipelines_local/test_parse_operators/step_13.ref, tenzir/integration/data/reference/pipelines_local/test_parse_operators/step_16.ref, tenzir/integration/data/reference/pipelines_local/test_parse_operators/step_18.ref, web/docs/operators/context.md
This change removes the events output from quite a few context-related operators, and also makes less of them take generic arguments in favor of fixed arguments that produce better diagnostics when they're misused.
Note that this is a mirror of #4143, where CI got stuck entirely for some reason and there was no way to run it. So here's my attempt to run it by recreating the PR.
=> Remove events output from many context operators

web/docs/user-guides/run-pipelines/README.md, web/versioned_docs/version-Tenzir v4.12/user-guides/run-pipelines/README.md
This change fixes the wrong `retry-on-error` key in the configured pipeline example in the documentation.
=> Fix a wrong key in the configured pipeline example

changelog/next/bug-fixes/4139.md, libtenzir/builtins/operators/python.cpp, python/tenzir/tools/python_operator_executor.py, tenzir/integration/data/reference/python/test_python_operator_invalid_syntax/step_00.ref, tenzir/integration/data/reference/python/test_python_operator_invalid_syntax/step_01.ref, tenzir/integration/data/reference/python/test_python_operator_invalid_syntax_in_file/step_00.ref, tenzir/integration/tests/python.bats
1. Instead of compiling and executing the code at every record batch, compile only once at the beginning. Therefore, syntax errors can be identified even in a streaming context where the first record batch has not arrived.
=> Find syntax errors before record batch reading

libtenzir/include/tenzir/index.hpp, libtenzir/src/index.cpp
This reworks how the index handles active partition timeouts to be easier to reason about. We have empirically noticed that sometimes partitions do not get flushed and hope that this fixes the underlying issue—the old code for this was a mess, to say the least.
=> Make index flush timeouts more consistent

changelog/next/features/4147-chart-axis-type.md, libtenzir/builtins/operators/chart.cpp, tenzir/integration/data/reference/pipelines_local/test_chart_arguments/step_04.ref, tenzir/integration/data/reference/vast/test_bar_chart/step_01.ref, tenzir/integration/data/reference/vast/test_bar_chart/step_03.ref, tenzir/integration/data/reference/vast/test_line_chart/step_01.ref, tenzir/integration/data/reference/vast/test_line_chart/step_03.ref, web/docs/operators/chart.md
Relevant for https://github.com/tenzir/issues/issues/1256.
=> Add axis types as chart operator flags

changelog/next/bug-fixes/4166--every-transformation-shutdown.md, libtenzir/builtins/operators/every.cpp
`every` when used with a transformation or a sink did not shut down properly before this change.
=> Fix shutdown of `every <interval> <transformation|sink>`

libtenzir/src/execution_node.cpp, libtenzir/src/index.cpp, libtenzir/src/spawn_index.cpp
The index actor is one of our busiest actors, and it's still one of the places where read and write paths collide. This change pins the actor onto a single thread that lives outside the actor system's thread pool.
=> Detach the index actor

changelog/next/bug-fixes/4170--fix-port-reopen.md, libtenzir/builtins/operators/python.cpp, libtenzir/builtins/operators/shell.cpp, libtenzir/include/tenzir/detail/preserved_fds.hpp, libtenzir/src/detail/preserved_fds.cpp, shell.nix
This fixes an unwanted interaction between the `http` and `tcp` connectors and the `python` and `shell` operators. When a connector opens a listening port the forked subprocesses would inherit the file descriptors representing the resource. That prevented the connector from being recreated while the subprocesses were still running.
=> Fix reopening ports while subprocesses are open

changelog/next/bug-fixes/4173--chart-multiple-y-axis.md, libtenzir/builtins/operators/chart.cpp
The `chart` operator failed to render a chart when the y-axis was not specified explicitly and the events contained more than two top-level fields.
=> Use consistent attributes for y-axis in `chart`

changelog/next/bug-fixes/4175--from-tcp-read-json.md, libtenzir/builtins/operators/tcp-listen.cpp
We accidentally broke this with the Tenzir v4.12 release.
=> Restore implicit `read json` in `from tcp`

libtenzir/builtins/operators/unique.cpp
This does the same thing, but is faster and actually covered by tests.
=> Implement `unique` in terms of `deduplicate`

libtenzir/builtins/aspects/index.cpp
This is temporary and for debugging purposes in a production setup, so I don't think this needs documentation. This will be removed again.
=> Add the `show index` aspect

.github/workflows/nix.yaml
This action prepends `nix.conf` every time it runs.
=> Restrict magic-nix-cache to hosted runners

libtenzir/builtins/formats/json.cpp
Previously, when using `read json --arrays-of-objects` with a non-array input, we reported the following (confusing) error:
```
error: SUCCESS: No error
= note: expected an array of objects
```
This PR changes it to something like:
```
error: expected an array of objects
= note: got: <a snippet from the actual input>
```
=> Improve error message for `--arrays-of-objects`

tenzir/integration/data/misc/scripts/webserver.py, tenzir/integration/data/reference/http/test_load_http_post/step_00.ref, tenzir/integration/data/reference/http/test_load_http_post_form/step_00.ref, tenzir/integration/data/reference/http/test_save_http_post/step_00.ref, tenzir/integration/data/reference/http/test_save_http_post/step_01.ref, tenzir/integration/data/reference/http/test_save_http_post_add_header/step_00.ref, tenzir/integration/data/reference/http/test_save_http_post_delete_header/step_00.ref, tenzir/integration/data/reference/http/test_save_http_post_overwrite_header/step_00.ref, tenzir/integration/data/reference/http/test_save_http_put/step_00.ref
This PR makes the HTTP integration tests independent of the value of the `Accept-Encoding` header.
=> Make tests independent of Accept-Encoding header

libtenzir/include/tenzir/node.hpp, libtenzir/src/node.cpp
The old code had a race condition that sometimes triggered an assertion failure in CI. Now the tracking is properly implemented through monitoring, which should fix the issue we've been seeing.
=> Fix the lifetime tracking of node components

changelog/next/bug-fixes/4212-satta.md, plugins/amqp/src/plugin.cpp
This ensures that the `amqp` operator actually fails in cases such as network disconnects, which otherwise would not cause pipelines with amqp connectors to restart on failure.
=> Treat AMQP library exceptions as actual errors

changelog/next/bug-fixes/4210--slice-negative-end.md, libtenzir/builtins/operators/slice.cpp
Before this change, the `slice` operator would wait for its entire input to arrive when used with a positive begin and a negative (or missing) end value. This changes the implementation to return events eagerly that are known to be before the end of the range.
Fixes tenzir/issues#1820
=> Improve `slice` with positive begin and negative end

libtenzir/include/tenzir/concept/parseable/tenzir/time.hpp
This makes schema inference in many parsers a lot faster. We noticed that on GCC, we spend an unreasonable amount of time parsing durations when reading GELF.
=> Speed up the duration parser

web/docs/operators/metrics.md
This change adds the missing `open_fds` metric to the `tenzir.metrics.process` documentation.
=> Add the `open_fds` metric to the docs

changelog/next/changes/4211--slice-syntax.md, libtenzir/builtins/operators/head.cpp, libtenzir/builtins/operators/slice.cpp, libtenzir/builtins/operators/tail.cpp, plugins/parquet/integration/tests/tests.bats, tenzir/integration/tests/feather.bats, tenzir/integration/tests/pipelines_local.bats, web/docs/operators/head.md, web/docs/operators/slice.md, web/docs/operators/tail.md
This changes the `slice` operator to use a more familiar syntax for slicing events: `<begin>:<end>`, `<begin>:`, or `:<end>`.
This makes room for adding strides to the operator in the famililar Python syntax.
=> Change the syntax of the `slice` operator

changelog/next/bug-fixes/4222--remove-superfluous-path-separators.md, libtenzir/builtins/connectors/s3.cpp, plugins/gcs/src/plugin.cpp
Arrow 16 tightened their URI parsing: Double slashes for post-bucket path separators are now forbidden. We previously generated S3 and GCSs paths out of a parsed `arrow::util::Uri`, using a `"{}/{}", uri.host(), uri.path()"` format string to compensate for missing slashes. This exposed an unnecessary additional slash that this change removes.
See this Arrow PR diff: https://github.com/apache/arrow/commit/0148db4f97bfcf80237b265ee0d9a4b61194ffde
=> Remove the superfluous path separators when using S3 or GS connectors

changelog/next/bug-fixes/4236--multiple-schemas-in-contexts.md, libtenzir/builtins/contexts/geoip.cpp, libtenzir/builtins/contexts/lookup_table.cpp, nix/tenzir/plugins/source.json
The `lookup-table` (and theoretically the `geoip`) context did not handle multi-schema table slices correctly when being inspected. This change fixes that.
=> Support multiple table slice schemas when dumping contexts

.github/workflows/nix.nu, .github/workflows/nix.yaml, changelog/next/features/4188--rpm-package.md, cmake/TenzirPackage.cmake, nix/tenzir/default.nix, scripts/install.sh, scripts/rpm/postinstall, scripts/rpm/postuninstall, scripts/rpm/preinstall, scripts/rpm/preuninstall, tenzir/services/systemd/tenzir-node.service.in
This adds an RPM package build and integrates it with the installer and CI.
The package should work with RedHat, OpenSuse and their derivatives.
Installer testing is done with Rocky Linux.
=> Build an RPM package

web/docs/setup-guides/deploy-a-node.md
This adds one missing piece from #4188, namely the addition of an `RPM` tab in the manual node installation instructions.
=> Add an RPM tab in the deploy-a-node documentation

scripts/debian/postinst, scripts/debian/postrm, scripts/install.sh, scripts/rpm/postinstall, scripts/rpm/postuninstall
* Clear the destination path of the package download so `curl` does not abort.
* Drop the check for `adduser`, because it is out of place in the installer.
* Add `/opt/tenzir/bin` to the system default path for ease of use.
=> Minor installer improvements

changelog/next/features/4249--write-arrays-of-objects.md, libtenzir/builtins/formats/json.cpp, web/docs/formats/json.md
The new `write json --arrays-of-objects` option writes all events arriving within the same batch into a JSON array. This is convenient when interfacing with REST APIs through the `http` connector.
Fixes https://github.com/tenzir/issues/issues/1855
=> Add an option for writing JSON arrays of objects

libtenzir/builtins/operators/from_load_read.cpp, libtenzir/builtins/operators/to_write_save.cpp, libtenzir/builtins/operators/version.cpp, libtenzir/include/tenzir/plugin.hpp, libtenzir/src/exec_pipeline.cpp, plugins/zmq/src/plugin.cpp
Now that we render metrics from node-internal operators grayed-out, it became quickly apparent that these three were not categorized correctly.
=> Treat `publish`, `subscribe`, and `version` as internal

.github/workflows/docker.yaml, .github/workflows/nix.yaml, .github/workflows/tenzir.yaml, nix/overlay.nix, nix/tenzir/plugins/source.json, plugins/fluent-bit/integration/tests/tests.bats
This PR addresses a bit of flakyness in the integration tests:
* The `read stdin via fluent-bit` test is now skipped because it sometimes fails to produce any output.
* The tests of the `lookup` operator now install a test timeout and add some waiting time for initializing background lookups before continuing with subsequent steps.
This PR also adds opt-in CI steps to connect to the Tenzir tailnet for debugging.
=> Improve integration test robustness

plugins/zmq/src/plugin.cpp
The ZMQ Plugin prints debug information about every send and receive operation. This drowns out all other messages from the log files. This change reduces the level of these logs to TRACE, so that they don't get emitted in the default settings.
=> Tune down ZMQ logging

changelog/next/bug-fixes/4261--pipeline-updates-node-shutdown.md, nix/tenzir/plugins/source.json
This fixes a bug in pipeline management that caused the states of pipeline to be persisted even when the node was already shutting down.
Shutting down a node naturally stops some source operators. Pipelines with these sources naturally complete when the node shuts down. However, from a user perspective, these pipelines should run again when the node starts up again, as they were running when the node was stopped.
To solve this problem, the pipeline manager component no longer writes state updates for pipelines _after_ the node shutdown sequence started.
=> Do not persist pipeline state updates on node shutdown

web/blog/tenzir-v4.1/index.md
Algolia complained about this one when re-indexing docs.tenzir.com.
=> Fix a broken link in an old blog post

changelog/next/bug-fixes/4268--ip-equals-subnet.md, libtenzir/src/evaluate.cpp
A user in Discord asked this question:
> Hey, is there a chance to formulate the following statement more simple: `src_ip in 192.168.0.0/16 || src_ip in 172.16.0.0/12 || src_ip in 10.0.0.0/8`. I tried src_ip in `[192.168.0.0/16, 172.16.0.0/12, 10.0.0.0/8]` but this doesn't work.
We _used_ to support this transparently, because `ip == subnet` was treated the same way as `ip in subnet`, and `x in [y1, y2, ...]` resolves to `x == y1 or x == y2 or ...`. This PR adds back support for `ip == subnet`.
The subnet key support in `lookup-table` contexts also relies on this working when used with the `lookup` operator, which is fixed by this change as well.
=> Evaluate `ip == subnet` predicates

changelog/next/bug-fixes/4224--configured-context-loading-precedence.md, nix/tenzir/plugins/source.json
This change adds order to the chaos of loading contexts.
Configured contexts will be loaded first, and non-configured contexts that happen to share the same name will be renamed to avoid non-deterministic loading conflicts.
=> Handle loading of configured and non-configured contexts with the same name

changelog/next/bug-fixes/4224--configured-context-loading-precedence.md
This is an update for a changelog entry that contained outdated information.
=> Fix the configured context load-related changelog entry

changelog/next/changes/4273--approx-median.md, changelog/next/features/4273--percentile.md, libtenzir/builtins/aggregation-functions/quantile.cpp, web/docs/operators/summarize.md
This adds aggregation functions `p99`, `p95`, `p90`, `p75`, and `p50`, and renames `approximate_median` to `median`.
With TQL2 we probably want this to just be `percentile(0.99, foo)` rather than `p99(foo)`, but for now this is the best we can do and I had a use case for these.
=> Add percentile aggregation functions

changelog/next/features/4274--lookup-table-erase.md, libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/contexts/lookup_table.cpp, nix/tenzir/plugins/source.json, web/docs/contexts/bloom-filter.md, web/docs/contexts/lookup-table.md
For `lookup-table` contexts, the `context update` operator now sports a new `--erase` flag, which entries to be removed rather than aded.
=> Enable selective deletion of lookup table entries

nix/tenzir/plugins/source.json
On a node where several pipelines are running, the the pipeline manager competes with them for scheduling time, causing the /pipeline/create endpoint to take upwards of 10s on non-powerful systems like ECS nodes or github runners.
See https://github.com/tenzir/tenzir-plugins/pull/252
=> Detach the pipeline manager

changelog/next/bug-fixes/4280--commutative-comparison.md, libtenzir/src/evaluate.cpp
While `ip == subnet` worked, `subnet == ip` did not. The same applied to `string == pattern` and `pattern == string`.
=> Make `ip == subnet` and `string == pattern` commutative

changelog/next/features/4279--allow-pip-stdout.md, libtenzir/builtins/operators/python.cpp
Pip sometimes wants to draw a spinner on `stdout` during package installation. This currently leads to setup failures, because we're closing `stdout` before execing pip and pip does not check if `stdout` is `None` when probing if it is a TTY.
=> Allow pip to write to stdout in venv creation

.gitmodules, nix/update-impl.sh
For submodules other than `contrib/tenzir-plugins`, this sets the `shallow = true` option, which causes `git submodule update` to do a shallow clone of submodules, unless `--no-recommend-shallow` is used.
For `contrib/tenzir-plugins`, this explicitly disables shallow cloning, and sets the merge strategy to rebase in the submodule in case of uncomitted changes. This makes rebasing across submodule bumps a lot easier.
=> Make submodules easier to work with

changelog/next/bug-fixes/4289--summarize-by-null.md, libtenzir/builtins/operators/summarize.cpp, libtenzir/src/table_slice.cpp
This is a two-fold change:
1. The `put`, `set`, `extend`, and `replace` operators when used to assign a field the value `null` set the string type rather than the null type, because they predated the null type. This is now fixed.
2. The `summarize` operator no longer crashes when grouping by a null type.
Fixes tenzir/issues#1900
=> Fix using `summarize … by x` when `x` is of type `null`

changelog/next/features/4290--rendered-diagnostics.md, nix/tenzir/plugins/source.json, tenzir/integration/tests/tcp.bats, web/docs/operators/diagnostics.md
The new `rendered` field contains the rendered diagnostic for use in the app so that it can display diagnostics the same way we render them on the command-line.
=> Add a `rendered` field to diagnostics

changelog/next/bug-fixes/4288--start-abort-error.md, libtenzir/builtins/commands/exec.cpp, libtenzir/builtins/operators/serve.cpp, libtenzir/src/error.cpp, libtenzir/src/exec_pipeline.cpp, libtenzir/src/execution_node.cpp, libtenzir/src/pipeline_executor.cpp, nix/tenzir/plugins/source.json, web/openapi/openapi.yaml
This changes the error message for something like `version | version` from
~~~
error: failed to run
error: 
~~~
to
~~~
error: 'version' does not accept events as input
= note: failed type inference
~~~
I don't think the resulting diagnostic is good, but this PR is just about restoring the behavior that we had previously (until it was broken by one of the diagnostic propagation PRs).
=> Fix start abort error message

changelog/next/features/5126.md, libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/contexts/geoip.cpp, libtenzir/builtins/contexts/lookup_table.cpp, libtenzir/include/tenzir/detail/subnet_tree.hpp, libtenzir/include/tenzir/plugin.hpp, libtenzir/src/detail/subnet_tree.cpp, libtenzir/test/detail/subnet_tree.cpp, nix/tenzir/plugins/source.json, web/docs/contexts/lookup-table.md
The context update operator can now handle two additional flags, update-timeout and create-timeout, allowing the user to control when entries should be expired. The operator introduces a new struct value_data which holds additional time information along with the original value data. Expired entries are removed from memory on save() and load(). Update-timeout only tracks running time.
=> Allow configuring timeouts per lookup table entry

plugins/parquet/parquet.cpp
This PR fixes the error diagnostic that occurs when the parquet writer creation fails. (Doesn't need a changelog IMHO)
=> Fix parquet file writer diagnostic

changelog/next/bug-fixes/4297--backoff-changes.md, libtenzir/src/execution_node.cpp
This turns down the execution node backoff behavior. Instead of going from 10ms to 1s with 1.25x increases, we now go from 250ms to 1 min with 2x increases.
Additionally, this causes execution nodes that explicitly ask not to be scheduled to be exempt from backoff and not to be scheduled at all.
=> Tone down execution node backoff behavior

changelog/next/features/4300--lookup-parallel-level.md, nix/tenzir/plugins/source.json, web/docs/operators/lookup.md
This adds a new `--parallel <level>` option to the `lookup` operator that controls how many partitions it opens at once for retrospective lookups. Cranking this number up makes lookups significantly faster, but also causes its resource usage to rise accordingly.
=> Make the parallel level in `lookup` configurable

nix/tenzir/plugins/source.json
This simplifies the shutdown logic of the `context-manager` actor significantly. No user-visible changes.
=> Remove the context watchdog actor

libtenzir/builtins/operators/export.cpp, libtenzir/builtins/operators/summarize.cpp, libtenzir/src/execution_node.cpp
This makes a small change to the scheduling behavior of `summarize … timeout …` and `summarize … update-timeout …`, which are now scheduled less aggressively.
=> Reduce CPU usage of `summarize … [update-]timeout …`

changelog/next/changes/4309--show-hidden-pipelines.md, nix/tenzir/plugins/source.json
This fixes a bug: hidden pipelines are supposed to be exempt from `api /pipeline/list`, but not from `show pipelines`. Otherwise, it is impossible to retrieve their ids for debugging purposes.
=> Include hidden pipelines in `show pipelines`

libtenzir/src/http.cpp
Trailing `=` in a Base64 header caused the wrong branch to be selected.
=> Fix HTTP header parsing logic

changelog/next/features/4314--ttl-in-api.md, nix/tenzir/plugins/source.json, web/openapi/openapi.yaml
Turns out that it's rather useful to show the TTL in addition to the remaining TTL when listing pipelines.
Fixes https://github.com/tenzir/issues/issues/1905
=> Add the `ttl` to the `/pipeline/list` API

libtenzir/src/offset.cpp
This fixes access into struct arrays and record batches for empty offsets. This is handled nicely already for table slices, but it looks like we forgot this overload. I ran into this while working on some other code, and figured it'd be worth extracting this fix already. It shouldn't be possible for users to run into this before TQL2.
=> Fix `offset{}.get(…)` for struct arrays and record batches

changelog/next/bug-fixes/4317--kafka-args.md, plugins/kafka/src/plugin.cpp
This was advertised to exist in the docs, but was actually only implemented for the ´kafka` loader. The fix is mostly a carbon copy of the loader code.
Fixes tenzir/issues#1889
=> Add missing `-X` option for `kafka` saver

libtenzir/builtins/components/metrics_collector.cpp, libtenzir/include/tenzir/node.hpp, libtenzir/include/tenzir/plugin.hpp, libtenzir/src/node.cpp, libtenzir/src/plugin.cpp, nix/tenzir/plugins/source.json
This extends the component_plugin interface so that can provide a list of other components that have to be instantiated before the plugins own component can be spawned.
=> Allow components to depend on other components

changelog/next/bug-fixes/4326--diagnostics-collector.md, nix/tenzir/plugins/source.json
This PR fixes an issue where diagnostics where not properly propagated and thus not available to the `diagnostics` operator.
=> Fix minor issues with the diagnostics and metrics collector

changelog/next/features/4329--partitions-operator.md, libtenzir/builtins/operators/partitions.cpp, libtenzir/builtins/operators/show.cpp, libtenzir/include/tenzir/actors.hpp, libtenzir/src/catalog.cpp, nix/tenzir/plugins/source.json, web/docs/operators/partitions.md, web/docs/operators/show.md
The `partitions [<expr>]` operator supersedes the `show partitions` operator. The new and optional positional argument is a filter expression for doing a candidate check in the catalog component. This has two primary use cases:
1. Seeing which schemas would be considered for `export | where <expr>` by running `partitions <expr> | deduplicate schema`.
2. Quickly calculating an upper bound for the number of results in `export | where <expr>` by running `partitions <expr> | summarize events=sum(events)`.
Fixes https://github.com/tenzir/issues/issues/1532
=> Add an operator for partition candidate checks

changelog/next/bug-fixes/4330--fix-deletion-of-configured-contexts.md, nix/tenzir/plugins/source.json
This fixes an oversight in https://github.com/tenzir/tenzir/pull/4325.
=> Fix deletion of removed configured contexts

changelog/next/bug-fixes/4330--fix-deletion-of-configured-contexts.md, changelog/next/features/4329--partitions-operator.md, changelog/v4.17.3/bug-fixes/4330.md, changelog/v4.17.3/features/4329.md, python/pyproject.toml, version.json, web/versioned_docs/version-v4.17/operators/partitions.md, web/versioned_docs/version-v4.17/operators/show.md
This commit was created with `/scripts/prepare-release`.
* Updated `/version.json` to `v4.17.3`.
* Moved all changelog entries from `/changelog/next` to `/changelog/v4.17.3`.
* Updated the python bindings version in `/python/pyproject.toml` to `v4.17.3`.
=> Prepare repository for Tenzir v4.17.3

changelog/next/bug-fixes/4333--fix-bad-file-descriptor-in-python-operator.md, libtenzir/builtins/operators/python.cpp, libtenzir/builtins/operators/shell.cpp
This fixes "Bad file descriptor" errors from the python operator and shell operators.
Additionally, a thread-safety issue in the python operators environment cloning routine is worked around.
=> Fix two concurrency issues related to child process creation

changelog/next/bug-fixes/4341--gelf-parser-splitting.md, libtenzir/builtins/formats/json.cpp
The zero-size check in the `split_at_null()` input loop was causing the loop to invalidate chunks if the first character was a null character. This is easily triggerable by using the `gelf` parser on `gralog` data. The NDJSON events are separated by null characters, and the parser was ignoring events if such an invalidation occured.
=> Remove the zero-size check in the split_at_null() input loop

changelog/next/bug-fixes/4346--subscriber-crash.md, nix/tenzir/plugins/source.json
This fixes a very rare crash in the node through an assertion failure when in an SPMC or MPMC setup one of multiple subscribers to the same topic disconnects, where other subscribers were sent the next batch of events without waiting for them to acknowledge the previous batch.
Fixes tenzir/issues#1941
=> Fix possible crash when one of multiple subscribers disconnects

changelog/next/bug-fixes/4349--export-live-where.md, changelog/next/changes/4349--subscribe-metrics.md, libtenzir/builtins/operators/export.cpp, nix/tenzir/plugins/source.json
… and a small bug fix for `export --live | where … ` when using type extractors or concepts.
=> Push expressions into `subscribe` for better metrics

libtenzir/builtins/commands/exec.cpp, libtenzir/builtins/operators/if.cpp, libtenzir/include/tenzir/diagnostics.hpp, libtenzir/include/tenzir/exec_pipeline.hpp, libtenzir/include/tenzir/tql2/exec.hpp, libtenzir/include/tenzir/tql2/parser.hpp, libtenzir/include/tenzir/tql2/resolve.hpp, libtenzir/include/tenzir/tql2/tokens.hpp, libtenzir/include/tenzir/try.hpp, libtenzir/src/argument_parser2.cpp, libtenzir/src/exec_pipeline.cpp, libtenzir/src/tql2/exec.cpp, libtenzir/src/tql2/parser.cpp, libtenzir/src/tql2/resolve.cpp, libtenzir/src/tql2/tokens.cpp, tenzir/integration/data/reference/lexer/test_invalid_utf-2d8/step_00.ref
This PR improves multiple APIs with a new `failure_or<T>` return value (that returns a `failure` when a `diagnostic::error` was emitted) and uses this to refactor quite a few functions. It also exposes a `parse_and_compile` function for a follow-up PR that will be used to integrate TQLv2 into the pipeline manager.
=> Refactor TQLv2 execution and expose `parse_and_compile`

libtenzir/builtins/connectors/s3.cpp, libtenzir/include/tenzir/plugin.hpp, libtenzir_test/src/main.cpp, plugins/zmq/src/plugin.cpp, tenzir/tenzir.cpp
This fixes a rather obscure bug that I've been trying to hunt down for quite some time, where some plugins are not stored sorted by name. Turns out this was only happening for builtins and depended on the order of static initialization. Plugins may bundle further builtins, which then get added once the plugin is loaded.
This also removes `plugin::deinitialize()`—I finally figured out what the issue was.
=> Ensure plugins are always in the right order

libtenzir/include/tenzir/detail/assert.hpp, libtenzir/include/tenzir/detail/narrow.hpp, libtenzir/src/detail/assert.cpp
Before:
```
error: todo
= note: unhandled exception in exec-node tql2.summarize
```
After:
```
error: todo @ /__w/tenzir/libtenzir/builtins/functions/numeric.cpp:266
= note: unhandled exception in exec-node tql2.summarize
```
=> Always render the source location for panics

libtenzir/builtins/operators/export.cpp, libtenzir/include/tenzir/actors.hpp, libtenzir/include/tenzir/importer.hpp, libtenzir/src/importer.cpp
Before this change, `export --internal --live` (which backs `metrics --live` and `diagnostics --live`) received all imported events, not just internal events. This change makes it so that this the internal attribute is evaluated earlier.
To get a good feel of the reduction, use the following pipelines:
```
export --live
| summarize eps=count(.) timeout 1s
| summarize mean(eps) timeout 1m
```
```
export --live --internal
| summarize eps=count(.) timeout 1s
| summarize mean(eps) timeout 1m
```
Previously, the `export` operators needed to evaluate the sum of the events coming in, now they don't anymore.
=> Reduce load in `metrics --live` and `diagnostics --live`

nix/tenzir/plugins/source.json, web/openapi/openapi.yaml
This change tightens the enforcement of requirements for `hidden` pipelines. They must always start automatically, and autodelete in all stopping cases. Instead of making the user enforce that (and even missing an enforcement for `autodeletion` flags), we simply overwrite the flags in the request.
=> Tie pipeline autocreation & autodeletion to the hidden flag

libtenzir/builtins/operators/partitions.cpp
We have a use for this in an environment where running `export | summarize min(:time), max(:time)` is too expensive. This addresses that particular need by enabling `partitions --experimental-include-ranges | summarize min(ranges.time.min), max(ranges.time.max)`.
Note that the option is intentionally undocumented and will be removed again in the future without further notice.
=> Add an experimental mechanism for inspecting min-max sketches

libtenzir/builtins/connectors/curl.cpp, libtenzir/src/http.cpp, libtenzir/test/http.cpp
This adds supports for adding URL parameters `?foo=42&bar=43` as `http::request_item` and also adds a TQLv2 version of the HTTP loader: 
```
load_http <url>, method=<string>, params=<record>, headers=<record>
```
Example:
```python
load_http(
"http://api.example.org", 
params={foo: "test", bar: "baz"}, 
headers={"My-Custom-Header": "Example"},
)
```
=> Handle URL params in loader and add `load_http` for TQLv2

changelog/next/bug-fixes/4363--lookup-crash.md, nix/tenzir/plugins/source.json
This fixes a bug that could lead to an assertion failure because of a race condition in how parallel retro lookups tracked how many partitions were enqueued.
Fixes tenzir/issues#1968
=> Fix open partition tracking in the `lookup` operator

changelog/next/bug-fixes/4367--tcp-reuseaddr.md, libtenzir/builtins/operators/tcp-listen.cpp
A pipeline with `from tcp://...` could not be restarted seamlessly because the listening port was blocked for a certain amount of time after the pipeline was stopped.
This change adds the necessary flags so the port can be reused immediately.
=> Allow immediate restarts of the TCP listen connector

changelog/next/features/4369--metrics-name.md, libtenzir/builtins/operators/metrics.cpp, web/docs/operators/diagnostics.md, web/docs/operators/metrics.md
`metrics <name>` is equivalent to `metrics | where #schema == "tenzir.metrics.<name>"`, which is a very common thing to write and a lot easier to type and understand.
=> Add an optional `name` argument to the `metrics` operator

changelog/next/changes/4370--serve-timeouts.md, libtenzir/builtins/operators/serve.cpp, libtenzir/include/tenzir/defaults.hpp
This brings up the default and maximum long-polling timeouts for `/serve` from 2s and 5s to 5s and 10s, respectively.
I've made this change because we've started polling a lot of metrics and diagnostics from the app, and this drastically reduces the load on the API when there are no diagnostics.
We can't really raise it much higher because of AWS' lambda and websocket gateway timeouts, but this I think we can safely do.
=> Raise the default and max timeouts for `/serve`

changelog/next/changes/4365--low-prio-export.md, changelog/next/features/4339--custom-operator-metrics.md, changelog/next/features/4339-4365--custom-operator-metrics.md, libtenzir/builtins/operators/export.cpp, libtenzir/src/argument_parser2.cpp, libtenzir/src/node.cpp, web/docs/operators/export.md, web/docs/operators/metrics.md
This is a complete rewrite of the `export` operator that brings a few changes:
1. The operator is no longer detached, but rather cooperatively scheduled. This makes the operator cheaper to start.
2. The operator now emits metrics with the name `tenzir.metrics.export` once per second and on shutdown.
3. The operator now schedules up to three partitions at once for retroactive queries, pipelining them for an improved performance, especially when using smaller partitions. A new `--parallel <level>` option allows for overriding this setting.
4. The gap between retro and live exports is now drastically reduced, as the live export starts immediately and no longer waits for the retro export to finish. Note that this doesn't eliminate the gap window entirely, as there is still a gap between the …
=> Revamp the `export` operator

changelog/next/features/4368--api-metrics.md, libtenzir/include/tenzir/node.hpp, libtenzir/src/node.cpp, web/docs/operators/metrics.md
> [!NOTE]
> This depends on the actor registry changes made in #4365.
The new `tenzir.metrics.api` metrics record every single interaction with a Tenzir Node through its API.
For example, this shows how often each endpoint is used per minute:
```
metrics --live
| where #schema == "tenzir.metrics.api"
| summarize count=count(.) by path timeout 1m
| write lines
```
```
/pipeline/reset-ttl 1
/pipeline/launch 19
/pipeline/update 44
/serve 81
```
This shows the most commonly started pipeline through the app in the last hour:
```
metrics
| where #schema == "tenzir.metrics.api" and path == "/pipeline/launch"
| top params.definition
| head 1
| write lines
```
```
"diagnostics |\nwhere pipeline_id == \"load-test-1\" | where run == 15\n| sort timestamp asc" 10
```
=> Introduce API metrics

changelog/next/changes/4348--deduplicate-diagnostics.md, libtenzir/src/diagnostics.cpp
The newline is currently always printed to `stdout` instead of the target stream. This mostly "works" when using `tenzir` directly from the terminal, but obviously doesn't in many other cases.
=> Fix diagnostic newline printing

changelog/next/features/4374--platform-metrics.md, nix/tenzir/plugins/source.json, web/docs/operators/metrics.md
This adds `metrics platform`—a simple metric emitted once per second that signals whether the connection to the Tenzir Platform is alive and well from the node's perspective.
=> Emit connection status metrics from the platform

libtenzir/builtins/operators/api.cpp, libtenzir/include/tenzir/actors.hpp, libtenzir/src/node.cpp, nix/tenzir/plugins/source.json, web/docs/operators/metrics.md
End-to-end request tracing, who thought this'd ever be a thing?
=> Add the `request_id` to API metrics

changelog/next/features/4380--disable-node-to-node-conns.md, libtenzir/src/start_command.cpp, tenzir.yaml.example, web/docs/setup-guides/deploy-a-node.md
This change makes it so that setting the value `false` for the `tenzir.endpoint` option causes the node not to expose the node as a remote actor for `tenzir` processes or other nodes to connect to it.
=> Allow disabling node-to-node connections

changelog/next/bug-fixes/4382--fix-every-export.md, libtenzir/builtins/operators/export.cpp
=> Don't terminate `export` when used with `every`

changelog/next/bug-fixes/4389--fix-every-export-again.md, libtenzir/builtins/operators/export.cpp
The previous `exit_reason::normal` did not cause the export bridge actor to exit because the `importer` still held a strong handle.
=> Send a hard shutdown to the export bridge

changelog/next/bug-fixes/4396--exprt-live-overflow.md, changelog/next/changes/4396--export-queued-events.md, libtenzir/builtins/operators/export.cpp, web/docs/operators/export.md, web/docs/operators/metrics.md
Before this change, a backpressure-blocked pipeline with `export --live` was able to use potentially use infinite amounts of memory.
This also adds the `queued_events` field to export metrics.
=> Prevent unbounded memory usage in `export --live`

changelog/next/bug-fixes/4399-sub-hidden-back-pressure.md, libtenzir/builtins/operators/tcp-listen.cpp, libtenzir/include/tenzir/actors.hpp, libtenzir/include/tenzir/execution_node.hpp, libtenzir/include/tenzir/operator_control_plane.hpp, libtenzir/include/tenzir/pipeline_executor.hpp, libtenzir/src/exec_pipeline.cpp, libtenzir/src/execution_node.cpp, libtenzir/src/node.cpp, libtenzir/src/pipeline.cpp, libtenzir/src/pipeline_executor.cpp, nix/tenzir/plugins/source.json, web/docs/operators/subscribe.md
This change makes it so that `subscribe` no longer propagates back pressure when run as part of a hidden pipeline, i.e., a pipeline that is not visible on the Tenzir Platform.
Without this change, it was surprisingly easy to break publishers by simply subscribing to their topic and piping the data into an operator that did nothing, e.g., `serve` with a very small buffer size.
=> Break back pressure in hidden subscribers

.github/workflows/tenzir.yaml, plugins/web/CMakeLists.txt
The Homebrew package for its http parser dependency was disabled quite a while ago because the library is unmaintained and no longer compiled from source against our current compiler toolchain, so it's really hard to build the `web` plugin on macOS. This just disables it.
This also re-enables the `parquet` plugin on macOS, as that no longer uses illegal instruction as far as I can tell.
=> Disable the `web` plugin on macOS

libtenzir/builtins/operators/buffer.cpp
We emitted the field as `free`, but had `remaining` in the schema.
=> Fix bug in `buffer` metrics

.github/workflows/tenzir.yaml
This makes it so that on the next release, we will upload not just `v4.19.0`, but also `v4.19` and `v4` images.
Fixes tenzir/issues#1977
=> Upload Docker images for major and major.minor version

changelog/next/changes/4411--serve-simple-format-only.md, libtenzir/builtins/aspects/schemas.cpp, libtenzir/builtins/operators/serve.cpp, libtenzir/include/tenzir/type.hpp, libtenzir/src/type.cpp, libtenzir/test/type.cpp, web/openapi/openapi.yaml
This is now always the default. We've had it for quite some time now, and we've used it in the app from the very day we added it.
Fixes tenzir/issues#1706
=> Remove the `use_simple_format` option for `/serve`

libtenzir/builtins/functions/ip.cpp
This change implements an `ip()` function in TQL2 that generates `ip`-typed values out of `string`, `ip` and `null` values.
=> Implement the `ip()` function in TQL2

libtenzir/include/tenzir/arrow_utils.hpp, libtenzir/include/tenzir/tql2/eval_impl.hpp, libtenzir/src/tql2/eval_impl.cpp, tenzir/integration/data/reference/expression/test_list_indexing/step_00.ref, tenzir/integration/tests/expression.bats
This PR adds list indexing to TQL2. 
```
source [
{ x: [1, 2, 3] },
{ x: [4, 5] },
]
y = x[2]
z = x[-1]
```
```
warning: list index out of bounds
--> <input>:5:7
|
5 | y = x[2]
|       ~ 
|
{
"x": [
1,
2,
3
],
"y": 3,
"z": 3
}
{
"x": [
4,
5
],
"y": null,
"z": 5
}
```
=> Add list indexing

libtenzir/include/tenzir/detail/to_xsv_sep.hpp, libtenzir/include/tenzir/io/read.hpp, libtenzir/include/tenzir/io/save.hpp, libtenzir/include/tenzir/io/write.hpp, libtenzir/include/tenzir/value_ptr.hpp, libtenzir_test/tenzir/test/serialization.hpp, shell.nix
Added missing #pragma once in some files.
The default llvm toolchain is v17 in nix-pkgs now and there is no need to pin it to a lower version.
=> Minor changes

changelog/next/bug-fixes/4428--handle-amqp-heartbearts-in-saver.md, plugins/amqp/src/plugin.cpp
AMQP connections with heartbeats enabled require periodic acknowledgement and response to heartbeat frames sent from the broker, even in situations where no explicit interactions with the broker occur for a long time. We need to explicitly care about heartbeats in such cases.
This PR adds additional code that ensures that heartbeats are handled appropriately when configured in an `amqp` saver.
Please review carefully, I have little experience with C++ memory management features such as `shared_ptr`s and their behaviour when captured in lambdas.
=> Explicitly handle AMQP heartbeats in saver

libtenzir/builtins/operators/python.cpp, python/tenzir/tools/python_operator_executor.py
We cannot use the `|` type union syntax yet.
This also contains a fix for the python operator cleanup logic.
=> Restore Python 3.9 compatibility

nix/tenzir/plugins/source.json
We already have `// experimental-tql2` to enable the new language for the app, configured pipelines, etc. We want to drop the `experimental` prefix. Thus, `// tql2` is the new flag. The longer form is keeps working for compatibility, but should no longer be used.
=> Simplify `// tql2` flag

libtenzir/src/application.cpp, libtenzir/src/file.cpp, libtenzir/src/io/write.cpp, libtenzir/src/start_command.cpp, tenzir.yaml.example
This is useful for `docker compose` setups in conjunction with OS chosen ports. A client instance can read the endpoint from a shared volume path to learn about the listening port.
=> Add a --write-endpoint=<path> option to tenzir-node

libtenzir/builtins/operators/partitions.cpp
Achieving a factor 100 speedup on my admittedly pathological catalog with >80000 unique schemas.
=> Slightly optimize the partitions operator

changelog/next/bug-fixes/4439--consistent-subscribe-metrics.md, nix/tenzir/plugins/source.json
Events that the `subscribe` operator receives while the buffer is empty and `buffer_rp` is pending get delivered via `buffer_rp` - but the metrics were missing. This change adds metrics for those events.
=> Emit metrics for events that get emitted as part of push() in the subscribe operator

libtenzir/builtins/aspects/plugins.cpp
This makes it easier to spot which formats, connectors, and operators are still missing at this time.
=> Add TQL2 plugins types to `show plugins`

libtenzir/builtins/connectors/file.cpp
This makes it so that `load_file "~/example.json"` works.
=> Expand home directory in `load_file`

changelog/next/changes/4447--memory-control.md, libtenzir/builtins/operators/export.cpp, libtenzir/src/execution_node.cpp, nix/tenzir/plugins/source.json, tenzir.yaml.example, web/docs/installation/tune-performance/README.md, web/docs/operators/serve.md
The new `tenzir.demand` configuration section is an expert-only configuration section that lets users control how eagerly operators demand input from their upstream operators.
=> Add new expert-only options to control demand

libtenzir/include/tenzir/type.hpp, libtenzir/src/tql2/eval_impl.cpp, libtenzir/src/type.cpp, tenzir/integration/data/reference/expression/test_list_construction/step_00.ref, tenzir/integration/tests/expression.bats
Previously, item types of a `[...]` expression had to match exactly (ignoring top-level `null` values). This PR relaxes that restriction to generally allow unifyable types, so that things like `[{x: 42}, {x: null}]` or `[{x: 42}, {y: 42}]` are valid.
=> Unify types in list expressions

libtenzir/builtins/operators/throttle.cpp, nix/tenzir/plugins/source.json, web/docs/operators/azure-log-analytics.md, web/docs/operators/throttle.md
This makes it possible to set the window size over which the bandwidth is restricted. Additionally, this updates `azure-log-analytics` to make use of `throttle` to properly respect the upstream rate limit.
=> Expose `--within <duration>` for `throttle`

libtenzir/builtins/operators/pass.cpp
Stumbled upon this not being ported yet because it's the file I always copy when I create a new operator.
=> Port `pass` to TQL2

libtenzir/builtins/functions/string.cpp
`" \thello, world!\n".trim()` becomes `"hello, world!"`. The `trim` method takes an optional named argument `chars` that must be a constant-evaluated string containing characters to trim.
=> Add a `trim` method for TQL2

libtenzir/builtins/operators/import.cpp
I don't think anyone's ever run into this, but I just happened to do so while trying to reproduce something else. It's a workaround, not a fix, but I think that's good enough for now.
=> Guard against empty events in the catalog

changelog/next/bug-fixes/4499--serve-cpu-usage.md, libtenzir/builtins/operators/serve.cpp
Here's a bad interaction I did not think of before: `ctrl.set_waiting(false)` _immediately_ schedules an operator again so that it can wake itself up from a request response handler. The `serve` operator did not properly dismiss empty events—which are sent directly before an operator starts idling—and thus went into an infinite loop of starting to idle and waking up again.
=> Fix excessive CPU usage of `serve`

tenzir/integration/tests/batching.bats, tenzir/integration/tests/feather.bats, tenzir/integration/tests/gelf.bats, tenzir/integration/tests/leef.bats, tenzir/integration/tests/time.bats, tenzir/integration/tests/vast_server.bats
CI sometimes hangs in tests without bats timeouts (it can also hang in tests with timeouts, but that seems to happen only under special circumstances). Thus I added timeouts to the remaining test files.
=> Add missing integration test timeouts

changelog/next/bug-fixes/4505--slice-regression.md, libtenzir/builtins/operators/slice.cpp, libtenzir/src/detail/assert.cpp, tenzir/integration/tests/pipelines_local.bats
This fixes an invalid assertion failure when `slice` when used with a positive begin and negative end value returned less events than `-end`.
Additionally, this removes a duplicate source location in assertions.
=> Fix `slice 1:-1` for exactly one event

changelog/next/bug-fixes/4508--uncaught-exception.md, libtenzir/builtins/operators/python.cpp, libtenzir/builtins/operators/shell.cpp
This follows up on a mysterious segfault from an uncaught exception we've seen in a production deployment. The exception was thrown by some Boost.Process API, so it could've only been the `shell` or `python` operator, and since execution nodes have an exception handler installed it couldn't be from the operator's run loop directly. This led me directly to this manually spawned thread int he `shell` operator.
Additionally, this change makes the `python` operator signal its startup quicker. It doesn't make it actually initialize the venv any faster, but it makes it so that starting a pipeline doesn't wait for it anymore.
=> Fix a potentially uncaught exception in `shell`

changelog/next/bug-fixes/4516--azure-fix.md, nix/tenzir/plugins/source.json
This fixes a regression introduced in Tenzir v4.19.2 in the `azure-log-analytics` operator that prevented it from starting correctly.
=> Fix regression in `azure-log-analytics`

libtenzir/CMakeLists.txt, libtenzir/include/tenzir/detail/preserved_fds.hpp, nix/fast_float/source.json, python/uv-source-info.json
This bumps the following dependencies:
- simdjson to v3.10.0
- fast_float to v6.1.4
- uv to v0.3.0
This also adds support for Boost v1.86 or newer, which changed some include paths.
=> Bump bundled dependencies to their latest version

changelog/next/features/4513--unstoppable-pipelines.md, libtenzir/include/tenzir/package.hpp, libtenzir/src/package.cpp, libtenzir/src/version.cpp, nix/tenzir/plugins/source.json, tenzir.yaml.example, web/docs/packages.md, web/docs/usage/run-pipelines/README.md, web/openapi/openapi.yaml
This change implements the `unstoppable` flag. Pipelines with that flag enabled automatically start, can not be stopped or paused, and if they do complete, they automatically fail.
=> Implement unstoppable pipelines

changelog/next/bug-fixes/4523--ip-parsing.md, libtenzir/builtins/formats/json.cpp, libtenzir/include/tenzir/concept/parseable/tenzir/data.hpp, libtenzir/src/data.cpp
We previously parsed fields such as `{"x": "2dff::"}` as a string, instead of the IPv6 address `2dff::`. The reason for that is that some places did not account for ordering requirements of the `|` parser combinator. If durations tried first, then the `2d` prefix is parsed as a valid duration, before the completeness check sees that the rest of the string was not consumed, therefore failing the data parsing and keeping it as a string. This PR changes the order, such that parsers that accept a prefix of another parser are ordered after that other parser.
=> Fix data parser precedence

libtenzir/include/tenzir/concept/parseable/core/choice.hpp, libtenzir/include/tenzir/concept/parseable/tenzir/time.hpp, libtenzir/include/tenzir/concept/printable/std/chrono.hpp, libtenzir/src/tql2/parser.cpp, libtenzir/test/time.cpp
This fixes parsing of negative compound durations and pretty-printing of negative durations.
- Fixes tenzir/issues#2080
- Fixes tenzir/issues#2082
=> Fix duration parsing and printing

.dockerignore, scripts/debian/install-dev-dependencies.sh
I ran into issues building a Docker image running `docker build . -f Dockerfile --target tenzir-node-de` without these dependencies.
=> Add bats-assert and bats-support dependencies

changelog/next/bug-fixes/4530--export-crash.md, libtenzir/src/node.cpp
We've seen a few reports of crashes on main where the `export` operator fails to retrieve the `filesystem` component's actor handle. This cannot happen on startup, as the filesystem is registered before the node has started up, but it can very well happen on shutdown, if the node is tearing down while a new `export` operator is starting up. This fixes the crash by responding with a proper error message instead when a component is not available.
Fixes https://github.com/tenzir/issues/issues/2081
=> Fix a crash when starting `export` on shutdown

changelog/next/bug-fixes/4531--context-inspect-crash.md, libtenzir/builtins/contexts/lookup_table.cpp
This fixes a crash resulting from invalid API usage when running `context inspect <ctx>` for a `lookup-table` context with heterogeneous values using subnets as keys.
=> Fix crash for heterogeneous subnet lookup tables

scripts/macOS/install-dev-dependencies.sh
These dependencies are pre-installed on the macOS runners, so there's no need to attempt to install them again.
=> Fix macOS CI warnings

libtenzir/builtins/operators/api.cpp, libtenzir/include/tenzir/arrow_utils.hpp, libtenzir/include/tenzir/error.hpp, libtenzir/src/error.cpp
For example:
```
// tql2
api "/pipeline/update", {
id: "1e6b6d7c-4b7f-4cbf-bf65-115a7fc27145",
action: "stop",
}
```
- Fixes https://github.com/tenzir/issues/issues/2091
=> Port the `api` operator to TQL2

libtenzir/builtins/functions/community_id.cpp, tenzir/integration/data/reference/functions/test_community-2d5fid/step_00.ref
This adds source location information to a few more diagnostics emitted by the `community_id` function, and also converts two errors into warnings, as run-time type errors are generally emitted as warnings.
=> Improve `community_id` diagnostics

libtenzir/include/tenzir/package.hpp, libtenzir/src/package.cpp, libtenzir/src/version.cpp, nix/tenzir/plugins/source.json, web/docs/operators/package.md, web/docs/operators/packages.md, web/docs/packages.md
This contains two updates to the package format:
* Support a `config.overrides` field in the package definition that can be used to modify other fields of the package
* Rename 'snippets' to 'examples'
* Add a new optional `config.version` key that can be set to any string by the user to indicate the package version
* Add a new optional 'config.metadata` key that can be used to store arbitrary opaque data
* Add a new `packages` operator that can show the installed package information in an extended format more suited to consumption by the app
=> Revamp package format

libtenzir/builtins/functions/misc.cpp, tenzir/integration/data/reference/functions/test_has/step_00.ref, tenzir/integration/tests/functions.bats
Checks the immediate children of `<record>` for existence of a field named `<string>`. Currently, does not check for nulls.
Closes https://github.com/tenzir/issues/issues/2088
=> Implement `<record>.has(<string>)`

changelog/next/bug-fixes/4535--retro-queued-events.md, changelog/next/features/4535--faster-lookup.md, libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/contexts/lookup_table.cpp, libtenzir/include/tenzir/plugin.hpp, nix/tenzir/plugins/source.json
This makes `lookup` faster by performing one catalog lookup per event in the context update, as opposed to one catalog lookup per batch of events. This may seem a bit counterintuitive, but the large disjunction of expressions for batched updates caused a lot of false positives. This new approach has less of them, but on the other hand may cause duplicate results to be returned from the catalog. To offset this, the `lookup` operator now merges expressions into a disjunction when it notices repeat partitions being returned as candidates.
This also fixes an issue where a failed catalog lookup caused the `retro.queued_events` metric to miscount until after the node restarted.
- Fixes tenzir/issues#2055
- Fixes tenzir/issues#2056
=> Perform individual catalog lookups in `lookup`

changelog/next/bug-fixes/4554--launch-hotfix.md, nix/tenzir/plugins/source.json
This fixes a case with a missing test—calling `/pipeline/launch` for a pipeline that has no sink, and configuring the implicit sink to be just `serve` without `cache`.
=> Fix `/pipeline/launch` when no cache is provided

changelog/next/bug-fixes/4558--empty-record-schema.md, libtenzir/src/concept/parseable/tenzir/legacy_type.cpp, libtenzir/src/series_builder.cpp, plugins/fluent-bit/integration/tests/tests.bats, scripts/ocsf-schemas.py
This PR adds the OCSF schema definitions as built-in Tenzir schemas, which are auto-generated by a small script that fetches the latest OCSF schema from https://schema.ocsf.io. For some types (see the Python script for a complete list), we currently omit some fields because OCSF allows cyclic types. Furthermore, objects with unknown fields or with fields of unknown type are omitted right now. This can be improved in follow-up PRs.
Also, I added a small bug fix to this PR which allows schema definitions to contain empty record types.
=> Add OCSF schema type definitions

cmake/TenzirRegisterPlugin.cmake, libtenzir/include/tenzir/plugin.hpp
gcc-14 seems to not produce unique types for lambdas. This causes builtin plugins to not be registered, crashing the binary on startup.
=> Fix gcc-14 not deducing unique types for lamdbas

libtenzir/include/tenzir/configuration.hpp, libtenzir/src/configuration.cpp, libtenzir/src/plugin.cpp, tenzir/tenzir.cpp
We noticed that flamegraphs show a large amount of time on startup being spent in the function `tenzir::config_dirs(…)`. Apparently, the function was called $`N+1`$ times for $`N`$ plugins and builtins available. That's a bit unnecessary, so I shuffled the code around to only call the function exactly once.
Additionally, this cleans up some code that has been deprecated for over a year now.
=> Make `tenzir` and `tenzir-node` start faster

changelog/next/bug-fixes/4579-udp-reuseaddr.md, libtenzir/builtins/connectors/udp.cpp
This avoids failures when restarting pipelines.
=> Set `SO_REUSEADDR` in the UDP connector

libtenzir/src/tql2/eval_impl.cpp
This makes it so that `test = a.very.long.path.to[0].some.other[2].value` where `a == {}` no longer emits one warning for each field access and index expression that fails to evaluate after the initial missing field is found. Instead, only a single warning is produced:
~~~
warning: record does not have this field
--> <input>:1:25
|
1 | from {a: {}} | test = a.very.long.path.to[0].some.other[2].value
|                         ~~~~ 
|
~~~
Also, I added a small fix to the evaluator, where index expressions did not properly account for the nullability of both sides and field accesses did not propagate the nullability from the struct array to the field array.
=> Improve `null` handling of field access and index expressions

changelog/next/bug-fixes/4583--gapless-live-export.md, libtenzir/builtins/operators/export.cpp, libtenzir/include/tenzir/actors.hpp, libtenzir/include/tenzir/importer.hpp, libtenzir/src/importer.cpp, tenzir/integration/tests/vast_misc.bats
This removes the up to 30s delay between importing and exporting events. Most notably, this will make metrics and diagnostics in the Tenzir Platform appear instantly.
This is achieved by buffering up to 40s of events (or, to be more precise, `tenzir.active-partition-timeout + 10s`) in the importer, and forwarding that data for all new exports that subscribe to it. The exports then waits for the catalog lookup to return, and immediately returns all events that are newer than the newest event in any of the considered candidate partitions.
Practically, this removes the gap in `export --live --retro` (and `metrics` and `diagnostics` by extension). There still exists a theorical gap if the catalog needs more than 10s to ack a partition. But if that's the case we have a whole bunch of other …
=> Remove the delay between importing and exporting events

changelog/next/features/4594--buffer-bytes.md, libtenzir/builtins/operators/buffer.cpp, libtenzir/include/tenzir/chunk.hpp, libtenzir/include/tenzir/table_slice.hpp, libtenzir/src/chunk.cpp, libtenzir/src/execution_node.cpp, libtenzir/src/table_slice.cpp, web/docs/operators/buffer.md
This extends the `buffer` operator to support bytes as input in addition to the existing support for events. Note that the `drop` policy is not supported when using bytes as an input, as—unlike for events—dropping parts of a bytes stream can go horribly wrong.
- Fixes tenzir/issues#2153
=> Support bytes inputs in the `buffer` operator

changelog/next/bug-fixes/4597--node-connection-timeout.md, libtenzir/builtins/commands/rebuild.cpp, libtenzir/include/tenzir/node_control.hpp
This is not what the timeout was intended for, and if the node is under high load this can lead to timeout errors that are not handled at all, causing pipelines to fail.
=> Stop using connection timeout to get node components

changelog/next/features/4590--JSON-size-increase.md, libtenzir/builtins/formats/json.cpp
The `batch_size` parameter for `simdjson`s `iterate_many` is now dynamically increased if the parsing fails due to a capacity error.
This for example happens with https://ja4db.com/api/read/ (also requires `--arrays-of-objects`)
Fixes https://github.com/tenzir/issues/issues/845
=> Dynamically grow simdjson buffer if necessary

changelog/next/bug-fixes/4601--faster-arrays-of-objects.md, libtenzir/builtins/formats/json.cpp
Calling `doc_it.source()` resets simdjson's internal data structure, which made `--arrays-of-objects` perform worse the larger the array was.
=> Make `read json --arrays-of-objects` faster

libtenzir/builtins/operators/buffer.cpp, libtenzir/builtins/operators/cache.cpp, libtenzir/builtins/operators/every_cron.cpp, libtenzir/builtins/operators/from_load_read.cpp, libtenzir/builtins/operators/local_remote.cpp, libtenzir/builtins/operators/shell.cpp, libtenzir/builtins/operators/summarize.cpp, libtenzir/builtins/operators/unordered.cpp, libtenzir/include/tenzir/pipeline.hpp, libtenzir/src/execution_node.cpp
This replaces the `input_independent` property of operators with a smarter `idle_after` property, and makes use of it in the `read` operator to improve scheduling of the operator when is not yet finished but has no demand, and the `read` operators parser has events "stuck" in its generator's state, e.g., in a series builder's internal buffer.
=> Improve idle detection of operators

changelog/next/bug-fixes/4602--graceful-tcp-connection-errors.md, libtenzir/builtins/operators/tcp-listen.cpp
Pipelines starting with `from tcp` no longer go into the failed state when a single connection fails.
=> Keep from tcp pipelines running on connection failures

libtenzir/builtins/functions/community_id.cpp, libtenzir/include/tenzir/argument_parser2.hpp, libtenzir/src/argument_parser2.cpp, tenzir/integration/data/reference/functions/test_community-2d5fid/step_01.ref, tenzir/integration/data/reference/functions/test_community-2d5fid/step_02.ref, tenzir/integration/data/reference/functions/test_community-2d5fid/step_03.ref, tenzir/integration/tests/functions.bats
It is now possible to add named, required arguments to an `argument_parser2`:
```
auto s = std::string{};
parser.add( "name", s );
```
The argument parser will check ensure that all named required arguments were present and return a failure otherwise.
In the synopsis, named required arguments will be listed after the positional arguments, before non-required named arguments. Non-required named arguments now have a trailing `?` to signal that they are optional.
Fixes https://github.com/tenzir/issues/issues/2146
=> Add support for named required arguments to TQL2

nix/tenzir/plugins/source.json, web/docs/installation/install-a-package.md, web/docs/operators/package.md, web/docs/write-a-package.md
This adds two new, optional parameters to TQL2's `package_add`:
- A positional argument that may either be a package identifier or a path to a package, and
- a named argument `inputs` that is a record used for setting package inputs.
A few examples:
```
// tql2
package_add "slack", inputs={"webhook-url": "…"}
package_add "path/to/package.yaml", inputs={ … }
package_add "https://raw.githubusercontent.com/tenzir/library/main/feodo/package.yaml"
from … | package_add inputs={ … }
```
=> Add a simpler way to install packages

libtenzir/builtins/connectors/tcp.cpp, libtenzir/builtins/operators/load_tcp.cpp, libtenzir/builtins/operators/tcp-listen.cpp, libtenzir/include/tenzir/fwd.hpp, libtenzir/include/tenzir/try.hpp, libtenzir/src/argument_parser2.cpp, web/docs/operators/metrics.md
This is an all-new `load_tcp` for TQL2, and our first operator to support a fully nested pipeline.
The operator has the following synopsis:
```
load_tcp <url> { ... }?,
connect=<bool>?,
parallel=<uint64>?,
tls=<bool>?,
certfile=<string>?,
keyfile=<string>?
```
The nested pipeline runs once per connection, joining the output (either events or bytes) at the end of the `load_tcp` operator.
=> Implement `load_tcp` for TQL2

libtenzir/builtins/operators/to_hive.cpp, libtenzir/include/tenzir/detail/zip_iterator.hpp
Example:
```
to_hive "<uri>", 
partition_by=[year, month], 
format="json",
max_size=200M,  // default: 100M (bytes)
timeout=10min   // default: 5min
```
The `<uri>` can be some local path or a blob storage URI. Since this is a TQL2-only operator for now, there is no changelog.
=> Add `to_hive` operator for partitioned writes

libtenzir/builtins/functions/string.cpp, libtenzir/include/tenzir/argument_parser2.hpp, libtenzir/include/tenzir/tql2/entity_path.hpp, libtenzir/include/tenzir/tql2/plugin.hpp, libtenzir/include/tenzir/tql2/registry.hpp, libtenzir/src/plugin.cpp, libtenzir/src/tql2/exec.cpp, libtenzir/src/tql2/plugin.cpp, libtenzir/src/tql2/registry.cpp, libtenzir/src/tql2/resolve.cpp
Plus a few convenience changes and small fixes.
For example, this makes it possible to have both a `reverse` operator (operating on event streams) and a `reverse` function (operating on strings or lists).
=> Make it possible to give operators and functions the same name

nix/tenzir/plugins/source.json
This adds two new configuration options for Tenzir Nodes: `TENZIR_TOKEN` and `TENZIR_PLATFORM_CONTROL_ENDPOINT`.
The token supersedes the tenant id and api key in the existing platform configuration file. The platform control endpoint supersedes the control endpoint option in the existing platform configuration file, but is no longer required and defaults to `wss://ws.tenzir.app/production`.
The token's format is computed from the tenant id and the api key. Take for example a platform configuration file like this:
```
api-key: jjyKtVVv5XKZmTXS0luIfb3aqTSJELiMIHllI5h59f4
tenant-id: t-8w5man4n
control-endpoint: wss://ws.tenzir.app/production
```
Instead of needing to create this file, users can now simply set the following environment variable for the node:
```bash …
```
=> Introduce `TENZIR_TOKEN`

libtenzir/builtins/formats/json.cpp
Without this fix, trying to ingest gelf data from a file in a TQL2 pipeline would fail with the following error:
```
error: gelf parser: SCALAR_DOCUMENT_AS_VALUE: A JSON document made of a scalar (number, Boolean, null or string) is treated as a value. Use get_bool(), get_double(), etc. on the document instead. 
= note: skips invalid JSON '{"version":"1.1","timestamp":1.71146624E9,"host":"192.1 ... (truncated 1048522 bytes)
```
=> Split at null bytes in TQL2 gelf parser

libtenzir/builtins/formats/lines.cpp
Because options in TQL2's argument parser are just assignment expressions, we cannot use a constant on the left-hand side, and thus also not as an argument name.
I renamed the option to `split_at_null=bool` instead, which is a better name in any case.
- Fixes https://github.com/tenzir/issues/issues/2234
=> Rename `null=bool` option for TQL2's `read_lines`

libtenzir/include/tenzir/tql2/tokens.hpp, libtenzir/src/tql2/parser.cpp, libtenzir/src/tql2/tokens.cpp
Adds support for raw strings as `r"<text>"` and `r#"<text>"#`. Currently, variable number of `#`s is not supported.
- Closes https://github.com/tenzir/issues/issues/2185
=> Implement (single delimiter) raw strings for TQL2

changelog/next/changes/4636--lookup-prefer-recent.md, nix/tenzir/plugins/source.json
This changes the `lookup` operator to unconditionally prefer recent newer persisted events across context updates in favor of going by the order in which context updates arrive.
=> Prefer recent partitions for retro lookups

libtenzir/builtins/operators/load_tcp.cpp
Fixing an oversight from #4615.
=> Add a timestamp to the load_tcp metrics

.github/workflows/tenzir.yaml, Dockerfile, scripts/debian/build-arrow.sh, scripts/debian/install-aws-sdk.sh, scripts/debian/install-dev-dependencies.sh
The official Arrow packages for Debian do not include support for the Azure filesystem module. For this reason we now build a customized Arrow config as part of the dependency installation setup step, so the connector is available in the Docker images.
Note:
This now also builds arrow in the regular Debian CI, and that'll cause some noticeably longer CI runtimes. We may consider not building the `azure-blob-storage` plugin in that mode to reduce the impact on end-to-end runtimes.
=> Enable azure-blob-storage support in the Docker image

libtenzir/builtins/operators/head.cpp, libtenzir/builtins/operators/slice.cpp, libtenzir/builtins/operators/tail.cpp
Moves `head` and `tail` operators to slice.cpp removing the need for `pipeline::internal_parse_as_operator()`.
=> Move `head` and `tail` operators to slice.cpp

changelog/next/bug-fixes/4646--python-operator-fds.md, libtenzir/builtins/operators/python.cpp
In boost::process, a pipe's file descriptors are closed in its destructor.
When they were already closed, this results in a harmless "Bad file descriptor" result in the best case when attempting to close an already-closed fd.
In the worst case, the descriptor was already re-opened in the meantime and we close an unrelated file descriptor.
=> Fix double-closing fds in the python operator

changelog/next/features/4645.md, libtenzir/builtins/operators/sample.cpp, libtenzir/builtins/operators/slice.cpp, web/docs/operators/sample.md
Adds a `sample` operator for allowing [dynamic sampling](https://docs.cribl.io/edge/dynamic-sampling-function/).
- Closes https://github.com/tenzir/issues/issues/2246
=> Add `sample` operator

changelog/next/bug-fixes/4655--fix-lookup-metrics.md, libtenzir/include/tenzir/fwd.hpp, nix/tenzir/plugins/source.json
This fixes incorrectly repeated `context_updates` reported in `metrics lookup` when using the `lookup` operator with multiple fields.
- Fixes https://github.com/tenzir/issues/issues/2208
=> Fix incorrect context updates count in lookup metrics

libtenzir/CMakeLists.txt, nix/azure-sdk-for-cpp/default.nix, nix/overlay.nix, nix/tenzir/default.nix, plugins/azure-blob-storage/CMakeLists.txt, plugins/azure-blob-storage/include/saver.hpp, plugins/azure-blob-storage/src/plugin.cpp
This adds support for the `azure-blob-storage` operator to all packages built on the static binary build.
=> Enable azure-blob-storage in the DEB and RPM packages

libtenzir/builtins/operators/sample.cpp, web/docs/operators/sample.md
Fixes `--max-rate` and adds a new option `--max-samples` identical to the older behavior (which is much easier to grasp IMHO).
=> Add `--max-samples` option to `sample` and fix `--max-rate`

libtenzir/include/tenzir/diagnostics.hpp, libtenzir/include/tenzir/tql2/parser.hpp, libtenzir/include/tenzir/tql2/resolve.hpp, libtenzir/include/tenzir/tql2/tokens.hpp, libtenzir/src/tql2/exec.cpp, libtenzir/src/tql2/parser.cpp, libtenzir/src/tql2/resolve.cpp, libtenzir/src/tql2/tokens.cpp
This temporary solution makes it possible to parse an AST from a string, but without location information (= without good diagnostics). This is necessary because the diagnostic infrastructure doesn't support multiple source fragments for the same pipeline, and also because we need to parse a list of assignments as part of an upcoming context type. We should revisit this in the future when we built the necessary stuff to deal with this in a better way.
=> Add anonymous parsing functions

changelog/next/features/4668--actor-metrics.md, libtenzir/include/tenzir/detail/actor_metrics.hpp, libtenzir/include/tenzir/importer.hpp, libtenzir/src/detail/actor_metrics.cpp, libtenzir/src/importer.cpp, libtenzir/src/index.cpp, libtenzir/src/node.cpp, web/docs/operators/metrics.md
The actor metric is a low-level tool to measure the state of an actor over time. It is mostly targeted at component actors and the only measurement right now is the number of messages in the inbox.
=> Add metrics for select component actors

changelog/next/bug-fixes/4669--cleanup-python-venvs.md, libtenzir/builtins/operators/python.cpp, libtenzir/src/configuration.cpp, libtenzir/src/spawn_node.cpp, tenzir.yaml.example, tenzir/tenzir.cpp
When the node crashes or the the python operator encounters some other bugs, it can happen that the created virtualenv for that instance of the operator gets left behind on disk. Over time, this can accumulate, leading to a large amount of wasted disk space.
To counteract this, we remove all old virtualenvs from previous runs of a tenzir node on the same host whenever we start the node.
This does not solve the problem for virtualenvs created by tenzir client processes, however the intuition is that there the problem is much less severe, because these are created mostly manually and at a much lower frequency.
=> Clean up old venvs in the python operator

libtenzir/builtins/operators/sort.cpp, libtenzir/include/tenzir/concepts.hpp
This gets a basic version of `sort` for TQL2 off the ground. This still comes with a rather large TODO: we need to change comparisons between `data` and `data_view` to work across types, putting nulls last.
- Fixes https://github.com/tenzir/issues/issues/2136
=> Implement `sort` for TQL2

libtenzir/CMakeLists.txt, libtenzir/builtins/operators/to_hive.cpp
This is a leftover from Friday's demo preparations, in particular we wanted to implement a way to use urls like `s3://bucket/key?root_url=https://s3.local/` in combination with partitioning.
Adding a `boost::url` dependency for this seems like overkill, however Arrow's `util::Uri` class is read-only and doesn't allow modifying url components, and the platform plugin already depends on `boost::url` so hopefully this won't make a difference in any of our CI environments in practice.
Example (of the success case):
```
$ ./bin/tenzir --tql2 'version | to_hive "http://user:pass@tenzir.example.org:32/foo/#asdf?foo=bar", partition_by=[major], format="json"'
error: failed to upload chunk to http://user:pass@tenzir.example.org:32/foo/major=4/0.json#asdf?foo=bar
= note: !! unspecified: curl: …
```
=> Handle queries, fragments, etc. in the to_hive operator

libtenzir/src/evaluator.cpp, libtenzir/src/index.cpp, libtenzir/src/node.cpp, libtenzir/src/passive_partition.cpp, libtenzir/src/posix_filesystem.cpp, libtenzir/src/store.cpp, nix/tenzir/plugins/source.json
As a band-aid fix for the increasingly overwhelming log sizes of the node, I went through some of the most verbose log messages and made a judgement call on each whether to keep, demote or remove that log message.
=> Reduce log verbosity of the node

web/docs/tql2/operators.md, web/docs/tql2/operators/cache.md, web/docs/tql2/operators/rare.md, web/docs/tql2/operators/read_kv.md, web/docs/tql2/operators/top.md
Some docs were already there, but they were not shown on the overview page, and I also expanded them a bit (plus some small fixes in other docs).
To be merged after #4672.
=> Add docs for `top` and `rare`

libtenzir/src/multi_series_builder.cpp, libtenzir/src/multi_series_builder_argument_parser.cpp, libtenzir/test/multi_series_builder.cpp, web/docs/formats.md
Originally, we disallowed combining `--raw --merge --schema=schema` for technical reasons.
However, since then a refactor in the multi series builder actually made that easily possible, so we are now lifting that restriction.
The TQL2 docs already document the state after this PR.
=> Lift the restriction on combining `raw` and `merge` for parsers

libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/contexts/geoip.cpp, libtenzir/builtins/contexts/lookup_table.cpp, libtenzir/include/tenzir/detail/weak_handle.hpp, libtenzir/include/tenzir/plugin.hpp, nix/tenzir/plugins/source.json
This is a leftover from the "snapshot" feature of the `lookup` operator that was dead code now, so we were able to just remove it.
- Fixes https://github.com/tenzir/issues/issues/2251
=> Remove `context::make_query()`

libtenzir/include/tenzir/session.hpp, libtenzir/src/session.cpp, libtenzir/src/tql2/eval.cpp
Ran into this during development of "aggregation" contexts, and figured it'd make sense to just split this out to get it reviewed separately.
I've also used the opportunity to move a few things from header to source files.
=> Make it harder to create a dangling `session_provider`

libtenzir/src/tql2/ast.cpp
This makes the following way faster:
```
// tql2
metrics "operator"
where source or sink
```
=> Implement predicate pushdown for `where <pred>`

libtenzir/include/tenzir/tql2/ast.hpp, web/docs/tql2/language/expressions.md, web/docs/tql2/operators/assert.md, web/docs/tql2/operators/azure_log_analytics.md, web/docs/tql2/operators/save_google_cloud_pubsub.md
We made a call yesterday in the team between `@` and `meta.` as a prefix for metadata, and agreed to use `@`. So this adapts the remaining places in the docs accordingly.
=> Consistently refer to metadata with `@`

changelog/next/bug-fixes/4688--serve-error-return-instantly.md, libtenzir/builtins/operators/serve.cpp
Before this change, the `/serve` endpoint waited for its long-poll timeout to expire if the pipeline failed before the first request to `/serve` came in. Now it returns instantly. For the Tenzir Platform, this causes the loading button in the Explorer to disappear immediately for such cases.
Here's a simle reproduction that now returns instantly but took some time before:
```
// tql2
shell "echo null"
read_json
serve "foo"
```
```
// tql2
api "/serve", {
serve_id: "foo"
}
```
=> Return instantly in `/serve` if pipeline fails early

changelog/next/bug-fixes/4694--cache-writeable.md, libtenzir/src/configuration.cpp, tenzir.yaml.example, tenzir/tenzir.cpp
The `tenzir` binary creates intermediate directories for the cache directory as necessary. If these do not yet exist, they will be owned by the first user running the process. That can cause other users running the process later to fail, as they may not have permission to access the intermediate directories if the system is locked down enough. This change fixes this problem by simply removing the intermediate directories.
=> Ensure cache directory is writable for multiple users

changelog/next/bug-fixes/4689--null-comparision-ops.md, libtenzir/src/tql2/eval_binary.cpp
Implements: 
- `<bool> or <null>`
- `<null> or <null>`
- `<bool> and <null>`
- `<null> and <null>`
Closes https://github.com/tenzir/issues/issues/2168
=> Implement `and` and `or` for `null_type`

changelog/next/bug-fixes/4702--restart-buffer.md, libtenzir/builtins/operators/buffer.cpp, libtenzir/builtins/operators/tcp-listen.cpp, libtenzir/include/tenzir/actors.hpp, libtenzir/include/tenzir/execution_node.hpp, libtenzir/include/tenzir/operator_control_plane.hpp, libtenzir/include/tenzir/pipeline_executor.hpp, libtenzir/src/execution_node.cpp, libtenzir/src/node.cpp, libtenzir/src/pipeline.cpp, libtenzir/src/pipeline_executor.cpp
This fixes a rather annoying bug: it was not possible to instantiate the `buffer` operator a second time without parsing it again. This is due to how the operator, which physically consistents of two operators, exchanges information by (ab)using the actor registry as a communication channel. This broke when (1) restarting a pipeline with the oeprator through the Tenzir Platform, or (2) using the operator in a nested pipeline that gets instantiated multiple times, for example in `load_tcp` with at least two connections.
=> Allow reinstantiating the `buffer` operator

changelog/next/bug-fixes/4674--fix-load_tcp-connection-closing.md, libtenzir/builtins/operators/load_tcp.cpp
This came up while testing tcp connections. Sending many events over individual connections left lots of those connections in the `CLOSE_WAIT` state.
=> Explicitly close ending TCP connection sockets

changelog/next/bug-fixes/4701--mode.md, changelog/next/features/4701--value-counts.md, libtenzir/builtins/aggregation-functions/mode_value_counts.cpp, libtenzir/builtins/operators/version.cpp, web/docs/tql2/operators/summarize.md
This adds a `value_counts` aggregation function that returns an a list of values alongside their frequency.
Additionally, this fixes a bug in `mode` that caused it to only consider the first non-null value per batch.
=> Add a `value_counts` aggregation function

Dockerfile, changelog/next/bug-fixes/4690--google-cloud-pubsub-docker, plugins/fluent-bit/integration/tests/setup_suite.bash, plugins/google-cloud-pubsub/include/saver.hpp, plugins/parquet/integration/tests/setup_suite.bash, plugins/sqs/integration/tests/setup_suite.bash, plugins/web/integration/tests/setup_suite.bash, plugins/yara/integration/tests/setup_suite.bash, scripts/debian/install-google-cloud.sh
This PR builds the google_cloud_cpp dependency in the docker image, enabling the google-cloud-pubsub connector.
=> Enable google-cloud-pubsub connector in the Docker Image

changelog/next/bug-fixes/4709--summarize-no-groups.md, libtenzir/builtins/operators/summarize.cpp, tenzir/integration/data/reference/pipelines_local/test_summarize_an_empty_input/step_00.ref, tenzir/integration/tests/pipelines_local.bats
This makes TQL2's `summarize` work properly when there are no groups and no input by creating a new bucket and then immediately finishing it to return the aggregation function's default values as a single event. This makes `from [] | summarize count=count()` return the expected `{count: 0}` instead of nothing.
- Fixes https://github.com/tenzir/issues/issues/2289
=> Fix TQL2 `summarize` with no groups and no input

web/docs/tql2/operators/load_google_cloud_pubsub.md, web/docs/tql2/operators/save_google_cloud_pubsub.md, web/versioned_docs/version-v4.22/tql2/operators/load_google_cloud_pubsub.md, web/versioned_docs/version-v4.22/tql2/operators/save_google_cloud_pubsub.md
The TQL2 docs for `load_google_cloud_pubsub` and `save_google_cloud_pubsub` were written for positional arguments, but the operators in TQL2 have required, named arguments.
This also fixes the past versioned docs, since those were also wrong.
=> Fix the TQL2 for the google_cloud_pubsub operators

changelog/next/bug-fixes/4717--str-of-enumeration.md, libtenzir/builtins/functions/string.cpp
This makes `str(some_enum_value)` return the textual name of the entry instead of a string that contains just its numeric index. We might in general make enum usable where strings are usable in the future, but this is an obvious bug for which the fix should not be controversial.
=> Make `str(enum)` return the name of the enum entry

changelog/next/features/4720--load-balance.md, libtenzir/builtins/operators/load_balance.cpp, libtenzir/include/tenzir/detail/stable_map.hpp, libtenzir/src/argument_parser2.cpp, libtenzir/src/tql2/exec.cpp, web/docs/tql2/operators.md, web/docs/tql2/operators/load_balance.md
This PR adds a `load_balance` operator that can be used to distribute events over a set of nested pipelines:
```tql
let $cfg = [{
ip: 192.168.0.30,
token: "example-token-1234",
}, {
ip: 192.168.0.31,
token: "example-token-5678",
}]
subscribe "input"
load_balance $cfg {
let $endpoint = str($cfg.ip) + ":8080"
to_splunk $endpoint, hec_token=$cfg.token
}
```
=> Add `load_balance` operator 

tenzir/tenzir.cpp
We were trying to write to `TENZIR_ERROR()` before creating the logger context.
=> Move invalid use of logger in startup code

changelog/next/features/4730--universal-function-call-syntax.md, libtenzir/builtins/formats/cef.cpp, libtenzir/builtins/formats/grok.cpp, libtenzir/builtins/formats/json.cpp, libtenzir/builtins/formats/leef.cpp, libtenzir/builtins/functions/ip.cpp, libtenzir/builtins/functions/misc.cpp, libtenzir/builtins/functions/string.cpp, libtenzir/builtins/functions/time.cpp, libtenzir/builtins/operators/sort.cpp, libtenzir/builtins/operators/top_rare.cpp, libtenzir/include/tenzir/argument_parser2.hpp, libtenzir/include/tenzir/tql2/ast.hpp, libtenzir/include/tenzir/tql2/plugin.hpp, libtenzir/include/tenzir/tql2/registry.hpp, libtenzir/src/argument_parser2.cpp, libtenzir/src/tql2/parser.cpp, libtenzir/src/tql2/registry.cpp, libtenzir/src/tql2/resolve.cpp, tenzir/integration/data/reference/expression/test_universal_function_call_syntax/step_00.ref, tenzir/integration/data/reference/expression/test_universal_function_call_syntax/step_01.ref, tenzir/integration/data/reference/expression/test_universal_function_call_syntax/step_02.ref, tenzir/integration/data/reference/expression/test_universal_function_call_syntax/step_03.ref, tenzir/integration/data/reference/parser/test_functions/step_00.ref, tenzir/integration/data/reference/parser/test_ocsf_example/step_00.ref, tenzir/integration/tests/expression.bats, web/docs/tql2/functions.md
This makes `"abc".starts_with("ab")` equivalent to `starts_with("abc", "ab")` for every function. Thus, the distinction between functions and methods no longer exists.
=> Add universal function call syntax

web/blog/five-design-principles-for-building-a-data-pipeline-engine/index.md
This removes a dead link in an old blogpost.
=> Remove link to a removed docs page

libtenzir/builtins/aggregation-functions/all.cpp, libtenzir/builtins/aggregation-functions/any.cpp, libtenzir/builtins/aggregation-functions/collect.cpp, libtenzir/builtins/aggregation-functions/count_distinct.cpp, libtenzir/builtins/aggregation-functions/distinct.cpp, libtenzir/builtins/aggregation-functions/first_last.cpp, libtenzir/builtins/aggregation-functions/mean.cpp, libtenzir/builtins/aggregation-functions/min_max.cpp, libtenzir/builtins/aggregation-functions/mode_value_counts.cpp, libtenzir/builtins/aggregation-functions/stddev_variance.cpp, libtenzir/builtins/aggregation-functions/sum.cpp, libtenzir/builtins/functions/numeric.cpp, libtenzir/builtins/operators/summarize.cpp, libtenzir/fbs/aggregation.fbs, libtenzir/include/tenzir/tql2/plugin.hpp
This is in preparation for lookup-table contexts with explicitly specified fields via aggregation functions, which need to be able to roundtrip correctly.
I've split this out into a separate PR to make this easier to review; tests for this will arrive with the follow-up story that makes the changes to the contexts, as only then this newly added code will be reachable by users.
Note that `median` and `quantile` cannot be serialized and deserialized as of this PR, as they internally use Apache Arrow's TDigest implementation, which is unfortunately hidden via the pimpl idiom. We will need to change that in a follow-up PR to use another TDigest implementation that we can actually serialize.
=> Allow aggregation functions to be saved and restored

changelog/next/changes/4738--pub-sub-topics.md, nix/tenzir/plugins/source.json, web/docs/operators/publish.md, web/docs/operators/subscribe.md, web/docs/tql2/operators/publish.md, web/docs/tql2/operators/subscribe.md
We had this grand idea in the past when adding the `publish` and `subscribe` operators to make topics hierarchical. Because of that, we URL-encoded them, envisioning use of the forward slash as a separator. In practice, what we've ended up doing is really treating the topics as totally separate channels, and using schema names to form a hierarchy if we want one.
Unforutnately, the URL-encoding became user-visible with the introduction of the `publish` and `subscribe` metrics, which contained the URL-encoded topic in metrics. This was confusing not just for users, but also for ourselves in production setups we manage.
This change removes the URL-encoding entirely. It also changes the default topic to be `main`.
=> Stop URL-encoding pub/sub topics

changelog/next/bug-fixes/4749--separate-docker-volumes.md, docker-compose.yaml
relates to https://github.com/tenzir/issues/issues/2322
docker-compose volumes overlap which causes unintended side effects
Use separate volumes in docker-compose
=> Use separate volumes in docker-compose

changelog/next/bug-fixes/4742--cache-directory-wipe.md, libtenzir/src/spawn_node.cpp
On systems with strict access control, it can happen that the `tenzir-node` binary has permissions to write into the provided cache directory, but not to recreate the cache directory inside its parent folder.
So instead of removing the directory, we only wipe all contents of the directory on startup.
=> Only wipe the cache directory contents but not the dir itself

changelog/next/bug-fixes/4756--enumerate-prepend.md, libtenzir/builtins/operators/enumerate.cpp, libtenzir/include/tenzir/tql2/set.hpp, libtenzir/src/tql2/set.cpp
This causes `enumerate` to prepend the added field insread of appending it, which (1) restores the behavior from TQL1 and (2) is just generally nicer to use.
- Fixes https://github.com/tenzir/issues/issues/2269
=> Prepend the field added by `enumerate`

nix/tenzir/plugins/source.json
The operator took a named rather than a positional argument since the introduction of modules. This luckily hasn't landed in a release yet.
=> Fix `package::remove` in TQL2

libtenzir/src/version.cpp
This allows the platform to handle the renaming of the package-related operators more smoothly.
=> Add a feature flag for modules in TQL2

changelog/next/changes/4758--cache-timeout-options.md, libtenzir/builtins/operators/cache.cpp, nix/tenzir/plugins/source.json, web/docs/operators/cache.md, web/docs/tql2/operators/cache.md, web/openapi/openapi.yaml
This renames `ttl` to `read_timeout` and `max_ttl` to `write_timeout` for the `cache` operator. I stumbled over this while renaming the TTL options in a similar manner for the `lookup-table` context. The new names are more idiomatic and clearly express what the timeouts are doing.
=> Improve names for the `cache` operator's timeout options

changelog/next/bug-fixes/4761--fix-kafka-config-options.md, libtenzir/src/plugin.cpp, plugins/kafka/builtins/plugin.cpp, plugins/kafka/src/plugin.cpp
Internal option name mangling broke the config options for the `kafka` plugin. This patch reverses the implicit unflattening so `kafka` gets the options in the form it expects them.
=> Fix configuration options for the kafka plugin

libtenzir/builtins/operators/summarize.cpp, web/docs/tql2/operators/summarize.md
This makes the following pipeline 20x faster:
```
// tql2
load_http "https://storage.googleapis.com/tenzir-datasets/M57/suricata.json.zst"
decompress "zstd"
read_suricata
where @name == "suricata.flow"
summarize distinct(flow.state)
```
=> Make the `summarize` operator unordered

changelog/next/bug-fixes/4771--to-hive-local.md, libtenzir/builtins/operators/to_hive.cpp
The proposed documentation change from #4770 is a bug, not a feature—the operator had its location unset, which caused it to fall back to the previous operator's location.
=> Make `to_hive` a "local" operator

libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/contexts/lookup_table.cpp, libtenzir/include/tenzir/context.hpp, nix/tenzir/plugins/source.json
This adds a few more nice features to contexts in TQL2:
- The `value=<expr>` option for `context::update` allows for specifying arbitrary expressions to update the context with, enabling lookup tables holding values that are not records.
- The output field of `context::enrich` is now specified via `into=<field>`.
- The `format="plain|ocsf"` option toggles whether the `context::enrich` operator writes enrichments in the OCSF Enrichment object format.
- The `mode="set|append"` option toggles whether the `context::enrich` operator appends into a list instead of overwriting the field.
=> Add a few more niceties to TQL2 contexts

nix/tenzir/plugins/source.json
This adds the context name as the provider field for OCSF enrichments. This was already documented, but not implemented.
=> Add the `provider` field to `format="ocsf"` enrichments

changelog/next/bug-fixes/4785--where.md, libtenzir/builtins/operators/where.cpp
This fixes two bugs in the `where` operator when the evaluated predicate contained `null` values:
1. When the result only contained `true` and `null`, we incorrectly returned the entire input.
2. When the result contained `null` and at least one `false`, we ran into UB by incorrectly accessing the value of an `arrow::BooleanArray` for an invalid row.
Now, we correctly warn about `null` values in the result and drop all events for which the predicate evaluated to `null`.
=> Fix bugs in `where` when predicate evaluates to `null`

web/docs/tql2/operators.md, web/docs/tql2/operators/context/create_bloom_filter.md, web/docs/tql2/operators/context/create_geoip.md, web/docs/tql2/operators/context/create_lookup_table.md, web/docs/tql2/operators/context/enrich.md, web/docs/tql2/operators/context/inspect.md, web/docs/tql2/operators/context/load.md, web/docs/tql2/operators/context/remove.md, web/docs/tql2/operators/context/reset.md, web/docs/tql2/operators/context/save.md, web/docs/tql2/operators/context/update.md, web/docs/tql2/operators/measure.md, web/docs/tql2/operators/top.md
Adds two missing quotes and shortens some content to make it not line-break (when viewed on a MacBook Pro).
=> Small docs fixes

libtenzir/builtins/operators/put_extend_replace_set.cpp, libtenzir/builtins/operators/sort.cpp, libtenzir/builtins/operators/summarize.cpp, libtenzir/include/tenzir/concept/convertible/data.hpp, libtenzir/include/tenzir/concept/parseable/core/optional.hpp, libtenzir/include/tenzir/concept/parseable/tenzir/pipeline.hpp, libtenzir/include/tenzir/concept/parseable/tenzir/schema.hpp, libtenzir/include/tenzir/detail/legacy_deserialize.hpp, libtenzir/include/tenzir/detail/logger_formatters.hpp, libtenzir/include/tenzir/detail/type_traits.hpp, libtenzir/include/tenzir/legacy_type.hpp, libtenzir/include/tenzir/optional.hpp, libtenzir/include/tenzir/view.hpp, libtenzir/src/concept/parseable/tenzir/expression.cpp, libtenzir/src/concept/parseable/tenzir/legacy_type.cpp, libtenzir/src/legacy_type.cpp, libtenzir/test/convertible.cpp, libtenzir/test/detail/legacy_deserialize.cpp, libtenzir/test/printable.cpp
This replaces every usage of `caf::optional` with `std::optional`
- Fixes https://github.com/tenzir/issues/issues/2334
=> Replace `caf::optional` with `std::optional`

nix/tenzir/default.nix
They were dropped from being included in the static binary during some refactorings.
=> Restore the s3 and from_velociraptor plugins

changelog/next/features/4792--append-prepend-concatenate.md, libtenzir/builtins/functions/list.cpp, web/docs/tql2/functions.md, web/docs/tql2/functions/append.md, web/docs/tql2/functions/concatenate.md, web/docs/tql2/functions/prepend.md
These are functionally equivalent to `[...lhs, rhs]`, `[rhs, ...lhs]`, and `[...lhs, ...rhs]`, respectively, and simply implemented as an AST transformation.
- Fixes https://github.com/tenzir/issues/issues/2184
=> Implement `append`, `prepend`, and `concatenate`

changelog/next/bug-fixes/4801--ndjson-parser-failure.md, libtenzir/builtins/formats/json.cpp
The NDJSON tries to continue with parsing the line after an error occurs. The current approach does not really work reliably though, see https://github.com/tenzir/issues/issues/2355. Thus this PR disables that logic, at least for now.
=> Ignore whole line when NDJSON parser fails

changelog/next/bug-fixes/4809--str-function-quotes.md, libtenzir/builtins/functions/string.cpp
Due to a bad function overload, the `str` function previously added extra quotes to strings: `str("") == "\"\""`. This bug fix makes it return the original input as-is instead.
=> Fix `str` function quotes

libtenzir/builtins/operators/compress_decompress.cpp
The original code did `.emplace` on the variant, which invalidates the buffer. Also, I replaced a bunch of calls to `narrow_cast` with `narrow`, although that doesn't really matter here.
=> Fix potential lifetime issue in `compress` and `decompress`

libtenzir/builtins/aggregation-functions/count_distinct.cpp, libtenzir/builtins/aggregation-functions/distinct.cpp
This was accidentally changed to a named argument in https://github.com/tenzir/tenzir/pull/4740. 
No changelog necessary because there wasn't a release in between.
=> Make the argument of `distinct` and `count_distinct` positional again

changelog/next/bug-fixes/4816--sockets.md, libtenzir/include/tenzir/os.hpp, libtenzir/src/os.cpp
`tenzir::socket` was defined in `socket.hpp` and `os.hpp` with different definitions. This resulted in a crash in the `sockets` operator which used the `os.hpp` `tenzir::socket` 
- Closes https://github.com/tenzir/issues/issues/2262
=> Fix ODR violation of `tenzir::socket` type

libtenzir/builtins/contexts/lookup_table.cpp, libtenzir/include/tenzir/argument_parser2.hpp, libtenzir/include/tenzir/bitmap.hpp, libtenzir/include/tenzir/concept/printable/tenzir/json.hpp, libtenzir/include/tenzir/concept/support/detail/variant.hpp, libtenzir/include/tenzir/data.hpp, libtenzir/include/tenzir/data_builder.hpp, libtenzir/include/tenzir/detail/legacy_deserialize.hpp, libtenzir/include/tenzir/detail/type_list.hpp, libtenzir/include/tenzir/detail/type_traits.hpp, libtenzir/include/tenzir/expression.hpp, libtenzir/include/tenzir/legacy_type.hpp, libtenzir/include/tenzir/series_builder.hpp, libtenzir/include/tenzir/table_slice_builder.hpp, libtenzir/include/tenzir/tql2/ast.hpp, libtenzir/include/tenzir/tql2/eval_impl.hpp, libtenzir/include/tenzir/type.hpp, libtenzir/include/tenzir/variant.hpp, libtenzir/src/configuration.cpp, libtenzir/src/data_builder.cpp, libtenzir/src/legacy_type.cpp, libtenzir/src/series_builder.cpp, libtenzir/src/table_slice_builder.cpp, libtenzir/src/tql2/ast.cpp, libtenzir/src/type.cpp, libtenzir/test/data_builder.cpp
These have been removed in the CAF 1.0 release. Some of them weren't used, the rest is copied over.
=> Copy some metafunctions from `caf::detail::type_list`

libtenzir/builtins/connectors/directory.cpp, libtenzir/builtins/connectors/file.cpp, libtenzir/builtins/contexts/geoip.cpp, libtenzir/builtins/operators/python.cpp, libtenzir/builtins/operators/shell.cpp, libtenzir/include/tenzir/detail/logger.hpp, libtenzir/include/tenzir/detail/scope_guard.hpp, libtenzir/include/tenzir/logger.hpp, libtenzir/include/tenzir/tql2/registry.hpp, libtenzir/src/detail/subnet_tree.cpp, libtenzir/src/disk_monitor.cpp, libtenzir/src/execution_node.cpp, libtenzir/src/logger.cpp, libtenzir/src/systemd.cpp, libtenzir/src/tql/parser.cpp, libtenzir/src/transfer.cpp, libtenzir/src/wah_bitmap.cpp, libtenzir_test/src/main.cpp, nix/tenzir/plugins/source.json, plugins/azure-blob-storage/include/saver.hpp, plugins/gcs/src/plugin.cpp, plugins/kafka/include/kafka/operator.hpp, plugins/s3/include/operator.hpp, tenzir/tenzir.cpp
The new implementation in CAF 1.0 does not implement the rule of 5 and is therefore not moveable. We do need that for our logger scope tho.
=> Migrate to tenzir::scope_guard

changelog/next/features/4821--aggregating-lists.md, libtenzir/builtins/aggregation-functions/all.cpp, libtenzir/builtins/aggregation-functions/any.cpp, libtenzir/builtins/aggregation-functions/collect.cpp, libtenzir/builtins/aggregation-functions/count_distinct.cpp, libtenzir/builtins/aggregation-functions/distinct.cpp, libtenzir/builtins/aggregation-functions/first_last.cpp, libtenzir/builtins/aggregation-functions/mean.cpp, libtenzir/builtins/aggregation-functions/min_max.cpp, libtenzir/builtins/aggregation-functions/mode_value_counts.cpp, libtenzir/builtins/aggregation-functions/stddev_variance.cpp, libtenzir/builtins/aggregation-functions/sum.cpp, libtenzir/builtins/functions/numeric.cpp, libtenzir/builtins/operators/top_rare.cpp, libtenzir/include/tenzir/tql2/plugin.hpp, libtenzir/src/tql2/plugin.cpp
This enables `[1, 2, 3].sum()` and all the other combinations you can think of. This was already documented, but not implemented.
The current implementation is done by mapping the list array's value array onto a table slice with a single field called `x`, and swapping the first argument of the aggregation function call with a root field called `x`. That's a bit hacky, but the alternative would've required changing the interface of aggregation functions not to evaluate their arguments on table slices directly anymore. Note that this effectively adds the restriction that the first argument of an aggregation function must be the aggregation function's subject, which holds true for all aggregation functions we currently have.
=> Allow aggregation functions to be called on lists

libtenzir/builtins/components/metrics_collector.cpp, libtenzir/builtins/contexts/bloom_filter.cpp, libtenzir/builtins/operators/api.cpp, libtenzir/builtins/operators/deduplicate.cpp, libtenzir/builtins/operators/shell.cpp, libtenzir/include/tenzir/error.hpp, libtenzir/src/error.cpp, libtenzir/src/execution_node.cpp, libtenzir/src/index.cpp, libtenzir/src/pipeline_executor.cpp, nix/tenzir/plugins/source.json
Our old CAF fork carries a patch to make `add_context` possible. We can now achieve the same result by using the diagnostics API, so we don't have to maintain a fork any more.
=> Replace add_context with diagnostic::error

changelog/next/features/4815--hex.md, libtenzir/builtins/functions/hex.cpp, tenzir/integration/data/reference/functions/test_hex/step_00.ref, tenzir/integration/data/reference/functions/test_hex/step_01.ref, tenzir/integration/tests/functions.bats, web/docs/tql2/functions/decode_hex.md, web/docs/tql2/functions/encode_hex.md
Implements: 
- `encode_hex(blob|string) -> string`
- `decode_hex(blob|string) -> blob`
Closes https://github.com/tenzir/issues/issues/2364
=> Implement `encode_hex()` and `decode_hex()`

changelog/next/bug-fixes/4825--fix-misnamed-option.md, changelog/next/changes/4825--splunk-tls.md, changelog/next/features/4825--splunk-tls.md, nix/tenzir/plugins/source.json, web/docs/tql2/operators/to_splunk.md
Adds options for `to_splunk` to specify CA Certificates, Client Certificate and Keyfile for the certificate.
Additionally tries to default to `https` in some cases where the URL doesn't have a scheme.
Unfortunately, this doesn't work for common cases such as `localhost:8088` or `127.0.0.1:8088`.
- Closes https://github.com/tenzir/issues/issues/2372
=>  Improve `to_splunk` TLS functionality

changelog/next/features/4828--subnet-network.md, libtenzir/builtins/functions/misc.cpp, nix/tenzir/plugins/source.json, web/docs/tql2/functions.md, web/docs/tql2/functions/network.md
This fixes a crash for enrichments of mixed types.
=> Fix crash in `context::enrich` for heterogeneous enrichments

changelog/next/bug-fixes/4829--multiline-syslog.md, libtenzir/builtins/connectors/udp.cpp, libtenzir/builtins/formats/syslog.cpp
This adds a timeout to the multiline syslog in order to not hold back the last event until the next one shows up.
There also is a fix to `load_udp` , that wasnt live yet.
- Fixes https://github.com/tenzir/issues/issues/2379
=> Add timeout to multiline syslog

changelog/next/changes/4834--kafka-topic.md, changelog/next/changes/4834--str-string.md, libtenzir/builtins/functions/string.cpp, libtenzir/src/argument_parser2.cpp, plugins/kafka/include/kafka/operator.hpp, plugins/kafka/src/plugin.cpp, tenzir/integration/data/reference/expression/test_universal_function_call_syntax/step_02.ref, tenzir/integration/data/reference/expression/test_universal_function_call_syntax/step_03.ref, tenzir/integration/data/reference/functions/test_community-2d5fid/step_01.ref, tenzir/integration/data/reference/functions/test_community-2d5fid/step_02.ref, tenzir/integration/data/reference/functions/test_community-2d5fid/step_03.ref, web/docs/tql2/functions.md, web/docs/tql2/functions/float.md, web/docs/tql2/functions/int.md, web/docs/tql2/functions/ip.md, web/docs/tql2/functions/string.md, web/docs/tql2/functions/time.md, web/docs/tql2/functions/uint.md, web/docs/tql2/functions/where.md, web/docs/tql2/operators/load_kafka.md, web/docs/tql2/operators/save_kafka.md
- Rename `str` to `string` and provide `str` as a deprecated fallback
- Improvements for where function docs: Use "keep" instead of remove, rename example to not use negation
- Missing `encode_hex` and `decode_hex` in function overview
- Change `{load,save}_kafka` topic argument to be positional and required
- Remove default of topic `tenzir` from TQL2 kafka operators
- Fix argument parser docs links for functions and things in packages
=> Prepare small fixes for release

web/docusaurus.config.js, web/package.json, web/registerCopyButton.js, web/src/css/custom.scss, web/yarn.lock
Once again, there were quite a few hoops to pass through.
With the `jsx: true` option in the transformer, it disables the onclick handler on the transformer, which we manually add later on each page that contains the correct class name. See the implementation of the `registerCopyButton` function to understand what's going on here.
I expected docusaurus component swizzling to work, but adding the registerCopyButton as a hook (as the `@rehype-pretty/transformers` library suggests) to /theme/Root.tsx or /theme/Layout/index.tsx didn't do the job.
Note: The style of the copy-button is different for named codeblocks, and I couldn't find any easy way to match the styles completely (even though https://github.com/rehype-pretty/rehype-pretty-code/blob/eee1b216347fe4c1181ddf80bfa6a6a8e427ffdd/packag …
=> Add copy button to named language code blocks

changelog/next/bug-fixes/4846--startup-index-crash.md, libtenzir/src/index.cpp
On startup, the node actor starts its core components in order of how they depend on another. However, with the addition of the `tenzir.ingest` metrics, which are measured in the index component, we introduced a circular dependency between the importer and index components.
This change fixes a rare crash when the importer was started after the index tried emitting its first metrics. We observed this a few times in CI, and I have never heard of this happening in production.
Previously discussed here:
- https://github.com/tenzir/tenzir/pull/4845#issuecomment-2525575046
=> Fix a rare crash in the index actor on startup

changelog/next/4856--flatbuffer-file-size.md, changelog/next/bug-fixes/4856--flatbuffer-file-size.md, libtenzir/builtins/contexts/geoip.cpp, libtenzir/src/fbs/flatbuffer_container.cpp, libtenzir/src/index.cpp, libtenzir/src/passive_partition.cpp, libtenzir/src/posix_filesystem.cpp, libtenzir/src/sketch/bloom_filter.cpp, libtenzir/src/table_slice.cpp, libtenzir/src/type.cpp, nix/tenzir/plugins/source.json
In #4778 we changes the behavior of `chunk::map()` to return
a true-ish empty chunk instead of an error.
This revealed a lot of bugs in many call sites of `chunk::mmap()`,
where we didn't correctly check that the mapped file was bigger
than the minimum expected file size.
=> Check mmapped chunks for required minimum size

changelog/next/bug-fixes/4861--fix-export-where.md, libtenzir/src/tql2/ast.cpp
This fixes a panic when performing predicate pushdown for pipelines such as `export | where "foo" == "bar"`. The issue is that `"foo" == "bar"` is valid expression, but we perform a translation into a format that the catalog understands, which doesn't support expressions like that. Thus, this PR adds a check that validates the expression before returning it.
=> Validate legacy expressions when splitting for predicate pushdown

libtenzir/src/argument_parser2.cpp
Previously, things like `load_file follow=true` would be accepted by the argument parser because it skipped required positional arguments when it encountered a named argument.
=> Fix required positional argument skipping

changelog/next/features/4811--http-args.md, libtenzir/builtins/connectors/curl.cpp, tenzir/integration/data/reference/http2/test_load_http_post/step_00.ref, tenzir/integration/data/reference/http2/test_load_http_post_form/step_00.ref, tenzir/integration/data/reference/http2/test_save_http_post/step_00.ref, tenzir/integration/data/reference/http2/test_save_http_post_add_header/step_00.ref, tenzir/integration/data/reference/http2/test_save_http_post_delete_header/step_00.ref, tenzir/integration/data/reference/http2/test_save_http_post_overwrite_header/step_00.ref, tenzir/integration/data/reference/http2/test_save_http_put/step_00.ref, tenzir/integration/tests/http2.bats, web/docs/tql2/operators/load_http.md, web/docs/tql2/operators/save_http.md, web/docs/usage/enrich-with-threat-intel/README.md
This PR adds re-exposes existing HTTP functionality for TQL2.
How are we inferring the default protocol? In the past, we had this:
```
args.transfer_opts.default_protocol = protocol();
```
For HTTP, this should be either `http` or `https`. We only need this when there is no URL scheme given.
I would be inclined to go with HTTPs by default for security reasons.
=> Enhance HTTP connector controls

libtenzir/builtins/connectors/curl.cpp
The operators use blocking API calls, so on a system with little parallelism they were able to get the node to a halt.
=> Mark `{load,save}_http` as detached

.github/workflows/nix-config-base.json
To be reverted once the runner is back up.
=> Disable macOS Nix CI job

changelog/next/changes/4876--new-compression.md, libtenzir/builtins/operators/compress_decompress.cpp, libtenzir/builtins/operators/from_to_2.cpp, libtenzir/include/tenzir/tql2/plugin.hpp, libtenzir/src/plugin.cpp, tenzir/integration/data/reference/from_to/test_from_deduction/step_02.ref, tenzir/integration/data/reference/from_to/test_from_deduction/step_03.ref, tenzir/integration/data/reference/from_to/test_from_deduction/step_04.ref, tenzir/integration/data/reference/from_to/test_from_deduction/step_05.ref, tenzir/integration/data/reference/from_to/test_from_failure/step_01.ref, tenzir/integration/data/reference/from_to/test_to_deduction/step_02.ref, tenzir/integration/data/reference/from_to/test_to_deduction/step_03.ref, tenzir/integration/data/reference/from_to/test_to_deduction/step_04.ref, tenzir/integration/data/reference/from_to/test_to_deduction/step_05.ref, tenzir/integration/data/reference/from_to/test_to_failure/step_01.ref, tenzir/integration/data/reference/pipelines_local/test_legacy_operator/step_02.ref, web/docs/tql2/operators.md, web/docs/tql2/operators/compress.md, web/docs/tql2/operators/compress_brotli.md, web/docs/tql2/operators/compress_bz2.md, web/docs/tql2/operators/compress_gzip.md, web/docs/tql2/operators/compress_lz4.md, web/docs/tql2/operators/compress_zstd.md, web/docs/tql2/operators/decompress.md, web/docs/tql2/operators/decompress_brotli.md, web/docs/tql2/operators/decompress_bz2.md, web/docs/tql2/operators/decompress_gzip.md, web/docs/tql2/operators/decompress_lz4.md, web/docs/tql2/operators/decompress_zstd.md
This PR deprecates `compress` and `decompress` in favor of separate operators, exposing more options for Brotli and Gzip.
- Fixes: https://github.com/tenzir/issues/issues/2412
=> Split `compress`/`decompress` into separate operators

changelog/next/features/4884--tql2-udos.md, libtenzir/include/tenzir/tql2/entity_path.hpp, libtenzir/include/tenzir/tql2/registry.hpp, libtenzir/src/tql2/registry.cpp, libtenzir/src/tql2/resolve.cpp, tenzir/integration/data/reference/user_defined_operators/test_shadowing_udo/step_00.ref, tenzir/integration/data/reference/user_defined_operators/test_unknown_udo/step_00.ref, tenzir/integration/data/reference/user_defined_operators/test_valid_udo/step_00.ref, tenzir/integration/tests/user_defined_operators.bats, tenzir/tenzir.cpp, web/docs/integrations/zeek/README.md
With this PR, user-defined operators can be written and used in TQL2. To use TQL2, start your definition with the comment `// tql2`, or use the `--tql2` flag to opt into TQL2 as the default.
=> Add user-defined operators to TQL2

libtenzir/builtins/aggregation-functions/all.cpp, libtenzir/builtins/aggregation-functions/any.cpp
This led to a very curious "expected `bool`, got `bool`" warning and returned nulls. This appears to have been introduced with our new variant traits, which behave a bit different from CAF's sum type access that we used before.
No changelog entry necessary, as we didn't release this yet. However, we should very carefully check whether there are other places affected by this that aren't covered by tests.
=> Fix overeager fallback in `any` and `all`

python/pyproject.toml, version.json
This commit was created with `/scripts/prepare-release`.
* Updated `/version.json` to `v4.25.1`.
* Moved all changelog entries from `/changelog/next` to `/changelog/v4.25.1`.
* Updated the python bindings version in `/python/pyproject.toml` to `v4.25.1`.
=> Prepare repository for Tenzir v4.25.1

plugins/zmq/CMakeLists.txt
Prior to this change it was possible to not find the `cppzmq` dependency and run into a compilation error because `#include <zmq.hpp>` doesn't exist (which `cppzmq` provides).
=> Make finding cppzmq required

python/uv-source-info.json
This chagne was created automatically by running:
```bash
./python/update-uv-sources.sh
```
=> Update uv from 0.3.0 to 0.5.21

libtenzir/src/tql2/exec.cpp
The `let` resolver returns `failure_or<void>`. If it returns a failure, all subsequent compilation steps are not attempted. If we cannot evaluate an expression on the right side of `let`, we previously emitted an error, but did not return a failure, which meant that the rest of the compilation was performed. However, this produces confusing diagnostics due to unresolved `$` variables. This PR makes it so that we return a failure such that the compilation process is aborted after `let` resolving.
=> Ensure that `let` resolving phase fails when `let` expression errors

CMakeLists.txt, cmake/TenzirRegisterPlugin.cmake
This change makes the path shown in our assertions deterministic, hiding information about the environment that the build was compiled in.
=> Hide build directory paths in source location

nix/tenzir/check.nix, nix/tenzir/default.nix
A few minor cleanups.
The removal of the thinLTO compile cache might actually reduce the memory pressure and speed up builds on systems that used it before.
=> Follow ups for #4931

web/docs/tql2/operators/pipeline/list.md
These were incorrectly showing `package::list` in a few places.
=> Fix `pipeline::list` docs

changelog/next/features/4918--platform-tls-options.md, nix/tenzir/plugins/source.json, web/docs/installation/deploy-the-platform.md
In order to enable the node to work with platform instances using self-signed certificates, this PR adds two options
```
TENZIR_PLUGINS__PLATFORM__SKIP_PEER_VERIFICATION=true/false
TENZIR_PLUGINS__PLATFORM__CACERT=/path/to/ca.cert
```
in order to skip certificate verification (for true self-signed certificates) or to use a custom CA certificate as trust anchor (for internal certificate authorities or self-signed certificates generated with `trustme`)
=> Add plugin options to enable self-signed platform certificates

changelog/next/features/4949--retention-policy.md, libtenzir/include/tenzir/diagnostics.hpp, libtenzir/include/tenzir/importer.hpp, libtenzir/include/tenzir/retention_policy.hpp, libtenzir/include/tenzir/try.hpp, libtenzir/src/catalog.cpp, libtenzir/src/importer.cpp, nix/tenzir/plugins/source.json, tenzir.yaml.example, tenzir/tenzir.cpp, web/docs/tql2/operators/diagnostics.md, web/docs/tql2/operators/metrics.md
This adds two new configuration options `tenzir.retention.metrics` and `tenzir.retention.diagnostics`, which control how Tenzir stores metrics and diagnostics, respectively.
The options are checked in two places:
- The compactor maps them to time-based compaction rules.
- The importer does not forward metrics or diagnostics for which the retention policy is set to zero seconds.
=> Add `tenzir.retention` configuration

libtenzir/include/tenzir/actors.hpp, libtenzir/src/execution_node.cpp, web/docs/tql2/operators/cron.md
This rewrites `exec_node_actor` to use a traits class for its signature and the new class-based actor setup over the previous function-based setup. This makes no functional difference, but much improves the developer experience by shortening stacktraces by around 90%.
To test this, I've modified the `discard` operator to intentionally run into an assertion locally. On the current `main` branch, I get the following stacktrace:
<details>
<summary>Click to expand</summary>
```
0x4c6e800107148ca8: (tenzir::detail::panic_impl(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, std::__1::source_location)+0x28)
0x2148000107149030: (tenzir::detail::fail_assertion_impl(char const*, std::__1::basic_string_view<char, std::__1::char_traits<char>>, …
```
=> Use actor traits for `exec_node_actor`

changelog/next/changes/4954--deprecate-tql1.md, libtenzir/builtins/commands/exec.cpp, libtenzir/include/tenzir/exec_pipeline.hpp, libtenzir/src/exec_pipeline.cpp, nix/tenzir/plugins/source.json, tenzir/bats/data/reference/vast_server/test_yaml/step_01.ref, tenzir/bats/lib/bats-tenzir/load.bash, tenzir/bats/tests/version.bats, web/docs/tql2/operators/legacy.md
This deprecates TQL1, causing all TQL1 pipelines to emit a warning on startup that instructs the user to update to TQL2.
The warning can intentionally not be disabled. We want this to be a bit on the annoying side.
- Fixes https://github.com/tenzir/issues/issues/2329
=> Deprecate TQL1

.github/workflows/nix.yaml
This feature relies on an undocumented GitHub API that will stop working on Feburary 1st.
https://determinate.systems/posts/magic-nix-cache-free-tier-eol/
=> Remove Magic Nix Cache

changelog/next/changes/4966--metrics-no-more-hidden.md, nix/tenzir/plugins/source.json
We collect way too many operator metrics. This helps cut down the noise by no longer collecting metrics for hidden pipelines.
=> Stop collecting metrics for hidden pipelines

docker-compose.yaml, env.example
This changes the developer-facing Docker Compose setup to make use of `TENZIR_TOKEN` instead of the old variables.
Additionally, this makes `TENZIR_VERSION=v4.27 docker compose up` a shorter way of writing `TENZIR_IMAGE=ghcr.io/tenzir/tenzir:v4.27 docker compose up` , which saves a bit of time when testing with different versions locally as a developer.
=> Adjust developer-facing Docker setup to `TENZIR_TOKEN`

web/docusaurus.config.js, web/package.json, web/yarn.lock
Since VSCode marketplace doesn't allow namespaced packages like @tenzir/vscode-tql, we published the vscode-tql package without the namespace on npm.
Closes https://github.com/tenzir/issues/issues/2785.
=> Bump vscode-tql package for the docs site

changelog/next/features/4983--opensearch-fixup.md, libtenzir/builtins/operators/to_opensearch.cpp, nix/tenzir/plugins/source.json, web/docs/tql2/operators/to_opensearch.md, web/docs/tql2/operators/to_splunk.md
This adds an explicit `tls` option to `to_opensearch` allowing its usage with TLS in the generic `to`. For consistency, those arguments are also added to `to_splunk`.
Additionally, it fixes a few small, but not user-exposed bugs in `to_opensearch`.
- Fixes https://github.com/tenzir/issues/issues/2818
=> Add explicit `tls` options to `to_opensearch` and `to_splunk`

.github/workflows/tenzir.yaml, changelog/next/bug-fixes/4984-serve-hang.md, changelog/next/changes/4984--cache-overuse.md, libtenzir/builtins/operators/cache.cpp, libtenzir/builtins/operators/serve.cpp, tenzir.yaml.example, web/docs/tql2/operators/cache.md, web/openapi/openapi.yaml
We're currently implementing a feature for the Tenzir Platform that heavily relies on caching in nodes. For that, we've made three changes to the `cache` operator:
1. Unless specified explicitly, caches have no more default capacity in terms of event.
2. Instead of (1), we now track the global cache capacity in number of bytes. This is limited to 1GiB by default, and can be configured with the `tenzir.cache.capacity` option. For practical reasons, we require at least 64MiB of caches.
3. The default `wrtie_timeout` of caches increased from 1 minute to 10 minutes, and can now be configured with the `tenzir.cache.lifetime` option.
Additionally, and this is tacked onto this PR for easier testing with the Tenzir Platform, this makes two changes to `/serve`:
1. We've added an additional field …
=> Evict old caches when exceeding capacity limits

python/pyproject.toml, version.json
NOTE: merging this into #4987 to save one CI cycle and get the patch release out a bit quicker.
=> Prepare repository for Tenzir v4.28.1

.github/workflows/tenzir.yaml, nix/tenzir/plugins/source.json, python/pyproject.toml, version.json
The recent performance improvements caused a test to fail that was unfortunately timing-dependent because the pipeline it tested got faster. This has caused the release artifact uploads for v4.28 to fail, too.
=> Make pipeline manager tests more reliable

libtenzir/builtins/operators/cache.cpp
This is a follow-up to the last remaining TODO from my recent changes to `cache`, where I couldn't do this yet because the new `table_slice::approx_bytes` function was not yet merged into main and not easily cherry-pickable.
=> Make `cache` faster by re-using cached approx bytes

CMakeLists.txt, cmake/TenzirProvideFindModule.cmake, cmake/TenzirRegisterPlugin.cmake, flake.nix, libtenzir/CMakeLists.txt, libtenzir/src/detail/installdirs_relocatable.cpp.in, nix/tenzir/default.nix, nix/tenzir/plugins/default.nix, nix/tenzir/plugins/generic.nix, tenzir/CMakeLists.txt
This change makes it possible to install library archives into a different path than shared libraries. We then make use of it in the non-static Nix build which shaves off ~500 MB of the runtime closure.
=> Slim down the regular nix-built docker image

libtenzir/builtins/operators/serve.cpp, nix/tenzir/plugins/source.json
This fixes a regression introduced in a recent change I made that removed usage of the node actor's message handler to retrieve component handles in favor of using the regisrty where possible.
It turns out that we still have the possibility to spawn the REST API externally via `tenzir-ctl web server`, which under-the-hood spawns `rest_handler_actor` instances in a client process. After my recent change this now ran into an assertion failure, as I had naïvely assumed that the REST handlers were singletons in the node.
This change now reverts the recent changes for the two affected actors. A proper fix would be to change the actors to run inside the node, but as we do not support building the `web` plugin locally on macOS I am likely not the right person to be making that change.
To test …
=> Fix out-of-process REST APIs

docker-compose.yaml
We have `docker compose run tenzir` to interact with the Tenzir Node from within the Docker network already, so there's no reason to expose the port to the outside world.
This makes to easier to run `docker compose up` multiple times on the same host.
In addition, this makes the REST API opt-in via `docker compose run tenzir-api`. This does need to expose the port to the outside world, and there was little reason to always enable it as it is rarely used.
No changelog entry as this is a developer-facing change only.
=> Do not expose the CAF port in Docker Compose setup

libtenzir/builtins/connectors/tcp.cpp
This is motivated by a recent bug-hunting session, where we had to invest a bit of time into figuring out which of the various configured pipelines was failing with a connection error.
=> Improve diagnostics for connection failures in tcp operator

changelog/next/bug-fixes/5007--color-auto.md, libtenzir/builtins/commands/exec.cpp, libtenzir/include/tenzir/exec_pipeline.hpp
This change makes it so that the default implicit events sink properly respects the `--color=[always|never|auto]` command-line option of the `tenzir` binary and the [`NO_COLOR`](https://no-color.org) env variable.
=> Respect `--color` option in default implicit events sink

nix/tenzir/plugins/source.json
Starting a node with a custom CA cert for the platform would always result in a warning message 
```
ignoring unknown config field .cacert
```
even though the config field is, in fact, known.
=> Avoid 'unknown config option' warning for TLS-related platform settings

changelog/next/changes/5009--chart-null.md, libtenzir/builtins/operators/chart2.cpp, tenzir/tests/exec/chart/null_break.tql, tenzir/tests/exec/chart/resolution.tql
Additionally, this now fills gaps for all chart types.
=> Allow values to be `null` when charting

libtenzir/src/default_configuration.cpp
The `caf.middleman.enable-automatic-connections` option causes remote actors to attempt to form a mesh to avoid tunneling. For our upcoming execution node rewrite, setting this option makes the initial setup a lot easier as it allows us to spawn execution nodes centrally instead of having each execution node spawn the following execution node.
Additionally, this changes away from the default app identifier `generic-caf-app` to `tenzir`. App identifiers need to match when connecting to a remote actor.
This change is not user-observable with the current execution model, but will become very relevant once we support spanning pipelines across many nodes.
=> Enable automatic connections in CAF's middleman

changelog/next/features/4985--duration-abs.md, libtenzir/builtins/functions/abs.cpp, libtenzir/builtins/functions/duration.cpp, web/docs/tql2/functions.md, web/docs/tql2/functions/_count_duration.mdx, web/docs/tql2/functions/_duration.mdx, web/docs/tql2/functions/abs.md, web/docs/tql2/functions/count_days.mdx, web/docs/tql2/functions/count_hours.mdx, web/docs/tql2/functions/count_microseconds.mdx, web/docs/tql2/functions/count_milliseconds.mdx, web/docs/tql2/functions/count_minutes.mdx, web/docs/tql2/functions/count_months.mdx, web/docs/tql2/functions/count_nanoseconds.mdx, web/docs/tql2/functions/count_seconds.mdx, web/docs/tql2/functions/count_weeks.mdx, web/docs/tql2/functions/count_years.mdx, web/docs/tql2/functions/days.mdx, web/docs/tql2/functions/hours.mdx, web/docs/tql2/functions/microseconds.mdx, web/docs/tql2/functions/milliseconds.mdx, web/docs/tql2/functions/minutes.mdx, web/docs/tql2/functions/months.mdx, web/docs/tql2/functions/nanoseconds.mdx, web/docs/tql2/functions/seconds.mdx, web/docs/tql2/functions/slice.md, web/docs/tql2/functions/weeks.mdx, web/docs/tql2/functions/years.mdx
New functions `years`, `months`, `weeks`, `days`, `hours`, `minutes`, `seconds`,
`milliseconds`, `microseconds` and `nanoseconds` convert a numeric value to the
equivalent duration.
The `count_*` functions calculate how many units can the duration be broken
into, i.e. `duration / unit`.
=> Implement sub-duration functions

changelog/next/bug-fixes/5011--error-inside-if.md, libtenzir/src/tql2/exec.cpp
We previously assumed that the creation of the operator underlying the `if` statement cannot fail. However, this is not true at the moment (for example, there can be a conflict when one operator is local and the other is remote). This PR ensures that we handle the error properly. It also propagates the location of the `if` keyword such that this info can be used in diagnostics.
=> Fix compilation error handling inside `if`

changelog/next/bug-fixes/5014--subscribe-predicate-pushdown.md, nix/tenzir/plugins/source.json
This fixes a bug where pipelines of the form `subscribe <topic> | where <value> in <field>` had missing results. This happened because the `subscribe` operator did not normalize the pushed-up predicate from `where`, causing `<field> in <value>` to be evaluated instead.
=> Normalize pushed-up predicates in `subscribe`

nix/tenzir/default.nix
A previous refactoring of the Tenzir Nix packaging introduced a precedence error. `+` binds stronger than `else` in nixlang.
=> Fix darwin-static release builds

changelog/next/bug-fixes/5025--from-fluent-bit-hang.md, plugins/fluent-bit/include/fluent-bit/fluent-bit_operator.hpp
The `from_fluent_bit` operator reported its successful startup only after emitting its first event. This caused problems in the Tenzir Platform, which when deploying a pipeline waits until that pipeline has started to report success.
=> Fix startup delay in `from_fluent_bit`

changelog/next/bug-fixes/5027--to-splunk-tls.md, libtenzir/builtins/operators/to_opensearch.cpp, libtenzir/include/tenzir/curl.hpp, nix/tenzir/plugins/source.json
We previously asserted that setting the option _fails_. This makes it so that we assert that it _succeeds_.
Also moves a bunch of side-effects out of `TENZIR_ASSERT`.
=> Fix `tls` option of `to_splunk`

changelog/next/bug-fixes/5029--udo-resolution.md, tenzir/tenzir.cpp
A user reported that their user-defined operators failed to resolve entities. Usually, this error is supposed to only occur when users define circular dependencies in their user-defined operators, which they clearly did not.
I found this as a minimal reproduction:
```yaml
tenzir:
operators:
a: |
b
b: |
pass
```
What was curious was that this worked if I switched the names of the two user-defined operators:
```yaml
tenzir:
operators:
a: |
pass
b: |
a
```
Digging a bit deeper, it looked like we did the entity resolution in lexicographical order, as that is what we got from parsing the configuration file. That approach is obviously broken: Whether a user-defined operator is usable from another one should not depend on the names of the operators.
To fix this, I changed the resolution …
=> Make UDO resolution order-independent

changelog/next/features/5026--manual-pipeline-id.md, nix/tenzir/plugins/source.json, web/openapi/openapi.yaml
The web is a lossy place. If a request from the Tenzir Platform to deploy a pipeline does not get a response, we ideally want to retry it—but that could potentially have bad side effects like deploying a pipeline twice if sending the same request again can create a different state than the one we wanted to have. Ultimately, the platform cannot know if the node received a request when it did not get a response.
This changes the `/pipeline/create` and `/pipeline/launch` endpoints to optionally accept a new `id` parameter for manually assigning a pipeline id. That's far from a perfect fix as duplicate requests will still get responded to with an error, but it's the best we can do for now without majorly revisiting the code behind the `/pipeline` API.
=> Allow assigning ids for pipelines manually

changelog/next/bug-fixes/5031--package-ignore-additional-fields.md, libtenzir/src/package.cpp
We're looking to adding more fields to packages, in particular a `categories` field for categorization. While testing the changes from tenzir/library#69 I noticed that installation of packages fails for additional fields instead of warning and ignoring them.
=> Ignore additional fields in package config

.github/workflows/analysis.yaml, .github/workflows/bump-plugins-submodule.yaml, .github/workflows/docker-manual.yaml, .github/workflows/docker.yaml, .github/workflows/installer.yaml, .github/workflows/nix-manual.yaml, .github/workflows/tenzir.yaml, .github/workflows/update-sbom.yaml, .github/workflows/upload-cache-artifact.yaml, changelog/next/bug-fixes/5035--load-tcp-v20.md, libtenzir/builtins/operators/load_tcp.cpp
This fixes two bugs in `load_tcp`:
1. The operator forwarded empty batches, which causes unnecessary wakeups.
2. When the TCP connection was slower than the following pipeline, the operator both buffered the batches and forwarded them immediately, potentially duplicating the batches. This did not only produce broken data, but also made (1) a much worse problem.
=> Avoid idle wakeups in `load_tcp`

changelog/next/bug-fixes/5033--arrow-metadata-mismatch.md, libtenzir/include/tenzir/arrow_table_slice.hpp, libtenzir/include/tenzir/type.hpp, libtenzir/src/arrow_table_slice.cpp, libtenzir/src/table_slice.cpp, libtenzir/src/tql2/eval_impl.cpp, libtenzir/src/tql2/set.cpp, libtenzir/src/type.cpp
This fixes a crash in Debug builds (via `TENZIR_ASSERT_EXPENSIVE`) in the pipeline `from {} | x = this`, or, more generally speaking, any pipeline that involves an assignment on a field which has metadata.
The expensive assertion that fired here compared that Tenzir's and Arrow's metadata on Tenzir's types and Arrow's fields and schemas matches exactly. A performance optimization made in Tenzir Node v4.28 introduced this bug that under some circumstances caused a mismatch between the two.
The impact of this bug is luckily only small. Events persisted with `write_feather`, `write_parquet`, or `import` restore the metadata from Arrow when read. This implies a loss of metadata for nested fields with metadata persisted since the release of v4.28, but luckily the data is not in a broken state …
=> Fix mismatch in type metadata after assignments

changelog/next/bug-fixes/5037--fluent-bit-signed-int.md, libtenzir/include/tenzir/concept/printable/tenzir/data.hpp, libtenzir/include/tenzir/concept/printable/tenzir/view.hpp, libtenzir/test/cast.cpp, libtenzir/test/printable.cpp
This removes the leading plus for positive signed integers in `tenzir::data` when rendered as a string.
This came up as part of a bug search in the `from_fluent_bit` and `to_fluent_bit` operators, where `options={port: 9200}` got forwarded as `port=+9200` to Fluent Bit, and was then just ignored because of that pesky little plus character.
The reason for why this leading plus existed is long gone: `vast export ascii <predicate>` hasn't been a thing in years, and that relied on our internal data printer (and parser) for rendering, introducing a need to distinguish between signed and unsigned integers.
=> Change how signed ints are rendered in logs

changelog/next/bug-fixes/5039--large-cache-eviction.md, libtenzir/builtins/operators/cache.cpp
When a cache would grow beyond the byte size configured in `tenzir.cache.capacity`, a pipeline warning is emitted, and the cache operator no longer accepts new events. Offending events are discarded, meaning that the cache will have stopped just short of exceeding the limit.
Additionally, caches all report their sizes up to a central cache eviction service which periodically evicts older caches that cause the global limit to be exceeded.
However, currently the reported size of the a cache that "stopped just short" of exceeding the limit includes the size of the events that would've caused it to be exceeded, leading the eviction service to immediately evict the cache.
This PR makes it so the size of offending events isn't included in the size reported to the eviction service.
=> Fix cache eviction always happening on maximally large caches

Dockerfile
This should make our demo nodes run a bit smoother at the cost of making pipelines on them a bit slower.
=> Limit resource usage for demo nodes

changelog/next/bug-fixes/5042--cache-fix.md, libtenzir/builtins/operators/cache.cpp
This fixes an infinite hang in `<source> | head 0 | cache "<id>"`, which successfully created the cache, but then failed to shut it down. This happened because the pipeline writing into the cache lazily registered itself at the cache upon writing the first batch of events. The fix was to simply register beforehand.
=> Fix hang in `cache` when creating an empty cache

changelog/next/bug-fixes/5043--heterogeneous-evaluation-fix.md, libtenzir/src/multi_series.cpp, libtenzir/src/tql2/eval_impl.cpp
Tenzir's evaluator mostly deals with batches of uniformly typed data. However, some functions can return different types depending on the actual value of the input – for example, `parse_json`. Thus, there is some segmentation logic which deals with heterogeneous types and allows the rest of the evaluator to assume uniform types. This PR fixes a few issues within that code, and also contains a drive-by fix for the evaluation of record expressions.
=> Fix splitting logic for heterogeneous evaluation

libtenzir/include/tenzir/detail/scope_guard.hpp, tenzir/tenzir.cpp
We recently added exception catching for panics, but did not account for a `std::thread` that was not joined on unwind. This PR makes it so that we join the thread on unwind instead, preventing a `std::terminate`. There is no changelog because the panic machinery is only visible for bugs anyway.
=> Fix panic catching in `main()`

changelog/next/bug-fixes/5050--from-ndjson.md, libtenzir/builtins/operators/from_to_2.cpp
We previously checked parser eligibility by testing whether a file extension ends with a specific suffix. This test incorrectly asserted that only one parser can match an extension.
Unfortunately, the check was written in a way where it tested extensins without the leading dot, causing `.ndjson` files to both match the `ndjson` and `json` parsers.
=> Fix crash in `from "path/to/file.ndjson"`

changelog/next/bug-fixes/5052--zeek-tsv.md, libtenzir/builtins/formats/zeek_tsv.cpp
This fixes the following pipeline:
```
from "https://storage.googleapis.com/tenzir-datasets/M57/zeek-all.log.zst" {
decompress_zstd
read_zeek_tsv
}
where @name == "zeek.analyzer"
```
This returned one additional field with the name `\0`, which failed UTF8 validation, causing nodes to be disconnected from the platform when running this pipeline in the Explorer.
=> Fix bug that caused `read_zeek_tsv` to produce invalid fields

changelog/next/bug-fixes/5053--fluent-bit-strings.md, plugins/fluent-bit/include/fluent-bit/fluent-bit_operator.hpp
This fixes a recently added regression that causes strings to be forwarded with double quotes. A user reported this via Discord.
=> Fix passing string params to `{from,to}_fluent_bit`

changelog/next/changes/5024--pipeline-metrics.md, changelog/next/features/5024--pipeline-metrics.md, libtenzir/builtins/operators/export.cpp, libtenzir/include/tenzir/diagnostics.hpp, nix/tenzir/plugins/source.json, web/docs/tql2/operators/metrics.md
This PR adds `metrics "pipeline"` as an easier-to-understand version of the now deprecated `metrics "operator"`.
Operator metrics were very detailed. We simply generated too many of them, causing them to take away significant compute resources. Looking at how we utilize operator metrics in the Tenzir Platform, it became clear that we just need a small subset of the information that they provided. The new pipeline metrics are exactly that subset, showing the ingress and egress of every managed pipeline pre-aggregated in windows of ten seconds.
We will remove operator metrics once we have adapated the Tenzir Platform to make use of pipeline metrics instead.
=> Introduce `metrics "pipeline"`

Dockerfile
This allows the usage of the 'capsh' binary in our docker compose setups. The capsh binary in turn is currently the easiest way to manipulate ambient capabilities from the command line, which are required to allow the tenzir node to e.g. bind to privileged ports in host networking mode.
=> Add 'libcap2-bin' as runtime dependency to Dockerfile

.github/workflows/installer.yaml
Should fix the nightly installer CI test.
=> Drop tests for EOL ubuntu releases

changelog/next/features/5062--type-of.md, libtenzir/builtins/functions/misc.cpp, libtenzir/builtins/operators/measure.cpp, libtenzir/builtins/operators/serve.cpp, libtenzir/include/tenzir/type.hpp, libtenzir/src/type.cpp, libtenzir/src/version.cpp, web/docs/tql2/functions.md, web/docs/tql2/functions/type_id.md, web/docs/tql2/functions/type_of.md, web/openapi/openapi.yaml
The type definitions returned by `/serve` and `measure _definition=true` were tailor-made for the Explorer in the Tenzir Platform, and returned a simplified version of Tenzir's type system.
Planned changes to the Explorer require revisiting these simplifications, as the full schema definition is now required in the Tenzir Platform. To enable this in a backwards-compatible way, this PR makes three changes:
1. It introduces a new `type_of(x: any) -> record` function that returns the exact type definition of a TQL expression. For example, `this = type_of(this)` replaces an event with its exact schema definition.
2. It introduces a hidden option `_exact_definition=bool` to the `measure` operator, which always overrules the existing `_definition=bool?  option and causes the operator to return …
=> Make schema definitions represent the type system exactly

nix/tenzir/plugins/source.json
CI is broken on main as the CI job that updates the source.json file failed for some reason we have yet to investigate. This fixes it up manually.
=> Manually fix up the plugin sources

.github/workflows/bump-plugins-submodule.yaml
The generated app token we use by default in that workflow does not seem to be supported when connecting via regular http and curls netrc functionality.
=> Fix the bump-submdoule CI workflow

changelog/next/bug-fixes/5084--fix-fluent-bit-stacks.md, nix/fluent-bit/default.nix
This is larger then the page size of all currently supported platforms, with apple silicon being the biggest at 16K.
The specific value 24576 is coming from the fluent-bit configuration docs, claiming it to be the default value. The code must have gone out of sync from the docs, so we now set it explicitly.
This change fixes a segfault when the fluent-bit engine is rebatching large-ish events in its internal format. For example
plugins
repeat 1000
to_fluent_bit "http", fluent_bit_options={
host: "localhost",
format: "json_lines"
}
would reliably crash before this change.
=> Hardcode the fluent-bit page size to 24576

changelog/next/bug-fixes/5085--and-or-short-circuit.md, changelog/next/features/5085--inline-if-else.md, libtenzir/builtins/operators/from_to_2.cpp, libtenzir/include/tenzir/multi_series.hpp, libtenzir/include/tenzir/tql2/ast.hpp, libtenzir/include/tenzir/tql2/eval_impl.hpp, libtenzir/src/tql2/ast.cpp, libtenzir/src/tql2/eval_binary.cpp, libtenzir/src/tql2/eval_impl.cpp, libtenzir/src/tql2/parser.cpp, tenzir/bats/data/reference/expression/test_list_construction/step_00.ref, tenzir/tests/exec/binop/and.tql, tenzir/tests/exec/binop/and.txt, tenzir/tests/exec/binop/else.tql, tenzir/tests/exec/binop/else.txt, tenzir/tests/exec/binop/if.tql, tenzir/tests/exec/binop/if.txt, tenzir/tests/exec/binop/or.tql, tenzir/tests/exec/binop/or.txt, web/docs/tql2/language/expressions.md, web/docs/tql2/operators/metrics.md
This PR implements `if` and `else` expressions. They work just like the short-hand form in Python.
The rules are very simple:
- `value if true` => `value`
- `value if false` => `null`
- `value if null` => `null` and warning
- `value else fallback` => `value`
- `null else fallback` => `null`
These can be combined:
- `value if true else fallback` => `value`
- `value if false else fallback` => `fallback`
- `value if null else fallback` => `fallback` and warning
This is pretty useful. For example, `if … else` combines nicely with the new `metrics "pipeline"`:
```
metrics "pipeline"
summarize (
pipeline_id,
ingress=sum(ingress.bytes / ingress.duration.count_seconds() if not ingress.internal else 0.0),
from_node=sum(ingress.bytes / ingress.duration.count_seconds() if ingress.internal else 0.0), …
```
=> Implement `if … else` expressions and short-circuiting for `and` / `or`

tenzir.yaml.example
The platform plugin optionally reads its configuration from the global tenzir config, instead of its own plugin config.
Therefore, this PR documents these options in the global example config file.
=> Add global platform plugin options to example config

python/pyproject.toml, version.json
This commit was created with `/scripts/prepare-release`.
* Updated `/version.json` to `v4.31.1`.
* Moved all changelog entries from `/changelog/next` to `/changelog/v4.31.1`.
* Updated the python bindings version in `/python/pyproject.toml` to `v4.31.1`.
=> Prepare repository for Tenzir v4.31.1

changelog/next/bug-fixes/5091--data-builder-limit.md, libtenzir/include/tenzir/data_builder.hpp, libtenzir/src/data_builder.cpp
These arbitrary limits were put there during development to prevent unbounded memory consumption and retention by the `data_builder`, as its internal structure would be kept around (for both optimization and batching reasons) for the entirety of a pipeline.
With this change, the limit is gone, and instead the memory is released after every event, if it exceeded the size limit.
=> Remove 20k element limits from `data_builder`

libtenzir/include/tenzir/node.hpp, libtenzir/include/tenzir/spawn_node.hpp, libtenzir/src/node.cpp, libtenzir/src/spawn_node.cpp, tenzir.yaml.example
This removes the `tenzir.node-id` option that was dead code, and additionally addresses all clang-tidy warnings in all node-related files.
I didn't bother adding a changelog entry as this option was never documented in the first place outside of the example config file, and as far as I can tell it's been dead code for years.
=> Remove unused `tenzir.node-id`  option

changelog/next/bug-fixes/5100--check-json-array-validity.md, libtenzir/include/tenzir/json_parser.hpp
An oversight in the JSON parser caused it to try to enter incomplete arrays, causing segfaults with inputs as simple as
```
tenzir --tql2 'from {} | x = "[ ".parse_json()'
```
The change here adds the missing check.
=> Check array validity before iterating

changelog/next/bug-fixes/5103--save-tcp.md, libtenzir/builtins/connectors/tcp.cpp
It's not save to issue a request from instantiate from the legacy saver API and using exec-node state in the corresponding response hnadler.
This rewrites `save_tcp` with the operator API, which as a byproduct fixes this problem, as we can now properly yield control to the exec node after issuing the request.
=> Fix a stack-use-after-move in `save_tcp`

libtenzir/builtins/commands/exec.cpp, libtenzir/src/application.cpp
We discussed internally that we want to be a bit more lenient with the removal of the TQL2-only mode option. This adds the command-line flag `--tql2` back as a no-op.
=> Add back the `--tql2` option as a no-op

changelog/next/features/5119--diags-hidden.md, web/docs/tql2/operators/diagnostics.md, web/docs/tql2/operators/metrics.md
For an upcoming feature of the Tenzir Platform, we require the ability to get all diagnostics from all pipelines visible on the Pipelines page. This adds a `hidden` field to the output of the `diagnostics` operator that makes this possible.
=> Add a `hidden` field to `diagnostics`

docker-compose.yaml
This fixes the missing double-quotes in the `healthcheck` section of the `docker-compose.yaml` file, that utilized the `api` TQL command:
```
$ tenzir --connection-timeout=30s --connection-retry-delay=1s 'api /ping'
error: expected expression, got `/`
--> <input>:1:5
|
1 | api /ping
|     ^ got `/`
|
```
Now it works fine:
```
$ tenzir --connection-timeout=30s --connection-retry-delay=1s 'api "/ping"'
{
version: "5.0.0",
}
```
=> Fix healthcheck in docker-compose.yaml

.clang-tidy, changelog/next/bug-fixes/5133--fork-nested-pipeline.md, libtenzir/builtins/operators/fork.cpp
A user reported in Discord that `fork { context::update … }` failed with a panic. This fixes that problem.
=> Use a proper subpipeline for `fork`

libtenzir/src/series_builder.cpp, web/docs/tql2/functions.md, web/docs/tql2/functions/parse_kv.mdx, web/docs/tql2/operators.md
This PR fixes a few mistakes in the docs, such as `type_id` instead of `type_of` and bad links due to copy-paste.
It also contains some minor changes like aligning the capitalization of "syslog", "key-value pairs" and "zstd".
Finally, I removed a leftover debug logging statement that somehow ended up being merged into main.
=> Fix some minor things in docs and remove leftover debug log

changelog/next/features/5123--read_lines-split-regex.md, libtenzir/builtins/formats/lines.cpp, libtenzir/include/tenzir/split_at_regex.hpp, tenzir/tests/exec/operators/read_lines/split_at_regex.tql, tenzir/tests/exec/operators/read_lines/split_at_regex.txt, web/docs/tql2/operators/read_lines.md
This change enhances the `read_lines` operator with a `split_at_regex=<regex>` option. This is handy for input bytestreams that do not contain newlines or NULL bytes as a delimiter.
```
echo -n '<123>foo=bar <456>foo=baz x=y <999>x=z' | \
tenzir '
read_lines split_at_regex=" (?=<)"
message = line.parse_grok("<%{NONNEGINT:priority}>%{GREEDYDATA:kv_payload}")
'
```
=> Add a `split_at_regex` option to `read_lines`

libtenzir/include/tenzir/type.hpp, libtenzir/src/tql2/eval.cpp, libtenzir/src/tql2/eval_impl.cpp, libtenzir/src/type.cpp
This avoids calls to the rather expensive `record_type::fields()` function in favor of doing a direct field lookup.
=> Make field access faster

libtenzir/src/tql2/set.cpp
Consider this pipeline:
```
from {}
repeat 1k
batch
label = "head" if random().round() == 1 else "tails"
measure
select events
write_lines
```
After this change, this reliably prints `1000`. Before, it would print a series of numbers adding up to `1000`, as the recently added rebatching in the `set` operator only took place when the operator was allowed to reorder events.
=> Always rebatch in `set`

changelog/next/bug-fixes/5154--google-logging-nix.md, nix/tenzir/plugins/names.nix
=> Enable `to_gogle_cloud_logging` for the Nix builds

.clang-tidy, changelog/next/bug-fixes/5156--catalog-delay.md, libtenzir/include/tenzir/actors.hpp, libtenzir/include/tenzir/catalog.hpp, libtenzir/src/catalog.cpp, libtenzir/src/index.cpp
This fixes the `export`, `metrics`, `diagnostics` and `partitions` operators when used on startup before the catalog loaded its state. The operators now correctly wait until the catalog has initialized instead of returning no results.
=> Delay catalog lookups until catalog is ready

changelog/next/bug-fixes/5163--pm-shutdown.md, libtenzir/src/node.cpp
This fixes a rare race condition on shutdown that was observed by a user and reported via Discord. On shutdown, the pipeline manager component, which, as the name suggests, manages the lifetime of running pipelines in the node, needs to take special care that it is the instance that's shutting down pipelines, so that it knows not to update the pipelines' last known state to `stopped`, `completed`, or `failed`.
This change fixes a bug that could occur due to an indeterministic shutdown order, where if another component shut down first it could consequentially cause dependent pipelines to complete or fail. The pipeline manager would then record these new states before shutting down by itself, and the pipelines would not get restarted on startup.
The bug was pretty rare, and more likely to …
=> Always shut down the pipeline manager first

changelog/next/bug-fixes/5164--pid-file-empty.md, libtenzir/include/tenzir/detail/pid_file.hpp, libtenzir/src/detail/pid_file.cpp
During my many tests of for tenzir/tenzir#5163, I sometimes stopped the node after the `pid.lock` file was created but before it was written to, causing it to be empty. Afterwards, my node always refused to start up again until I manually deleted the `pid.lock` file.
This change makes it so that we warn the user about the incorrect shutdown, but still start up, overriding the file.
=> Do not refuse startup when `pid.lock` is invalid

libtenzir/builtins/functions/duration.cpp
Additionally, this emits a helpful warning that the user was likely looking for `count_seconds()` and friends, or did not need to call the function in the first place.
=> Make `seconds()` and friends no-ops on durations

libtenzir/include/tenzir/detail/base58.hpp, libtenzir/include/tenzir/ecc.hpp, libtenzir/src/detail/base58.cpp, libtenzir/src/ecc.cpp, libtenzir/test/detail/base58.cpp, libtenzir/test/ecc.cpp, tenzir/CMakeLists.txt
This PR adds two sets of data encoding/decoding functions:
* A base58 encoding to transform bytes into a URL-safe representation
* An elliptic curve public-key encryption to securely transmit arbitrary byte buffers
Since both the secrets and the static workspace config branches depend on these, they're split out into a separate PR here.
=> Add base58 and ECC cryptography primitives

changelog/next/bug-fixes/5183--zstd-compression-level.md, libtenzir/builtins/formats/feather.cpp
Support for this was apparently silently dropped at some point in the past, and nobody ever noticed. The option is documented in the example configuration file, and this makes it work again.
=> Do not ignore the `tenzir.zstd-compression-level` option

.github/workflows/nix.nu, flake.lock, flake.nix, libtenzir/CMakeLists.txt, libtenzir/src/detail/installdirs_relocatable.cpp.in, nix/overlay.nix, nix/tenzir/default.nix, nix/tenzir/image.nix, nix/tenzir/plugins/default.nix, nix/tenzir/plugins/source.nix, shell.nix, tenzir/bats/tests/vast_server.bats
This makes the nix-built non-slim docker image functionally equivalent with the Debian Trixie Dockerfile based image.
You can test it with
```
nix run .#tenzir.asImage.tenzir.copyToDockerDaemon
docker run tenzir/tenzir 'plugins | where kind == "dynamic" | this = {name: name} | write_lines'
```
=> Switch to nix2container for nix built docker images

changelog/next/bug-fixes/5204--to-hive.md, libtenzir/builtins/operators/to_hive.cpp
This operator was only partially converted by #5194, such that it still tried to use the `save` operator when pre-checking the validity of the given URL.
=> Fix URL check in `to_hive`

changelog/next/bug-fixes/5210--flatten-recursion.md, libtenzir/src/data.cpp
This was a nasty one: Every 101st field of objects when sorted alphabetically in configuration files was skipped.
=> Fix config parsing bug

changelog/next/bug-fixes/5219--cache-buffer-hang.md, libtenzir/src/execution_node.cpp
This fixes a regression introduced with the recent change to use `delay` over `run_delayed_weak` for the scheduler loop in the execution nodes.
Turns out that it is a bad idea to go delay -> schedule -> delay -> schedule -> … (ad infinitum) because that effectively bypasses CAF's limit for how many actions can run inline. This change breaks this loop.
=> Fix hang for operators with infinite idle timeout

libtenzir/CMakeLists.txt, libtenzir/builtins/connectors/email.cpp, libtenzir/builtins/connectors/udp.cpp, libtenzir/include/tenzir/variant_traits.hpp, libtenzir/test/variant_traits.cpp, plugins/azure-blob-storage/builtins/load_plugin.cpp, plugins/azure-blob-storage/builtins/save_plugin.cpp, plugins/gcs/include/operator.hpp, plugins/google-cloud-pubsub/builtins/load_plugin.cpp, plugins/google-cloud-pubsub/builtins/save_plugin.cpp, plugins/kafka/include/kafka/operator.hpp, plugins/nic/include/operator.hpp, plugins/s3/include/operator.hpp, plugins/sqs/include/operator.hpp, plugins/zmq/include/operator.hpp, web/docs/development/build-from-source.md
This PR
- Aligns our `{fmt}` requirements to 10.0.0. Fixes https://github.com/tenzir/issues/issues/2983
- Marks all connectors ported to dedicated operators as `detached`. Fixes https://github.com/tenzir/issues/issues/3043
- Improves failed variant access assertion message. Fixes https://github.com/tenzir/issues/issues/3052
=> Some backlog cleaning

changelog/releases/v5.3.1.yaml
Apparently GitHub silently removes inline code blocks in text inputs for `workflow_dispatch` actions.
=> Fix v5.3.1 release title

.github/workflows/tenzir.yaml
We yanked the 5.3.1 release, causing the regression test to no longer work. This simply filters the versions from the matrix.
- Fixes https://github.com/tenzir/issues/issues/3084
=> Disable regression tests for v5.3.0 & v5.3.1

changelog/changes/cN6XIKaqV5L5dK2pzedsJShuu8.md, libtenzir/include/tenzir/tql2/tokens.hpp, libtenzir/src/tql2/parser.cpp, libtenzir/src/tql2/tokens.cpp
Since we went for `@name` to access event metadata (instead of `meta.name`), the `meta` keyword should be removed.
=> Remove `meta` keyword

changelog/changes/cN6XIKaqV5L5dK2pzedsJShuu8.md, libtenzir/src/tql2/tokens.cpp
The lexer had two copies of the `meta` keyword, and #5275 only removed one.
=> Remove missed duplicate of `meta` keyword

changelog/changes/MSvVneBFHeY1Eny6ldFfUt6gdK.md
When there are no (non-hidden) pipelines, `pipeline::activity` rotated its internal buffers, but it did not notify subscribers that that the data changed.
=> Fix `pipeline::activity` refresh when there are no running pipelines

changelog/changes/credit-relax-origin.md, changelog/changes/insist-remain-worry.md, libtenzir/builtins/operators/http.cpp, nix/caf/source.json, nix/update-impl.sh
This change sets the correct domain for TLS SNI support and adds support for CGROUP core count limits by bumping to the latest commit on the CAF main branch.
=> Add SNI support to `from_http` and fix thread counts

docs/functions/print_cef.md, docs/functions/print_leef.md
This PR quickly fixes the "See Also" links in the docs for `print_cef` and `print_leef`.
- Fixes https://github.com/tenzir/issues/issues/3111
=> Fix links in the `print_cef` and `print_leef` docs

changelog/changes/token-welsh-thread.md, docs/operators/publish.md, libtenzir/builtins/operators/if.cpp, libtenzir/include/tenzir/group.hpp, libtenzir/include/tenzir/rebatch.hpp, libtenzir/src/tql2/set.cpp
This changes the `publish` operator to no longer expect its topic to be a constant. Instead, the topic can now be derived from each individual event.
As a small optimization on the side, this also removes the implicit `batch` operator before `publish`, moving a more efficient logic into the operator itself. The operator now also only emits metrics at most once every second per schema, and one additional time at the end of its input per schema if necessary. Previously, it emitted a metric for each batch of events.
=> Allow dynamic topics in `publish`

changelog/changes/Ezv8Vz2A1XgON7euQJjkNvrhQM.md, docs/operators/save_tcp.mdx, libtenzir/builtins/connectors/tcp.cpp, nix/update-impl.sh, tenzir/bats/data/reference/pipelines_local/test_parse_operators/step_14.ref, tenzir/bats/data/reference/pipelines_local/test_parse_operators/step_15.ref, tenzir/bats/data/reference/pipelines_local/test_parse_operators/step_19.ref, tenzir/tests/exec/operators/save_tcp/reconnect.tql, tenzir/tests/exec/operators/save_tcp/reconnect.txt, tenzir/tests/run.py
The `save_tcp` (`from "tcp://..."`) operator now tries to reconnect in case of recoverable errors such as network outages and in case the remote end disconnects.
You can use the new options `retry_delay: duration` and `max_retry_count: int` to tune the behavior to your needs. The default values are set to 30 seconds and 10 times respectively.
This PR also removes the TQL1 TCP connector plugin.
=> Make save_tcp reconnect on network outages

changelog/changes/centre-backed-agree.md, libtenzir/include/tenzir/index.hpp, libtenzir/src/index.cpp
The index actor keeps track of all currently running `partition_transformer`s and properly shuts them down.
- Fixes https://github.com/tenzir/issues/issues/3009
=> Properly handle `partition_transformer` shutdown

changelog/changes/poetry-almost-mobile.md, libtenzir/builtins/operators/http.cpp
Additionally, removes an incorrect `std::move()`.
=> Fix metadata series length in `from_http_server_operator`

.github/workflows/update-ocsf-schemas.yaml
The "actor" is always the person that last modified the workflow when using the `schedule` trigger. I don't like getting mentions for this.
=> Remove noise in `update-ocsf-schemas` CI workflow

changelog/changes/enable-steer-bases.md, libtenzir/builtins/operators/http.cpp
This PR makes it possible to have `void` output operators in parsing pipelines *iff* the parent pipelines is a `void` output.
=> Support void sinks in parsing pipelines

libtenzir/builtins/operators/ocsf.cpp
This make it so that enum lists are not mapped for now, which will be added as a feature at later point in time. 
Not released yet => no changelog.
=> Guard against enum lists in `ocsf::derive`

changelog/changes/center-carpet-useful.md, libtenzir/include/tenzir/defaults.hpp
We discovered issues with pipeline subprocesses with high-volume pipelines. This change disables the feature by default until the cause for this is found and resolved.
=> Disable pipeline subprocesses by default

changelog/changes/charge-father-comply.md, libtenzir/src/tql2/ast.cpp
Previously, queries such as `export | where this["foo.bar"] == 42` were not optimized with the storage engine.
=> Optimize `export | where …` with `this["foo.bar"]` fields

changelog/changes/should-never-ticket.md, libtenzir/builtins/formats/xsv.cpp, tenzir/tests/exec/functions/print/print_csv.tql, tenzir/tests/exec/functions/print/print_csv.txt
This fixes the incorrectly named `field_separator`
in the configured `print_*sv` functions.
If you want to `print_csv` with custom `field_sepator`s,
use `print_xsv` instead.
=> Fix incorrect name for `list_separator` option

changelog/changes/delete-topic-state.md, changelog/changes/plant-ending-center.md
We now support trailing slashes and custom source versions in the S3 URL for `to_amazon_security_lake`
See https://github.com/tenzir/tenzir-plugins/pull/426
=> Support custom source versions for `to_amazon_security_lake`

plugins/clickhouse/builtins/to_clickhouse.cpp, plugins/clickhouse/include/clickhouse/easy_client.hpp, plugins/clickhouse/src/easy_client.cpp
This keeps the connection to the ClickHouse server alive by pinning it
on a schedule.
- Fixes https://github.com/tenzir/issues/issues/3193
=> Keep alive connection in `to_clickhouse`

.gitmodules, changelog/changes/suffer-strain-floor.md, libtenzir/src/argument_parser2.cpp, nix/caf/source.json, nix/update-impl.sh, nix/update-plugins.sh, nix/update.sh
The updated CAF has a bug with the defaulting of HTTP ports, making it so that `from_http` always returns an error.
=> Fix `from_http` port error

docs/operators/from_file.md
This PR improves the docs by removing a no-longer-need caution aside.
=> Remove caution aside from `from_file`

changelog/changes/badge-server-street.md, libtenzir/builtins/operators/ocsf.cpp
Previously, the outgoing events were assigned names such as `_ocsf.v1_5_0.dns_activity` because we copied the metadata from our internal schema encoding instead.
=> Preserve metadata in `ocsf::derive` and `ocsf::trim`

libtenzir/CMakeLists.txt, libtenzir/include/tenzir/module.hpp, libtenzir/src/pattern.cpp, scripts/debian/build-arrow-package.sh, tenzir/tenzir.cpp
From Arrow 21 on the compute functions are shipped as a separate library, so we adjust the build scaffold and initialize the functions on startup.
=> Bump Docker image build to Arrow 21

changelog/changes/passed-shell-bottle.md, libtenzir/builtins/formats/syslog.cpp, libtenzir/include/tenzir/arrow_table_slice.hpp, libtenzir/include/tenzir/cast.hpp, libtenzir/src/cast.cpp, libtenzir/src/tql2/eval_impl.cpp
Our syslog parser now allows for a `.` character in the tag/app_name
field and a `-` for the process ID, which will be treated as `null`.
=> More lenient RFC 3164 Syslog parsing

changelog/changes/lumber-guess-leave.md, docs/operators/read_lines.md, libtenzir/builtins/formats/lines.cpp, tenzir/bats/data/reference/lines/test_parse_null_delimited_events/step_00.ref
The replacement is `read_delimited "\0"`.
=> Deprecate `read_lines split_at_null=true`

changelog/changes/screen-queen-strike.md, libtenzir/src/table_slice.cpp
This should fix any crashes based on issues with `transform_columns`
and also properly work nested types such as lists.
- Fixes https://github.com/tenzir/issues/issues/3017
=> Change `resolve_enumerations` to use new `replace`

changelog/changes/mount-booth-desert.md, libtenzir/src/from_file_base.cpp
The `from_file` operator emits a warning when using `remove=true` if the file could not be removed. When deleting the last file inside an S3 directory, we keep that directory around by inserting a zero-sized object. However, this failed when the necessary `PutObject` permissions were not granted, thus emitting a warning even though the file was removed successfully. For this specific case, we thus no longer emit a warning. Other issues during file deletion are still reported.
=> Ignore missing S3 `PutObject` permissions for `from_file remove=true`

libtenzir/include/tenzir/detail/weak_handle.hpp
Extracted from @tobim's https://github.com/tenzir/tenzir/pull/5451 because we would like to get this in earlier.
No changelog because I think this bug didn't manifest itself for anyone and it's hard to tell where it would.
=> Fix `weak_handle` behavior for `nullptr` actors

tenzir/tests/node/secrets/resolution_failure.tql, tenzir/tests/node/secrets/resolution_failure.txt
The platform plugin is disabled in the MacOS CI, which causes this test
to "fail" with a different error message.
=> Disable secret resolution failure test

flake.nix, nix/caf/default.nix, nix/empty-libgcc_eh/default.nix, nix/overlay.nix, nix/overrides/apache-orc.nix, nix/overrides/jemalloc.nix, nix/package.nix, nix/tenzir/default.nix, nix/tenzir/plugins/default.nix, nix/update.sh
This builds CAF and tenzir with clang instead of GCC.
Build with `nix build .#tenzir-static-clang`.
=> Add a clang based static binary variant

docs/operators/metrics.md, libtenzir/builtins/metrics/caf.cpp
This applies a similar fix to the message metrics to the actor metrics.
The per-actor counts can be shown with a pipeline like this:
```
let $resolution = 1min
let $range = 3h
let $start = now()
metrics "caf"
where timestamp > $start - $range
where system.has("running_actors_by_name")
this = {timestamp: timestamp, actors: system.running_actors_by_name}
unroll actors
this = {timestamp: timestamp, ...actors}
count = count/$resolution.count_seconds()
where count > 1/$resolution.count_seconds()
chart_area x=timestamp, position="stacked", y=sum(count), group=name else "N/A", resolution=$resolution, x_min=$start-$range
```
=> Fix CAF running actor metrics

libtenzir/src/package.cpp
This PR removes whitespace characters between the frontmatter and the TQL program definition.
=> Handle whitespace after pipeline frontmatter

libtenzir/CMakeLists.txt
When the bundled simdjson is used on purpose (for example, because the system-installed one has an incompatible version), then the include paths were set up in a way where the system headers were used even though we were linking against the bundled simdjson version.
=> Fix include order when using bundled simdjson
